### ISSUE TITLE
txnbuild: replace "required field" pointers with invalid defaults

### ISSUE THREAD

**Issue by ire-and-curses** [stellar/go#1029]
The use of pointers in `txnbuild` structs may be overloaded. We went down the path of making all the options in `SetOptions` pointers. This was because some of them had valid empty values (e.g. you are allowed to pass an empty string for `home domain`), so we needed to distinguish between that and a true "unset". And once we had some, it made sense for consistency to have them all (within that operation). It leads to broader API design questions though. For example, now that we have an `Asset` pointer here, should we have an Asset pointer in the other operation structs, for consistency? I can see arguments both ways.

@MonsieurNicolas said:
> The problem with overloading pointers is that pointers actually do mean something here as you point out @ire-and-curses : nil means an optional value that is not set. I wonder if some of those issues should just be fixed at the XDR generator layer: if the default for "Asset" (XLM) doesn't make sense it seems to violate one of go's principles to have "default values that make sense", so maybe we should default to something else like "uninitialized" and have people explicitly set those to XLM when needed, maybe that means at the low level that we may use pointers everywhere (to avoid default values) - and use some other wrapper for optional types (as opposed to just pointers).
NB: we have the same problem in the C++ generated code, where in most cases those default values are time bombs waiting to explode (and the code is supposed to set them to something else).

@tomquisel said:
> I agree with @MonsieurNicolas'  idea that the default value of `Asset` should be some invalid asset that causes an error if you every try to use it, rather than XLM.
That removes the need for a pointer, and the question of whether `Asset` should be a pointer everywhere it shows up

If we are in agreement, then this issue would be to provide dummy default values that would raise errors, wherever we believe values **must** be explicitly specified. Pointers would be reserved for optional values only.

@bartekn what do you think about this?

**Comment by bartekn** [comment]
> nil means an optional value that is not set

I think that I agree with this statement. In the context of operations, asset is never an optional field and that's true that `Asset{}` is XLM looks a little bit strange. I think this can be solved by something like:
```go
type AssetType xdr.AssetType

const (
	AssetTypeNative           AssetType = xdr.AssetTypeAssetTypeNative
	AssetTypeCreditAlphanum4  AssetType = xdr.AssetTypeAssetTypeCreditAlphanum4
	AssetTypeCreditAlphanum12 AssetType = xdr.AssetTypeAssetTypeCreditAlphanum12
)

type Asset interface {
	GetType() AssetType
}

type NativeAsset struct{}

func (n *NativeAsset) GetType() AssetType {
	return AssetTypeNative
}

type CreditAsset struct {
	Code   string
	Issuer string
}

func (n *CreditAsset) GetType() (AssetType, error) {
	switch {
	case len(n.Code) >= 1 && len(n.Code) <= 4:
		return AssetTypeCreditAlphanum4, nil
	case len(n.Code) >= 5 && len(n.Code) <= 12:
		return AssetTypeCreditAlphanum12, nil
	default:
		return AssetTypeCreditAlphanum4, errors.New("Invalid asset code")
	}
}
```
This way the default value for native and credit asset structs have a meaning but the value of `Asset` in payment operation struct can be `nil` to indicate that it's not set.

It's not in a scope of this issue but related. We should discuss pros and cons of: #51. Maybe it'll be better indeed to have a common asset structs that will be used by different packages.

**Comment by tomquisel** [comment]
@bartekn I like your proposal for the `Asset` type. Doesn't it allow us to make the `Asset` field of a payment operation not a pointer any more? A payment always has an asset, so why still allow a not-set asset in a payment?

**Comment by bartekn** [comment]
`Asset` is an interface in my example and it's kind of special in Go. Interface value is actually a pair: pointer to a type and pointer to associated data. We can say it's always a pointer but with a syntax of a value. Code example:
```go
// code from my previous comment here

type PaymentOperation struct {
    Destination string
    Amount string
    Asset Asset
}

func main() {
    nativePayment := PaymentOperation{
        Destination: "G...",
        Amount: "1.50",
        Asset: NativeAsset{},
    }

    creditPayment := PaymentOperation{
        Destination: "G...",
        Amount: "1.50",
        Asset: CreditAsset{Code: "USD", Issuer: "G..."},
    }

    noAssetPayment := PaymentOperation{
        Destination: "G...",
        Amount: "1.50",
        // when no asset, Asset = nil
    }
}
```
So by default `Asset` is `nil` but at the same time assets passed to `PaymentOperation` don't have to be pointers (but must implement `Asset` interface).

**Comment by tomquisel** [comment]
@bartekn gotcha, that sounds perfect to me.
