### ISSUE TITLE
gofmt varies across different CI builds

### ISSUE THREAD

**Issue by ire-and-curses** [stellar/go#1030]
Our Travis CI requires successful builds against Go 1.9, 1.10 and 1.11, and also builds against `tip`. As a precursor step, it enforces `gofmt`.

The implementation of `gofmt` varies between these versions of Go. It is thus possible to commit code formatted by one version of `gofmt` that is [rejected by other versions](https://github.com/golang/go/issues/22695#issuecomment-344483632). Code like this can never pass the build process as currently implemented.

Official recommendation from linked thread above:

  > Note that these kinds of minor changes like these are expected from time to time. In general, we recommend against building systems that are sensitive to the exact version of gofmt or go/printer being used. For example, a continuous integration test that fails if any code already checked into a repository is not “properly formatted” is inherently fragile and not recommended.

 > When multiple programs must agree about the exact details of go formatting, they should arrange to share a single point of truth by all invoking the same gofmt binary. For example, in the Go open source repository, we arrange for goimports and our Git pre-commit hook to agree about source code formatting by having both invoke the gofmt binary found in the current path.

 > Our position is don't write tests like that. Treat running gofmt over your source as best-effort during submit but not something to be reverified automatically after submit.

One solution, suggested by @tomquisel is: remove the CI check; add a [pre-commit hook](https://www.viget.com/articles/two-ways-to-share-git-hooks-with-your-team/) to `.githooks`; add a note to an appropriate developer `.md` doc. Here, developers may have different Go versions. If this turns out to cause thrashing, we can deal with it then. It would mean that some parts of the code base might be formatted slightly differently from others, depending on who makes changes.

Another solution, suggested by @MonsieurNicolas is: drop support for Go 1.9; Add a developer note to set the expectation that developers would use latest Go (1.12.x); in CI, only run `gofmt` for the expected developer version.

We need to decide on how to proceed and then implement ASAP to unblock breaking builds like [this one](https://travis-ci.org/stellar/go/builds/508624898).

**Comment by ire-and-curses** [comment]
PR to implement single Go version: #1035

We can add a note for preferred developer version to CONTRIBUTING once #1034 has landed.

Do we want to drop 1.9 and add 1.12? I've left the existing supported versions for now.

**Comment by tomquisel** [comment]
Since 1.12 is stable, it seems like we should CI against it. @bartekn @brahman81 any reason to continue supporting 1.9? If so, we should just keep them all.

**Comment by bartekn** [comment]
According to [Golang Release Policy](https://golang.org/doc/devel/release.html#policy):
> Each major Go release is supported until there are two newer major releases. For example, Go 1.5 was supported until the Go 1.7 release, and Go 1.6 was supported until the Go 1.8 release. We fix critical problems, including critical security problems, in supported releases as needed by issuing minor revisions (for example, Go 1.6.1, Go 1.6.2, and so on).

I guess we should support the latest 2 major releases. However, if 1.9 doesn't cause any problems other than with go fmt (that's already fixed in #1035) it would be great to leave it so we can still test our packages, like tx builder and clients, to ensure they work in 1.9. Don't have strong opinion about this though: 1.9 is pretty old.

**Comment by ire-and-curses** [comment]
I went ahead and added Go 1.12. I ran into some problems with `go vet`: raised #1038.
