### ISSUE TITLE
Should we decrease Friendbot from 10,000XLM to 1,000XLM?

### ISSUE THREAD

**Issue by vcarl** [stellar/go#1045]
[Friendbot](https://stellar.expert/explorer/testnet/account/GAIH3ULLFQ4DGSECF2AR555KZ4KNDGEKN4AFI4SU2M7B43MGK3QJZNSR) has been funding a lot more accounts lately, which has led to it draining very rapidly—about 1B XLM/week.

![Screen Shot 2019-03-22 at 12 03 51 PM](https://user-images.githubusercontent.com/1551487/54852809-58e1ba00-4cc4-11e9-898c-97952832a148.png)

Reasons to change it:

* Instant 10x decrease in the drain on Friendbot's reservoirs
* Testnet XLM has no value, so the amount sent is completely arbitrary
* With 100B XLM available on the Testnet per reset, there's the potential to run out if the rate of funded accounts picks up by another few multiples.

Reasons not to change it:

* There may be automated tests built around the assumption of having 10,000XLM to play with. Decreasing this could break tests.

**Comment by tomquisel** [comment]
We've gotten friendbot to a more reliable place, and I think we need to stick with 10k for backwards compatibility. closing this out.
