### ISSUE TITLE
Friendbot periodically runs out of XLM

### ISSUE THREAD

**Issue by vcarl** [stellar/go#1046]
One recurring problem is that the Friendbot runs out of Lumens to give away, blocking testnet users from creating new accounts. This is because Friendbot currently serves from an arbitrary account which is manually funded. There's a [separate issue](https://github.com/stellar/puppet-v4/issues/31) to better monitor the balance, but manual processes are prone to failure.

There are a couple of options to resolve this permanently.

* Friendbot could send funds directly from the source account with 100,000,000,000 XLM.
* Friendbot could be automatically topped up as its balance dips below a certain threshold.

Both of these equally solve the problem.

I'm not aware of specific risks with giving Friendbot the keys to the testnet kingdom. The worst case scenario is that somebody steals the secret key and makes off with the entire testnet balance, but a) it would just be vandalism, testnet assets have no value and b) that's a current risk as Friendbot has to be manually sent testnet XLM by an SDF employee.

Automatically topping up has more moving parts, as it would entail a server running somewhere and monitoring the account's balance. However this is a pretty trivial service to keep operating.

**Comment by bartekn** [comment]
Can we close this? We have proper alerting now.
