### ISSUE TITLE
Idea: publish official SDF dumps of Horizon DB to enable faster complete ingestion

### ISSUE THREAD

**Issue by tomquisel** [stellar/go#1061]
What: publish official SDF dumps of Horizon DB to enable faster complete ingestion
Who: Horizon admins who run `CATCHUP_COMPLETE` ingestion
Why: It can take up to a month to successfully run your own `CATCHUP_COMPLETE` ingestion depending on hardware and if not using parallelism. If admins can point their Horizon at an official DB dump, the Horizon needs to only catch up for the time since the dump, and should be ready in less than a day.

One argument I've heard against this approach is that it requires Horizon admins to trust the SDF dumps. I'd counter that this is true, but anyone who is worried can still run their own complete ingestion. Using the dump is only an optimization, not a requirement.

**Comment by ire-and-curses** [comment]
:+1: for this. How will we verify that the dumps we produce are accurate and be alerted if something is corrupt?

**Comment by mollykarcher** [comment]
https://github.com/orgs/stellar/projects/37/views/16
