### ISSUE TITLE
Write launch plan for new Go SDK

### ISSUE THREAD

**Issue by ire-and-curses** [stellar/go#1067]
We need a short document describing how we will proceed to deprecate the existing `build` and `horizon.Client` libraries, and point people to the new `txnbuild` and `horizonclient` libraries.

Points to consider:

* What's the best practice for deprecating a Go library?
* Should we move the code out of the `exp` directory?
* What should the overlap period be before the old code is retired?
* Which docs need to be updated to point to the new SDK?

**Comment by ire-and-curses** [comment]
Draft plan here: https://docs.google.com/document/d/1118x68ZFCS8Qys2JbkBHThnd78sP9kn5wUCr66h7uUQ/edit#

**Comment by theaeolianmachine** [comment]
Hey @ire-and-curses just so you know, that doc is only viewable internally — perhaps make it publicly visible, or put some of the plan in the issue or repo?

**Comment by ire-and-curses** [comment]
"Soft" release planned for 26 April:

Pre-release:
- [ ]  Deprecate existing horizon/client + build library
  - [ ]  Add `// Deprecated:` lines to package doc, major methods (golang wiki) (blog post) (stdlib example)
  - [ ] Update READMEs with DEPRECATED at the top
- [ ] Move code from /exp to top level
- [ ] Check online GoDocs are up to date and make sense
  - [ ] Update Go SDK entry in stellar developers site
  - [ ] Overview: https://www.stellar.org/developers/go/reference/index.html
  - [ ] Basic Examples: https://www.stellar.org/developers/go/reference/examples.html
  - [ ] Godoc (should point to client packages, not just to the whole repo)

Release:
- [ ] Set a version for new SDK
- [ ] Create release
- [ ] Try downloading/installing/using on testnet/using in prod
