### ISSUE TITLE
Bridge - Bad Sequence. Please, try again

### ISSUE THREAD

**Issue by minherc** [stellar/go#1108]
[https://stellar.stackexchange.com/questions/2368/bridge-bad-sequence-please-try-again](https://stellar.stackexchange.com/questions/2368/bridge-bad-sequence-please-try-again)

**Comment by tomquisel** [comment]
@minherc it looks like that question has been removed. Are you still having issues? I'm going to close this issue, but feel free to re-open if you are and add more details.
