### ISSUE TITLE
Expose history archive capabilities as a library from stellar-archivist

### ISSUE THREAD

**Issue by nikhilsaraf** [stellar/go#1120]
We want to expose the capabilities of interacting with the history archive as a library for external use. This capability is already available in [`stellar-archivist`](https://github.com/stellar/go/tree/master/tools/stellar-archivist).

The `Archive` struct, currently in the `archivist` package in the `internal` folder, is primarily what we wish to expose. We want the API to look like the portion of the image below marked in a red outline (bottom left of image). There are a lot of inter-dependencies between items in the `internal` package and the `Archive` struct, but the code for stellar-archivist is very well designed and in line with the proposed design in the image below.

Here is the approach that I propose for this refactor:
1. Rename the `internal` folder to `archivist` and fix import statements in `main.go`
2. Keep the `ArchiveBackend` interface in the `archivist` folder and package along with all its implementations
3. Un-export methods that expose the internals of specific implementations such as `MakeS3Backend`, `MakeFsBackend`, `MakeHttpBackend`, `MakeMockBackend`, and any other methods we deem unfit for exposure as the API for this library.
4. Possibly move the `main.go` into a new `cmd` folder as `cmd/stellar-archivist.go` to follow Golang convention, with a very small `main.go` file that calls `RootCmd.Execute()` in `cmd/stellar-archivist.go` ([example](https://github.com/stellar/kelp/blob/master/main.go))

---------

![Ingest imported](https://user-images.githubusercontent.com/1028334/55767764-15f74480-5a2f-11e9-8f42-184910f87b64.png)

**Comment by nikhilsaraf** [comment]
fyi @tomquisel @MonsieurNicolas @bartekn please let me know your thoughts on this proposal.

**Comment by tomquisel** [comment]
Looks good to me @nikhilsaraf!
