### ISSUE TITLE
Horizon: loadAccount slow after starting a stream

### ISSUE THREAD

**Issue by sgehrman** [stellar/go#1121]
Hey, just noticed this reproducible issue.  Let me know if this makes sense.

So, if I start a payment stream on an account, and then try to loadAccount to get the account info, that loadAccount is very very slow.  If I remove the stream call before loadAccount, it's very fast.  It seems starting the stream is preventing the loadAccount from returning right away.

Does this make sense?  I can investigate, but thought I would see if anyone had ideas first.

I set the reconnectTimeout to 60000 if that makes any difference.  Is setting this higher of any use? 

pseudo code:

// slow
stream()
loadAccount()   // take long time to get results

// fast
// stream()
loadAccount()   // now it's fast

```
loadAccount(publicKey) {
        return this.server().loadAccount(publicKey)
}

stream() {
    const stopper = builder.stream({
      reconnectTimeout: 60000,
      onmessage: txResponse => {
        console.log(txResponse)
      },
      onerror: error => {
           console.log(error, 'onerror')
       }
    })
}
```

**Comment by tomquisel** [comment]
@howardtw do you have any idea what this could be?

**Comment by tomquisel** [comment]
@sgehrman Thanks for the report! Your slow and fast examples look identical to me, could you revise them? Also, how slow are we talking for that second call to `loadAccount()`? It could just be the [browser restriction](https://docs.pushtechnology.com/cloud/latest/manual/html/designguide/solution/support/connection_limitations.html) on total number of open connections to a subdomain. It's hard to imagine it's happening on the server side now that I think about it more.

**Comment by sgehrman** [comment]
I'll do more experiments. Maybe it is the browser restriction. I have a page where I'm listening for transactions on a bunch of wallets at once.  That would make sense. Thanks for the response.

**Comment by sgehrman** [comment]
A related question.  if I need to monitor 10 accounts for payments.  Should I just stream every transaction and filter on my end?  I'm worried that the traffic from Horizon would be large, but if there is a browser restriction on connections, I guess I would have no choice?  I'm just trying to monitor if something on an account changes.  I really don't even need all the transaction info. I just need to know if something happened.  Is there a way to stream without getting all the data?  Maybe there should be an option to stream but only send some minimal 'ping' type message?  Let me know what you think.
