### ISSUE TITLE
Add HistoryArchiveAdapter to work with historyarchive package with test

### ISSUE THREAD

**Issue by nikhilsaraf** [stellar/go#1134]
Link to [ingestion design doc](https://github.com/stellar/go/blob/master/services/horizon/internal/docs/plans/new_horizon_ingest.md)
Link to [detailed structure of history archive files produced by Stellar-Core](https://github.com/stellar/stellar-core/blob/master/docs/history.md#detailed-structure-of-history-archives)
Link to [examples of stellar-archivist usage](https://github.com/stellar/go/tree/master/tools/stellar-archivist)
Link to [integration with other services doc](https://github.com/stellar/stellar-core/blob/master/docs/integration.md)

Expand the design to implement `HistoryArchiveAdapter` that works with `Archive` in the historyarchive project.

Add a test that validates a bucket using `HistoryArchiveAdapter` from a file in the filesystem using a filesystem backend.

- [x] implement `HistoryArchiveAdapter`
- [x] test with file system or S3 adapter
- [x] little tool to calculate stats for archives to prove usage. Tx/s over 5 min period.

This is the red portion in the image below:
![Ingest imported_history_archive_adapter](https://user-images.githubusercontent.com/1028334/56322080-eb874480-611c-11e9-8e71-b432a61c42c7.png)

pending review comment items:
- [ ] StateReadCloser: https://github.com/stellar/go/pull/1216#discussion_r284794230

**Comment by nikhilsaraf** [comment]
Here are some notes from our deep dive into history archive ledgers and buckets yesterday

1. GetState API should return a ledgerHeader object along with a StateReader.

2. StateReader.Read() should return “Dead”, “Alive”, or “Init” in addition to the xdr.LedgerEntry. Init only supported from protocol 11 onwards.

3. Buckets to be read in descending order, in the order of 9.snap, 9.curr, 8.snap, ..., 1.curr

4. Second implementation after MemoryStateReader can be a 18-way-merge reader which is similar to the merge step in merge sort, and outputs only a single entry per key which is always an “Init” entry. This should be a different API from StateReader to differentiate, since it would not have the incremental bucket-specific LedgerEntry values (ie no Alive and Dead entries).

5. TxSet, results, SCP do not need to be ingested right now since that will be used in the next stage when we have LedgerCloseData.

6. Testing — Unit Test that creates a bucket programmatically and verifies that the values read out from StateReader are correct. That is, it validates the read order and that the HistoryArchiveAdapter produces a StateReader that goes over all the required data from the HistoryArchive checkpoint file.

![IMG_4752](https://user-images.githubusercontent.com/1028334/57324001-cbafc480-70bb-11e9-9c9a-c8712aebf762.JPG)

**Comment by nikhilsaraf** [comment]
to move the conversation from email to here, copying @bartekn 's comments on above:

> 1. GetState API should return a ledgerHeader object along with a StateReader.

For the checkpoint ledger or for all the ledgers between previous and current checkpoint? This is data in `ledger` folder, correct?

> 2. StateReader.Read() should return “Dead”, “Alive”, or “Init” in addition to the xdr.LedgerEntry. Init only supported from protocol 11 onwards.
> 
> 3. Buckets to be read in descending order, in the order of 9.snap, 9.curr, 8.snap, ..., 1.curr
> 
> 4. Second implementation after MemoryStateReader can be a 18-way-merge reader which is similar to the merge step in merge sort, and outputs only a single entry per key which is always an “Init” entry. This should be a different API from StateReader to differentiate, since it would not have the incremental bucket-specific LedgerEntry values (ie no Alive and Dead entries).

I was thinking to keep StateReaders simple and always return raw data from buckets. Then if user doesn't need raw data they can use Processor provided by us that merges all the changes and returns flat data to the next item on the pipeline.

However, I'm wondering if there's any use case (other than tests) when users need raw bucket data instead of final state ("Init" entries only).

**Comment by nikhilsaraf** [comment]
> For the checkpoint ledger or for all the ledgers between previous and current checkpoint? This is data in ledger folder, correct?

Yes

---------
> I was thinking to keep StateReaders simple and always return raw data from buckets. Then if user doesn't need raw data they can use Processor provided by us that merges all the changes and returns flat data to the next item on the pipeline.
> 
> However, I'm wondering if there's any use case (other than tests) when users need raw bucket data instead of final state ("Init" entries only).

That's a good point. I think the question boils down to how much of the bucket architecture we want to expose to the end user of `HistoryArchiveAdapter`.

I'm of the opinion that we should abstract away the details of the bucket architecture. We can have a single StateReader API that outputs `dead`, `alive`, `init` entries. This API will also work for the 18-way-merge implementation which will only output `init` entries. If we want to expose more details of the archives in the future then it may require a different API and will probably have an entirely different use case too.

@MonsieurNicolas @tomquisel @ire-and-curses thoughts?

**Comment by MonsieurNicolas** [comment]
~~I think it's fine either way:
for the first version having a non optimal stream of changes coming from buckets is fine (ie, having entries getting created only to be updated or deleted in a different bucket).~~

I agree that we should try to avoid bleeding certain details of the bucket list deep into the pipeline.

For this to work, I think that we should try to expose this data with the same schema than the other "diffs":
* buckets contain things as [BucketEntry](https://github.com/stellar/stellar-core/blob/a4e9f1e320529cb9cfc2cecf4c1e3f2fd6437043/src/xdr/Stellar-ledger.x#L172)
* later stellar-core exposes meta with streams of [LedgerEntryChange](https://github.com/stellar/stellar-core/blob/a4e9f1e320529cb9cfc2cecf4c1e3f2fd6437043/src/xdr/Stellar-ledger.x#L284).
   * `STATE` was added to help Horizon ingest data (before we only provided new state, but Horizon in some cases needs the "previous state"), so the meta is now generated as a pair `(old "STATE", new state)` (for updates/deletes) and creates are just creates (there is no previous state)

The mapping looks like this:

| BucketEntry | LedgerEntryChange |
| ------------- | ---------------------- |
| LIVE             | CREATED or UPDATED | 
| DEAD          |  REMOVED |

Starting with protocol 11, `BucketEntry` (with INIT) has a better mapping:

| BucketEntry | LedgerEntryChange |
| ------------- | ---------------------- |
| INIT             | CREATED |
| LIVE             | UPDATED | 
| DEAD          |  REMOVED |

Now that I write this, it seems that trying to make the pre-protocol 11 work is going to be challenging.
You're going to need
* either a database of sorts as to emit the proper meta (you need the "previous" value), and it's the wrong place to keep state (we should only keep state in processors that manage "views" of the ledger).
* or implement something like 18-way merge (that provides the "previous value" for each entry)

The alternative (18-way merge) makes this problem irrelevant as what is going to be emitted will be "pure": only "CREATED" entries (no need to remember what the old value was), in addition to being more efficient.

**Comment by nikhilsaraf** [comment]
ok, I can update the implementation to be an 18-way-merge implementation.
I'd want to merge what I have so far into the master branch since it gives a reasonable output and has basic testing too.
I can then work on the 18-way merge as an improvement off the new master, modifying my [current implementation](https://github.com/stellar/go/pull/1216).
@MonsieurNicolas  does this sound good?

**Comment by MonsieurNicolas** [comment]
yes, sounds good!

**Comment by nikhilsaraf** [comment]
Closing, as I believe this is complete as off this commit: https://github.com/stellar/go/commit/bd2c1a55262bdfee0542ee5d333d0a92a6003df6

If not, then please feel free to reopen
