### ISSUE TITLE
Prevent address exhaustion attack

### ISSUE THREAD

**Issue by bartekn** [stellar/go#119]
_This is theoretical attack but should be discussed and at least mentioned in a README file._

[BIP-32](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki) allows generating up to 2,147,483,648 - 1 addresses using a single public master key. In theory, someone could send lots of requests and generates lots of unused addresses.

RPS | Exhausted in
-|-
100 | 248 days
1000 | 24 days
10000 | 59 hours

Possible solutions:
* Use `m / purpose' / coin_type'` [derivation path](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki#path-levels) and generate a new account when `address_index` level becomes exhausted.
* Rate limiting (implemented in bifrost?)
* Captcha (implemented in bifrost?)

**Comment by howardtw** [comment]
Closing because it's bifrost related
