### ISSUE TITLE
txnbuild: Deprecate default base fee

### ISSUE THREAD

**Issue by ire-and-curses** [stellar/go#1221]
`txnbuild` uses a default base fee of 100 stroops. As discussed in [#166](https://github.com/stellar/js-stellar-base/issues/166), it should become mandatory to provide one.

If it's not done soon, this will have to be a deprecation warning etc.

Would be great to add an example to the docs of how to get dynamic fee suggestions from the client when this is done.

**Comment by poliha** [comment]
closed in #1443
