### ISSUE TITLE
"internal" package are not importable

### ISSUE THREAD

**Issue by alpe** [stellar/go#126]
Horizon is now almost completely under the "internal" package. With this package you locked out any projects using horizon as lib. Which may be the intention but I wanted to highlight this as a breaking change to the original setup.
See:
https://docs.google.com/document/d/1e8kOo3r51b2BWtTs_1uADIA5djfXhPT36s6eHVRIvaU/edit

**Comment by jedmccaleb** [comment]
What parts are you wanting to import?

**Comment by alpe** [comment]
NP, I don't need to import horizon packages. I was more concerned about effect to the community but I should have checked sourcegraph before: [![Sourcegraph](https://sourcegraph.com/github.com/stellar/horizon/-/badge.svg)](https://sourcegraph.com/github.com/stellar/horizon?badge)
