### ISSUE TITLE
Error getting auth data by request ID: get failed: get failed: pq: relation \"auth_data\" does not exist

### ISSUE THREAD

**Issue by Cheny-chen** [stellar/go#1270]
I follow the [api reference](https://www.stellar.org/developers/guides/anchor/4-compliance-server.html).

The **extra_memo: 'Test transaction'** is in the form.  Then, I got the error message **"Error getting auth data by request ID: get failed: get failed: pq: relation \"auth_data\" does not exist"**.

When I check compliance database, auth_data table is empty.  

What should I do?

```
request.post({
  url: 'http://localhost:8001/payment',
  form: {
    id: 'unique_payment_id',
    amount: '1',
    asset_code: 'USD',
    asset_issuer: 'GAIUIQNMSXTTR4TGZETSQCGBTIF32G2L5P4AML4LFTMTHKM44UHIN6XQ',
    destination: 'amy*your_org.com',
    source: 'SAV75E2NK7Q5JZZLBBBNUPCIAKABN64HNHMDLD62SZWM6EBJ4R7CUNTZ',
    sender: 'tunde_adebayo*your_org.com',
    // `extra_memo` is required for compliance (use it instead of `memo`)
    extra_memo: 'Test transaction',
  }
}, function(error, response, body) {
......
});
```

**Comment by bartekn** [comment]
Bridge server has been deprecated and removed.
