### ISSUE TITLE
ci: Ensure CircleCI only builds artifacts for releases that actually need artifacts

### ISSUE THREAD

**Issue by accordeiro** [stellar/go#1304]
The script on `scripts/build_release_artifacts/main.go` currently builds and uploads artifacts for all tagged commits that match a certain pattern. However, some projects like the Go SDK don't really have artifacts (the code itself is the release).

We should adapt the CI config so that CircleCI doesn't try to build artifacts for artifact-less projects in the monorepo.

**Comment by ire-and-curses** [comment]
Example: [PR](https://github.com/stellar/go/pull/1303); [Circle log](https://circleci.com/gh/stellar/go/349?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

**Comment by accordeiro** [comment]
@ire-and-curses I've been thinking of a way to solve this, but wanted to check with you before moving forward:

When a new tag in the format `<package>-v<X.X.X>` is created, the script should:
1. Try to find the corresponding package directory
2. If it finds it, it looks for a `main.go` at the top level. If it doesn't find one, `return 0`.
3. Inspect the `main.go` and look for a `main()` function. If it doesn't find one, `return 0`.
4. If there is a `main()` function, there are likely some binary artifacts to be built, so it runs the artifact building script. If the script succeeds, `return 0`, otherwise return the error.

What do you think?

**Comment by bartekn** [comment]
I think it's too complicated. W should probably just use regexp to extract package name from a tag (`<package>-v<X.X.X>`) and create an array of packages that `build_release_artifacts` ignores.

**Comment by ire-and-curses** [comment]
I think it's cool, but maybe a bit complex? Another approach might be to use the presence of a .file to indicate that building binaries should occur.
