### ISSUE TITLE
Add unit and race condition tests for ingest components

### ISSUE THREAD

**Issue by bartekn** [stellar/go#1343]
Identify the most critical components of the new ingestion system (and new ingestion package in Horizon) and aim for 90%+ (?) test coverage.

Ideally, we should also update GH and Circle to fail the PR if coverage of selected packages goes below 90%.

**Comment by ire-and-curses** [comment]
What are the critical components that we're aiming to cover? Trying to understand how much work there is here.

**Comment by bartekn** [comment]
I think we should have really good coverage for (including subpackages):
* `exp/ingest`
* `exp/support/pipeline`
* `services/horizon/internal/expingest`

We've been working on this for some time. Example PRs: #1757, #1607.

**Comment by bartekn** [comment]
Coverage results as of d6ecdda839c45382fb68bddf5cbaf18affe60ac5:
* `/expingest/fake_ledger_backend.go` 0.0%
* `/expingest/fsm.go` 89.7%
* `/expingest/group_processors.go` 0.0%
* `/expingest/logging_change_reader.go` 86.7%
* `/expingest/main.go` 61.2%
* `/expingest/mock_orderbook_graph.go` 77.8%
* `/expingest/processors/account_data_processor.go` 76.1%
* `/expingest/processors/accounts_processor.go` 68.4%
* `/expingest/processors/asset_stats_processor.go` 80.6%
* `/expingest/processors/asset_stats_set.go` 92.3%
* `/expingest/processors/effects_processor.go` 87.3%
* `/expingest/processors/ledgers_processor.go` 100.0%
* `/expingest/processors/new_orderbook_processor.go` 80.0%
* `/expingest/processors/offers_processor.go` 83.3%
* `/expingest/processors/operations_processor.go` 94.9%
* `/expingest/processors/participants_processor.go` 80.5%
* `/expingest/processors/signers_processor.go` 79.6%
* `/expingest/processors/trades_processor.go` 95.7%
* `/expingest/processors/transactions_processor.go` 100.0%
* `/expingest/processors/trust_lines_processor.go` 77.5%
* `/expingest/processors_runner.go` 0.0%
* `/expingest/verify.go` 7.5%

Going to create separate issues now.
