### ISSUE TITLE
Release is overwritten by CircleCI

### ISSUE THREAD

**Issue by bartekn** [stellar/go#1348]
I've just released [Horizon 0.18.0 rc1](https://github.com/stellar/go/releases/tag/horizon-v0.18.0rc1) and noticed that CircleCI overwritten the release (removed the old release and created a new release with a different title, description and author). Can we change the configuration to just publish binaries to an existing release?

Assigning to @accordeiro as he was working on this. CC: @tomquisel.

**Comment by accordeiro** [comment]
Sure, @bartekn – I'll ping you offline to get a better understanding of what we should change.
