### ISSUE TITLE
Spec out lightning integration 

### ISSUE THREAD

**Issue by tomerweller** [stellar/go#135]
Lightning is coming to stellar-core. This is a placeholder issue for specing out the platform side of it. 
Once we figure out the different components, we can create more specific issues. 

It seems like the major components on the platform side will be:
- [ ] Horizon support
- [ ] Client SDKs support
- [ ] A Demo app

**Comment by howardtw** [comment]
What's the status of this one @tomerweller ? Has the development of this been taken over by Interstellar?

**Comment by tomerweller** [comment]
Very outdated issue. closing.
