### ISSUE TITLE
What if China blocked horizon.stellar.org

### ISSUE THREAD

**Issue by immartian** [stellar/go#1379]
The horizon server is hardcoded in this SDK which is very risky to be attacked by censored countries, like China. https://github.com/stellar/go/blame/d3dc3be65d9af93660ef4aa5de1e53f0c24bc38d/clients/horizon/client_test.go#L21

Of course, it's possible to change horizon server to another one but it won't be easy for users who had a previous version when the blockage happened, and there's no way to switch to another one easily from the client side. 

A censorship-proof solution should be considered in this big context.

**Comment by bartekn** [comment]
You can easily change this to any other server. Default servers are there so users can quickly start building and testing new apps. In production you should use your own Horizon server instead of the servers provided by SDF.

**Comment by immartian** [comment]
Surely you can use another server in a real scenario, but the censorship system can easily block any dedicated server if it's been found functioning. I guess my question is how to prevent from such kind of single point failure if it's horizon.stellar.org, or whatever.
