### ISSUE TITLE
add failed operation count to ledger resource

### ISSUE THREAD

**Issue by tomerweller** [stellar/go#1385]
The ledger resource currently reports `operation_count` which represents the number of successful applied in the ledger.

With protocol 11 changes it's difficult to asses the used capacity of a transaction set without a failed operation count.  

I suggest deprecating `operation_count` and introducing `successful_operation_count` and `failed_operation_count`.

Note: failed operations might be semantically confusing. An operation result can be successful, but if it's within a failed transaction, the operation is not applied and therefore it has in fact failed. I don't think that's a sufficient reason not to introduce the failed operations metric, but it's important to document accordingly.

**Comment by bartekn** [comment]
The name can be confusing, indeed. Maybe we should call it: `successful_transaction_operation_count` and `failed_transaction_operation_count`?

**Comment by tomerweller** [comment]
@bartekn that sounds even more confusing to me :) 
Maybe failure is a strong word. How about `applied_operations_count` and `not_applied_operations_count` ?

**Comment by ire-and-curses** [comment]
+1 for "applied"

**Comment by bartekn** [comment]
I think `applied` is also confusing because of stellar-core transaction [life cycle](https://www.stellar.org/developers/guides/concepts/transactions.html#life-cycle) terminology: 
> Once SCP agrees on a particular transaction set, that set is applied to the ledger.

But maybe it's because I've been working with stellar-core related code recently?

What do you think about: `operation_count_in_successful_transactions` and `operation_count_in_failed_transactions`? 😉

**Comment by tomerweller** [comment]
That's a lot of words @bartekn, though passable. Going to throw one last proposal in the mix. 
I'm rethinking the capacity motivation and to measure that what we actually need is just the number of operations in the txset. So maybe add a `txset_operation_count` and leave the current `operation_count` as is is?

**Comment by bartekn** [comment]
Sounds good to me. I added it to Horizon 0.18.1 milestone so we should probably start working on this to be able to release it in this sprint.

**Comment by abuiles** [comment]
Fixed in #2690 - this will be in the next horizon release.
