### ISSUE TITLE
bifrost: queue deduplication assumption

### ISSUE THREAD

**Issue by alpe** [stellar/go#139]
I just run into this although it's WIP.
Queue systems do `at-least-once` or `at-most-once` delivery. At-most-once won't be an option as you can loose transactions so any consumer needs to handle duplicated by design. Even [SQS](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/standard-queues.html) does so. You can relax the constraints on 
https://github.com/stellar/go/blob/a6b43e22c8d0a731587e1bde1defb1038b0d7752/services/bifrost/queue/main.go#L27
but add deduplication handling to the consumers.

**Comment by bartekn** [comment]
The next comment line after the one you copied here mentions [AWS SQS FIFO](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/FIFO-queues.html) queues which implement this requirement:
https://github.com/stellar/go/blob/a6b43e22c8d0a731587e1bde1defb1038b0d7752/services/bifrost/queue/main.go#L28
But for 99% of Bifrost deployments using default database queue implementation is sufficient.

**Comment by alpe** [comment]
Apologies. I wasn't aware that `FIFO` is a special product in the SQS family. It wasn't available when I used it last time. Anyway, I think bifrost is a very cool product. It's just hard to contribute.

**Comment by bartekn** [comment]
> Apologies. I wasn't aware that FIFO is a special product in the SQS family. It wasn't available when I used it last time. Anyway, I think bifrost is a very cool product.

Thanks!

> It's just hard to contribute.

Why?
