### ISSUE TITLE
horizonclient: AccountDetail should receive a string.

### ISSUE THREAD

**Issue by poliha** [stellar/go#1391]
currently when a user tries to get the deails of an account from horizon, they need to pass an `AccountRequest{AccountID, DataKey}` struct. We only really need the `AccountID` which is a string and not the struct. 
Changing this now will be a breaking change, so for now we can re-introduce the `LoadAccount(AccountID string)` method which is present in other SDKs. This wil be responsible for getting the details of an account from horizon, with just the `AccountID` as a parameter.

**Comment by ire-and-curses** [comment]
Could you link to the code in question?

**Comment by poliha** [comment]
@ire-and-curses  this is an example of the current usage [here](https://github.com/stellar/go/blob/master/clients/horizonclient/main_test.go#L19L31) 
```golang
...
accountRequest := AccountRequest{AccountID: "GCLWGQPMK..."}
account, err := client.AccountDetail(accountRequest)
```
What I am suggesting is 
```golang
...
account, err := client.LoadAccount("GCLWGQPMK...")
```

**Comment by ire-and-curses** [comment]
Thanks for the link. I guess I'm wondering what problem this solves? In the example you gave, it's true that you only need part of the struct. On the other hand it doesn't seem difficult to provide the struct with the `DataKey` not set,as you do in your example. Could you expand on what you're concerned about with the current interface?

**Comment by bartekn** [comment]
I think I suggested this change. Basically, it's for consistency: https://github.com/stellar/go/pull/1314#discussion_r286480768. We should decide one way or the other.

**Comment by ire-and-curses** [comment]
Ok, I agree about the consistency problem. I'm not sure that this suggestion resolves that though? After this is implemented, the existing API will still be inconsistent, but we'll have a second way (with a different sounding name) that is similar but slightly different, which doesn't seem great to me.

I appreciate the desire to avoid a breaking change, but I'm not sure there's a way round that. Maybe we can just change the function signature on a major release branch and accumulate a few more before releasing? It doesn't seem too urgent.

**Comment by poliha** [comment]
Yes I agree that is not difficult to provide the struct without `DataKey`. The focus here is really for consistency. The plan was to introduce the new method now and deprecate `AccountDetail` in the next major release.

**Comment by abuiles** [comment]
I think this is fine as it is for now, we can revisit in the future.
