### ISSUE TITLE
discuss need for asset_type in API as well as other layers

### ISSUE THREAD

**Issue by nikhilsaraf** [stellar/go#142]
This can be easily inferred from the `asset_code`. we decided to leave it off for the "all assets" endpoint since it's redundant. See the order_book endpoint which requires it. We should consider where all it is redundant and where we can simplify this data representation.

Note that in some cases we are using upto 64 bytes to save the `asset_type` in the db (see `history_trades` and `history_assets`). `xdr.Asset` uses an `int32` (4 bytes) to represent the `asset_type`. Since we only need 2 bits, we should upgrade these to use a `char` data type (1-byte; min storage type I could find in postgres).

Also note that the overhead of storing a row in postgres is [23 bytes](https://stackoverflow.com/a/2966655) which is much greater than the 4 bytes we are currently saving for 4-character codes, (but 12-character codes are now 4-bytes longer because of the int32 asset_type).

My vote is for eliminating the concept and storing a `[12]byte` always for `asset_code`.

**Comment by tomerweller** [comment]
Yes. Mostly, it makes the Horizon API quite cumbersome, for no apparent reason.

**Comment by jedmccaleb** [comment]
Want to keep for future compatibility
