### ISSUE TITLE
exp/ingest: Closer suffix might not be necessary

### ISSUE THREAD

**Issue by tamirms** [stellar/go#1432]
A lot of interfaces and structs in the ingest package have a naming convention where the names are suffixed with "Closer." e.g. `StateReadCloser` , `StateWriteCloser`, `bufferedStateReadWriteCloser`

Is it necessary to include the `Closer` suffix? it seems like all of the interfaces and structs implement the `Close` function. In other words, there is never a reader or writer which is not a closer so we might as well just shorten the names to `StateReader` , `StateWriter`, `bufferedStateReadWriter`, etc.

I'm aware that in the golang standard library there is https://golang.org/pkg/io/#ReadCloser https://golang.org/pkg/io/#WriteCloser . However, in that context it makes sense because `ReadCloser` is a composition of both the `Reader` and `Closer` interfaces. There are concrete types which implement just `Reader` and other concrete types which implement `ReadCloser` which creates the need for two distinct interfaces.

Also, in the golang standard library most of the concrete types which implement the `ReadCloser` or `WriteCloser` interface do not have the `Closer` suffix. For example, https://golang.org/pkg/io/#PipeReader and https://golang.org/pkg/io/#PipeWriter . So, if it is necessary to have both a `Reader` and a `ReadCloser` interface in the ingest package, then I would recommend that the `Closer` suffix only be present in the interface names and not in the names of the concrete types which implement the interfaces

**Comment by ire-and-curses** [comment]
I think this might be an artifact of the way the design has evolved. Some of the `Close` methods were not present in the original design, but have been added during implementation as we realised their necessity. 

I think I agree with both points, and wonder whether we could just drop `Closer` everywhere.
