### ISSUE TITLE
exp/ingest: avoid sync.once when a constructor would suffice

### ISSUE THREAD

**Issue by tamirms** [stellar/go#1433]
`sync.Once` is used a lot to initialize various structs. It seems more conventional to have a constructor function which initializes a struct (and potentially return an error as well).

I think it is cleaner to explicitly initialize a struct rather than have the struct be implicitly initialized via `sync.Once` whenever a method is invoked on the struct

**Comment by ire-and-curses** [comment]
Is there guidance somewhere preferring one over the other?

**Comment by tamirms** [comment]
I couldn't find a discussion about when to use `sync.Once` and when to use a constructor but I think that the most common use case for `sync.Once` is to implement singletons or to cache one time operations:

http://marcio.io/2015/07/singleton-pattern-in-go/
https://golangcode.com/run-code-once-with-sync/

**Comment by ire-and-curses** [comment]
When I was implementing it I read this in the [package docs](https://golang.org/pkg/sync/#Once):

`Do is intended for initialization that must be run exactly once.`

**Comment by tamirms** [comment]
`sync.Once` is flexible enough to do the work of a constructor in many cases but I think using `sync.Once` for that use case is a bit overkill. My reasons for that opinion are:

* you need to remember to invoke `sync.Once.Do()` at the beginning of every member function of the struct. If the initialization function can return an error then that error needs to be bubbled up in each of the member functions as well. that adds boiler plate to each of the member functions. 

* initializing structs implicitly using `sync.Once` doesn't allow me to handle initialization errors in isolation. there could be cases where I'd prefer to handle initialization errors right away after creating the struct via a constructor.

* there's also the synchronization overhead of checking whether initialization is complete every time you invoke a member function of the struct. admittedly, this overhead is pretty small so this point is pretty minor

From what I understand the argument for using `sync.Once` instead of a constructor is that it is possible to declare a struct without calling the constructor function and then when you invoke one of the member functions that would result in bad behavior because the struct is not initialized. However, I feel that this is a non issue because creating structs via constructors is a common pattern in go code

**Comment by bartekn** [comment]
My only concern was that developers can create objects directly (without constructor) and would end with uninitialized object. This could be especially harmful in situations where object that wasn't initialized correctly may return invalid results (https://github.com/stellar/go/pull/1456#discussion_r300112550).

I think there's a solution that would prevent this. It looks like you can create private struct but make the fields public, ex:
```go
type pipeline {
  // some fields
}

func NewPipeline() pipeline {
  // init code
}

func (p *pipeline) Process() error {
  // processing code 
}

```
I need to run some tests, ex. I'm not sure how it's rendered in godoc, if you can use the private type in other packages (ex. you want to pass pipeline to session - maybe `interface` could help), or if you can embed the type. But if all works, it could be a solution.

**Comment by tamirms** [comment]
it's better to not return unexported types. The go linter treats that as a warning https://github.com/golang/lint/issues/210

the suggested alternative is to return an interface instead of an unexported type.

However, I think the presence of a constructor  and the fact that all the struct fields are unexported makes it obvious that you should not create a struct instance without the constructor. There is a precedence in lots of go code for having constructors initialize structs, see https://golang.org/doc/effective_go.html#composite_literals

**Comment by bartekn** [comment]
> the suggested alternative is to return an interface instead of an unexported type.

Makes sense, I mentioned it in the previous comment.

> However, I think the presence of a constructor and the fact that all the struct fields are unexported makes it obvious that you should not create a struct instance without the constructor.

It's not so obvious. For example, you can use constructor OR composite literal to create `bytes.Buffer` and both ways are perfectly fine. And `Buffer` has no exported fields.

> However, I think the presence of a constructor and the fact that all the struct fields are unexported makes it obvious that you should not create a struct instance without the constructor. There is a precedence in lots of go code for having constructors initialize structs, see https://golang.org/doc/effective_go.html#composite_literals

I think I agree except situations where "misusing" an object (instantiating it using composite literal except using a constructor) can have dangerous implications, like producing a different result (pre-hook example I linked above). I worry that we won't always remember to check what can happen when user creates an object not the way we wanted.

What do you think about this: We default to using constructors but constructors return interface types (implemented by private structs). We can export the concrete type but only after carefully checking if instantiating not via constructor is safe (i.e. in the worst case the code will error or panic instead of producing invalid results or behaviour).

**Comment by tamirms** [comment]
@bartekn sounds good to me!

**Comment by bartekn** [comment]
I checked `ingest` package. We don't use `sync.Once` anymore for inits.
