### ISSUE TITLE
Implement DatabaseStateReader

### ISSUE THREAD

**Issue by bartekn** [stellar/go#1457]
`MemoryStateReader` still requires a lot of memory. Maybe we should implement `DatabaseStateReader` that saves temp structures to disk? It will be slower that `MemoryStateReader` but won't require much memory.

**Comment by ire-and-curses** [comment]
Update: the implementation so far (#1539) works but is pretty slow. We'll look at stellar-core's similar implementation for guidance to see if it can be improved.

**Comment by bartekn** [comment]
I checked stellar-core's code and there's a quite complicated [data structure](https://github.com/stellar/stellar-core/blob/master/src/ledger/LedgerTxn.h) that makes it really fast. To be honest, I don't understand it well yet (besides LRU caching). I implemented simple cache with dumping random part of cache to a DB when cache limit is reached. I'm currently testing the performance and will provide results later today. It's definitely faster than the current implementation in #1539 but will check if it's fast _enough_.
