### ISSUE TITLE
Test network is Failed to fund new wallet

### ISSUE THREAD

**Issue by gluk73** [stellar/go#1464]
Test network is Failed to fund new wallet.

{
  "type": "https://stellar.org/horizon-errors/server_error",
  "title": "Internal Server Error",
  "status": 500,
  "detail": "An error occurred while processing this request.  This is usually due to a bug within the server software.  Trying this request again may succeed if the bug is transient, otherwise please report this issue to the issue tracker at: https://github.com/stellar/go/issues. Please include this response in your issue."
}
![stellar failure](https://user-images.githubusercontent.com/52410852/60434919-eeb8a980-9c10-11e9-84fc-d4d9f5439c34.JPG)

**Comment by bartekn** [comment]
Fixed.

**Comment by ire-and-curses** [comment]
@bartekn what was the problem?

**Comment by bartekn** [comment]
Friendbot run out of test lumens.
