### ISSUE TITLE
Make sure fee and ledger upgrade changes are processed

### ISSUE THREAD

**Issue by bartekn** [stellar/go#1470]
Meta changes are stored in 3 places:
* fee meta,
* transaction (tx and ops) meta,
* upgrades.

We need to ensure users follow all the changes, probably via a helper methods. Fee meta and transaction meta is already handled in [`LedgerTransaction.GetChanges`](https://godoc.org/github.com/stellar/go/exp/ingest/io#LedgerTransaction.GetChanges) we need to add upgrades.

**Comment by ire-and-curses** [comment]
I'm not completely sure what this means - could you add a description?

**Comment by bartekn** [comment]
Sorry, I created an issue as a quick note to myself while working on a code. Description updated.

**Comment by bartekn** [comment]
Ledger upgrades can be found in [`upgradehistory`](https://github.com/stellar/stellar-core/blob/master/docs/db-schema.md#upgradehistory) table. See: https://github.com/stellar/stellar-core/blob/master/docs/integration.md#applying-changes-in-the-high-resolution-custom-view

**Comment by bartekn** [comment]
Closed in: #1862.
