### ISSUE TITLE
services/ticker: add CORS headers to allow front-end applications to use the ticker

### ISSUE THREAD

**Issue by accordeiro** [stellar/go#1471]
We should enable browser applications to fetch data from the ticker, which means adding [this config](https://enable-cors.org/server_nginx.html) to nginx.

**Comment by bartekn** [comment]
Is it devops issue? If so should be moved to [puppet-v4](https://github.com/stellar/puppet-v4) repo. However can be easily added in ticker app itself.

**Comment by accordeiro** [comment]
Yeah, this is a DevOps issue – we're planning to do it via nginx config since the `/markets.json` and `/assets.json` are served by nginx directly, instead of via a go HTTP server.

I've just created the issue here because I needed to mention it on a blog post response, and the other repo isn't public. I'll follow-up here and close this when the issue is fixed :)

**Comment by bartekn** [comment]
Oh, makes total sense! Thanks!

**Comment by accordeiro** [comment]
Quick follow-up: CORS headers now available across all Ticker endpoints.
