### ISSUE TITLE
horizon error 500 when submitting transaction

### ISSUE THREAD

**Issue by minhaj-shakeel** [stellar/go#1477]
I am trying to create account on my private stellar network which is established by using core. I also attached horizon to one od the nodes , and when I am trying to create a transaction on network it for openening an account it shows

`{u'status': 500, u'type': u'https://stellar.org/horizon-errors/server_error', u'detail': u'An error occurred while processing this request.  This is usually due to a bug within the server software.  Trying this request again may succeed if the bug is transient, otherwise please report this issue to the issue tracker at: https://github.com/stellar/go/services/horizon/internal/issues. Please include this response in your issue.', u'title': u'Internal Server Error'} `

**Comment by bartekn** [comment]
Do you see any `level=error` log entries?

**Comment by minhaj-shakeel** [comment]
```
INFO[2019-07-05T11:39:25.330+05:30] Submission system result                      hash= pid=34459 req=Minhajs-MacBook-Air.local/2oyJWwloQ7-000009 result="{Err:tx failed: AAAAAAAAAZD////6AAAAAA== Hash: LedgerSequence:0 EnvelopeXDR:AAAAAHN2/eiOTNYcwPspSheGs/HQYfXy8cpXRl+qkyIRuUbWAAABkAAAAAAAAAABAAAAAAAAAAEAAAALbmV3IGFjY291bnQAAAAAAgAAAAAAAAAAAAAAAKepztJ9kSpBauqqbYLItkg91SG1325yOdPmfi5DsyfwAAAAF0h26AAAAAAAAAAAAAAAAADrSfii1yQhTzlw8Bm9uaP7lnN4z1PtrFJbGH4fGghXawAAABdIdugAAAAAAAAAAAERuUbWAAAAQG56AGdfQ21qt8y5qEEJtbJJiUsYPJhRWjN5lHYv27No9S5TO6JQTM8jtCvTdCE7lRiPZv5JLxPLNSzjlDKjUg4= ResultXDR: ResultMetaXDR:}" service=txsub.System
INFO[2019-07-05T11:39:25.330+05:30] Finished request                              app_name=undefined app_version=undefined bytes=889 client_name=py-stellar-base client_version=1.2.2 duration=0.011024836 forwarded_ip= host="localhost:8000" ip="[::1]" ip_port="[::1]:62184" method=POST path=/transactions/ pid=34459 req=Minhajs-MacBook-Air.local/2oyJWwloQ7-000009 route=/transactions status=400 streaming=false
```

**Comment by bartekn** [comment]
> `u'status': 500`
> status=400

These logs are not connected.
