### ISSUE TITLE
Documentation for /accounts/{account id} says trustlines that require auth won't be shown

### ISSUE THREAD

**Issue by patrickxb** [stellar/go#1503]
On this page:

https://www.stellar.org/developers/horizon/reference/endpoints/accounts-single.html

It states:

> The balances section in the returned JSON will also list all the trustlines this account established. Note this will only return trustlines that have the necessary authorization to work. Meaning if an account A trusts another account B that has the authorization required flag set, the trustline won’t show up until account B allows account A to hold its assets.

This doesn't seem to be accurate.  For example:

https://horizon.stellar.org/accounts/GBZX4364PEPQTDICMIQDZ56K4T75QZCR4NBEYKO6PDRJAHZKGUOJPCXB

```
 "balances": [
    {
      "balance": "0.0000000",
      "limit": "922337203685.4775807",
      "buying_liabilities": "0.0000000",
      "selling_liabilities": "0.0000000",
      "last_modified_ledger": 24795752,
      "is_authorized": false,
      "asset_type": "credit_alphanum4",
      "asset_code": "EUR",
      "asset_issuer": "GAKBPBDMW6CTRDCXNAPSVJZ6QAN3OBNRG6CWI27FGDQT2ZJJEMDRXPKK"
    },
```

Note the `"is_authorized": false` for that asset.

**Comment by ire-and-curses** [comment]
Good catch! This was added a few months ago in [8a330cb](https://github.com/stellar/go/commit/8a330cb9e8ea4791a76e199dd998126dd2a6c3bb). Looks like we just forgot to update the doc.
