### ISSUE TITLE
Implement Horizon /offers/:id endpoint

### ISSUE THREAD

**Issue by orbitlens** [stellar/go#1520]
Currently there is no way to fetch an offer by its id from the Horizon. The only workaround is to discover the parent account for the offer (which is impossible on the client side), fetch all account offers, and match returned results by id.

`accounts/:accountId/offers` endpoint returns a paging link to the offer, but the server returns `404 Resource Not Yet Implemented`:

```
"_embedded": {
    "records": [
      {
        "_links": {
          "self": {
            "href": "https://horizon.stellar.org/offers/87691697"
          },
...
```

**Comment by bartekn** [comment]
Closed in #1598.
