### ISSUE TITLE
services/horizon: expose alternative path finding endpoint 

### ISSUE THREAD

**Issue by tamirms** [stellar/go#1525]
In https://github.com/stellar/go/pull/1458 we were able to prototype a path finding endpoint which uses an in memory orderbook. This alternative implementation of the path finding endpoint is much faster than the existing implementation and it returns paths which are more optimal. Using the in memory orderbook should also fix the reliability problems noted here: https://github.com/stellar/go/issues/1496

We should provide a configuration option to expose the new path finding implementation in horizon. In that release we can also remove the required `destination_account` parameter which is not used by the endpoint.

**Comment by bartekn** [comment]
Closed in #1519.
