### ISSUE TITLE
txnbuild: add a method for verifying SEP-10 challenge transactions

### ISSUE THREAD

**Issue by poliha** [stellar/go#1530]
The `txnbuild` package has a method(`BuildChallenge`) that builds a [SEP 10](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0010.md) challenge transaction. There should be a corresponding method(`VerifyChallenge`)  that verifies a [SEP-10](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0010.md) challenge transaction.

This method should do the following

- [x] decode the received input as a base64-urlencoded XDR representation of Stellar transaction envelope;

- [x] verify that transaction source account is equal to the server's signing key;

- [x] verify that transaction has time bounds set, and that current time is between the minimum and maximum bounds;

- [x] verify that transaction contains a single Manage Data operation and its source account is not null;

- [x] verify that transaction envelope has a correct signature by server's signing key;

- [x] verify that transaction envelope has a correct signature by the operation's source account;

**Comment by abuiles** [comment]
@poliha  Is the following checking that the transaction was signed by the client?

> verify that transaction envelope has a correct signature by the operation's source account;

If that's the case, are we sure this should be part of this checks? the way I understand it is, as a client, I want to check that the challenge is valid before signing it and send it back to the server.

Maybe we could add a flag to check bot the signature on the operation source account. 

`VerifyChallenge(challenge, serverAccountId, checkOperation = true)`

**Comment by poliha** [comment]
@abuiles The verification steps above is done by the server before responding with a JWT for the client to access other services. We have been approaching the building and verification of the challenge from the perspective of the server. The SEP doesn't mention a validation step for the client @tomq is this by design?
In my opinion, i don't think we need the client to verify anything because the transaction can never be submitted to the network.

**Comment by abuiles** [comment]
@poliha makes sense. My reasoning was that as a client I want to do some checks before signing it, at least I want to make sure the sequenceNumber is 0 -- but that's such a simple check that it can be left to the client  to implement it.

**Comment by abuiles** [comment]
I think this was fixe dby @leighmcculloch

**Comment by leighmcculloch** [comment]
This was done by @poliha in #1576 actually 😄. 👍
