### ISSUE TITLE
Add helper to sign an existing XDR-encoded transaction

### ISSUE THREAD

**Issue by ire-and-curses** [stellar/go#1540]
Similar to #1530, we should provide a higher-level helper to allow a user to sign a transaction that was provided to them as an encoded string. This workaround can be retired once we implement #1329 so should be as lightweight as possible (i.e. just a simple helper function).

Example of current workaround: https://stellar.stackexchange.com/questions/2689/what-is-the-correct-way-to-unmarshal-an-encoded-transaction-for-signing

**Comment by poliha** [comment]
This is no longer required. see fix in #1329
