### ISSUE TITLE
Draft of a technical ingestion blog post aimed at developers

### ISSUE THREAD

**Issue by ire-and-curses** [stellar/go#1546]
We will eventually want to publish a blog post about how the ingestion system works, and how to use it as a developer. In order to help the other members of the Horizon team get up to speed, let's spend no more than half a day of effort writing a draft of this now that they can use to orient themselves as they begin to work with the system.

Note that this should not include *why* we are doing ingestion, and the benefits it brings. That will be a [separate blog post](https://www.stellar.org/developers/blog/our-new-horizon-ingestion-engine).

**Comment by ire-and-curses** [comment]
Discussed this with @bartekn and @tamirms. We'll make a Google doc to work on collaboratively. Bartek will sketch out the topics and start us off.

**Comment by bartekn** [comment]
The doc is ready but I think we need to improve before making it public. Do you want to move this issue to the backlog or close or create another one @ire-and-curses?

**Comment by ire-and-curses** [comment]
Actually I think this is done. The internal doc we produced is great, and will be easy to mine for the blog post later.
