### ISSUE TITLE
Only maintain support for the last two releases of Golang 

### ISSUE THREAD

**Issue by tamirms** [stellar/go#1548]
Go 1.13 is scheduled to be released soon in August. Currently, we support Go 1.10, 1.11, and 1.12. If we want migrate to go modules instead of using dep it would be great if we could drop support for Go 1.10.

@leighmcculloch  has also noted that:

> Go security releases and only support back to the last 2 versions of Go

> for anything financial/critical it's usually best to only offer official support for versions that are still receiving security updates (which is officially the last 2 versions so right now Go1.12 and 1.11)

To drop support for older versions of Go we need to update the documentation in the repo and edit the circle ci configuration to stop testing our builds on older versions of Go.

**Comment by leighmcculloch** [comment]
The reference for which releases are supported is here:
>Each major Go release is supported until there are two newer major releases. For example, Go 1.5 was supported until the Go 1.7 release, and Go 1.6 was supported until the Go 1.8 release. We fix critical problems, including critical security problems, in supported releases as needed by issuing minor revisions (for example, Go 1.6.1, Go 1.6.2, and so on).
-- https://golang.org/doc/devel/release.html#policy

**Comment by leighmcculloch** [comment]
@tamirms and I spoke earlier today and agreed I could take this issue. I forgot to update it till now. ☝️
