### ISSUE TITLE
restrict trade aggregation to specific resolutions

### ISSUE THREAD

**Issue by tomerweller** [stellar/go#155]
Right now, aggregation can use any arbitrary bucket size resolution. This works because aggregation is done on the fly. 

We need to restrict this to a specific set of resolutions, given that in the future these will likely be pre-computed. 

Resolutions: 
- 5-minutes
- 1-hour
- 1-day
- 1-week

**Comment by howardtw** [comment]
Closing because we have another similar [PR](https://github.com/stellar/go/issues/632)
