### ISSUE TITLE
services/horizon: pre-compute trade aggregations

### ISSUE THREAD

**Issue by tomerweller** [stellar/go#1554]
The trade aggregation endpoint currently aggregates trade stats on the fly. For high resolutions (24 hour buckets, for example) on active pairs this can get pretty slow.
 
We could pre-compute buckets in preset resolutions for improved performance. 

However, this would take up a bunch of space and only dex frontends really care. So we should put this behind a configuration flag. 

Happy to discuss in person, as I'm the person who wrote this behemoth :)

**Comment by ire-and-curses** [comment]
That makes sense to me. We did caching something like this for the StellarX trading graphs, to speed up performance by reducing the time range of Horizon calls.

**Comment by howardtw** [comment]
We talked about this before here -> https://github.com/stellar/go/issues/632

**Comment by bartekn** [comment]
Let's track it in https://github.com/stellar/go/issues/632.
