### ISSUE TITLE
Signing method for unsigned XDR using stellar/go/txnbuild

### ISSUE THREAD

**Issue by saulodigital** [stellar/go#1557]
There's a feature missing in Stellar Go, if we create a transaction from an unsigned XDR and later try to sign it, txnbuild doesn't support a signing method of unsigned XDR (tx.sign method doesn't do that).

There will be errors if we change stellar/go/build to stellar/go/txnbuild with the intention to remove all dependency from accessing stellar/go packages such as horizon, build, xdr and use only txnbuild and horizonclient.

To solve this issue we can think of two solutions:

Option A - We write a simple method from build,xdr package that signs the unsigned XDR. However, this will be against the ideology of using just txnbuild and horizonclient. This will be sort of a temporary hack to solve this signing issue.

Option B - A method for signing unsigned XDR is added to stellar/go/txnbuild. This will solve our problem and possibly help other users who may need this feature.

**Comment by ire-and-curses** [comment]
We are working on supporting `txnbuild` initialisation from XDR right now - see #1329 for current progress. We expect to release this soon.

If you need this immediately, the workaround requires the `xdr` libary, as you say. Take a look at this Stack Exchange Q&A for a working example: [What is the correct way to unmarshal an encoded transaction for signing](https://stellar.stackexchange.com/q/2689/1552)

**Comment by Keleigh123** [comment]
Hi I can't seem to find a solution for unmarshalling an already built unsigned XDR to add a signature. Was the solution for this introduced with the txnbuild package? I would be very grateful if I can be assisted on this
