### ISSUE TITLE
Fix TimeBounds error in txnbuild/README.md

### ISSUE THREAD

**Issue by mikeyrf** [stellar/go#1561]
There's a small, but potentially time-consuming error in the example code provided in the [`txnbuild/README.md`](https://github.com/stellar/go/tree/master/txnbuild#txnbuild) file. The `Timebounds` field in the constructed `txnbuild.Transaction` is set to `txnbuild.NewTimebounds(0, 300)` but this puts a max **unix time** bound of 300 seconds, so the tx will always fail.

If this is changed to `txnbuild.NewTimeout(300)`, the network accepts the tx just fine.

**Comment by ire-and-curses** [comment]
@mikeyrf good catch! If you could submit a quick PR for that, it would be awesome :)

**Comment by mikeyrf** [comment]
@ire-and-curses thanks, but more of my own floundering that led to it :/ ... PR submitted 👍

**Comment by abuiles** [comment]
Fixed via #1567
