### ISSUE TITLE
update go sdk to support all assets endpoint

### ISSUE THREAD

**Issue by nikhilsaraf** [stellar/go#157]

**Comment by poliha** [comment]
Yes, it might be worth revisiting the design of the API. For example, something that seems missing is the equivalent of the JS sdk `CallBuilder`, which might be really useful in extending the supported endpoints.

**Comment by howardtw** [comment]
Do you think we can close this issue? @poliha @ire-and-curses?

**Comment by poliha** [comment]
Yes. Resolved in #974
