### ISSUE TITLE
Migrate Horizon to new ingestion

### ISSUE THREAD

**Issue by bartekn** [stellar/go#1577]
## Remaining ingestion issues

- #1470 Make sure fee and ledger upgrade changes are processed - when a protocol upgrade happens it's possible that the state is updated too. New ingestion must apply these changes.
- ~#1550 Ingestion: verify updating data against stellar-core~
- #1393 Configure ingestion pipeline from a configuration file - would be great to have new Horizon to allow filtering data and turning on/off features. It's not blocking and requires more design process so the other issues are more important.
- Ingestion system upgrades (not creating an issue yet). In case the ingestion system is upgraded we currently clear the state and build it from a latest checkpoint. When we'll start adding historical data (txs, ops, effects) this needs to be updated as we shouldn't be removing historical data. Also think about reingestion of historical data.
- Ensure history archive and ledger backend are for the same network.

## Endpoints

In general I think we should prepend all new endpoints with `/exp` prefix (including `/accounts` and `/paths` unfortunately). The system is still experimental and when we're sure that everything's working correctly we can easily replace old endpoints. List of endpoints with a short summary of actions required below. Separate issues to be created.

---

No changes planned to the following endpoints:

* `/`
* `/metrics`
* `POST /transactions`

For the following endpoints we need a new processor saving ledgers to a DB (tracked in #1709):

- [x] `/ledgers`
- [x] `/ledgers/{ledger_id}`
- [x] `/fee_stats` - generation maybe in post-processing hook?

For the following endpoints we need a new processor (#1711) saving transactions to a DB (tracked in #1712 ):

- [x] `/transactions`
- [x] `/transactions/{tx_id}`
- [x] `/ledgers/transactions`
- [x] `/accounts/{account_id}/transactions`

For the following endpoints we need a new processor saving operations to a DB:

- [x] `/operations`
- [x] `/operations/{id}`
- [x] `/ledgers/{id}/operations`
- [x] `/ledgers/{id}/payments`
- [x] `/accounts/{account_id}/operations`
- [x] `/accounts/{account_id}/payments`
- [x] `/transactions/{tx_id}/operations`
- [x] `/transactions/{tx_id}/payments`
- [x] `/payments`

We already have a new `offers` table (and processor updating offers in a database) so should be easy to implement endpoints below (tracked in #1597):

- [x] `/offers`
- [x] `/offers/{id}`
- [x] `/accounts/{account_id}/offers`
- [x] `/order_book` - I think order book graph can be used, it already has sorted order books inside.
- [x] `/paths` (already implemented)

Add more filters ex. by trustline to `/accounts`. Also we need to add `accounts` table that will keep all accounts data (ex. signers, trustlines should be in a separate table) (tracked in #1766).

- [x] `/accounts/` (partially)
- [x] `/accounts/{account_id}/`
- [x] `/assets` (should use `trustlines` table, if there's a need: aggregating data every X ledgers for performance) (#1765)

All endpoints below are responsible for displaying effects and we need a set of new processors to extract them (see "Effects processors" notes):

- [x] `/effects`
- [x] `/ledgers/effects`
- [x] `/accounts/{account_id}/effects`
- [x] `/accounts/{account_id}/trades`
- [x] `/accounts/{account_id}/data/{key}`
- [x] `/operations/{id}/effects`
- [x] `/transactions/{tx_id}/effects`
- [x] `/trades`
- [x] `/offers/{id}/trades`
- [x] `/trade_aggregations`

### Effects processors notes

- Should be easy to do with [`LedgerTransaction.GetChanges`](https://godoc.org/github.com/stellar/go/exp/ingest/io#LedgerTransaction.GetChanges).
- The old ingestion system has this huge [`switch`](https://github.com/stellar/go/blob/master/services/horizon/internal/ingest/session.go#L151) checking operation type and creating effects based on this. Would be great to use pipeline to pass only transactions with operations a given processor is interested. So something like:
```
-> FilterTransactionsProcessor{OperationType: CreateAccount}
  -> CreateAccountEffectsProcessor{}
-> FilterTransactionsProcessor{OperationType: Payment}
  -> PaymentEffectsProcessor{}
```
OR, filter operations needed by a given effects group:
```
-> FilterTransactionsProcessor{OperationType: []{CreateAccount, Payment, PathPayment, ...}
  -> AccountEffectsProcessor{}
-> FilterTransactionsProcessor{OperationType: []{SetOptions}
  -> SignerEffectsProcessor{}
```
both ways will make the code easier to understand and test.
- Not in a scope of the this issue but in a future pipeline will also update trade aggregations buckets (https://github.com/stellar/go/issues/632).

**Comment by ire-and-curses** [comment]
:tada: :tada: :tada: :tada: :tada:
