### ISSUE TITLE
Display trust line authorization state in the balances list

### ISSUE THREAD

**Issue by bartekn** [stellar/go#159]
Since this feature is used by more users recently it would be great to access it in Horizon. Seems to be very easy to implement.

Desired change to the JSON. Add a new array that is present if there are any unauthorized trustlines:
```
...,
"balances": [
    {
      "balance": "10.0000000",
      "limit": "922337203685.4775807",
      "asset_type": "credit_alphanum12",
      "asset_code": "DUBUNDA",
      "asset_issuer": "GCGTJPNBL7TNUO647AWQFEEL2PHK4BJ56RZCT77H2R6AHPCUC7CCHHGV"
    },
    {
      "balance": "9999.9999900",
      "asset_type": "native"
    }
  ],
"unauthorized_balances":[
 {
      "balance": "0.0000000",
      "limit": "922337203685.4775807",
      "asset_type": "credit_alphanum4",
      "asset_code": "USD",
      "asset_issuer": "GCGTJPNBL7TNUO647AWQFEEL2PHK4BJ56RZCT77H2R6AHPCUC7CCHHGV"
    },
],
...

```

**Comment by r8d8** [comment]
@bartekn, 
can I take it?

**Comment by bartekn** [comment]
I see Jed added "help wanted" tag so I think you can give it a try :)

**Comment by r8d8** [comment]
Related to https://github.com/stellar/horizon/issues/298

**Comment by dulanov** [comment]
@r8d8 I am going to sync my own horizon instance with the testnet in order to look at the trustlines table content, from the code there is no feeling that only authorized trustlines show up:

```go
var selectTrustline = sq.Select(
	"tl.accountid",
	"tl.assettype",
	"tl.issuer",
	"tl.assetcode",
	"tl.tlimit",
	"tl.balance",
	"tl.flags",
).From("trustlines tl")
```

then

```go
	// populate balances
	this.Balances = make([]Balance, len(ct)+1)
	for i, tl := range ct {
		err = this.Balances[i].Populate(ctx, tl)
		if err != nil {
			return
		}
	}
```

**Comment by r8d8** [comment]
@bartekn, 
can you please specify how this authorization state should be presented.
If i get it roght here is [request to db](https://github.com/stellar/go/blob/master/services/horizon/internal/db2/core/trustline.go#L41) that returns info for account, and then [API callback](https://github.com/stellar/go/blob/master/services/horizon/internal/actions_account.go#L28) for reuired data

**Comment by bartekn** [comment]
> Related to stellar/horizon#298

@r8d8 Thanks, haven't noticed this. Let's track it in https://github.com/stellar/horizon/issues/298

**Comment by jedmccaleb** [comment]
other way let's close the other issue and track this here.

**Comment by jedmccaleb** [comment]
@nullstyle  In the returned JSON from `/accounts`, would you be ok with another array called "unauthorized_balances" or something that lists the trustlines that still need go be auth'd by the issuer? It seemed like originally you wanted a separate endpoint to get the unauthorized trustlines of an account but maybe just clearly separating them out would be enough?

**Comment by r8d8** [comment]
Have created three accounts - [GCGT]( https://horizon-testnet.stellar.org/accounts/GCGTJPNBL7TNUO647AWQFEEL2PHK4BJ56RZCT77H2R6AHPCUC7CCHHGV)(issuer), [GA6T]( https://horizon-testnet.stellar.org/accounts/GA6TXOR64DZX6KRNDVBLL2MRILUXUDHIHMGUE4YFMXWOUQBF2GGMXQZD
), [GAF7](https://horizon-testnet.stellar.org/accounts/GAF76ZPFK3IY6GZ7L46XHE7RFLSTN6H5DM3EZNQU4SJKWRCD7PBSEGDA):

* `GCGT` has flag `AUTORIZATION_ REQUIRED`
* `GA6T` and `GAF7` created trustlines to `GCGT` for asset code `DUBUNDA`. Trustline was approved only for `GAF7`.

But both accounts have the same record (see links), no way to distinguish pending trustline. For pending trustline the output is:

```json
"balances": [
    {
      "balance": "0.0000000",
      "limit": "922337203685.4775807",
      "asset_type": "credit_alphanum12",
      "asset_code": "DUBUNDA",
      "asset_issuer": "GCGTJPNBL7TNUO647AWQFEEL2PHK4BJ56RZCT77H2R6AHPCUC7CCHHGV"
    },
    {
      "balance": "9999.9999900",
      "asset_type": "native"
    }
  ]
```

SQL request shows that `flags` field differs for those accounts, we can use it:

```console
core_testnet=# SELECT * FROM trustlines WHERE assetcode = 'DUBUNDA';
                        accountid                         | assettype |                          issuer                          | assetcode |       tlimit        | balance | flags | lastmodified 
----------------------------------------------------------+-----------+----------------------------------------------------------+-----------+---------------------+---------+-------+--------------
 GA6TXOR64DZX6KRNDVBLL2MRILUXUDHIHMGUE4YFMXWOUQBF2GGMXQZD |         2 | GCGTJPNBL7TNUO647AWQFEEL2PHK4BJ56RZCT77H2R6AHPCUC7CCHHGV | DUBUNDA   | 9223372036854775807 |       0 |     0 |      5423500
 GAF76ZPFK3IY6GZ7L46XHE7RFLSTN6H5DM3EZNQU4SJKWRCD7PBSEGDA |         2 | GCGTJPNBL7TNUO647AWQFEEL2PHK4BJ56RZCT77H2R6AHPCUC7CCHHGV | DUBUNDA   | 9223372036854775807 |       0 |     1 |      5423668
(2 rows)
```

@nullstyle, ok the field will be  `trustline_requested` (you suggested [here](https://github.com/stellar/horizon/issues/298#issuecomment-236255334))? Also, what do you think about add pending trustline for the issuer resources?

**Comment by dulanov** [comment]
@jedmccaleb mey be more simple, just a new additional `unauthorized` bool flag for `balances` field:

```json
"balances": [
    {
      "balance": "0.0000000",
      "limit": "922337203685.4775807",
+++      "unauthorized": false,
      "asset_type": "credit_alphanum12",
      "asset_code": "DUBUNDA",
      "asset_issuer": "GCGTJPNBL7TNUO647AWQFEEL2PHK4BJ56RZCT77H2R6AHPCUC7CCHHGV"
    },
    {
      "balance": "9999.9999900",
      "asset_type": "native"
    }
  ]
```

**Comment by dulanov** [comment]
I like stellar's approach to use relational DB a lot, you don't need over-complicated tools like [etherscan](https://etherscan.io) at all ;)

Ah, @r8d8 FYI how many not unauthorized trustlines exist right now:

```sql
SELECT count(*) FROM trustlines WHERE trustlines.flags = 0
 count
-------
   162
(1 row)
```

or the `auth_required` accounts ration (`0.5%`):

```sql
core_testnet=# SELECT
core_testnet-#   count(accounts.accountid) * 100.0 / (SELECT DISTINCT count(*) FROM accounts) as auth_ratio
core_testnet-# FROM accounts WHERE accounts.flags&1 = 1;
       auth_ratio
------------------------
 0.50973018282322557260
(1 row)
```

**Comment by elie222** [comment]
As this doesn't look like it's being implemented, is there a workaround that is recommended?

The two workarounds I see possible at the moment are `Operations for Account` and `Effects for Account`. With the former:

```json
{
        "id": "45441435481418753",
        "paging_token": "45441435481418753",
        "source_account": "GBATMJI6RR6UTOBP6LVOUEJXTNB5JQ6U3RXXJSZYJRZU7H3IJNDDWX2W",
        "type": "allow_trust",
        "type_i": 7,
        "created_at": "2018-08-17T00:44:06Z",
        "transaction_hash": "20d0db0e80432886c90a6f498463e85526758d29f2bf167c34d7ca388d3f4cb0",
        "asset_type": "credit_alphanum12",
        "asset_code": "MyToken",
        "asset_issuer": "GBATMJI6RR6UTOBP6LVOUEJLTNB5JQ6U3RXXJSZYJRZU7H3IJNDDWX2W",
        "trustee": "GBATMJI6RR6UTOBP6LVOUEJXTNB5JQ6U3RXXJSZYJRZU7H3IJNDDWX2W",
        "trustor": "GALZCFIDNHXIKPRACMHICAUXIRXH2JXMSXYQBACTEM4WDEQGJJJBXE6Q",
        "authorize": true
      },
```

But you may have to sift through many pages of operations / effects, so I don't see this as a great solution.

**Comment by nikita-ng** [comment]
Facing the same issue. Please update the horizon /account/ API as its required.

**Comment by howardtw** [comment]
Closing. The `Balance` struct will have a new [field](https://github.com/stellar/go/blob/master/protocols/horizon/main.go#L150) called `is_authorized` in the next release.
