### ISSUE TITLE
FriendBot is not working

### ISSUE THREAD

**Issue by donamk** [stellar/go#1591]
I test with several accounts but all failed and showed the following error.

```
{
  "type": "https://stellar.org/horizon-errors/server_error",
  "title": "Internal Server Error",
  "status": 500,
  "detail": "An error occurred while processing this request.  This is usually due to a bug within the server software.  Trying this request again may succeed if the bug is transient, otherwise please report this issue to the issue tracker at: https://github.com/stellar/go/issues. Please include this response in your issue."

```

**Comment by alicedevgit** [comment]
I've got the same problem, also when posting transaction.

It seems test network has some problem?

**Comment by ire-and-curses** [comment]
The test network entered surge pricing mode, and friendbot's fees were insufficient for its transactions to be included in the ledger. Fixed in #1594. Longer term fix is planned: #1592.

**Comment by brabo-hi** [comment]
FriendBot not working to add fund on testNet.
```
// The SDK does not have tools for creating test accounts, so you'll have to
// make your own HTTP request.
import java.net.*;
import java.io.*;
import java.util.*;

String friendbotUrl = String.format(
  "https://friendbot.stellar.org/?addr=%s",
  pair.getAccountId());
InputStream response = new URL(friendbotUrl).openStream();
String body = new Scanner(response, "UTF-8").useDelimiter("\\A").next();
System.out.println("SUCCESS! You have a new account :)\n" + body);
```
I am getting the following error
```
Error during processing of request: 'Error response from the server.'. Completing with 500 Internal Server Error response. To change default exception handling behavior, provide a custom ExceptionHandler.
```

**Comment by ire-and-curses** [comment]
@brabo-hi Friendbot funding is working for me. If this is still a problem for you, please raise an issue here: https://github.com/stellar/java-stellar-sdk/issues

**Comment by brabo-hi** [comment]
> @brabo-hi Friendbot funding is working for me. If this is still a problem for you, please raise an issue here: https://github.com/stellar/java-stellar-sdk/issues

Yes it is working when using curl
