### ISSUE TITLE
Ingestion: port offers-related endpoints to new ingestion system

### ISSUE THREAD

**Issue by ire-and-curses** [stellar/go#1597]
We already have a new offers table (and processor updating offers in a database) so should be easy to implement endpoints below:

- [x] `/offers` (#1610)
- [x] `/offers/{id}` (#1602)
- [x] `/accounts/{account_id}/offers` (#1694)
- [x] `/order_book` - I think order book graph can be used, it already has sorted order books inside, if not just use a DB. (#1705)
- [x] `/paths` (already implemented)

Each endpoint should be done as a separate PR.

This work is part of #1577.

**Comment by abuiles** [comment]
This is done cc @tamirms
