### ISSUE TITLE
Decide on use of int64 in JSON responses.

### ISSUE THREAD

**Issue by abuiles** [stellar/go#1609]
This is a follow up of #1363 - we have multiple places where we return int64 in JSON responses, which could lead to issues in JS applications. We fixed the problem reported in #1363, but the question now is, should we do the same for the following struct and moving forward, does it make sense to avoid int64 on Horizon structs? We haven't been consistent with this.

- [x] go/protocols/horizon/operations/main.go:139:10:	OfferID int64 `json:"offer_id"`
- [x] go/protocols/horizon/operations/main.go:146:10:	OfferID int64 `json:"offer_id"`
- [x] go/protocols/horizon/effects/main.go:260:20:	OfferID           int64  `json:"offer_id"`
- [x] go/protocols/horizon/main.go:228:21:	ID                 int64      `json:"id"`
- [x] go/protocols/horizon/main.go:376:16:	Timestamp     int64     `json:"timestamp"`
- [x] go/protocols/horizon/main.go:377:16:	TradeCount    int64     `json:"trade_count"`

**Comment by bartekn** [comment]
@abuiles can you update the Horizon 0.20.0 CHANGELOG with that list and add `Action needed` tags (for 0.22.0 release)?

**Comment by ire-and-curses** [comment]
After internal discussion we're going to change all of these in Horizon 0.25, to give SDKs enough time to handle it.

**Comment by ire-and-curses** [comment]
Yes. These fields will change to `string`. We'll be raising issues with all the SDKs (ours + community). We'll aim to support the fields both before and after the change with the next SDK version, so that the Horizon update won't cause clients to break at a discrete point in time.

**Comment by abuiles** [comment]
Fixed on#2021.
