### ISSUE TITLE
removed support for for context aware handlers in rs/cors affects horizon binary built

### ISSUE THREAD

**Issue by yulemata** [stellar/go#164]
The guys from rs/cors have removed support for context aware handlers. See here https://github.com/rs/cors/issues/32.

This causes binary built errors if someone before building did a glide update. I tried building horizon after doing a glide update and got the following error: 
`github.com/stellar/go/vendor/github.com/rs/cors
vendor/github.com/rs/cors/cors.go:197:30: cannot convert func literal (type func("github.com/stellar/go/vendor/golang.org/x/net/context".Context, http.ResponseWriter, *http.Request)) to type xhandler.HandlerFuncC`

Solution for the above issue is explained here https://github.com/rs/cors/issues/36.

Workaround until this issue is solved: Do not do glide update.

**Comment by howardtw** [comment]
Closing because horizon-v0.18.0 will have the updated lib of cors.
