### ISSUE TITLE
bridge and compliance services promote support of mysql when we announced it was not supported

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/go#1659]
Both the `bridge` and `compliance` services mention in their `CHANGELOG`s that mysql databases are unsupported, however in READMEs and code it is still advertised. According to a chat offline with @poliha, we made an explicit decision to stop supporting mysql on these two services when they were ported to the monorepo.

Changelogs:

https://github.com/stellar/go/blob/bcd03d3073aece7adc43aacb6d9ec80b4892937c/services/bridge/CHANGELOG.md#L17

https://github.com/stellar/go/blob/bcd03d3073aece7adc43aacb6d9ec80b4892937c/services/compliance/CHANGELOG.md#L16

In their code mysql support is still present:

https://github.com/stellar/go/blob/bcd03d3073aece7adc43aacb6d9ec80b4892937c/services/bridge/internal/config/main.go#L102-L103

https://github.com/stellar/go/blob/bcd03d3073aece7adc43aacb6d9ec80b4892937c/services/compliance/internal/config/main.go#L86-L87

We should make all the code and documentation about database support for these two services align by:
- [x] Remove mention of `mysql` from `bridge` README to stop advertising something we are already not maintaining support @leighmcculloch 
- [x] Remove mention of `mysql` from `compliance` README to stop advertising something we are already not maintaining support @leighmcculloch 
- [x] Remove support for `mysql` from `bridge` code @leighmcculloch 
- [x] Remove support for `mysql` from `compliance` code @leighmcculloch 
- [x] Remove mention of `mysql` from `bridge` guides https://www.stellar.org/developers/guides/anchor/2-bridge-server.html @rice2000 
- [x] Remove mention of `mysql` from `compliance` guides https://www.stellar.org/developers/guides/anchor/4-compliance-server.html @rice2000

Note: `federation` appears to support `mysql` without any indications we've ever wanted to deprecate support for it in that service. Unless we identify we want to stop supporting it there too, we should not remove support from that service as part of this code cleanup.

**Comment by leighmcculloch** [comment]
I added some additional checkboxes above to remove mention of mysql from the guides as well. We still mention it in those.

**Comment by leighmcculloch** [comment]
Reopening, because the guide/docs changes haven't been done yet. That's with @rice2000.

**Comment by rice2000** [comment]
Yep.  I'll get to that this week.

**Comment by rice2000** [comment]
I fixed the docs.  Ready to close.

**Comment by leighmcculloch** [comment]
Thanks @rice2000 ! 🎉
