### ISSUE TITLE
Make examples fully qualified

### ISSUE THREAD

**Issue by msfeldstein** [stellar/go#1660]
Currently our example code (for example [StreamPayments](https://godoc.org/github.com/stellar/go/clients/horizonclient#example-Client-StreamPayments)) shows code running inside our Go SDK package, but anyone else will be running code outside the package.  This means that they will need to properly qualify all the classes and methods, add the proper imports.  This makes it far harder to just copy/paste/run examples.  We should have the examples be fully qualified.

From @leighmcculloch :
```
we should put our examples in a separate files, something like examples_test.go, and at the top of the file, change package wonderfulthings to package wonderfulthings_test.

it will mean you’ll need to import github.com/stellar/wonderfulthings and throughout the code you’ll reference functions, types, etc as wonderfulthings.AmazingType.
```

**Comment by Rabatte** [comment]
It will definitely be helpful. thank you very much
