### ISSUE TITLE
horizon db init - authentication failed

### ISSUE THREAD

**Issue by sgehrman** [stellar/go#167]
$ horizon db init
ERRO[0000] connect failed: pq: password authentication failed for user

I'm a noob, help would be appreciated.

**Comment by mvaneijk** [comment]
Looks like you haven't set the environmental variables. 

Please read the https://github.com/stellar/go/blob/master/services/horizon/internal/docs/reference/admin.md

**Comment by dulanov** [comment]
It looks like you need to specify a password for username `user` (Ex.: `postgresql://user:secret@localhost/dbname?sslmode=disable`).

**Comment by sgehrman** [comment]
I did set the env vars, but I don't know much about postgres.  I set up a db, but not sure why it's choosing a particular user name and I don't know how to set the password and don't know how to specify the password when running horizon. Instructions step by step would help.  I did manage to get stellar-core running with postgres, by luck, but that was a bit simpler since the .cfg file has the db, name and password.  Thanks, I'm very new to setting up databases.

**Comment by sgehrman** [comment]
Thanks, adding the username:password fixed it.  I'm really new to postgres, so adding more info to your instructions would be helpful.  Instructions on making a new user with a password and creating a db would help and add the username:pass to the example urls.  I got it working by luck and trial and error that lasted hours.

**Comment by sgehrman** [comment]
I'm trying to connect my client app to my local horizon.  Getting net::ERR_SSL_PROTOCOL_ERROR

Trying this:     this.server = new StellarSdk.Server('https://192.168.133.106:8000')

env:

export DATABASE_URL="postgres://bubba:bubba@localhost/horizon?sslmode=disable"
export STELLAR_CORE_DATABASE_URL="postgres://bubba:bubba@localhost/stellar?sslmode=disable"
export STELLAR_CORE_URL="http://bubba:bubba@localhost:11626"

I have no idea what I'm doing.  A better setup tutorial would help for noobs.

Thanks

**Comment by dulanov** [comment]
Just try `http://192.168.133.106:8000')` instead. Or you try to use it in production env?

**Comment by sgehrman** [comment]
I tried that and horizon complained about connecting to not secure server or something, will try again if you need an exact error message.

**Comment by dulanov** [comment]
`new StellarSdk.Server('https://192.168.133.106:8000', opts = {allowHttp: true})` or config SSL certificates for Horizon if you really need SSL.

**Comment by sgehrman** [comment]
@dulanov  
I got things working, but now I put up a live server with SSL.  Now getting ERR_SSL_PROTOCOL_ERROR on this server.  You mentioned config for horizon for SSL?  How do I do this?  Do I just need to set all the http:// to https: in the config files?  I also set it to require SSL, so not sure if this redirect to https is the problem. I installed a Let's Encrypt cert and that was one of the options. 

Thanks

**Comment by dulanov** [comment]
Yes, simply try to rewrite it to `https://` and remove `opts={allowHttp: true}`.

**Comment by sgehrman** [comment]
I did set the https in my client app and did remove those opts.  Does the server configs need to change?

**Comment by sgehrman** [comment]
https://stellarkit.io:8000 if you want to try it, it's on testnet

**Comment by dulanov** [comment]
Right now it doesn't work, did you configure horizon according this instructions - https://github.com/stellar/go/blob/master/services/horizon/internal/docs/developing.md#-enabling-tls-on-your-local-workstation?

**Comment by dulanov** [comment]
> You can simply add --tls-cert tls/server.crt --tls-key tls/server.key to your command line invocations of horizon, or you may specify TLS_CERT and TLS_KEY environment variables.

**Comment by sgehrman** [comment]
Thanks, will try that.  Let me know if there are docs about this so I can read about it.

**Comment by dulanov** [comment]
Also take a look at https://www.stellar.org/developers/horizon/reference/admin.html

**Comment by sgehrman** [comment]
Sorry for being a noob.  I don't get it.  I'm running the docker container.  I don't know what TLS is exactly.  Do I run this script on my server?  Where is this script? What is the new cert that gets created? Do I need to bash into my docker and change stuff in there?
