### ISSUE TITLE
Horizon experimental ingest never completes

### ISSUE THREAD

**Issue by patrickxb** [stellar/go#1673]
I've tried `ENABLE_EXPERIMENTAL_INGESTION=true` three times now on two different servers and it has never completed.  They are m5.large aws instances, not in docker.

```
Aug 28 19:29:54 ip-10-0-7-153 stellar-horizon[23058]: time="2019-08-28T19:29:54.476Z" level=info msg="Processing entries from History Archive Snapshot" numEntries=2400000 pid=23058 sequence=25555199 service=expingest
Aug 28 19:31:20 ip-10-0-7-153 stellar-horizon[23058]: time="2019-08-28T19:31:20.763Z" level=info msg="Processing entries from History Archive Snapshot" numEntries=2500000 pid=23058 sequence=25555199 service=expingest
```

That is the last line in the log file for expingest, it has been 21 hours since then and no expingest activity.  This is the second attempt, but the original attempt stopped at exactly the same place.  The process 23058 did not crash and is still running.

I had to turn off ENABLE_EXPERIMENTAL_INGESTION because with it on, `/paths` is disabled and thus path payments are disabled, but we need it on to fix several issues with path payments:

https://github.com/stellar/go/issues/1496
https://github.com/stellar/go/issues/1128

**Comment by marcinx** [comment]
Try with 0.20.1. It ingests via memory and takes about an hour on Horizon with full history. On 0.20.0 it ran for 3 days and did not finish.

**Comment by bartekn** [comment]
@patrickxb this is probably the case. Please upgrade to 0.20.1 and try again. I have a PR ready that updates CHANGELOG to inform about 0.20.0 issue: https://github.com/stellar/go/pull/1674.

**Comment by ire-and-curses** [comment]
Also we just wrote this short guide for trying out the new ingestion: https://github.com/stellar/go/blob/master/services/horizon/internal/expingest/BETA_TESTING.md

Please raise issues if there's anything unclear or missing. It's hard for us to replicate the experience of an external dev so your feedback is appreciated!

**Comment by ire-and-curses** [comment]
Does this work for you now @patrickxb?
