### ISSUE TITLE
expingest: test ingested state on every ledger checkpoint

### ISSUE THREAD

**Issue by ire-and-curses** [stellar/go#1687]
#1677 adds support for occasional checking of ingested data on commit. However, to really prove this, ledger state needs to be validated against stellar-core on every checkpoint ledger (see discussion in #1677). We should find a way to run the work of #1550 routinely for every new ledger. The process should raise an alert if any discrepancy is found.

- [ ] Identify a simple way to run the ledger check routinely
- [ ] Confirm the check is hitting every ledger
- [ ] Raise an alert if any check fails
- [ ] Store info about the failed run for later inspection (ledger seqnum, git commit ID)

**Comment by ire-and-curses** [comment]
https://github.com/stellar/go/pull/1677#issuecomment-526670173 - This could be implemented as a Kubernetes cron job.

**Comment by bartekn** [comment]
> ledger state needs to be validated against stellar-core on every ledger

Every *checkpoint* ledger.

> Store info about the failed run for later inspection

We don't anything more than ledger sequence and git commit id as it should be reproducible on dev machine.

Other than that sounds great!

**Comment by ire-and-curses** [comment]
Thanks, updated :+1:

**Comment by ire-and-curses** [comment]
@tamirms thanks for implementing this! Did we add the doc we discussed yet or are you tracking that separately?

**Comment by bartekn** [comment]
Just wanted to confirm if we have alerting enabled to check if the script is running and also if we do the same thing for testnet (in case of protocol upgrade involving buckets, briefly discussed this with @tamirms some time ago).

**Comment by tamirms** [comment]
@ire-and-curses yes, I write a doc about the ingestion alert and it is included in the survival guide

@bartekn there are no alerts which check that the script is active. once https://github.com/stellar/go/pull/1779#issuecomment-535403171 is resolved we can add alerts for that.

The job is currently running against mainnet only. I'll work on scheduling a separate job for test net
