### ISSUE TITLE
Go dep ensure fails

### ISSUE THREAD

**Issue by jaglinux** [stellar/go#1690]
Tried on Windows and Linux systems, failed at same location.
Command : dep ensure -v
(24/101) Failed to write github.com/klauspost/crc32@v1.1
grouped write of manifest, lock and vendor: error while writing out vendor tree: failed to write dep tree: failed to export bitbucket.org/ww/goautoneg:
        (1) hg is not installed:
        (2) hg is not installed:
        (3) hg is not installed:
        (4) failed to list versions for https://bitbucket.org/ww/goautoneg: remote: Mercurial (hg) is required to use this repository.
remote:
remote: https://confluence.atlassian.com/x/vLRCMw
fatal: unable to access 'https://bitbucket.org/ww/goautoneg/': The requested URL returned error: 405
: exit status 128
        (5) failed to list versions for ssh://git@bitbucket.org/ww/goautoneg: ssh_exchange_identification: read: Connection reset by peer
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
: exit status 128
        (6) failed to list versions for git://bitbucket.org/ww/goautoneg: fatal: unable to connect to bitbucket.org:
bitbucket.org[0: 18.205.93.2]: errno=No such file or directory
bitbucket.org[1: 18.205.93.1]: errno=No such file or directory
bitbucket.org[2: 18.205.93.0]: errno=No such file or directory

: exit status 128
        (7) failed to list versions for http://bitbucket.org/ww/goautoneg: remote: Mercurial (hg) is required to use this repository.
remote:
remote: https://confluence.atlassian.com/x/vLRCMw
fatal: unable to access 'http://bitbucket.org/ww/goautoneg/': The requested URL returned error: 405
: exit status 128

**Comment by ire-and-curses** [comment]
If you are using an older release that uses `go dep`, please install Mercurial first, as explained in the README associated with that release. We switched today to using Go modules, not `go dep`, so if you are using the current version of the repository, please refer to the current [README](https://github.com/stellar/go).
