### ISSUE TITLE
Implement ledger DB processor

### ISSUE THREAD

**Issue by tamirms** [stellar/go#1708]
We need to populate ledgers in horizon using the new experimental ingestion system. This will allow us to port the following endpoints to be compatible with the new ingestion system:

`/ledgers`
`/ledgers/{ledger_id}`

**Comment by ire-and-curses** [comment]
Adding this as a stretch goal to Horizon 0.23 milestone.

**Comment by tamirms** [comment]
implemented in https://github.com/stellar/go/pull/1949
