### ISSUE TITLE
Implement transactions DB processor

### ISSUE THREAD

**Issue by tamirms** [stellar/go#1711]
We need to populate transaction data in horizon using the new experimental ingestion system. This will allow us to port the following endpoints to be compatible with the new ingestion system:

`/transactions`
`/transactions/{tx_id}`
`/ledgers/transactions`
`/accounts/{account_id}/transactions`

This work is part of #1577.

**Comment by bartekn** [comment]
While working on this please make sure to use [`BatchInsertBuilder`](https://godoc.org/github.com/stellar/go/support/db#BatchInsertBuilder). Without it processing will be too slow for large ledger (we experience this in the old ingestion).

**Comment by tamirms** [comment]
fixed in https://github.com/stellar/go/pull/2037
