### ISSUE TITLE
Compare local state with stellar-core state in actions

### ISSUE THREAD

**Issue by bartekn** [stellar/go#1726]
As a security precaution compare ledger entries with the state in stellar-core in in actions code.

This is another issue (#1723 #1607 #1550) to make sure state in Horizon is correct. We may need to remove this check in a future but it's essential while new ingestion system is still experimental.

**Comment by ire-and-curses** [comment]
What are we comparing? Ledger hash? What will we do if there's a discrepancy? I'm thinking we should log an error and make sure we're alerted.

**Comment by bartekn** [comment]
I briefly explained it in https://github.com/stellar/go/issues/1766. We need to compare values (entier ledger entry, ex. account) in Horizon DB and stellar-core DB. If there's a difference and last updated ledger fields are the same it means there's a bug. In such case we should emit `error` message and mark state as invalid (`exp_state_invalid` flag) that will lock access to state endpoint.

**Comment by bartekn** [comment]
Closed in #1868. We can reopen if it's useful for any other endpoint.
