### ISSUE TITLE
Horizon infinite ingestion

### ISSUE THREAD

**Issue by mahansky** [stellar/go#173]
My Horizon instance ingests ledgers 1-639016 and then it does nothing (?).
It stops at `"history_latest_ledger": 639016` everytime I try it.
I tried running `horizon db reap`, `horizon db clear`, tried dropping all tables and running init again..
Horizon outputs this line again and again (even when "stuck") 
`time="abc" level=info msg="ingest: already in progress" pid=abc`
Server's resources are used the same as when the ingestion works fine (from 1-639016) so it's doing something.
I had it running for 3 days and it didnt change. 
```
"horizon_version": "v0.11.1-dirty",
"core_version": "v0.6.3-dirty",
"history_latest_ledger": 639016,
"history_elder_ledger": 1,
"core_latest_ledger": 14706658,
"core_elder_ledger": 1,
```

**Comment by bartekn** [comment]
Probably the core node lost track of consensus.
