### ISSUE TITLE
Remove misleading [Go SDK] title from horizon docs

### ISSUE THREAD

**Issue by msfeldstein** [stellar/go#1741]
https://www.stellar.org/developers/horizon/reference/

This page has [Go SDK] in the title and in the header of the page, but its about horizon, not necessarily the Go SDK.  It has examples for Go, Javascript, and Java, as well as basic REST endpoint info for horizon.  It's misleading to title it Go SDK even though horizon technically lives in the Go Repo
<img width="1069" alt="Screenshot 2019-09-11 at 3 36 55 PM" src="https://user-images.githubusercontent.com/161135/64740374-02eb1380-d4aa-11e9-918d-a12891d29e09.png">

**Comment by leighmcculloch** [comment]
This is no longer an issue. The docs were redesigned and don't have the Go SDK at the top of the rest page.
