### ISSUE TITLE
Automate query params parsing and validation using query structs.

### ISSUE THREAD

**Issue by abuiles** [stellar/go#1748]
As part of #1606, where we defined a new way to handle actions and routes, we talked about how to do automatic query params parsing and validation.  

Instead of having something like this:

https://github.com/stellar/go/blob/30048098dbf638553496eab489f741e066c29fab/services/horizon/internal/actions/offer.go#L28-L48

We should be able to define a struct roughly like the following:

```go
type OffersPageRequest struct {
  Cursor int64 `name:"cursor", validate:"cursor"`
  Limit int `name:"limit", validate:"limit"`
  Order Order `name:"order", validate:"order"`
  SellerID xdr.AccountId `name:"seller_id"`
  Selling xdr.Asset `prefix:"selling_"`
  Buying xdr.Asset `prefix:"buying"`
}
```

And then have each field pulled and validated automatically from the request. 

@bartekn suggested looking at https://godoc.org/github.com/google/go-querystring/query, we'll have to do some more research do add validation.

**Comment by bartekn** [comment]
We use github.com/asaskevich/govalidator for validation in the bridge server. It's possible to write custom validators.

**Comment by abuiles** [comment]
Fixed here https://github.com/stellar/go/pull/1755
