### ISSUE TITLE
services/keystore: encrypt encrypted keysBlob when stored

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/go#1758]
### Context
In [keystore](https://github.com/stellar/go/tree/7b83a490a2fd0d8df64d578fa9ed26eb5c5cbc39/services/keystore) the client is responsible for encrypting the keys and provides the keys already encrypted in the [keysBlob](https://github.com/stellar/go/blob/7b83a490a2fd0d8df64d578fa9ed26eb5c5cbc39/services/keystore/spec.md#encrypted-keys-data) field to the server. The keystore itself doesn't do any encryption or protection of the user data `keysBlob`.

### Problem
The rng and encryption libraries of the client are expected to be sufficient, but the server can't make any guarantees about this. The keystore should be ensuring the data is stored securely regardless of how well the client has been positioned to do so.

### Solution
We could classify the input `keysBlob` data from the client as if it is plain text sensitive data and have keystore encrypt it with keys managed in a HSM/KMS, that the operations team managing the deployment of keystore have control over maintaining.

### Other impacts
Normally we'd want to rotate keys on some fixed period as well, but because every key is  encrypted with a theoretically unique passphrase+salt I'm not sure if that is necessary in a practical sense, at least until such time as a passphrase or the encryption algorithm is known compromised. This would as a bonus make it possible for us to guarantee the data we are storing in the keystore is always being protected using the currently recommended algorithm and give us the ability to rotate the algorithm used on the backend even if frontends lag behind or don't have the capability to rotate the encrypted blob onto using new algorithms.

Downsides of doing this are that it complicates deployment of the service.

**Comment by leighmcculloch** [comment]
@stanford-scs Do you have any thoughts on this?

**Comment by leighmcculloch** [comment]
@howardtw @shanzzam @accordeiro This is something I think we'd want to do if we were going to use keystore, but given that we aren't using keystore we should probably close it. What do you think?

**Comment by howardtw** [comment]
Yep I agree that we probably shouldn't spend time on Keystore until we find an increasing adoption of it by wallets out there. 👍
