### ISSUE TITLE
Implement /assets endpoint using experimental ingestion

### ISSUE THREAD

**Issue by bartekn** [stellar/go#1765]
Here's the initial idea how to build it using `expingest`:
* We create a new state processor that saves trust lines to Horizon DB. We may need to split `DatabaseProcessor` into multiple processors sharing the same DB transaction as it's getting too big. When updating DB is done it creates aggregations and saves them to another table.
* We create a new ledger processor that updates trust lines in Horizon DB using txmeta. We may finally use [`pipeline.Store`](https://godoc.org/github.com/stellar/go/exp/support/pipeline#Store) to forward assets that have changed to the next processor that will aggregate data for these assets only.
* Trust lines table will be also useful for #442.

**Comment by tamirms** [comment]
The endpoint is implemented in https://github.com/stellar/go/pull/1824 . However, the PR depends on https://github.com/stellar/go/pull/1810 and https://github.com/stellar/go/pull/1819 . Once both those PRs are merged, https://github.com/stellar/go/pull/1824 can be reviewed and merged

**Comment by bartekn** [comment]
Closed in #1824.
