### ISSUE TITLE
Update txnbuild to support stellar-core v12 (part 1 or 2)

### ISSUE THREAD

**Issue by ire-and-curses** [stellar/go#1771]
Before v12 vote:
- [ ] Add deprecation warning to `txnbuild` to indicate that the existing `PathPayment` operation will be renamed to `PathPaymentStrictReceive` in a few  weeks' time
- [ ] Add new operation `PathPaymentStrictReceive` to SDK, duplicating existing `PathPayment` operation. Programmers can begin moving client calls immediately
- [ ] Raise corresponding build issues for other SDKs (including JS and Java)
- [ ] Update Godoc and examples
- [ ] Release

This is part of #1737.

**Comment by bartekn** [comment]
Partially closed in #1776. We still need to add deprecation warnings and check if godoc looks good.
