### ISSUE TITLE
Update Horizon to support stellar-core v12

### ISSUE THREAD

**Issue by ire-and-curses** [stellar/go#1772]
Before v12 vote:
- [ ] Note deprecation of returned type in `\operations` and `\payments` source code
- [x] Update the XDR library in the monorepo with the v12 definition files from `stellar-core`
- [x] Update Horizon to map incoming new types to `path_payment`. Continue to accept old `path_payment` type
- [ ] Update documentation for [operation types](https://www.stellar.org/developers/horizon/reference/resources/operation.html) - indicate that response may not match underlying operation, and mention both old and new operation names
- [ ] Note deprecation in release notes. Schedule to start returning `path_payment_strict_receive` and `path_payment_strict_send` in `type` field in two releases time (Horizon 0.24)
- [ ] Release

This is part of #1737.

**Comment by bartekn** [comment]
In progress in: https://github.com/stellar/go/pull/1776
