### ISSUE TITLE
Update txnbuild to support stellar-core 12 (part 2 of 2)

### ISSUE THREAD

**Issue by ire-and-curses** [stellar/go#1773]
After v12 vote:
- [ ] Release new operation `PathPaymentStrictSend` to SDK, implementing new v12 operation

This is part of #1737.

**Comment by bartekn** [comment]
In progress in: https://github.com/stellar/go/pull/1776

**Comment by bartekn** [comment]
I realized that this is split into 2 issues. Maybe we can merge this into #1771. I think we can do everything at once:
- Add `PathPaymentStrictSend` (devs should be able to create ops before v12 for testing).
- Create `PathPaymentStrictReceive` that is an alias for `PathPayment` (done in #1776 as explained in #1771).
- Remove `PathPayment` after deprecation time.

**Comment by ire-and-curses** [comment]
@bartekn we can discuss again if you feel strongly, but in the last discussion we converged on doing this in two steps, and delaying the new operation, because a user calling the new operation would have a bad experience until the vote happens (and it wouldn't be clear why).

**Comment by bartekn** [comment]
OK, we can talk tomorrow, maybe I misunderstand something.

**Comment by ire-and-curses** [comment]
After internal discussion we agree. Let's merge these and release all together, so that developers can try the new operations out on testnet prior to the pubnet rollout.
