### ISSUE TITLE
Documentation about horizon.Error.Problem

### ISSUE THREAD

**Issue by oelmekki** [stellar/go#1787]
Hi guys,

When using the horizonclient go package (with `Client.SubmitTransactionXDR`), I sometimes get the error:

```
horizon error: "Transaction Failed" - check horizon.Error.Problem for more information
```

Maybe I missed something obvious, but looking at both documentation and source code, I just can't find how I'm supposed to do that. The error returned by `SubmitTransactionXDR` is just a standard go error type, without a `Problem` field, I can't find `Error.Problem` constants neither in `horizonclient` nor `protocol/horizon`, and I don't find anything else I could check.

Could you give an example about how we're supposed to check for error details?

Thanks!

**Comment by ire-and-curses** [comment]
Returned error type should be [`horizonclient.Error`](https://godoc.org/github.com/stellar/go/clients/horizonclient#Error). Then you can use the provided helper methods to get details of what happened.

If that's not what you're seeing, please provide a minimal example code that repros the problem and we'll take a look.

**Comment by oelmekki** [comment]
Hi,

Thanks for your time!

Here is [an example](https://gist.github.com/cc389a9a1c272428787685f6896733c4).

It wouldn't run for several reasons like missing source account or bogus
secret key, but it doesn't matter, it doesn't compile because of the
problem I want to show. If I try to build it, I get the error:

```
$ go build main.go 
./main.go:47:7: herr.ResultString undefined (type error has no field or method ResultString)
```

If I try [to force it](https://gist.github.com/ef4dcf0a450a102f6dbce4e6e56ad3a3) to `horizonclient.Error` type, I get:

```
$ go build main2.go 
./main2.go:46:10: cannot assign error to herr (type horizonclient.Error) in multiple assignment: need type assertion
./main2.go:47:10: cannot convert nil to type horizonclient.Error
```

And indeed,
[SubmitTransactionXDR](https://github.com/stellar/go/blob/4775aaf681c170bc33e6fc1e4b5b68e60bf87f30/clients/horizonclient/client.go#L361) is returning a standard `error` type. Am I missing something?

**Comment by ire-and-curses** [comment]
I agree it's not the clearest interface. Usually the returned error will be subtyped, but the signature is a more general interface, so it's left to documentation to tell you what to expect. The [godoc](https://godoc.org/github.com/stellar/go/clients/horizonclient#Client.SubmitTransactionXDR) for the method mentions what can be returned:

>  SubmitTransactionXDR submits a transaction represented as a base64 XDR string to the network. err can be either error object or horizon.Error object.

The correct way to use this is to check the type and then take appropriate action. Using your example, something like this works:

```golang
	_, herr := client.SubmitTransactionXDR(xdr)
	if herr != nil {
		if herr2, ok := herr.(*horizonclient.Error); ok {
			fmt.Println("Error has additional info")
			fmt.Println(herr2.ResultCodes())
			fmt.Println(herr2.ResultString())
			fmt.Println(herr2.Problem)
		}
		return
	}
```

This type assertion pattern is a standard error approach (see e.g. the [Go blog](https://blog.golang.org/error-handling-and-go)).
