### ISSUE TITLE
Separate tests explicitly into unittests and integration tests

### ISSUE THREAD

**Issue by ghost** [stellar/go#179]
My general idea is to separately run generic unittests and only by demand or by CI also integration tests which should depend explicitly on some `Dockerfile` with pre-configurated mysql and redis env. Build tags can be used to control which tests to run - `// +build integration` and then `go test -tags=integration` or simply separate via [short mode](http://golang.org/pkg/testing/#Short) because:

> write all tests normally. if it is a long-running tests, or an integration test, follow this naming convention and check for -short to be nice to your peers.

**Comment by 2opremio** [comment]
We implemented separate integration tests a while ago ( #2916 )
