### ISSUE TITLE
Send latest ingested ledger sequence in HTTP response header

### ISSUE THREAD

**Issue by bartekn** [stellar/go#1791]
`horizon-cmp` returns a lot of diff results that are simply there because the requests are processed at different ledgers. Would be great if Horizon sent a `Latest-Ledger` (name TBD) header with a sequence number of the last processed ledger. This would allow to quickly check if the diff is because of a bug or not. The header can be sent for new ingestion endpoints only.

This change requires to start a `REPEATABLE READ, READ ONLY` transaction because a new ledger can be processed between reading ledger sequence and actual results. This can be done in a middleware that starts and rollbacks a transaction. In the future it can be helpful for processing batch requests.

PS. added to Horizon 0.22.0 milestone because the change is rather simple.

**Comment by ire-and-curses** [comment]
With this change, we would ignore these fake diffs. If I understand correctly in this situation we also don't validate the endpoint output, whether we make the change or not, because to validate we need the same ledger from both sides of the diff.

Should we consider changing `horizon-cmp` to track specific ledgers from the first server, and then ask for those same ledger IDs on the second server?

**Comment by bartekn** [comment]
> With this change, we would ignore these fake diffs. If I understand correctly in this situation we also don't validate the endpoint output, whether we make the change or not, because to validate we need the same ledger from both sides of the diff. So it seems like there's a gap in our testing.

Not really, it will largely decrease number of false positives. This change protects from generating a diff in a very short time window when servers are on different ledgers:
```
   A: ledger 1       A: ledger 2         A: ledger 3 
 ----------------|-------------------|-----------------|----

   B: ledger 1            B: ledger 2         B: ledger 3 
 --------------------|-------------------|-----------------|----

                 |---|               |---|             |---|

Different ledgers ^^^                 ^^^               ^^^
```

We can still save them but ex. in a different folder to focus more on real differences. If something like this happens we can retry the same path after a few seconds.

> Should we consider changing horizon-cmp to track specific ledgers from the first server, and then ask for those same ledger IDs on the second server?

This is not so easy when you request state endpoints and history endpoints with `order=desc&cursor=now` and `order=asc&cursor={some_recent_cursor}` because when new ledger is ingested on one server on not on the other the response will be different.

**Comment by ire-and-curses** [comment]
If we're retrying the same path after a few seconds then I agree there's no issue.

**Comment by tamirms** [comment]
fixed in https://github.com/stellar/go/pull/1830

**Comment by bartekn** [comment]
I realized that we should not do it for streaming endpoints. In repeatable read tx changes to the DB will not be visible so basically streaming is broken now.

**Comment by bartekn** [comment]
Opened a new issue instead: https://github.com/stellar/go/issues/1864.
