### ISSUE TITLE
Add a CLA bot

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/go#1798]
The process for accepting contributions with our existing CLA being completed via a Google Form requires someone from @stellar/platform-committers to check that the person has signed the CLA, and to manually ask.

It's a much better experience if humans aren't involved in these things, and if the CLA is checked and requested immediately when the contributor opens their PR, it closes the loop fast.

A CLA bot could also label PRs as `cla: required` and `cla: ok` to make it really clear if PRs are good to go or not.

**Comment by leighmcculloch** [comment]
FYI @tomquisel @ire-and-curses I believe you will have thoughts on this.

**Comment by ire-and-curses** [comment]
This sounds fantastic to me!

**Comment by leighmcculloch** [comment]
There are two GitHub Apps that offer CLA checking:
- https://github.com/cla-assistant/cla-assistant
- https://github.com/apps/cla-bot

There are many we can host ourselves:
- https://github.com/clabot/clabot

A lot of companies also roll their own, because it is also a very simple app to build and host, so that's also an option, and I'd be happy to pick that up in a future sprint.

However, before we go to the effort of rolling our own we might want to try an existing solution.

The [clabot](https://github.com/apps/cla-bot) app keeps the list of signers in a repository which I think is really simple and it means we can easily access it without the list being locked away in someone elses database, so I suggest we give it a go. The repo where that list lives can be private if needed, and it can live in one repository and be shared by all our other repositories.

**Comment by leighmcculloch** [comment]
Closing because we have a CLA bot, even though it has some rough edges.
