### ISSUE TITLE
Remove `transaction.fee_paid` field

### ISSUE THREAD

**Issue by bartekn** [stellar/go#1812]
From CHANGELOG:
* `fee_paid` field on Transaction resource has been deprecated and will be removed in 0.23.0 (previously scheduled for 0.22.0). Please use new fields added in 0.18.0: `max_fee` that defines the maximum fee the source account is willing to pay and `fee_charged` that defines the fee that was actually paid for a transaction. See [CAP-0005](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0005.md) for more information.

**Comment by bartekn** [comment]
Closed in #1828.

**Comment by tamirms** [comment]
fixed in https://github.com/stellar/go/pull/2126/files
