### ISSUE TITLE
No testnet for Horizon v0.22.0

### ISSUE THREAD

**Issue by g574** [stellar/go#1820]
Hello,
there is a [new Horizon releases with breaking changes](https://github.com/stellar/go/releases/tag/horizon-v0.22.0) however the [testnet](https://horizon-testnet.stellar.org/) is still on v0.20.0.
Is there another testnet with v0.22.0 or would you be able to upgrade?

Many thanks.

**Comment by bartekn** [comment]
Horizon 0.22.0 does not contain breaking change, it adds support for Stellar Protocol v12 but it's not a breaking change. Test network will be upgraded to v12 on Monday, we will deploy Horizon by then.
