### ISSUE TITLE
Horizon should not have a strong affinity to stellar-core

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/go#183]
One of the things I noticed in how Horizon is configured and designed is that it wants to have a dedicated core instance.

While this is fine for development, we probably want to fix this such that we can:
 * scale horizon servers independently from core servers (we should be able to have more horizon servers than core servers and the opposite), which allows to load balance horizon queries across all core instances
    * this also takes care of a problem with the current implementation that makes it impossible to switch over to a different core instance as other instances don't necessarily keep the right data around.
 * not have horizon instances fail when its core instance dies (so increased availability)

The good news is that core already supports this:
we don't have a limit on the number of "cursors" used to keep track of which historical data can be deleted (we basically keep around data down to the smallest cursor), so having a cursor per horizon instance should be the only change needed from a data retention point of view (ie, instead of using `HORIZON`, use something like `HORIZON001` for node 001).

There are a few subtle things here that needs to happen to ensure that cursors are setup and updated correctly, in particular each Horizon instance must round-robin between instances to ensure that the cursor is updated on all core instances over time.

For the transaction layer, there might be a few differences:
it will work pretty much the same way as transactions are flooded between core instances (so submitting a transaction to a node and re-submitting or querying a different node a few seconds later should yield the same result) - but injecting transactions rapidly may yield a different result than today (bad seq num) - the simplest approach here might be to have stickier connections to the core instances (for the HTTP layer), ie only switch to a different machine when there is a problem.

**Comment by oryband** [comment]
Hey @MonsieurNicolas @bartekn . I'm gonig to tackle this and submit a PR soon.

**Comment by bartekn** [comment]
We released [Horizon 1.6.0](https://github.com/stellar/go/releases/tag/horizon-v1.6.0) which adds an experimental feature for Captive Stellar-Core that solves the issues described in this issue. It's still not production ready but I think we can close this.
