### ISSUE TITLE
/offers endpoint not available during state ingestion

### ISSUE THREAD

**Issue by bartekn** [stellar/go#1831]
It looks like `/offers` endpoint it not available during state reingestion. It should display `StillIngesting` error but instead it simply loads indefinitely.

**Comment by bartekn** [comment]
@abuiles since you were working on this, could you check it out?

**Comment by abuiles** [comment]
@bartekn 👍

**Comment by abuiles** [comment]
@bartekn I think this was fixed with https://github.com/stellar/go/pull/1847 --  @tamirms can you confirm?

**Comment by bartekn** [comment]
I've just checked it locally it works. Yes, it seems that #1847 fixed this.
