### ISSUE TITLE
pq error in DatabaseProcessor

### ISSUE THREAD

**Issue by bartekn** [stellar/go#1836]
When testing #1819 rebased onto `release-horizon-v0.23.0` locally I see one of the errors below:
```
Processor DatabaseProcessor (Offers) errored: Error in processLedgerOffers: exec failed: driver: bad connection
```
```
Error running post-hook: Processor DatabaseProcessor (Accounts) errored: Error in processLedgerAccounts: exec failed: pq: unexpected Parse response 'C'
```
```
Error running post-hook: Processor DatabaseProcessor (Accounts) errored: Error in processLedgerAccounts: exec failed: pq: unexpected Parse response 'D'
```
I checked the code and I think it can be connected to https://github.com/stellar/go/commit/6c29c3181416c97004b14bfb638431fe8d1f1aa6 where we read rows connected to asset stats in the DB transaction while inserting/updating/deleting rows. So it's basically a concurrency issue. Issues related to this I was able to find: https://github.com/lib/pq/issues/81, https://github.com/lib/pq/issues/635.

It looks like it's actually due to postgres protocol design so possible fixes are basically not getting data while updating DB:
- Moving `SELECT` to the stage when DB writes are done.
- Adding `RWMutex` on `DatabaseProcessor` so reading does not interfere with writing.

Assigning to @tamirms as he's the author of https://github.com/stellar/go/commit/6c29c3181416c97004b14bfb638431fe8d1f1aa6 and adding P1 tag as the ingestion pipeline doesn't work. We need to fix this before releasing Horizon 0.23.0.

**Comment by tamirms** [comment]
fixed by https://github.com/stellar/go/pull/1837
