### ISSUE TITLE
ignore autogenerated sql & bindata files

### ISSUE THREAD

**Issue by nikhilsaraf** [stellar/go#184]
bindata.go
all autogenerated .sql files from .rb files

these are polluting code reviews and we need a nice way to handle this.

some context:
we don't want to autogenerate this based on scripts because it's expensive and won't let travis complete in time.

alternative is to use a zip file when it's generated so it shows up as only 1 file in code reviews and travis can just unzip it.

**Comment by tomerweller** [comment]
- agreed 
- generating test scenarios as part of the general build will also ensure that it isn't broken. right now, test generation can be broken and we won't know about it until someone makes a change to the schema.

**Comment by tomquisel** [comment]
Closing this since there are more recent conversations on it. like #827
