### ISSUE TITLE
Revisit Ingestion workflow to preload asset data

### ISSUE THREAD

**Issue by nikhilsaraf** [stellar/go#185]
applies to history_assets and asset_stats

we should preload the assets tables at the beginning of ingestion so the lazy loading of assets happens once and in bulk. Following from that, whenever we perform the asset stats queries we will have data for the corresponding asset and can therefore do these stats queries in bulk to make them more efficient on the db.

Additionally as part of this change, we should consider having an order-preserving id hash as the primary key on the history_assets that can be used by external tables like asset_stats and also used for sorting on that key value.
see this for an example of such a hash algorithm: http://cmph.sourceforge.net/chm.html

**Comment by bartekn** [comment]
Fixed in the new ingestion system.
