### ISSUE TITLE
[Hubble] Create a script that efficiently reads history archives into intermediate storage

### ISSUE THREAD

**Issue by debnil** [stellar/go#1850]
To enable better data analytics over the history of the network, we want to efficiently read from history archives into some intermediate storage (i.e., Postgres).

**Comment by nikhilsaraf** [comment]
Once the spike is complete (#1851), we can start pulling data from archives and pushing it to our chosen datastore (streaming).

**Comment by nikhilsaraf** [comment]
@debnil adding some more definition to this task. Feel free to break it out into smaller tasks as you see fit. 

## What to do
- [ ] Pull state data from history archives into Postgres
- [ ] Pull ledger data from history archives into Postgres
- [ ] Dutiful logging for items such as IDs, hashes, timing, number of files, etc.
## Possible tools to be used
- new horizon ingestion system primitives
- only use standardized SQL for easy portability
## Required Testing
- [ ] a specific ledger state is pulled correctly
- [ ] transactions from a specific ledger are pulled correctly
- [ ] re-running a state job is idempotent
- [ ] re-running a ledger job is idempotent
- [ ] more tests as needed
## Deliverables
- [ ] single well-tested Golang binary that takes configuration inputs from the command line (archive URL, postgres URL, etc.) and performs the tasks described above.

**Comment by debnil** [comment]
Closing due to changes in our approach to data analytics
