### ISSUE TITLE
Strict-send pathfinder returns non-existent paths.

### ISSUE THREAD

**Issue by marcinx** [stellar/go#1856]
**Describe the bug**
Horizon returns non-existent paths on `/paths/strict-send`. 

Have a look at https://horizon.stellar.org/paths/strict-send?destination_account=GASKYWPPQ2VSO6KNIPIRVXMSSDGZLYZQ67CDTLVXOXYDG26SPZ66EDCQ&source_asset_type=credit_alphanum4&source_asset_code=EUR&source_asset_issuer=GA4ARTT4HG4MYFFA3JJIVWLGE53PAHMKDBCBCNRHCSIR3KZP5BVNNTD6&source_amount=6.14

Amongst other non-existent paths it returns:
```
      {
        "source_asset_type": "credit_alphanum4",
        "source_asset_code": "EUR",
        "source_asset_issuer": "GA4ARTT4HG4MYFFA3JJIVWLGE53PAHMKDBCBCNRHCSIR3KZP5BVNNTD6",
        "source_amount": "6.1400000",
        "destination_asset_type": "native",
        "destination_amount": "1174.3516812",
        "path": [
          {
            "asset_type": "credit_alphanum4",
            "asset_code": "USD",
            "asset_issuer": "GDSRCV5VTM3U7Y3L6DFRP3PEGBNQMGOWSRTGSBWX6Z3H6C7JHRI4XFJP"
          },
          {
            "asset_type": "credit_alphanum4",
            "asset_code": "ETH",
            "asset_issuer": "GBVOL67TMUQBGL4TZYNMY3ZQ5WGQYFPFD5VJRWXR72VA33VFNL225PL5"
          },
          {
            "asset_type": "credit_alphanum4",
            "asset_code": "NGNT",
            "asset_issuer": "GAWODAROMJ33V5YDFY3NPYTHVYQG7MJXVJ2ND3AOGIHYRWINES6ACCPD"
          }
        ]
      }
```

When trying to execute a strict-send payment with this path and the `destinationMin` set to `1174.3516812 * 0.99` it returns `op_too_few_offers`.

**What version are you on?**
v0.22.1

**To Reproduce**
Fetch best paths per asset as given by `/paths/strict-send` and try to execute strict-send payments with the given destinationAmount (minus padding). 

**Expected behavior**
Horizon should return existent paths only.

**Additional context**
Tried several paths given by `/paths/strict-send`, which seemed abnormally high and ran into `op_too_few_offers` every time. 

When a path depth/length of 5 is used on Horizon (instead of the default 4, as on e.g. horizon.stellar.org) even more non-existent paths with astronomical "profits" are returned. 

@bartekn @tamirms @tomquisel

**Comment by marcinx** [comment]
When a --max-path-length=5 is used, then Horizon returns "even better" non-existent paths with up to 19378 XLM for 6.14 EUR.

```
      {
        "source_asset_type": "credit_alphanum4",
        "source_asset_code": "EUR",
        "source_asset_issuer": "GA4ARTT4HG4MYFFA3JJIVWLGE53PAHMKDBCBCNRHCSIR3KZP5BVNNTD6",
        "source_amount": "6.1400000",
        "destination_asset_type": "native",
        "destination_amount": "19378.6001251",
        "path": [
          {
            "asset_type": "credit_alphanum4",
            "asset_code": "USD",
            "asset_issuer": "GDSRCV5VTM3U7Y3L6DFRP3PEGBNQMGOWSRTGSBWX6Z3H6C7JHRI4XFJP"
          },
          {
            "asset_type": "credit_alphanum4",
            "asset_code": "XLMG",
            "asset_issuer": "GCVNN7O5JISPEYUTLK3JYGBDWCPDIHB4MTG4PMSJVIKJCR64NOXWI3YH"
          },
          {
            "asset_type": "credit_alphanum4",
            "asset_code": "BTC",
            "asset_issuer": "GAUTUYY2THLF7SGITDFMXJVYH3LHDSMGEAKSBU267M2K7A3W543CKUEF"
          },
          {
            "asset_type": "credit_alphanum4",
            "asset_code": "BTC",
            "asset_issuer": "GATEMHCCKCY67ZUCKTROYN24ZYT5GK4EQZ65JJLDHKHRUZI3EUEKMTCH"
          }
        ]
      }
```

**Comment by tamirms** [comment]
fixed by https://github.com/stellar/go/pull/1863
