### ISSUE TITLE
when ı connect horizon api ı see conncetion refused error.

### ISSUE THREAD

**Issue by dnzhnshn** [stellar/go#1885]
when ı connect horizon api with stellar/quickstart docker image. 
my comment:

horizon db init --db-url postgres://stellar:123456789@127.0.0.1:5432/core --stellar-core-db-url postgres://stellar:123456789@127.0.0.1:5432/core_stellar  --stellar-core-url http://localhost:11626

and my horizon.env:

export DATABASE_URL="postgres://stellar:123456789@127.0.0.1:5432/core"
export STELLAR_CORE_DATABASE_URL="postgres://stellar:123456789@127.0.0.1:5432/core_stellar"
export STELLAR_CORE_URL="http://localhost:11626"
export LOG_LEVEL="info"
export INGEST="true"

export INGEST_FAILED_TRANSACTIONS="true"
export PER_HOUR_RATE_LIMIT="72000"
export NETWORK_PASSPHRASE="XLMNETWORK"
export DISABLE_ASSET_STATS="true"

command window error:

2019/10/29 13:30:50 connect failed: dial tcp 127.0.0.1:5432: connect: connection refused

help me please.

**Comment by ire-and-curses** [comment]
For support, please ask your question at https://stellar.stackexchange.com/. Looks like you need to fix your postgres permissions.
