### ISSUE TITLE
DatabaseBackend.GetLatestLedgerSequence can crash with "index out of range" error

### ISSUE THREAD

**Issue by bartekn** [stellar/go#1888]
If `SelectRaw` in `DatabaseBackend.GetLatestLedgerSequence` returns no rows it crashes with: 
```
runtime error: index out of range [0] with length 0
```
Check why `SelectRaw` doesn't return `ErrNoRows` in such case.

**Comment by tamirms** [comment]
fixed in https://github.com/stellar/go/pull/1914
