### ISSUE TITLE
Bridge and Compliance binaries are under depracated repo

### ISSUE THREAD

**Issue by gaclaudiu** [stellar/go#1892]
Hi ,
Link to prebuilt binaries of Bridge and Compliance server points to a deprecated repo. 
Example for Bridge : https://github.com/stellar-deprecated/bridge-server/releases . 
I tried to follow the links for downloading the binaries present on : 

- https://github.com/stellar/go/blob/master/services/bridge/README.md 

- https://github.com/stellar/go/blob/master/services/compliance/README.md

I also notice that Federation binaries link points to a correct location (is not depracated). 
Can someone help me out to find the correct location of the binaries for Bridge and Compliance and also fix the readme links ?

**Comment by leighmcculloch** [comment]
@gaclaudiu Thanks for finding those broken links. I've updated both in #1895 and #1896. The bridge and compliance binaries are in the same place as the federation binaries, all on the `stellar/go` repositories releases page.
