### ISSUE TITLE
Update ingestion to support metaV2

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/go#1902]
There is some missing meta in protocol version older than version 10. This impacts transactions with one time signers (that get removed after operations in v9 and earlier; and during signature verification in v10 and later). Those changes are invisible in the meta which may confuse certain ingestion processors that keep track of signers on accounts.

We're adding support for a new version of the meta that allows for changes both preceding (`meta.v2().txChangesBefore` is the same than `meta.v1().txChanges`) and succeeding operation level changes (`meta.v2().txChangesAfter`) in https://github.com/stellar/stellar-core/pull/2315 that will be in build 12.2.0

The meta generation is behind a feature flag (disabled by default) for now in core, to enable the new meta format set in the configuration file:
` SUPPORTED_META_VERSION=2`

**Comment by ire-and-curses** [comment]
Related issue: https://github.com/stellar/stellar-core/issues/2217 (@bartek)

**Comment by bartekn** [comment]
Blocked on https://github.com/stellar/puppet-v4/issues/942.

**Comment by ire-and-curses** [comment]
Now depends on https://github.com/stellar/go/pull/1890

**Comment by bartekn** [comment]
Closed in #2096.
