### ISSUE TITLE
horizon 500 error when submitting a transaction

### ISSUE THREAD

**Issue by TFiroozian** [stellar/go#1903]
I'm trying to submit a transaction using my horizon instance and I get 500 error
I use this horizon https://stellar-horizon.blockeq.com/

![image](https://user-images.githubusercontent.com/30416427/68217419-9162a980-ffb0-11e9-9905-0459e26f9543.png)

Also, I've found this logs for the time I submitted the transaction
``
time="2019-11-04T20:50:47.498Z" level=error msg="failed to submit: json decode failed: invalid character '<' looking for beginning of value" pid=1 req=f186521215ee/Fj2fArF9fJ-090455 stack="[main.go:43 submitter.go:49 system.go:169 system.go:124 actions_transaction.go:44 base.go:185 actions_transaction.go:29 base.go:57 main_generated.go:112 server.go:2007 mux.go:418 server.go:2007 cors.go:190 server.go:2007 compress.go:66 server.go:2007 middleware.go:171 server.go:2007 middleware.go:182 timer.go:212 middleware.go:181 server.go:2007 middleware.go:78 server.go:2007 xff.go:64 server.go:2007 middleware.go:50 server.go:2007 request_id.go:68 server.go:2007 middleware.go:39 server.go:2007]"
``

**Comment by bartekn** [comment]
I think your `STELLAR_CORE_URL` is wrong. Please change it to the HTTP port of stellar-core.
