### ISSUE TITLE
Invalid `ingest-state-reader-temp-set` value:

### ISSUE THREAD

**Issue by SalleryWang** [stellar/go#1904]

**Comment by leighmcculloch** [comment]
Hi @SalleryWang, could you share some details about the flag and environment variable configuration options that are being passed to Horizon on start?

That parameter can be configured with the `--ingest-state-reader-temp-set` flag or the `INGEST_STATE_READER_TEMP_SET` environment variable. It defaults to `memory` but you can set it to `memory` or `postgres`.

**Comment by ire-and-curses** [comment]
Closing as this sounds like user error. See @leighmcculloch's comment for valid choices for this variable.
