### ISSUE TITLE
Support String or Number Unmarshalling in Int64 fields

### ISSUE THREAD

**Issue by abuiles** [stellar/go#1912]
Add `UnmarshalJSON` to the following structs, allowing `string` or `number` where an `Int64` is expected 

- [x] go/protocols/horizon/effects/main.go:260:20:	NewSeq           int64  `json:"new_seq"`
- [x] go/protocols/horizon/operations/main.go:139:10:	OfferID int64 `json:"offer_id"`
- [x] go/protocols/horizon/operations/main.go:146:10:	OfferID int64 `json:"offer_id"`
- [x] go/protocols/horizon/effects/main.go:260:20:	OfferID           int64  `json:"offer_id"`
- [x] go/protocols/horizon/main.go:228:21:	ID                 int64      `json:"id"`
- [x] go/protocols/horizon/main.go:376:16:	Timestamp     int64     `json:"timestamp"`
- [x] go/protocols/horizon/main.go:377:16:	TradeCount    int64     `json:"trade_count"`

**Comment by ire-and-curses** [comment]
This is for the SDK right?

**Comment by abuiles** [comment]
@ire-and-curses no, this is a tracker for https://github.com/stellar/go/pull/1909#pullrequestreview-315809606

**Comment by abuiles** [comment]
@ire-and-curses here's the PR for the js-sdk https://github.com/stellar/js-stellar-sdk/pull/457

**Comment by abuiles** [comment]
This was finished.
