### ISSUE TITLE
"Account for issuer does not exist" in /assets

### ISSUE THREAD

**Issue by bartekn** [stellar/go#1928]
Requesting `/assets?limit=50&asset_code=ETH` for public network Horizon returns `500 Internal Server Error` and error log:
```
Account for issuer GD6G33B7A3TKWCG3TKCIVJTVJGWUWUCMEDHGOOQYSYUMHY76VWJ5Q5IE does not exist
```

I quickly compared core and horizon state tables and it looks like everything is correct. It seems that account can be removed when there are empty trust lines pointing to it. So Horizon should continue populating asset stats response when issuer does not exist.

horizon.stellar.org returns the following for this issuer:
```json
      {
        "_links": {
          "toml": {
            "href": ""
          }
        },
        "asset_type": "credit_alphanum4",
        "asset_code": "ETH",
        "asset_issuer": "GD6G33B7A3TKWCG3TKCIVJTVJGWUWUCMEDHGOOQYSYUMHY76VWJ5Q5IE",
        "paging_token": "ETH_GD6G33B7A3TKWCG3TKCIVJTVJGWUWUCMEDHGOOQYSYUMHY76VWJ5Q5IE_credit_alphanum4",
        "amount": "0.0000000",
        "num_accounts": 7,
        "flags": {
          "auth_required": false,
          "auth_revocable": false,
          "auth_immutable": false
        }
      },
```

Git blame: https://github.com/stellar/go/blame/443af18bbca2d30b4dbe4ed62a5c4d036785aaf7/services/horizon/internal/actions/asset.go#L99

**Comment by tamirms** [comment]
fixed in https://github.com/stellar/go/pull/1930
