### ISSUE TITLE
Disambiguate authorised vs non-authorised trustlines in responses

### ISSUE THREAD

**Issue by ire-and-curses** [stellar/go#1938]
(Spun out from #1933)

There was a [SE question](https://stellar.stackexchange.com/questions/2844/viewing-trustlines-for-authorization-required-assets-from-an-asset-issuer-perspe) yesterday where the author said:

> Ideally I would like to get a list of accounts that are authorized to hold your asset and also a list of accounts that have "applied" for a trustline to hold your asset via Horizon.

We see `num_accounts` in the context of `/assets` ([doc](https://www.stellar.org/developers/horizon/reference/resources/asset.html)), but it's a little ambiguous, since it could refer to either authorised trustlines, non-authorised trustlines, or both. The says

> The number of accounts that: 1) trust this asset and 2) where if the asset has the auth_required flag then the account is authorized to hold the asset.

It would be cool to be able to get both, as they are two distinct use cases.

**Comment by OwenJacob** [comment]
If we can see the number of accounts unauthorized how could we determine the account IDs?

I quite like [this](https://github.com/stellar/go/issues/1933#issuecomment-554444656) which I assume refers to the accounts/?asset=code:issuer endpoint.

The overall objective is for an asset issuer to be able to identify an account that applied for authorization and is still waiting for the allow authorization operation to happen.

Thanks! (If I can lend a hand with the implementation I would be more than happy to!)

**Comment by OwenJacob** [comment]
I've just tested the accounts/?asset=code:issuer endpoint and it can show me who is authorized and who is not authorized to hold an asset

Super work :)

**Comment by ire-and-curses** [comment]
Given that we can iterate over the list to get the info originally requested, I think this is low priority. I'm going to go ahead and close it.
