### ISSUE TITLE
Feature Request: Add `last_modified_time` to account response

### ISSUE THREAD

**Issue by morleyzhi** [stellar/go#1945]
### What problem does your feature solve?
When you bring up an account's information, the account and its balances have `last_modified_ledger` set but not `last_modified_time`:

https://horizon-testnet.stellar.org/accounts/GAX3HE63QELVOSMTPOLCXCOAJ3NOHV5PF6FZCKJ6D63MYPM25DIJBWLP

Whereas, for example, offers come back with both values:

https://horizon-testnet.stellar.org/accounts/GB34PTUQQPYKN7XPWFZCIP77X5ZAEQEB3IN227EHIZFGLUUDS2Y2JVRW/offers

Getting the timestamp directly is more dev-friendly than trying to figure out the timestamp of a given ledger.

### What alternatives are there?

A dev can hit Horizon for ledger information, but that's another roundtrip when the information is readily available. 

We may also be able to model this as a join, but that too seems a little indirect.

**Comment by ire-and-curses** [comment]
We discussed this and agree it's a good idea. We would probably want to add this to all endpoints where we currently have only ledger number.

**Comment by ire-and-curses** [comment]
Discussed this - there's no immediate urgency.

**Comment by ire-and-curses** [comment]
If this is easy let's try and fit it into 0.25 as well, since we're changing a bunch of API at the same time.

**Comment by abuiles** [comment]
👍 also since this is an addition it isn't terrible if it goes post 0.25, the bad ones are when we break things.

**Comment by ire-and-curses** [comment]
An additional question is what to do with endpoints such as `\paths` which don't provide a ledger number. The time when the backend makes the request may be a decent approximation given that a ledger is closed approximately every 5 seconds. On the other hand having the actual ledger timestamp would be both more accurate and allow cross-referencing against other data by ledger number/timestamp, but that's a bigger change.
