### ISSUE TITLE
services/horizon: Index out of range for requests with empty url param

### ISSUE THREAD

**Issue by bartekn** [stellar/go#1965]
### What version are you using?

Horizon 0.23.1

### What did you do?

Request: `/accounts//offers?limit=100`

### What did you expect to see?

No error.

### What did you see instead?

```
runtime.boundsError runtime error: index out of range [0] with length 0
/var/lib/jenkins/jobs/stellar-horizon-public/workspace/services/horizon/internal/actions/helpers.go:612
```

**Comment by abuiles** [comment]
Fixed in #1973
