### ISSUE TITLE
Gap detected error in expingest when shutting down

### ISSUE THREAD

**Issue by bartekn** [stellar/go#1975]
### What version are you using?

Horizon 0.22.2.

### What did you do?

Shutdown Horizon by sending SIGTERM.

### What did you expect to see?

No error.

### What did you see instead?

Error returned from ingest.LiveSession: Gap detected (ledger 26687301 does not exist but 26907134 is latest)

### Logs

Logs (`service=expingest` only):

Time | horizon_msg | horizon_ledger | horizon_type | horizon_err
-- | -- | -- | -- | --
November 21st 2019, 21:40:44.921 | Finished processing ledger | 26907132 | - | -
November 21st 2019, 21:40:44.921 | Processed ledger | 26907132 | ledger_pipeline | -
November 21st 2019, 21:40:49.938 | Reading new ledger | 26907133 | - | -
November 21st 2019, 21:40:50.024 | Processing ledger | 26907133 | ledger_pipeline | -
November 21st 2019, 21:40:50.027 | Finished processing ledger | 26907133 | - | -
November 21st 2019, 21:40:50.027 | Processed ledger | 26907133 | ledger_pipeline | -
November 21st 2019, 21:40:55.042 | Reading new ledger | 26907134 | - | -
November 21st 2019, 21:40:55.104 | Processing ledger | 26907134 | ledger_pipeline | -
November 21st 2019, 21:40:55.108 | Processed ledger | 26907134 | ledger_pipeline | -
November 21st 2019, 21:40:55.108 | Finished processing ledger | 26907134 | - | -
November 21st 2019, 21:40:58.762 | Shutting down ingestion system... | - | - | -
November 21st 2019, 21:40:58.764 | Error returned from ingest.LiveSession: Gap detected (ledger 26687301 does not exist but 26907134 is latest) | - | - | -
November 21st 2019, 21:41:00.772 | Reading new ledger | 26907135 | - | -
November 21st 2019, 21:41:00.773 | expingest panic | - | - | Pipeline was shut down...

Please note that `expingest panic Pipeline was shut down...` error should be fixed by https://github.com/stellar/go/pull/1972.

### More info

Looks like 26687301 (2019-11-08T02:28:49Z) is the ledger from around the time when Horizon was deployed and restarted the last time (2019-11-08 02:28:06) but the value is constantly updated in `resumeFromLedger` so this shouldn't happen... I was trying to repro this by shutting down ingestion in different moments but I wasn't able to reproduce it,  `lastIngestedLedger` in `resumeFromLedger` was always correct.

Adding to Horizon 0.24.0 because it's worth checking before next stable.

Random thoughts:
* You can see that [`Session shut down`](https://github.com/stellar/go/blob/horizon-v0.22.2/services/horizon/internal/expingest/main.go#L347) msg is not present in the log what may prove that the application stayed in `LiveSession.resume` function.
* In `LiveSession.resume`, `ledgerSequence` variable is always incremented what can be seen in the beginning of the logs above.
* If `LiveSession.Resume` returns an error `s.retry.onError` should call `LiveSession.Resume` again with a value updated `GetLatestSuccessfullyProcessedLedger()`.

**Comment by abuiles** [comment]
I spent a couple of hours looking into this without much success. I'll keep an eye on my logs in case I see a scenario where we can reproduce it.

**Comment by bartekn** [comment]
Closing since we've removed dependency on `exp/pipeline`.
