### ISSUE TITLE
`strconv.ParseFloat: parsing "": invalid syntax` error

### ISSUE THREAD

**Issue by bartekn** [stellar/go#2006]
### What version are you using?

Horizon 0.24.0 RC

### What did you do?

Production cluster requests mirroring. Happened after server restart, possibly connected to fee stats.

### What did you expect to see?

No errors.

### What did you see instead?

`strconv.ParseFloat: parsing \"\": invalid syntax`

**Comment by tamirms** [comment]
fixed in https://github.com/stellar/go/pull/2009
