### ISSUE TITLE
"canceling statement due to user request" when streaming /accounts/{id}/payments

### ISSUE THREAD

**Issue by bartekn** [stellar/go#2007]
### What version are you using?

Horizon 0.24.0 RC.

### What did you do?

Running horizon-cmp comparing prd to stg. Request to: `/accounts/GCLTVFJLOSF4C6HFLI4TQD2U6QSUJ2PZWFPLD3NDNUEO54MOIPHNQULB/payments?order=desc&limit=50`

`horizon_req:"horizon-pubnet-001a/WZOsKrSXxL-2544388"`

### What did you expect to see?

No errors in the logs.

### What did you see instead?

```
canceling statement due to user request
```

**Comment by abuiles** [comment]
Fixed in #2008
