### ISSUE TITLE
Wrong Compliance protocol url on compliance server github page

### ISSUE THREAD

**Issue by gaclaudiu** [stellar/go#2016]
### What version are you using?
https://github.com/stellar/go/tree/master/services/compliance

### What did you do?
I clicked on the Compliance protocol link from the compliance-server section. 

### What did you expect to see?
I expected to see the page describing the compliance protocol used by the compliance service.

### What did you see instead?
I see a 404 not found page and here is the link of it :https://www.stellar.org/developers/learn/integration-guides/compliance-protocol.html

**Comment by leighmcculloch** [comment]
@gaclaudiu Thank you for reporting the broken link. The link will be fixed in #2020. You can access the compliance protocol documentation [here](https://www.stellar.org/developers/guides/compliance-protocol.html).
