### ISSUE TITLE
services/horizon/expingest: Separate DB connection pool for ingestion service

### ISSUE THREAD

**Issue by bartekn** [stellar/go#2018]
Currently, all of the Horizon services share the same DB connection pool. In case of increased number of HTTP requests, it's possible that ingestion service will have to wait for an idle connection. We need to create a separate connection pool (with a number of open connections equal to [horizon max] - [max needed by ingestion at any given time: 2 right now?]) for ingestion service to make sure it can always proceed.

**Comment by ire-and-curses** [comment]
Now that we have split ingesting and front-facing nodes, this isn't necessary for our cluster. It could still potentially be helpful for single machine deployments. Let's revisit if that seems to be the case.

**Comment by bartekn** [comment]
Reopening. Frontend nodes still run ingestion because they ingest offers into in-memory order book.
