### ISSUE TITLE
services/horizon: Different response in /trade_aggregations for the same request params

### ISSUE THREAD

**Issue by bartekn** [stellar/go#2019]
### What version are you using?

Comparing Horizons using `horizon-cmp`.

### What did you do?

Sent the following requests:
* https://horizon.stellar.org/trade_aggregations?base_asset_type=credit_alphanum4&base_asset_code=BCH&base_asset_issuer=GAEGOS7I6TYZSVHPSN76RSPIVL3SELATXZWLFO4DIAFYJF7MPAHFE7H4&counter_asset_type=native&start_time=1569497716095&end_time=1569584116095&resolution=900000&limit=200&order=desc&c=0.14748656148279315
* https://horizon-stg-pubnet.stellar.org/trade_aggregations?base_asset_type=credit_alphanum4&base_asset_code=BCH&base_asset_issuer=GAEGOS7I6TYZSVHPSN76RSPIVL3SELATXZWLFO4DIAFYJF7MPAHFE7H4&counter_asset_type=native&start_time=1569497716095&end_time=1569584116095&resolution=900000&limit=200&order=desc&c=0.14748656148279315

### What did you expect to see?

Response is exactly the same.

### What did you see instead?

`open` and `close` values are different, all other values are exactly the same.

```diff
87c87
<         "open": "3687.5821073",
---
>         "open": "3697.5693755",
89,93d88
<           "N": 341127158,
<           "D": 92507
<         },
<         "close": "3697.5693755",
<         "close_r": {
95a91,95
>         },
>         "close": "3687.5821073",
>         "close_r": {
>           "N": 341127158,
>           "D": 92507
114c114
<         "open": "3674.6131853",
---
>         "open": "3687.5821073",
116,117c116,117
<           "N": 1104783478,
<           "D": 300653
---
>           "N": 341127158,
>           "D": 92507
141c141
<         "open": "3674.6131852",
---
>         "open": "3674.6131853",
143,147d142
<           "N": 110139181,
<           "D": 29973
<         },
<         "close": "3674.6131853",
<         "close_r": {
149a145,149
>         },
>         "close": "3674.6131852",
>         "close_r": {
>           "N": 110139181,
>           "D": 29973
249c249
<         "open": "3786.1758138",
---
>         "open": "3832.4071033",
251,255d250
<           "N": 413022561,
<           "D": 109087
<         },
<         "close": "3832.4071033",
<         "close_r": {
257a253,257
>         },
>         "close": "3829.1767367",
>         "close_r": {
>           "N": 1018258507,
>           "D": 265921
276c276
<         "open": "3785.9405958",
---
>         "open": "3788.0421520",
278,279c278,279
<           "N": 710674053,
<           "D": 187714
---
>           "N": 473505269,
>           "D": 125000
303c303
<         "open": "3733.5715040",
---
>         "open": "3841.5673739",
305,309d304
<           "N": 233348219,
<           "D": 62500
<         },
<         "close": "3841.5673739",
<         "close_r": {
311a307,311
>         },
>         "close": "3733.5715040",
>         "close_r": {
>           "N": 233348219,
>           "D": 62500

```

**Comment by 2opremio** [comment]
I cannot reproduce. I've also looked at the endpoint's code and I can't think of anything which could cause it. Maybe there's something going on with the ingestion? Maybe a last-ledger mismatch when making the queries?

**Comment by bartekn** [comment]
Duplicate of https://github.com/stellar/go/issues/1814.
