### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Monkeytech1990** [stellar/go#2028]
Error: An error occurred while processing this request. This is usually due to a bug within the server software. Trying this request again may succeed if the bug is transient, otherwise please report this issue to the issue tracker at: https://github.com/stellar/go/issues. Please include this response in your issue

**Comment by ire-and-curses** [comment]
We'll need a bit more information than that. ;)

Which endpoint were you hitting when you got that error? What was your request?

**Comment by Monkeytech1990** [comment]
I dont know what endpoint is. It happens when I try to sell or trade my crypto. It also doesn't allow me to sell or trade anything

**Comment by ire-and-curses** [comment]
What app or website are you using?

**Comment by efritze** [comment]
I'm getting the same error.

I get the error when I enter the following URL directly on Google Chrome:

https://horizon.stellar.org/order_book?selling_asset_type=native&buying_asset_type=credit_alphanum4&buying_asset_code=BTC&buying_asset_issuer=GAUTUYY2THLF7SGITDFMXJVYH3LHDSMGEAKSBU267M2K7A3W543CKUEF&limit=50&c=0.9792815280920741

No orderbook request works.

**Comment by efritze** [comment]
FYI, the above requests fails for our users in Cameroon , UK and in Canada.

**Comment by leighmcculloch** [comment]
We identified an issue. Details are at the link below. We're monitoring a fix for the issue. Can you try again?

https://status.stellar.org/incidents/kfrqf4q92w0n

**Comment by efritze** [comment]
The orderbooks work now on our end so far.

**Comment by leighmcculloch** [comment]
Great. I'm going to close this issue now. Please reopen if the problem recurs. From here the incident link above is the best place to monitor the incident till it is resolved.
