### ISSUE TITLE
Can not cancel disappeared order, funds are locked

### ISSUE THREAD

**Issue by rafaelwv** [stellar/go#2029]
Public key: GDNXNMVJUMX4VLK4NJG6ZH5TTSDWTPESAXXVK6F7FNB3GT5TEISPPEFJ

I have a selling order open that isn't listed anymore, I can't cancel it nor can I transfer my LTC tokens, swap, convert or withdraw my LTCs.

Let me know if you need anything else apart from what the error says;

We had trouble fetching your orders, please try again later! An error occurred while processing this request. This is usually due to a bug within the server software. Trying this request again may succeed if the bug is transient, otherwise please report this issue to the issue tracker at: https://github.com/stellar/go/issues. Please include this response in your issue.

**Comment by leighmcculloch** [comment]
@rafaelwv Are you still seeing the issue now?

We identified an issue that may or may not have been related. Details are at the link below. https://status.stellar.org/incidents/kfrqf4q92w0n

**Comment by rafaelwv** [comment]
Relation with this fixed bug confirmed, this is fixed. Thanks!
