### ISSUE TITLE
Sell crypto

### ISSUE THREAD

**Issue by Monkeytech1990** [stellar/go#2031]
### What did you see instead?
For some reason the sell button doesn't work me. I press it and it doesn't create a order. Im trying to sell RMT but it wont let me

**Comment by ire-and-curses** [comment]
What is the name of the app you are using?

**Comment by Monkeytech1990** [comment]
Im using the stellar x website

**Comment by ire-and-curses** [comment]
Unfortunately, this isn't the place for StellarX issues. I've let the StellarX team know that their error message needs to be changed. Please submit this issue here instead: https://stellarxsupport.zendesk.com/hc/en-us/requests/new
