### ISSUE TITLE
Don't include Stellar Go monorepo URL in Horizon 500 errors

### ISSUE THREAD

**Issue by ire-and-curses** [stellar/go#2034]
We had a partial Horizon [outage](https://status.stellar.org/incidents/kfrqf4q92w0n) today. Some users of third party apps came to [raise](https://github.com/stellar/go/issues/2028) [issues](https://github.com/stellar/go/issues/2029) [here](https://github.com/stellar/go/issues/2031), because our error message was passed on verbatim to the userbase of the app. The error says:

>Error: An error occurred while processing this request. This is usually due to a bug within the server software. Trying this request again may succeed if the bug is transient, otherwise please report this issue to the issue tracker at: https://github.com/stellar/go/issues. Please include this response in your issue

This causes confusion and wastes everyone's time. Additionally, a third party running (a possibly forked) Horizon may not want server errors to generate bug reports pointing to our repo.

We should change the message and remove the URL. Developers hitting the error can likely figure out the correct place to report this.

**Comment by abuiles** [comment]
@ire-and-curses added as a long stretch goal for 0.25.0
