### ISSUE TITLE
Horizon on https problems

### ISSUE THREAD

**Issue by sgehrman** [stellar/go#204]
Trying to get Horizon to work with https.

Tried to follow these instructions, but probably messed something up.
https://github.com/stellar/go/blob/master/services/horizon/internal/docs/developing.md#-enabling-tls-on-your-local-workstation

Instructions weren't clear, so I made some guesses.  I'm running the stellar docker image on a server, works fine. Site has certificate and accessing the website in https works.

1. bashed into the docker container 
2. I ran the regen.sh tool and created the certs and they are at /tls
3. modified the horizon.env and added this:
export TLS_CERT="/tls/server.crt"
export TLS_KEY="/tls/server.key"
4. Restarted horizon, no errors
5. client app now uses https url to the server for horizon
6. now getting ERR_INSECURE_RESPONSE in client

I'm assuming I'm missing a step.  Do I need to change urls in config files from http to https?

Thanks

**Comment by bartekn** [comment]
I think the issue is that certificates generated using `regen.sh` are self signed certificates and these are not accepted by browsers. You can generate a free certificate using [Let's Encrypt](https://letsencrypt.org/).

**Comment by bartekn** [comment]
If you have _star_ certificate (you can use it for subdomains too) there should be no problem using it in horizon.

Testnet is a test network, lumens have no value there so there are no real fees. Developers can test things.

**Comment by sgehrman** [comment]
Thanks @bartekn !!
Works now!  I'm hosting a mainnet stellar node, will be live in a bit.
