### ISSUE TITLE
docker-quickstart rate limits bridge server reqs

### ISSUE THREAD

**Issue by nikhilsaraf** [stellar/go#205]
When using the bridge server with the quickstart image...

It logs the following message a lot:
INFO[0001] Started listening for new payments            accountId=GADR2YWD44XSP4WOK2FHYQUCLF7G5HRGSVIDIY3QFVH7UXYGUQ7BNE7C cursor=now service=PaymentListener
and now it is getting rate limit exceeded error
I think the stream call is not blocking as expected?
looking here:
https://github.com/stellar/bridge-server/blob/master/src/github.com/stellar/gateway/listener/payment_listener.go
now getting errors like this from the java API:
org.stellar.sdk.requests.TooManyRequestsException: The rate limit for the requesting IP address is over its alloted limit.
bridge says this and dies now:
FATA[0000] StatusCode indicates error: {
  "type": "https://stellar.org/horizon-errors/rate_limit_exceeded",
  "title": "Rate limit exceeded",
  "status": 429,
  "detail": "The rate limit for the requesting IP address is over its alloted limit.  The allowed limit and requests left per time period are communicated to clients via the http response headers 'X-RateLimit-*' headers."
}

Our partner found the issue to be the quickstart image...
I found the problem with the payment stream not blocking us because the operation is not supported by the docker quickstart image. It works if I use horizon-testnet.stellar.org
From the docker horizon I get the following 404 response which isn't handled by the java SDK or bridge server:

HTTP/1.1 404 Not Found
Content-Type: application/problem+json; charset=utf-8
X-Ratelimit-Limit: 72000
X-Ratelimit-Remaining: 71998
X-Ratelimit-Reset: 3574
Date: Mon, 11 Dec 2017 06:51:49 GMT
Content-Length: 373
Connection: close

{
  "type": "https://stellar.org/horizon-errors/not_found",
  "title": "Resource Missing",
  "status": 404,
  "detail": "The resource at the url requested was not found.  This is usually occurs for one of two reasons:  The url requested is not valid, or no data in our database could be found with the parameters provided.",
  "instance": "4219ad33b358/o6HnAowfyz-000012"
}

**Comment by bartekn** [comment]
I think the issue is rate limiting. They should just increase the [limits](https://github.com/stellar/go/blob/master/services/horizon/.env.template#L7).

**Comment by nikhilsaraf** [comment]
I think that's what it is set at because the header above (`X-Ratelimit-Limit: 72000`) should be the hourly limit, no?
Their bridge server is constantly making requests he says, when connected to the docker quickstart image, and just gets fixed by switching over to horizon-testnet.stellar.org

**Comment by bartekn** [comment]
Yes this is hourly limit. Can you send bridge server log?

**Comment by nikhilsaraf** [comment]
I don't have the logs, but @poliha pointed out that it is likely because horizon and stellar-core was not in sync which is why bridge kept retrying, eventually exhausting the available rate limit quotas.

Closing this issue for now based on that explanation.

**Comment by glowkeeper** [comment]
I was getting this exact same error. In fact, I have the exact same setup - [bridge server](https://github.com/stellar/bridge-server) with the quickstart image. I 'solved' it by doubling the rate limit of the quickstart image to _144000_. Is that bad?

**Comment by glowkeeper** [comment]
Actually, I'm getting the same error now - I must have just postponed things. Perhaps I will double again, but that just has the feeling of deferring a deeper problem. I'm interested if @nikhilsaraf has any more information....

**Comment by nikhilsaraf** [comment]
@glowkeeper I think this is the correct way of doing it. If the problem persists after setting a much higher limit (say 5x) then can you let us know and upload the logs so we can reopen this issue?

**Comment by glowkeeper** [comment]
@nikhilsaraf  - cool, thanks for letting me know. I'm currently running at 4x and things seem to be holding up (although, my MacBook Pro is running very hot!)

**Comment by nikhilsaraf** [comment]
@glowkeeper is your bridge server going into a constant loop?
can you also check whether your horizon is able to keep up with stellar-core or whether it is lagging behind? (you can see when it registers an operation vs. what you see on Stellar dashboard)

**Comment by glowkeeper** [comment]
@nikhilsaraf thanks for following up. 

> _is your bridge server going into a constant loop?_

Maybe? I get a constant stream of these messages:

**INFO[0059] Started listening for new payments            accountId=GDFNDXPVUH2A35M5BJVTTS3ABE67ACE5IIMIHM35FZS7VXN2762QC454 cursor=now service=PaymentListener**

However, given the messages are marked **INFO**, and it tells me the bridge server is doing what I presumed it's supposed to be doing, I thought that was _probably_ okay...

> _can you also check whether your horizon is able to keep up with stellar-core or whether it is lagging behind? (you can see when it registers an operation vs. what you see on Stellar dashboard)_

Is this the [Stellar dashboard](https://dashboard.stellar.org/)? How do I see when Horizon registers an operation? How do I marry those two things? Just FYI; I'm using the [horizon testnet](https://horizon-testnet.stellar.org/). Please forgive me if these are silly questions, but I'm a n00b to the Stellar eco-system....

**Comment by nikhilsaraf** [comment]
@glowkeeper how often (per minute) are you seeing that INFO message?

A better way of finding out if your horizon is in sync is to go to the root url (`/`) on your horizon and compare the values of `history_latest_ledger` vs. `core_latest_ledger`. They should be the same.
If `history_latest_ledger` < `core_latest_ledger` then it means that your horizon is lagging behind.
