### ISSUE TITLE
Remove GetCreateAssetID usage from actions

### ISSUE THREAD

**Issue by bartekn** [stellar/go#2061]
There are several places outside `ingest` package where `history.Q.GetCreateAssetID` method is used. It's possible that when an asset does not exist there may be attempts to create it more than once (ex. multiple requests at the same time). In such situation the following error will be logged:
```
get failed: pq: duplicate key value violates unique constraint "history_assets_asset_code_asset_type_asset_issuer_key"
```
Instead, `history.Q.GetAssetID` method should be used. In general, Horizon shouldn't need write access to a DB outside `ingest` package.

**Comment by abuiles** [comment]
Fixed in #2120
