### ISSUE TITLE
Find a solution for binary distribution

### ISSUE THREAD

**Issue by tomerweller** [stellar/go#207]
The github releases page is becoming a bit messy. We need a solution that can handle:
a. multiple assets on different release schedules
b. snapshots, preferably separated from versioned releases

**Comment by howardtw** [comment]
Is this one also outdated?

**Comment by tomerweller** [comment]
Have you looked at the "releases" tab recently? :) 

No, I wouldn't say it's outdated. Github releases was not really designed for distribution of multiple distinct artifcats with different versions. There's a lot going on in our `travis.yml` and the `build_release_artifacts` scripts to work around that.

**Comment by howardtw** [comment]
yeah of course I have looked at the release tab, but I was not if it was even messier.

Ok. I'm gonna leave it here for now since it's not directly related to Horizon backend.

**Comment by 2opremio** [comment]
Is this about Horizon releases, or something else? I think Horizon releases are fine.

**Comment by ire-and-curses** [comment]
I think this can be closed. We distribute Horizon through apt packages, Docker as well as Github source.

Please reopen if disagree.

**Comment by leighmcculloch** [comment]
I think the issue that Tomer is highlighting is that the GitHub releases page is messy and so discovering and finding binaries is difficult. I think this is still the case, and hasn't been resolved.

It's common to ship Go applications as single binaries, which we do via the GitHub releases page in addition to distribution methods @ire-and-curses mentioned.

Fixing GitHub's UI is probably not something we can do though. We need a page that surfaces our products and download links.

We have this page in the old docs https://www.stellar.org/developers/software/ but for Horizon it only links to https://github.com/stellar/go/tree/master/services/horizon which is useless for someone wanting to run Horizon, not compile it.

We have this page in the new docs https://developers.stellar.org/docs/software-and-sdks/ which links to here https://developers.stellar.org/docs/run-api-server/ which also doesn't contain a download link. There's the quick start guide https://developers.stellar.org/docs/run-api-server/quickstart/ but at that point that's 3 links deep in that search. 

I think we need something similar to what we used to have for all our products/downloads, but possibly more prominent, and kept up-to-date.
