### ISSUE TITLE
error 500

### ISSUE THREAD

**Issue by Rodrelle** [stellar/go#209]
{
  "type": "https://stellar.org/horizon-errors/server_error",
  "title": "Internal Server Error",
  "status": 500,
  "detail": "An error occurred while processing this request.  This is usually due to a bug within the server software.  Trying this request again may succeed if the bug is transient, otherwise please report this issue to the issue tracker at: https://github.com/stellar/go/services/horizon/internal/issues. Please include this response in your issue.",
  "instance": "horizon-live-001/QGI2gLSOXK-15722169"
}
------
"id": "64422009769041921",

**Comment by Rodrelle** [comment]
I can not recover my lumens and i have to say that this has been a learning experience.   Please let me know if Horizon can send the lumens back into my wallet OR if it can forward the lumens into the blockchain so i can recieve them in the Binance exchange

**Comment by Rodrelle** [comment]
Now it shows

{
  "type": "https://stellar.org/horizon-errors/bad_request",
  "title": "Bad Request",
  "status": 400,
  "detail": "The request you sent was invalid in some way",
  "instance": "horizon-live-001/RcwS4gjlor-5357436"
}

**Comment by bartekn** [comment]
Looks like you removed your account and sent lumens to `GAHK7EEG2WWHVKDNT4CEQFZGKF2LGDSW2IVM4S5DP42RBW3K6BTODB4A`. This is how `account_merge` operation works. If you don't control this account there is no way to send this lumens anywhere else.

**Comment by Rodrelle** [comment]
@bartekn , I reopen the account . 
  But the lumens are still no where to be found.  
Did I lose them?  Because they are not in the binance account.

**Comment by Rodrelle** [comment]
I just need help recovering them.
