### ISSUE TITLE
exp/ingest/io: Ignore operation meta if tx result is txInternalError

### ISSUE THREAD

**Issue by bartekn** [stellar/go#2111]
Due to a tx meta generation bug in stellar-core (https://github.com/stellar/stellar-core/pull/2383) it's possible that tx meta is incorrect for transactions with `txInternalError` result code. For such transactions, operations meta should be ignored but we should still apply `TxChanges` in v1 and `txChangesBefore` in v2 ([confirmed](https://stellarfoundation.slack.com/archives/C0367MGFL/p1578704980059000) by @MonsieurNicolas).

**Comment by abuiles** [comment]
We need to fix it here too https://github.com/stellar/go/blob/release-horizon-v0.25.0/exp/ingest/io/ledger_transaction.go#L204

**Comment by abuiles** [comment]
Fixed in #2117
