### ISSUE TITLE
Migration guide for moving to v1.0 (new ingestion)

### ISSUE THREAD

**Issue by ire-and-curses** [stellar/go#2127]
Add a short migration guide, indicating

* a few lines about why you might/might not want to upgrade (dev release, helpful if you have perf issues with core lookups, early adopter feedback, will become mandatory soon; but might not want to run on prod services yet)
* a few lines on the major changes (e.g. no stellar-core data access any more)
* expected resource requirements changes (RAM, CPU, disk)
* summary of relevant new command line options
* how to migrate the DB from old to new ingestion
* database incompatibility after the migration (aka no going back)

**Comment by bartekn** [comment]
[Beta Testing doc](https://github.com/stellar/go/blob/release-horizon-v0.25.0/services/horizon/internal/expingest/BETA_TESTING.md) is a good base for the new doc.

**Comment by bartekn** [comment]
A few more notes from internal doc:
* Info about INGEST flag. (can be set on multiple Horizon machines but not during the upgrade to the new system).
* Orderbook and path finding available on ingesting instances only!
* HistoryArchiveURL flag is now required!
* DB space requirements.
* Asset stats enabled by default.

**Comment by bartekn** [comment]
While working on #2116 I realized that organizations doing sequential deploy (update one server after another, one at a time) the upgrade to new system won't work correctly when `EXPINGEST=true`. The ingesting instances will try to write to `exp_history_*` tables what will fail after DB migration. Such organizations should remove `EXPINGEST=true` and restart the servers or stop the servers and start it when all instances are upgraded with the new binary/package.

**Comment by bartekn** [comment]
Alpha testing guide: https://github.com/stellar/go/pull/2153.

**Comment by abuiles** [comment]
I think we can close this since #2153 has the required info cc @ire-and-curses
