### ISSUE TITLE
testnet: upgrade to HTTPS

### ISSUE THREAD

**Issue by nikhilsaraf** [stellar/go#213]
while using friendbot on horizon-testnet I found that we don't upgrade an HTTP connection to HTTPS.
This issue does not exist on the live net horizon instance because we are failing on HTTP rather than letting that through, which is ok.

Also, the self link in paging refers to an HTTP link instead of HTTPS, which should get fixed if we upgrade the connection to HTTPS initially.

**Comment by nengine** [comment]
Hello, When I run horizon server, it defaults to http. Could you let me know how can I run it on https? Thanks.

**Comment by parvanesh93** [comment]
did anyone find an answer to the described issue? how can i config ssl for friendbot service on my private network?

**Comment by bartekn** [comment]
I think it's already done.
