### ISSUE TITLE
Horizon got "REAPER" (Auto clear history data after 36 hours)

### ISSUE THREAD

**Issue by datspider** [stellar/go#214]
I recognize that my horizon server auto clearing history of transactions after 36 hours. When I check the log of my horizon server, I saw something called "reaper" (attach logs below). So what is that and why/how it happened? Thank you for your help.

time="2017-12-13T04:50:18Z" level=info msg="Starting request" host="13.114.44.60:8000" ip="118.69.187.7:43778" method=GET path="/accounts/GBP7IJ27GISKXFUS5Q26QTXMJVML2HAC5TWXFGJRX75SKD5VJGIQBXPM/offers?c=0.382987074132187" pid=5 req="ip-10-0-0-100/aB1EoHxi5P-003110" 
time="2017-12-13T04:50:18Z" level=info msg="Finished request" bytes=577 duration=1.574679ms host="13.114.44.60:8000" ip="118.69.187.7:43778" method=GET path="/accounts/GBP7IJ27GISKXFUS5Q26QTXMJVML2HAC5TWXFGJRX75SKD5VJGIQBXPM/offers?c=0.382987074132187" pid=5 req="ip-10-0-0-100/aB1EoHxi5P-003110" status=200 streaming=false 
time="2017-12-13T04:50:18Z" level=info msg="Finished request" bytes=2633 duration=6.877596ms host="13.114.44.60:8000" ip="118.69.187.7:43756" method=GET path="/accounts/GBJDOZ4BXV4VPWWSY5VHIEQF3TPOLWZSJK7B53Q3PCFGX76TTVEQB4T7?c=0.492207108815943" pid=5 req="ip-10-0-0-100/aB1EoHxi5P-003108" status=200 streaming=false 
time="2017-12-13T04:50:18Z" level=info msg="Finished request" bytes=2174 duration=7.252851ms host="13.114.44.60:8000" ip="118.69.187.7:43776" method=GET path="/accounts/GBP7IJ27GISKXFUS5Q26QTXMJVML2HAC5TWXFGJRX75SKD5VJGIQBXPM?c=0.24329216420018973" pid=5 req="ip-10-0-0-100/aB1EoHxi5P-003109" status=200 streaming=false 
time="2017-12-13T04:50:18Z" level=info msg="reaper: clearing" new_elder=755484 pid=5 
time="2017-12-13T04:50:18Z" level=info msg="reaper succeeded" new_elder=755484 pid=5 
time="2017-12-13T04:50:19Z" level=info msg="reaper: clearing" new_elder=755484 pid=5 
time="2017-12-13T04:50:19Z" level=info msg="reaper succeeded" new_elder=755484 pid=5 
time="2017-12-13T04:50:20Z" level=info msg="reaper: clearing" new_elder=755484 pid=5 
time="2017-12-13T04:50:20Z" level=info msg="reaper succeeded" new_elder=755484 pid=5 
time="2017-12-13T04:50:21Z" level=info msg="reaper: clearing" new_elder=755484 pid=5 
time="2017-12-13T04:50:21Z" level=info msg="reaper succeeded" new_elder=755484 pid=5 
time="2017-12-13T04:50:22Z" level=info msg="reaper: clearing" new_elder=755485 pid=5 
time="2017-12-13T04:50:22Z" level=info msg="reaper succeeded" new_elder=755485 pid=5 
time="2017-12-13T04:50:23Z" level=info msg="reaper: clearing" new_elder=755485 pid=5 
time="2017-12-13T04:50:23Z" level=info msg="reaper succeeded" new_elder=755485 pid=5 
time="2017-12-13T04:50:24Z" level=info msg="reaper: clearing" new_elder=755485 pid=5 
time="2017-12-13T04:50:24Z" level=info msg="reaper succeeded" new_elder=755485 pid=5 
time="2017-12-13T04:50:25Z" level=info msg="reaper: clearing" new_elder=755485 pid=5 
time="2017-12-13T04:50:25Z" level=info msg="reaper succeeded" new_elder=755485 pid=5 
time="2017-12-13T04:50:26Z" level=info msg="reaper: clearing" new_elder=755486 pid=5 
time="2017-12-13T04:50:26Z" level=info msg="reaper succeeded" new_elder=755486 pid=5 
time="2017-12-13T04:50:27Z" level=info msg="reaper: clearing" new_elder=755486 pid=5 
time="2017-12-13T04:50:27Z" level=info msg="reaper succeeded" new_elder=755486 pid=5 
time="2017-12-13T04:50:28Z" level=info msg="reaper: clearing" new_elder=755486 pid=5 
time="2017-12-13T04:50:28Z" level=info msg="reaper succeeded" new_elder=755486 pid=5 
time="2017-12-13T04:50:29Z" level=info msg="reaper: clearing" new_elder=755486 pid=5 
time="2017-12-13T04:50:29Z" level=info msg="reaper succeeded" new_elder=755486 pid=5 
time="2017-12-13T04:50:30Z" level=info msg="reaper: clearing" new_elder=755486 pid=5 
time="2017-12-13T04:50:30Z" level=info msg="reaper succeeded" new_elder=755486 pid=5 
time="2017-12-13T04:50:31Z" level=info msg="Finished request" bytes=0 duration=14.999819425s host="13.114.44.60:8000" ip="52.199.36.244:35756" method=GET path="/transactions?cursor=3298294365163520" pid=5 req="ip-10-0-0-100/aB1EoHxi5P-003095" status=0 streaming=true 
time="2017-12-13T04:50:31Z" level=info msg="Finished request" bytes=0 duration=14.999798604s host="13.114.44.60:8000" ip="52.199.36.244:35758" method=GET path="/operations?cursor=3298294365163521" pid=5 req="ip-10-0-0-100/aB1EoHxi5P-003096" status=0 streaming=true 
time="2017-12-13T04:50:31Z" level=info msg="Starting request" host="13.114.44.60:8000" ip="52.199.36.244:35762" method=GET path="/operations?cursor=3298294365163521" pid=5 req="ip-10-0-0-100/aB1EoHxi5P-003111" 
time="2017-12-13T04:50:31Z" level=info msg="Starting request" host="13.114.44.60:8000" ip="52.199.36.244:35760" method=GET path="/transactions?cursor=3298294365163520" pid=5 req="ip-10-0-0-100/aB1EoHxi5P-003112" 
time="2017-12-13T04:50:31Z" level=info msg="reaper: clearing" new_elder=755487 pid=5 
time="2017-12-13T04:50:31Z" level=info msg="reaper succeeded" new_elder=755487 pid=5 
time="2017-12-13T04:50:32Z" level=info msg="Finished request" bytes=0 duration=14.945486694s host="13.114.44.60:8000" ip="118.69.187.7:43742" method=GET path="/transactions?cursor=3298294365163520" pid=5 req="ip-10-0-0-100/aB1EoHxi5P-003097" status=0 streaming=true

**Comment by howardtw** [comment]
Hi @datspider, I believe the reaper is run once every hour. You can specify the number of ledgers you want to retain in the horizon history with this config flag `history-retention-count`. The default value is 0, meaning that Horizon will keep all history. This system is designed to remove data from the history database such that it does not grow indefinitely.

Let me know if you have further question.

**Comment by howardtw** [comment]
Closing this issue for now.
