### ISSUE TITLE
Remove old ingestion system metrics from /metrics

### ISSUE THREAD

**Issue by bartekn** [stellar/go#2158]

**Comment by abuiles** [comment]
@bartekn is this still valid? I had a look at the metrics response but it's not clear which ones are related with the old ingestion system.

**Comment by bartekn** [comment]
I think you are right. All of the metrics are registered in the main package but then updated in internal packages - I was thinking it's true for `ingest` package too. But it seems we didn't have any ingestion metrics in the old system (other than `history.latest_ledger` and similar).
