### ISSUE TITLE
Latest-Ledger header invalid when streaming /order_book

### ISSUE THREAD

**Issue by bartekn** [stellar/go#2159]
### What version are you using?

Comparing Horizon 0.24.1 and c193c699de1cedf844533d9c3a7bf85da5b22d2a deployed to horizon-stg-pubnet.

### What did you do?

Compared **streaming** (normal requests work correctly) response of:
```
/order_book?buying_asset_code=BTC&buying_asset_issuer=GBVOL67TMUQBGL4TZYNMY3ZQ5WGQYFPFD5VJRWXR72VA33VFNL225PL5&buying_asset_type=credit_alphanum4&selling_asset_code=NGNT&selling_asset_issuer=GAWODAROMJ33V5YDFY3NPYTHVYQG7MJXVJ2ND3AOGIHYRWINES6ACCPD&selling_asset_type=credit_alphanum4
```

### What did you expect to see?

`Latest-Ledger` is the same or a difference is <= 2 ledgers.

### What did you see instead?

The difference is 10 ledgers:
```diff
< Latest-Ledger: 27892169
---
> Latest-Ledger: 27892179
```
up to >100 ledgers (!) for some order books:
```diff
< Latest-Ledger: 27901126
---
> Latest-Ledger: 27901564
```
It's not clear to me if the header or actually the data is invalid.

**Comment by bartekn** [comment]
To debug it more I checked when 27901126 and 27901564 were ingested exactly in stg and prd clusters. The difference between the start of processing the ledger in the first server and the end of processing in the last server was less than ~2 sec. for both ledgers.

**Comment by ire-and-curses** [comment]
Other streaming endpoints don't seem to do this. So it's just the orderbook.

**Comment by bartekn** [comment]
> I checked when 27901126 and 27901564

I also checked 27901126+1 in case the ingestion was slow but it was also ingested in <0.2 sec. in all servers around 5 sec. after 27901126.

**Comment by bartekn** [comment]
This is `horizon-cmp` issue: #2234.
