### ISSUE TITLE
Refactor state processors to new design

### ISSUE THREAD

**Issue by tamirms** [stellar/go#2166]
All `StateProcessors` in the `services/horizon/internal/expingest/processors` package  should be refactored to the new design https://github.com/stellar/go/issues/2165

- [x] [AccountDataProcessor](https://github.com/stellar/go/pull/2138/files)
- [x] AssetStats
- [x] AccountSigners
- [x] Offers
- [x] Orderbook Graph
- [x] Trustlines

**Comment by bartekn** [comment]
Closed in #2176.
