### ISSUE TITLE
Refactor Ledger Processors to new design

### ISSUE THREAD

**Issue by tamirms** [stellar/go#2167]
All `LedgerProcessors` in the `services/horizon/internal/expingest/processors` package  should be refactored to the new design https://github.com/stellar/go/issues/2165

- [x] [Transaction Processor](https://github.com/stellar/go/pull/2138/files)
- [x] [Ledger Processor](https://github.com/stellar/go/pull/2177/commits/2a7d87ef1320b5bdbcb86382c1f0c7c4762be09d)
- [x] [Trades Processor](https://github.com/abuiles/go/commit/3fe9340a5ec0adfee865bb2eeeb4da1ca45682bf)
- [x] [Effects Processor](https://github.com/abuiles/go/commit/10104d0d0c15b9720387da15d2323520480bf85d)
- [x] [Operations Processor](https://github.com/abuiles/go/commit/9a04c4c3debbaf45439efe81c4dda893a8a5e792)
- [x] [Participants Processor](https://github.com/abuiles/go/commit/ebf6bf7415e82310033da35ad1da4f8f3bbf1fa2)

**Comment by abuiles** [comment]
tracking here https://github.com/stellar/go/pull/2177

**Comment by abuiles** [comment]
@tamirms merged  with #2177
