### ISSUE TITLE
Check performance of new ingestion design against the existing implementation

### ISSUE THREAD

**Issue by tamirms** [stellar/go#2173]
We should make sure we aren't introducing a performance hit when we refactor the ingestion system to match the new design.

**Comment by tamirms** [comment]
@bartekn reported today:

> good news. I’ve just run verify-range on DRA spam ledgers (26988927-26989439), using refactored processors. the state ingestion takes 13-15 minutes (no noticable change compared to pre-refactoring code), the slowest ledger ingestion in that range is ~1.4 sec. (also no noticable changes). state at the last ledger was correct. we obviously need to check entire pubnet history again but so far it looks good

**Comment by bartekn** [comment]
OK, `verify-range` results for pubnet after refactoring is here: https://docs.google.com/spreadsheets/d/1ZDEuLhSroygYP8dnDHdHRBDna9SexeC2eXFZi8zIDkk/edit?usp=sharing. The list contains all the ledgers ingested in more than 2 sec. I'll check the top ledgers next week but it looks like most of the ledgers ingested in >=5s. have more than 1000 ops (so above the current limit per ledger in pubnet).

**Comment by bartekn** [comment]
I fixed one issue connected to `Signers` processor in #2218 and checked the 22208959-22209023 range again. Here are the results:

duration | duration-post-2218 | sequence
-|-|-
13.9469 | 4.029861544 | 22208965
11.0928 | 1.751115648 | 22208988
4.3639 | 1.657593559 | 22208997
4.2035 | 2.013245022 | 22208977
3.0682 | 1.358358424 | 22208980
2.712189486 | 1.377062454 | 22208972
2.6111 | 1.081471923 | 22209001
2.2401 | 0.993159722 | 22208993
2.1919 | 0.980369355 | 22209006
2.0916 | 2.185135273 | 22209009

**Comment by bartekn** [comment]
OK, moving to stable milestone to check performance one last time before a stable release.
