### ISSUE TITLE
Update API reference docs before 1.0.0 stable

### ISSUE THREAD

**Issue by bartekn** [stellar/go#2179]
- [x]  Make sure that API docs are up to date with all the latest changes.
- [x] Make sure all the endpoints have detailed explanation of the data. 
   - [x] `/assets` count return authorized trust lines only
   - [x] `/accounts` returns all trust lines (authorized and unauthorized)
   - [x] Update `/fee_stats` response.
   - [x] Remove deprecated `fee_paid` field from Transaction response (replace it with the `fee_charged` and `max_fee` fields)
   - [x] Update fields from `int64` to `string`. 
       <details>
   
       - Attribute `offer_id` in [manage buy offer](https://www.stellar.org/developers/horizon/reference/resources/operation.html#manage-buy-offer) and [manage sell offer](https://www.stellar.org/developers/horizon/reference/resources/operation.html#manage-sell-offer) operations.
   
       - Attribute `offer_id` in `Trade` effect.
   
       - Attribute `id` in [Offer](https://www.stellar.org/developers/horizon/reference/resources/offer.html) resource.
   
       - Attribute `timestamp` and `trade_count` in [Trade Aggregation](https://www.stellar.org/developers/horizon/reference/resources/trade_aggregation.html) resource.
   
       See https://github.com/stellar/go/issues/1609, https://github.com/stellar/go/pull/1909, and https://github.com/stellar/go/issues/1912 for more info
       </details>
   - [x] Update operation types to canonical names (if needed) (see https://github.com/stellar/go/pull/2134).

**Comment by abuiles** [comment]
@bartekn I just updated a bunch of docs in https://github.com/stellar/go/pull/2253, added as checklist here, please check it out, let me know if something is missing and I can fix it.

**Comment by abuiles** [comment]
Fixed, the release branch has all the docs up to date.
