### ISSUE TITLE
Friendbot underfunded

### ISSUE THREAD

**Issue by oryband** [stellar/go#218]
I'm getting consistent `"op_underfunded"` errors when trying to fund newly created accounts from friendbot. Possibly related to stellar/horizon/issues/405 (I'm not the one draining it, of course).

I'm following the golang instructions in this document: https://github.com/stellar/docs/blob/efcc63ffc7d73ebd537a5b7a0d0e59121918fb01/guides/get-started/create-account.md

**Comment by bartekn** [comment]
Fixed, thanks!

**Comment by bdteo** [comment]
The same happens again. Could you, please, reopen the issue ?
