### ISSUE TITLE
Reintroduce buildState which transitions to resume on success or back to init on failure

### ISSUE THREAD

**Issue by tamirms** [stellar/go#2183]
The redesigned ingestion has compressed the `init` and `buildState` into one. It will be easier to test and understand if kept the `buildState` node in the state machine. However, we should make sure that no transactions are shared between any two nodes in the state machine.

It's probably necessary that `buildState` checks the following invariants:

`(ingestVersion != CurrentVersion || lastIngestedLedger == 0) && (lastHistoryLedger == 0 || lastHistoryLedger == lastCheckpoint)`

If those conditions fail, then it should return to `init`. On success, it should progress to `resume`

**Comment by bartekn** [comment]
FIxed in #2202.
