### ISSUE TITLE
Polish ingestion interfaces

### ISSUE THREAD

**Issue by tamirms** [stellar/go#2187]
We should go through the interfaces and exported structs / functions in the ingestion packages to make sure they are named correctly and are easy to understand. We should make sure there are comments on exported declarations and that the declarations are located in the correct packages.

**Comment by tamirms** [comment]
Also, we should update the [`exp` package](https://github.com/stellar/go/tree/master/exp):

`exp/ingest`, `exp/orderbook`, and `exp/tools/dump-ledger-state` should be moved out from `exp`. also, `exp/support/pipeline` should be removed

**Comment by ire-and-curses** [comment]
Also, [services/horizon/internal/expingest](https://github.com/stellar/go/tree/master/services/horizon/internal/expingest) should be renamed since it's not experimental any more.

**Comment by 2opremio** [comment]
This is already handled by #3110
