### ISSUE TITLE
Fix dump ledger state job

### ISSUE THREAD

**Issue by tamirms** [stellar/go#2188]
The dump ledger state job in `exp/tools/dump-ledger-state` is commented out because it uses the previous ingestion pipelines and sessions. We should rewrite this job to use the new ingestion design.

**Comment by bartekn** [comment]
We will likely merge the release branch early next week. Looks like we should fix it before then.

**Comment by tamirms** [comment]
@bartekn I will produce a PR for this today

**Comment by tamirms** [comment]
fixed in https://github.com/stellar/go/pull/2309
