### ISSUE TITLE
Support new /trades endpoint in go SDK 

### ISSUE THREAD

**Issue by tomerweller** [stellar/go#219]

**Comment by cecilygardner** [comment]
@michaelran16  - hold on this until the resources package extraction is done (https://github.com/stellar/go/issues/137)

**Comment by michaelran16** [comment]
Is someone actively working on #137? 
If not, I can close #219 and #220 this week and the resource package work won't be affected.

**Comment by michaelran16** [comment]
Added in https://github.com/stellar/go/pull/428/
