### ISSUE TITLE
Improve friendbot status codes

### ISSUE THREAD

**Issue by ddombrowsky** [stellar/go#2219]
### What version are you using?

None.  I'm just using friendbot.

### What did you do?

Attempting to fund test wallet GDPZRDTWIMY2ZQ2TSMKR3TD2KQI24GPYATMTCMW3Y6MNV5G5XVZNMOOP

The account is valid.
https://www.stellar.org/laboratory/#explorer?resource=accounts&endpoint=single&values=eyJhY2NvdW50X2lkIjoiR0RQWlJEVFdJTVkyWlEyVFNNS1IzVEQyS1FJMjRHUFlBVE1UQ01XM1k2TU5WNUc1WFZaTk1PT1AifQ%3D%3D&network=test

### What did you expect to see?

Successful transfer of 10000 lumens.  Funding of other accounts works fine.

### What did you see instead?

```
Failed to fund GDPZRDTWIMY2ZQ2TSMKR3TD2KQI24GPYATMTCMW3Y6MNV5G5XVZNMOOP on the test network
{
  "type": "https://stellar.org/horizon-errors/server_error",
  "title": "Internal Server Error",
  "status": 500,
  "detail": "An error occurred while processing this request.  This is usually due to a bug within the server software.  Trying this request again may succeed if the bug is transient, otherwise please report this issue to the issue tracker at: https://github.com/stellar/go/issues. Please include this response in your issue."
}
```

**Comment by ire-and-curses** [comment]
I see lumens in the account you linked to. Friendbot doesn't "top-up" accounts that already exist - it creates new accounts. Having said that, this is not the best error message to get back.

**Comment by ddombrowsky** [comment]
k.  I didn't know it was for new accounts only.

**Comment by leighmcculloch** [comment]
We should also change the `500` status code in this situation to maybe `409` given there's a conflict since the resource (account) already exists.

**Comment by ire-and-curses** [comment]
Next steps:

- [ ] Return something other than 500 for this situation (409?)
- [ ] Return an informative error, e.g. `account already exists`
