### ISSUE TITLE
Use canonical asset representation for filtering offers by selling or buying

### ISSUE THREAD

**Issue by abuiles** [stellar/go#2225]
Instead of using `selling_asset_type`, `selling_asset_code`, and `selling_asset_issuer`, let's have a single query param call `selling` which takes `AssetCode:AssetIssuer` or `native`.

The same should be done for `buying`.

**Comment by ire-and-curses** [comment]
This is targeted for 1.0 stable, assuming that we can do it in a backwards-compatible way.

**Comment by abuiles** [comment]
Fixed in #2252
