### ISSUE TITLE
Running `db reingest range` blocks main ingestion process

### ISSUE THREAD

**Issue by bartekn** [stellar/go#2231]
### What version are you using?

Horizon 1.0.0-beta

### What did you do?

Run `horizon db reingest range x y`.

### What did you expect to see?

Horizon reingests selected range, main ingestion proceeds.

### What did you see instead?

Main ingestion blocked during reingestion process.

### Comment

When user runs `db reingest range` the state machine of the ingestion process executes `historyRangeState` that always acquires the ingestion lock on ledger sequence value. We should update the state data to:
```go
type historyRangeState struct {
	fromLedger       uint32
	toLedger         uint32
	reingesting      bool
}
```
If `reingesting` is `true`, it should:
* not acquire the lock,
* clear history range,
* go to `stopState` when done.

Additionally, we should probably have an extra check to ensure user does not reingest the latest range - this can cause some issues in the main ingestion process.

**Comment by tamirms** [comment]
fixed in https://github.com/stellar/go/pull/2242
