### ISSUE TITLE
Send `Latest-Ledger` header in all endpoints

### ISSUE THREAD

**Issue by bartekn** [stellar/go#2233]
We started sending `Latest-Ledger` header for state related endpoints but we should do it for all endpoints. It will help reducing a number of false positives in `horizon-cmp`.

**Comment by 2opremio** [comment]
After giving this quite a bit of thought. Isn't it overkill to set that header (and in turn access the DB for all endpoints) to make `horizon-cmp` happy?

Can you point me to instances of `horizon-cmp` failing because of this?

**Comment by ire-and-curses** [comment]
From discussion offline:

the endpoints which are not immutable and missing the Last-Ledger header are the ones where you query for multiple objects according to some search criteria:

* /transactions
* fetching all transactions, fetching transactions for an account, fetching all operations, fetching operations for an account, fetching all effects, fetching effects for an account, fetching all payments, fetching all payments for an account, fetching all ledgers
* all the trade endpoints
