### ISSUE TITLE
Add tests to `/expingest/verify.go`

### ISSUE THREAD

**Issue by bartekn** [stellar/go#2264]
Part of #1343. Continue working on tests in: `verify_range_state_test.go`. Expected coverage 80%+.

**Comment by ire-and-curses** [comment]
I see that `verify.go` is now 60% covered. Is there more to do here or is this sufficient?

**Comment by bartekn** [comment]
It's at 75% now, looks like the most important code paths are covered (some missing tests for returning errors). Closing.
