### ISSUE TITLE
horizon should complain if no DATABASE_URL specified

### ISSUE THREAD

**Issue by nikhilsaraf** [stellar/go#228]
Partner raised an issue that they could not get horizon running and I suggested exporting the env var which fixed it. They were expecting horizon to complain if the setup was incomplete, which seems like a fair expectation.

**Comment by nullstyle** [comment]
It does:

```
➜ horizon
2018/01/08 11:21:02 Invalid config: db-url is blank.  Please specify --db-url on the command line or set the DATABASE_URL environment variable.
```

Could you please provide some more context?

**Comment by nikhilsaraf** [comment]
if they specify db-url then it doesn't give this error, but still doesn't work. This is broken I believe since the db-url command line param does not work.
Currently we make them use the DATABASE_URL env var only.

**Comment by nullstyle** [comment]
Hmm... thats a bug then.  `--db-url` should work interchangeably with the environment variables:  https://github.com/stellar/go/blob/master/services/horizon/main.go#L163

**Comment by nikhilsaraf** [comment]
yeah, I remember when I had tried running it with `--db-url` it didn't work for me either but it worked with the env var. I can retry with --db-url again to make sure if you want.

**Comment by nullstyle** [comment]
if you can get me a repro that'd be great

**Comment by nikhilsaraf** [comment]
tried to repro locally but it works, don't know why it didn't work earlier. Anyhow, closing now. thanks for prodding on this issue.

**Comment by juliavi** [comment]
Is there an open bug for this issue?

**Comment by nikhilsaraf** [comment]
We could not repro this issue so we closed this issue. Is it not working for you @juliavi?
