### ISSUE TITLE
Add API version to Horizon

### ISSUE THREAD

**Issue by bartekn** [stellar/go#229]
We should consider tagging API version in horizon and SDKs should check if they are compatible. I think this would allow us to push breaking changes more safely.

**Comment by nullstyle** [comment]
Here's an article that gives a brief overview of our options from an external view, and in general I agree with the author on his points:  http://blog.restcase.com/restful-api-versioning-insights/

**Comment by howardtw** [comment]
What's the priority of this one compared to other issues? Just want to follow up with it.

**Comment by theaeolianmachine** [comment]
@tomquisel perhaps we start putting priority labels on issues in the repos? We don't have to go through them all, but perhaps experiment piecemeal (P0-P3 seems good enough)? Just a thought.

**Comment by howardtw** [comment]
I absolutely support the idea of the putting a priority tag with an issue. I'd like to go through them all though I don't know if I'm able to give them the correct label ☝️ ✌️

**Comment by tomquisel** [comment]
Great idea! We've got P1-P4 for this repo (I think when we discussed it earlier there was an argument for starting at 1 vs 0?), and I've been using it here and there. I'll use it more!

**Comment by tomquisel** [comment]
As far as the issue, I'm just going to close it. When we make a breaking change, we'll adopt one of the strategies in Scott's link. No need to do it before that.
