### ISSUE TITLE
horizon db reap command does nothing

### ISSUE THREAD

**Issue by efritze** [stellar/go#2307]
### What version are you using?
horizon v0.24.1

### What did you do?

I ran:

horizon --history-retention-count 10000 db reap

including all other necessary command line arguments.

### What did you expect to see?

I expected to see feedback that the reaper actually reaped older unnecessary ledger entries in the horizon database.

### What did you see instead?

Nothing. The command line returned with no error messages.

**Comment by efritze** [comment]
After looking at the Go source code, I found this under services/horizon/cmd/db.go:

```go
var dbReapCmd = &cobra.Command{
	Use:   "reap",
	Short: "reaps (i.e. removes) any reapable history data",
	Long:  "reap removes any historical data that is earlier than the configured retention cutoff",
	Run: func(cmd *cobra.Command, args []string) {		
		err := initApp().DeleteUnretainedHistory()
		if err != nil {
			log.Fatal(err)
		}
	},
}
```

I believe the issue arises because the db reap command is calling initApp().DeleteUnretainedHistory() without an updated view of the current ledger. 

Indeed, adding the following line of code solves the issue on my end: 		initApp().UpdateLedgerState()



```go
var dbReapCmd = &cobra.Command{
	Use:   "reap",
	Short: "reaps (i.e. removes) any reapable history data",
	Long:  "reap removes any historical data that is earlier than the configured retention cutoff",
	Run: func(cmd *cobra.Command, args []string) {
                //Adding the following line prior to calling DeleteUnretainedHistory  fixed the issue on my end.
		initApp().UpdateLedgerState()
		
		err := initApp().DeleteUnretainedHistory()
		if err != nil {
			log.Fatal(err)
		}
	},
}

```

**Comment by tamirms** [comment]
@efritze Your diagnosis is correct, thanks for filing the issue! I have created a PR https://github.com/stellar/go/pull/2336 to fix this issue
