### ISSUE TITLE
building: Unable to checkout github.com/visionmedia/go-debug

### ISSUE THREAD

**Issue by sgehrman** [stellar/go#231]
That repository is gone or private? I'm pretty sure this was working a few days ago.

[WARN]  Unable to checkout github.com/visionmedia/go-debug
[ERROR] Update failed for github.com/visionmedia/go-debug: Unable to get repository: Cloning into '/root/.glide/cache/src/https-github.com-visionmedia-go-debug'...
fatal: could not read Username for 'https://github.com': No such device or address
: exit status 128

**Comment by nullstyle** [comment]
Fix is here:  https://github.com/stellar/go/pull/232

**Comment by nullstyle** [comment]
Thanks for the heads up @sgehrman, and sorry for the inconvenience.
