### ISSUE TITLE
Feature Request: Implement SEP 29 "Account Memo Requirements" in the SDK

### ISSUE THREAD

**Issue by ire-and-curses** [stellar/go#2329]
### What problem does your feature solve?
Implement [SEP 29](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0029.md) "Account Memo Requirements" in the SDK.

### What would you like to see?

1. A helper method to set up a memo on an account.

> To set up memo prerequisites for an account, the owner submits a transaction with a MANAGE_DATA operation that adds a data entry with the name config.memo_required (in lower case following SEP-18 notation) and value 1 (a single character string "1" - ASCII code 49 or Unicode U+0031).

2. Modify transaction submission to check for payment operations, and if present, call Horizon to check the account for the presence of `config.memo_required`.

> When a payment sender submits a transaction containing a PAYMENT, PATH_PAYMENT_STRICT_SEND, PATH_PAYMENT_STRICT_RECEIVE, or MERGE_ACCOUNT operation they:
> 
>  Load details about the destination account.
>  Check if the destination account has the config.memo_required data entry set. If so:
>         Verify that the transaction memo field is set.
>         If memo is not set, show a notification and prevent the transaction from submission.
>  For transactions containing more than one operation, perform the same checks for each operation.
> 

3. Provide a way to force an override of this check, for clients that know this is unnecessary for their use case.

4. Consider providing a cache (in-memory or file). If implemented, cache should be size bounded and time-limited, both configurable.

### What alternatives are there?

This can be implemented in Horizon to avoid the round trip check. However to do so violates the abstraction of Horizon as a thin presentation layer over the underlying blockchain content. It would add custom logic that would only be valid for transactions submitted through Horizon (transactions submitted directly to stellar-core would not benefit from this logic). Horizon alternative clients would also have to implement identical logic.

The expectation of SEP enforcement in SDKs is well-established.

If this implementation turns out to be unworkable in practice, and mitigations such as caching are ineffective, future options include

1. Modifying Horizon `/accounts` endpoint to allow filtering for multiple accounts in one pass, as a pre-step before tx submission (e.g. something like `/accounts?filter[id]=acccount1,account2,account3,...`)
2. Moving this logic into Horizon.
3. Dropping this logic if or when [CAP 27](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0027.md) "First-class Multiplexed Accounts" achieves wide-spread adoption.

**Comment by ire-and-curses** [comment]
We should discuss and pick standard names for the helper method and options. Then we can suggest those names across all SDKs and replicate this issue.

**Comment by ire-and-curses** [comment]
Thinking about it more, point 3 should probably be reversed, i.e. pass a flag to do the checking, default to current behaviour (no checking).

**Comment by tomquisel** [comment]
I'm leaning towards the default being `do the check`. If an app upgrades the SDK blindly, and for some reason needs to send payments that bypass the check, they'll start getting errors, investigate, and discover they need to set the flag. This seems like a low cost since it's not a silent failure, and it's a rare case that payments need to be sent that bypass the memo rule.

The upside to this default is that wallets get the memo protection for their users for free on upgrade. Wallet devs don't have to go track down all the scenarios where payments can be sent and be sure the flag is on. Obviously it depends some on the SDK (signatures may need to change in case a previously synchronous call becomes async, but ideally that can be avoided by adding the `config.memo_required` check at a logical step like at transaction submission).

I'm also hoping this can make it into the next sprint since there's quite a bit of ecosystem excitement about it!

**Comment by tomerweller** [comment]
SEP29 checks should be active by default. Making it opt-in undermines the spirit of the SEP. We want wallets (including exchanges) to do the check without changing a line of code.

**Comment by ire-and-curses** [comment]
We discussed this and agreed the following:

1. We will do the implementation in the Go SDK first (at high priority) and then replicate to other SDKs, so that we can standardise on the interface.
2. We will not implement caching or potentially batching memo checks at this time. Both add significant complexity. User can avoid the need for time-based caching if they control the account and track setting the memo id. Batching needs significant thought as i) it may eventually span other endpoints; ii) it adds a lot of complexity to evaluating received responses; iii) database implications need evaluation.
3. We will default to opt-in for the reasons expressed by @tomquisel and @tomerweller. We'll probably do this using an optional argument in the high-level tx submission method.
4. Implementer to decide what to do with the low-level XDR submission method. Opt-in means decoding the envelope and inspecting it. Doing nothing may be fine here.

**Comment by tomerweller** [comment]
> Consider providing a cache (in-memory or file). If implemented, cache should be size bounded and time-limited, both configurable.

A short-lived account cache can go a long way. The typical payment flow has the sender fetching the destination account to see that it's setup properly. That happens shortly before the actual send happens so the sep29 check can use the same account resource to check for the data entry.

**Comment by abuiles** [comment]
Fixed via #2379
