### ISSUE TITLE
Error while placing order or withdraw

### ISSUE THREAD

**Issue by lifewillwait** [stellar/go#2333]
### What did you do?

placing orders doesn't work

### What did you see instead?

"An error occurred while processing this request. This is usually due to a bug within the server software. Trying this request again may succeed if the bug is transient, otherwise please report this issue to the issue tracker at: https://github.com/stellar/go/issues. Please include this response in your issue."

**Comment by bartekn** [comment]
Can you provide more information? Is it your local Horizon, if so can you send a log? What was the transaction envelope?

**Comment by lifewillwait** [comment]
I was trying to place an order on StellarX.com  and got message: 

"An error occurred while processing this request. This is usually due to a bug within the server software. Trying this request again may succeed if the bug is transient, otherwise please report this issue to the issue tracker at: https://github.com/stellar/go/issues. Please include this response in your issue."

Same thing is when I tried to withdraw funds

**Comment by bartekn** [comment]
Please contact StellarX support here: https://stellarxsupport.zendesk.com/hc/en-us Looks like it's StellarX issue.

**Comment by lifewillwait** [comment]
> 
> 
> Can you provide more information? Is it your local Horizon, if so can you send a log? What was the transaction envelope?



> 
> 
> Please contact StellarX support here: https://stellarxsupport.zendesk.com/hc/en-us Looks like it's StellarX issue.

Ok, thank You, that sounds logical :) . I got here for reporting cause it was stated like that in error message. Have a nice day!

**Comment by ire-and-curses** [comment]
This is why we need #2034

**Comment by lifewillwait** [comment]
Hi, thank you for fast response. Unfortunatelly I don't understand what to
do. Im not developer nor using third party app. I was trying to place
orders throuh web page www.stellarx.com via chrome browser and via firefox
browser. What should i do?

Best regards,
Ivan

**Comment by ire-and-curses** [comment]
Sorry Ivan, my comment is for our benefit so we can improve this and future people won't get sent here. You should go ahead and contact StellarX support as @bartekn suggested. Good luck!
