### ISSUE TITLE
exp/services/recoverysigner: add GET /accounts/<address> endpoint

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/go#2341]
The `GET /accounts/<address>` endpoint is not yet implemented.

The endpoint is detailed in SEP-30 (not yet merged at the writing of this).

Note ideal to attempt this until after #2324 and #2339 to reduce the amount of code that needs to be refactored when those tasks are done.

**Comment by howardtw** [comment]
Closed by https://github.com/stellar/go/pull/2463
