### ISSUE TITLE
Support stellar-core protocol 13 (CAP 30) - "Remove NO_ISSUER Operation Results"

### ISSUE THREAD

**Issue by abuiles** [stellar/go#2359]
The upcoming `stellar-core` [protocol 13 release](https://github.com/stellar/stellar-core/projects/18) will add support for [CAP 30](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0030.md) ("Remove NO_ISSUER Operation Results").

**Horizon**
- We don't need to make any change for this in Horizon. Most of the code that references `*NoIssuer` is on [codes.String](https://github.com/abuiles/go/blob/10ee142de653ec94644444a24537d2e457c63c13/services/horizon/internal/codes/main.go#L38-L39) - we could remove the mentions to no issue here, but we should probably keep it for **backwards compatibility** support.
- These fields are not mentioned in the docs, nothing to do there.
- [ ] ~Remove mention to `PaymentNoIssuer` in https://github.com/stellar/go/blob/master/services/bridge/README.md~

**SDK**
- At the SDK level I found the `*NoIssuer` fields only referenced in the `xdr` generated code.
- [ ] We need to broadcast this change to the rest of the community and users since it might be app code  reading those fields. Apps won't break, they'll just end up with code that will never get executed.

**Backward compatibility**
We can release support for this before protocol 13 is deployed to stellar-core since this doesn't require any change at the XDR level and `*_NO_ISSUER` is not used in application code. We still need to tell the community about it since they might have application code that relies on this. But even if that's the case, their code won't break since we won't be changing XDRs. 

If CAP 30 doesn't make it through, we can rollback the code without problems.

**Comment by abuiles** [comment]
@rice2000 do you have this CAP in your list of upcoming changes? we need to let people know about it, in case they are relying on this result.

**Comment by rice2000** [comment]
I will make sure to include it.  Thanks @abuiles

**Comment by abuiles** [comment]
Thanks!
