### ISSUE TITLE
NoSQL Driver like Redis or AWS DynamoDB

### ISSUE THREAD

**Issue by heri16** [stellar/go#236]
Using SQL just for a simple accounts directory seems like a performance bottleneck. NoSQL databases like Redis, BerkeleyDB, or AWS DynamoDB would provide better query performance for Federation Server and Bridge Server storage.

I would propose a feature for AWS DynamoDB as I am currently porting to Serverless Framework on AWS Lambda. This would make running infrastructure for an anchor very low cost (almost free) and very easy to do by just running `sls deploy`.

**Comment by bartekn** [comment]
We would certainly accept support for NoSQL databases. We started with SQL drivers first because most FIs we were working with used them so it was easy for them to connect federation server to existing database.

**Comment by aneeshvaidya** [comment]
I'd be willing to work on this! I could use a little guidance though as it would be my first contribution to the stellar project :)

**Comment by heri16** [comment]
How is it coming along @aneeshvaidya ?

**Comment by bartekn** [comment]
`services/bridge` has been deprecated and removed.
