### ISSUE TITLE
Support Muxed Accounts (CAP 27)

### ISSUE THREAD

**Issue by tamirms** [stellar/go#2365]
The Stellar Core protocol 13 release will introduce a new type of account id called muxed accounts. Here is a summary of the changes (see https://github.com/stellar/stellar-protocol/blob/master/core/cap-0027.md for the full set of details):

The multiplexed account type is represented by a new XDR union:

~~~ {.c}
enum CryptoKeyType
{
    KEY_TYPE_ED25519 = 0,
    KEY_TYPE_MUXED_ED25519 = 256,  // This is new
    KEY_TYPE_PRE_AUTH_TX = 1,
    KEY_TYPE_HASH_X = 2
};

// Source or destination of a payment operation
union MuxedAccount switch (CryptoKeyType type) {
 case KEY_TYPE_ED25519:
     uint256 ed25519;
 case KEY_TYPE_MUXED_ED25519:
     struct {
         uint64 id;
         uint256 ed25519;
     } med25519;
};
~~~

The following fields, which were previously an `AccountID` or
`AccountID*`, are now a `MuxedAccount` or `MuxedAccount*`
(respectively):

* `PaymentOp::destination`
* `PathPaymentStrictReceiveOp::destination`
* `PathPaymentStrictSendOp::destination`
* `Operation::sourceAccount`
* `Operation::destination` (for `ACCOUNT_MERGE`)
* `Transaction::sourceAccount`
* `SimplePaymentResult::destination`

To support Muxed Accounts we will need to implement the following changes in Horizon and the SDKs:

- [x] Update the `strkey` package and the other Horizon SDK implementations to support muxed accounts.
- [x] add the restriction that all accounts in a valid SEP 10 challenge transaction must have type `KEY_TYPE_ED25519`, see https://github.com/stellar/stellar-protocol/issues/562
- [x] When ingesting transactions extract the underlying "G" address from a `MuxedAccount` and use that value when storing account columns in the Horizon database.
- [ ] Eventually we may need to add functionality to Horizon which distinguishes transactions involving MuxedAccounts from normal AccountIDs. Doing that may require us to change our data model. If so, we should either add a migration which will upgrade previously ingested `MuxedAccount` transactions to the new data model, or, reingest all transactions occurring since the start of protocol 13.

We should be able to implement these changes and release them before protocol 13 is deployed to stellar core. Also, the SDK changes to support the new type of StrKey should not be breaking for any of the clients.

**Comment by ire-and-curses** [comment]
CAP 27 XDR can be found here: https://github.com/xdrpp/stellar-core/tree/dm/muxacct

Unfortunately it looks like it's not based on top of current stellar-core master yet, which is a pain. I've pinged @stanford-scs to see if he could update the branch soon. If not we can proceed by merging this against stellar core 13's transaction.x file.

**Comment by ire-and-curses** [comment]
Since all needed changes for both Horizon and SDKs are in shared libraries, I think it's fine to track them both from this one issue.
