### ISSUE TITLE
Error "Cursor should have exactly one colon" when cursor param provided in assets request.

### ISSUE THREAD

**Issue by Synesso** [stellar/go#2368]
### What version are you using?

Running against public Horizon, which is `1.0.0-948d8d1221abd4f15cac2d3a9eb44b31633cd3b9`

### What did you do?

1. [List an asset by issuer](https://horizon.stellar.org/assets?asset_issuer=GAKZHAWTNE4VCHQX5B7N6ZSMQIF7DP7VGHIDFKVQWP4KLKI4RDBGLAEM&order=asc&limit=100) - success
2. [Add an `cursor=1` param to that url](https://horizon.stellar.org/assets?asset_issuer=GAKZHAWTNE4VCHQX5B7N6ZSMQIF7DP7VGHIDFKVQWP4KLKI4RDBGLAEM&order=asc&limit=100&cursor=1) - 400 bad request

### What did you expect to see?

A subset of the same assets and a 200 response.

### What did you see instead?

```{
  "type": "https://stellar.org/horizon-errors/bad_request",
  "title": "Bad Request",
  "status": 400,
  "detail": "The request you sent was invalid in some way.",
  "extras": {
    "invalid_field": "cursor",
    "reason": "cursor must contain exactly one colon"
  }
}
```

**Comment by abuiles** [comment]
@Synesso  What were you trying to do with `cursor=1`? This value is not a valid cursor for this end-point. I think you need to load the first or last page and then start from there. 

@ire-and-curses @bartekn @tamirms maybe we should probably start exploring an offset based  strategy for pagination.

**Comment by bartekn** [comment]
> @Synesso What were you trying to do with cursor=1? This value is not a valid cursor for this end-point. I think you need to load the first or last page and then start from there.

I think the bug @Synesso is trying to report is that the error message is invalid. It mentions colons but cursor value in next/prev doesn't contain colons.

> @ire-and-curses @bartekn @tamirms maybe we should probably start exploring an offset based strategy for pagination.

It's not a good idea, especially for `order=desc`. When new rows arrive offset will be ambiguous.

**Comment by ire-and-curses** [comment]
Yeah the colon message shouldn't be user-facing. The user probably can't fix the cursor by messing with cursors or underscores. We can just say `invalid cursor` or something.

@Synesso why did you expect to get a 200 back from this?

**Comment by Synesso** [comment]
Hi Eric.

`cursor=1` is the documented example value
<https://www.stellar.org/developers/horizon/reference/endpoints/assets-all.html#arguments>
for this parameter.

This query has returned 200s until the latest release.

It sounds like the query has been hardened, but both the error message and
the documentation are incorrect.
