### ISSUE TITLE
Assets endpoint contains fewer records than expected.

### ISSUE THREAD

**Issue by Synesso** [stellar/go#2369]
### What version are you using?

Stellar Quickstart Docker image `latest`. Horizon reports `v1.0.0`.

### What did you do?

Now that the quickstart image is available for use, I was able to run my test integration suite against it. There are failures in regard to the /assets endpoint. It is now returning fewer records than expected.

To replicate the error:

1. check out https://github.com/Synesso/scala-stellar-sdk/commit/e47f2c3c2afd13b06789b4cf36034e5cf0716e37
2. run `sbt it:test`. (You will need to wait ~5 minutes as this is the time it currently takes the quickstart image to initialise).
3. Two tests related to /assets endpoint will fail. At this stage the docker container will still be running and you can inspect the state to confirm that multiple assets should be present.

Assets trusted in operations:
```
curl -s 'http://localhost:8000/operations?limit=200' | jq -r '._embedded.records[]|select(.type_i==6)|(.asset_issuer + ":" + .asset_code)'
GAAYHQF2PNZ3H6LE5AX3UJSGUR2DQXHHGXYMHF32TDYF2FFPTTOFI3PA:Aardvark
GAAYHQF2PNZ3H6LE5AX3UJSGUR2DQXHHGXYMHF32TDYF2FFPTTOFI3PA:Beaver
GAAYHQF2PNZ3H6LE5AX3UJSGUR2DQXHHGXYMHF32TDYF2FFPTTOFI3PA:Chinchilla
GAAYHQF2PNZ3H6LE5AX3UJSGUR2DQXHHGXYMHF32TDYF2FFPTTOFI3PA:Chinchilla
GBZXN7PIRZGNMHGA7MUUUF4GWPY5AYPV6LY4UV2GL6VJGIQRXFDNMADI:Chinchilla
```

Additional assets referenced in a buy offer:

```
curl -s 'http://localhost:8000/operations?limit=200' | jq -r '._embedded.records[]|select(.type_i==12)|(.selling_asset_issuer + ":" + .selling_asset_code)'
GCYTIVTAEF6AJOZG5TVXE7OZE7FLUXJUJSYAZ3IR2YH4MNINDJJX4DXF:Dachshund
```

### What did you expect to see?

The same as in Horizon versions prior to v1.

Assets reported by Horizon:

```
curl -s 'http://localhost:8000/assets?limit=200' | jq -r '._embedded.records[]|(.asset_issuer + ":" + .asset_code)'
GAAYHQF2PNZ3H6LE5AX3UJSGUR2DQXHHGXYMHF32TDYF2FFPTTOFI3PA:Aardvark
GAAYHQF2PNZ3H6LE5AX3UJSGUR2DQXHHGXYMHF32TDYF2FFPTTOFI3PA:Beaver
GAAYHQF2PNZ3H6LE5AX3UJSGUR2DQXHHGXYMHF32TDYF2FFPTTOFI3PA:Chinchilla
GBZXN7PIRZGNMHGA7MUUUF4GWPY5AYPV6LY4UV2GL6VJGIQRXFDNMADI:Chinchilla
GCYTIVTAEF6AJOZG5TVXE7OZE7FLUXJUJSYAZ3IR2YH4MNINDJJX4DXF:Dachshund
```

### What did you see instead?

Assets reported by Horizon:

```
curl -s 'http://localhost:8000/assets?limit=200' | jq -r '._embedded.records[]|(.asset_issuer + ":" + .asset_code)'
GAAYHQF2PNZ3H6LE5AX3UJSGUR2DQXHHGXYMHF32TDYF2FFPTTOFI3PA:Chinchilla
GBZXN7PIRZGNMHGA7MUUUF4GWPY5AYPV6LY4UV2GL6VJGIQRXFDNMADI:Chinchilla
```

**Comment by Synesso** [comment]
These are [the fixtures](https://github.com/Synesso/scala-stellar-sdk/blob/e47f2c3c2afd13b06789b4cf36034e5cf0716e37/src/it/scala/stellar/sdk/LocalNetworkIntegrationSpec.scala#L105-L163) that are injected into the network state.

**Comment by bartekn** [comment]
Could you send the full `/assets` response pre-v1.0.0 and in v1.0.0? pre-v1.0.0 Horizon didn't remove assets with 0 authorized trust lines that could lead to a large number of empty trust lines in a DB. I believe this can be the reason because in [assertions](https://github.com/Synesso/scala-stellar-sdk/blob/e47f2c3c2afd13b06789b4cf36034e5cf0716e37/src/it/scala/stellar/sdk/LocalNetworkIntegrationSpec.scala#L263-L267) code both `amount` and `num_accounts` are zeros.
