### ISSUE TITLE
Transaction Failed Say Horizon Error

### ISSUE THREAD

**Issue by anggelaudiaa** [stellar/go#237]
When I submit transaction I get error with transaction failed horizon error status 400? how i fix this
{
  "type": "https://stellar.org/horizon-errors/transaction_failed",
  "title": "Transaction Failed",
  "status": 400,
  "detail": "The transaction failed when submitted to the stellar network. The `extras.result_codes` field on this response contains further details.  Descriptions of each code can be found at: https://www.stellar.org/developers/learn/concepts/list-of-operations.html",
  "instance": "horizon-live-001/RcwS4gjlor-240066901",
  "extras": {
    "envelope_xdr": "AAAAAPs/IfFolFceFp69zD1OyC1GMy5eQp8FsGUM+xorCrdPAAAAZACtjykAAAAEAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAOytLG+UpV8K00nAAF9xaHfbvhQv0syvZqxsuMx5DsYcAAAAAAAAAABHhowAAAAAAAAAAASsKt08AAABAyUqLzDKmQhIYceQuHVKkQLlsM+ncwtodI8Tvgl3OyJfQdPtCxQKU6Ctg5UDKpGdptMh8G3/bk2K+5O5pz8gIAw==",
    "result_codes": {
      "transaction": "tx_bad_auth"
    },
    "result_xdr": "AAAAAAAAAGT////6AAAAAA=="
  }
}

**Comment by bartekn** [comment]
You probably signed your transaction for another network (live network / test network).

**Comment by anggelaudiaa** [comment]
can you tell me step by step for fix this? thanks

2018-01-08 20:48 GMT+07:00 Bartek Nowotarski <notifications@github.com>:

**Comment by bartekn** [comment]
What SDK/language are you using?

**Comment by humman39** [comment]
have the same problem, not buying more

**Comment by BhumikaB** [comment]
same problem using python sdk

**Comment by bartekn** [comment]
`tx_bad_auth` error happens when transaction is signed for a different network or is signed using a wrong secret key. If you have more questions please ask at: https://stellar.stackexchange.com
