### ISSUE TITLE
Deadlock when running `db reingest range` on multiple instances

### ISSUE THREAD

**Issue by bartekn** [stellar/go#2370]
### What version are you using?

Horizon 1.0.0

### What did you do?

https://stellar.stackexchange.com/questions/3015/parallel-ingestion-with-horizon-1-0-0-is-not-working-second-horizon-waits-for

Run `db reingest range` in two processes:
```
horizon db reingest range 20000001 21000000
horizon db reingest range 25000001 25100000
```

### What did you expect to see?

No errors.

### What did you see instead?

Deadlock:
```
2020-03-04 23:53:12.012 UTC [21575] horizon@horizon ERROR:  deadlock detected
2020-03-04 23:53:12.012 UTC [21575] horizon@horizon DETAIL:  Process 21575 waits for ShareLock on transaction 49443; blocked by process 22965.
        Process 22965 waits for ShareLock on transaction 43142; blocked by process 21575.
        Process 21575: INSERT INTO history_accounts (address) VALUES ($1),($2),($3),($4),($5),($6) ON CONFLICT (address) DO NOTHING
        Process 22965: INSERT INTO history_accounts (address) VALUES ($1),($2),($3),($4),($5),($6),($7),($8),($9),($10),($11),($12),($13) ON CONFLICT (address) DO NOTHING
2020-03-04 23:53:12.012 UTC [21575] horizon@horizon HINT:  See server log for query details.
2020-03-04 23:53:12.012 UTC [21575] horizon@horizon CONTEXT:  while inserting index tuple (5596,64) in relation "history_accounts"
2020-03-04 23:53:12.012 UTC [21575] horizon@horizon STATEMENT:  INSERT INTO history_accounts (address) VALUES ($1),($2),($3),($4),($5),($6) ON CONFLICT (address) DO NOTHING
```

**Comment by bartekn** [comment]
Did some research on this and it seems that the fix is to sort the accounts before inserting them, see [1]:
> ShareLocks are row locks that are taken on each row as it is written by the transaction. ShareLock deadlocks occurs when two separate transactions try to write the same rows in opposite order. And then, it clicked. It’s the classic mutex example of AB vs BA locking.
> ...
> Fixing the ShareLock deadlock required sorting the inserts to ensure that the implicit ShareLocks taken when each row in the batch was written would always be in the same order.

It's possible that it's also a problem for `history_assets` because this is the only (along with `history_accounts`) table that is written with the same data from multiple ranges.

Before we close this, it's worth checking if we're able to reingest entire pubnet history (like we did with `verify-range`).

Why did it work before? I think we run this several times in the old system but the SQL queries were the same. It's possible that we were using different set of ranges so the bug didn't activate.

[1] https://dockyard.com/blog/2018/06/15/you-still-need-to-care-about-locks-with-transactions

**Comment by tamirms** [comment]
> Why did it work before?

up until https://github.com/stellar/go/pull/2242 was merged, only one instance of `horizon db reingest range` could run at a time because you needed to acquire the select for update lock before you could start ingesting.

**Comment by bartekn** [comment]
I meant: before the new ingestion system.
