### ISSUE TITLE
exp/services/recoverysigner: validate request parameters on POST/PUT endpoints

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/go#2388]
The recoverysigner has a couple endpoints that accept fields for storing alongside a registered account but does very little validation on the contents of those fields.

Validation should be implemented for the following endpoints:

- `POST /accounts/<address-id>`
- `PUT /accounts/<address-id>` (this endpoint isn't implemented yet, but will be in #2340)

Some ideas for what type of validation should be added:

- Fields that are not listed as optional should always be provided in the request with a non-empty value. e.g. `identities[].role`, `identities[].auth_methods[].value`.
- Fields that contain specific types of data should have their format validated. e.g. `identities[].auth_methods[].value` should have its contents validated as either a valid address, phone number, or email based on the adjacent `type` field.
- Arrays that we'd normally expect to contain at least one item should validate for that. e.g. `identities` and `identities[].auth_methods`.
- Limit the number of identities that can be added to something reasonable.
- Limit the number of auth methods that can be added to something reasonable.

**Comment by leighmcculloch** [comment]
#2390 adds validations of identities, role, auth methods and auth method type. Still need to add validation of auth method values to ensure the stellar address, phone number, or email address provided in the field are valid for each.

**Comment by mollykarcher** [comment]
Closing all recoverysigner issues
