### ISSUE TITLE
cleanup horizon's root endpoint

### ISSUE THREAD

**Issue by nikhilsaraf** [stellar/go#239]
1. orderbook endpoint should not list buying_issuer and selling_issuer, but instead it should list buying_asset_issuer and selling_asset_issuer for a correct API.

2. no friendbot api displayed in root for pub net

**Comment by MikeFair** [comment]
3. Friendbot API link in Testnet is wrong (Perhaps should be split out into "ServiceLinks" field?)

Wishlist:
4. Add the current Base_Reserve and Base_Fee amounts for the network

**Comment by ramontayag** [comment]
Looks like it's [this line](https://github.com/stellar/go/blob/3a84b177d74e14c7c5e0736013bfd299414d0692/services/horizon/internal/resource/root.go#L33) that needs changing.

**Comment by rudle** [comment]
Hello, I'm taking a look at this issue. Given that it's a few months old, I'd like to clarify some of the points made above. Regarding points 2 & 3, I believe that 2 has been addressed but I'm confused about the behaviour. To be specific, I see a friendbot API in both testnet and public net. It seems like the redirect from $stellarURL/friendbot -> friendbot.$stellarURL is not working correctly. How can I inspect the value of [the config](https://github.com/stellar/go/blob/7d1e810f65bc661a9702916b8acf11156b29a119/services/horizon/main.go#L212) at runtime?

**Comment by rudle** [comment]
Thanks for bringing me up to speed @nikhilsaraf. I'm now understanding that we want to hide the friendbot-url in cases in which there is no friendbot available. I'm also now able to answer my own question about the redirect not working: it only works in the testnet!

I'll start coding on this and hopefully have a PR ready soon.

**Comment by rudle** [comment]
See the two PRs above, they address points 1-3.
I need some help understanding the domain a bit better before I can get to 4. Searching the code base for BaseFee and BaseReserve, I see that those are properties of a particular ledger (https://github.com/stellar/go/blob/1e48159f0bd313c7cb993ca2d8cb9edf69d94841/protocols/horizon/main.go#L160) - is that true? If so, I don't think it fits in with the root resource adapter.

**Comment by nikhilsaraf** [comment]
Yes, fee is a property of a particular ledger --I agree that the root resource is _not_ the best place for it. We are in the process of introducing a new endpoint that exposes operation fee and base reserve information in this PR: https://github.com/stellar/go/pull/586

Closing this issue since issue no. 4 will be addressed in the linked PR. Feel free to reopen if needed.
