### ISSUE TITLE
tx.Sign() reports empty network passphrase

### ISSUE THREAD

**Issue by gzigzigzeo** [stellar/go#243]
I have a problem with Go API.

This works:

  	tx := b.Transaction(
        b.Network{config.Current.NetworkPassphrase},
    		b.SourceAccount{config.Current.FunderPubkey},
    		b.AutoSequence{config.Current.HorizonClient},
    		b.CreateAccount(
      			b.Destination{pubkey},
      			b.NativeAmount{config.Current.InitialBalance},
    		),
  	)

  	txe := tx.Sign(config.Current.SignerPvtkey)
  	blob, err := txe.Base64()

This does not:

    tx := b.Transaction(
        b.Network{config.Current.NetworkPassphrase},
    		b.SourceAccount{config.Current.AssetIssuerPubkey},
    		b.AutoSequence{config.Current.HorizonClient},
    		b.AllowTrust(
    			   b.Trustor{pubkey},
    			   b.Asset{
                 Code: config.Current.AssetCode,
                 Issuer: config.Current.AssetIssuerPubkey,
                 Native: false,
             },
    		),
    )

https://github.com/stellar/go/blob/d85348ad5eb60a5770eae197108391e9b1cde413/build/transaction.go#L67

config.Current.NetworkPassphrase is not empty.

Here, after "result.Mutate(b)" result.child.NetworkPassphrase
becomes empty.

Am I doing something wrong?

**Comment by bartekn** [comment]
You should use [`AllowTrustAsset`](https://godoc.org/github.com/stellar/go/build#AllowTrustAsset) instead of `Asset`:
```go
package main

import (
	b "github.com/stellar/go/build"
	"github.com/stellar/go/clients/horizon"
	"github.com/stellar/go/network"
	"log"
)

func main() {
	pubkey := "GCIUZYUXYO754AJZ5JJDWZRRELW3ZCSEJV4T2KIV3GTNOLPFNF7H2IHH"
	secret := "SBENSVT5SX6HNKQURYHTPMEWGNJ7BEJJ3YEMD5K5W7JEE5PBY4D2GH67"
	passphrase := network.TestNetworkPassphrase
	horizonClient := horizon.DefaultTestNetClient
	issuerPubkey := "GDRWBLJURXUKM4RWDZDTPJNX6XBYFO3PSE4H4GPUL6H6RCUQVKTSD4AT"
	assetCode := "MOBI"

	tx := b.Transaction(
		b.Network{passphrase},
		b.SourceAccount{issuerPubkey},
		b.AutoSequence{horizonClient},
		b.AllowTrust(
			b.Trustor{pubkey},
			b.AllowTrustAsset{assetCode},
		),
	)

	if tx.Err != nil {
		log.Fatal(tx.Err)
	}

	txe := tx.Sign(secret) // Here should be issuer secret, but for this snippet it does not matter
	blob, err := txe.Base64()

	if err != nil {
		log.Fatal(err)
	}

	log.Print(blob)
}
```

But basically the core issue is https://github.com/stellar/go/issues/79 as currently builder errors are not checked properly by developers.
