### ISSUE TITLE
txnbuild: move network passphrase field from Transaction object to Sign func

### ISSUE THREAD

**Issue by howardtw** [stellar/go#2439]
**Why**

Because both the Transaction and the TransactionEnvelope xdr structs don't contain a passphrase, one cannot get a `txnbuild.Transaction` object back with the network passphrase set when calling `txnbuild.TransactionFromXDR`. It is inconvenient given the reason that one has to set the network passphrase manually before calling the `Sign` function.

Removing the Network field out from `txnbuild.Transaction` makes the object consistent with the xdr form. Furthermore, passing it to the Sign func makes the clearer that it's a higher level of abstractions used by the SDKs and it is required before signing.

**Comment by ire-and-curses** [comment]
Related: https://github.com/stellar/go/issues/1259#issuecomment-603493853

**Comment by howardtw** [comment]
Closed by https://github.com/stellar/go/pull/2495
