### ISSUE TITLE
Horizon returns wrong result

### ISSUE THREAD

**Issue by mertgonul** [stellar/go#2444]
### What version are you using?
```
https://horizon-testnet.stellar.org/

 "horizon_version": "1.0.1-2c2d8fb0c3ae0516dcbbb39f189ca00731c9c8c3",
 "core_version": "stellar-core 12.5.0 (703982cd3e60f5981d156659b1d3e447ea1b15a8)"
```

### What did you do?
I'm trying to send a transaction with min-max time bounds but Horizon cant handle it. It returns "op_no_destination" even destination accounts are exist or given maxTime bound value exceed.

Heres my XDR : 
https://www.stellar.org/laboratory/#xdr-viewer?input=AAAAAHLiqWqQ4jFUzQQUkf4kXllPVnWaBaICs9g7a4tnKD0uAAAAyAAPoBkAAAACAAAAAQAAAABehoAQAAAAAF6GgDgAAAAAAAAAAgAAAAAAAAABAAAAAMeCGIU7NlIy%2Foy1u3BKKJiR5%2BXW5VMKRKF9ToEkyImYAAAAAAAAAAKtdBMAAAAAAAAAAAgAAAAAhTMthAdh4wxtwcSHqWWpbxS5PXwTpwB75w0Mb4eHU%2FUAAAAAAAAAAoeHU%2FUAAABAUXRx%2B3GACvFdIJyo3uldbkNBWw7MKNlLMe0FjxUr4eczncBw90PBtuZo5xOfOGjkrMSCxNhQs3YU118xmd%2B4DSTIiZgAAABA%2FbCimfWoS2QKjy%2BxVAZxHjqzmhQ7PVFZ4gpOE%2B65YmiNfIjz796ba8Puyh0lfByDRUand80eJUK7ozbHd6FLDw%3D%3D&type=TransactionEnvelope&network=test

```
 curl -X POST \
     -F "tx=AAAAAHLiqWqQ4jFUzQQUkf4kXllPVnWaBaICs9g7a4tnKD0uAAAAyAAPoBkAAAACAAAAAQAAAABehoAQAAAAAF6GgDgAAAAAAAAAAgAAAAAAAAABAAAAAMeCGIU7NlIy/oy1u3BKKJiR5+XW5VMKRKF9ToEkyImYAAAAAAAAAAKtdBMAAAAAAAAAAAgAAAAAhTMthAdh4wxtwcSHqWWpbxS5PXwTpwB75w0Mb4eHU/UAAAAAAAAAAoeHU/UAAABAUXRx+3GACvFdIJyo3uldbkNBWw7MKNlLMe0FjxUr4eczncBw90PBtuZo5xOfOGjkrMSCxNhQs3YU118xmd+4DSTIiZgAAABA/bCimfWoS2QKjy+xVAZxHjqzmhQ7PVFZ4gpOE+65YmiNfIjz796ba8Puyh0lfByDRUand80eJUK7ozbHd6FLDw==" \
  "https://horizon-testnet.stellar.org/transactions"

```

### What did you expect to see?
tx_too_late or tx_success

### What did you see instead?

```
    "result_codes": {
      "transaction": "tx_failed",
      "operations": [
        "op_no_destination",
        "op_success"
      ]
    }
```

**Comment by mertgonul** [comment]
@ire-and-curses @abuiles

**Comment by mertgonul** [comment]
It becomes really interesting.. Heres another one

XDR :
https://laboratory.stellar.org/#xdr-viewer?input=AAAAAH6FLABMVaOouH1OQ%2FNAVCrLX9MnWkXqLMEvDQbKCdwdAAABkAASNx4AAAACAAAAAAAAAAAAAAAEAAAAAAAAAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABjFyojpE9f%2Fl8VLXP5GCizwDnAFIuccmTGLoigQq8KU0AAAABAAAAAAAAAAUAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAADAAAAAQAAAAMAAAABAAAAAwAAAAAAAAAAAAAAAAAAAAEAAAAAGK%2FSmx%2FusBErScN5c75dLbRDo5VJ4%2FNxnS3BEgc3nP8AAAAAAAAAAAjw0YAAAAAAAAAABQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAIAAAABAAAAAgAAAAEAAAACAAAAAAAAAAAAAAAAAAAAAoeHU%2FUAAABAiM4TWjdb9NvZwZOoi2uMuh2vWWjVKuxi0%2BORAlI8SdJj3Z7AeI1i4vz9xxds7M8H1pfbBJbLOME5%2F9LQ2lDiAxe9UjgAAABA%2F%2B1D%2Bl%2B4d4P0sVoP9F3AixObf9VuzrbaqL5lm9yv2OLa4cKrekIkhj%2BJdnd%2FPBYVt4%2BiNdXdkI5xEp09lVCdAA%3D%3D&type=TransactionEnvelope&network=test

```
 curl -X POST \
     -F "tx=AAAAAH6FLABMVaOouH1OQ/NAVCrLX9MnWkXqLMEvDQbKCdwdAAABkAASNx4AAAACAAAAAAAAAAAAAAAEAAAAAAAAAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABjFyojpE9f/l8VLXP5GCizwDnAFIuccmTGLoigQq8KU0AAAABAAAAAAAAAAUAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAADAAAAAQAAAAMAAAABAAAAAwAAAAAAAAAAAAAAAAAAAAEAAAAAGK/Smx/usBErScN5c75dLbRDo5VJ4/NxnS3BEgc3nP8AAAAAAAAAAAjw0YAAAAAAAAAABQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAIAAAABAAAAAgAAAAEAAAACAAAAAAAAAAAAAAAAAAAAAoeHU/UAAABAiM4TWjdb9NvZwZOoi2uMuh2vWWjVKuxi0+ORAlI8SdJj3Z7AeI1i4vz9xxds7M8H1pfbBJbLOME5/9LQ2lDiAxe9UjgAAABA/+1D+l+4d4P0sVoP9F3AixObf9VuzrbaqL5lm9yv2OLa4cKrekIkhj+Jdnd/PBYVt4+iNdXdkI5xEp09lVCdAA==" \
  "https://horizon-testnet.stellar.org/transactions"
```

XDR targeting seq num 5127151569338370 but account's current seq is one higher 5127151569338371. Horizon doesn't return an error about this when i submit into it.

It returns 
```
    "result_codes": {
      "transaction": "tx_failed",
      "operations": [
        "op_success",
        "op_success",
        "op_no_destination",
        "op_success"
      ]
    }
```

even destination account "GAMK7UU3D7XLAEJLJHBXS456LUW3IQ5DSVE6H43RTUW4CEQHG6OP7GJ4" exist on the network. 

**op_no_destination** is not possible for the tx. It should be return an error about seq number of the source account.

**Comment by abuiles** [comment]
@mertgonul the transactions you are trying to re-submit actually went through but they failed because of the reasons explained in the result code. You can grab the hash for each transaction and then search it in Horizon 

The following are the failed transactions you linked above 

https://horizon-testnet.stellar.org/transactions/9dc5887e433678e395ab08ff394c239723e6abad6504556c367ca08644282e50

https://horizon-testnet.stellar.org/transactions/4863822ae4ec6012f8355ce9606eb3fb5547d1dddbc1040fa19e9d583227cf79

If you want to re-submit the transaction, you need to use a new sequence number. 

We'll explore augmenting the horizon response to make this more clear.

**Comment by ire-and-curses** [comment]
It's also worth noting that consensus-level results are recorded. Once a transaction has made it to consensus and failed, even if the state of the ledger changes in the future, you won't get different error responses in the future **for this transaction**. See [this doc](https://www.stellar.org/developers/horizon/reference/endpoints/transactions-create.html) for more.

**Comment by bartekn** [comment]
Closing because it seems to be resolved.
