### ISSUE TITLE
Implement CAP 15 (fee bump) support in Go SDK

### ISSUE THREAD

**Issue by ire-and-curses** [stellar/go#2468]
This work needs to be done in two parts.

- In part 1, we release an SDK that sends protocol 12 transactions, and can read protocol 13 as far as possible.
- In part 2, we release an SDK that reads and writes protocol 13 transactions.

- [ ]  Update SDK so that it is compatible with the new horizon transaction response structure
- [ ] Update SDK to allow transaction lookup by either its hash or its inner hash (in the case the transaction is a fee bump)
- [ ] Consider what other features could make look ups for fee bumps ergonomic
- [ ] Update SDK to build transactions from XDR from both protocol 12 and protocol 13, as far as possible. This means shimming for part 1.
- [ ] Update SDK with functionality to create and submit fee bump transactions. Note that fee bump transactions have a [different fee rate calculation](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0015.md#fee-rate) compared to normal transactions.
- [ ] Consider SEP 10 implications of fee bump transactions. We probably want to add the restriction that a fee bump transaction cannot be a valid SEP 10 challenge transaction.

Parent issue: #2360

**Comment by ire-and-curses** [comment]
@tamirms I made a first sketch summarising the work, please edit at will.

**Comment by bartekn** [comment]
Presumably fixed by https://github.com/stellar/go/pull/2495. Can you confirm? If not, please reopen.
