### ISSUE TITLE
Horizon Prebuilt Releases Missing

### ISSUE THREAD

**Issue by khelle** [stellar/go#247]
There are no longer any prebuilt releases availalbe on github, despite docs and installation instructions leading to them, resulting in getting 404 Error.

**Comment by bartekn** [comment]
https://github.com/stellar/go/releases

Where did you see a broken link to releases?

**Comment by khelle** [comment]
https://github.com/stellar/go/tree/master/services/horizon

Downloading The Server section links to non-existing releases. 

What's more the link you provided also does not have any Horizon release. I only see 0.12 Testing, but do not see any stable release for the mainnet.

**Comment by bartekn** [comment]
We moved horizon to another repository, you can find older releases by clicking a link on that page:
> See the old releases page for prior releases

(https://github.com/stellar/horizon/releases)

There are still not stable versions in this repo, we will update the Releases page once 0.12 is stable.
