### ISSUE TITLE
setup gometalinter configuration

### ISSUE THREAD

**Issue by tomerweller** [stellar/go#249]
This needs to be strict enough to catch potential bugs (unused return values, specifically errors) but not bury us under a huge pile of warnings.

**Comment by 2opremio** [comment]
@tomerweller I am considering to close this.

We are currently using https://staticcheck.io/  (i.e. `/staticcheck.sh` ) for which we explicitly mention what checks to apply. Isn't that good enough?

**Comment by tomerweller** [comment]
That's quite the prehistorical issue :) 
I don't have context anymore but sounds good @2opremio.

**Comment by leighmcculloch** [comment]
+1 I think closing this is the right call and we could use more features of staticcheck if we want to get more. gometalinter is no longer preferred tool and even vim-go has moved away from it to staticcheck recently.
