### ISSUE TITLE
Dangling preauth_tx signers due to CAP 28

### ISSUE THREAD

**Issue by 2opremio** [stellar/go#2501]
To reproduce:

Given an account A

1. Add a pre-auth signer (S) to A, associated to a transaction T, with an unachievable sequence number. (e.g. T has A as a source and a sequence number lower than `Sequence(A)`)
2. Submit A
3. Core doesn't accept T but removes S
4. Horizon still displays S in `GET accounts/A`
5. It's impossible to remove S from Horizon's state. Trying to remove S manually with `SetOps(Account=A, Signer=S,  Weigth=0)` doesn't help, since Core has already removed S in (3).

I think this may be a blocker for 1.2 since, otherwise, this will result in Horizon's DB being polluted and I don't see an easy way to clean it up later on.

**Comment by 2opremio** [comment]
It turns out that, in my setup, Core is not deleting T in (3) and it is indeed manually removable.

I need to figure out why my local environment is not following CAP 28, I am using the `stellar-core:latest` container which I thought came with CAP 28. I need to investigate this.

**Comment by 2opremio** [comment]
I was misinterpreting CAP 28. Core will only clear the signer when there is a problem in signature verification. If the sequence number is invalid, the signer won't be cleared.

**Comment by tomquisel** [comment]
Do you think that's the right call in CAP 28? While slightly painful, it's probably not too late to tweak the CAP.

**Comment by ire-and-curses** [comment]
Also, if this is the right approach, can the CAP language be tweaked to be clearer?

**Comment by 2opremio** [comment]
> Core will only clear the signer when there is a problem in signature verification. If the sequence number is invalid, the signer won't be cleared.

This is not totally correct either. CAP28 will take effect with incorrect sequences as well, but they need to be included in the ledger, which will only happen if they are correct with respect to the previous ledger (i.e. there needs to be another, concurrent transaction in the same Ledger which makes them invalid due to application ordering). More on https://github.com/stellar/go/issues/2377#issuecomment-618431408

> Do you think that's the right call in CAP 28? While slightly painful, it's probably not too late to tweak the CAP.

I think the problem is on my interpretation of CAP 28, which turns out to be more subtle than I thought (thanks a lot to @jonjove  for clarifying it).

> Also, if this is the right approach, can the CAP language be tweaked to be clearer?

@sisuresh mentioned he will be clarifying it (but not changing the implications of the CAP).
