### ISSUE TITLE
TestRepeatableReadStream/object_stream_creates_repeatable_read_tx is flaky

### ISSUE THREAD

**Issue by tamirms** [stellar/go#2508]
The test failure below occurred in https://github.com/stellar/go/pull/2505

```
--- FAIL: TestRepeatableReadStream (0.00s)
    --- FAIL: TestRepeatableReadStream/object_stream_creates_repeatable_read_tx (0.00s)
        stream_handler_test.go:230: expected [a b] but got [a]
FAIL
```

I thought this issue was fixed by https://github.com/stellar/go/pull/2462 but it turns out the test is still flaky.

**Comment by bartekn** [comment]
I think it hasn't happened since then. Closing.
