### ISSUE TITLE
False positive alert in dump ledger state job

### ISSUE THREAD

**Issue by tamirms** [stellar/go#2509]
The dump ledger state job begins by requesting the latest snapshot ledger.
https://github.com/stellar/go/blob/master/exp/tools/dump-ledger-state/run_test.sh#L12

When this request fails `LATEST_LEDGER` is set to the empty string which causes the job to fail and trigger an alert.

We should abort the job without triggering an alert if `LATEST_LEDGER` is empty.

Also, we should avoid sending slack alerts from the script. Instead we should log an error message 
in the script on failures. Then we can create an elastic search rule to trigger the alert.

**Comment by bartekn** [comment]
Moving to current sprint. Looks like easy to fix and will remove false positives.

**Comment by bartekn** [comment]
Fixed in https://github.com/stellar/go/pull/2822.
