### ISSUE TITLE
horizonclient: add a helper to get AssetType based on asset code (and issuer)

### ISSUE THREAD

**Issue by howardtw** [stellar/go#2513]
Many requests in horizonclient have one or more of `AssetType` fields, which can be derived from the length of asset code.

Chances are we might also need asset issuer as an input to be able to determine whether it is `native` asset or not. (Can we say that an asset is native if the asset code is `XLM` and the asset issuer is empty?)

In another project, I have to implement something like this
```
func assetType(asset string) horizonclient.AssetType {
	if asset == "native" {
		return horizonclient.AssetTypeNative
	}
	assetCode := strings.SplitN(asset, ":", 2)[0]
	if len(assetCode) <= 4 {
		return horizonclient.AssetType4
	}
	return horizonclient.AssetType12
}
```
where asset is in the form of [asset code]:[asset issuer]. It would be helpful if our library has something like this built in.

**Comment by Shaptic** [comment]
After the [protocol-14](https://github.com/stellar/go/tree/protocol-14) branch is merged, this will be **almost** doable via the `xdr.BuildAssets` helper:

```go
package main

import (
	"github.com/stellar/go/txnbuild"
	"github.com/stellar/go/xdr"
)

func main() {
	// The input string is any canonical asset identifier as specified in SEP-11.
	rawString := "native"

	// Note: all error checks omitted.
	assets, _ := xdr.BuildAssets(rawString)

	// It returns a list, so you'll need to grab the first element.
	asset, _ := txnbuild.AssetFromXDR(assets[0])
	t, _ := asset.GetType()
	
	switch t {
	case txnbuild.AssetTypeNative:
	case txnbuild.AssetTypeCreditAlphanum4:
	case txnbuild.AssetTypeCreditAlphanum12:
	}
}
```

However, the above `assetFromXDR()` function is [currently hidden](https://github.com/stellar/go/blob/protocol-14/txnbuild/asset.go#L103). Alternatively, we could also add something new like `txnbuild.AssetFromString()` that does the above internally to hide this boilerplate from SDK users.
