### ISSUE TITLE
SET_OPTIONS operation (set inflation destination) yields SIGNER_UPDATED effect

### ISSUE THREAD

**Issue by orbitlens** [stellar/go#252]
#### Example: 
https://horizon.stellar.org/operations/67304349436485633/effects
```
...
"type": "set_options",
"inflation_dest": "GA3FUYFOPWZ25YXTCA73RK2UGONHCO27OHQRSGV3VCE67UEPEFEDCOPA"
...
```

#### Got
```
...
"type": "signer_updated"
"weight": 1,
"key": ""
...
```

#### Expected
Horizon should return ACCOUNT_HOME_DOMAIN_UPDATED effect mentioned in the [documentation](https://www.stellar.org/developers/horizon/reference/resources/effect.html#account-effects). I'm not sure if it's a Horizon or Core bug.

**Comment by orbitlens** [comment]
Would be great if you could also look at #166.

**Comment by howardtw** [comment]
@orbitlens I think this one might have been fixed. When I looked the [effect](https://horizon.stellar.org/operations/67304349436485633/effects) you pasted above, it showed `"type": "account_inflation_destination_updated"`, which is correct.
