### ISSUE TITLE
Horizon: endless 'ledger gap detected' when using horizon from master on fresh db

### ISSUE THREAD

**Issue by sgehrman** [stellar/go#253]
I can run horizon 0.11.1 just fine and don't have this issue, but if I build horizon from source master branch it will work fine on an existing DB (one created by 11.1), but a fresh db seems to put horizon in the gap detected loop.

One more clue. If I quit horizon master, then start 0.11.1 it also is stuck in gap detected mode, but If I delete the db and restart 0.11.1 it's fine. So the master branch horizon gets a fresh db in a weird state?

It's also possible my build method is just bad and creates a buggy horizon.

I tested it a few times with same results.  Just passing it along.  

horizon:
 HISTORY_RETENTION_COUNT=8640

core:
CATCHUP_RECENT=8640

ledger gap detected (possible db corruption): validateLedgerChain: failed to load cur ledger: sql: no rows in result set

**Comment by bartekn** [comment]
I think this PR https://github.com/stellar/go/pull/226 will fix it.

**Comment by sgehrman** [comment]
Cool. Let me know if you need a tester.

**Comment by tomquisel** [comment]
@sgehrman closing this out. Feel free to reopen if it's not fixed for you.
