### ISSUE TITLE
Unable to sell Lumens to get USD

### ISSUE THREAD

**Issue by vcallegarip** [stellar/go#2538]
### What version are you using?
Not sure where I can find the version in StellarX website

### What did you do?
I attempted to sell my lumens to USD so I can withdraw but I got this error.

### What did you expect to see?
Not sure. First time I do this. I expected see a balance in USD

### What did you see instead?
 An error occurred while processing this request. This is usually due to a bug within the server software. Trying this request again may succeed if the bug is transient, otherwise please report this issue to the issue tracker at: https://github.com/stellar/go/issues. Please include this response in your issue.

**Comment by ire-and-curses** [comment]
Please contact StellarX support here: https://stellarxsupport.zendesk.com/hc/en-us Looks like it's a StellarX issue.

**Comment by ire-and-curses** [comment]
Related: #2034
