### ISSUE TITLE
Can't open order any currencie

### ISSUE THREAD

**Issue by NyuLucy** [stellar/go#2539]
### What did you expect to see?
A normal buy order with a success alert.

### What did you see instead?

An error tells me to come here to report error if persist, and its been hours without can't buy anything.
![Captura](https://user-images.githubusercontent.com/26631415/80897489-82f41100-8cf9-11ea-882a-89b45703525f.PNG)

**Comment by NyuLucy** [comment]
error still here. tried different browsers

**Comment by ire-and-curses** [comment]
Please contact StellarX support here: https://stellarxsupport.zendesk.com/hc/en-us Looks like it's a StellarX issue.

Related: #2034
