### ISSUE TITLE
Unable to send xlm to any wallet (including Stellar)

### ISSUE THREAD

**Issue by hkarhem** [stellar/go#2540]

**Comment by hkarhem** [comment]
Have tried multiple times to send xlm from stellarx wallet, but getting error, says may be a bug.

**Comment by myf2uclub** [comment]
i am also getting the same problem

**Comment by ire-and-curses** [comment]
Please contact StellarX support here: https://stellarxsupport.zendesk.com/hc/en-us Looks like it's a StellarX issue.

Related: #2034
