### ISSUE TITLE
Pending order missing and fatal error on withdrawn process

### ISSUE THREAD

**Issue by Ipposnif** [stellar/go#2542]
Hi guys, I really back for you so please don't deploy and leave unattended such beauty for 72 hours!
I tell you this because at the moment the platform is unusable: my pending orders present in the ladder are not listed in my account and I cannot manage them. I also tried to withdraw some XLM but I get the error:
An error occurred while processing this request. This is usually due to a bug within the server software. Trying this request again may succeed if the bug is transient, otherwise please report this issue to the issue tracker at: https://github.com/stellar/go/issues. Please include this response in your issue.

**Comment by NyuLucy** [comment]
can u open new orders? thats my problem since 2 days now

**Comment by ire-and-curses** [comment]
Please contact StellarX support here: https://stellarxsupport.zendesk.com/hc/en-us Looks like it's a StellarX issue.

Related: #2034
