### ISSUE TITLE
Implement fast TXMeta

### ISSUE THREAD

**Issue by ire-and-curses** [stellar/go#2550]
This is the meta issue for the [fast TXMeta](https://docs.google.com/document/d/1U0G-7r-GGn-O02n-1WahNn8dy0o78f-knRuqZF7s-I0/edit?usp=sharing) project.

The goal is to decouple Horizon from the stellar-core database, remove the need for stellar-core to maintain txmeta internally, and allow Horizon to come up to date with historical ledger information quickly and easily.

"Offline mode" means the bulk replay mode where a captive stellar-core with in-memory ledger processing is used to generate historical txmeta very quickly.

"Online mode" means the current-ledger trickle mode where a captive stellar-core provides on-going ledger updates in real-time.

"FSC" means "fast stellar-core", a stellar-core instance running in-memory solely for the purpose of producing txmeta.

**Offline mode**
- [x] Clean up single threaded prototype implementation (#2551)
- [ ] Implement and profile parallel ingestion (#2552)
- [x] Produce a benchmark that demonstrates that `Horizon can complete a full ingestion in under 24 hours on a x1.32xlarge AWS machine.`

**Online mode**
- [x] Discuss whether we need online mode to run in-memory
- [x] Identify any needed work on stellar-core side and raise issues
- [x] Update interface to communicate bulk (offline) vs trickle (online) mode
- [x] Update prototype to support online mode
- [x] Produce a test demonstrating code can catch up offline and then switch to online mode
- [x] Confirm crash/restart works reliably during online mode (no corruption etc)
- [x] Identify how to implement transaction submission

**Clustering**
- [x] Remove requirement for front-end Horizon nodes to directly ingest to memory
- [x] Implement support for multiple online Horizon-FSC instances for redundancy

**Packaging**
- [x] Determine how to optimally package and distribute Horizon-FSC for ease of use

**Cleanup**
- [ ] Remove Horizon accesses to stellar-core DB during ingestion
- [x] Remove stellar-core queries made from the `txsub` package for the case where Horizon is configured to ignore failed transactions (implement a short lived failed transactions cache in ingestion instead?) and transaction status is requested.
- [ ] Clean up and remove all cursors and any vestigial code that accesses the stellar-core database.

**Stretch goals (nice to have)**
- [ ] Implement XDR contract changes to allow partial ledger processing.
- [ ] Fall back to sqlite for more modest hardware / very large ledgers
- [ ] Confirm Horizon-FSC runs on Windows (Docker container sufficient)

**Comment by bartekn** [comment]
Closing because all the items here are done, in separate issues or will be added later during a code cleanup stage.

**Comment by ire-and-curses** [comment]
So. Cool.
