### ISSUE TITLE
exp/services/recoverysigner: log authentication method identifiers in all logs to track who is performing operations

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/go#2568]
### What
Log the ID of the auth method that has been verified when an action is being performed by the recoverysigner server.

### Why
It may be useful when auditing what identities have interacted with an account to be able to identify exactly which identity performed which operations.

This is a follow up to #2358.

**Comment by mollykarcher** [comment]
Closing all recoverysigner issues
