### ISSUE TITLE
Error Parsing Price for ManageSellOffer Operation

### ISSUE THREAD

**Issue by qiwu7** [stellar/go#2579]
### What version are you using?
5b5b4d6174e131b20380ec43fab55d4908106d4f

### What did you do?
use the following to retrieve envelope xdr
```
curl --location --request GET 'https://horizon-testnet.stellar.org/ledgers/142220/transactions' | jq '._embedded.records[1].envelope_xdr'
```

```
func main() {
	envelopeXDR := "AAAAAgAAAABDEP4VQWm3jomKahN5UCW4Bmxfym0cgn12vT4ThV81SgAAAGQAAiuJAAAAAgAAAAAAAAAAAAAAAQAAAAEAAAAAQxD+FUFpt46JimoTeVAluAZsX8ptHIJ9dr0+E4VfNUoAAAADAAAAAVNFQwAAAAAA4oSfAJtLwUw3su8iSHJB8refwQ45OL55+YxCq7vFHJEAAAAAAAAAADuaygAAAAABO5rKAAAAAAAAAAAAAAAAAAAAAAGFXzVKAAAAQLSJWk7CPp1N29pETu9uKYDJqqsHoH4LtsJV9aL6/nI5UNzcRGe0L4C0x47xMacezObrIw4N1Y6tbQ3LPla/sg4="
	genericTx, err := txnbuild.TransactionFromXDR(envelopeXDR)
	if err != nil {
		fmt.Println("error building generic transaction from envelope xdr")
	}
	// Unpacks the GenericTransaction instance into a txnbuild.Transaction
	tx, ok := genericTx.Transaction()
	if !ok {
		fmt.Println("error unpacking generic tx")
	}

	for _, op := range tx.Operations() {
		xdrOp, err := op.BuildXDR()
		if err != nil {
			fmt.Printf("error building xdrOp from txnbuild.Operation: %v\n", err)
		} else {
			fmt.Printf("successfully building xdrOp from txnbuild.Operation: %v\n", xdrOp)
		}
	}
}

```

then saw the following error
```
error building xdrOp from txnbuild.Operation: failed to parse 'Price': Couldn't find approximation
```

### What did you expect to see?
I expect to build the xdr.Operation from the txnbuild.Operation successfully

### What did you see instead?
But I saw an error while building it
```
error building xdrOp from txnbuild.Operation: failed to parse 'Price': Couldn't find approximation
```

Possible location that causes the failure 
https://github.com/stellar/go/blob/8c55e6b56b16d74f9a8dd952419c0746b4d21d86/txnbuild/manage_offer.go#L102-L105

**Comment by ire-and-curses** [comment]
https://laboratory.stellar.org/#xdr-viewer?input=AAAAAgAAAABDEP4VQWm3jomKahN5UCW4Bmxfym0cgn12vT4ThV81SgAAAGQAAiuJAAAAAgAAAAAAAAAAAAAAAQAAAAEAAAAAQxD%2BFUFpt46JimoTeVAluAZsX8ptHIJ9dr0%2BE4VfNUoAAAADAAAAAVNFQwAAAAAA4oSfAJtLwUw3su8iSHJB8refwQ45OL55%2BYxCq7vFHJEAAAAAAAAAADuaygAAAAABO5rKAAAAAAAAAAAAAAAAAAAAAAGFXzVKAAAAQLSJWk7CPp1N29pETu9uKYDJqqsHoH4LtsJV9aL6%2FnI5UNzcRGe0L4C0x47xMacezObrIw4N1Y6tbQ3LPla%2Fsg4%3D&type=TransactionEnvelope&network=test

It seems to be a rounding problem in `price`.

Numerator: 1
Denominator: 1000000000
Result of `price.StringFromFloat64(float64(result.Price.N) / float64(result.Price.D))`: 0.0000000

**Comment by ire-and-curses** [comment]
Underlying issues that also need fixing: #2514, #2515

**Comment by bartekn** [comment]
Yes, looks like https://github.com/stellar/go/issues/2514 should fix this one. The code in https://github.com/stellar/go/blob/5b5b4d6174e131b20380ec43fab55d4908106d4f/txnbuild/manage_offer.go#L126-L150 tries to find a string/decimal representation of the price because manage offer builder accepts strings only. When #2514 is done we can simply pass N and D.

**Comment by qiwu7** [comment]
do we have an eta for this issue? Appreciated 🎉
