### ISSUE TITLE
bifrost demo: display keypair in the beginning of the funnel 

### ISSUE THREAD

**Issue by tomerweller** [stellar/go#258]
Currently, we expose the user's generated account keypair at the end of the purchase funnel, making it very easy to loose one's private key. It might be helpful to move this to the beginning of the funnel with multiple confirmations from the user that it has been saved, including a print prompt. Simlar to how mobius did this: 
  
![screenshot_20180118_104314](https://user-images.githubusercontent.com/815704/35176419-b587e6f4-fd2d-11e7-86b1-32b98e8e59ae.png)

**Comment by bartekn** [comment]
It's possible to do it now. Both functions: [`Bifrost.Session.startBitcoin `](https://github.com/stellar/bifrost-js-sdk#bifrostsessionstartbitcoinonevent--promise) and [`Bifrost.Session.startEthereum `](https://github.com/stellar/bifrost-js-sdk#bifrostsessionstartethereumonevent--promise) return a promise that resolved parameters contain a key pair. It's just to devs when they want to display it.
