### ISSUE TITLE
Move old actions code to the new architecture

### ISSUE THREAD

**Issue by bartekn** [stellar/go#2582]
We've been planning to upgrade actions code for a long time but it seems we should finally do it. Recently found memleak (#2535) showed that there are 3 codepaths responsible for streaming endpoints. This code duplication is messy and hard to maintain.

When upgrading the code we should also update the code responsible for queries to query structs we use in the new `actions` package.

Here's a list of files that need to be moved. Please comment to ask yourself [a group of] files.

- [x] actions_data.go
- [x] actions_effects.go
- [x] actions_ledger.go
- [x] actions_metrics.go
- [x] actions_not_found.go https://github.com/stellar/go/pull/2838
- [x] actions_not_implemented.go https://github.com/stellar/go/pull/2838
- [x] actions_operation.go
- [x] actions_operation_fee_stats.go
- [x] actions_path.go @abuiles 
- [x] actions_rate_limit_exceeded.go https://github.com/stellar/go/pull/2838
- [x] actions_root.go @2opremio 
- [x] actions_trade.go
- [x] actions_transaction.go

## Data @2opremio 
- [x] `r.Get("/accounts/{account_id}/data/{key}/")`

## Transactions @abuiles 
- [x] `r.Get("/accounts/{account_id:\\w+}/transactions", w.streamIndexActionHandler(w.getTransactionPage, w.streamTransactions))`
- [x] `r.Get("/ledgers/{ledger_id}/transactions", w.streamIndexActionHandler(w.getTransactionPage, w.streamTransactions))`
- [x] `r.Get("/transactions", w.streamIndexActionHandler(w.getTransactionPage, w.streamTransactions))`
- [x] `r.Get("/transactions/{tx_id}/", showActionHandler(w.getTransactionResource))`

## Operations @abuiles 
- [x] `r.Get("/accounts/{account_id:\\w+}/operations", OperationIndexAction{}.Handle)`
- [x] `r.Get("/ledgers/{ledger_id}/operations", OperationIndexAction{}.Handle)`
- [x] `r.Get("/transactions/{tx_id}/operations", OperationIndexAction{}.Handle)`
- [x] `r.Get("operations/", OperationIndexAction{}.Handle)`

## Operation @2opremio
- [x] `r.Get("operations/{id}", OperationShowAction{}.Handle)`

## Payments @abuiles 
- [x] `r.Get("/accounts/{account_id:\\w+}/payments", OperationIndexAction{OnlyPayments: true}.Handle)`
- [x] `r.Get("/ledgers/{ledger_id}/payments", OperationIndexAction{OnlyPayments: true}.Handle)`
- [x] `r.Get("/transactions/{tx_id}/payments", OperationIndexAction{OnlyPayments: true}.Handle)`
- [x] `r.Get("/payments", OperationIndexAction{OnlyPayments: true}.Handle)`

## Effects @2opremio 
- [x] `r.Get("/accounts/{account_id:\\w+}/effects", EffectIndexAction{}.Handle)`
- [x] `r.Get("/ledgers/{ledger_id}/effects", EffectIndexAction{}.Handle)`
- [x] `r.Get("/transactions/{tx_id}/effects", EffectIndexAction{}.Handle)`
- [x] `r.Get("operations/{op_id}/effects", EffectIndexAction{}.Handle)`
- [x] `r.Get("/effects", EffectIndexAction{}.Handle)`

## Trades @abuiles 
- [x] `r.Get("/accounts/{account_id:\\w+}/trades", TradeIndexAction{}.Handle)`
- [x] `r.Get("/trades", TradeIndexAction{}.Handle)`
- [x] `r.Get("/offers/{offer_id}/trades", TradeIndexAction{}.Handle)`
- [x] `r.Get("/trade_aggregations", TradeAggregateIndexAction{}.Handle)`

## Others 
- [x] `r.Get("/accounts/{account_id}/", w.streamShowActionHandler(w.getAccountInfo, true))`
- [x] `r.Get("/accounts/{account_id}/data/key", w.streamShowActionHandler(w.getAccountInfo, true))`
- [x] `r.Get("/ledgers", LedgerIndexAction{}.Handle)`
- [x] `r.Get("/ledgers/{ledger_id}/", LedgerShowAction{}.Handle)`
- [x] `r.Post("/transactions", TransactionCreateAction{}.Handle)`
- [x] `r.Get("/fee_stats", FeeStatsAction{}.Handle)` @abuiles 
- [x] `r.Get("/", RootAction{}.Handle)` 
- [x] `w.internalRouter.Get("/metrics", MetricsAction{}.Handle)`
- [x] `w.internalRouter.Get("/debug/pprof/heap", pprof.Index)`
- [x] `w.internalRouter.Get("/debug/pprof/profile", pprof.Profile)`

**Comment by bartekn** [comment]
Let's try fixing https://github.com/stellar/go/issues/997 when working on this.

**Comment by 2opremio** [comment]
Strictly speaking this is done. However, the file layout of the main package (`/services/horizon/internal` is awkward (to say the least):

```
.
├── actions
├── actions_account_test.go
├── actions_data_test.go
├── actions_effects_test.go
├── actions_ledger_test.go
├── actions_operation_fee_stats_test.go
├── actions_operation_test.go
├── actions_path_test.go
├── actions_payment_test.go
├── actions_root_test.go
├── actions_trade_test.go
├── actions_transaction_test.go
├── app.go
├── app_test.go
├── handler.go
├── helpers_test.go
├── httpt_test.go
├── httpx
├── init.go
├── middleware.go
├── middleware_test.go
├── operationfeestats
├── stream_handler_test.go
└── web.go
```

All the `actions_*_test.go` really belong to the same package as the action implementations. However, there is a dependency on App (which I started to break out on #2848 and #2850 ) which prevents that from happening.

My plan to solve this is to put all HTTP-related _things_ into the already existing `httpx` package. For that I would:

1. Create`httpx.Server` with the http-related parts of `App` and `web`
2. Optionally, move the routing parts of `web.go` and `middleware.go` into `httpx/router.go`
3. Move `handler.go`, `helpers_{test}.go`, `httpt_test.go` to `httpx`
4. Move the `actions` package to `httpx/actions/` and move `actions_*_test.go` to `httpx/actions_test` (Ideally, all those tests would leave on `httpx/actions` but, since the tests will depend on `httpx.Server` and the server depends on the actions, it would create a dependency cycle.
5. Optionally, move app.go into its own package `app`.

**Comment by bartekn** [comment]
Sounds good to me!

> Optionally, move the routing parts of web.go and middleware.go into httpx/router.go

I think we should do that. It would be great if `App` was only responsible for starting services based on the config and injecting them. This would allow complete separation for testing (`App` not required in `httpx` tests etc.).

> Move the actions package to httpx/actions/ and move actions_*_test.go to httpx/actions_test (Ideally, all those tests would leave on httpx/actions but, since the tests will depend on httpx.Server and the server depends on the actions, it would create a dependency cycle.

I think it's fine to leave actions in `actions` and make `httpx` only responsible for HTTP stack not the business logic.

Regarding tests: I'm afraid it will require refactoring because some of them depend on `App`. If it turns out to be a big problem we can start with moving tests to `actions` first and them continue with refactoring explained here.

**Comment by 2opremio** [comment]
> I think it's fine to leave actions in `actions` and make `httpx` only responsible for HTTP stack not the business logic.

For good or for bad, actions are HTTP-only, since they have an `http.Request` as input.

> Regarding tests: I'm afraid it will require refactoring because some of them depend on `App`. If it turns out to be a big problem we can start with moving tests to `actions` first and them continue with refactoring explained here.

There are not that many dependencies on App and some of them will go away with the `http.Server` split. Let's see.

**Comment by 2opremio** [comment]
Closing. I created https://github.com/stellar/go/issues/2866 to split the action tests and move them to a better location later on.
