### ISSUE TITLE
bifrost should accept XLM

### ISSUE THREAD

**Issue by tomerweller** [stellar/go#259]
This is counter intuitive but from the user perspective they should be able to use the same flow to purchase with lumens. One such use case is when the user doesn't actually have their own Stellar account, but rather an XLM balance in an exchange, and they want to withdraw directly to participate in an ICO.

**Comment by ramontayag** [comment]
Wouldn't you need to just put an offer for `XLM` -> `YOUR.TOKEN` and this would work?
