### ISSUE TITLE
Update prototype to run online ingestion mode

### ISSUE THREAD

**Issue by bartekn** [stellar/go#2610]
In https://github.com/stellar/go/pull/2322 we added a prototype to use FSC in an offline mode (to ingest old ledgers). Let's experiment with an online mode. We should simply replace existing `DatabaseBackend` in ingest package in Horizon with `captiveBackend` and see what happens, then fix simple bugs and create GH issues for larger problems.

During Horizon team meeting we already identified some issues, for example: a request to get the first ledger after stellar-core startup blocks until state is synchronized. This can affect distributed ingestion.

This issue can potentially be assigned to two developers.

**Comment by abuiles** [comment]
If we don't have core how can we determine how far behind are we from core?  do we have to remove the following? 

>  "core_latest_ledger": 530962,

**Comment by abuiles** [comment]
We need to gracefully shutdown when ingesting from captive on online mode, currently we get 

> ERRO[2020-06-01T17:14:39.620-05:00] Error in ingestion state machine              current_state="resume(latestSuccessfullyProcessedLedger=531247)" error="Error running processors on ledger: Error creating ledger reader: error reading ledger from backend: unmarshalling framed LedgerCloseMeta: unmarshalling XDR frame header: xdr:DecodeUint: EOF while decoding 4 bytes - read: '[]'" next_state="resume(latestSuccessfullyProcessedLedger=531247)" pid=24589 service=expingest

**Comment by bartekn** [comment]
OK, now that @graydon answered my questions I think I have more info to be able to open a discussion and create a list of issues and changes we may need to implement. I still think we shouldn't actively work on this other than experimenting. It's still possible that we may need to implement a new `run-from` mode in Stellar-Core. Both modes have their pros and cons and (unless I'm wrong) I think it's hard to find something in the middle.

The new `stellar run-from` mode I was thinking about works exactly like `stellar run` but instead of getting the LCL sequence from a database it accepts it as a command line param. This simple change (looking at this without a good knowledge of Stellar-Core code) can fix or improve some of the issues described below:
* Decreases ops work related to running Stellar-Core. Horizon admins doesn't need to create Postgres DB or sqlite DB path. All temp files are removed when Horizon is stopped.
* Requires a single command to rewind the stream instead of `new-db`, `catchup X/0`, `run`.
* When rewinding, the buckets are applied much faster (because it's not using a disk).

Unfortunately it introduces new set of problems:
* The state is always built at the startup (but it's faster than writing it into a DB).
* Requires almost 3GB of RAM (and this can increase when ledger grows).

I think I'm leaning to the existing `stellar-core run` command because rebuilding state in Horizon is a rare event compared to Horizon restarts which are much slower in `run-from`.

I'm currently working in `captive-core-online` branch trying to make it up and running using the easiest (not the best) solutions for problems below to catch more issues. Will update the list after finding more.

--- 

### Config

**Problem:** In the online mode, with Horizon _connected_, Stellar-Core operates with a normal config. We need both quorum set and DB connection string because we need to persist the latest ledger closed by Core and read by Horizon. Users should be able to pass a path to their `stellar-core.cfg`.

**Possible solutions:**
* When we start Stellar-Core in the online mode we can use https://github.com/stellar/stellar-core/pull/2574 to make it stream the meta to a specified pipe/file which updates the config.
* We need a new config option to allow passing `stellar-core.cfg` in the online mode.

### No way to rewind the stream

**Problem:** The is no way to rewind the stream but there are two situations in which this can be really helpful:
* Horizon read ledger X from the pipe but was shutdown (ex. due to a deploy). When it starts again, the next ledger it can read is X+1.
* As above but Horizon crashes.

**Possible solutions:**
* Trivial: `stellar-core new-db`, `stellar-core catchup X/0`, `stellar-core run`. The downside: it will need to apply buckets again so it's slow. And because it's using persistent storage it's actually slower than in-memory version.
* Horizon can cache latest ledgers is a DB but there is still a short window between reading a ledger and saving it when crash can occur.
* Stellar-Core and Horizon can communicate via file instead of a pipe. This solves the problem with rewinding but Stellar-Core need to trim this file from time to time. This brings back the problem of cursors.

### Delay when (re)building state

**Problem:** There is no buffering in Stellar-Core: metadata-writing part is performed synchronously with ledger-close. So it won't close the ledger until Horizon reads ledger meta from a pipe. If this happens, after 35 seconds Stellar-Core will lose sync with the network. In the worst case it will have to wait for the next checkpoint to be published.

The problem is that Horizon actually doesn't read new ledgers from a ledger backend (for around 15 minutes) when (re)building state. This happens when a fresh Horizon instance is started or when a version upgrade requires the state to be rebuilt.

At the same time it needs to load checkpoint ledger X before reading buckets to check the bucket list hash (in `LedgerHeader`) to ensure the data has not been changed by a malicious actor.

**Possible solutions:**
* Do nothing and accept waiting for ledger X+1 after the state is built. Up to 5 minutes waiting time for the checkpoint + apply time.
* Buffering could help but 15 minutes waiting is equal to 180 ledgers what can increase a RAM usage if the ledgers are big (if buffered in RAM instead of a disk).

**Comment by bartekn** [comment]
Online mode experiment PR: https://github.com/stellar/go/pull/2694

**Comment by bartekn** [comment]
Prototype is complete. We're planning to release it as an experimental feature in [Horizon 1.6.0](https://github.com/stellar/go/milestone/29).
