### ISSUE TITLE
exp/services/webauth: define and implement a set of useful metrics exposed on an admin port

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/go#2623]
### What

Define and implement a set of useful metrics that are exposed on an admin port.

### Why

To allow for greater visibility into a deployment of webauth, and how it is being used and behaving.

**Comment by leighmcculloch** [comment]
- [ ] Challenge count
- [ ] Challenge complete count for successfully signed txns
- [ ] Challenge complete count for failed signed txns

**Comment by mollykarcher** [comment]
Closing all webauth issues
