### ISSUE TITLE
Remove all instances of code that access core db

### ISSUE THREAD

**Issue by abuiles** [stellar/go#2643]
We should remove Core DB access where possible. Ideally, Horizon shouldn't rely on Core DB to work correctly.

## TODO
The following are a list of places where we still using core's db which we won't be able to drop yet.

- [x] We still need coreQ to get the LatestLedger  - we need to figure a solution for this before being able to drop access to core's db #2725.
- [x] `ledgerbackend` .
- [x] `SubmissionSystem` https://github.com/stellar/go/pull/2702

**Comment by bartekn** [comment]
I think that ultimately we should remove all Core DB access before shipping captive core. Simply remove `db2/core` package and see what happens.

**Comment by abuiles** [comment]
I just added the following ticket to keep track of the other task to get this done https://github.com/stellar/go/issues/2725

**Comment by abuiles** [comment]
This has been fixed now.
