### ISSUE TITLE
Improve captive-core error reporting

### ISSUE THREAD

**Issue by 2opremio** [stellar/go#2669]
If the captive core fails to start for whatever reason, the relevant error isn't printed and a parsing error is printed instead:

```
2020/06/04 19:55:15 error preparing range: opening getting ledger `from-1`: unmarshalling framed LedgerCloseMeta: unmarshalling XDR frame header: xdr:DecodeUint: EOF while decoding 4 bytes - read: '[]'
```

In this case, the relevant error was:
```
/usr/local/bin/stellar-core: error while loading shared libraries: libpq.so.5: cannot open shared object file: No such file or directory
```

which wasn't printed out until enabling logging (uncommenting the following lines):

https://github.com/stellar/go/blob/05bc2caec65bc795559b70ee1c25afe398148bc1/exp/ingest/ledgerbackend/stellar_core_runner.go#L62-L76

We should also print out errors with proper formatting (i.e. the same logging format as the rest of horizon messages)

**Comment by bartekn** [comment]
I wonder if we should create a struct used for Core-Horizon communication instead of sending `LedgerCloseMeta` only. I think about something like:
```xdr
union Message switch (MessageType type)
{
case ERROR_MSG:
    Error error;
case SYNC_PROGRESS:
    int percent;
case META:
    LedgerCloseMeta meta;
}
```
This way we can get errors via pipe instead of parsing stellar-core logs. Will forward this to stellar-core team.

**Comment by bartekn** [comment]
This is solved: https://github.com/stellar/go/pull/2803. The error should be part of Horizon log when https://github.com/stellar/go/pull/2673 is done.

**Comment by bartekn** [comment]
I'm reopening this. I think it's worth adding Stellar-Core logs to Horizon log but wrap it in our log format. This way we can add labels (I propose `service=ingest subservice=stellar-core`) so it's easy to filter them out but. We can also identified critical (form Horizon point of view) errors in Stellar-Core log and promote such logs to `error` level.

**Comment by ire-and-curses** [comment]
I'd be cautious about identifying specific critical errors. It couples Horizon to stellar-core's log format, which is not a formal API and could change at any time (and silently stop reporting in our logs).

**Comment by bartekn** [comment]
> I'd be cautious about identifying specific critical errors.

We won't do that. We are going to keep Core log together with Horizon log.
