### ISSUE TITLE
bifrost: add support for timelocked accounts

### ISSUE THREAD

**Issue by tomerweller** [stellar/go#267]
Almost all ICOs have some sort of time-lock period, even if only for the duration of the sale.

Some issuers have used used `Authorization revocable` on their assets to achieve this. By revoking assets right after moving them and then un-revoking at the end of the sale. This is cumbersome and does not provide any transparency for the process.

I propose using multi-sig accounts and time locked transactions to achieve this. 

The gist: 
- The issuer will create an account and place the user's assets in it.
- The issuer will add the user as a signee on this account and adjust weights to be 2/2. 
- The issuer and the user will pre-sign a timlocked transaction to transfer full ownership to the user at the end of the sale.
- The user will be given a copy of this transaction. 
- Optionally, the issuer will save a copy of the transaction and will auto-submit it at the right time.

**Comment by bartekn** [comment]
Duplicate of https://github.com/stellar/go/issues/260?
