### ISSUE TITLE
Missing effects for PATH_PAYMENT operation

### ISSUE THREAD

**Issue by orbitlens** [stellar/go#268]
Some PATH_PAYMENT operations return invalid set of effects. As a result, the account balance can't be reconstructed based on effects which causes data inconsistency between the `core` and `horizon` databases.

#### Affected operations examples
https://horizon.stellar.org/operations/60226681419337729
https://horizon.stellar.org/operations/60226891872735233

#### Steps to check data inconsistency

Query to the `core` database
```
SELECT accountid, balance/10000000.0 as balance
FROM trustlines
WHERE issuer = 'GC22OC7R4X4GGSBMRSWWF7UAWXDXLL6PAHVUEQTOAGYFHPHZ3R5L63XH' 
  AND assetcode = 'WowToken'
```
returns
```
accountid             balance
========
GBTGFLYM7BLTHFU5FL4MRJPX4WPJ22QSDTZQI3UF3KC7GKN3TSHHWDUK    16
```

However, when you look at the effects for the mentioned account, the sum of remaining `WowToken`s is 18 after all recalculations.

https://horizon.stellar.org/accounts/GBTGFLYM7BLTHFU5FL4MRJPX4WPJ22QSDTZQI3UF3KC7GKN3TSHHWDUK/effects?limit=200

The query over the `horizon` db gives me the same result, 18.

```
SELECT sum(CASE
           WHEN type = 2 AND (details ->> 'asset_code') = 'WowToken'
             THEN (details ->> 'amount') :: DOUBLE PRECISION
           WHEN type = 3 AND (details ->> 'asset_code') = 'WowToken'
             THEN -1 * (details ->> 'amount') :: DOUBLE PRECISION
           WHEN type = 33 AND (details ->> 'bought_asset_code') = 'WowToken'
             THEN (details ->> 'bought_amount') :: DOUBLE PRECISION
           WHEN type = 33 AND (details ->> 'sold_asset_code') = 'WowToken'
             THEN -1 * (details ->> 'sold_amount') :: DOUBLE PRECISION
           ELSE 0 END) amount
FROM history_effects
WHERE history_account_id = (SELECT id
                            FROM history_accounts
                            WHERE address = 'GBTGFLYM7BLTHFU5FL4MRJPX4WPJ22QSDTZQI3UF3KC7GKN3TSHHWDUK')
```

#### Comments from @vogel 

> look at 2 last operations 60226681419337729
> and 60226891872735233
> those send native from GBTGFLYM7BLTHFU5FL4MRJPX4WPJ22QSDTZQI3UF3KC7GKN3TSHHWDUK
> then GC22OC7R4X4GGSBMRSWWF7UAWXDXLL6PAHVUEQTOAGYFHPHZ3R5L63XH converts them to WowCredit (as it is the only one that has offers for that)
> and then accpets
> so 2 last operations do not affect WowToken of GBTGFLYM7BLTHFU5FL4MRJPX4WPJ22QSDTZQI3UF3KC7GKN3TSHHWDUK

**Comment by howardtw** [comment]
Closing because this has been resolved in https://github.com/stellar/go/pull/543
