### ISSUE TITLE
The orders page throws an error when there is a partially filled order

### ISSUE THREAD

**Issue by Ipposnif** [stellar/go#2687]
Hi,
I noticed that every time I have an order that is partially matched, the \orders page shows this error message:

Whoops!
We couldn’t load that feature. Please try again!

**Comment by Ipposnif** [comment]
I'm using the official web site, and the error shows on page https://www.stellarx.com/activity/orders.
I have a pending  [GOLD GRAM] Sell order, partially filled. Actually, when I'm writing, it is still in front of the market at price 677.
Like I said before when I click Activity (https://www.stellarx.com/activity/orders) The error message is :

Whoops!
We couldn’t load that feature. Please try again!

**Comment by ire-and-curses** [comment]
Gotcha. I was asking how you came to this place to submit your issue because we are not part of StellarX (maybe they sent you a bad error message asking you to submit here?).

Please contact StellarX support here: https://stellarxsupport.zendesk.com/hc/en-us
Looks like it's a StellarX issue.
