### ISSUE TITLE
Add config option to stellar-core.cfg file

### ISSUE THREAD

**Issue by bartekn** [stellar/go#2706]
In the online mode users should be allowed to set their quorum slices and DB configuration. To allow this Horizon should accept a new config option with a path to `stellar-core.cfg` file. This file should be copied to a temp folder when `stellar-core` process is started.

**Comment by ire-and-curses** [comment]
Related core PR (this is in 13.2): https://github.com/stellar/stellar-core/pull/2574

**Comment by bartekn** [comment]
Fixed in https://github.com/stellar/go/pull/2823.
