### ISSUE TITLE
Use current Stellar-Core state when restarting

### ISSUE THREAD

**Issue by bartekn** [stellar/go#2708]
In the current code, `CaptiveStellarCore` always clears Stellar-Core state persisted to the database to catchup and start streamed from the last ledger ingested by Horizon. This can be improved if Stellar-Core ledger < Horizon ledger. In such case `CaptiveStellarCore` can fast-forward to the ledger it needs.

`CaptiveStellarCore` should also restart the process if forwarding would take too much time. The code similar to this was part of original `CaptiveStellarCore` but was removed to simplify experimental code. Now that we know the final API we can add it back.

**Comment by ire-and-curses** [comment]
This is blocked while we decide among possible options for online stellar-core.

**Comment by bartekn** [comment]
We decided to always use in-memory version by using https://github.com/stellar/go/issues/2842.
