### ISSUE TITLE
exp/services/webauth: remove genjwk command replace with jwk-keygen tool

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/go#2718]
### What
Remove `genjwk` command and replace with instructions in the README for how to use the [jwk-keygen] tool.

### Why
The webauth app contains a command for generating a new JSON Web Keys. This functionality is generic and not unique to webauth. It was added as a useful helper but deployers should generate keys using common standard tools. One tool that generates JWKs is the jwk-keygen tool released by Square and we could remove the code we need to maintain here by using it.

[jwk-keygen]: https://github.com/square/go-jose/tree/v2/jwk-keygen

**Comment by mollykarcher** [comment]
Closing all webauth issues
