### ISSUE TITLE
horizon db migrate up is unresponsive

### ISSUE THREAD

**Issue by huyntsgs** [stellar/go#2719]
Hi team,
I am upgrading to horizon 1.4.0 My stellar-core is already up to 13.1.0

After I run migrate command. It is about 3 hours over but not complete. There is not any message from horizon.
`horizon db migrate up 3 --db-url "postgresql://postgres:xxx@10.110.80.3:5432/horizon"`

Could you tell me how long does it take to upgrade from 1.2.0 to 1.4.0? Or i missed something? Thanks.

**Comment by ire-and-curses** [comment]
It can take a while, but it depends on how much of Stellar history your Horizon has ingested, and your hardware. It's also important to have sufficient extra disk space. During the migration postgres produces a temporary copy of the migrating table, which needs significant extra space. Please see the notes here: https://github.com/stellar/go/releases/tag/horizon-v1.1.0
