### ISSUE TITLE
DatabaseBackend should return TxSet in hash order

### ISSUE THREAD

**Issue by bartekn** [stellar/go#2721]
https://github.com/stellar/go/pull/2720 fixes a bug introduced in #2710: the order of transactions in `LedgerCloseMetaV0.TxSet` and results&meta in `LedgerCloseMetaV0.TxProcessing` are ordered differently. We should update `DatabaseBackend` to return `LedgerCloseMetaV0.TxSet` in a correct hash order.

**Comment by ire-and-curses** [comment]
For future reference, from communication with @jonjove "hash order" means
> lexicographical byte-wise comparison (of the transaction hash) based on https://en.cppreference.com/w/cpp/container/array/operator_cmp where the template parameter T = std::uint8_t
