### ISSUE TITLE
Go basic example fails with multi-value in single-value context error.

### ISSUE THREAD

**Issue by baroncharlus** [stellar/go#273]
The example here:

https://github.com/stellar/go/blob/master/docs/reference/examples.md

returns the following:
```
# command-line-arguments
./main.go:17:21: multiple-value build.Transaction() in single-value context
```
environment: go version go1.9.2 darwin/amd64

I have a PR coming that fixes the issue for me, but I might just be missing something. Haven't been gophering for long so no hard feelings either way.

**Comment by bartekn** [comment]
Closed by #274.
