### ISSUE TITLE
exp/services/recoverysigner: add keyset rotation command

### ISSUE THREAD

**Issue by howardtw** [stellar/go#2732]

**Comment by leighmcculloch** [comment]
I think alongside a command to rotate keys we also need tests in the general application code that test key rotation, decrypt, encrypt with different situations of rotating the keys.

**Comment by howardtw** [comment]
That's part of the plan. We will have to make sure we will be able to decrypt with old the signing keys after a rotation.

**Comment by howardtw** [comment]
Close by https://github.com/stellar/go/pull/2740. Not sure why it wasn't closed automatically when I merged the PR.
