### ISSUE TITLE
exp/services/recoverysigner: add encryption-tink-keyset-public config

### ISSUE THREAD

**Issue by howardtw** [stellar/go#2733]

**Comment by leighmcculloch** [comment]
We want this option, but I think I heard you mention during planning today that this option would allow starting up the service without the private key. Its use should require the specification of the private key too with the `encryption-tink-keyset` option. We don't have a use case where the service should run only with the public key.

**Comment by howardtw** [comment]
@leighmcculloch I summarized all the available options [here](https://github.com/stellar/go/pull/2730). Looks like we are saying we should remove (2). Can you point out which else options we should also remove? It hasn't been clear to me, and this is exactly the reason I opened this draft PR.

**Comment by leighmcculloch** [comment]
I'm closing this because of #2811.
