### ISSUE TITLE
stellar-hd-wallet probably shouldn't echo the passphrase

### ISSUE THREAD

**Issue by kfiresmith** [stellar/go#275]
Currently, stellar-hd-wallet echos back the user-input during entry of their seed-protection password [1].  

There are ways to prevent echo from stdin using already-dependent Go modules [2], so hopefully this should be a trivial enhancement to make.  It should probably also make the user enter it twice and diff to prevent typos.

I took a run at this in a personal fork, but I'm terrible with Go and couldn't get the desired result.

[1].  https://github.com/stellar/go/blob/master/tools/stellar-hd-wallet/commands/accounts.go#L43
[2].  https://godoc.org/golang.org/x/crypto/ssh/terminal#ReadPassword

**Comment by howardtw** [comment]
Hi @kfiresmith this would be a nice feature to add, but I think `stellar-hd-wallet` is meant to be used as a reference implementation, not something to use in production. I'm closing this one and #276.
