### ISSUE TITLE
exp/services/recoverysigner: add tests for the KMS client

### ISSUE THREAD

**Issue by howardtw** [stellar/go#2750]
We use [these](https://github.com/stellar/go/blob/51656b3c9a6f376ee5c32798f9dd3afcc8219b51/exp/services/recoverysigner/internal/crypto/mock_test.go) mocks to test to mock out the call to the kms client. However, we don't currently have a way to test the kms client in cmd/keyset.go. It's fairly important to test the tool as it's critical to make sure we can use the kms client without any problem when `encryption-kms-key-uri` is provided. Without the took working properly, we cannot start the recovery signer in a secure way.

Similarly, we don't have a way to exercise the code path when a valid kms key uri is provided [here](https://github.com/stellar/go/blob/51656b3c9a6f376ee5c32798f9dd3afcc8219b51/exp/services/recoverysigner/internal/crypto/crypto.go#L18).

**Comment by leighmcculloch** [comment]
Here's an idea for what we could do using the [local-kms](https://github.com/nsmithuk/local-kms) tool:

https://github.com/stellar/go/compare/recoverysigner-unique-signing-keys...recoverysigner-unique-signing-keys-kms-tests

**Comment by mollykarcher** [comment]
Closing all recoverysigner issues
