### ISSUE TITLE
exp/services/webauth: send application name to Horizon

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/go#2752]
### What
Send application name, but not version, in requests to Horizon using the Go SDKs config AppName field.

### Why
So that when running the webauth service alongside Horizon with other services that interact with Horizon, it is possible to distuingish in logs which requests have come from the webauth service and therefore possible to generate metrics on the usage of the Horizon API by the webauth service.

**Comment by ire-and-curses** [comment]
Could you expand on the "Why" a little? I'm having trouble grasping what this does.

**Comment by leighmcculloch** [comment]
> Could you expand on the "Why" a little? I'm having trouble grasping what this does.

Expanded. Let me know if that makes more sense.

**Comment by mollykarcher** [comment]
Closing all webauth issues
