### ISSUE TITLE
What needs to be done before the Scary Banner(tm) on stellar-hd-wallet can be removed?

### ISSUE THREAD

**Issue by kfiresmith** [stellar/go#276]
The Go reference implementation of SEP-0005 is the current best option for secure generation of HD keys.  I'd like to start building community documentation and support for this method of key generation ASAP because there is a real need for this functionality in the community that hasn't been met yet by any current popular offering.  

In addition to my own end-user testing (#275), I see it faced peer review prior to being merged.  Whatever other testing or evaluation needs to be done, please let me know, @bartekn. 

Thanks!

(https://github.com/stellar/go/blame/master/tools/stellar-hd-wallet/README.md#L10)

**Comment by howardtw** [comment]
Closing. See the [comment](https://github.com/stellar/go/issues/275#issuecomment-485513608).
