### ISSUE TITLE
"reingest" does not import accounts, assets and effects data

### ISSUE THREAD

**Issue by nengine** [stellar/go#277]
I didn't set INGEST=true at the beginning and now I wanted to import all historical data from stellar-core. I did "horizon db reingest", but accounts, assets and effects data was not imported. I do however see lots of data in ledger table.

Is reingest is a correct way to reimport the data from stellar-core?

Thanks.

**Comment by orbitlens** [comment]
Two days ago I run the `reingest` command on my node. Everything seems to be fine, assets and effects data was synced. 

Stellar Core v9.1.0
Horizon v0.12.0 Testing

**Comment by nullstyle** [comment]
Something else must be wrong if ledgers exist but not accounts assets or effects.  Could you try updating to the latest master and retrying @nengine

**Comment by nengine** [comment]
Hi, I have default settings as CATCHUP_COMPLETE=false at the stellar-core node, so when I checked ledgerseq at ledgerheaders table earlier sequence numbers are missing so may be stellar-core node may not have all transactions from the beginning?

**Comment by nullstyle** [comment]
If you use `CATCHUP_COMPLETE=false` then you'll only have a subset of the data in the ledger @nengine.  New accounts, effects, etc. will show up as they are added to the ledger.
