### ISSUE TITLE
Create integration tests for different ingestion backends

### ISSUE THREAD

**Issue by bartekn** [stellar/go#2812]
TBA I'm writing a doc about it but basically we need tests that check if a compiled binary ingest ledgers using different backends and in single/distributed ingestion environment. Testing it manually is error prone and slow.

**Comment by bartekn** [comment]
We discussed it a little bit in Horizon Team meeting and we agreed to start with a small test and then, maybe, build a framework if we find integration tests really useful and time saving.

We should follow the following points when running integration tests:
* Obtain a system under test.
* Seed necessary test data.
* Perform actions using the system under test.
* Verify behaviours.

In the first iteration this is how it could look like:
* **Obtain a system under test** Start a standalone network, simply by using a bash script. See the code in `stellar/quickstart` to understand how to do it. See if https://github.com/bats-core/bats-core recommended by @2opremio can be helpful here.
* **Seed necessary test data** Use `txnbuild` or `xdr2go` to submit some transactions. In the future we can start the network at new protocol version and submit new operations. We can also sync to pubnet or testnet to use existing network data as a seed.
* **Perform actions using the system under test** Use `txnbuild` or `xdr2go` to submit some transactions. Use `horizonclient` to get Horizon responses to check.
* **Verify behaviours** We should use the standard `testing` package test function and `testify/assert` for assertions. Tests should be part of `services/horizon` package. Should be skipped using [`T.Skip`](https://golang.org/pkg/testing/#T.Skip) if not in integration testing environment (ex. check Circle-CI env variable).

The simplest test can:
1. Connect to pubnet/testnet using Stellar-Core and start Horizon ingesting node.
2. Submit a transaction creating a new account sending payment to self.
3. Confirm if the transaction and the account changes are available via Horizon API.

**Comment by bartekn** [comment]
The simple integration tests framework was added in https://github.com/stellar/go/pull/2916. However, we will change the engine to use `stellar/horizon` instead of `stellar/quickstart`. This will make this more flexible. Moving to backlog.

**Comment by tamirms** [comment]
Improvements to the current implementation are tracked in https://github.com/stellar/go/issues/3031
