### ISSUE TITLE
txnbuild: Use strings to represent accounts in txnbuild operations

### ISSUE THREAD

**Issue by tamirms** [stellar/go#2813]
We have an `Account` interface to represent Stellar accounts. The interface includes functions to get the account address and the account sequence number. This interface is useful for describing the source account of a Stellar transaction since we need to obtain the sequence number in order to define the transaction.

Many transaction operations also include `Account` fields. However, we never need the sequence number of an account to build an operation XDR. Instead of using the `Account` interface in operation structs, it would be more ergonomic to use strings since we only care about he account address when constructing operations.

Replacing the type of `Account` fields in all operation structs would require a major version bump. We should plan to include this change in the 4.0.0 release of `txnbuild`.

**Comment by ire-and-curses** [comment]
This has been done, released in txnbuild v6.
