### ISSUE TITLE
Distributed ingestion vulnerable to starvation if one of the nodes is slow

### ISSUE THREAD

**Issue by bartekn** [stellar/go#2853]
Distributed ingestion introduced in 1.0.0 improves availability of Horizon ingestion. When one of ingesting nodes (or connected Stellar-Core instance) is down, the other ingesting nodes will continue ingestion. However, it's vulnerable to starvation. If one of the nodes is ingesting a ledger very slowly, the other nodes wait until it's done (release the ingestion lock).

The problem is not easy. It's possible that slowness of ingestion is due to a ledger with many ledger entry changes. Currently, I think we should defer to alerting in case of a slow ingestion and manually turning off the slow node. I'm opening this issue for visibility and discussion.

The issue was noticed by @MonsieurNicolas. Thanks!

**Comment by leighmcculloch** [comment]
> If one of the nodes is ingesting a ledger very slowly, the other nodes wait until it's done (release the ingestion lock).

When we've seen a node ingest slowly what was the cause of the slowness?

**Comment by bartekn** [comment]
1. Ledger with a ton of ledger entry changes.
1. Hardware issues in general and similar, ex. in AWS - running out of CPU BurstBalance.
1. Ledger backend slowness.
1. Horizon DB slowness (but then other ingesting nodes will be slow too).

**Comment by bartekn** [comment]
For the record: I was thinking about the trivial solution for this issue which is running multiple ingestion nodes against the same ledger and commit only the work of the fastest worker (that would cancel the other nodes work). Unfortunately it won't work because in all tx isolation levels in Postgres if one transaction updates a row the other one updating the same row will wait until the initial tx `COMMIT` or `ROLLBACK`. Because of this, if the initial tx gets stuck and does not close the tx the other nodes will wait indefinitely.

**Comment by bartekn** [comment]
I'm closing this because it seems hard to do without reinventing how ingestion system currently works. In https://github.com/stellar/go/pull/3645 I added recommended config to Horizon Admin guide to improve availability in case of connection issues.
