### ISSUE TITLE
Add simple instructions on How To Run Horizon For Dummies

### ISSUE THREAD

**Issue by irisli** [stellar/go#287]
I'm thinking of running my own Horizon server with minor source code changes (namely adding more pairs to orderbook).

Is it possible to add instructions on how to build from source?

**Comment by nebolsin** [comment]
I believe there're instructions on how to build from source in the [administration guide](https://github.com/stellar/go/blob/master/services/horizon/internal/docs/reference/admin.md#building).

**Comment by irisli** [comment]
@nebolsin Oh, good stuff, thanks.

**Comment by swetakedia** [comment]
@nebolsin I have followed the instructions give in admin guide. PFB the steps I have followed:

1. Installed go in /usr/local/ folder
2. set GOPATH to /usr/local/go in .profile file
3. Installed glide using - curl https://glide.sh/get | sh
4. created following directoru in /usr/local/go/src - github.com/stellar/
5. cd /usr/local/go/src/github.com/stellar 
6. git clone https://github.com/stellar/go.git && cd go
7. glide install
8. To build binary - go install github.com/stellar/go/services/horizon
However I am getting following error:

warning: GOPATH set to GOROOT (/usr/local/go) has no effect
github.com/stellar/go/clients/stellarcore/client.go:4:2: cannot find package "context" in any of:
/usr/local/go/src/github.com/stellar/go/vendor/context (vendor tree)
/usr/local/go/src/vendor/context
/usr/local/go/src/context (from $GOROOT)
($GOPATH not set)

If I print GOPATH - it shows - /usr/local/go
Moreover - glide install doesn't give me any error.

Can anyone help me out - where I am going wrong?

Go version is 1.6

@irisli  Let me know if you could successfully build the horizon.

**Comment by zulucrypto** [comment]
@swetakedia - I was able to get it installed on OS X by following the administration guide. I'm running go 1.9.4, so you could try upgrading your version of Go and see if that helps.

**Comment by nebolsin** [comment]
I think @swetakedia's problem has been solved in #291.

@irisli if admin guide answers your question this issue could probably be closed?

**Comment by irisli** [comment]
I still have yet to run my own Horizon, but I will assume that the guide @swetakedia wrote is good enough.

Thanks
