### ISSUE TITLE
Update ingestion effects processor to ingest sponsoring related effects

### ISSUE THREAD

**Issue by abuiles** [stellar/go#2891]
We need to update the effects processor to ingest the following effects:

- [ ] `sponsorship_created`: This appears when a new ledger entry is created and it has a sponsor. The effect will be associated with the operation creating the ledger entry. **Not all ledger entries have a created, removed, and update effect (e.g., offers) - we’ll add the accompanying sponsorship created effect only on the ledger entries which have effects**
- [ ] `sponsorship_updated`: This appears when a ledger entry is updated and the sponsor from the previous state is different to the current one. The effect will be associated with the operation updating the ledger entry.
- [ ] `sponsorship_removed`: This appears when a ledger entry is removed or as part of the `revoke_sponsorship_op`

Effects are processed in the `effects` functions in `transactionOperationWrapper`

Start in `history.EffectType = 60`

**Comment by bartekn** [comment]
Closed in https://github.com/stellar/go/pull/2951.
