### ISSUE TITLE
Facing issue while building horizon

### ISSUE THREAD

**Issue by swetakedia** [stellar/go#291]
Hi,

I need to build horizon for some development purpose.  I have followed all the steps as given in [https://github.com/stellar/go/blob/master/services/horizon/internal/docs/reference/admin.md#building](url)

PFB the details of the steps followed:

I followed following steps:
1. Installed go in /usr/local/ folder
2. set GOPATH to /usr/local/go in .profile file
3. Installed glide using - curl https://glide.sh/get | sh
4. created following directory in /usr/local/go/src - github.com/stellar/
5. cd /usr/local/go/src/github.com/stellar 
6. git clone https://github.com/stellar/go.git && cd go
7. glide install
8. To build binary - go install github.com/stellar/go/services/horizon
However I am getting following error:

**warning: GOPATH set to GOROOT (/usr/local/go) has no effect
github.com/stellar/go/clients/stellarcore/client.go:4:2: cannot find package "context" in any of:
/usr/local/go/src/github.com/stellar/go/vendor/context (vendor tree)
/usr/local/go/src/vendor/context
/usr/local/go/src/context (from $GOROOT)
($GOPATH not set)**

If I print GOPATH - it shows - /usr/local/go
Moreover - glide install doesn't give me any error. I am getting just one warning:

**[WARN]  Lock file may be out of date. Hash check of YAML failed. You may need to run 'update'**

Can anyone help me out - where I am going wrong?

Go version is 1.6

If I copy the context folder which is present inside goji in vendor folder. I am getting following error:
**warning: GOPATH set to GOROOT (/usr/local/go) has no effect
github.com/stellar/go/clients/stellarcore
../clients/stellarcore/client.go:140: req.WithContext undefined (type *http.Request has no field or method WithContext)**

**Comment by nebolsin** [comment]
The GOPATH environment variable is used to specify directories outside of $GOROOT that contain the source for Go projects and their binaries. A common setup is to set `GOPATH=$HOME/go` (this is also a default starting from Go 1.8). 

Also your Go version is quite old, you need to upgrade (`golang.org/x/net/context` package has been moved into the standard library as `context` starting from Go 1.7). I’d recommend you to upgrade to 1.9.

**Comment by swetakedia** [comment]
@nebolsin Thanks, The issue was with go version. Upgrading it to go 1.9 helped.
