### ISSUE TITLE
Federation server install/configure on linux server

### ISSUE THREAD

**Issue by guru-god** [stellar/go#2969]
### What problem does your feature solve?
My environment is as following : Linux (Centos), MySQL
I downloaded latest release of horizon and tried to upload cfg file as config and set dsn as mysql.
After all done of above, I run ./horizon, but it gives me error this : 

2020/08/29 15:56:33 Invalid config: db-url is blank. Please specify --db-url on the command line or set the DATABASE_URL environment variable.
I tried to find similar issue to mine, but I couldn't find answer.
### What would you like to see?
I'd like to know how to download/install federation server in detail step by step.

**Comment by ire-and-curses** [comment]
You mention federation server, but you are running Horizon. Which do you mean?

Horizon needs to know where you database is located. Please read https://github.com/stellar/go/blob/master/services/horizon/internal/docs/admin.md#configuring.

**Comment by guru-god** [comment]
@ire-and-curses Firstly, I downloaded https://github.com/stellar/go/tree/master/services/federation and I tried to build.
But I got errors.
`main.go:7:2: cannot find package "github.com/go-chi/chi" in any of:
        /usr/lib/golang/src/github.com/go-chi/chi (from $GOROOT)
        /root/go/src/github.com/go-chi/chi (from $GOPATH)
main.go:8:2: cannot find package "github.com/spf13/cobra" in any of:
        /usr/lib/golang/src/github.com/spf13/cobra (from $GOROOT)
        /root/go/src/github.com/spf13/cobra (from $GOPATH)
main.go:9:2: cannot find package "github.com/stellar/go/handlers/federation" in any of:
        /usr/lib/golang/src/github.com/stellar/go/handlers/federation (from $GOROOT)
        /root/go/src/github.com/stellar/go/handlers/federation (from $GOPATH)
main.go:10:2: cannot find package "github.com/stellar/go/support/app" in any of:
        /usr/lib/golang/src/github.com/stellar/go/support/app (from $GOROOT)
        /root/go/src/github.com/stellar/go/support/app (from $GOPATH)
main.go:11:2: cannot find package "github.com/stellar/go/support/config" in any of:
        /usr/lib/golang/src/github.com/stellar/go/support/config (from $GOROOT)
        /root/go/src/github.com/stellar/go/support/config (from $GOPATH)
main.go:12:2: cannot find package "github.com/stellar/go/support/db" in any of:
        /usr/lib/golang/src/github.com/stellar/go/support/db (from $GOROOT)
        /root/go/src/github.com/stellar/go/support/db (from $GOPATH)
main.go:13:2: cannot find package "github.com/stellar/go/support/errors" in any of:
        /usr/lib/golang/src/github.com/stellar/go/support/errors (from $GOROOT)
        /root/go/src/github.com/stellar/go/support/errors (from $GOPATH)
main.go:14:2: cannot find package "github.com/stellar/go/support/http" in any of:
        /usr/lib/golang/src/github.com/stellar/go/support/http (from $GOROOT)
        /root/go/src/github.com/stellar/go/support/http (from $GOPATH)
main.go:15:2: cannot find package "github.com/stellar/go/support/log" in any of:
        /usr/lib/golang/src/github.com/stellar/go/support/log (from $GOROOT)
        /root/go/src/github.com/stellar/go/support/log (from $GOPATH)`

**Comment by guru-god** [comment]
@ire-and-curses 
I uploaded federation.cfg file to the GO_PATH/bin because I could find federation file there. 
the cfg file was following toml syntax and it was like this

```
[database]
type = "mysql"
dsn = "dbuser:dbpassword@host/dbname"
```
But after I run `./federation`, I got this error.

`ERRO[2020-08-31T15:09:05.670Z] config file: invalid fields: Type`

Could you tell me what is wrong in my config file?
Thanks

**Comment by ire-and-curses** [comment]
Please read: https://github.com/stellar/go/tree/master/services/federation#config

MySQL is not supported.

**Comment by guru-god** [comment]
Does it support only pgsql?
