### ISSUE TITLE
Invalid begin_sponsor when multiple sponsoring sandwiches in a transaction

### ISSUE THREAD

**Issue by bartekn** [stellar/go#2989]
### What version are you using?

`protocol-14` branch.

### What did you do?

Submit a transaction with multiple sponsorships:
```
BEGIN_SPONSORING_FUTURE_RESERVES (source: A, sponsored_id: B)
BEGIN_SPONSORING_FUTURE_RESERVES (source: C, sponsored_id: D)
END_SPONSORING_FUTURE_RESERVES (source: B)
END_SPONSORING_FUTURE_RESERVES (source: D)
```

### What did you expect to see?

`begin_sponsor` fields on both `EndSponsoringFutureReserves` operations are the same.

### What did you see instead?

`begin_sponsor` fields should be different (point to actual sponsor).

I think we need to check IDs here instead of finding the first Begin operation:
https://github.com/stellar/go/blob/9f2f2e66f128fde9e321d226438e3861f9c6b391/services/horizon/internal/expingest/processors/operations_processor.go#L140-L151

**Comment by 2opremio** [comment]
Good catch!!

**Comment by 2opremio** [comment]
I had to close it manually, why aren't closing annotations working?

**Comment by 2opremio** [comment]
maybe because I am not an admin? (yet another reason to change that)

**Comment by abuiles** [comment]
I think it only works when the branch is merged to master.
