### ISSUE TITLE
How to build Claimable Balance Predicate on txbuild?

### ISSUE THREAD

**Issue by abuiles** [stellar/go#3000]
We should offer some high level helpers in `txnbuild` to make it easy for people to create claimable balances predicates.

Following the spirit of `txnbuild` users, final users should need access to the XDR library.

We could have some helpers like:

```
txnbuild.AndPredicate(left, right)
txnbuild.OrPredicate(left, right)
txnbuild.NotPredicate(left, right)
txnbuild.AbsBeforePredicate(int64)
txnbuild.RelBeforePredicate(int64)
```

**Comment by abuiles** [comment]
@Shaptic I added some initial helper here to help us write the integration tests https://github.com/abuiles/go/commit/6d3d8e8686a6e05b815ba0d79237daae98b1b47b -- we can use this for now internally, while we define the final interface for txnbuild.

**Comment by abuiles** [comment]
@2opremio @tamirms can you check the interface here https://github.com/abuiles/go/commit/6d3d8e8686a6e05b815ba0d79237daae98b1b47b#diff-53889a0fa496ed0e06224eaebe4319d7R25 -- this is just an initial version to help us write integration tests.

**Comment by Shaptic** [comment]
I cherry-picked the above commit as part of my [`predicate-tests`](https://github.com/Shaptic/go/tree/predicate-tests) branch (see [exact file](https://github.com/Shaptic/go/blob/predicate-tests/services/horizon/internal/txnbuild/create_claimable_balance.go) and added some things as I needed them for the tests.

**Comment by abuiles** [comment]
We had a conversation and decided to move forward with the factory method to create `xdr.ClaimPredicate`and keep a txnbuild struct to wrap the destination as a string and then the predicate as an xdr struct.

We'll have the following in txnbuild

```
type Claimant struct {
	Destination string
	Predicate   xdr.ClaimPredicate
}

func (c *Claimant) BuildXDR() (xdr.Claimant, error) {
  ...
}
func (c *Claimant) FromXDR(xdrClaimant xdr.Claimant) error {
  ...
}
```

**Comment by Shaptic** [comment]
This was implemented & merged in the above.
