### ISSUE TITLE
Unable to sign tx with KP generated with .Parse()

### ISSUE THREAD

**Issue by alien35** [stellar/go#304]
The documentation says: If the provided input is a seed, the resulting KP will have signing capabilities. Shouldn't the type KP consequently return a 'Seed() string' value or something similar?

**Comment by bartekn** [comment]
[`KP`](https://godoc.org/github.com/stellar/go/keypair#KP) is an interface and it has `Seed` method. Please post other questions you have to [Stack Exchange](https://stellar.stackexchange.com/).
