### ISSUE TITLE
Refactor sponsorship integration tests

### ISSUE THREAD

**Issue by 2opremio** [stellar/go#3075]
* They are really verbose.
* They use `assert.Eventually` which apparently isn't necessary (Horizon seems to guarantee strict ordering after submitting a transaction).
* Part of the machinery could be moved into the integration-test infrastructure.
* Test could potentially be merged (they all follow a similar workflow). It may not be possible since different tests have different particularities (e.g. claimable balances cannot be explicitly revoked).

**Comment by Shaptic** [comment]
I haven't been exposed much to the sponsorship tests, and it would be good to familiarize myself with that side of the Protocol 14 changes. Do you mind if I pick this up?

**Comment by 2opremio** [comment]
Of course not, go ahead!
