### ISSUE TITLE
Consider renaming predicate JSON fields to snake case

### ISSUE THREAD

**Issue by bartekn** [stellar/go#3079]
### What version are you using?

1.9.0

### What did you do?

Request claimable balance created by @abuiles: https://horizon-testnet.stellar.org/claimable_balances/0000000043d380c38a2f2cac46ab63674064c56fdce6b977fdef1a278ad50e1a7e6a5e18:

```json
    {
      "destination": "GB6QDNU47MYBR4NDTRP7M3FW27DAFOEADN5KDQI2DAVWW6YVKKG4QJS7",
      "predicate": {
        "and": [
          {
            "not": {
              "absBefore": "2020-09-30T16:19:04Z"
            }
          },
          {
            "or": [
              {
                "absBefore": "2020-09-30T16:34:04Z"
              },
              {
                "not": {
                  "absBefore": "2020-10-01T22:17:24Z"
                }
              }
            ]
          }
        ]
      }
    }
```

### What did you expect to see?

`abs_before` - snake case name consistent with other fields.

### What did you see instead?

`absBefore` - camel case.

**Comment by abuiles** [comment]
Fixed in https://github.com/stellar/go/pull/3086
