### ISSUE TITLE
header_xdr not set in ledgers endpoint

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/go#308]
Call one of the `ledgers` endpoints (single ledger or multiple ledgers).

For example: https://www.stellar.org/laboratory/#explorer?resource=ledgers&endpoint=all&values=eyJvcmRlciI6ImRlc2MifQ%3D%3D&network=public

the field `header_xdr` seems to be all 0s

expected:
actual header that was ingested.

```
  "header_xdr": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
```

**Comment by bartekn** [comment]
And it's not present at all in testnet: https://horizon-testnet.stellar.org/ledgers?order=desc&limit=1

I checked if maybe it's a bug in https://github.com/stellar/go/pull/338 but it's not related.
