### ISSUE TITLE
json: cannot unmarshal number into Go struct field RevokeSponsorship.offer_id of type string

### ISSUE THREAD

**Issue by bartekn** [stellar/go#3081]
### What version are you using?

1.9.0

### What did you do?

Found this transaction when checking the logs:
https://horizon-protocol14.stellar.org/transactions/36c0f3aaf915667f3a15ef2bba2df4496f17a78e82112e58d26deef6dc203957 it's `/operations` return 500:
https://horizon-protocol14.stellar.org/transactions/36c0f3aaf915667f3a15ef2bba2df4496f17a78e82112e58d26deef6dc203957/operations
and the following error:
```
json: cannot unmarshal number into Go struct field RevokeSponsorship.offer_id of type string
```

**Comment by bartekn** [comment]
OK, I think it was fixed in https://github.com/stellar/go/pull/3072. @2opremio you can close this if it's the same bug.

**Comment by 2opremio** [comment]
I do think it's the same bug but... could you test on testnet to be sure?

**Comment by bartekn** [comment]
The problem is here. We save the offer_id as string:
https://github.com/stellar/go/blob/47e9c166af25331dd4c451a0cca72565e29016bf/services/horizon/internal/expingest/processors/operations_processor.go#L492
but then it's unmarshaled into int64:
https://github.com/stellar/go/blob/47e9c166af25331dd4c451a0cca72565e29016bf/protocols/horizon/operations/main.go#L259

**Comment by 2opremio** [comment]
@bartekn note the `string` tag (i.e. it will accept a string even if it's an int64). I tested it.

Also, you were testing it on the 1.19 RC and not on the the GA release. I do think it's the same bug but I will eat my hat if you reproduce it on testnet (with the 1.19 final release)

**Comment by 2opremio** [comment]
PS: it's being tested at https://github.com/stellar/go/blob/8535626b249d88f0098d11322c17f9a12c3466ad/services/horizon/internal/integration/protocol14_sponsorship_ops_test.go#L829

**Comment by abuiles** [comment]
@2opremio @bartekn I smoke test this in testnet and the problem is fixed - https://horizon-testnet.stellar.org/transactions/02a69bb0dc83d004ae918aab2d10c9dbc2cbf4451ab12927a691b87e5c6c5079/operations 

The `string` tag @2opremio  pointed above does the right thing and also the PR where the fixed was introduced mentions this specific scenario: `* Fix type for RevokeSponsorship's OfferID field, which was causing a 500 error on `/operations` due to an unmarshalling error.`

**Comment by bartekn** [comment]
@abuiles thanks for checking!
