### ISSUE TITLE
cursor in /claimable_balances not validated

### ISSUE THREAD

**Issue by bartekn** [stellar/go#3085]
### What version are you using?

1.9.0

### What did you do?

Request `/claimable_balances` with invalid `cursor` value. Ex: https://horizon-testnet.stellar.org/claimable_balances?cursor=1003529-00000043d380c38a2f2cac46ab63674064c56fdce6b977fdef1a278ad50e1a7e6a5e18 (hex-encoded balance id is malformed).

### What did you expect to see?

`400 Bad Request` response.

### What did you see instead?

`500 Internal Server Error` response.

**Comment by abuiles** [comment]
Fixed in #3088
