### ISSUE TITLE
test db migrations in horizon

### ISSUE THREAD

**Issue by tomerweller** [stellar/go#311]
migrations are mostly untested right now. important for new releases

**Comment by alpe** [comment]
Are you planning to verify that migrations are correct or that the model works with the upgraded DB? I did some integration tests for bifrost last year that included DB migrations, but my focus was on the model/ logic. fyi: https://github.com/alpe/go/blob/bifrost_recover/services/bifrost/database/submission_store_integration_test.go

**Comment by 2opremio** [comment]
For Horizon, up-migrations are tested in every test using the DB (probably down migrations too, I will confirm)
