### ISSUE TITLE
Debug slow ingestion (2020-10-14)

### ISSUE THREAD

**Issue by bartekn** [stellar/go#3128]
### What version are you using?

1.9.1

### What did you do?

On 2020-10-14 between 0:30-1:30am UTC pubnet ingestion was slower, with average ingestion duration on all pubnet ingesting instances of 1.5s. It looks like there were many trustline updates in the ledgers and we don't batch updates. Maybe this would improve the speed?

<sup>(chart time in UTC+2)</sup>
<img width="823" alt="Screenshot 2020-10-14 at 11 22 39" src="https://user-images.githubusercontent.com/464938/95969881-93172d00-0e0f-11eb-97ea-aa5e15cad82c.png">

Ledgers with ingestion duration >=4s:

Time | horizon_msg | horizon_sequence | horizon_duration | horizon_stats_accounts_updated | horizon_stats_operations_in_successful | horizon_stats_trust_lines_updated
-- | -- | -- | -- | -- | -- | --
October 14th 2020, 01:15:03.464 | Processed ledger | 32,087,698 | 4.188 | 299 | 969 | 1,784
October 14th 2020, 01:14:53.029 | Processed ledger | 32,087,696 | 4.307 | 282 | 962 | 1,794
October 14th 2020, 01:12:34.908 | Processed ledger | 32,087,670 | 5.867 | 322 | 992 | 1,841
October 14th 2020, 01:10:51.408 | Processed ledger | 32,087,651 | 4.263 | 237 | 929 | 1,749
October 14th 2020, 01:10:08.787 | Processed ledger | 32,087,643 | 4.166 | 248 | 927 | 1,742
October 14th 2020, 01:09:49.115 | Processed ledger | 32,087,639 | 5.801 | 185 | 883 | 1,695
October 14th 2020, 01:08:54.166 | Processed ledger | 32,087,629 | 4.1 | 363 | 938 | 1,703
October 14th 2020, 01:05:36.281 | Processed ledger | 32,087,592 | 4.599 | 279 | 962 | 1,790
October 14th 2020, 01:05:25.375 | Processed ledger | 32,087,590 | 4.388 | 260 | 943 | 1,762
October 14th 2020, 01:04:08.807 | Processed ledger | 32,087,576 | 4.085 | 258 | 942 | 1,767
October 14th 2020, 01:03:36.784 | Processed ledger | 32,087,570 | 4.008 | 262 | 944 | 1,764
October 14th 2020, 01:02:18.998 | Processed ledger | 32,087,555 | 4.333 | 272 | 958 | 1,793
October 14th 2020, 01:01:29.650 | Processed ledger | 32,087,546 | 4.069 | 261 | 947 | 1,761
October 14th 2020, 01:00:38.261 | Processed ledger | 32,087,536 | 4.512 | 237 | 928 | 1,744
October 14th 2020, 00:56:35.219 | Processed ledger | 32,087,490 | 4.83 | 240 | 941 | 1,759
October 14th 2020, 00:56:23.056 | Processed ledger | 32,087,488 | 4.254 | 240 | 926 | 1,737
October 14th 2020, 00:55:05.281 | Processed ledger | 32,087,473 | 4.524 | 251 | 937 | 1,756
October 14th 2020, 00:54:54.563 | Processed ledger | 32,087,471 | 4.249 | 260 | 944 | 1,757
October 14th 2020, 00:51:10.391 | Processed ledger | 32,087,429 | 4.081 | 270 | 947 | 1,777
October 14th 2020, 00:50:37.886 | Processed ledger | 32,087,423 | 4.01 | 215 | 909 | 1,717
October 14th 2020, 00:50:06.367 | Processed ledger | 32,087,417 | 4.427 | 235 | 925 | 1,738
October 14th 2020, 00:48:34.937 | Processed ledger | 32,087,400 | 4.304 | 365 | 938 | 1,689
October 14th 2020, 00:48:26.316 | Processed ledger | 32,087,398 | 6.35 | 255 | 933 | 1,752
October 14th 2020, 00:48:04.591 | Processed ledger | 32,087,394 | 4.763 | 238 | 931 | 1,743
October 14th 2020, 00:47:54.561 | Processed ledger | 32,087,392 | 5.579 | 293 | 968 | 1,797
October 14th 2020, 00:47:11.161 | Processed ledger | 32,087,384 | 5.002 | 269 | 949 | 1,767
October 14th 2020, 00:46:49.368 | Processed ledger | 32,087,380 | 4.032 | 259 | 938 | 1,754
October 14th 2020, 00:46:39.114 | Processed ledger | 32,087,378 | 4.496 | 263 | 948 | 1,772
October 14th 2020, 00:46:07.114 | Processed ledger | 32,087,372 | 4.075 | 302 | 979 | 1,809
October 14th 2020, 00:45:36.024 | Processed ledger | 32,087,366 | 4.699 | 345 | 891 | 1,604
October 14th 2020, 00:45:13.863 | Processed ledger | 32,087,362 | 4.574 | 262 | 948 | 1,770

**Comment by bartekn** [comment]
Similar thing happened yesterday:
<img width="826" alt="Screenshot 2020-10-29 at 12 33 58" src="https://user-images.githubusercontent.com/464938/97563222-065d9900-19e3-11eb-9b16-774a1b573f49.png">
<img width="830" alt="Screenshot 2020-10-29 at 12 34 11" src="https://user-images.githubusercontent.com/464938/97563251-0d84a700-19e3-11eb-8076-ee1b9b9258f9.png">
However, I checked the code again and we do batch trust line updates. Would be great debugging why it's that slow.

**Comment by 2opremio** [comment]
@bartekn wasn't this resolved?

**Comment by bartekn** [comment]
Haven't happened since then. Will reopen if something like occurs again.
