### ISSUE TITLE
Ensure that it's possible to create accounts with zero starting balance.

### ISSUE THREAD

**Issue by Shaptic** [stellar/go#3141]
With the introduction of Protocol 14 and specifically [CAP-33](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0033.md), accounts can now be created **without** a starting balance when they are sponsored.

The [CAP notes](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0033.md#operation-validity-changes):
> **Operation Validity Changes**  
> Any downstream system relying on the fact that `CreateAccountOp` is invalid if `startingBalance = 0` will be affected.

This subtlety is easy to overlook, so please ensure that the SDK allows this updated constraint.

**If this SDK validates the starting balance to prevent starting balances of zero, please update the SDK to allow it.** When a transaction is submitted the Stellar network will ensure the amount is non-zero if it needs to be in the specific situations it is required, but SDKs should no longer require it for all cases.

**Comment by Shaptic** [comment]
I've confirmed that this is already possible with the Go SDK by trying out the following integration test:
```go
	t.Run("ZeroBalance", func(t *testing.T) {
		keys, accounts := itest.CreateAccounts(2, "1000")
		sponsor, sponsorPair := accounts[0], keys[0]
		newAccountKeys := keypair.MustRandom()
		newAccountID := newAccountKeys.Address()
		ops := []txnbuild.Operation{
			&txnbuild.BeginSponsoringFutureReserves{SponsoredID: newAccountID},
			&txnbuild.CreateAccount{
				Destination: newAccountID,
				Amount:      "0",
			},
			&txnbuild.EndSponsoringFutureReserves{
				SourceAccount: &txnbuild.SimpleAccount{AccountID: newAccountID},
			},
		}

		signers := []*keypair.Full{sponsorPair, newAccountKeys}
		txResp, err := itest.SubmitMultiSigOperations(sponsor, signers, ops...)
		itest.LogFailedTx(txResp, err)
	})
```
There were no errors.

**Comment by ire-and-curses** [comment]
Nice!

**Comment by Shaptic** [comment]
We can do better than a one-off test: #3142 adds a permanent unit test. :blush:
