### ISSUE TITLE
xdr: github.com/lib/pq and other database code has crept into the xdr package

### ISSUE THREAD

**Issue by nullstyle** [stellar/go#3152]
--- SDF golang folks ---
Hey y'all,

Long time no interact;  Hope everyone is doing well. 
--- We now resume your regularly scheduled issue  ---

As part of https://github.com/stellar/go/commit/d49164254ee4d543d520d1e8581f2f75c1f06d3e, the `xdr` package picked up a -- in my opinion at least -- heavy-weight package dependency in the way of `github.com/lib/pq`.  When I was originally envisioning the `xdr` package it would try to keep package dependencies to a minimum, and IMO `pq` is over the line.  I don't think golang projects that interact with stellar should need to import postgres related code to get up in running.  As an example of some of the badness, I can show the output of `depth ./network`:

```
(base) ➜  go git:(master) ✗ depth ./network
./network
  ├ bytes
  ├ strings
  ├ github.com/stellar/go/hash
  │ └ crypto/sha256
  ├ github.com/stellar/go/support/errors
  │ └ github.com/pkg/errors
  │   ├ fmt
  │   ├ io
  │   ├ path
  │   ├ runtime
  │   └ strings
  └ github.com/stellar/go/xdr
    ├ bytes
    ├ database/sql/driver
    ├ encoding
    ├ encoding/base64
    ├ encoding/binary
    ├ encoding/hex
    ├ errors
    ├ fmt
    ├ io
    ├ math/big
    ├ regexp
    ├ sort
    ├ strconv
    ├ strings
    ├ github.com/lib/pq
    │ ├ bufio
    │ ├ bytes
    │ ├ context
    │ ├ crypto/md5
    │ ├ crypto/sha256
    │ ├ crypto/tls
    │ ├ crypto/x509
    │ ├ database/sql
    │ ├ database/sql/driver
    │ ├ encoding/binary
    │ ├ encoding/hex
    │ ├ errors
    │ ├ fmt
    │ ├ io
    │ ├ io/ioutil
    │ ├ math
    │ ├ net
    │ ├ net/url
    │ ├ os
    │ ├ os/user
    │ ├ path
    │ ├ path/filepath
    │ ├ reflect
    │ ├ runtime
    │ ├ sort
    │ ├ strconv
    │ ├ strings
    │ ├ sync
    │ ├ sync/atomic
    │ ├ time
    │ ├ unicode
    │ ├ github.com/lib/pq/oid
    │ └ github.com/lib/pq/scram
    │   ├ bytes
    │   ├ crypto/hmac
    │   ├ crypto/rand
    │   ├ encoding/base64
    │   ├ fmt
    │   ├ hash
    │   ├ strconv
    │   └ strings
    ├ github.com/stellar/go-xdr/xdr3
    │ ├ fmt
    │ ├ io
    │ ├ math
    │ ├ reflect
    │ ├ strconv
    │ └ time
    ├ github.com/stellar/go/strkey
    │ ├ bytes
    │ ├ encoding/base32
    │ ├ encoding/binary
    │ ├ github.com/stellar/go/crc16
    │ │ ├ bytes
    │ │ ├ encoding/binary
    │ │ └ errors
    │ └ github.com/stellar/go/support/errors
    └ github.com/stellar/go/support/errors
49 dependencies (39 internal, 10 external, 0 testing).
```

It looks like these changes were made to support the changes made to horizon ingestion; IMO It's not really good practice to have horizon specific database code to leak out into the lower level structures of the codebase.  To solve this, horizon should wrap the native XDR types in `pq`-specific boxes that define `Scan()`  as appropriate.  

Would y'all be open to a pull request implementing this refactoring?  Happy to discuss further.

**Comment by nullstyle** [comment]
Things look much nicer when you simply delete `xdr/db.go`:  

```
(base) ➜  go git:(master) ✗ rm xdr/db.go
(base) ➜  go git:(master) ✗ depth ./network
./network
  ├ bytes
  ├ strings
  ├ github.com/stellar/go/hash
  │ └ crypto/sha256
  ├ github.com/stellar/go/support/errors
  │ └ github.com/pkg/errors
  │   ├ fmt
  │   ├ io
  │   ├ path
  │   ├ runtime
  │   └ strings
  └ github.com/stellar/go/xdr
    ├ bytes
    ├ encoding
    ├ encoding/base64
    ├ encoding/binary
    ├ errors
    ├ fmt
    ├ io
    ├ math/big
    ├ regexp
    ├ sort
    ├ strconv
    ├ strings
    ├ github.com/stellar/go-xdr/xdr3
    │ ├ fmt
    │ ├ io
    │ ├ math
    │ ├ reflect
    │ ├ strconv
    │ └ time
    ├ github.com/stellar/go/strkey
    │ ├ bytes
    │ ├ encoding/base32
    │ ├ encoding/binary
    │ ├ github.com/stellar/go/crc16
    │ │ ├ bytes
    │ │ ├ encoding/binary
    │ │ └ errors
    │ └ github.com/stellar/go/support/errors
    └ github.com/stellar/go/support/errors
26 dependencies (19 internal, 7 external, 0 testing).
```

Of course, that won't actually perform the refactoring, I simply wanted to show the potential for cleaning up the dependency tree.

**Comment by abuiles** [comment]
@nullstyle hey welcome back! what you are proposing makes sense. It seems like the actual struct that depends on it is `xdr.Price`.  And by looking at the code, it seems like we might be able to keep `Scan` and `Value` without depending on pq.

If we go with your route we should probably check that no other services/app rely on this behavior, since this would be a breaking change.

**Comment by nullstyle** [comment]
@abuiles good point regarding keeping the change minimal and non-breaking where we can.

**Comment by nullstyle** [comment]
Here's a rough cut:  https://github.com/stellar/go/compare/master...nullstyle:depq

Thoughts?

**Comment by leighmcculloch** [comment]
I think that diff looks good but since it is a breaking change I agree with @abuiles that we should target a v5 release of the Go SDK. The change is a worse kind of breaking change; it is a subtle breaking change that breaks at runtime and not compile time. If code is already using `xdr.Price` with `"sql".Rows.Scan(...)`, when we remove the `Scan` function from the Go SDK, the code will continue to compile but will error at runtime.

It's not surprising we introduced this dependency into the xdr package and it is possible we've made or will make this mistake again here or in other packages since the Go SDK packages, Horizon, and all our services in this repo share a single Go Module. It's very easy to introduce a dependency into the Go SDK without realizing. It would be harder for us to make this mistake if we took on the multiple modules work we have planned (https://github.com/stellar/go/issues/1237) and made the Go SDK, Horizon, and each service have its own Go Module. Until we make the change towards separate Go Modules technically lib/pq is part of the dependency graph of any module importing the xdr package, even if the xdr package doesn't import it. cc @ire-and-curses

**Comment by nullstyle** [comment]
@leighmcculloch sounds like you guys have some bigger plans for the code than my change will fit with.    I'll rock on my own fork while you all make whatever structural changes you've got in the pipelines.   Thanks for the heads up!

**Comment by nullstyle** [comment]
It's also worth noting, even though the dependency would technically remain until the monorepo is separated  into modules, that's not really the issue i'm concerned with.  In my case, I'm building a binary whose go code I want to audit on a package by package basis, regardless of modules; I only am concerned about the import graph.

**Comment by nullstyle** [comment]
Ping.  Correct me if I'm wrong but you guys have done the v5 release, right?    This fix doesn't seem to have gotten in.  Could someone from the SDF clarify what you guys are expecting from me with regards to closing this issue?  Who is deciding on what gets into the v6 release and whats the expected timeframe?

**Comment by ire-and-curses** [comment]
v5 got released in a hurry to handle breaking SEP changes. There isn't a timeframe for v6 yet. It is lower priority than other things we have to do (like getting the fast txmeta out the door by end of year). In the meantime I'd like to leave this open if that works for you.

**Comment by nullstyle** [comment]
word

**Comment by bartekn** [comment]
I checked the issue and it looks like we no longer use `xdr.Price.Scan` anywhere in `stellar/go` since https://github.com/stellar/go/commit/599673d1b9746ace4701bfe2668f224e80aabd0d which changed the trade aggregations query to not return arrays. I opened the PR to remove the function in https://github.com/stellar/go/pull/3646, as suggested above this can be a breaking change for some folks so better to release it in a major bump version.

**Comment by leighmcculloch** [comment]
@bartekn I think #3646 addresses the worst part of this problem, the introduction of the lib/pq dependency into the xdr package, but I don't think it is completely addressed. The xdr package still contains database code which seems like responsibility creep to me, and I think was what @nullstyle was getting at.

For example:
https://github.com/stellar/go/blob/11f0c3f96df0ac113341d8a00fdc295fe30f246f/xdr/db.go#L13-L21

These functions don't need to live in the `xdr` package. We can define types such as `AccountFlagsDB` that embed the xdr type and provide a `Scan` function. 

For example:

```
type AccountFlagsDB AccountFlags

func (t *AccountFlagsDB) Scan(src interface{}) error {
	// ...
}
```

Horizon can scan into the `AccountFlagsDB`, and then the value can be cast to `AccountFlags` for use elsewhere.

I think they should probably be moved into horizon's internal package unless we plan to support this functionality as part of the Go SDK long term.

**Comment by bartekn** [comment]
Makes sense! Reopening.

**Comment by 2opremio** [comment]
While I agree that those methods shouldn't necessarily live there. However, the reality is that Go enforces defining methods in the same package as the type.

We could use synonyms as @leighmcculloch suggests but:

1. I find that to be pretty artificial.

2. `Scan()/Value()` implementation checking is dynamic and I don't trust our current test coverage to catch all the problems (I quickly tried removing db.go and after running all the horizon tests I only got errors for the `Asset` type)

IMO, it's not worth the pain. Please reopen if you disagree.

**Comment by nullstyle** [comment]
I'm sorry, but completely dismissing my concerns (which are not artificial) is not acceptable.  

I mean come on guys, I've waited patiently for nearly a year for you to incorporate this simple, miniscule change -- with a patch provided -- to only have this show back up closed the next time I log into github.  This is not cool @bartekn 

So, do you guys just recommend I fork the SDK and go my own way?

**Comment by nullstyle** [comment]
love it:

```
(base) ➜  go git:(master) depth ./network
./network
  ├ bytes
  ├ strings
  ├ github.com/stellar/go/hash
  │ └ crypto/sha256
  ├ github.com/stellar/go/support/errors
  │ └ github.com/pkg/errors
  │   ├ errors
  │   ├ fmt
  │   ├ io
  │   ├ path
  │   ├ runtime
  │   ├ strconv
  │   └ strings
  └ github.com/stellar/go/xdr
    ├ bytes
    ├ database/sql/driver
    ├ encoding
    ├ encoding/base64
    ├ encoding/binary
    ├ encoding/hex
    ├ encoding/json
    ├ errors
    ├ fmt
    ├ io
    ├ math/big
    ├ regexp
    ├ sort
    ├ strconv
    ├ strings
    ├ time
    ├ github.com/pkg/errors
    ├ github.com/stellar/go-xdr/xdr3
    │ ├ fmt
    │ ├ io
    │ ├ math
    │ ├ reflect
    │ ├ strconv
    │ └ time
    ├ github.com/stellar/go/strkey
    │ ├ bytes
    │ ├ encoding/base32
    │ ├ encoding/binary
    │ ├ github.com/stellar/go/crc16
    │ │ ├ bytes
    │ │ ├ encoding/binary
    │ │ └ errors
    │ └ github.com/stellar/go/support/errors
    └ github.com/stellar/go/support/errors
29 dependencies (22 internal, 7 external, 0 testing).```
