### ISSUE TITLE
Make integration tests work with Captive core

### ISSUE THREAD

**Issue by 2opremio** [stellar/go#3153]
There was an initial effort at #3114  (which didn't work because of #3137). The current effort is at #3144

**Comment by 2opremio** [comment]
This is blocked by #3157

**Comment by 2opremio** [comment]
And now it's blocked by https://github.com/stellar/stellar-core/issues/2778

**Comment by tamirms** [comment]
fixed by https://github.com/stellar/go/pull/3291
