### ISSUE TITLE
account creation with horizon api

### ISSUE THREAD

**Issue by kiahmed** [stellar/go#318]
how can I create a new account in testnet with just http call to horizon rest api something like this 35.199.39.129:8000/friendbot ? Doc says [here](https://www.stellar.org/developers/guides/get-started/create-account.html) to use some sdk but I wanna integrate from an enterprise app context where I can't really run js client lib sdk or other lang , it has to be a simple dynamic rest api call returning new account id and details on successful creation.  Also, if mainnet requires an existing account with fund to issue another account , then how do the very first account with fund gets issued..

Some quick help greatly appreciated.

**Comment by bartekn** [comment]
Please ask questions in [Stack Exchange](https://stellar.stackexchange.com/). This section is for issues and bugs only.
