### ISSUE TITLE
Unable to send payments

### ISSUE THREAD

**Issue by nagarwa2** [stellar/go#3188]
### What version are you using?
"horizon_version": "1.10.1-c5107ad336973eecbf3b0cef587f631df4f0f658"
"core_version": "stellar-core 14.1.1 (5b2989d334f578b00ac9b5996888257f5922a8a4)"

### What did you do?
Upgraded and restarted the horizon server.

### What did you expect to see?
Able to send payments for an account.

### What did you see instead?
Whenever I am trying to send payment operation using stellar java sdk (v0.21.1), I am getting below response from server
org.stellar.sdk.responses.SubmitTransactionTimeoutResponseException: Timeout. Please resubmit your transaction to receive submission status. More info: https://www.stellar.org/developers/horizon/reference/errors/timeout.html
	at org.stellar.sdk.Server.submitTransactionXdr(Server.java:269)
	at org.stellar.sdk.Server.submitTransaction(Server.java:303)
	at org.stellar.sdk.Server.submitTransaction(Server.java:344)

Using below java code to send payments 
```
Builder transactionBuilder = new Transaction.Builder(sourceAccount,selectedNetwork).addOperation( new PaymentOperation.Builder(destination.getAccountId(), new AssetTypeNative(), amount.toPlainString()) .build()).setBaseFee(200) .setTimeout(10);
 if (memoReference != null) { 
MemoText memo = Memo.text(memoReference); 
transactionBuilder.addMemo(memo); 
} 
Transaction transaction = transactionBuilder.build(); transaction.sign(account); 
SubmitTransactionResponse response = stellarHorizonServer.submitTransaction(transaction);
```

This was working before. Can anybody please let me know what I am doing wrong ?

**Comment by ire-and-curses** [comment]
Did this start failing after the Horizon upgrade? Is the Horizon version you quoted the previous version or the upgraded version?

Are you running on testnet or pubnet?

Does the code work against SDF Horizon servers?

**Comment by nagarwa2** [comment]
This is the upgraded version. Looks like it start after the upgrade as previously it was working as expected. I used to not see timeouts. 

In this version, every transaction is going into timeout. I am running on pubnet.

I am able to connect and make payments through SDF Horizon servers but I see the same error without receiving transaction hash in response.

**Comment by ire-and-curses** [comment]
Could you elaborate on what you mean by

>I am able to connect and make payments through SDF Horizon servers but I see the same error without receiving transaction hash in response.

Are you saying you never get a successful response from SDF pubnet servers? How do you know the payment succeeded? Can you share a Horizon link to the successful payment?

**Comment by nagarwa2** [comment]
Yes, I do not get a response and see the timeout error. But after some time when I see the wallet, the transaction was successful. 
One of the transaction with the above scenario : 
https://stellarchain.io/tx/de3f49fa3848418a944f74f9434f62fdd623a01aba3783c615086d474eb0c4a9

**Comment by nagarwa2** [comment]
Hello, any update on this ?

**Comment by ire-and-curses** [comment]
We'll try and repro this. It may be an SDK issue. If you are able to try a similar TX submission with another SDK against your Horizon instance, that would be helpful, but not essential.

**Comment by bartekn** [comment]
@nagarwa2 it would help if you could send Horizon logs from around the time you submit transaction. There are multiple reasons why it can be happening:
* Surge pricing in the network (but looking at the fee in your tx and the number of ops in the ledger it should be good),
* Horizon is lagging (currently Horizon needs to be synced with Horizon for transaction submission to work correctly),
* Stellar-Core is lagging (delays submitting transaction to the network).

**Comment by tamirms** [comment]
I was able to send transactions to https://horizon-testnet.stellar.org/ using v0.21.1 of the Java SDK. The only issue I experienced was that 10 seconds was too low of a timebounds for the transaction and I received a response with a `tx_too_late` error code. However, once I increased the timebounds to 100 seconds, I always got a successful transaction response

**Comment by ire-and-curses** [comment]
@nagarwa2 does increasing your timebounds solve the problem for you?

**Comment by nagarwa2** [comment]
Unfortunately no. Strange thing I have noticed is when I deploy my JAVA application to IBM server and try to make payment using https://horizon.stellar.org I get response as null while the same code works on my local. I did change the timeout to 180 seconds but still no luck.

**Comment by nagarwa2** [comment]
Ok, so finally figured out the issue. My server time was not in sync. After sync it started working.
