### ISSUE TITLE
module .. does not contain package github.com/stellar/go/clients/txnbuild

### ISSUE THREAD

**Issue by aanupam23** [stellar/go#3202]
### What version are you using?
v0.0.0-20201109195737-ef1e30d4691b

### What did you do?
There is an incorrect installation command in txnbuild README.md which specifies Installation instruction as 
```
    go get github.com/stellar/go/clients/txnbuild
```

The above command is incorrect since txnbuild is not part of client directory. If the above command is used, the below error message will be displayed
```
module github.com/stellar/go@upgrade found (v0.0.0-20201109195737-ef1e30d4691b), but does not contain package github.com/stellar/go/clients/txnbuild
```

This should be 
```
go get github.com/stellar/go/txnbuild
```

### What did you expect to see?
I expected the installation of txnbuild.

### What did you see instead?
It threw error

**Comment by leighmcculloch** [comment]
Thanks @aanupam23. I am correcting the installation instructions in #3207.
