### ISSUE TITLE
Can't get friendbot to work on testnet (local)

### ISSUE THREAD

**Issue by ZeroGraviti** [stellar/go#321]
I built the `friendbot` microservice locally on my Debian system. However, `friendbot` console log indicates that it is not able to see the accounts I am trying to create and fill with some balances
```
INFO[0466] HTTP response duration=0.00245707 ip="[::1]:33468" method=GET pid=30491 request_id=host/sgqJnOwsJA-000010 response_bytes=360 status=404 uri="/?addr=GD7SXZB5OJNR3X2HTJ45WI7V2VJV6E4RRFIKLJMEKJKGIJYPTSAUZZ2Y"
INFO[1106] HTTP request ip="[::1]:36072" method=GET pid=30491 request_id=host/sgqJnOwsJA-000011 uri="/?addr=GAWAEA2IG4SMDIA2BVG4NSWKI4AR26CDQ5FVPZU7YWEVZWNIDYH3KHER"
```
And in the `horizon` console I see a 404 being returned as well:
```
req="host/ftYerWqFdT-000025"
INFO[1087] Finished request bytes=325 duration=1.036369ms host="localhost:8000" ip="[::1]:55630" method=GET path="/accounts/GB6QPEJTJQQBGFR3DHLVA4DZUGNLZOHUYOMUHZOH43U5PLBQC7QUW5CI" pid=30506 req="host/ftYerWqFdT-000025" status=404 streaming=false
```
Looks like horizon cannot create the accounts in core_testnet to which it is configured..

**_Here is my local testnet info_**
**os** 
```
user@hostname:~$ uname -a
Linux hostname 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux
```
**golang**
```
user@hostname:~/go/services/horizon$ go env
GOARCH="amd64"
GOBIN="/home/user/goprojects/bin"
GOCACHE="/home/user/.cache/go-build"
GOEXE=""
GOhostnameARCH="amd64"
GOhostnameOS="linux"
GOOS="linux"
GOPATH="/home/user/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build511052720=/tmp/go-build -gno-record-gcc-switches"
```

I have built stellar-core locally and this is the start command line:
`user@hostname:~$ /usr/local/bin/stellar-core --conf /usr/local/bin/stellar-core.cfg`

I downloaded horizon from the github releases link @ https://github.com/stellar/go/releases/download/horizon-v0.12.0-testing/horizon-v0.12.0-testing-linux-amd64.tar.gz

```
user@hostname:~$ horizon version
v0.12.0-testing
```
I started horizon with the following command line:
`user@hostname:~$ horizon --stellar-core-url=http://localhost:8080 --friendbot-url=http://localhost:8004/ --db-url=postgres://localhost:5432/horizon_testnet --stellar-core-db-url=postgres://localhost:5432/core_testnet --ingest`

After building friendbot locally I use the following command line to start it up:
`user@hostname:~$ friendbot --conf /usr/local/bin/stellar-friendbot.cfg`

Can someone guide me on this ?

TIA.

**Comment by bartekn** [comment]
Closing because it has been posted here: https://stellar.stackexchange.com/questions/555/how-to-successfully-build-stellar-horizon-locally-on-debian
