### ISSUE TITLE
[SDF] Start another ingesting instance in captive-core cluster using captivecore wrapper

### ISSUE THREAD

**Issue by bartekn** [stellar/go#3212]
Work with the ops team to create another ingesting instance in a new captive-core cluster in stg environment. A new ingesting Horizon instance should connect to another server where [`captivecore`](https://github.com/stellar/go/tree/master/exp/services/captivecore) is installed and listening. This will allow us to understand pros and cons of both options and decide what we should run in production.

**Comment by 2opremio** [comment]
As a reference, I implemented this in https://github.com/stellar/kube/pull/399

**Comment by bartekn** [comment]
I'm meeting with @brahman81 today to discuss another thing so we can talk about this quickly.

**Comment by ire-and-curses** [comment]
This was done, now decommissioned as going forward we can use hybrid old/new instances in staging.
