### ISSUE TITLE
Enumerate & Test the potential fast tx-meta and captive core configurations.

### ISSUE THREAD

**Issue by Shaptic** [stellar/go#3219]
In #3112, we have the following sub-task:
 - Different possible configurations are enumerated and tested for bugs.

This issue exists to fulfill the "enumeration" aspect of this task. **It's intended to be deeply collaborative** (since I don't have nearly as much context as anyone else), so please edit it freely to expand it with the various configurations you know more about. It also should serve as an _almost_ copy-pastable breakdown for when we create user- and developer-facing documentation.

# Configurations
Based on the design doc and other documentation related to the architecture of fast txmeta and captive core, we essentially support two key deployment strategies: **all-in-one** and **multi-machine**.

In both cases, the following Horizon parameters (that are likewise expressible as environmental variables) enables captive core:
 - `--enable-captive-core-ingestion`

while the following are used depending on whether or not the Core node lives with the Horizon node:
 - `--stellar-core-config-path`, `--stellar-core-binary-path`
 - `--remote-captive-core-url`

## All-in-One
This deployment strategy is catered towards developers and users without serious load requirements that want to "get up and go" as quickly as possible. There are many ways to get going this way, in order of "we support it":
  1. running the Debian-based packages directly,
  2. Docker-based deployment, and
  3. manual compilation and deployment.

### Prebuilt Packages
In this route, we have a [Ubuntu repository](https://github.com/stellar/packages#package-based-installation) that hosts our packages. This involves [configuring](https://github.com/stellar/packages/blob/master/docs/installing-individual-packages.md#installing-individual-packages) both Stellar Core and Horizon through their respective methods (the `.cfg` file and env vars, respectively) to enable captive core ingestion.

Naturally, manual compilation is nearly identical to the pre-built route, except Core is built [from scratch](https://github.com/stellar/stellar-core/blob/master/INSTALL.md). This is the likely deployment route if you're not on a Debian-based system.

In either case, given the following prerequisites:
  - existence of a `stellar-core` binary under `/usr/local/bin`,
  - two PostgreSQL instances: one with a DB named `stellar` on port 5641, and another named `horizon` on port 5432
the following (lengthy) command will run Horizon with a captive core instance:

```bash
$ STELLAR_CORE_DATABASE_URL='postgres://postgres@localhost:5641/stellar?sslmode=disable' `
  HISTORY_ARCHIVE_URLS='https://history.stellar.org/prd/core-testnet/core_testnet_001' `
  NETWORK_PASSPHRASE='Test SDF Network ; September 2015' `
  STELLAR_CORE_URL='http://localhost:11626' `
  INGEST=true PER_HOUR_RATE_LIMIT=0 `
  DATABASE_URL='postgres://postgres@localhost:5432/horizon?sslmode=disable' 
  ./horizon --enable-captive-core-ingestion `
    --stellar-core-binary-path=/usr/local/bin/stellar-core `
    --stellar-core-config-path=stellar-core-testnet.cfg 
```
Naturally, all of the paths and URIs can point to other locations (databases living in docker containers, for example) as needed.

### Docker-based deployment 
Do we have/want the equivalent of `stellar/quickstart` or our Compose-based workflow for captive core?

### Kubernetes-based deployment
The multi-machine section on k8s will go into more detail, but essentially we have an additional manifest to provide a single-machine override to the [Kustomize](https://kustomize.io/)-based deployment configuration.

## Multi-Machine
The other primary deployment method is be spread across machines, with each key component of the fast txmeta architecture---Captive Core, Horizon ingestion, and Horizon HTTP---separated and independently scalable.

<img src="https://i.imgur.com/YrdixD5.png" width="240">

Obviously, this is doable "by hand" much like the above methods, but we only support on a Kubernetes-based deployment solution via [Kustomize](https://kustomize.io/). 

TODO: This can be filled out with the relevant instructions when those are complete.

**Comment by ire-and-curses** [comment]
@Shaptic what's the status here?

**Comment by Shaptic** [comment]
![image](https://user-images.githubusercontent.com/822243/109852017-2effd480-7c09-11eb-9535-38f9c67b2173.png)

At this point, I think we can actually abandon a lot of this enumeration. The migration guide and (pending) deployment docs should cover the "All-in-One" as well as the "Multi-Machine" sections (by virtue of describing Remote Captive Core) entirely. 

The other remaining sections (Docker and K8s) remain unclear to me since we are (a) apparently continuing to support stellar/quickstart (has it been updated to deploy Captive Core correctly?) and (b) I haven't been exposed to the k8s side at all. (Note that this touches a bit on the "this should be collaborative" part in the intro :wink:). 

@ire-and-curses I recommend we make separate issues for the latter two points if we want to move forward with documenting a recommended deployment process for them formally, but I can't make the call on whether or not that's the case.

**Comment by ire-and-curses** [comment]
Ok let's just close this for now. When we get there I would like to document K8s but we can do that then.

I think we're actually at a point where we can push quickstart deprecation, but we need to sync with @brahman81 on that, and right now we've all got a lot of other things on our plates.
