### ISSUE TITLE
Response from assets endpoint doesn't include assets whose holders are UNAUTHORZIED or AUTHORIZED_TO_MAINTAIN_LIABILITIES

### ISSUE THREAD

**Issue by howardtw** [stellar/go#3240]
### What version are you using?

This is the current Horizon behavior as of the issue opened date with the latest commit sha being [it](https://github.com/stellar/go/commit/15de5ffd450223e1bc5abf80575d906dc2eabb6e)

### What did you do?

Someone issued 100 OOO tokens from GAWAYMF36WZTCPOTNDM5M7DBQTFAJZCQYAPPV2THVEDXIBS2MB3RWZIA to [GDDCNH4CJ5UP56VLV6AANKAII6V3CU3FRURCWWO2CAYMIT5Q5YFCXLWI](https://horizon-testnet.stellar.org/accounts/GDDCNH4CJ5UP56VLV6AANKAII6V3CU3FRURCWWO2CAYMIT5Q5YFCXLWI), but that person cannot see the asset through the assets endpoint with either the [asset issuer](https://horizon-testnet.stellar.org/assets?asset_issuer=GAWAYMF36WZTCPOTNDM5M7DBQTFAJZCQYAPPV2THVEDXIBS2MB3RWZIA) or the [asset code](https://horizon-testnet.stellar.org/assets?asset_code=OOO).

### What did you expect to see?

I expected to see the assets is included in the response of the assets endpoint regardless asset holders' authorization state.
```
"records": [
      {
        "asset_type": "credit_alphanum4",
        "asset_code": "OOO",
        "asset_issuer": "GAWAYMF36WZTCPOTNDM5M7DBQTFAJZCQYAPPV2THVEDXIBS2MB3RWZIA",
        "amount": "100",
        "num_accounts": 1,
        "flags": {
          "auth_required": true,
          "auth_revocable": true,
          "auth_immutable": false
        }
      }
    ]
```

### What did you see instead?

Nothing is returned in the response.
```
 "_embedded": {
    "records": []
  }
```

**Comment by howardtw** [comment]
@tamirms after some further experiments, I think they are recorded in the Horizon DB, but the endpoint just simply doesn't count the assets in the accounts where the authorization flag is set to either `UNAUTHORZIED` or `AUTHORIZED_TO_MAINTAIN_LIABILITIES`.

Example:
I issued 150 `XXX` from `GBHNRQGRM2QJU5PGEILXDXOOWNQ7NCUOQJOIBXQR5TQ4UUPRNCHUN6B7` to `GCPEONTZCDJ4WN2HMMN7QSHNACKTIMUVILCX4BTSFZ2RBBLC3HKUJ2AH` and 50 `XXX` from `GBHNRQGRM2QJU5PGEILXDXOOWNQ7NCUOQJOIBXQR5TQ4UUPRNCHUN6B7` to `GBT2R5M7YOW2AQUAUJFMPWITVCFJJ2EYHFPBYTTVDVDJWJVQR3U42VYV`. 

I can see the assets endpoint returns `150` with `num_accounts` being `1` when the authorization flag is set to `authorized` in `GBHNRQGRM2QJU5PGEILXDXOOWNQ7NCUOQJOIBXQR5TQ4UUPRNCHUN6B7`. And when I used `allow_trust` to authorize `GBT2R5M7YOW2AQUAUJFMPWITVCFJJ2EYHFPBYTTVDVDJWJVQR3U42VYV`, the result became `200` with `num_accounts` being `2`.

**Comment by howardtw** [comment]
A quote from @tamirms 
```
If there is 1 AUTHORIZED trustline, then the asset will be in the horizon database. Let's say in the next ledger, the trustline is revoked, at that point because there are no trustlines for that asset the asset is removed from the horizon db.
```
For anyone who will be looking into it.

**Comment by bartekn** [comment]
Fixed in https://github.com/stellar/go/pull/3454. Will be part of Horizon 2.1.0 release.
