### ISSUE TITLE
Feature Request: improve the assets endpoint

### ISSUE THREAD

**Issue by howardtw** [stellar/go#3241]
### What problem does your feature solve?

For regulated assets, the issuers often want to track the assets the've issued/distributed. However, regulated asset holders will have their account set to `UNAUTHORZIED` or `AUTHORIZED_TO_MAINTAIN_LIABILITIES` when they are not transacting the asset. And it seems like the assets endpoint doesn't return the assets in accounts with the flag to those two values.

### What would you like to see?

The response from the assets endpoint includes all assets regardless the authorization state in asset holders' accounts.

While there an [issue](https://github.com/stellar/go/issues/3240) targeted to address it, there are more things we can consider when we implement a solution.

Currently the response includes the flags in the issuer account, and those flags can be set with `set_options` ops in the issuer's account. There are a few things to consider regarding it:

1. The flags in the response only reflect the current state of the issuing accounts. However,  the `authorization_required ` flag in the issuer's account will only determine the default state of the trustline at the time when a holder creates one, and it will not affect existing trustlines. In other words, if an issuer issues some of the asset with `authorization_required` to set `false` and issues some of the assset with `authorization_required` to set `true`, I'm not sure whether it makes sense to add all accounts with different default states of the trustline together and display them under the current state of the issuer's account.
2. Even if we decide to pursue point above by categorizing the response by the default state of the trustline, we are only looking at the response from the issuer's standpoint. It will be useful if we can categorize the response by the asset holder's account state as well. The state of asset holders' accounts can be set by `allow_trust` ops. Currently, there are three authorization states an asset holder can have, `AUTHORIZED`, `AUTHORIZED_TO_MAINTAIN_LIABILITIES`, and `UNAUTHORIZED`. And the assets endpoint only counts the accounts in the `AUTHORIZED` state.

I understand there could be several combinations (24 at maximum, with 8 from the first point and 3 from the second point) if we do both of the above. If we can only pick one, it would think the second is more important than the first.

### What alternatives are there?

N/A

**Comment by bartekn** [comment]
I think it is fixed in https://github.com/stellar/go/pull/3454. Will be part of Horizon 2.1.0 release.
