### ISSUE TITLE
Batch remove offers in OffersProcessor

### ISSUE THREAD

**Issue by bartekn** [stellar/go#3246]
### What version are you using?

1.11.1

### What did you do?

Processor durations stats added in https://github.com/stellar/go/pull/3224 revealed that `OffersProcessor` (green line) is much slower than other processors:

<img width="855" alt="Screenshot 2020-11-23 at 17 55 38" src="https://user-images.githubusercontent.com/464938/99991257-19cb0c80-2db5-11eb-9985-29c32052548b.png">

Comparing this to Ledger Entry Change chart we can see that there are a lot of offer removals in ledgers:

<img width="857" alt="Screenshot 2020-11-23 at 17 56 34" src="https://user-images.githubusercontent.com/464938/99991376-3c5d2580-2db5-11eb-95a8-4dccf061bf54.png">

It looks like batching offer removals could largely improve the speed of ingestion: https://github.com/stellar/go/blob/f1c5d7131ca589713596dfc1ee717a1360f1a14b/services/horizon/internal/ingest/processors/offers_processor.go#L85-L90. ~Because batch removals can be useful for other processors (and services) we should create a new struct in `support/db` similar to `BatchInsertBuilder`.~ Actually we don't `DELETE` offers but we update `deleted` flag. We should change the query to use `IN` instead of `=`.

**Comment by bartekn** [comment]
2x improvement!

<img width="841" alt="Screenshot 2020-11-26 at 11 03 35" src="https://user-images.githubusercontent.com/464938/100336935-0b5c3b00-2fd7-11eb-8297-47af0ee444f1.png">

**Comment by ire-and-curses** [comment]
Wow, super cool!
