### ISSUE TITLE
Add testnet/pubnet sync, catchup (BoundedRange) and reingest integration tests

### ISSUE THREAD

**Issue by bartekn** [stellar/go#3248]
Add integration tests that sync with the network: build state and ingest a few ledgers. This will help ensure that Horizon is able to sync and catch bugs like https://github.com/stellar/go/pull/3231 before release testing.

**Comment by bartekn** [comment]
To clarify, I think we should test 3 things:
1. starting from scratch to check if horizon can build state without a problems + a few ledgers,
2. starting from existing DB (`start` -> `resume` transition in FSM scenario). this would catch https://github.com/stellar/go/pull/3231,
3. `horizon db reingest` so we are sure that reingesting works (I believe it doesn’t in the latest version because of https://github.com/stellar/go/pull/3260).

**Comment by bartekn** [comment]
@2opremio @tamirms you asked why we should do testnet/pubnet tests and I answered that I was probably wrong and standalone should work too. That's true but what is the status of captive core tests in standalone? I'm looking at #3267 and realized that it wouldn't catch #3231 or #3260 because both issues were connected to captive core.

**Comment by 2opremio** [comment]
Note that as soon as the integration tests can be run with captive core (which is almost there, I think) the tests at #3267 will be run with captive core too.

**Comment by bartekn** [comment]
OK! I just wanted to confirm we'll be able to have them before beta. If not, it would be great to have testnet/pubnet tests.
