### ISSUE TITLE
Detecting if Horizon is in sync with the network

### ISSUE THREAD

**Issue by bartekn** [stellar/go#3252]
Opening this issue to discuss possible ways to detect if Horizon (and connected Stellar-Core) is in sync with the network. This important because we may block access to Horizon if data is stale and we probably want to block access to txsub in this case because all attempts to submit a transaction would fail with `Timeout` errors. Additionally, a number of ledgers to ingest can be very useful metric helping understand how much more is required by Horizon to sync with the network.

### Stellar-Core HTTP endpoint

Stellar-Core exposes some information in `/info` endpoint like `state` and `ledger.num` that can be helpful detecting if it's in sync. This would be a perfect solution however we need to check if the information provided by `/info` are up to date while streaming ledgers in captive-core mode. `CaptiveStellarCore` backend contains a small buffer of 20 ledgers and Stellar-Core will pause streaming ledgers if it's full.

There are also some issues connected to more complicated deployments when there are non-ingesting instances (that potentially don't have access to Stellar-Core endpoint) and when using `captivecore` wrapper server (that exposes it's own HTTP API only). In both cases the values in `/info` would need to be transfered to Horizon key value store or exposed via a proxy.

### Last ingested ledger age

Another option is to track age of last ingested ledger (compared to current timestamp). Similar to Core's `ledger.age` in `/info`. This would give a rough information about sync status. While this solution require no dependencies (like running Core instance) it can give false positives if network closes a few _slow_ ledgers. For example, let's say we set a stale threshold (https://github.com/stellar/go/issues/3210) to 15 seconds (which is 3 ledgers given the average close time of 5 seconds): if network closes a ledger in 20 second Horizon would assume that it's out of sync but it's not.

## Comparison

x | Stellar-Core HTTP endpoint | Last ingested ledger age
-|-|-
Accuracy | Real-time (given it works when buffer full) | Estimation based on average ledger close time
Dependencies | Running Stellar-Core instance | None
Deployment | Won't work without extra configuration when non-ingesting instances available and in `captivecore` wrapper | No issues

**Comment by tamirms** [comment]
> however we need to check if the information provided by /info are up to date while streaming ledgers in captive-core mode. CaptiveStellarCore backend contains a small buffer of 20 ledgers and Stellar-Core will pause streaming ledgers if it's full.

I just tested the behavior of the http endpoint in captive core. As @bartekn mentioned, when horizon's buffer reaches its capacity of 20 ledgers, captive core will pause streaming ledgers. I discovered that while captive core is paused, it does not accept any http requests. That means the http endpoint will not be available when horizon's ledger buffer is full.

**Comment by bartekn** [comment]
We implemented "Last ingested ledger age" and added many metrics related to Horizon and Stellar-Core sync status. I think we can close this.
