### ISSUE TITLE
Move/remove root endpoint fields that depend on running Stellar-Core instance

### ISSUE THREAD

**Issue by bartekn** [stellar/go#3254]
The following fields in the root endpoint are updated by accessing Stellar-Core's `/info` endpoint that may not be available in captive core deployments (ex. from non-ingesting instances):
* `core_version`
* `core_latest_ledger`
* `core_supported_protocol_version`

Let's discuss if we want to move them to metrics (updated from ingesting instances) or remove completely.

**Comment by ire-and-curses** [comment]
Seems valuable to have them visible from non-ingesting instances for clients/operators. Is there any downside to moving them to metrics?

**Comment by bartekn** [comment]
> visible from non-ingesting instances for clients/operators

Not sure if clients needs to know the fields listed in the first post.

> Is there any downside to moving them to metrics?

I don't think so, it's actually quite easy given we already export horizon version via /metrics.

**Comment by ire-and-curses** [comment]
>Not sure if clients needs to know the fields listed in the first post.

I think it's valuable because clients can potentially proxy the info downstream. E.g. a network monitoring tool could identify out of date installations.

Since it's also easy I am in favour of doing this.

**Comment by bartekn** [comment]
Non-ingesting instances need to connect to Stellar-Core for txsub anyway.
