### ISSUE TITLE
Decode base64 encoded Account "data" when loading an Account

### ISSUE THREAD

**Issue by MikeFair** [stellar/go#326]
When you set Managed Data on an Account, the value gets base64 encoded.
When you load the account back via Horizon, you get the base64 encoded version instead of the value that was original supplied.

For example, if you set the managed data using:
```{  "LinkedAccountId" : "d2025a6f-39ab-49c9-a38f-ad08d2230dda" }```

what comes back from the SDK is:
```{ "LinkedAccountId" : "ZDIwMjVhNmYtMzlhYi00OWM5LWEzOGYtYWQwOGQyMjMwZGRh" }```

I don't know whether the clients should fix this or if Horizon should, but either way what we put in should be what comes out. ;)

I have a patch for `clients/horizon/client.go` to decode them on arrival in LoadAccount I can provide as a PR, but I'm uncertain if this should really go in Horizon instead.

**Comment by bartekn** [comment]
Horizon needs to encode data value somehow, printing raw bytes is not an option. When it comes to Go SDK, we already have [`Account.GetData`](https://godoc.org/github.com/stellar/go/clients/horizon#Account.GetData) method that decodes the value.

Closing, will reopen if I misunderstood you.
