### ISSUE TITLE
Integration tests don't cleanup their Postgres databases

### ISSUE THREAD

**Issue by 2opremio** [stellar/go#3268]
While writing https://github.com/stellar/go/pull/3267 I found out that the integration tests are not dropping their dedicated Horizon Postgres database.

I tried fixing it (look at the TODOs in the code from the PR above) but it turns out that Horizon's `App` leaves open sessions behind .... even after closing it (leading to `database  is being accessed by other users` errors).

This may indicate that Horizon is leaking DB connections, so we should look into it.

**Comment by bartekn** [comment]
Possibly fixed?

**Comment by 2opremio** [comment]
I will test this out.

**Comment by 2opremio** [comment]
It's still broken, I get this error upon uncomenting the `postgres.Close()` call.

```
=== CONT  TestProtocol16Basics
    db.go:108: 
        	Error Trace:	db.go:108
        	            				db.go:135
        	            				db.go:53
        	            				integration.go:181
        	            				integration.go:170
        	            				once.go:68
        	            				once.go:59
        	            				integration.go:167
        	            				testing.go:901
        	            				testing.go:1007
        	            				testing.go:1187
        	Error:      	Received unexpected error:
        	            	pq: database "test_b9831a09ca15" is being accessed by other users
        	Test:       	TestProtocol16Basics
--- FAIL: TestProtocol16Basics (26.89s)
=== RUN   TestProtocol16Basics/Sanity
```

The test passes when the call is commented.
