### ISSUE TITLE
Check if Horizon works properly when compiled using Go 1.16

### ISSUE THREAD

**Issue by bartekn** [stellar/go#3293]
We should check if it works fine. There were some changes related to CGO. We probably (no longer) use it but better check. Also check if building artifacts works on buster.

**Comment by leighmcculloch** [comment]
I believe @stellar/ops-team expressed some concern not with building with Go 1.16, but building the release artifacts .deb files on a version of Debian newer than Stretch. I'm not familiar with the details, but this testing should include testing that the release artifacts built with Debian Buster are in good working order.

**Comment by 2opremio** [comment]
In progress at https://github.com/stellar/go/pull/3288

**Comment by bartekn** [comment]
Looks like it's working fine in Go 1.16.2. In compiles, runs in stg and verify range tests work.
