### ISSUE TITLE
Consider moving optional context out of CaptiveCoreConfig and make it a parameter of PrepareRange

### ISSUE THREAD

**Issue by tamirms** [stellar/go#3295]
In https://github.com/stellar/go/pull/3278 `CaptiveCoreConfig` was extended to include an optional context field. The context in `CaptiveCoreConfig` acts as a parent context for all `PrepareRange()` sessions. In other words, if the parent context is cancelled then, any pending `PrepareRange()` / `GetLedger()` operation will be terminated even though `Close()` was not called. 

In the PR @2opremio mentioned:

>In general, it's not considered a good practice to store the context unless it's an ephemeral object (e.g. a request).
>
>Normally, the context is passed to each operation so that it can be configured per operation.

With that feedback in mind, perhaps it would be better to move the context so that it's a parameter to `PrepareRange()` instead.

**Comment by bartekn** [comment]
This was fixed in https://github.com/stellar/go/pull/3576.
