### ISSUE TITLE
HTTPS doesn't seem to be working for federation

### ISSUE THREAD

**Issue by s-a-y** [stellar/go#33]
Even though I specify TLS certificates in the config it still starts insecure.

**Comment by bartekn** [comment]
What do you mean by "starts insecure"? Are you sure your certificate contains your CA intermediate certificates?

**Comment by s-a-y** [comment]
I'm using certificate issued by cloudflare and there is no problem with it. I use the same for nginx, however when I start federation server I get this:
<img width="676" alt="screen shot 2017-02-13 at 9 18 47 am" src="https://cloud.githubusercontent.com/assets/1667781/22866656/201db2a8-f1ce-11e6-8c10-a0fa2fb2cf6d.png">
or behind cloudflare
<img width="993" alt="screen shot 2017-02-13 at 9 18 57 am" src="https://cloud.githubusercontent.com/assets/1667781/22866659/26927506-f1ce-11e6-892a-887b564ca7c8.png">
It works well if I just use http on another port.

**Comment by bartekn** [comment]
Any company that is using federation server haven't experienced problems with SSL. So I suspect there is something wrong with your certificate/configuration/proxy/etc. Ping me (bartek) on our [slack](http://slack.stellar.org/) and I will try to help.

**Comment by s-a-y** [comment]
stellar/docs:#195
