### ISSUE TITLE
Feature Request: Support querying claimable balances by creating account

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/go#3306]
### What problem does your feature solve?

There is no effecient method for the sender of a [two-part payment](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0023.md), i.e. the creator of a claimable balance, to identify unclaimed claimable balances they created.

It's possible to filter claimable balances by the sponsor field, and that field is set to the account that created the claimable balance if the ledger entry isn't sponsored. However, claimable balances that are sponsored by a third party like a wallet service won't have the creator set there and no application should rely on the sponsor being the sender.

Claimable balances were created with the intention of facilitating two-part payments. While they provide generic types for separating an amount into a balance disconnected from any account they still need to facilitate payments like how direct payments do. A sender should be able to identify what payments they've sent that haven't been claimed.

Example of how to query by sponsor which is similar but insufficient:
https://horizon.stellar.org/claimable_balances/?sponsor=GDCJIHD3623OCYNH65UUQC3NLG2D6YCNCDPZULRLCLOA76TBQRL6A3TF

### What would you like to see?

It be possible to filter by the account that created the claimable balance, by using a new query parameter such as `?creator=G...`.

Example:
https://horizon.stellar.org/claimable_balances/?creator=GDCJIHD3623OCYNH65UUQC3NLG2D6YCNCDPZULRLCLOA76TBQRL6A3TF

### What alternatives are there?

It's possible to get all operations that an account created and therefore discover all claimable balances that we're created in all time and each could be queries to discover if it had been claimed, but that would be inefficient. The logic exists to query claimable balances by other accounts and it's intuitive to expect that same filter to be available to the creating account.

This issue is related to #3305 and https://github.com/stellar/go/issues/3380.

cc @stellar/horizon-committers

**Comment by tamirms** [comment]
@leighmcculloch do you expect this endpoint to only return unclaimed claimable balances or should it also include claimable balances which have already been claimed?

**Comment by leighmcculloch** [comment]
FYI I think #3380 overlaps with solving this lookup issue for any wallet needing to find pending two-part payments that includes the creator as a claimant.

**Comment by 2opremio** [comment]
@leighmcculloch After an internal discussion, we observed that:

1. implementing this would be pretty involved and disruptive
2. we don't even support this kind of query for accounts (there is no way to query accounts by their creating account). 

Thus, unless a compelling business usecase is provided which justifies it, we won't include it in our sprint backlog for now.

Note, however, that you will be able to query the creator of a given claimable balance (the reverse query) through #3305 (by querying the operations and obtaining the first one, which will be the creation) or, if we agree on a solution to #3380, you will be able to get this directly when querying a claimable balance.

**Comment by bartekn** [comment]
I guess we can close this. Please reopen if I'm missing something.
