### ISSUE TITLE
Return `Service Unavailable` error when there is a delay in ingestion

### ISSUE THREAD

**Issue by bartekn** [stellar/go#333]
Horizon should return `503 Service Unavailable` error when there's a delay in ingestion rather than data that is not up to date.

**Comment by nullstyle** [comment]
This already exists:  https://github.com/stellar/go/blob/master/services/horizon/main.go#L46

Just set the stale threshold to 1 and horizon will return https://www.stellar.org/developers/horizon/reference/errors/stale-history.html
