### ISSUE TITLE
stellar-hd-wallet accounts command not working on Windows 10 

### ISSUE THREAD

**Issue by ericstamper** [stellar/go#334]
I have tried multiple times to use the stellar-hd-wallet on various Windows 10 systems and every attempt gives errors when using the accounts command. 

The "new" command allows me to create a 24 word seed. If I then try to generate the associated keys by running the "accounts" command, it always asks for an input of "How many words?" No matter what value is entered (supposedly it should be 24 in my case) it returns an error message with the date, time and "Invalid value"

![stellar-wallet](https://user-images.githubusercontent.com/2281043/36826403-02f5bd72-1cdb-11e8-8f8b-d3a95f5ca3b3.png)

**Comment by ericstamper** [comment]
I have figured out what the problem is, and how to correct it. The problem is on line 18 of commands/io.go. That line strips of the newlines from the command line entry. On windows, however, stripping off the "\n" is not sufficient, since the newlines on windows consist of "\r\n". 

The basic fix is to import the runtime package and then determine the operation system using runtime.GOOS. If the operating system is windows, then it can strip off "\r\n" from the command line entry, otherwise the code will remain unchanged and strip off only the "\n".

I am more than happy to submit a pull request for the updated code. Would it be best that this be done against the master branch or the separate stellar-hd-wallet branch, which appears to be 100 days behind the master branch? I welcome any feedback.

![wallet-code](https://user-images.githubusercontent.com/2281043/36951250-7010f4e8-1fcf-11e8-83d8-d613f6145750.png)

**Comment by bartekn** [comment]
Closed in https://github.com/stellar/go/pull/345
