### ISSUE TITLE
Add timeouts to all functions called from Tick()

### ISSUE THREAD

**Issue by bartekn** [stellar/go#3344]
### What version are you using?

1.13.1

### What did you do?

We don't set timeouts in functions in `horizon.App.Tick()` so if the connection gets stuck for any reason it will block entire `Tick()` method forever. It will affect metrics, fee stats and all the components of the system that rely on ingestion/ledger related stats.

Thanks @jacekn for reporting this!

**Comment by bartekn** [comment]
Additionally check other places where this can cause issues.

**Comment by 2opremio** [comment]
Related https://github.com/stellar/go/issues/613
