### ISSUE TITLE
Feature Request: add transaction memo's to /payments response

### ISSUE THREAD

**Issue by JakeUrban** [stellar/go#3355]
### What problem does your feature solve?

Transaction `memo`'s are used to identify transactions in various SEPs (6, 24, 31), but the `/payments` endpoint does not include this attribute in its response, leading us (the integration team) to recommend using the `/accounts/{account}/transactions` endpoint instead.

### What would you like to see?

Adding a transaction's `memo` to it's associated `/payment` record.

### What alternatives are there?

Using the `/accounts/{account}/transactions` endpoint or making an additional request to the transactions URL provided in the `_links` object.

**Comment by bartekn** [comment]
There is `join=transactions` GET parameter you can add to `/accounts/{account}/payments` that will fetch tx details under payment resource. Does it solve the problem for you?

**Comment by JakeUrban** [comment]
Yes it does, thanks
