### ISSUE TITLE
Add horizon health check endpoint

### ISSUE THREAD

**Issue by tamirms** [stellar/go#3396]
It would be useful to have a healthcheck endpoint that guarantees horizon is fully operational. Fully operation could be defined as being able to submit transactions to stellar core. Assuming that definition, the health check could query its stellar core (or captive core) instance to see that its synced to the network.

**Comment by jacekn** [comment]
Most load balancers I know are happy with healthcheck endpoints returning http 200 so that will be enough.
But if it's easy it might be useful to also have health info returned in text format so that operators can query it to check status easily. Maybe something like:
```
{
    "ready": false,
    "database_connected": true,
    "core_up": true,
    "core_synced": false
}
```

**Comment by bartekn** [comment]
For the future assignee: adding the code for healtcheck somewhere around https://github.com/stellar/go/pull/3414 and https://github.com/stellar/go/pull/3418 can help implementing this faster.

**Comment by bartekn** [comment]
Also, my 2 cents: while I think this could be really useful I think we should keep in mind how health check are used in many platforms. In ELB for example I think the default is 2 failures will mark an instance as unavailable but then it will require 10 successes to bring it back. This means that a short blip can actually make the instance unavailable for a longer time.

Other than that, it's ok for me.
