### ISSUE TITLE
Allow setting LOG_FILE_PATH when starting Stellar-Core in captive mode

### ISSUE THREAD

**Issue by bartekn** [stellar/go#3438]
### What problem does your feature solve?

Some users would like to specify where Stellar-Core stores it's log file files because a default `/tmp` location is not always right.

### What would you like to see?

A new config flag that is forwarded to Captive Stellar-Core config (both online and offline modes).

### What alternatives are there?

Ideally, Stellar-Core team implements https://github.com/stellar/stellar-core/issues/2943 so there is no need to store log file anywhere (we embed it in Horizon log anyway).

**Comment by bartekn** [comment]
OK, there was a [misunderstanding](https://github.com/stellar/stellar-core/issues/2943#issuecomment-790574424) on my side. We still need a flag so nothing changes in this issue but if the flag is not set we should explicitly set `LOG_FILE_PATH=""` so the log file is not written anywhere.

**Comment by Shaptic** [comment]
After discussion with ops, here's the agreed-upon strategy for this moving forward:
- We'll expose an optional parameter, e.g. `--captive-core-log-path`
- **If this is set**, we'll stop logging `subservice=core` in Horizon and pass the path along to `LOG_FILE_PATH`
- **If not**, we'll continue with the current behavior (log in Horizon and set param to `""`)
