### ISSUE TITLE
Bifrost giving Error 500 (Internal Server Error)

### ISSUE THREAD

**Issue by shaheryar607** [stellar/go#344]
I have been trying to go on https://bifrost.stellar.org/ since 3 days but I keep getting an error message.

From the Chrome console this is what I'm Getting:
/generate-ethereum-address Failed to load resource: the server responded with a status of 500 (Internal Server Error)
(index):57 Error: Request failed with status code 500
at createError (app.js:2103)
at settle (app.js:2073)
at XMLHttpRequest.handleLoad (app.js:1945)
session.startEthereum.then.catch.err @ (index):57

I am encountering this error on the public Stellar infrastructure. What exactly is going on? Is there a problem on my end? Does this happen often?

**Comment by bartekn** [comment]
Our instance run out of free disk space. This is now fixed. Thanks for reporting this.
