### ISSUE TITLE
Captive core peer port can clash with other stellar core instances running on the machine

### ISSUE THREAD

**Issue by tamirms** [stellar/go#3441]
On stellar core the peer port is configured to 11625 by default. When captive core is launched it will fail to start if the peer port is occupied by another process (e.g. a stellar core instance running on the same host). To mitigate this we could either disable the peer port if that's possible or we could select a random port which is available on the host.

**Comment by smdwireless** [comment]
I think by simply adding a switch in the configuration options, maybe something like:
```
--captive-core-peer-port=
CAPTIVE_CORE_PEER_PORT
```

This can be set manually or defaulted to 11625

**Comment by jacekn** [comment]
stellar-core config supports `PEER_PORT` option whcih defaults to 11625. Maybe we can use it for this purpose?
