### ISSUE TITLE
[CAP 35] Improve integration test coverage

### ISSUE THREAD

**Issue by 2opremio** [stellar/go#3447]
Right now we only have happy-path coverage (and for `SetTrustlineFlags` we still need to test the details and effects).

We should add more tests, for instance, the tests suggested by @leighmcculloch at https://github.com/stellar/go/pull/3368#discussion_r562827974

Part of #3348

**Comment by paulbellamy** [comment]
From reading the comment on #3368, and [cap35](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0035.md), the list of extra potential tests I have is below. Not sure we need to hit *all* of these, as a lot should be handled by core.

## Happy path
  - [ ] Claiming back a partial amount.

## Sad Path
  - [ ] enabling and disabling it (tested implicitly by below?)
    - [ ] trying to set AUTH_CLAWBACK_ENABLED_FLAG after trustline created
  - [ ] set options should fail to set clawback enabled when not revocable
  - [ ] low threshold signature
  - [ ] negative amount
  - [ ] from == issuer
    - [ ] Shouldn't be able to clawback yourself/
  - [ ] invalid asset
  - [ ] claimable balance
    - [ ] already claimed
    - [ ] already cancelled?
    - [ ] source account not clawbackable
    - [ ] source account not allowed to clawback
    - [ ] source account is not issuer
    - [ ] created when clawback not enabled on issuer account, then clawback
        enabled on issuer account after. should still fail.
    - [ ] can't clawback it twice.
  - [ ] accounts
    - [ ] clawback not enabled on from account
    - [ ] clawback not enabled on issuer account
    - [ ] clawback enabled, but revocable not enalbed
    - [ ] trustline source != issuer (Is this a scenario?)
    - [ ] clawback should still work when holder is unauthorized
    - [ ] clawback should still work when holder is authorized_to_maintain_liabilities
    - [ ] from account has no trustline for asset
    - [ ] from account does not hold asset
    - [ ] from account insufficient funds
    - [ ] from account sufficient funds including selling liabilities
      - [ ] should fail unless issuer deauthorizes/reauthorizes the from account
      - [ ] deauthorize/reauthorize should work

**Comment by paulbellamy** [comment]
Per discussion, for stuff where it is behaviour around core, it makes more sense to maybe sanity-check the error response gets generated correctly, and the horizon state is in the expected state. Possibly a table-driven test makes sense here.
