### ISSUE TITLE
[CAP 35] Update documentation

### ISSUE THREAD

**Issue by 2opremio** [stellar/go#3449]
Update documentation at https://github.com/stellar/new-docs
- Add new operations
- Add new effects
- Add new operation details for pre-existing operations (if needed)
- Add new Account flag (if needed)
- Add new Trustline flag (if needed)
- Add new Claimable Balance flag (if needed)

**Comment by Shaptic** [comment]
Also covered by stellar/new-docs#355. There's value in keeping it here for tracking purposes, but are there more docs requirements within the monorepo itself (docstrings, etc.)?

**Comment by Shaptic** [comment]
I believe this was closed when stellar/new-docs#355 closed.
