### ISSUE TITLE
Add JSON -> XDR Horizon endpoint

### ISSUE THREAD

**Issue by vladfaust** [stellar/go#346]
Many languages (like my favorite, Crystal) lack in a handful XDR implementation, which leads to a lower adoption. Currently such kind of developer can forward JSON'ed transaction to their ~~Federation~~ Bridge server and interact with Stellar from there, but such approach decreases decentralization. Horizon could have some builder endpoint itself which would convert JSON transaction input to XDR.

How I see it: an app builds a JSON transaction without signatures and sends it to `/builder` endpoint, getting XDR in response. A user then signs the XDR and sends it back to Horizon Create Transaction edpoint. I do know that signatures must be part of the XDR payload, but I think this could be overcome somehow without messing up with blockchain history (like appending signatures to the payload within Horizon itself).

~~The challenge here is to invent a JSON transaction protocol, but I don't see much difficulties here, because JSON structure would be same as XDR but with named fields~~ Already done in Bridge

**Comment by bartekn** [comment]
We can discuss this but right now you can use [`/builder`](https://github.com/stellar/bridge-server/blob/master/readme_bridge.md#post-builder) endpoint of the Bridge server.

**Comment by vladfaust** [comment]
@bartekn it decreases decentralization. There must be a third-party Bridge server to use `/builder` endpoint. How about merging builder into Horizon?
