### ISSUE TITLE
43_add_claimable_balances_flags migration does not work if claimable_balances table contains rows

### ISSUE THREAD

**Issue by bartekn** [stellar/go#3465]
I'm getting:
```
2021/03/12 14:24:59 pq: column "flags" of relation "claimable_balances" contains null values handling 43_add_claimable_balances_flags.sql
```
when migrating existing DB with data in `claimable_balances` table. I think it's happening because a new `flags` field is defined as `NOT NULL` but does not have a default value.

Assigning to @2opremio because you added a file, please assign to somebody else if needed.

**Comment by 2opremio** [comment]
Good catch. Will fix!!
