### ISSUE TITLE
Federation Server does not return stellar_address field

### ISSUE THREAD

**Issue by mz7mz7mz7** [stellar/go#347]
I see that official Federation Server implementation ( https://github.com/stellar/go/tree/master/services/federation ) does not return field: **stellar_address** in the response JSON, even according to https://www.stellar.org/developers/guides/concepts/federation.html it appears to be a mandatory field.
I tested federation build using this implementation with the www.stronghold.co wallet and although Stronghold does not report any issue it also does not resolve the address. I think this is the side effect of not adding stellar_address field as the standard requires.

Is there any plan on adding it?

**Comment by dejl** [comment]
This would be amazing. Some clients like Stellarterm rely on this field to convey information to the user
