### ISSUE TITLE
How to generate a keypair correctly?

### ISSUE THREAD

**Issue by urbanurba** [stellar/go#3478]
Hi,
how to generate a keypair correctly?
Take test seed here: https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0005.md

seed: "e0eec84fe165cd427cb7bc9b6cfdef0555aa1cb6f9043ff1fe986c3c8ddd22e3"

correct result: m/44'/148'/0' GDRXE2BQUC3AZNPVFSCEZ76NJ3WWL25FYFK6RGZGIEKWE4SOOHSUJUJ6 SBGWSG6BTNCKCOB3DIFBGCVMUPQFYPA2G4O34RMTB343OYPXU5DJDVMN

How to properly turn seed into a correct result (keypair)? Trying:
```
import (
    "github.com/stellar/go/keypair"
)
var seeds [32]byte
copy(seeds[:], []byte("e0eec84fe165cd427cb7bc9b6cfdef0555aa1cb6f9043ff1fe986c3c8ddd22e3"))
pair, err := keypair.FromRawSeed(seeds)
xlmAddr := pair.Address()
xlmPK := pair.Seed()
fmt.Println(xlmAddr)
fmt.Println(xlmPK)
```
Result is different...

**Comment by leighmcculloch** [comment]
Hi!

The seed in your example is a hex string, so you need to decode it with the `encoding/hex` package's `DecodeString` function.

Once you have the SEP-5 seed decoded into a `byte[]`, you can derive a key from the SEP-5 seed using the `github.com/stellar/go/exp/crypto/derivation` package.

Checkout the example here:
https://github.com/stellar/go/blob/horizonclient-v6.0.0/exp/crypto/derivation/main_test.go#L13

**Comment by urbanurba** [comment]
Changed to this:
```
xlmSeed, _ := hex.DecodeString("e0eec84fe165cd427cb7bc9b6cfdef0555aa1cb6f9043ff1fe986c3c8ddd22e3")
xlmKey, err := xlmDrv.DeriveForPath(xlmDrv.StellarPrimaryAccountPath, xlmSeed)
pair, err := keypair.FromRawSeed(xlmKey.RawSeed())
fmt.Println(pair.Seed())
fmt.Println(pair.Address())
```
Still the wrong result.

But this seed example - "000102030405060708090a0b0c0d0e0f"
gets correct result:
SB6VZS57IY25334Y6F6SPGFUNESWS7D2OSJHKDPIZ354BK3FN5GBTS6V
GCWSJRG6YZSA374IY7LF53PIGTO6JD6BP5CNMUAVNWL3YYE636F3APML
https://github.com/stellar/go/blob/horizonclient-v6.0.0/exp/crypto/derivation/main_test.go#L27

**Comment by overcat** [comment]
Hi @urbanurba, You should use `BIP39 Seed` in SEP-05, not `m/44'/148' key`. If you want to reproduce test 1 in SEP-10, please use the following code.

```go
package main

import (
	"encoding/hex"
	"fmt"
	"github.com/stellar/go/exp/crypto/derivation"
	"github.com/stellar/go/keypair"
)

func main() {
	// I ignored all errors.
	bip39Seed, _ := hex.DecodeString("e4a5a632e70943ae7f07659df1332160937fad82587216a4c64315a0fb39497ee4a01f76ddab4cba68147977f3a147b6ad584c41808e8238a07f6cc4b582f186")
	for i := 0; i < 10; i++ {
		path := fmt.Sprintf(derivation.StellarAccountPathFormat, i)
		keyPair, _ := derivation.DeriveForPath(path, bip39Seed)
		pair, _ := keypair.FromRawSeed(keyPair.RawSeed())
		fmt.Printf("%s %s %s\n", path, pair.Address(), pair.Seed())
	}
}

```

Actually `m/44'/148' key` is the intermediate value generated during the calculation, if you are interested in it, add a breakpoint [here](https://github.com/stellar/go/blob/horizonclient-v6.0.0/exp/crypto/derivation/main_test.go#L13) and explore `k.Key`.

Hope this information is helpful to you.

**Comment by urbanurba** [comment]
@overcat, this is what I was looking for, 
thank you very much!

**Comment by bartekn** [comment]
Closing, please reopen if needed.
