### ISSUE TITLE
Horizon: Update SDKs for /assets summary changes

### ISSUE THREAD

**Issue by paulbellamy** [stellar/go#3487]
Follow on work from https://github.com/stellar/go/pull/3454, to update the SDKs to use the new fields in preparation for the old fields being deprecated in Horizon 3.0.

We should:
- [x] wait for next horizon release (2.2.0?), so that all changes are in.
- [x] Update the official sdks
    - [x] go
    - [x] java https://github.com/stellar/java-stellar-sdk/pull/339
    - [x] javascript https://github.com/stellar/js-stellar-sdk/pull/628
- [x] Update the docs https://github.com/stellar/new-docs/pull/373
- [x] Notify the community sdks to also update.

**Comment by paulbellamy** [comment]
Once https://github.com/stellar/go/pull/3502 is merged, we should include that in these updates.

**Comment by bartekn** [comment]
Can be closed?
