### ISSUE TITLE
Horizon: Update SDKs for /claimable_balances new endpoints

### ISSUE THREAD

**Issue by paulbellamy** [stellar/go#3488]
Follow on work from https://github.com/stellar/go/pull/3483, to update the SDKs to expose the new endpoints.

We should:
- [x] wait for next horizon release (2.2.0?), so that all changes are in.
- [x] Update the official sdks
    - [x] go
    - [x] java https://github.com/stellar/java-stellar-sdk/pull/339
    - [x] javascript https://github.com/stellar/js-stellar-sdk/pull/628
- [x] Update the docs https://github.com/stellar/new-docs/pull/373
- [x] Notify the community sdks to also update.

**Comment by bartekn** [comment]
Can be closed?
