### ISSUE TITLE
Internal server error on /trade_aggregation API

### ISSUE THREAD

**Issue by navinbisht** [stellar/go#349]
Setup my own horizon 
Calling an API for trade_aggregation

        https://staging.globalblockchain.io:9000/trade_aggregations?base_asset_type=credit_alphanum4&base_asset_code=MOBI&base_asset_issuer=GA6HCMBLTZS5VYYBCATRBRZ3BZJMAFUDKYYF6AH6MVCMGWMRDNSWJPIH&counter_asset_type=native&start_time=1514764800&end_time=1520508146620&resolution=900000&limit=200&order=desc&c=0.2979189516029812

Got an error response

        {
            "type": "https://stellar.org/horizon-errors/server_error",
            "title": "Internal Server Error",
            "status": 500,
            "detail": "An error occurred while processing this request.  This is usually due to a bug within the server software.  Trying this request again may succeed if the bug is transient, otherwise please report this issue to the issue tracker at: https://github.com/stellar/go/services/horizon/internal/issues. Please include this response in your issue.",
            "instance": "7608d668f9b4/DLZIsyB3Rg-000003"
        }

**Comment by bartekn** [comment]
Looks like it's been fixed.
