### ISSUE TITLE
Make ingest.LedgerTransaction.Meta private

### ISSUE THREAD

**Issue by bartekn** [stellar/go#3491]
`LedgerTransaction.Meta` is low-level object and can be misused. We should make it private (`GetChanges()` should be used instead).

> @tamirms great catch! Yes, `transaction.Meta.Operations` will likely be empty because we're at V2 right now so the proper way would be to get `transaction.Meta.V2.Operations`. So yes, we should use `transaction.GetChanges()` and maybe we should make `LedgerTransaction.Meta` private (in a separate PR).

_Originally posted by @bartekn in https://github.com/stellar/go/pull/3483#r600465388_

**Comment by 2opremio** [comment]
I am half-through a PR to fix this but:

1. A setter in unavoidable for tests (creating fixtures). Maybe I could place the setter in a `_test` file (I am not sure it will work due crossing packages) but ...
2. A getter is needed in `db2/history` for marshalling before ingesting into the DB (`transactionToRow()`)

Thus, I am not sure this can be done without leaking.

**Comment by bartekn** [comment]
What about this:
* We change `LedgerTransaction` to be an interface. That way we don't need a setter, we can just create a separate implementation for tests.
* Regarding `db2/history`, we can allow getting raw meta via a method called `GetUnsafeMeta()` or something like this.

Thoughts, @stellar/horizon-committers?

**Comment by 2opremio** [comment]
>     * We change `LedgerTransaction` to be an interface. That way we don't need a setter, we can just create a separate implementation for tests.

Can you elaborate on how you would do this? I think you would end up having to export the setter regardless of whether it's in an interface or a struct.
