### ISSUE TITLE
Batch status check queries for pending transactions in txsub

### ISSUE THREAD

**Issue by bartekn** [stellar/go#3552]
### What version are you using?

2.1.0

### What did you do?

@tomerweller was running into performance issues when submitting thousands of transactions to a standalone network. It looks like the problem is related to this code:
https://github.com/stellar/go/blob/56d94a2f370fde4e8a7500658cc7fa57ddfc08e4/services/horizon/internal/txsub/system.go#L307-L325

With many pending transactions getting its' results, even when separate queries are fast, can cumulate to a very long updates time (few seconds time). The chart below shows the time distribution of tx status updates after an example ledger ingestion:
<img width="814" alt="Screenshot 2021-04-20 at 00 21 07" src="https://user-images.githubusercontent.com/464938/115376959-73522e80-a1cf-11eb-91e8-9970609acda1.png">

### What did you expect to see?

When checking the status of pending transaction we should send a single batch query instead of thousands queries asking for a single tx result. This should make this magnitudes faster.

When working on this please remember about two things:
* Postgres param limit of around 65k. If a batch query needs to send more params it should be called multiple times.
* The query used right now is searching for both normal txs and fee bump txs. The batch query should do the same thing.

**Comment by ire-and-curses** [comment]
How do we decide when we've accumulated enough status checks to send a single batch query? There's a tradeoff here between not waiting and batching for performance.

**Comment by bartekn** [comment]
Currently we check it on every app tick which is every second, even when there are no pending txs.
