### ISSUE TITLE
Feature Request: Improve CI pipeline to work on forks.

### ISSUE THREAD

**Issue by bukowa** [stellar/go#3568]
### What problem does your feature solve?
Testing stellar/go on forked repositories. That helps when;
- you are testing code that will go into pull request
- you are working on your own fork

### What would you like to see?
Circleci configuration that works on forks. Right now i am experiencing this issue:
https://github.com/stellar/go/blob/master/.circleci/config.yml#L365
````
#!/bin/sh -eo pipefail
echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
TAG=$(git rev-parse --short HEAD)
docker build -f services/horizon/docker/Dockerfile.dev -t stellar/horizon:$TAG .
docker push stellar/horizon:$TAG
Must provide --username with --password-stdin

Exited with code exit status 1

CircleCI received exit code 1
````
I don't think we are able to push docker images into official docker.io/stellar registry.

### What alternatives are there?
Rewriting `.circleci/config.yaml` on forks.

**Comment by leighmcculloch** [comment]
Thanks for reporting this issue with testing on forks. This repository is migrating to GitHub Actions and most builds and tests run on GitHub Actions now and should work on forks. 🎉
