### ISSUE TITLE
Feature Request: Provide recipes to automate provisioning new Horizon instances

### ISSUE THREAD

**Issue by tamirms** [stellar/go#3577]
Some suggestions:

* Helm charts for k8s deployments
* ansible playbooks
* Terraform module

**Comment by sreuland** [comment]
The helm chart provision sounds great, that deployment is [referenced as a possibility in refactored horizon docs for installation.](https://github.com/stellar/stellar-docs/pull/162/files#diff-6bd36975a4aca50d1b90871f3599722171a467a79307afffbc0ac6bcd112b4aeR15)

**Comment by mollykarcher** [comment]
Closed with https://github.com/stellar/stellar-docs/pull/223

**Comment by sreuland** [comment]
@tamir, [helm chart for provisioning Horizon](https://github.com/stellar/helm-charts/tree/main/charts/horizon) is published and  [public docs updated to explain how to use the horizon helm chart](https://github.com/stellar/stellar-docs/pull/216), I think this ticket can be closed now with consideration for helm as the standard and not proceeding with terraform/ansible implementations also. Will close this ticket if you agree on scope?

**Comment by tamirms** [comment]
@sreuland sounds good to me!
