### ISSUE TITLE
Horizon does not commit DB transaction while ingesting

### ISSUE THREAD

**Issue by dimaa6** [stellar/go#3581]
### Horizon version:

2.1.1-fee60c9c1d96605258250cd5b83c373b9f5490cd
go1.16.2

### My setup:

I have some history of Horizon DB from the last year. It finished at certain ledger. Now I need to catch up with actual blockchain. I don't use captive core.

### Command line:

./horizon --db-url=postgresql://horizon:horizon@127.0.0.1/horizon?sslmode=disable --stellar-core-db-url=postgresql://stellar:stellar@127.0.0.1/stellar?sslmode=disable --stellar-core-url=http://127.0.0.1:11626 --network-passphrase="Public Global Stellar Network ; September 2015" --history-archive-urls=http://history.stellar.org/prd/core-live/core_live_001/ --log-file=/home/chainfacts/horizon/log/horizon.log --ingest serve --stellar-core-binary-path=/home/user/stellar-core-16.0 --enable-captive-core-ingestion=false

### Expected result:

I expected Horizon to commit DB transaction either after each ledger it loads, or after some small batch of ledgers.

### What I see instead:

Instead I see Horizon output:

time="2021-05-04T05:39:00.230Z" level=info msg="Processing ledger" commit=false ledger=true pid=19622 sequence=30805714 service=ingest state=false
time="2021-05-04T05:39:00.622Z" level=info msg="Processed ledger" commit=false duration=0.392226914 ledger=true pid=19622 sequence=30805714 service=ingest state=false stats_operations=130 stats_operations_account_merge=0 stats_operations_allow_trust=0 stats_operations_begin_sponsoring_future_reserves=0 stats_operations_bump_sequence=0 stats_operations_change_trust=1 stats_operations_claim_claimable_balance=0 stats_operations_clawback=0 stats_operations_clawback_claimable_balance=0 stats_operations_create_account=1 stats_operations_create_claimable_balance=0 stats_operations_create_passive_sell_offer=0 stats_operations_end_sponsoring_future_reserves=0 stats_operations_in_failed=6 stats_operations_in_successful=124 stats_operations_inflation=0 stats_operations_manage_buy_offer=69 stats_operations_manage_data=0 stats_operations_manage_sell_offer=51 stats_operations_path_payment_strict_receive=4 stats_operations_path_payment_strict_send=0 stats_operations_payment=4 stats_operations_revoke_sponsorship=0 stats_operations_set_options=0 stats_transactions=49 stats_transactions_failed=6 stats_transactions_successful=43
time="2021-05-04T05:39:00.622Z" level=info msg="Processing ledger" commit=false ledger=true pid=19622 sequence=30805715 service=ingest state=false

Notice commit=false. I have a log from a previous attempt to load Stellar blockchain into Horizon DB made a year ago and there it says commit=true. Transaction is indeed not committed, when I either query Horizon via JSON RPC to provide latest ledger, or select count of ledgers in DB, highest ledger number does not change and is what I had before I started ingestion.

Postgres is indeed busy, machine is I/O bound, here is the output of iotop:

  TID  PRIO  USER     DISK READ  DISK WRITE  SWAPIN     IO>    COMMAND                                                                                                                                         
19687 be/4 postgres    2.87 M/s  622.15 K/s  0.00 % 65.30 % postgres: horizon horizon 127.0.0.1(58684) INSERT
27808 be/4 postgres    3.73 K/s   55.88 K/s  0.00 % 35.44 % postgres: checkpointer
4544 be/4 postgres   14.90 K/s    4.61 M/s  0.00 % 11.94 % postgres: stellar stellar 127.0.0.1(51658) INSERT
27810 be/4 postgres    0.00 B/s  566.27 K/s  0.00 %  1.62 % postgres: walwriter
27809 be/4 postgres    0.00 B/s 1743.50 K/s  0.00 %  1.44 % postgres: background writer

Size of horizon DB grows in Postgres, but transaction is never committed.

**Comment by bartekn** [comment]
Horizon is in catching up state and in this state it commits after ingesting all the ledgers (due to the fact that it holds the lock for a distributed ingestion).

If you want to have access to historical endpoints while catching up you need to catchup manually:
1. Stop all horizon instances.
2. Start reingestion: `horizon db reingest range [start ledger] [end ledger]` where `[start ledger]` is the last ledger ingested by horizon and `[end ledger]` is the latest ledger closed by the network.
3. Start another Horizon instance without `--ingest` flag.

If you are far behind the latest history you can also run multiple reingesting processes to catchup faster. More information [here](https://github.com/stellar/go/blob/master/services/horizon/internal/docs/captive_core.md#reingestion).

**Comment by dimaa6** [comment]
@bartekn Thank you! I would be happy to use reingest, but I cannot start it. If I set STELLAR_CORE_BINARY_PATH set (as per instructions from the page you referred to), it says:

Invalid config: one or more captive core params passed (--stellar-core-binary-path or --captive-core-config-append-path) but --ingest not set. If you are migrating from Horizon 1.x.y read the Migration Guide here: https://github.com/stellar/go/blob/master/services/horizon/internal/docs/captive_core.md

If I unset it, it says:

error preparing range: error starting prepare range: opening subprocess: error running stellar-core: error waiting for `stellar-core new-db` subprocess: could not start `stellar-core [new-db]` cmd: fork/exec : no such file or directory

Though stellar-core is available.
