### ISSUE TITLE
Horizon: support querying by Muxed Account and incorporate Muxed accounts in responses

### ISSUE THREAD

**Issue by 2opremio** [stellar/go#3591]
Following the description of https://github.com/stellar/stellar-protocol/issues/617 we should add support for Muxed Accounts in:

1. All account-parameterized requests
2. Responses

With respect to requests ~we should support Muxed Accounts when:~ (edit: we decided to not do this for now)

- ~Querying transactions by account~
- ~Querying operations by account~
- ~Querying effects by account? (we may want to stick to G-addresses for effects)~

With respect to responses, we should support Muxed Accounts when:
- [x] Responding with Operation objects (source account and payment/merge/clawback destination)
- [ ] Responding with Transaction objects (source account)
- [ ] Responding with Effects?

Note: this description may not be complete yet, I will be incorporating new tasks while going through the API and DB.

**Comment by 2opremio** [comment]
The first thing we should clarify/design is how Horizon should respond based on whether it receives an M-acount or or a G-account as a query parameter. Depending on what we decide we could end up with a different DB schema.


There are a bunch of approaches which could be followed:

1. Be strict about G-addreses:
   * If the user provides a G-address (lets call it `GADDR` ), she strictly means that G-address explicitly. Responses should only contain data related to ` GADDR` . In particular, M-addresses with the same underlying `GADDR`  should be discarded.

2. Be strict about M-addresses: 
   * If the user provides an M-address (lets call it `MADDR` , with underlying G-address GADDR), she strictly means that M-address explicitly. Responses should only contain data related to that M-address. Other M-addresses with the same underlying ` GADDR`  as `MADDR` should be discarded. In addition, data related to `GADDR` (i.e. the `Ed25519` variant of `MADDR`, without an `Id`) should also be discarded.

3. Glob G-addresess:
   * If the user provides a G-address (lets call it ` GADDR` ), she means any `Ed2551` or `Med25519` account with the same `Ed25519` data as GADDR. In particular the response should include all the M-addresses with the same `Ed25519` value as `GADDR`, regardless of their ID. And, of course, `GADDR` should be included.

4. Glob M-addresses:
   * If the user provides an M-address (lets call it `MADDR` , with underlying G-address `GADDR`). she means any `Ed2551` or `Med25519` account with the same `Ed25519` data as `GADDR`. In particular the response should include all the M-addresses with the same `Ed25519` value as `GADDR`, regardless of their ID. And, of course, `GADDR` should be included.


I would choose (2) and (3): be strict about M-addresses and glob G-addresses.

We could also make it configurable at query-time, but that would complicate the API and (maybe) the DB schema.

Thoughts?

**Comment by Shaptic** [comment]
Answering this first requires a fundamental understanding of the scope of Horizon's role within muxed accounts. Are we providing a de-facto custodial implementation here? Will it be for stateful endpoints or just historical endpoints? As much as I like the idea of _not_ having `x` slightly-different custodial implementations out there in the world for every exchange that wants it (out of the interest of not reinventing the wheel `x` times), this is still a pretty big burden for us to bear, resource- and complexity-wise. 

My vote would be to keep Horizon as pure as Core in this regard (i.e. Core doesn't "understand" muxed accounts; they're an off-chain convention as far as they're concerned), meaning a vote for (1)-ish and (4)-ish. By "ish" I mean something even simpler than what they're offering above: (1ish) would be "If a user provides a G-address, Horizon behaves as it already does.", and (4ish) would be "If a user provides an M-address, Horizon turns it into a G-address and (1ish) applies." This would be the lowest-impact implementation, right? No DB changes, just transform any M-address in a request to its underlying G-address and move on, then shove the M-address into the response at the end (or don't, because the caller should already know which M-address did the query).

I do think (2) and (3) makes sense for a "true" implementation, but maybe we should wait until there's a clear need for us to take on this role before making the investment? We can just offer barebones support (i.e. just accept the M as if it's a G) for now, and let the consumers of the feature deal with the actual muxing as they'd like.

**Comment by 2opremio** [comment]
Now, regarding Muxed accounts in responses, my plan is to add new fields with a `_muxed` suffix (other name suggestions are welcome). The reason to keep existing fields as is, is backwards compatibility.

The field won't be present if the account used isn't muxed.

For instance, here's an `/operations` response with the new fields:


```json
{
  "_links": {
    "self": {
      "href": "https://horizon.stellar.org/operations/?cursor=\u0026limit=10\u0026order=asc"
    },
    "next": {
      "href": "https://horizon.stellar.org/operations/?cursor=33818572492801\u0026limit=10\u0026order=asc"
    },
    "prev": {
      "href": "https://horizon.stellar.org/operations/?cursor=12884905985\u0026limit=10\u0026order=desc"
    }
  },
  "_embedded": {
    "records": [
      {
        "_links": {
          "self": {
            "href": "https://horizon.stellar.org/operations/12884905985"
          },
          "transaction": {
            "href": "https://horizon.stellar.org/transactions/3389e9f0f1a65f19736cacf544c2e825313e8447f569233bb8db39aa607c8889"
          },
          "effects": {
            "href": "https://horizon.stellar.org/operations/12884905985/effects"
          },
          "succeeds": {
            "href": "https://horizon.stellar.org/effects?order=desc\u0026cursor=12884905985"
          },
          "precedes": {
            "href": "https://horizon.stellar.org/effects?order=asc\u0026cursor=12884905985"
          }
        },
        "id": "12884905985",
        "paging_token": "12884905985",
        "transaction_successful": true,
        "source_account": "GA7QYNF7SOWQ3GLR2BGMZEHXAVIRZA4KVWLTJJFC7MGXUA74P7UJVSGZ",
       "source_account_muxed": "MA7QYNF7SOWQ3GLR2BGMZEHXAVIRZA4KVWLTJJFC7MGXUA74P7UJUAAAAAAAAAAAACJUQ",
        "type": "create_account",
        "type_i": 0,
        "created_at": "2015-09-30T17:15:54Z",
        "transaction_hash": "3389e9f0f1a65f19736cacf544c2e825313e8447f569233bb8db39aa607c8889",
        "starting_balance": "20.0000000",
        "funder": "GAAZI4TCR3TY5OJHCTJC2A4QSY6CJWJH5IAJTGKIN2ER7LBNVKOCCWN7",
        "account": "GALPCCZN4YXA3YMJHKL6CVIECKPLJJCTVMSNYWBTKJW4K5HQLYLDMZTB"
      },
      {
        "_links": {
          "self": {
            "href": "https://horizon.stellar.org/operations/12884905986"
          },
          "transaction": {
            "href": "https://horizon.stellar.org/transactions/3389e9f0f1a65f19736cacf544c2e825313e8447f569233bb8db39aa607c8889"
          },
          "effects": {
            "href": "https://horizon.stellar.org/operations/12884905986/effects"
          },
          "succeeds": {
            "href": "https://horizon.stellar.org/effects?order=desc\u0026cursor=12884905986"
          },
          "precedes": {
            "href": "https://horizon.stellar.org/effects?order=asc\u0026cursor=12884905986"
          }
        },
        "id": "12884905986",
        "paging_token": "12884905986",
        "transaction_successful": true,
        "source_account": "GA7QYNF7SOWQ3GLR2BGMZEHXAVIRZA4KVWLTJJFC7MGXUA74P7UJVSGZ",
        "source_account_muxed": "MA7QYNF7SOWQ3GLR2BGMZEHXAVIRZA4KVWLTJJFC7MGXUA74P7UJUAAAAAAAAAAAACJUQ",
        "type": "payment",
        "type_i": 1,
        "created_at": "2015-09-30T17:15:54Z",
        "transaction_hash": "3389e9f0f1a65f19736cacf544c2e825313e8447f569233bb8db39aa607c8889",
        "asset_type": "native",
        "from": "GAAZI4TCR3TY5OJHCTJC2A4QSY6CJWJH5IAJTGKIN2ER7LBNVKOCCWN7",
        "to": "GAQAA5L65LSYH7CQ3VTJ7F3HHLGCL3DSLAR2Y47263D56MNNGHSQSTVY",
        "to_muxed": "MAQAA5L65LSYH7CQ3VTJ7F3HHLGCL3DSLAR2Y47263D56MNNGHSQSAAAAAAAAAAE2LP26",
        "amount": "99999999959.9999700"
      },
```

In this case all the accounts are multiplexed, but, as I mentioned, a missing `_muxed` field would indicate that the account use isn't multiplexed (i.e. `Ed25519` type and not `Med25519`).

**Comment by leighmcculloch** [comment]
> my plan is to add new fields with a `_muxed` suffix

Looks good to me. It looks the same as the [SEP-23 proposal for Horizon responses](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0023.md#horizon-api-changes).

Can you also include the `_muxed_id` which is also mentioned in the SEP? It will allow systems trying only on the JSON days to extract the iD simply. If it is added, can it be added as a string type? Even though the value is an integer ID it's an int64 and JavaScript only formally supports 32bit. Also, we have discussed adding non-integer IDs so strings would lend themselves to that extension in the future.

**Comment by 2opremio** [comment]
@leighmcculloch sure!

**Comment by 2opremio** [comment]
We discussed this in the Horizon meeting and decided to keep it simple and avoid schema changes (which would be required for querying by M-strkey).

Thus, the conclusion so far is that:
* For querying, we will pick option (3) (G-strkey globbing) and nothing else for now. I will however spend some time thinking about what schema changes would be required for (2) (strict M-strkey querying)
* For responses there was already quorum on adding `_muxed`  and `_muxed_id` suffixes, as described in SEP-23. So we will do that.

**Comment by 2opremio** [comment]
The only remaining point is so far is, do we care about Muxed accounts for effects?

I am not sure it adds a lot of value. _If_ we decide to do it, I propose to incorporate the `_muxed` and `_muxed_id` suffixes like we will do with the operation details:

That would be something like:

```json
{
  "_links": {
    "self": {
      "href": "https://horizon.stellar.org/effects?cursor=\u0026limit=10\u0026order=asc"
    },
    "next": {
      "href": "https://horizon.stellar.org/effects?cursor=33676838572034-1\u0026limit=10\u0026order=asc"
    },
    "prev": {
      "href": "https://horizon.stellar.org/effects?cursor=12884905985-1\u0026limit=10\u0026order=desc"
    }
  },
  "_embedded": {
    "records": [
      {
        "_links": {
          "operation": {
            "href": "https://horizon.stellar.org/operations/12884905986"
          },
          "succeeds": {
            "href": "https://horizon.stellar.org/effects?order=desc\u0026cursor=12884905986-1"
          },
          "precedes": {
            "href": "https://horizon.stellar.org/effects?order=asc\u0026cursor=12884905986-1"
          }
        },
        "id": "0000000012884905986-0000000001",
        "paging_token": "12884905986-1",
        "account": "GAQAA5L65LSYH7CQ3VTJ7F3HHLGCL3DSLAR2Y47263D56MNNGHSQSTVY",
        "acount_muxed": "MAQAA5L65LSYH7CQ3VTJ7F3HHLGCL3DSLAR2Y47263D56MNNGHSQSAAAAAAAAAAE2LP26",
        "account_muxed_id": foo,
        "type": "account_credited",
        "type_i": 2,
        "created_at": "2015-09-30T17:15:54Z",
        "asset_type": "native",
        "amount": "99999999959.9999700"
      },

```

**Comment by 2opremio** [comment]
In addition, I don't think it's going to be possible to add `source_account_muxed` and `source_account_muxed_id` for transactions without changing the schema.

Unlike with operations, for which we have a schema-free JSON column for the details, the transactions table would need to be modified in order to support the new fields.

**Comment by leighmcculloch** [comment]
> do we care about Muxed accounts for effects?

I think we do, simply for the fact that once this change is rolled out for other endpoints we're making a statement that when `_muxed` is present, the address was muxed, and when not, it wasn't. It will be very unintuitive that a missing `_muxed` on effects doesn't also signal that the address wasn't muxed.

**Comment by tomerweller** [comment]
> In addition, I don't think it's going to be possible to add source_account_muxed and source_account_muxed_id for transactions without changing the schema.

The schema already contains the transaction envelope xdr, which should contain all the information required.

Looks like the envelope is already being used to extract memos here: https://github.com/stellar/go/blob/6d45e627f4ab14d111199dc6d1d2fa8f80ea1276/services/horizon/internal/resourceadapter/transaction.go#L45

We can move the envelope decoding outside of the `memoBytes()` function and reuse it for muxed accounts as well. 

With that said, decoding every transaction envelope on the fly might have a performance impact.

**Comment by 2opremio** [comment]
> With that said, decoding every transaction envelope on the fly might have a performance impact.

I implicitly discarded doing that for performance, but maybe it's acceptable? (I doubt it)

**Comment by 2opremio** [comment]
For the record, we ended up changing the schema and adding columns for the muxed accounts
