### ISSUE TITLE
Horizon: Stuck in loop when paginating (prev and asc alternating)

### ISSUE THREAD

**Issue by wanecek** [stellar/go#3637]
### What version are you using?

Testnet Horizon.

### What did you do?

I tried to fetch a larger range of ledgers using the HAL-format pagination links, and found myself to be stuck in a loop due to `asc` and `desc` swapping in the pagination links.

A big disclaimer here is that I should instead have been using `next` to start with, but instead choose `prev`. This may indeed be the intended behavior when reaching the End of History.

1. Make request to `https://horizon-testnet.stellar.org/ledgers?limit=200&order=desc`
2. Make request to previous item from `request._links.prev.href`

### What did you expect to see?

To not get stuck in a loop, but instead to keep the `desc` order and reach an endpoint in the form of an empty list. But, again, maybe this is the intended behavior.

### What did you see instead?

When logging the requests URLs, I got something like this:
```
...
Fetching:  https://horizon-testnet.stellar.org/ledgers?cursor=5018982817988608&limit=200&order=desc
Fetching:  https://horizon-testnet.stellar.org/ledgers?cursor=5018978523021312&limit=200&order=asc
Fetching:  https://horizon-testnet.stellar.org/ledgers?cursor=5018982817988608&limit=200&order=desc
Fetching:  https://horizon-testnet.stellar.org/ledgers?cursor=5018978523021312&limit=200&order=asc
Fetching:  https://horizon-testnet.stellar.org/ledgers?cursor=5018982817988608&limit=200&order=desc
Fetching:  https://horizon-testnet.stellar.org/ledgers?cursor=5018978523021312&limit=200&order=asc
Fetching:  https://horizon-testnet.stellar.org/ledgers?cursor=5018982817988608&limit=200&order=desc
Fetching:  https://horizon-testnet.stellar.org/ledgers?cursor=5018978523021312&limit=200&order=asc
Fetching:  https://horizon-testnet.stellar.org/ledgers?cursor=5018982817988608&limit=200&order=desc
...
```

**Comment by bartekn** [comment]
I'm afraid this is broken since early versions of Horizon and fixing would require making one more DB query for each request to find the starting cursor of the previous page. As a workaround you need to follow the steps you describe (so basically change the `order` param and use `next` links).
