### ISSUE TITLE
Command not working: $ horizon db reap

### ISSUE THREAD

**Issue by ckmakcesar** [stellar/go#364]
As I [encountered this Horizon ingestion issue](https://github.com/stellar/go/issues/335), I followed [this guide to try to repair my Horizon](https://github.com/stellar/go/blob/master/services/horizon/internal/docs/reference/admin.md#correcting-gaps-in-historical-data):

> Stop horizon.
> run horizon db reap to clear the historical database.
> Clear the cursor for horizon by running stellar-core -c "dropcursor?id=HORIZON" (ensure capitilization is maintained).
> Clear ledger metadata from before the gap by running stellar-core -c "maintenance?queue=true".
> Restart horizon.

$ DATABASE_URL="postgres://user:pass1234@localhost/horizon"
$ horizon db reap
`2018/03/15 16:01:59 Invalid config: db-url is blank.  Please specify --db-url on the command line or set the DATABASE_URL environment variable.`

$ horizon db reap "--db-url postgres://user:pass1234@localhost/horizon"
`Error: unknown flag: --db-url postgres://user:pass1234@localhost/horizon
Usage:
  horizon db reap [flags]`

It seems the flag "--db-url" does not work, so as the command. Thanks!

**Comment by nullstyle** [comment]
@ckmakcesar This was fixed with v0.12.1 with https://github.com/stellar/go/commit/1fabaebf261dd22a92c009ff2d5927883ec5a3e8

Please update and try again using `horizon db reap --db-url "postgres://user:pass1234@localhost/horizon"`
