### ISSUE TITLE
Upgrade to the latest version still the same problem

### ISSUE THREAD

**Issue by shenhao217** [stellar/go#3657]
Hello,Upgrade to the latest version still the same problem
time="2021-06-02T19:08:47.326Z" level=info msg="Tx: applying ledger 35703670 (txs:140, ops:322)" pid=16758 subservice=stellar-core
time="2021-06-02T19:08:47.421Z" level=info msg="Tx: applying ledger 35703671 (txs:197, ops:460)" pid=16758 subservice=stellar-core
time="2021-06-02T19:08:47.523Z" level=info msg="starting request" host="localhost:8080" ip="127.0.0.1:59274" method=POST path=/prepare-range pid=16758 req=stellar-north-american/QjkGXOhp9e-000365 subservice=api subsys=http useragent=Go-http-client/1.1
time="2021-06-02T19:08:47.523Z" level=info msg="finished request" bytes=134 duration="80.364µs" method=POST path=/prepare-range pid=16758 req=stellar-north-american/QjkGXOhp9e-000365 route=/prepare-range status=200 subservice=api subsys=http
**time="2021-06-02T19:08:47.869Z" level=warning msg="Could not prepare range" error="opening subprocess: Error fast-forwarding to 35703671: unmarshalling framed LedgerCloseMeta: xdr:decode: switch '19' is not valid enum value for union" pid=16758 preparedRange="[35703671,latest)" subservice=api**
time="2021-06-02T19:08:48.523Z" level=info msg="starting request" host="localhost:8080" ip="127.0.0.1:59274" method=POST path=/prepare-range pid=16758 req=stellar-north-american/QjkGXOhp9e-000366 subservice=api subsys=http useragent=Go-http-client/1.1
time="2021-06-02T19:08:48.523Z" level=info msg="finished request" bytes=134 duration="81.898µs" method=POST path=/prepare-range pid=16758 req=stellar-north-american/QjkGXOhp9e-000366 route=/prepare-range status=200 subservice=api subsys=http
time="2021-06-02T19:08:48.937Z" level=info msg="default: Config from /usr/local/product/horizon2.0/stellar-core.cfg" pid=16758 subservice=stellar-core
time="2021-06-02T19:08:48.972Z" level=info msg="default: Using QUORUM_SET: {" pid=16758 subservice=stellar-core
time="2021-06-02T19:08:48.972Z" level=info msg="\"t\" : 3," pid=16758 subservice=stellar-core
time="2021-06-02T19:08:48.972Z" level=info msg="\"v\" : [ \"sdf_watcher1\", \"sdf_watcher2\", \"sdf_watcher3\" ]" pid=16758 subservice=stellar-core
time="2021-06-02T19:08:48.972Z" level=info msg="}" pid=16758 subservice=stellar-core
time="2021-06-02T19:08:48.972Z" level=warning msg="default: Differs from generated: {" pid=16758 subservice=stellar-core
time="2021-06-02T19:08:48.972Z" level=info msg="\"t\" : 2," pid=16758 subservice=stellar-core
time="2021-06-02T19:08:48.972Z" level=info msg="\"v\" : [" pid=16758 subservice=stellar-core
time="2021-06-02T19:08:48.972Z" level=info msg="{" pid=16758 subservice=stellar-core
time="2021-06-02T19:08:48.972Z" level=info msg="\"t\" : 2," pid=16758 subservice=stellar-core
time="2021-06-02T19:08:48.972Z" level=info msg="\"v\" : [ \"sdf_watcher3\", \"sdf_watcher1\", \"sdf_watcher2\" ]" pid=16758 subservice=stellar-core
time="2021-06-02T19:08:48.972Z" level=info msg="}," pid=16758 subservice=stellar-core
time="2021-06-02T19:08:48.972Z" level=info msg="{" pid=16758 subservice=stellar-core
time="2021-06-02T19:08:48.972Z" level=info msg="\"t\" : 2," pid=16758 subservice=stellar-core
time="2021-06-02T19:08:48.972Z" level=info msg="\"v\" : [ \"COINQVEST (Finland)\", \"COINQVEST (Hong Kong)\", \"COINQVEST (germany)\" ]" pid=16758 subservice=stellar-core
time="2021-06-02T19:08:48.972Z" level=info msg="}" pid=16758 subservice=stellar-core
time="2021-06-02T19:08:48.972Z" level=info msg="]" pid=16758 subservice=stellar-core
time="2021-06-02T19:08:48.972Z" level=info msg="}" pid=16758 subservice=stellar-core
time="2021-06-02T19:08:48.972Z" level=info msg="default: Assigning calculated value of 0 to FAILURE_SAFETY" pid=16758 subservice=stellar-core
time="2021-06-02T19:08:49.027Z" level=info msg="Database: Connecting to: sqlite3://buckets/minimal.db" pid=16758 subservice=stellar-core
time="2021-06-02T19:08:49.039Z" level=info msg="SCP: LocalNode::LocalNode@GDLNU qSet: 1b865e" pid=16758 subservice=stellar-core
time="2021-06-02T19:08:49.039Z" level=info msg="default: Listening on 127.0.0.1:11626 for HTTP requests" pid=16758 subservice=stellar-core
time="2021-06-02T19:08:49.039Z" level=info msg="default: Application destructing" pid=16758 subservice=stellar-core
time="2021-06-02T19:08:49.040Z" level=error msg="default: Exception occurred while shutting down: sqlite3_statement_backend::prepare: no such table: storestate" pid=16758 subservice=stellar-core
time="2021-06-02T19:08:49.040Z" level=info msg="default: Application destroyed" pid=16758 subservice=stellar-core
time="2021-06-02T19:08:49.041Z" level=info msg="default: Minimal database not found, creating one..." pid=16758 subservice=stellar-core
time="2021-06-02T19:08:49.041Z" level=info msg="Database: Connecting to: sqlite3://buckets/minimal.db" pid=16758 subservice=stellar-core
time="2021-06-02T19:08:49.050Z" level=info msg="SCP: LocalNode::LocalNode@GDLNU qSet: 1b865e" pid=16758 subservice=stellar-core
time="2021-06-02T19:08:49.050Z" level=info msg="default: Listening on 127.0.0.1:11626 for HTTP requests" pid=16758 subservice=stellar-core
time="2021-06-02T19:08:49.135Z" level=info msg="default: *" pid=16758 subservice=stellar-core
time="2021-06-02T19:08:49.135Z" level=info msg="default: * The database has been initialized" pid=16758 subservice=stellar-core
time="2021-06-02T19:08:49.135Z" level=info msg="default: *" pid=16758 subservice=stellar-core
time="2021-06-02T19:08:49.135Z" level=info msg="Database: Applying DB schema upgrade to version 13" pid=16758 subservice=stellar-core
time="2021-06-02T19:08:49.138Z" level=info msg="Database: DB schema is in current version" pid=16758 subservice=stellar-core
time="2021-06-02T19:08:49.138Z" level=info msg="Ledger: Established genesis ledger, closing" pid=16758 subservice=stellar-core
time="2021-06-02T19:08:49.138Z" level=info msg="Ledger: Root account: GAAZI4TCR3TY5OJHCTJC2A4QSY6CJWJH5IAJTGKIN2ER7LBNVKOCCWN7" pid=16758 subservice=stellar-core
time="2021-06-02T19:08:49.138Z" level=info msg="Ledger: Root account seed: SB5MGOMXKRHDC5OSM26QEJBZWIWNWFSQRQARMPZG4XFSUPQQIWUXTVO6" pid=16758 subservice=stellar-core
time="2021-06-02T19:08:49.197Z" level=info msg="default: Connection effective settings:" pid=16758 subservice=stellar-core
time="2021-06-02T19:08:49.197Z" level=info msg="default: TARGET_PEER_CONNECTIONS: 16" pid=16758 subservice=stellar-core
time="2021-06-02T19:08:49.197Z" level=info msg="default: MAX_ADDITIONAL_PEER_CONNECTIONS: 128" pid=16758 subservice=stellar-core
time="2021-06-02T19:08:49.197Z" level=info msg="default: MAX_PENDING_CONNECTIONS: 500" pid=16758 subservice=stellar-core
time="2021-06-02T19:08:49.197Z" level=info msg="default: MAX_OUTBOUND_PENDING_CONNECTIONS: 56" pid=16758 subservice=stellar-core
time="2021-06-02T19:08:49.197Z" level=info msg="default: MAX_INBOUND_PENDING_CONNECTIONS: 444" pid=16758 subservice=stellar-core
time="2021-06-02T19:08:49.197Z" level=info msg="default: Application destructing" pid=16758 subservice=stellar-core
time="2021-06-02T19:08:49.198Z" level=info msg="default: Application destroyed" pid=16758 subservice=stellar-core
time="2021-06-02T19:08:49.202Z" level=info msg="default: Starting stellar-core stellar-core 17.1.0 (6c86d890d2e8d91324324701f5357c8cac5e3098)" pid=16758 subservice=stellar-core

I run horizon version and it shows 
2.4.0-ef4b12c76f8aad7a3c98e6152def7e26985f7ecd
go1.16.3

**Comment by bartekn** [comment]
Looking at the logs it seems you are running `captive-core` which is an experimental software. Please remove `--remote-captive-core-url` from your config.

**Comment by shenhao217** [comment]
Thank you very much for your suggestion, my problem has been solved, I wish you a happy life
