### ISSUE TITLE
Reingestion is broken for the `history_{transaction,operation}_claimable_balances` tables

### ISSUE THREAD

**Issue by 2opremio** [stellar/go#3659]
When running the following command in testnet, @jacekn found a problem

```
# stellar-horizon-cmd db reingest range 380400 381000
2021/06/03 09:28:50 error processing ledger sequence=380504: Error commiting changes from processor: error in *processors.ClaimableBalancesTransactionProcessor.Commit: could not flush transaction claimable balances to db: error adding values while inserting to history_transaction_claimable_balances: exec failed: pq: duplicate key value violates unique constraint "index_history_transaction_claimable_balances_on_ids"
```

It turns out that the `history_{transaction,operation}_claimable_balances` tables, introduced in Horizon 2.1, are not cleaned up (see the `DeleteRangeAll()` code) before reingesting a range. This causes conflicts with existing rows due to `UNIQUE` constraints.

**Comment by 2opremio** [comment]
We should consider releasing Horizon 2.4.1 with a fix for this

**Comment by ire-and-curses** [comment]
Yes we should do a patch release ASAP
