### ISSUE TITLE
Evaluate reingestion testing

### ISSUE THREAD

**Issue by 2opremio** [stellar/go#3660]
#3659 could had probably been avoided through testing.

We should evaluate Horizon's testing of reingestion.

**Comment by bartekn** [comment]
From duplicated https://github.com/stellar/go/issues/3695: we should add integration tests for reingestion: both single and parallel workers.

**Comment by 2opremio** [comment]
Anddd ... we managed to break reingestion in the exact same way at https://github.com/stellar/go/issues/4110 🤕

**Comment by 2opremio** [comment]
How I think we should test this is by creating an intergation test that:

1. Submits all the possible Stellar operations to Core
2. Makes sure those operations are ingested
3. Reingest the operations without resetting the DB (see `TestReingestDB()` as a reference)
4. Fails if a new operation is introduced (to make sure it's future proof). See https://github.com/stellar/go/pull/3560 as a reference
