### ISSUE TITLE
exp/services/recoverysigner: empty allowed accounts cause application crash

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/go#3665]
When starting the recoverysigner without allowed accounts, the application crashes.

The allowed accounts feature added in 15de5ffd450223e1bc5abf80575d906dc2eabb6e is intended to be an optional feature, but it appears it is required by the code because the code isn't handling its absence. The CLI options parameters don't have the parameter defined as required, so there is no helpful error message if a user doesn't provide it.

When starting the application without the parameter specified, I see the following error as if I have provided a malformed invalid value for the option.

```
FATA[2021-06-04T21:59:55.747Z] Error: parsing allowed source accounts: strkey is 0 bytes long; minimum valid length is 5  pid=17606
```

I think this should be fixed by keeping the parameter as optional and making it so that if no value is provided the previous behavior is retained.

**Comment by mollykarcher** [comment]
Closing all recoverysigner issues
