### ISSUE TITLE
Friendbot redirect not working (missing config?)

### ISSUE THREAD

**Issue by pselden** [stellar/go#367]
From here: https://github.com/stellar/go/pull/217 it seems like there was supposed to be a redirect to the friendbot microservice -- looks like the code is here: https://github.com/stellar/go/blob/master/services/horizon/internal/init_web.go#L130

However, when doing an actual request to it it does not appear that the FriendBotURL configuration is set up properly, because the redirect just points to /

This is causing issues with friendbot funding in all of the SDKs that use horizon for friendbot funding (and used to be a problem in labs until it was updated to point directly to the microservice).

```
curl https://horizon-testnet.stellar.org/friendbot?addr=GBJHO7WMYSRTO6WZ4H6PY6PHBPSHN6FRGHASDPM4QR4BW5FAGTTTNW6A 
<a href="/?addr=GBJHO7WMYSRTO6WZ4H6PY6PHBPSHN6FRGHASDPM4QR4BW5FAGTTTNW6A">Temporary Redirect</a>.
```

**Comment by harishrongala** [comment]
We are having the same issue. Says, 307 Temporary redirect

**Comment by nikhilsaraf** [comment]
this has been fixed
