### ISSUE TITLE
Make update to support latest stellar-core (10.0.0 release)

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/go#370]
The https://github.com/stellar/stellar-core/pull/1533 (BumpSeq) PR got merged into master.

Most notable changes that need to be supported in Horizon and SDKs:
* addition of the new `BUMP_SEQUENCE` operation
* move to signed `int64` type from `uint64` for `SequenceNumber` (I expect this one to be a search replace type of thing - no data was ever emitted that cannot be converted into the signed value)
* (Horizon only) meta data format changed
   * We now use `meta.v1().operations` instead of `m.operations()` , but code should be able to import both versions as we don't convert the old data
   * Additional meta data per transaction may be emitted in `meta.v1().txchanges` (for example this is where sequence number processing will appear instead of txhistory starting in v10 of the protocol). Those side effects are happening before operations but during the tx processing.

**Comment by nullstyle** [comment]
> We now use meta.v1().operations instead of m.operations() , but code should be able to import both versions as we don't convert the old data

Do you recommend we switch on the protocol version of the ledger header to decide what path to inspect?  or should we simply prioritize the new form over the old form?

**Comment by MonsieurNicolas** [comment]
no: `TransactionMeta` has a discriminant `v`, switch on its value instead (if 0 -> old path, 1 -> new path).
New stellar core is going to always generate the new format, even for old ledgers:
I did it like this such that we keep our options open and should be able to remove support for old meta format.

**Comment by MonsieurNicolas** [comment]
What is the target date for a "testing" version of this work?

We announced that this will be available to developers this week in testing environments (ie quickstart "testing" image).

As for the "stable" version, the "stable" release of core will land later this month, and a stable version of Horizon is a prerequisite to deploy it.
