### ISSUE TITLE
stellarCoreRunner.nonce is unused

### ISSUE THREAD

**Issue by bartekn** [stellar/go#3700]
`stellarCoreRunner.nonce` seems to be unused. We should remove it.

**Comment by Shaptic** [comment]
It looks like `nonce` is used by the Windows version of the `stellarCoreRunner`:

https://github.com/stellar/go/blob/a58b746a6de5c5056f841a61f8ad073247a16fdf/ingest/ledgerbackend/stellar_core_runner_windows.go#L13-L24

Now I don't think any of us have tested this properly on Windows in some time, but point is it's definitely not unused.

**Comment by 2opremio** [comment]
Yeah, I just checked this as well. I think we should close this.
