### ISSUE TITLE
Horizon reports reingest range overlap with newly ingested ledgers without 

### ISSUE THREAD

**Issue by dimaa6** [stellar/go#3701]
### Tried to run reingest:

./horizon --db-url="postgresql://horizon:horizon@127.0.0.1/horizon?sslmode=disable" --stellar-core-db-url="postgresql://stellar:stellar@127.0.0.1/stellar?sslmode=disable" --stellar-core-url="http://127.0.0.1:11626" --network-passphrase="Public Global Stellar Network ; September 2015" --history-archive-urls="http://history.stellar.org/prd/core-live/core_live_001" db reingest range 30681321 30681340 --force

### What did you expect to see?

Expected ranges to be ingested.

### What did you see instead?

postgres is waiting in deadlock:

```
SELECT blocked_locks.pid     AS blocked_pid,
         blocked_activity.usename  AS blocked_user,
         blocking_locks.pid     AS blocking_pid,
         blocking_activity.usename AS blocking_user,
         blocked_activity.query    AS blocked_statement,
         blocking_activity.query   AS current_statement_in_blocking_process
   FROM  pg_catalog.pg_locks         blocked_locks
    JOIN pg_catalog.pg_stat_activity blocked_activity  ON blocked_activity.pid = blocked_locks.pid
    JOIN pg_catalog.pg_locks         blocking_locks 
        ON blocking_locks.locktype = blocked_locks.locktype
        AND blocking_locks.database IS NOT DISTINCT FROM blocked_locks.database
        AND blocking_locks.relation IS NOT DISTINCT FROM blocked_locks.relation
        AND blocking_locks.page IS NOT DISTINCT FROM blocked_locks.page
        AND blocking_locks.tuple IS NOT DISTINCT FROM blocked_locks.tuple
        AND blocking_locks.virtualxid IS NOT DISTINCT FROM blocked_locks.virtualxid
        AND blocking_locks.transactionid IS NOT DISTINCT FROM blocked_locks.transactionid
        AND blocking_locks.classid IS NOT DISTINCT FROM blocked_locks.classid
        AND blocking_locks.objid IS NOT DISTINCT FROM blocked_locks.objid
        AND blocking_locks.objsubid IS NOT DISTINCT FROM blocked_locks.objsubid
        AND blocking_locks.pid != blocked_locks.pid
    JOIN pg_catalog.pg_stat_activity blocking_activity ON blocking_activity.pid = blocking_locks.pid
   WHERE NOT blocked_locks.granted;

blocked_pid | blocked_user | blocking_pid | blocking_user |   blocked_statement  |                            current_statement_in_blocking_process                            

        9714 | horizon      |        12888 | horizon       | SELECT key_value_store.value FROM key_value_store WHERE key_value_store.key = $1 FOR UPDATE | DELETE FROM history_effects WHERE history_operation_id >= $1 AND history_operation_id < $2
       16337 | horizon      |         9714 | horizon       | SELECT key_value_store.value FROM key_value_store WHERE key_value_store.key = $1 FOR UPDATE | SELECT key_value_store.value FROM key_value_store WHERE key_value_store.key = $1 FOR UPDATE
```
(2 rows)

First, it said that range intersects with already ingested range and I need to use force flag. force flag is not documented, I guessed it. Then, after figuring out force flag, I specified wider range and it stuck on ledger 30681343. Number was consistent, so I reduced highest ledger number to 30681340, but now it hangs upon completion. Am I doing anything wrong? Can somebody provide a minimal working example of reingest? There is no other instance of Horizon running.

**Comment by dimaa6** [comment]
Tried reingesting without captive core, still no success:

./horizon --db-url="postgresql://horizon:horizon@127.0.0.1/horizon?sslmode=disable" --stellar-core-db-url="postgresql://stellar:stellar@127.0.0.1/stellar?sslmode=disable" --stellar-core-url="http://127.0.0.1:11626" --network-passphrase="Public Global Stellar Network ; September 2015" --history-archive-urls="http://history.stellar.org/prd/core-live/core_live_001" --history-retention-count=0 --enable-captive-core-ingestion=false db reingest range 30681321 30681340 --force
INFO[2021-06-17T09:46:52.322Z] Ingestion system initial state                current_state="reingestHistoryRange(fromLedger=30681321, toLedger=30681340, force=true)" pid=23786 service=ingest
INFO[2021-06-17T09:46:52.322Z] Preparing ledger backend to retrieve range    from=30681321 pid=23786 service=ingest to=30681340
INFO[2021-06-17T09:46:52.413Z] Range ready                                   duration=0.091337033 from=30681321 pid=23786 service=ingest to=30681340

Nothing happens after that. posgtres shows no locks. Is there any configuration in which Horizon will reingest a range and commit DB transaction after reingesting?

**Comment by bartekn** [comment]
> There is no other instance of Horizon running.

I tried the same command using Captive-Core in 2.4.1 and it ingested it without a problem. Looking at the blocked queries output from your Postgres I think you actually have other Horizon running. I created this [Docker image](https://gist.github.com/bartekn/152599f0b7f63a4c442d86cd0baddc65) you can run to see it's working.

> Then, after figuring out force flag, I specified wider range and it stuck on ledger 30681343

It's possible if you are not use Captive-Core because then the process will wait indefinitely for ledger to appear in Stellar-Core DB. Without Captive-Core Horizon assumes all the required ledgers are in Stellar-Core DB. Thus, you should use Captive-Core.
