### ISSUE TITLE
Import session failed when ingest = true

### ISSUE THREAD

**Issue by matheusb-comp** [stellar/go#371]
After updating `stellar-core` to the version `9.2.0` (master branch `v9.2.0-41-g02c6714`), and `horizon` to version `0.12.3`, the ledgers are not ingested by horizon, and I get the following error:
```
INFO[0000] Starting horizon on :8000 (ingest: true)      pid=5111
ERRO[0001] import session failed: failed to load transactions: select failed: sql: Scan error on column index 5: xdr:decode: switch '1' is not valid for union  pid=5111
```

I also tried dropping both the core and horizon databases, initializing them again, and even tried the upgrade instructions described in the [Horizon v0.12.2](https://github.com/stellar/go/releases/tag/horizon-v0.12.2) release.

**Comment by matheusb-comp** [comment]
I understand now that I shouldn't use stellar-core master branch, since it is the development branch. Switched to prod (`v9.2.0`) and it works now.

About the error, it appears to be something related to the first bytes of the `result_xdr` that is stored in the `txhistory.txresult` field of the core database (maybe it was changed on commit [10179d](https://github.com/stellar/stellar-core/commit/10179d64d73cd75db3aa99535d00093c1c1e5775)?).

[Here](https://github.com/stellar/go/files/1839656/core-v9.2.0-41-g02c6714-history.zip) is a CSV of the `txhistory` my stellar-core generated.
For example the transaction `c242e433720aee00a118c0a4e25fb1ce3ef14d65b2555dc29c1d5fd06a3f2c16`
On [horizon.stellar.org](https://horizon.stellar.org/transactions/c242e433720aee00a118c0a4e25fb1ce3ef14d65b2555dc29c1d5fd06a3f2c16) the `result_xdr` is
> `AAAAAAAAAGQAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAA=`

while on the `txhistory` table it was stored as
> `wkLkM3IK7gChGMCk4l+xzj7xTWWyVV3CnB1f0Go/LBYAAAAAAAAAZAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAA==`

But I don't know enough about the XDR decode process to investigate this further.

**Comment by swetakedia** [comment]
@matheusb-comp - Hi I am facing the same issue however I am running  "build" : "v9.2.0-84-g6cd9f03", of stellar core.

I am building core from source - so any help to checkout a stable version will be helpful.

**Comment by matheusb-comp** [comment]
@swetakedia: Make sure you are compiling the `prod` branch, in my case it was the only one I downloaded, with the command:

`git clone --single-branch --branch prod https://github.com/stellar/stellar-core.git [<folder>]`
