### ISSUE TITLE
services/horizon: Make `migrate up/down [COUNT]` param mandatory to prevent wiping your db

### ISSUE THREAD

**Issue by paulbellamy** [stellar/go#3720]
### What problem does your feature solve?

Currently `horizon db migrate down` command accepts optional `[COUNT]` parameter. When not provided the command will default to all migrations and will start reverting them resulting in empty database.
This means that a user who, for example, forgets to add `--help` flat can accidentally wipe horizon data. Some commands, for example `horizon db`, will print help instead of performing actions so it's easy to incorrectly assume `horizon db migrate down` behaves in the same way.

### What would you like to see?

Make the `[COUNT]` param mandatory so people know more about what they're doing.

### What alternatives are there?

It's not clear how to establish what the `[COUNT]` should be when downgrading horizon. An alternative approach could be version number that we want to go back to. For example when downgrading to `2.3.1` users could run:
```
horizon db migrate to 2.3.1
```
With above they don't have to know how many (if any at all) schema downgrades are required.

**Comment by paulbellamy** [comment]
There's also an issue if you've downgraded the horizon deb package first, it won't have the relevant migration scripts to downgrade. For maximum magic, we could also store the down-migration script in the gorp_migrations table, allowing you to downgrade even if the horizon package you’re on doesn’t have the relevant migration files. but that seems like it might be too much magic...

**Comment by paulbellamy** [comment]
Not sure if there is a nice, low-maintenance, way to tie migrations to their relevant release version...

**Comment by ire-and-curses** [comment]
Some of what you're musing about reminds me of prior (only semi-resolved) discussions:
https://github.com/stellar/go/issues/1413
https://github.com/stellar/go/issues/909

**Comment by paulbellamy** [comment]
Ha, and @bartekn already had the same idea to store the migration in the table in https://github.com/stellar/go/issues/909#issuecomment-465993017
