### ISSUE TITLE
transactions endpoint returns 503 error

### ISSUE THREAD

**Issue by gutenye** [stellar/go#3732]
### What version are you using?

Public endpoint

### What did you do?

Open https://horizon.stellar.org/accounts/GAVYR7IQPRMJ3I3UFXFA4N3GINH56MSGUBZBVWSLWARB6YV3UQEL3VBU/transactions?cursor=154266373345464320&limit=2&order=asc

It returns

```
{
  "type": "https://stellar.org/horizon-errors/service_unavailable",
  "title": "Service Unavailable",
  "status": 503,
  "detail": "The request cannot be serviced at this time."
}
```

You can get the link from this reponse `_links.next.href` https://horizon.stellar.org/accounts/GAVYR7IQPRMJ3I3UFXFA4N3GINH56MSGUBZBVWSLWARB6YV3UQEL3VBU/transactions?limit=2

<img width="1186" alt="image" src="https://user-images.githubusercontent.com/377544/123960726-392cb680-d9e2-11eb-85cf-8409ca23ae02.png">

### What did you expect to see?

Returns 200 with tranactions

### What did you see instead?

Returns 503 Service Unavailable error

**Comment by bartekn** [comment]
I believe this is fixed now.

**Comment by gutenye** [comment]
@bartekn Thanks for the fix
