### ISSUE TITLE
stellar-archivist shows duplicated data when reading an archive file

### ISSUE THREAD

**Issue by Ronserruya** [stellar/go#374]
When using the "dumpxdr" command of stellar-archivist, it sometimes shows duplicated data in a place where it shouldn't be.

[results-006bc07f.txt](https://github.com/stellar/go/files/1845154/results-006bc07f.txt)
For example, working on the file: results-006bc07f.xdr, taken from S3:
history.stellar.org/prd/core-testnet/core_testnet_001/results/00/6b/c0/results-006bc07f

Some of the transaction ids are duplicated and are in the wrong ledgers.

The transaction hash `[93, 239, 45, 233, 97, 76, 223, 52, 226, 88, 7, 30, 244, 36, 148, 216, 53, 202, 46, 157, 111, 190, 191, 205, 135, 221, 119, 148, 248, 209, 78, 72]
Or , 5def2de9614cdf34e258071ef42494d835ca2e9d6fbebfcd87dd7794f8d14e48
`
Appears multiple times across many ledgers in the file, even though it should only be in ledge 7061569 (according to horizon)

**Comment by Ronserruya** [comment]
Wrote something small in python to read this file, and it confirmed that archivist did read the file wrong, this is the python file: 
[parseXDR.txt](https://github.com/stellar/go/files/2090524/parseXDR.txt)

and the results: 
[results.txt](https://github.com/stellar/go/files/2090529/results.txt)

You can see that the hash that was specified in the original issue only appears once and in the correct ledger.
I would just want to confirm that this is an actual bug with archivist and not some misunderstanding that I have on how these XDR files work

**Comment by bartekn** [comment]
Released [Archivist 0.2.0](https://github.com/stellar/go/releases/tag/stellar-archivist-v0.2.0) with a fix. Big thanks for @nebolsin for finding and fixing a bug!
