### ISSUE TITLE
services/horizon: result codes are incomplete for fee bump transactions

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/go#3748]
The response that comes back when fee bump transactions fails is vague because the response from Horizon doesn't include the result codes for the inner transaction.

For example:

```go
"result_codes":map[string]interface {}{"transaction":"tx_fee_bump_inner_failed"},
"result_xdr":"AAAAAAAAA4T////zecOBWim5RUgyAqeXn7WrULLG1b58e5KUxGBdK/7vzK8AAAAAAAAAAP////oAAAAAAAAAAA=="
```

If I decode the result_xdr I can see the result is more meaningful, but Horizon isn't including the full set of result codes in the output.

```
TransactionResult
  feeCharged: 900
  result: [txFeeBumpInnerFailed]
    innerResultPair
      transactionHash: ecOBWim5RUgyAqeXn7WrULLG1b58e5KUxGBdK/7vzK8=
      result
        feeCharged: 0
        result: [txBadAuth]
        ext: [undefined]
  ext: [undefined]
```

For clients who are parsing the JSON result codes it's not clear why the failure occurred, and I think we should include the inner transaction result codes in the result codes JSON field as well.

e.g., something like:
```go
"result_codes":map[string]interface {}{"transaction":"tx_fee_bump_inner_failed", "inner_transaction":"tx_bad_auth"},
```

**Comment by Shaptic** [comment]
js-stellar-sdk#621 seems related
