### ISSUE TITLE
Horizon: DB Runway: design DB benchmark

### ISSUE THREAD

**Issue by 2opremio** [stellar/go#3755]
- [x] Figure out if postgres has io metrics and table metrics. Are those useful for our benchmarking? pgbench?
- [x] Decide if we should include reingestion or not?
- [x] Find/Make a representative workload
- [x] Make a way to get a big representative DB
   - [ ] Copy from the last year - COPY INTO query?
   - [x] Reingestion might also be viable
   - [x] If we wanted random new data, could use Fuzzer

**Comment by paulbellamy** [comment]
# Should we include reingestion or not?

I think not, because:
- It is a constant-ish amount of data coming in (based on ledger size and rate).
- It is only processed on the write-only db node, so shouldn't affect query workloads.
- Since the incoming data will be quite small compared to the entire database size, replication load should be comparatively small.

**Comment by paulbellamy** [comment]
# Representative Workload & Benchmarking

First: Let's sample some logs from prod at different times of day, and feed them into [siege](https://github.com/JoeDog/siege).
  - simple, and quick to set up. Might be good enough.
  - siege lets us use a list of urls to hit, and mixes through them, so is a good fit for mixed workloads
  - To Measure: throughput/latency of requests. Distribution. DB load.
 

Next: If horizon turns out to be the bottleneck, we can log the db queries horizon is making, and feed them into pgbench.
 - Cuts out horizon, so it is more isolated to just the db load
 - Less realistic


Last: If we the response-time/load/etc distribution is not even, or we want to do more digging, add more in-depth postgres metrics to find bottlenecks.

**Comment by paulbellamy** [comment]
# Ingesting a big DB

Conveniently, the current db is 4TB (a power of 2), so we could double it and run tests each time to see how it scales.

To account for changing network usage, we *could* try to filter out more recent data, and clone that. But that seems like a pain, and wouldn't account for the network usage changing again in the future. The more recent data is bigger anyway, so if we clone all existing data, it should be more varied, while still being biased towards recent network usage.

## Options for Loading & Cloning Data

### Restore from backup?

- From talking with ops, the restore takes a few hours, but the db can take several days afterwards to become performant. Seems like that would make it difficult to trust benchmarks.
- Wouldn't help us get a db bigger than we have now.

### Reingest

- Reingest takes ~3 days, but performance is good right after.
- 3 days / 4TB = 18hr/TB, 64TB*18hr = 48 days, assuming linear. 🐌 

### Fuzzer

- Conceptually nice way to generate lots of new varied data.
- Data may not have bearing to real world usage.
- How could this be faster than reingest?
  - Injected these straight into the DB, but there's still a lot of network traffic to happen with that.
  - Send the txns in large COPY INTO batches, and use threading to pre-generate and buffer the batches going out.

### Data duplication/generation

- Basically, write a script which would duplicate data in the existing db, changing values as needed to not overlap
- Would need some input from the fuzzer, but only for key things (generating an asset, or account for example)
  - Ah ha, we could maybe use `generate_series` and `random` functions in postgres directly, instead.
- Could we minimize data transfer to/from the DB?
  - Work in big batches. From generating `history_trades_60000`, that inserts 1.8GB in ~10 minutes. So 175MB/minute = 64TB/7 years (oof), but most of that is doing the group aggregation. Benchmark this to see if we get better results for simpler copying. 🤞 
  - Only transfer new values where needed.
  - Minimize transactions.
- Seems promising. Needs benchmarking.

## Plan

Either Fuzzer or Data Duplication seem like the best approaches. Both approaches are similar, but data duplication/generation seems more likely to be performant and code-wise it will either be slightly simpler or totally awful (not sure yet). So, let's start with that. If it gets gnarly, we can try with the fuzzer, and hope the performance is not too much worse.

**Comment by 2opremio** [comment]
> First: Let's sample some logs from prod at different times of day, and feed them into [siege](https://github.com/JoeDog/siege).

@paulbellamy wouldn't it be simpler to use the load-balancer-logs functionality of horizon-cmp?

The nice part of it is that Horizon-cmp already knows how to read the ELB logs and transform them to requests (whilst I pressume we would need to do some massaging to the logs in order to use siege?)

**Comment by 2opremio** [comment]
In order to prioritize the data loading and know what tables we should be focusing on first, I have run a query to get the size of different tables (and the percentage of the total storage)

```sql
SELECT
   relname as "Table",
   pg_size_pretty(pg_total_relation_size(relid)) As "Size",
   pg_size_pretty(pg_total_relation_size(relid) - pg_relation_size(relid)) as "External Size",
   to_char
       (
        ((pg_total_relation_size(relid) * 100) /
         (SELECT SUM(pg_total_relation_size(relid)) FROM pg_catalog.pg_statio_user_tables))::float,
        'FM999999990.00'
       ) as "% of total Storage"
   FROM pg_catalog.pg_statio_user_tables ORDER BY pg_total_relation_size(relid) DESC;
```


Table                  |  Size   | External Size | % of total Storage
----------------------------------------|---------|---------------|------------
 history_transactions                   | 3466 GB | 775 GB        | 55.15
 history_operations                     | 1799 GB | 212 GB        | 28.62
 history_operation_participants         | 363 GB  | 203 GB        | 5.78
 history_effects                        | 326 GB  | 105 GB        | 5.19
 history_transaction_participants       | 262 GB  | 146 GB        | 4.18
 history_ledgers                        | 35 GB   | 9699 MB       | 0.56
 history_trades                         | 14 GB   | 9619 MB       | 0.22
 trust_lines                            | 4733 MB | 3522 MB       | 0.07
 accounts                               | 3306 MB | 2269 MB       | 0.05
 accounts_signers                       | 3062 MB | 2239 MB       | 0.05
 history_trades_60000                   | 2813 MB | 847 MB        | 0.04
 offers                                 | 2801 MB | 2716 MB       | 0.04
 history_accounts                       | 2312 MB | 1194 MB       | 0.04
 accounts_data                          | 22 MB   | 12 MB         | 0.00
 exp_asset_stats                        | 18 MB   | 6936 kB       | 0.00
 history_assets                         | 4064 kB | 2784 kB       | 0.00
 claimable_balances                     | 568 kB  | 392 kB        | 0.00
 history_claimable_balances             | 480 kB  | 272 kB        | 0.00
 history_transaction_claimable_balances | 312 kB  | 168 kB        | 0.00
 history_operation_claimable_balances   | 312 kB  | 168 kB        | 0.00
 key_value_store                        | 72 kB   | 56 kB         | 0.00
 gorp_migrations                        | 32 kB   | 24 kB         | 0.00


This tells us we should probably start to focus on ingesting data to the `history_transactions` and `history_operations` table, if we want be realistic with respect to the normal DB growth.

I have also run a similar query [approximating the the row count](https://stackoverflow.com/a/38684225/1914440) (and not the storage):

```sql
SELECT 
  relname,reltuples
FROM pg_class C
LEFT JOIN pg_namespace N ON (N.oid = C.relnamespace)
WHERE 
  nspname NOT IN ('pg_catalog', 'information_schema') AND
  relkind='r' 
ORDER BY reltuples DESC;
```


 relname                 |  reltuples  
----------------------------------------|-------------
 history_operation_participants         | 3.63757e+09
 history_operations                     |  3.1066e+09
 history_transaction_participants       | 2.76196e+09
 history_transactions                   | 1.55005e+09
 history_effects                        |  1.0516e+09
 history_ledgers                        | 3.60002e+07
 history_trades                         | 3.19023e+07
 history_trades_60000                   | 1.17729e+07
 history_accounts                       | 1.14724e+07
 accounts_signers                       | 5.67059e+06
 accounts                               | 5.47518e+06
 trust_lines                            | 3.53116e+06
 offers                                 |      163723
 accounts_data                          |       35637
 exp_asset_stats                        |       27183
 history_assets                         |        9149
 history_transaction_claimable_balances |        1907
 history_operation_claimable_balances   |        1907
 history_claimable_balances             |        1136
 claimable_balances                     |         338
 gorp_migrations                        |          48
 key_value_store                        |           4



From the row-count point of view we should focus on ` history_operation_participants`, ` history_operations`, ` history_transaction_participants `, `history_transactions` and `history_effects `

**Comment by paulbellamy** [comment]
> wouldn't it be simpler to use the load-balancer-logs functionality of horizon-cmp?
> 
> The nice part of it is that Horizon-cmp already knows how to read the ELB logs and transform them to requests (whilst I pressume we would need to do some massaging to the logs in order to use siege?)

Yes, but horizon-cmp (afaik) doesn't really do load-testing or measurement on the request timings, which is the part we want here.

**Comment by paulbellamy** [comment]
So for loading data, I had started with the `history_accounts` table (easy to generate fake data for to test stuff)

Generating some random values in postgres. (could do wherever tbh, but easy to use in functions for testing here)

```sql
  -- from https://dba.stackexchange.com/questions/22512/how-can-i-generate-a-random-bytea
  CREATE OR REPLACE FUNCTION random_bytea(bytea_length integer)
  RETURNS bytea AS $body$
      SELECT decode(string_agg(lpad(to_hex(width_bucket(random(), 0, 1, 256)-1),2,'0') ,''), 'hex')
      FROM generate_series(1, $1);
  $body$
  LANGUAGE 'sql'
  VOLATILE;

  -- generate a random hex string.
  CREATE OR REPLACE FUNCTION random_hex(length integer)
  RETURNS text AS $body$
      SELECT string_agg(lpad(to_hex(width_bucket(random(), 0, 1, 256)-1),2,'0'), '')
      FROM generate_series(1, $1/2);
  $body$
  LANGUAGE 'sql'
  VOLATILE;
  INSERT INTO history_accounts (address) (select random_base64(42) from generate_series(1,11521962*15));

  CREATE OR REPLACE FUNCTION random_base64(bytea_length integer)
  RETURNS text AS $body$
      SELECT encode(random_bytea(bytea_length), 'base64')
      FROM generate_series(1, $1);
  $body$
  LANGUAGE 'sql'
  VOLATILE;

  Create or replace function random_string(length integer)
  returns text as $$
  declare
    chars text[] := '{A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,2,3,4,5,6,7}';
    result text := '';
    i integer := 0;
  begin
    if length < 0 then
      raise exception 'Given length cannot be less than 0';
    end if;
    for i in 1..length loop
      result := result || chars[1+random()*(array_length(chars, 1)-1)];
    end loop;
    return result;
  end;
  $$ language plpgsql;
```

Will those generators be fast enough? Seems like yes (see below).

```sql
  -- 11,521,962 is select count(*) from history_accounts;
  select random_hex(56) from generate_series(1,11521962);
  -- Time: 69s = 5,760,981/s
  -- 11,521,962 accounts = 1,111MB, 1111MB / 69s = 16MB/s. oof..
  -- That's ok enough for this actually..
  -- so in 64TB (16x current), there should be 184,351,392 accounts
  -- 69s*15 = 1035s = 17.25 minutes
```

Ok, let's try inserting some new accounts...

```sql
  INSERT INTO history_accounts (address)
    -- length of addresses is 56 chars of base32
    (select random_string(56) from generate_series(1,11521962*15))
    -- Might be duplicates. we should check at the end that we have as many as
    -- expected and fill it in if needed until we have no duplicates.
    ON CONFLICT DO NOTHING;
  -- CPU seems pretty low while running this.. Are we depleting entropy? OSX entropy should be infinite. so... disk? Disk iops in the activity manager seem quite high. I suspect that's what we're hitting on my laptop.
  -- Time: ... long...
```

What if we used COPY? Is that faster?
```sql
  -- Write some random "addresses" to a csv file.
  COPY (select random_string(56) from generate_series(1,11521962*15)) TO STDOUT WITH CSV HEADER;
  -- Time: 28:25.38
  
  -- Then use this to read in that file with psql
  COPY history_accounts (address) FROM stdin with csv header;
  -- duplicate key?
  -- Time: ... long ...
  -- Ok, so this means it is actually the writing new accounts that takes time, not the random generation for sure.
```

Hypothesis: Postgres is writing to disk more frequently than it needs to. Can we turn down that frequency?

**Comment by paulbellamy** [comment]
How fast could we theoretically fill the disk? What is the iops/throughput limits on our rds instance of db.r5.8xlarge?

From [here](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.DBInstanceClass.html#Concepts.DBInstanceClass.Summary), [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-volume-types.html), and [here](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Storage.html#Concepts.Storage.GeneralSSD) between 250 MiB/S baseline to 4000MiB/S throughput, and 1,000–80,000 IOPS.

For our db instance we have 40,000 iops. 16 KiB max per I/O, so 640MiB/s throughput. (TODO: Check this)

With 250 megabits/second: `64 terrabytes / 250 megabits = 2,048,000 seconds = 23 days`
With 640 megabits/second: `64 terrabytes / 640 megabits = 800,000 seconds = 9 days`
With 4000 megabits/second: `64 terrabytes / 4000 megabits = 128,000 seconds = 35 hours`

So, depending on the aws disk setup, the theoretical fastest we could fill a 64TB disk is between 35 hours - 23 days.
