### ISSUE TITLE
Heartbeat in streaming

### ISSUE THREAD

**Issue by bartekn** [stellar/go#376]
Looks like many users are falling into an issue when connection is closed due to proxy/ELB idle timeout. One users in https://github.com/stellar/horizon/issues/424 suggested to send heartbeat every 15 seconds or so what is also recommended in EventSource RFC:
> Legacy proxy servers are known to, in certain cases, drop HTTP connections after a short timeout.
To protect against such proxy servers, authors can include a comment line
(one starting with a ':' character) every 15 seconds or so.

Are there any disadvantages other than sending a few more bytes every 15 seconds?

**Comment by oryband** [comment]
btw, we solved this issue by putting an nginx in front of horizon, which returns HTTP 200 after a certain amount of time. Thus, the client is forced to reconnect afterwards. It might not suit all needs, but it is an alternative solution to using heartbeats.

```nginx
server {
    # ...
    proxy_read_timeout 60;

    location / {
      proxy_pass http://localhost:8000;  # horizon

      # if the request is for sse, return 200 instead of 504
      #
      # we identify sse by looking for "text/event-stream" header
      if ($http_accept = "text/event-stream"){
        error_page 504 = @sse_response;
      }
    }

    location @sse_response {
      return 200;
    }
# ...
```
