### ISSUE TITLE
Horizon does not start correctly via Docker Compose in `standalone` mode.

### ISSUE THREAD

**Issue by Shaptic** [stellar/go#3775]
### What version are you using?
`master`

### What did you do?
Tried starting Horizon with Captive Core in a standalone setting via Docker Compose:

```bash
./start.sh standalone
```

### What did you expect to see?
A healthy running Horizon instance.

### What did you see instead?
A loop of ingestion errors having to do with a zeroed checkpoint ledger:

```bash
docker logs -f [...]
```

```txt
INFO[...] Starting horizon on :8000 (ingest: true)      pid=103980
INFO[...] Ingestion system initial state                current_state=start pid=103980 service=ingest
INFO[...] Ingestion system state machine transition     current_state=start next_state="buildFromCheckpoint(checkpointLedger=0)" pid=103980 service=ingest
ERRO[...] Error in ingestion state machine              current_state="buildFromCheckpoint(checkpointLedger=0)" error="unexpected checkpointLedger value" next_state=start pid=103980 service=ingest
INFO[...] Ingestion system state machine transition     current_state="buildFromCheckpoint(checkpointLedger=0)" next_state=start pid=103980 service=ingest
INFO[...] Ingestion system state machine transition     current_state=start next_state="buildFromCheckpoint(checkpointLedger=0)" pid=103980 service=ingest
ERRO[...] Error in ingestion state machine              current_state="buildFromCheckpoint(checkpointLedger=0)" error="unexpected checkpointLedger value" next_state=start pid=103980 service=ingest
```

**Comment by bartekn** [comment]
It looks like it's been broken forever. The `core-start.sh` file contains:
```bash
if [ "$1" = "standalone" ]; then
  # initialize history archive for standalone network
  stellar-core new-hist vs

  # serve history archives to horizon on port 1570
  pushd /history/vs/
  python3 -m http.server 1570 &
  popd
fi
```
So it makes Stellar-Core init history archive at ledger 0 (by calling `stellar-core new-hist vs`). In such case Horizon will wait in the `unexpected checkpointLedger value` loop until the first checkpoint is published. To fix this in `stellar/quickstart` we use [`horizon ingest init-genesis-state`](https://github.com/stellar/docker-stellar-core-horizon/blob/a631264084f02012a3d0b1957aeb87246d1648d5/start#L311) command to init state at ledger 1 (contains a single root account) so it can start ingestion without waiting for the first checkpoint. I think we need to do this here too.

**Comment by Shaptic** [comment]
I can confirm that `init-genesis-state` resolves this problem in a local run; thank you @bartekn! Unfortunately, we'll need to do something a little more elaborate to integrate this into the Docker Compose flow because this needs to be run prior to serving Horizon, but our current Dockerfile makes this hard.

**Comment by tamirms** [comment]
@Shaptic this is expected behavior because horizon will only start ingesting after the first history archive published. Although it initially appears that horizon is looping with ingestion errors, once the first checkpoint is published horizon will start ingesting successfully

**Comment by bartekn** [comment]
This seems to be solved. Please reopen if needed.
