### ISSUE TITLE
Update horiozn version error

### ISSUE THREAD

**Issue by shenhao217** [stellar/go#3781]
Hello,
2021/07/25 19:33:25 There are 1 migrations to apply in the "up" direction.
2021/07/25 19:33:25 The necessary migrations are: [48_rebuild_trade_aggregations.sql]
2021/07/25 19:33:25 A database migration is required to run this version (2.6.1-71350e687eaf44ae5badfabb545b8e754529c2d3) of Horizon. Run "horizon db migrate up" to update your DB. Consult the Changelog (https://github.com/stellar/go/blob/master/services/horizon/CHANGELOG.md) for more information.
After seeing this error, I executed this code horizon db migrate up
error log:
2021/07/25 19:30:41 Unable to create migration plan because of 43_add_claimable_balances_flags.sql: unknown migration in database

**Comment by bartekn** [comment]
Looking at timestamps I think you run `horizon db migrate up` using some old Horizon version. Please upgrade to the latest and try again. Closing now, I'll reopen if problem is happening again.

**Comment by shenhao217** [comment]
Thank you very much for your help, my problem has been solved, I wish you a happy life
