### ISSUE TITLE
Ingest liquidity pool operations

### ISSUE THREAD

**Issue by tamirms** [stellar/go#3808]
[CAP38](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0038.md) introduces two new operations which act on liquidity pools. There is the deposit operation which allows an account to deposit reserve assets into a liquidity pool in exchange for pool shares. And there is the withdrawal operation which allows an account to claim reserve assets for the underlying pool shares.

Also, the change trust operation will be extended to allow the creation, modification, and deletion of pool share trust lines. 

Below you can find the JSON definition for the withdrawal and deposit operation objects.

Deposit Liquidity Operation JSON
```
{
  "id": "3697472920621057",
  "paging_token": "3697472920621057",
  "transaction_successful": true,
  "source_account": "GBB4JST32UWKOLGYYSCEYBHBCOFL2TGBHDVOMZP462ET4ZRD4ULA7S2L",
  "type": "liquidity_pool_deposit",
  "type_i": 22,
  "created_at": "2021-11-18T03:47:47Z",
  "transaction_hash": "43ed5ce19190822ec080b67c3ccbab36a56bc34102b1a21d3ee690ed3bc23378",
  "liquidity_pool_id": "abcdef",
  "reserves": [
    {
      "asset": "JPY:GBVAOIACNSB7OVUXJYC5UE2D4YK2F7A24T7EE5YOMN4CE6GCHUTOUQXM",
      "max_deposit_amount": "1000.0000005"
    },
    {
      "asset": "EURT:GAP5LETOV6YIE62YAM56STDANPRDO7ZFDBGSNHJQIYGGKSMOZAHOOS2S",
      "max_deposit_amount": "3000.0000005"
    }
  ],
  "min_price": "0.2680000",
  "min_price_r": {
    "n": 67,
    "d": 250
  },
  "max_price": "0.3680000",
  "max_price_r": {
    "n": 73,
    "d": 250
  },
  "reserves_deposited": [
    {
      "asset": "JPY:GBVAOIACNSB7OVUXJYC5UE2D4YK2F7A24T7EE5YOMN4CE6GCHUTOUQXM",
      "amount": "983.0000005"
    },
    {
      "asset": "EURT:GAP5LETOV6YIE62YAM56STDANPRDO7ZFDBGSNHJQIYGGKSMOZAHOOS2S",
      "amount": "2378.0000005"
    }
  ],
  "shares_received": "1000"
}
```

Withdraw Liquidity Operation JSON
```
{
  "id": "3697472920621057",
  "paging_token": "3697472920621057",
  "transaction_successful": true,
  "source_account": "GBB4JST32UWKOLGYYSCEYBHBCOFL2TGBHDVOMZP462ET4ZRD4ULA7S2L",
  "type": "liquidity_pool_withdraw",
  "type_i": 23,
  "created_at": "2021-11-18T03:47:47Z",
  "transaction_hash": "43ed5ce19190822ec080b67c3ccbab36a56bc34102b1a21d3ee690ed3bc23378",
  "liquidity_pool_id": "abcdef",
  "reserves": [
    {
      "asset": "JPY:GBVAOIACNSB7OVUXJYC5UE2D4YK2F7A24T7EE5YOMN4CE6GCHUTOUQXM",
      "min_amount": "1000.0000005"
    },
    {
      "asset": "EURT:GAP5LETOV6YIE62YAM56STDANPRDO7ZFDBGSNHJQIYGGKSMOZAHOOS2S",
      "min_amount": "3000.0000005"
    }
  ],
  "shares": "200",
  "reserves_received": [
    {
      "asset": "JPY:GBVAOIACNSB7OVUXJYC5UE2D4YK2F7A24T7EE5YOMN4CE6GCHUTOUQXM",
      "amount": "993.0000005"
    },
    {
      "asset": "EURT:GAP5LETOV6YIE62YAM56STDANPRDO7ZFDBGSNHJQIYGGKSMOZAHOOS2S",
      "amount": "2478.0000005"
    }
  ]
}
```

Here's how the change trust operation will look like when performed against a pool share trustline:
```
{
  "id": "157639717969326081",
  "paging_token": "157639717969326081",
  "transaction_successful": true,
  "source_account": "GBBWI7TEVQBPEUXKYNGI3GBAH7EHFEREONKK3UK56ZSLJIDIYHQJCVSG",
  "type": "change_trust",
  "type_i": 6,
  "created_at": "2021-08-04T20:01:24Z",
  "transaction_hash": "941f2fa2101d1265696a3c7d35e7688cd210324114e96b64a386ab55f65e488f",
  "asset_type": "liquidity_pool_shares",
  "liquidity_pool_id": "abcdef",
  "limit": "1000",
  "trustor": "GBBWI7TEVQBPEUXKYNGI3GBAH7EHFEREONKK3UK56ZSLJIDIYHQJCVSG"
}
```

Tasks:

- [x] Update operations ingestion processor to support new deposit and withdraw liquidity operations
- [x] Update operations ingestion processor to support change trust operation on pool shares
- [x] Allow lookup of transactions and operations by pool id (this will require something like ClaimableBalancesTransactionProcessor but for liquidity pools)
- [ ] Add a [fuzzing](https://github.com/stellar/go/blob/master/services/horizon/internal/ingest/processors/offers_processor_test.go#L22-L54) test if possible

**Comment by 2opremio** [comment]
@tamirms I think `"min_amount"` should be renamed to `"min_withdraw_amount"` to make it consistent with `"max_deposit_amount"`. Thoughts?

**Comment by 2opremio** [comment]
In fact, I would probably do:

```
  "reserves_min": [
    {
      "asset": "JPY:GBVAOIACNSB7OVUXJYC5UE2D4YK2F7A24T7EE5YOMN4CE6GCHUTOUQXM",
      "amount": "1000.0000005"
    },
    {
      "asset": "EURT:GAP5LETOV6YIE62YAM56STDANPRDO7ZFDBGSNHJQIYGGKSMOZAHOOS2S",
      "amount": "3000.0000005"
    }
  ],
  ```
  
  instead of
  
  ```
    "reserves": [
    {
      "asset": "JPY:GBVAOIACNSB7OVUXJYC5UE2D4YK2F7A24T7EE5YOMN4CE6GCHUTOUQXM",
      "min_amount": "1000.0000005"
    },
    {
      "asset": "EURT:GAP5LETOV6YIE62YAM56STDANPRDO7ZFDBGSNHJQIYGGKSMOZAHOOS2S",
      "min_amount": "3000.0000005"
    }
  ],
  ```
  
  and 
  
    ```
    "reserves_max": [
    {
      "asset": "JPY:GBVAOIACNSB7OVUXJYC5UE2D4YK2F7A24T7EE5YOMN4CE6GCHUTOUQXM",
      "amount": "1000.0000005"
    },
    {
      "asset": "EURT:GAP5LETOV6YIE62YAM56STDANPRDO7ZFDBGSNHJQIYGGKSMOZAHOOS2S",
      "amount": "3000.0000005"
    }
  ],
  ```
  
  instead of
  
  ```
    "reserves": [
    {
      "asset": "JPY:GBVAOIACNSB7OVUXJYC5UE2D4YK2F7A24T7EE5YOMN4CE6GCHUTOUQXM",
      "max_deposit_amount": "1000.0000005"
    },
    {
      "asset": "EURT:GAP5LETOV6YIE62YAM56STDANPRDO7ZFDBGSNHJQIYGGKSMOZAHOOS2S",
      "max_deposit_amount": "3000.0000005"
    }
  ],
  ```
 
 
This change:
1. removes redundancy (`min_` and `max_` prefixes)
2. it simplifies the types used by the SDK (at least in Go, which uses struct tags for json marshalling)

**Comment by tamirms** [comment]
@2opremio sounds good to me. do you have any objections to this API change @marcelosalloum @paulbellamy ?

**Comment by 2opremio** [comment]
@tamirms regarding:

>  Allow lookup of transactions and operations by pool id (this will require something like ClaimableBalancesTransactionProcessor but for liquidity pools)

Is querying by transaction and operation part of the MVP? I think it will spare us a day or two

**Comment by tamirms** [comment]
>Is querying by transaction and operation part of the MVP? I think it will spare us a day or two

we will need to implement the db tables and ingestion for the querying in the MVP because otherwise it will require us to reingest history which is going to be burdensome on horizon operators

**Comment by 2opremio** [comment]
ok, will do

**Comment by marcelosalloum** [comment]
The changes to `reserves_max` and `reserves_min` LGTM!
