### ISSUE TITLE
Ingest liquidity pool effects

### ISSUE THREAD

**Issue by tamirms** [stellar/go#3809]
Horizon will need to add several new effects to support [CAP38](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0038.md) liquidity pools:

Below you can find the JSON definitions for the new liquidity pool effects:

Deposit Liquidity Effect
```
{
  "id": "0000000012884905986-0000000002",
  "paging_token": "12884905986-2",
  "account": "GAAZI4TCR3TY5OJHCTJC2A4QSY6CJWJH5IAJTGKIN2ER7LBNVKOCCWN7",
  "type": "liquidity_pool_deposited",
  "type_i": 81,
  "created_at": "2021-11-18T03:15:54Z",
  "liquidity_pool": {
    "id": "abcdef",
    "fee_bp": 30,
    "type": "constant_product",
    "total_trustlines": "300",
    "total_shares": "5000",
    "reserves": [
      {
        "balance": "1000.0000005",
        "asset": "EURT:GAP5LETOV6YIE62YAM56STDANPRDO7ZFDBGSNHJQIYGGKSMOZAHOOS2S"
      },
      {
        "balance": "2000.0000000",
        "asset": "PHP:GBUQWP3BOUZX34TOND2QV7QQ7K7VJTG6VSE7WMLBTMDJLLAW7YKGU6EP"
      }
    ]
  },
  "reserves_deposited": [
    {
      "asset": "JPY:GBVAOIACNSB7OVUXJYC5UE2D4YK2F7A24T7EE5YOMN4CE6GCHUTOUQXM",
      "amount": "983.0000005"
    },
    {
      "asset": "EURT:GAP5LETOV6YIE62YAM56STDANPRDO7ZFDBGSNHJQIYGGKSMOZAHOOS2S",
      "amount": "2378.0000005"
    }
  ],
  "shares_received": "1000"
}
```

Withdraw Liquidity Effect
```
{
  "id": "0000000012884905986-0000000002",
  "paging_token": "12884905986-2",
  "account": "GAAZI4TCR3TY5OJHCTJC2A4QSY6CJWJH5IAJTGKIN2ER7LBNVKOCCWN7",
  "type": "liquidity_pool_withdrew",
  "type_i": 82,
  "created_at": "2021-11-18T03:15:54Z",
  "liquidity_pool": {
    "id": "abcdef",
    "fee_bp": 30,
    "type": "constant_product",
    "total_trustlines": "299",
    "total_shares": "4000",
    "reserves": [
      {
        "balance": "7.0000005",
        "asset": "EURT:GAP5LETOV6YIE62YAM56STDANPRDO7ZFDBGSNHJQIYGGKSMOZAHOOS2S"
      },
      {
        "balance": "1.0000000",
        "asset": "PHP:GBUQWP3BOUZX34TOND2QV7QQ7K7VJTG6VSE7WMLBTMDJLLAW7YKGU6EP"
      }
    ]
  },
  "reserves_received": [
    {
      "asset": "JPY:GBVAOIACNSB7OVUXJYC5UE2D4YK2F7A24T7EE5YOMN4CE6GCHUTOUQXM",
      "amount": "993.0000005"
    },
    {
      "asset": "EURT:GAP5LETOV6YIE62YAM56STDANPRDO7ZFDBGSNHJQIYGGKSMOZAHOOS2S",
      "amount": "2478.0000005"
    }
  ],
  "shares_redeemed": "1000"
}
```

Liquidity Pool Trade Effect
```
{
  "id": "0000000012884905986-0000000002",
  "paging_token": "12884905986-2",
  "account": "GAAZI4TCR3TY5OJHCTJC2A4QSY6CJWJH5IAJTGKIN2ER7LBNVKOCCWN7",
  "type": "liquidity_pool_trade",
  "type_i": 83,
  "created_at": "2021-11-18T03:15:54Z",
  "liquidity_pool": {
    "id": "abcdef",
    "fee_bp": 30,
    "type": "constant_product",
    "total_trustlines": "300",
    "total_shares": "5000",
    "reserves": [
      {
        "balance": "1000.0000005",
        "asset": "EURT:GAP5LETOV6YIE62YAM56STDANPRDO7ZFDBGSNHJQIYGGKSMOZAHOOS2S"
      },
      {
        "balance": "2000.0000000",
        "asset": "PHP:GBUQWP3BOUZX34TOND2QV7QQ7K7VJTG6VSE7WMLBTMDJLLAW7YKGU6EP"
      }
    ]
  },
  "sold": {
    "asset": "JPY:GBVAOIACNSB7OVUXJYC5UE2D4YK2F7A24T7EE5YOMN4CE6GCHUTOUQXM",
    "amount": "983.0000005"
  },
  "bought": {
    "asset": "EURT:GAP5LETOV6YIE62YAM56STDANPRDO7ZFDBGSNHJQIYGGKSMOZAHOOS2S",
    "amount": "2378.0000005"
  }
}
```

Liquidity Pool Created Effect
```
{
  "id": "0000000012884905986-0000000002",
  "paging_token": "12884905986-2",
  "account": "GAAZI4TCR3TY5OJHCTJC2A4QSY6CJWJH5IAJTGKIN2ER7LBNVKOCCWN7",
  "type": "liquidity_pool_created",
  "type_i": 84,
  "created_at": "2021-11-18T03:15:54Z",
  "liquidity_pool": {
    "id": "abcdef",
    "fee_bp": 30,
    "type": "constant_product",
    "total_trustlines": "1",
    "total_shares": "0",
    "reserves": [
      {
        "balance": "0",
        "asset": "EURT:GAP5LETOV6YIE62YAM56STDANPRDO7ZFDBGSNHJQIYGGKSMOZAHOOS2S"
      },
      {
        "balance": "0",
        "asset": "PHP:GBUQWP3BOUZX34TOND2QV7QQ7K7VJTG6VSE7WMLBTMDJLLAW7YKGU6EP"
      }
    ]
  }
}
```

Liquidity Pool Removed Effect
```
{
  "id": "0000000012884905986-0000000002",
  "paging_token": "12884905986-2",
  "account": "GAAZI4TCR3TY5OJHCTJC2A4QSY6CJWJH5IAJTGKIN2ER7LBNVKOCCWN7",
  "type": "liquidity_pool_removed",
  "type_i": 85,
  "created_at": "2021-11-18T03:15:54Z",
  "liquidity_pool_id": “abcdef”
}
```

Liquidity [Revoked](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0038.md#settrustlineflagsop-and-allowtrustop)
```
{
  "id": "0000000012884905986-0000000002",
  "paging_token": "12884905986-2",
  "account": "GAAZI4TCR3TY5OJHCTJC2A4QSY6CJWJH5IAJTGKIN2ER7LBNVKOCCWN7",
  "type": "liquidity_pool_revoked",
  "type_i": 86,
  "created_at": "2021-11-18T03:15:54Z",
  "liquidity_pool": {
    "id": "abcdef",
    "fee_bp": 30,
    "type": "constant_product",
    "total_trustlines": "299",
    "total_shares": "4000",
    "reserves": [
      {
        "balance": "7.0000005",
        "asset": "EURT:GAP5LETOV6YIE62YAM56STDANPRDO7ZFDBGSNHJQIYGGKSMOZAHOOS2S"
      },
      {
        "balance": "1.0000000",
        "asset": "PHP:GBUQWP3BOUZX34TOND2QV7QQ7K7VJTG6VSE7WMLBTMDJLLAW7YKGU6EP"
      }
    ]
  },
  "reserves_revoked": [
    {
      "asset": "JPY:GBVAOIACNSB7OVUXJYC5UE2D4YK2F7A24T7EE5YOMN4CE6GCHUTOUQXM",
      "amount": "993.0000005",
      "claimable_balance_id": "cbid1235"
    },
    {
      "asset": "EURT:GAP5LETOV6YIE62YAM56STDANPRDO7ZFDBGSNHJQIYGGKSMOZAHOOS2S",
      "amount": "2478.0000005",
      "claimable_balance_id": "idcbd1234"
    }
  ],
  "shares_revoked": "1000"
}
```

Note that a liquidity pool ledger entry is created when the first trustline for a liquidity pool is created. The ledger entry is removed when the last trustline for a liquidity pool is removed.

Some of the existing trustline effects will need to be updated to support effects on pool shares:

Trustline Created Effect
```
{
  "id": "0157639717969326081-0000000001",
  "paging_token": "157639717969326081-1",
  "account": "GBBWI7TEVQBPEUXKYNGI3GBAH7EHFEREONKK3UK56ZSLJIDIYHQJCVSG",
  "type": "trustline_created",
  "type_i": 20,
  "created_at": "2021-08-04T20:01:24Z",
  "asset_type": "liquidity_pool_shares",
  "liquidity_pool_id": "abcdef",
  "limit": "1000"
}
```

Trustline Updated Effect
```
{
  "id": "0157639717969326081-0000000001",
  "paging_token": "157639717969326081-1",
  "account": "GBBWI7TEVQBPEUXKYNGI3GBAH7EHFEREONKK3UK56ZSLJIDIYHQJCVSG",
  "type": "trustline_updated",
  "type_i": 22,
  "created_at": "2021-08-04T20:01:24Z",
  "asset_type": "liquidity_pool_shares",
  "liquidity_pool_id": "abcdef",
  "limit": "2000"
}
```

Trustline Removed Effect
```
{
  "id": "0157639717969326081-0000000001",
  "paging_token": "157639717969326081-1",
  "account": "GBBWI7TEVQBPEUXKYNGI3GBAH7EHFEREONKK3UK56ZSLJIDIYHQJCVSG",
  "type": "trustline_removed",
  "type_i": 21,
  "created_at": "2021-08-04T20:01:24Z",
  "asset_type": "liquidity_pool_shares",
  "liquidity_pool_id": "abcdef",
  "limit": "0.0000000"
}
```

Tasks:

- [x] Update effects processor to support new liquidity pool effects
- [x] Update effects processor to support trustline created / updated / remove effects on pool share trustlines
- [x] Update effects processor to support trustline sponsorship created / updated / remove effects on pool share trustlines
- [x] Allow lookup of effects by pool id  (this part will depend on https://github.com/stellar/go/issues/3808  because it will use the same mechanism to lookup operations by pool id)
- [ ] Add a [fuzzing](https://github.com/stellar/go/blob/master/services/horizon/internal/ingest/processors/offers_processor_test.go#L22-L54) test if possible

**Comment by 2opremio** [comment]
> (this part will depend on Ingest liquidity pool operations #3808 because it will use the same mechanism to lookup operations by pool id)

@tamirms did you have a specific solution in mind? I was considering to add a (`NULLable`) poolid column (and index) to the effects table.

Did you envision joining the `history_operation_liquidity_pool` and `history_effects` tables by the `history_operation_id` column? I think that would also work, but it would require an extra join with the `history_liquidity_pools` table.

**Comment by tamirms** [comment]
>Did you envision joining the history_operation_liquidity_pool and history_effects tables by the history_operation_id column? I think that would also work, but it would require an extra join with the history_liquidity_pools table.

This is what I had in mind. But, adding the extra column should work as well

**Comment by 2opremio** [comment]
@tamirms is there a good reason to use `"balance"` keys instead of `"amount"`? 

i.e.

```
    "reserves": [
      {
        "balance": "1000.0000005",
        "asset": "EURT:GAP5LETOV6YIE62YAM56STDANPRDO7ZFDBGSNHJQIYGGKSMOZAHOOS2S"
      },
      {
        "balance": "2000.0000000",
        "asset": "PHP:GBUQWP3BOUZX34TOND2QV7QQ7K7VJTG6VSE7WMLBTMDJLLAW7YKGU6EP"
      }
    ]
```

```
    "reserves": [
      {
        "amount: "1000.0000005",
        "asset": "EURT:GAP5LETOV6YIE62YAM56STDANPRDO7ZFDBGSNHJQIYGGKSMOZAHOOS2S"
      },
      {
        "amount": "2000.0000000",
        "asset": "PHP:GBUQWP3BOUZX34TOND2QV7QQ7K7VJTG6VSE7WMLBTMDJLLAW7YKGU6EP"
      }
    ]
```

For uniformity (with `reserves_deposited` and `reserves_received`) I think it would be better to stick to `"amount"`.

**Comment by 2opremio** [comment]
@tamirms Also, since trading happens transparently for liquidity pools I am not sure when/how to emit the _Liquidity Pool Trade Effect_. What did you have in mind?

**Comment by tamirms** [comment]
@2opremio changing "balance" to "amount" sounds good to me.

regarding the liquidity pool trade effect, `xdr.ClaimAtom` was extended to include a special type for liquidity pool trades. whenever you see an operation on a `xdr.ClaimAtom` in effects_processor.go you will need to update the code to check for the case where the claim atom is of type `ClaimAtomTypeClaimAtomTypeLiquidityPool`

**Comment by 2opremio** [comment]
@tamirms shouldn't the`EffectTrustlineSponsorship*` effects also be updated to include liquidity pool trustlines?

**Comment by 2opremio** [comment]
We could reuse the `"asset"` key, but then we would need to come up with a way to represent liquidity pool assets in that context (e.g. `"liquidity_pool:<pool_id>"`) like @marcelosalloum suggested offline.

**Comment by tamirms** [comment]
> shouldn't theEffectTrustlineSponsorship* effects also be updated to include liquidity pool trustlines?

yeah, I think you're right. I forgot about those effects

**Comment by 2opremio** [comment]
@tamirms should we encode the liquidity pool asset in the asset field or add another key for it it?

i.e. Should we keep the trustline sponsorship effects as is, but encoding the liquidity_pool in the asset e.g.

```
{
  "id": "0000000012884905986-0000000002",
  "paging_token": "12884905986-2",
  "account": "GAAZI4TCR3TY5OJHCTJC2A4QSY6CJWJH5IAJTGKIN2ER7LBNVKOCCWN7",
  "type": "trustline_sponsorship_created",
  "type_i": 60,
  "created_at": "2021-11-18T03:15:54Z",
  "asset": “liquidity_pool:abcdef”,
  "sponsor": "GBVAOIACNSB7OVUXJYC5UE2D4YK2F7A24T7EE5YOMN4CE6GCHUTOUQXM"
}
```

or, should we make the `"asset"` field omitable and use a new `liquidity_pool_id` field instead?


```
{
  "id": "0000000012884905986-0000000002",
  "paging_token": "12884905986-2",
  "account": "GAAZI4TCR3TY5OJHCTJC2A4QSY6CJWJH5IAJTGKIN2ER7LBNVKOCCWN7",
  "type": "trustline_sponsorship_created",
  "type_i": 60,
  "created_at": "2021-11-18T03:15:54Z",
  “liquidity_pool_id": "abcdef”,
  "sponsor": "GBVAOIACNSB7OVUXJYC5UE2D4YK2F7A24T7EE5YOMN4CE6GCHUTOUQXM"
}
```

I think I would go for the second option

**Comment by 2opremio** [comment]
@tamirms another question. How come there are `PoolCreated` and `PoolRemoved` effects but ther is no`PoolUpdated` counterpart? Is it because that is covered by `Deposit`, `Withdrawn` and `LIquidityTrade` effects?

**Comment by tamirms** [comment]
@2opremio I prefer the second option as well. Perhaps we can add an asset_type field to the effects so we can distinguish between the liquidity pool trustline effects and the normal asset trustline effects

> How come there are PoolCreated and PoolRemoved effects but ther is noPoolUpdated counterpart? Is it because that is covered by Deposit, Withdrawn and LiquidityTrade effects?

That is correct the only way the pool can be modified is through deposit, withdrawal, trade, or changetrust effects.
