### ISSUE TITLE
SSE should start streaming when no operations for account in recent catchup

### ISSUE THREAD

**Issue by bartekn** [stellar/go#381]
While I was testing https://github.com/stellar/go/pull/379 I found strange behaviour which looks like a bug to me. I'm running core in `CATCHUP_RECENT` mode. When I try to stream operations for an account that does exist but has no operations in the set of ingested ledgers I receive `err` event.

```
curl -v -H "Accept: text/event-stream" "http://localhost:8000/accounts/GDKIJJIKXLOM2NRMPNQZUUYK24ZPVFC6426GZAEP3KUK6KEJLACCWNMX/operations?cursor=now"
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8000 (#0)
> GET /accounts/GDKIJJIKXLOM2NRMPNQZUUYK24ZPVFC6426GZAEP3KUK6KEJLACCWNMX/operations?cursor=now HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.54.0
> Accept: text/event-stream
> 
< HTTP/1.1 200 OK
< Access-Control-Allow-Origin: *
< Cache-Control: no-cache
< Connection: keep-alive
< Content-Type: text/event-stream; charset=utf-8
< Vary: Origin
< X-Ratelimit-Limit: 3600
< X-Ratelimit-Remaining: 3568
< X-Ratelimit-Reset: 3096
< Date: Wed, 28 Mar 2018 11:36:44 GMT
< Transfer-Encoding: chunked
< 
retry: 1000
event: open
data: "hello"

event: err
data: sql: no rows in result set

* Connection #0 to host localhost left intact
```

I think that horizon should simply start streaming, waiting for new operations.

Another issue (maybe minor) is that we send low level error (`sql: no rows in result set`). Instead, we should create a set of common errors that can occur while streaming (+ one general error, like `unexpected error`) and send these errors to the end user.

**Comment by tamirms** [comment]
It looks like the current behavior of horizon is correct. If you attempt to stream operations for an account which does not exist, the endpoint responds with a 404. If you attempt to stream operations for an account which exists but has no operations, the stream is kept open until the connection timeout and then the stream closes
