### ISSUE TITLE
Ingest liquidity pool trades

### ISSUE THREAD

**Issue by tamirms** [stellar/go#3810]
Horizon already has a database table which stores all trades occurring on the Stellar DEX. We will need to also include trades occurring on liquidity pools.

AMM trades differ from orderbook trades in the following ways:

- The price fraction will represent its numerator and denominator as 64 bit integers.
- AMM trades do not refer to offer ids (e.g. base_offer_id or counter_offer_id)
- Only one side of the trade will be executed by an account (either base_account or counter_account). The other side of the trade will be executed against a liquidity pool (either base_pool_id or counter_pool_id).

Here is an example response of an AMM trade:
```
{
  "id": "157235845014249474-0",
  "paging_token": "157235845014249474-0",
  "ledger_close_time": "2021-07-29T21:10:53Z",
  "trade_type": "liquidity_pool",
  "base_liquidity_pool_id": "abcdef",
  "liquidity_pool_fee_bp": 30,
  "base_amount": "0.0002007",
  "base_asset_type": "native",
  "counter_account": "GDW634JZX3VMEF2RZTCJTT34RITIMNX46QOGTYHCJEJL3MM7BLOQ6HOW",
  "counter_amount": "0.0022300",
  "counter_asset_type": "credit_alphanum4",
  "counter_asset_code": "VZT",
  "counter_asset_issuer": "GBENYXZDFFR2J4F4DB3YPBBAM244TXYOTIOOUQI5DBT3OKUU4ZJ2M7NO",
  "base_is_seller": false,
  "price": {
    "n": “10000000”,
    "d": “899997”
  }
}
```

Tasks:

- [x]  Update trades table to support storing AMM trades
- [ ]  Allow queries to find all trades for a given pool id
- [ ] Allow queries to find all trades by trade_type
- [x] Update trades processor to ingest AMM trades
- [ ] Add a [fuzzing](https://github.com/stellar/go/blob/master/services/horizon/internal/ingest/processors/offers_processor_test.go#L22-L54) test if possible
- [x] Make sure that any changes to the trades schema will not break trade aggregations

**Comment by bartekn** [comment]
There are also some skipped tests. Probably part of #3812.

**Comment by tamirms** [comment]
all those tasks will be implemented in https://github.com/stellar/go/issues/3835
