### ISSUE TITLE
Remove skipped tests after AMM ingestion is complete

### ISSUE THREAD

**Issue by tamirms** [stellar/go#3812]
In https://github.com/stellar/go/pull/3811 , I skipped a bunch of tests because they could only pass after AMM ingestion was implemented.

This issue is a reminder that we should make sure to fix all these TODOS:

```golang
	// TODO remove skip after amm ingestion is complete
	t.Skip()
```

**Comment by bartekn** [comment]
I fixed many skipped tests in #3868 but there are still some.

**Comment by 2opremio** [comment]
@bartekn which ones are left? I can't find them

**Comment by bartekn** [comment]
I searched for `.Skip()` and there are some in `actions_trade_test.go` and `trade_test.go`.
