### ISSUE TITLE
Liquidity Pool SDK Updates

### ISSUE THREAD

**Issue by paulbellamy** [stellar/go#3813]
- [x] Go SDK
- [x] JS SDK
- [ ] #3894
- [x] notify community SDKs

**Comment by tamirms** [comment]
The SDKs should have a helper function to compute a pool id. The pool id is derived by taking a sha256 hash of `LiquidityPoolParameters` which is defined in the [CAP-38 xdr](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0038.md#xdr-changes).

Most of the time applications will already have the pool id from the horizon responses. However, you do need to derive the pool id when you are creating a new pool and depositing into it within a single transaction.

BTW, creating a pool happens as a side effect of the `ChangeTrustOp` operation. The liquidity pool ledger entry is created automatically after the first trustline is created. Creating and depositing to a pool within a single transaction requires two operations.

The first operation will be a `ChangeTrustOp` operation which establishes the trustline and thereby creates the pool. The second operation is `LiquidityPoolDepositOp`. `LiquidityPoolDepositOp` takes a pool id parameter and that is why we need to have a function to derive the pool id.

**Comment by tamirms** [comment]
from @orbitlens 

>I think it worth adding the note in the docs that clients should always provide the slippage settings (or at least leave some room for the slippage if they don't plan to introduce such interface, e.g. 0.1% slippage by default).

>Otherwise, if the client explicitly sets "min_amount" for both assets based on the current pool state, it will result in multiple failed transactions while withdrawing funds from highly volatile pools. And of course, a terrible UX.

Maybe we could provide some wrappers on the deposit / liquidity operations in the SDK which allow you to configure the min_amount / min_price bounds based on a slippage percentage?

**Comment by paulbellamy** [comment]
Broke the java sdk out from this into a separate issue to track it independently.
