### ISSUE TITLE
Error 504 When high TPS for long time

### ISSUE THREAD

**Issue by bartekn** [stellar/go#382]
Moving from https://github.com/stellar/js-stellar-sdk/issues/150:

---
Currently, the Testnet Horizon has `X-Ratelimit-Limit: 17200`, so it should be ok to try with { 50TPS & 60seconds } (just 3000 requests).  

100% transactions suceeded with { 50TPS & **5second** }. But for longer periods (e.g. 60sec, 600sec), most of the transactions failed with the following error: 

```
Error: timeout of 60000ms exceeded

BadResponseError: Transaction submission failed. Server responded: 504 Gateway Timeout
```

[Seems the error code initiates here](https://github.com/stellar/js-stellar-sdk/blob/492d86fe2017df69d7f4d1336d7c575f816b1e99/src/server.js#L70). 

>  Ubuntu 16.04, 64bit
> Node v7 / v9 (both encountering same problem)
> 8GB RAM, 8core

p.s. 
All transactions are the same, i.e. Amy sends Bob 0.03 XLM. 

p.s. 
Several hundreds of accounts have been set up as [channels](https://www.stellar.org/developers/guides/channels.html), and simple load balancing was done to distribute transactions to the channels evenly. Bad_sequence error should be largely reduced.

**Comment by sohanlaxmicoin** [comment]
any fix ?

**Comment by munawarb** [comment]
I'm getting the same issue. Firing rapid transactions for long periods of time eventually errors out as a 504 error.

**Comment by bartekn** [comment]
Duplicate #305.
