### ISSUE TITLE
Include liquidity pool effects in the effects endpoint

### ISSUE THREAD

**Issue by tamirms** [stellar/go#3834]
https://github.com/stellar/go/issues/3809 will implement ingestion of liquidity pool effects. we want to make sure the new effects we added are included in the horizon effects response.

We also want to add a new REST endpoint to the horizon API for fetching effects which are relevant for a given liquidity pool:

`GET /liquidity_pools/<pool-id>/effects`

More details about this feature can be found in https://docs.google.com/document/d/1pXL8kr1a2vfYSap9T67R-g72B_WWbaE1YsLMa04OgoU/edit#

**Comment by 2opremio** [comment]
This isn't fixed. #3828 fixed https://github.com/stellar/go/issues/3809

**Comment by 2opremio** [comment]
I am working on this now.
