### ISSUE TITLE
Include liquidity pool trades in trades endpoint

### ISSUE THREAD

**Issue by tamirms** [stellar/go#3835]
https://github.com/stellar/go/issues/3810 will implement ingestion of liquidity pool trades. After that is complete we want to include liquidity pool trades in the trades response.

We will add an extra query parameter to the trades endpoint, `trade_type`, which defaults to `all`.

`GET /trades?trade_type={orderbook,liquidity_pools,all}`

The `trade_type` filter will work in addition to the base and counter asset pair filters. However, Horizon will reject requests which attempt to set `trade_type=liquidity_pools` when using the offer id filter.

The JSON definition of a trade will contain an extra field trade_type which indicates whether the trade occurred against the DEX or on a liquidity pool.

**Orderbook Trade JSON**

The price fraction will represent its numerator and denominator values as strings to be consistent with the liquidity pool trade JSON object.

{
  "id": "157235845014249474-0",
  "paging_token": "157235845014249474-0",
  "ledger_close_time": "2021-07-29T21:10:53Z",
  "offer_id": "738916928",
  "trade_type": "orderbook",
  "base_offer_id": "4768921863441637378",
  "base_account": "GAPP4CS5KSZSHF6A24JWZ2W6MZKPCQKCAW44Y7FFX46WS76WMBDYWKWH",
  "base_amount": "0.0002007",
  "base_asset_type": "native",
  "counter_offer_id": "738916928",
  "counter_account": "GDW634JZX3VMEF2RZTCJTT34RITIMNX46QOGTYHCJEJL3MM7BLOQ6HOW",
  "counter_amount": "0.0022300",
  "counter_asset_type": "credit_alphanum4",
  "counter_asset_code": "VZT",
  "counter_asset_issuer": "GBENYXZDFFR2J4F4DB3YPBBAM244TXYOTIOOUQI5DBT3OKUU4ZJ2M7NO",
  "base_is_seller": false,
  "price": {
    "n": “10000000”,
    "d": “899997”
  }
}

**Liquidity Pool Trade JSON**

The price fraction will represent its numerator and denominator values as strings because they will be 64 bit integers.
Fields that refer to offer ids (e.g. base_offer_id or counter_offer_id) are removed from the response object.
Only one side of the trade will be executed by an account (either base_account or counter_account). The other side of the trade will be executed against a liquidity pool (either base_liquidity_pool_id or counter_liquidity_pool_id).

```
{
  "id": "157235845014249474-0",
  "paging_token": "157235845014249474-0",
  "ledger_close_time": "2021-07-29T21:10:53Z",
  "trade_type": "liquidity_pool",
  "base_liquidity_pool_id": "abcdef",
  "liquidity_pool_fee_bp": 30,
  "base_amount": "0.0002007",
  "base_asset_type": "native",
  "counter_account": "GDW634JZX3VMEF2RZTCJTT34RITIMNX46QOGTYHCJEJL3MM7BLOQ6HOW",
  "counter_amount": "0.0022300",
  "counter_asset_type": "credit_alphanum4",
  "counter_asset_code": "VZT",
  "counter_asset_issuer": "GBENYXZDFFR2J4F4DB3YPBBAM244TXYOTIOOUQI5DBT3OKUU4ZJ2M7NO",
  "base_is_seller": false,
  "price": {
    "n": “10000000”,
    "d": “899997”
  }
}
```

Horizon will also provide an endpoint for retrieving all trades for a given liquidity pool:

`GET /liquidity_pools/<pool-id>/trades`

The response for this endpoint will only contain trade objects of type “liquidity_pool.”

More details about this API can be found in https://docs.google.com/document/d/1pXL8kr1a2vfYSap9T67R-g72B_WWbaE1YsLMa04OgoU/edit#

**Comment by bartekn** [comment]
I noticed that `offer_id` field has been removed in #3857 but it's present in the example response above. Any reason why?

**Comment by tamirms** [comment]
@bartekn `offer_id` should be removed from the example response. It has been marked as deprecated for a while now:

```
https://developers.stellar.org/api/resources/trades/object/
```
