### ISSUE TITLE
Add AMM integration tests

### ISSUE THREAD

**Issue by 2opremio** [stellar/go#3842]
The tests should cover:

* The full lifecycle of a liquidity pool: creation, deposit, withdrawal, trading, removal and revocation
* All the new liquidity pool effects
* All the updated effects (due to the introduction of the liquidity pools)
* Fetching the new liquidity pool operations (deposit and withdraw)
* Querying all the new liquidity pool endpoints (e.g. liquidity pools, effects, by liquidity pool, operations by liquidity pool, transactions by liquidity pool).
* Path payments (send and receive) through a liquidity pool.

In order to run the tests we should update CircleCI to: 
  * Incorporate new jobs to run protocol 18 integration tests. You can see an example at https://github.com/stellar/go/pull/3452 . Instead of using a protocol-specific name for the jobs we should probably use a more generic name (e.g. `next_protocol`) because we will be using separate integration tests for the future protocol releases.
  * Those jobs Core with protocol 18 support (which requires a Core debian package and docker image built with `--enable-next-protocol-version-unsafe-for-production` ).

**Comment by bartekn** [comment]
Most cases handled in #3868. Going to add revoke case when https://github.com/stellar/stellar-core/pull/3162 is merged.

**Comment by bartekn** [comment]
Image updated with new changes so this is no longer blocked.
