### ISSUE TITLE
Horizon friendbot 307 temporarily redirect

### ISSUE THREAD

**Issue by gosom** [stellar/go#387]
Docker horizon installation friendbot 

see here: https://github.com/stellar/horizon/issues/445

**Comment by ckmakcesar** [comment]
@gosom The repository Horizon is closed, we cannot see the issue 445... Could you describe what it was about?

**Comment by bartekn** [comment]
As far as I can remember Docker containers does not have friendbot enabled. I will open an issue in [docker-stellar-core-horizon](https://github.com/stellar/docker-stellar-core-horizon) to add friendbot support. For now, just use the service living here:
```
https://friendbot.stellar.org/?addr={public key of an account to fund}
```
