### ISSUE TITLE
Add a method returning LedgerEntryType of ingest.Change

### ISSUE THREAD

**Issue by bartekn** [stellar/go#3889]
_Originally posted by @bartekn in https://github.com/stellar/go/pull/3887#discussion_r701930453_

Both can be set but it doesn't matter because the type cannot be changed. We basically want to extract ledger entry type from the change. I guess this should be a method on `ingest.Change`.

**Comment by bartekn** [comment]
This issue wasn't about LP type (still cool we have it now!) but Ledger Entry type. Reopening.

**Comment by erika-sdf** [comment]
I think I am a little confused here. Is this different from just referencing `change.Type`?

**Comment by bartekn** [comment]
Oh, you are right. Somehow I was thinking that `change.Type` is `LedgerEntryChangeType`. Closing.
