### ISSUE TITLE
Offers in Stellar orderbooks do not use a reserve model

### ISSUE THREAD

**Issue by tomquisel** [stellar/go#389]
The problem is that an account can place multiple offers (including on the same orderbook), even if the funds necessary to execute all the offers exceeds the balance on the account.

Two possible models to fix this are:

1. use a per-orderbook reserve model
1. use a network-wide reserve model (preferred in my opinion)

## Per-orderbook reserve model

1. Enforce that the sum of offers in an orderbook for a particular account cannot exceed the account's balance.
1. If placing an offer would break that rule, return an error rather than place it.
1. In the case that an offer executes and an account balance is reduced, remove or cut down offers on other orderbooks that now violate the reserve rule.

## Network-wide reserve model

1. Enforce that the sum of offers across all orderbooks for a particular account and asset cannot exceed the account's balance for that asset.
1. If placing an offer would break that rule, return an error rather than place it.

The advantage of this model is there is no need to implicitly modify or remove a user's orders, and it's generally more intuitive.

@MonsieurNicolas I'd love your perspective.

**Comment by MonsieurNicolas** [comment]
Sound like protocol changes, the discussion on this topic is https://github.com/stellar/stellar-protocol/issues/36 - FYI those proposed changes were already discussed there

**Comment by tomquisel** [comment]
It looks like the conclusion of that issue is is to address the problem at the Horizon level instead of the protocol level. Could you reopen this issue with finding a fix at the Horizon level as the goal?

**Comment by MonsieurNicolas** [comment]
You can’t do a reserve model at the horizon layer. What we can do is something like what is linked in the other issue (order book view)

**Comment by tomquisel** [comment]
Gotcha, that makes sense.

I spoke with Scott and came up with a plan that isn't foolproof, but implements a reserve model for the average user at the Horizon level.

**Goal:** in Horizon, prevent a user from submitting a sell offer for an asset that exceeds their balance when added to all their other outstanding offers.

**Implementation:**

* In Horizon when user U submits a new offer O (or increase an existing offer) to sell asset A:
** Load account balance of A for U (supposedly this is fast)
** Load all of U's outstanding offers to sell A (from stellar-core offers table, which is relatively small)
** if all of U's offers (including O) to sell A exceed U's balance of A, reject the offer

This seems relatively lightweight, and enforces a reserve model as long as offers are made through Horizon. This is still quite valuable, as it prevents users of StellarX or other standard tools from generating phantom orders.

**Comment by MonsieurNicolas** [comment]
I am not sure I understand what this is really solving: if you're worried about people pumping the market with shadow offers, wouldn't those people just run their own stellar-core and a version of Horizon that doesn't perform this check? That's pretty cheap to do...

I only see only two choices: allow the problem to happen but compensate by having a way to resolve the view or don't let the problem happen altogether (and that's a protocol change).

**Comment by tomquisel** [comment]
I think it's a great point that this is not a 100% solution, so a protocol change like you're suggesting sounds like the best thing to me.

What's the best way to move that forward?

**Comment by MonsieurNicolas** [comment]
The conversation in the protocol repo needs to continue so that we can make the right change in the protocol layer. At that layer, the right change is not necessarily the change that fits this scenario the best but the change that is the most expressive that also happens to solve this particular business need.

**Comment by lenondupe** [comment]
@tomquisel If I understand you correctly the network-wide reserve model that you describe cannot avoid modifying offers either as account balances can be affected by changes other than trades. You have to take into account that people can make payments that affect balance and most annoyingly because most frequently (in the case of bots active in multiple markets): fees incurred by operations such as managing offers.

**Comment by jedmccaleb** [comment]
Tom there is a big thread about it here: https://github.com/stellar/stellar-protocol/issues/36

**Comment by bartekn** [comment]
This will fixed by [CAP-0003](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0003.md), https://github.com/stellar/stellar-core/pull/1718 and https://github.com/stellar/go/pull/531.
