### ISSUE TITLE
Small payment memo spam

### ISSUE THREAD

**Issue by tomquisel** [stellar/go#390]
In the past few months there have been a large number of tiny payments (0.00001 XLM) from a handful of source accounts going out to thousands of accounts across the network. The memo on these payments contains a spam message (for example a link to stellarpool.io). This provides a poor experience for users, and hurts the reputation of Stellar.

A solution would be to implement a check in Horizon (or Stellar core if necessary) that requires any payment with a memo to have an amount above 0.01 XLM. Any payment violating this would be rejected with an informative message.

Eventually spammers will try payments with other assets as well, so the system should be configurable to easily set arbitrary minimums for any asset payment containing a memo.

Does this sound like a good solution?

**Comment by MonsieurNicolas** [comment]
I thought people already implemented client side the equivalent of a "spam folder"?
I could see adding some simple filters when querying Horizon (like exclude trades smaller than X), but I don't see a reason to add complexity inbound in neither Horizon nor core.

**Comment by bartekn** [comment]
On that front: we merged and deployed: https://github.com/stellar/account-viewer/pull/55 which makes memo less prominent.

**Comment by tomquisel** [comment]
Sounds good! Resolving this for now as something that should be handled client-side.

**Comment by cavemanbingo** [comment]
@bartekn I don't think this is implemented well on Stellar's account viewer. It should only hide *incoming* transactions below the threshold--otherwise it's like sending a person's own transactions to spam. I sent a few very small transactions and couldn't find them in the account viewer, which was confusing.

**Comment by bartekn** [comment]
@cavemanbingo fixed in https://github.com/stellar/account-viewer/pull/73
