### ISSUE TITLE
Could not convert to *big.Rat (Bifrost)

### ISSUE THREAD

**Issue by shaheryar607** [stellar/go#391]
I have setup everything on Ubuntu and used the binary file to install bifrost. When I run bifrost server-test I keep getting error connecting to the server saying 'Invalid minimum accepted Bitcoin transaction value: : Could not convert to *big.Rat'. If I take out the bitcoin portion, I start getting the same error message with ethereum. My minimum_value_btc = "0.1" and minimum_value_eth = "0.1" is this.

I have tried multiple ways but I keep getting the same error. I have tried debugging using Ubuntu, and Mac OS.  I have even tried using docker on a their party repo https://github.com/StellarKit/stellar-bifrost and I am getting the same error. What is the issue?

**Comment by bartekn** [comment]
Could you copy your config file (remove secrets) here? I checked my local binary with `minimum_value_btc = "0.1"` and it worked. I will reopen when we confirm it's not an issue with your config file.

**Comment by shaheryar607** [comment]
Here is my bifrost.cfg file:

```
port = 8000
using_proxy = false
access-control-allow-origin-header = "*"

[bitcoin]
master_public_key = "xpub6DxSCdWu6jKqr4isjo7bsPeDD6s3J4YVQV1JSHZg12Eagdqnf7XX4fxqyW2sLhUoFWutL7tAELU2LiGZrEXtjVbvYptvTX5Eoa4Mamdjm9u"
rpc_server = "localhost:18332"
rpc_user = "user"
rpc_pass = "password"
testnet = true
minimum_value_btc = "0.1"

[ethereum]
master_public_key = "xpub6DxSCdWu6jKqr4isjo7bsPeDD6s3J4YVQV1JSHZg12Eagdqnf7XX4fxqyW2sLhUoFWutL7tAELU2LiGZrEXtjVbvYptvTX5Eoa4Mamdjm9u"
rpc_server = "localhost:8545"
network_id = "3"
minimum_value_eth = "0.1"

[stellar]
issuer_public_key = "GCGIZFVB4RMN5GL4G5M4SEZCGMO5IK3JACHF2TBRSJN363NPUB3NPQUL"
signer_secret_key = ""
token_asset_code = "HUG"
needs_authorize = true
horizon = "https://horizon-testnet.stellar.org"
network_passphrase = "Test SDF Network ; September 2015"

[database]
type="postgres"
dsn="postgres://stellar:password@localhost/bifrost?sslmode=disable"

```

**Comment by bartekn** [comment]
I extracted the code that parses `minimum_value_btc` and `minimum_value_eth` amounts: https://play.golang.org/p/oYHN24Vm9dN and it works with `0.1` value. I think that you have two copies of config file and load the wrong one. Please use `-c [config path]` to load the config file you sent in a comment above.

**Comment by shaheryar607** [comment]
I am already using this command:
bifrost stress-test -c /Users/home/go/src/bifrost/bifrost.cfg

I will look at my geth, bitcoin-core installation/port. Not sure if there's a problem on that end. I will try out a couple things and get back to you.
