### ISSUE TITLE
services/ticker: trade scraping stability improvements

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/go#3918]
We've seen volume of trades on Stellar increase over time to the point where Ticker is seeing some inefficiencies from time to time keeping up. 

I think we could do a few things to improve the trade scraping and make it more reliable:

- [ ] Talk to the team hosting the Horizon that Ticker is talking to about lifting limits, because the 3600req/hour ([ref](https://developers.stellar.org/api/introduction/rate-limiting/)) is too low and unrealistic for Ticker. The 3600req/hour is 1 request per second. Each request can collect 200 trades, that means for a 5s ledger we can collect 1000 trades. The maximum number of trades available in a ledger is 1000 operations x 5 paths in a path payment, i.e. 5000 trades.
- [ ] Investigate the exponential backoff retries. We've seen ([logs](https://kibana.stellar-ops.com/goto/eef755ddea984cb29d383262a07a1a34)) retries consistently occurring after ~5 seconds which suggest the backoff isn't coming into play. https://github.com/stellar/go/blob/d432e29122321d46727ce1f372be3ed6368b19f8/services/ticker/internal/utils/main.go#L86-L101
- [ ] Align retry time with the time Horizon is configured to restore access after a 429 Too Many Requests, so that our backoff is reasonably aligned with when Horizon will let us request again.

**Comment by bartekn** [comment]
Another possibility is: 🥁 `ingest` package 🥁 . 😉
