### ISSUE TITLE
GitHub's CodeQL checks are failing in master

### ISSUE THREAD

**Issue by 2opremio** [stellar/go#3968]
See https://github.com/stellar/go/runs/3736748989

**Comment by 2opremio** [comment]
All the problems except one (fixed at https://github.com/stellar/go/pull/3969 ) were false positives.

I marked the false positives as such

**Comment by 2opremio** [comment]
BTW, is there a reason not to run CodeQL in PRs so that we don't merge code with failing checks? (CC @leighmcculloch )

**Comment by leighmcculloch** [comment]
They should be running on PRs:
https://github.com/stellar/go/blob/0a091b90b4da54707aab1c44c0f05f9929fa4ea7/.github/workflows/codeql-analysis.yml#L8

We don't block merging on a codeql failure, we could though. 

Assuming the PR is #3963 it looks like CodeQL did run and it passed. If it was another PR that didn't run it could you link to it?

**Comment by 2opremio** [comment]
I didn't check if they ran on PRs, but the problem is that the check appears as failed in master but not in PRs

e.g. no errors here https://github.com/stellar/go/pull/3963 , but it failed here https://github.com/stellar/go/commit/e55e42a98f197e3d5313b605a1d5a01dad42f41b
