### ISSUE TITLE
Profile Horizon

### ISSUE THREAD

**Issue by 2opremio** [stellar/go#4022]
I don't think we have profiled the Time (CPU and Wallclock) and Memory performance of Horizon in a while.

We should try doing that and and improve any low hanging fruit we see. Particularly Horizon's ingestion pipeline.

For starters, this is a CPU profile I took from Horizon's staging pubnet deployment:
[pprof.stellar-horizon.samples.cpu.001.pb.gz](https://github.com/stellar/go/files/7391159/pprof.stellar-horizon.samples.cpu.001.pb.gz)

**Comment by 2opremio** [comment]
I took a quick look at the decoding object allocation and performance ... and I found that most (if not all) the intermediary buffers used by the [xdr decoding library](https://github.com/stellar/go-xdr/blob/master/xdr3/decode.go) end up allocated in the heap.

Here are the top-most object allocating functions of Horizon:

<img width="1078" alt="Screenshot 2021-11-02 at 17 18 22" src="https://user-images.githubusercontent.com/2362916/139904447-fce70dae-9d1c-477e-b596-b20493e0070b.png">

If we ignore the calls from the `reflect` package we can see that calls from `xdr.(*Decoder)` account for ~15% of the objects allocated.

Let's take a a peek at `DecodeInt()`:

```

pprof
stellar-horizon alloc_objects

      File: stellar-horizon
Type: alloc_objects
Time: Oct 22, 2021 at 1:30pm (CEST)
Active filters:
   focus=github\.com/stellar/go-xdr/xdr3\.\(\*Decoder\)\.DecodeInt
Showing nodes accounting for 8585334, 5.06% of 169782541 total
----------------------------------------------------------+-------------
      flat  flat%   sum%        cum   cum%   calls calls% + context 	 	 
----------------------------------------------------------+-------------
                                           7110754 82.82% |   github.com/stellar/go-xdr/xdr3.(*Decoder).decodeUnion github.com/stellar/go-xdr@v0.0.0-20201028102745-f80a23dac78a/xdr3/decode.go:530
                                            753674  8.78% |   github.com/stellar/go-xdr/xdr3.(*Decoder).DecodeBool github.com/stellar/go-xdr@v0.0.0-20201028102745-f80a23dac78a/xdr3/decode.go:175
                                            720906  8.40% |   github.com/stellar/go-xdr/xdr3.(*Decoder).decode github.com/stellar/go-xdr@v0.0.0-20201028102745-f80a23dac78a/xdr3/decode.go:801
   8585334  5.06%  5.06%    8585334  5.06%                | github.com/stellar/go-xdr/xdr3.(*Decoder).DecodeInt github.com/stellar/go-xdr@v0.0.0-20201028102745-f80a23dac78a/xdr3/decode.go:105
----------------------------------------------------------+-------------

```

All allocations come from [line 105](https://github.com/stellar/go-xdr/blob/f80a23dac78ac0567e25aa1052fe2d8fe86ed229/xdr3/decode.go#L96-L106), which corresponds to a `var buf [4]byte` array declaration:

```go
func (d *Decoder) DecodeInt() (int32, int, error) {
	var buf [4]byte
	n, err := io.ReadFull(d.r, buf[:])
```

One would think that `buf` would be kept in the stack, but unfortunately that's not the case, due to the call to `ReadFull` using a slice from created from `buf`. From the escape analysis output of go 17.2

```
sweepey:xdr3 fons$ pwd
/Users/fons/go/pkg/mod/github.com/stellar/go-xdr@v0.0.0-20200331223602-71a1e6d555f2/xdr3
sweepey:xdr3 fons$ go build -gcflags '-m -m -l' . |& grep decode.go
[...]
./decode.go:105:6: buf escapes to heap:
./decode.go:105:6:   flow: {heap} = &buf:
./decode.go:105:6:     from buf (address-of) at ./decode.go:106:32
./decode.go:105:6:     from buf[:] (slice) at ./decode.go:106:32
./decode.go:105:6:     from io.ReadFull(d.r, buf[:]) (call parameter) at ./decode.go:106:23
[...]
```

The same applies to the other decoding functions.

The problem is that the reader passed to `io.ReadFull` could keep a copy of `buf` around and thus Go decides to keep it in the heap ( Actually, I think that Go just lets the variable escape the stack due to the call, regardless of what the `io.ReadFull` actually does with it )

This means that, in order to dramatically reduce allocations we should change the Decoder's design so that it reads from a raw buffer (not requiring external IO calls causing stack escapes).

**Comment by leighmcculloch** [comment]
This is really interesting finding. 👏🏻 Combined with that finding we could also rewrite the xdrgen generated Go code to use the same pattern as stellar/xdrgen#65 does for encoding, and apply it to decoding so that no reflection is necessary.

**Comment by 2opremio** [comment]
The problems I identified above are fixed by https://github.com/stellar/go-xdr/pull/16

**Comment by 2opremio** [comment]
I think that after all the recent PRs we can consider XDR encoding and decoding sufficiently optimized for now.

If we decide to do more work in that regard, I think we should try to reduce decoding allocations, which will be hard but not impossible. For instance we could try to intern the Assets much like [string interning](https://en.wikipedia.org/wiki/String_interning)

**Comment by 2opremio** [comment]
I have profiled a staging captive core ingestion instance for 240 seconds and it seems that ingestion is dominated by the state verifier:

<img width="847" alt="Screenshot 2021-11-16 at 13 14 45" src="https://user-images.githubusercontent.com/2362916/141983708-13599e94-1722-4a55-af84-01c245c0a454.png">

**Comment by 2opremio** [comment]
While the CPU execution is dominated by the state verifier, Go's profiler only measures CPU time and not wallclock time.

Go's profiler also provides tracing, which AFAIU can be used to infer IO wait time

Finally https://github.com/felixge/fgprof combines both, providing wallclock profiling.

I am going to evaluate both in staging and see what I get. See https://github.com/stellar/go/pull/4079

**Comment by 2opremio** [comment]
Here is the fgprof time profile: [pprof.samples.time.001.pb.gz](https://github.com/stellar/go/files/7548572/pprof.samples.time.001.pb.gz)

Unfortunately, although it looks very different at the top level:
<img width="637" alt="Screenshot 2021-11-16 at 18 34 16" src="https://user-images.githubusercontent.com/2362916/142036605-e1cfb38c-3ee5-4e21-a379-09e8dc69045c.png">


When focusing on `RunAllProcessorsOnLedger`, it looks very similar to what it looked before:

<img width="639" alt="Screenshot 2021-11-16 at 18 35 09" src="https://user-images.githubusercontent.com/2362916/142036640-e199cb93-326b-42c9-905a-5953da37dfef.png">

So I am not sure fgprof is working well. It seems that, for some reason, it's missing DB queries.

**Comment by bartekn** [comment]
Add added metrics to specific batch inserts in https://github.com/stellar/go/pull/4080 and it turns out that `Exec` takes 34.91/37.35 = 93% of all time spent in `TransactionProcessor` (sample of 280 pubnet ledgers). So there's definitely something about the query itself (or some preprocessing of the query in `Exec`).

**Comment by 2opremio** [comment]
I think it would also be useful to add tracing to db queries in general

This golang issue includes some alternatives: https://github.com/golang/go/issues/18080

**Comment by bartekn** [comment]
It looks like all the XDR improvements and https://github.com/stellar/go/pull/4087 made `TransactionProcessor` fast again. Should we close this or move to backlog?

**Comment by 2opremio** [comment]
Move it to the backlog. I think we will need go keep working on this.

Also (without downplaying the improvements) the transaction's processor is still the bottleneck, right?

I still think there is a lot to be gained by improving the performance of the batch insert builder in general.

**Comment by bartekn** [comment]
What do you think about closing this issue and creating specific issues connected to performance improvements? This one is very general and I guess could live in the backlog forever.
