### ISSUE TITLE
Feature Request: Allow captive core to run with sqlite database

### ISSUE THREAD

**Issue by tamirms** [stellar/go#4038]
### What problem does your feature solve?

If the size of the ledger continues to increase this will result in captive core consuming more memory since it maintains all of its data structures in memory. Stellar Core supports running with a sqlite database. So allowing captive core to maintain some of its state on disk would help reduce memory usage. But we should measure the performance impact of this change.

**Comment by sreuland** [comment]
got some PR feedback, pulling back to `in progress` need to add new command line flag to allow operator to enable captive core sqlite db usage as option and keep the default captive core usage to current in-memory.
