### ISSUE TITLE
Column "ledger_header" does not exist when starting horizon server

### ISSUE THREAD

**Issue by datspider** [stellar/go#407]
<img width="1431" alt="screen shot 2018-04-17 at 8 27 16 am" src="https://user-images.githubusercontent.com/12639939/38843450-3696ce1a-4219-11e8-8c8b-44bf09f79701.png">

The log is above. I have 4 instances running Core, I want to expand my system so that I stop them and copy all the database, log to new Core. Then I update Core from "prod" branch and Horizon from "master" branch. When I start Core, they can consensus and running smoothly but when I start Horizon with INGEST=true I got this error.
Is there any conflict in the version of Core and Horizon?
Thank you for your support.

**Comment by nullstyle** [comment]
Your database has probably not been properly set up.

https://www.stellar.org/developers/horizon/reference/admin.html#preparing-the-database
