### ISSUE TITLE
services/horizon: slower catch up with captive core vs non-captive core

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/go#4090]
I've noticed that the tests for the stellar/quickstart image repeatedly take 6x longer on the build that has the `--enable-captive-core` option, and if you drill in to the time spent in the test, it is 300x longer (5m vs 20s). My understanding is the test in that repo waits for the instance to catch up. That seems like a pretty big difference. Given captive-core is the new approach it is a bit odd it is performing poorly in comparison. It's possible that this difference is not catch up, and is instead is the time it takes captive-core to setup, I'm not sure. But it seems like a big enough difference worth notifying someone about.

Example: 

<img width="627" alt="Screen Shot 2021-11-19 at 8 26 03 PM" src="https://user-images.githubusercontent.com/351529/142714357-52e379f6-8ca1-424f-821d-08c232ea6fc8.png">

Ref: https://github.com/stellar/quickstart/actions/runs/1483685683

I have not investigated this beyond what I've observed here. This issue is not impacting me, and is not blocking me on anything. I note that there was a similar issue #3132 opened and fixed previously, so I assume this problem is worth opening an issue over.

cc @bartekn who was involved with #3132

**Comment by bartekn** [comment]
The reason for this is that Captive-Core requires a HAS checkpoint to be published to be able to sync and start streaming ledgers - you can see that the difference between non-CC and CC tests is more or less 5 minutes which is equal to a checkpoint frequency.

We were able to improve the speed a little bit in `stellar/go` integration tests by setting `ARTIFICIALLY_ACCELERATE_TIME_FOR_TESTING=true` in Stellar-Core config that changes ledger close time to 1s and checkpoint frequency to 8 ledgers. This means that the first checkpoint is published after around 8s vs 5 minutes).

**Comment by leighmcculloch** [comment]
@bartekn Thanks for going into detail on what the difference is between running in these modes. 👍🏻
