### ISSUE TITLE
Feature Request: API - Add original integral value for ClaimableBalance:Claimant:Predicate:AbsBefore 

### ISSUE THREAD

**Issue by sreuland** [stellar/go#4095]
### What problem does your feature solve?
Some SDK clients will not able to parse the custom/extended ISO 8601 date format for absBefore returned in API json responses for ClaimableBalance:Claimant:Predicate:AbsBefore per [the Horizon serverside API implementation changes done last year.](https://github.com/stellar/go/pull/3183/files) 

If the absBefore value happens to equate to a large date beyond 4 digit year range of 0000-9999, and clients try to apply their standard datetime parsing library on it, they will likely get error or invalid value from languages such as js/python/java, this is because they follow the ISO 8601 more closely, and aren't equipped to either handle the "=/-" prefix that is appended at beginning of the absBefore date string emitted by API, or they don't use large enough integer value to capture the year which can now roughly be 292277026596 into future and -292471206707 in past.

### What would you like to see?
Add a new element, `AbsBeforeEpoch` to the API Resource 'ClaimableBalance:Claimant:Predicate', when a Predicate has `AbsBefore` value present, also include `AbsBeforeEpoch`, having the original integral value specified in the CreateClaimableBalance:Claimant:Predicate:AbsBefore source transaction. So, example of the updated API json model for 'ClaimableBalance:Claimant:Predicate' would resemble:

```
"claimants": [
    {
      "destination": "GBQECQVAS2FJ7DLCUXDASZAJQLWPXNTCR2DGBPKQDO3QS66TJXLRHFIK",
      "predicate": {
        "abs_before": "+39121901036-03-29T15:30:22Z",
        "abs_before_epoch": "1234567890982222222"
      }
    },
    {
      "destination": "GAKFBRS24U3PEN6XDMEX4JEV5NGBARS2ZFF5O4CF3JL464SQSD4MDCPF",
      "predicate": {
        "unconditional": true
      }
    }
  ]
```
Goal is to be additive, non-breaking change, denote `AbsBefore` as deprecated in the API docs for future removal. 

### What alternatives are there?
- Assess behavior of current SDKs: 
-- Go: works correctly, since it has the custom ser/deser code for absBefore
-- Java: throws exception as reported on [bug #354](https://github.com/stellar/java-stellar-sdk/issues/354) 
--  js: doesn't interpret absBefore, just pass through, if client code attempts to parse then would get issue.
-- python(StellarCN): same as js
- Update the API docs in any case to accurately inform clients about the details of the custom format of absBefore, have submitted [request #600](https://github.com/stellar/new-docs/issues/600). Clients choose how to handle/parse.
- Fix the Java SDK to handle the custom absBefore format since it's done automatically by the sdk during API json unmarshal phase, client has no control over it. Since issue already filed, have [PR #382](https://github.com/stellar/java-stellar-sdk/pull/382) to address.

**Comment by Shaptic** [comment]
Do we need to raise SDK issues for this new field? I think yes.

**Comment by sreuland** [comment]
> Do we need to raise SDK issues for this new field? I think yes.

Yes, SDK's should map this new optional field so clients can gain access to it, looks like it will be available from Horizon server starting from release 2.13.0. For most SDK's, the field was not required as they did not incur a runtime parsing problem, except for the Java SDK, which had runtime parsing issue on absBefore and a dependency on this issue for resolution, so there was already a ticket for this visibility on this new field in Java SDK ticket:
https://github.com/stellar/java-stellar-sdk/pull/382
