### ISSUE TITLE
Error 500 When high TPS (Horizon / GOlang)

### ISSUE THREAD

**Issue by ckmakcesar** [stellar/go#410]
Background: 

> Private network ; 4 nodes on the same network 
OS=Ubuntu16.04 
"horizon_version": "devel"
"core_version": "v9.2.0-126-g7497bd9-dirty"
"protocol_version": 10

Test case: js-stellar-sdk was used to submit "PayAsset" transaction, repeatedly at different TPS, via 500 channel accounts. 

Issue: Occasionally tx failed with the following message, especially when the TPS loading is higher (e.g. 100tps). 

p.s. Core network has been upgraded'with "maxtxsize=10000" ; Horizon has set rate limit to 1440000000. 

`$ console.log(error)` 

```

{ [NetworkError: 500]
  name: 'NetworkError',
  message: 500,
  data: 
   { status: 500,
     statusText: 'Internal Server Error',
     headers: 
      { 'content-type': 'application/problem+json; charset=utf-8',
        vary: 'Origin',
        'x-ratelimit-limit': '1440000000',
        'x-ratelimit-remaining': '1439981985',
        'x-ratelimit-reset': '3314',
        date: 'Wed, 18 Apr 2018 02:20:11 GMT',
        'content-length': '470',
        connection: 'close' },
     config: 
      { transformRequest: [Object],
        transformResponse: [Object],
        headers: [Object],
        timeout: 0,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        validateStatus: [Function: validateStatus],
        method: 'get',
        url: 'http://192.168.7.37:8000/accounts/GC4HZVOADQQFPFMUQL64TJXX7NVT5G4TLZFBHOAAOABE7KJMLVUN7MVG?c=0.841701039875218',
        withCredentials: undefined,
        data: undefined },
     request: 
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedHeader: {},
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'GET /accounts/GC4HZVOADQQFPFMUQL64TJXX7NVT5G4TLZFBHOAAOABE7KJMLVUN7MVG?c=0.841701039875218 HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.12.0\r\nHost: 192.168.7.37:8000\r\nConnection: close\r\n\r\n',
        _headers: [Object],
        _headerNames: [Object],
        _onPendingData: null,
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path: '/accounts/GC4HZVOADQQFPFMUQL64TJXX7NVT5G4TLZFBHOAAOABE7KJMLVUN7MVG?c=0.841701039875218',
        _ended: true,
        res: [Object],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null },
     data: 
      { type: 'https://stellar.org/horizon-errors/server_error',
        title: 'Internal Server Error',
        status: 500,
        detail: 'An error occurred while processing this request.  This is usually due to a bug within the server software.  Trying this request again may succeed if the bug is transient, otherwise please report this issue to the issue tracker at: https://github.com/stellar/go/services/horizon/internal/issues. Please include this response in your issue.' } } }

```

---

---

Edit: a glance on the Horizon log suggests this might be an issue with GOlang. 

> **dial tcp 192.168.7.27:11626: socket: too many open files**
https://stackoverflow.com/questions/32325343/go-tcp-too-many-open-files-debug

[Tried with tuning up ulimit](http://posidev.com/blog/2009/06/04/set-ulimit-parameters-on-ubuntu/) from 1024 to 100,000 but issue remains. 

> time="2018-04-18T10:15:49+08:00" level=error msg="failed to submit: http request errored: Get http://192.168.7.27:11626/tx?blob=AAAAAI8cgq5GnrvY%2FasRe(...)MNkDX1xHN4AAABA7nz%2Bi3Mw%2FBuGVBvkTKvB7am147WF3oDZ2oFt7cQ7FCDNqPOxlJOTXcmQHhw3TOZ%2FzqcOmy7cuGiMNGpqee07AQ%3D%3D: **dial tcp 192.168.7.27:11626: socket: too many open files**" pid=29116 stack="[main.go:43 submitter.go:40 system.go:150 system.go:105 actions_transaction.go:162 actions_transaction.go:148 base.go:119 actions_transaction.go:146 base.go:52 main_generated.go:152 <autogenerated>:1 router.go:119 middleware.go:88 server.go:1918 throttler.go:64 server.go:1918 cors.go:190 server.go:1918 compress.go:66 server.go:1918 options.go:70 server.go:1918 middleware_recover.go:27 server.go:1918 middleware_request_metrics.go:19 timer.go:212 middleware_request_metrics.go:18 server.go:1918 middleware_logger.go:32 server.go:1918 xff.go:64 server.go:1918]"

> time="2018-04-18T12:06:57+08:00" level=error msg="get failed: **dial tcp 127.0.0.1:5432: socket: too many open files**" pid=29116 stack="[main.go:43 session.go:106 session.go:83 transaction.go:16 main.go:30 system.go:65 actions_transaction.go:162 actions_transaction.go:148 base.go:119 actions_transaction.go:146 base.go:52 main_generated.go:152 <autogenerated>:1 router.go:119 middleware.go:88 server.go:1918 throttler.go:64 server.go:1918 cors.go:190 server.go:1918 compress.go:66 server.go:1918 options.go:70 server.go:1918 middleware_recover.go:27 server.go:1918 middleware_request_metrics.go:19 timer.go:212 middleware_request_metrics.go:18 server.go:1918 middleware_logger.go:32 server.go:1918]"

**Comment by bartekn** [comment]
It clearly isn't an issue with Horizon. You must increase your system limits. Try to ask at Stellar Stack Exchange.
