### ISSUE TITLE
services/horizon: still ingesting after sync is finished

### ISSUE THREAD

**Issue by suggalla** [stellar/go#4111]
## Issue Description

Version affected: Version: v18.1.0

Receiving this error from the SDK even after the node is fully synced:
```
  "type": "https://stellar.org/horizon-errors/still_ingesting",
  "title": "Still Ingesting",
  "status": 503,
  "detail": "Data cannot be presented because it's still being ingested. Please wait for several minutes before trying your request again."
```

This issue is similar to this: https://stellar.stackexchange.com/questions/5839/503-still-ingesting-forever-after-version-18-0-0-update

That has no response so I made an issue here.

**Comment by bartekn** [comment]
Can you send us the logs of your Horizon? Even though Stellar-Core is sync, a fresh Horizon instance needs to ingest current state. It can take up to 30 minutes (depending on the hardware spec) and is just done once.

**Comment by mollykarcher** [comment]
Closing this as there hasn't been any update to the request for more info above. Please re-open if you're still experiencing an issue.
