### ISSUE TITLE
services/horizon: duplicate key violation of unique constraint

### ISSUE THREAD

**Issue by alexqrid** [stellar/go#4112]
### What version are you using?
```sh
user@stellar:~/stellar$ ./stellar-core version
v18.0.3
user@stellar:~/stellar$ horizon version
2.11.0-07dcbb1e43d9ee991461e1284af1d11dcae645d7
go1.17.3

PostgreSQL 14.0 (Ubuntu 14.0-1.pgdg18.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit

```

### What did you do?
I was running horizon for a few months and everything were ok. But on 18 November 2021 horizon failed to ingest new blocks because of violating unique constraint `liquidity_pools_pkey`.  
I just dropped the database and reingested blocks, it was ok until today, the error happened again.
Here is a part of horizon logs and postgres logs:  

```sh
#HORIZON
[2021-12-01T04:21:27.839Z] Error in ingestion state machine current_state="resume(latestSuccessfullyProcessedLedger=38503090)" error="Error running processors on ledger: Error commiting changes from processor: error in *processors.LiquidityPoolsChangeProcessor.Commit: error upserting liquidity pools: exec failed:
 pq: duplicate key value violates unique constraint \"liquidity_pools_pkey\"" next_state="resume(latestSuccessfullyProcessedLedger=38503090)" pid=22569 service=ingest
#POSTGRES
2021-11-23 06:08:39.843 UTC [11804] user@horizon ERROR:  duplicate key value violates unique constraint "liquidity_pools_pkey"
2021-11-23 06:08:39.843 UTC [11804] user@horizon DETAIL:  Key (id)=(f7283cebce7c75aba5366e8e2e553d8236323a9d060120426d842e52ae226ba6) already exists.
2021-11-23 06:08:39.843 UTC [11804] user@horizon STATEMENT:  
                WITH r AS
                        (SELECT unnest($1::text[]) /* id */,unnest($2::smallint[]) /* type */,unnest($3::integer[]) /* fee */,unnest($4::bigint[]) /* trustline_count */,unnest($5::bigint[]) /* share_count */,unnest($6::jsonb[]) /* asset_r
eserves */,unnest($7::integer[]) /* last_modified_ledger */,unnest($8::boolean[]) /* deleted */)
                INSERT INTO liquidity_pools
                        (id,type,fee,trustline_count,share_count,asset_reserves,last_modified_ledger,deleted)
                SELECT * from r
                ON CONFLICT (id) DO UPDATE SET
                        id = excluded.id,type = excluded.type,fee = excluded.fee,trustline_count = excluded.trustline_count,share_count = excluded.share_count,asset_reserves = excluded.asset_reserves,last_modified_ledger = excluded.last_modified_ledger,deleted = excluded.deleted
2021-11-23 06:08:40.946 UTC [11804] user@horizon ERROR:  duplicate key value violates unique constraint "liquidity_pools_pkey"
2021-11-23 06:08:40.946 UTC [11804] user@horizon DETAIL:  Key (id)=(f844e4109338e59c5005d60e7377aa7f0518553fb75763e702c467de70575847) already exists.
```

I didn't saved the logs from 18th November, but I have a query screenshots that I made on that day. And it seems that the violation of unique constraint happens with the same key  `f7283cebce7c75aba5366e8e2e553d8236323a9d060120426d842e52ae226ba6`
<details><summary>Screenshots of the query </summary>

![image](https://user-images.githubusercontent.com/30272185/144196545-c10c569d-1b3e-45f6-b4aa-e62db01557e4.png)

After executing `VACUUM FULL ANALYZE`:
![image](https://user-images.githubusercontent.com/30272185/144196631-84177a86-3e7c-46b9-9209-c1b8542fcb96.png)

</details>

I thought that the error can be related to the postgresql issue and also asked about it in postgresql community chat, and received a link on [postgresql issue](https://www.postgresql.org/message-id/17245-ddf06aaf85735f36@postgresql.org).  
Anyway want to be sure that this is not a buggy code in `horizon`, as the problem occurs while processing the same pool `f7283cebce7c75aba5366e8e2e553d8236323a9d060120426d842e52ae226ba6` as far as I understood.

**Comment by 2opremio** [comment]
Possible related to #4110

**Comment by bartekn** [comment]
Thanks for reporting this. Indeed, this is strange because nobody reported anything similar and also SDF haven't experienced this issue. Also we have explicit `ON CONFLICT (id) DO UPDATE SET` clause so the really looks like Postgres bug.

**Comment by alexqrid** [comment]
It seems that the problem was with PostgreSQL 14.0 version. Horizon has been running for 21 days without any problem using ` PostgreSQL 14.1 (Ubuntu 14.1-1.pgdg18.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit`. 
I'm closing the issue as the problem solved.
