### ISSUE TITLE
services/horizon: Path Payment Strict Receive Not Using Liquidity Pools

### ISSUE THREAD

**Issue by Heteroculturalism** [stellar/go#4124]
## Issue Description

Strict Receive Path Payments Do Not Use Liquidity Pools

## Steps to Reproduce
In [Horizon Testnet](https://horizon-testnet.stellar.org), I executed a "swap", that is, a strict path payment to myself for one asset to another

`AAAAAgAAAABAPEGMsGRbM1VIw3l5TE3EHdrT9jgBR2g5CA5kGtRMfgAAAMgAEmFvAAAACgAAAAEAAAAAAAAAAAAAAABhonNjAAAAAAAAAAIAAAAAAAAABgAAAAJTb2xkaWVycwAAAAAAAAAACg7GN4V2JwQcc/8zzZdoU0R17Pg+fKjrRaJM/EeCA19//////////wAAAAAAAAACAAAAAVVTREMAAAAArGCmkUDdw6gF+Qhxjy7tSAOaQnMDHkmpdt0EdJBj+8gAAAACVAvkAAAAAABAPEGMsGRbM1VIw3l5TE3EHdrT9jgBR2g5CA5kGtRMfgAAAAJTb2xkaWVycwAAAAAAAAAACg7GN4V2JwQcc/8zzZdoU0R17Pg+fKjrRaJM/EeCA18AAAAAAmJaAAAAAAAAAAAAAAAAARrUTH4AAABA+G8ajYEIjjrbJsllCu+KzWIiGNZTWBrccuwTSJPyDblTeUqAEWAMDZskehGbd0Z8D9VYxCq5bWG0YR/2XxF5Dw==`

## Expected Result
The transaction succeed.  [According to Horizon](https://horizon-testnet.stellar.org/paths/strict-receive?source_account=GBADYQMMWBSFWM2VJDBXS6KMJXCB3WWT6Y4ACR3IHEEA4ZA22RGH4GMB&destination_asset_type=credit_alphanum12&destination_asset_issuer=GAFA5RRXQV3COBA4OP7THTMXNBJUI5PM7A7HZKHLIWREZ7CHQIBV7SXF&destination_asset_code=Soldiers&destination_amount=4), there is such a path.

## Actual Result
A failed transaction due to "op_too_few_offers"
`AAAAAAAAAMj/////AAAAAgAAAAAAAAAGAAAAAAAAAAAAAAAC////9gAAAAA=`

**Comment by ire-and-curses** [comment]
I think this can occur if the path Horizon returns is taken by someone else before your operation executes. But we should check it out.

**Comment by tamirms** [comment]
@Heteroculturalism it looks like the XDR you submitted did not include any assets in the path field. This is the tx you submitted:

https://laboratory.stellar.org/#xdr-viewer?input=AAAAAgAAAABAPEGMsGRbM1VIw3l5TE3EHdrT9jgBR2g5CA5kGtRMfgAAAMgAEmFvAAAACgAAAAEAAAAAAAAAAAAAAABhonNjAAAAAAAAAAIAAAAAAAAABgAAAAJTb2xkaWVycwAAAAAAAAAACg7GN4V2JwQcc%2F8zzZdoU0R17Pg%2BfKjrRaJM%2FEeCA19%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwAAAAAAAAACAAAAAVVTREMAAAAArGCmkUDdw6gF%2BQhxjy7tSAOaQnMDHkmpdt0EdJBj%2B8gAAAACVAvkAAAAAABAPEGMsGRbM1VIw3l5TE3EHdrT9jgBR2g5CA5kGtRMfgAAAAJTb2xkaWVycwAAAAAAAAAACg7GN4V2JwQcc%2F8zzZdoU0R17Pg%2BfKjrRaJM%2FEeCA18AAAAAAmJaAAAAAAAAAAAAAAAAARrUTH4AAABA%2BG8ajYEIjjrbJsllCu%2BKzWIiGNZTWBrccuwTSJPyDblTeUqAEWAMDZskehGbd0Z8D9VYxCq5bWG0YR%2F2XxF5Dw%3D%3D%0A%0A&type=TransactionEnvelope&network=test

The path field in the `pathPaymentStrictReceive` operation is empty. It should contain  `DOLLAR:GBMLAJ3MYHUL4FD245TGZWAMJ2D5ANJDKKDYRB5XKOU6D7AN7HE6O2QF` which is the intermediate asset in the path payment
