### ISSUE TITLE
Regression in 2.12. Pathfinding

### ISSUE THREAD

**Issue by marcinx** [stellar/go#4131]
### What version are you using?

Noticed regression in 2.12. (works fine in 2.11.)

### What did you do?

Invoked /paths/strict-send in 2.12

### What did you expect to see?

Results similar to /paths/strict-send in 2.11 and earlier versions

### What did you see instead?

It looks like 2.12. started omitting results in which the source asset and destination asset are the same. 

When invoking, e.g. https://horizon.stellar.org/paths/strict-send?destination_account=GASKYWPPQ2VSO6KNIPIRVXMSSDGZLYZQ67CDTLVXOXYDG26SPZ66EDCQ&source_asset_type=credit_alphanum4&source_asset_code=BTC&source_asset_issuer=GAUTUYY2THLF7SGITDFMXJVYH3LHDSMGEAKSBU267M2K7A3W543CKUEF&source_amount=0.0005953 the response **used to** include a result with the source asset `BTC:GAUTUYY2THLF7SGITDFMXJVYH3LHDSMGEAKSBU267M2K7A3W543CKUEF` being the destination asset at the same time.

The below result item is missing in 2.12. (but exists in 2.11.). The asset exists on the destination account but is missing as a corresponding result in the path finding response.

```
      {
        "source_asset_type": "credit_alphanum4",
        "source_asset_code": "BTC",
        "source_asset_issuer": "GAUTUYY2THLF7SGITDFMXJVYH3LHDSMGEAKSBU267M2K7A3W543CKUEF",
        "source_amount": "0.0005953",
        "destination_asset_type": "credit_alphanum4",
        "destination_asset_code": "BTC",
        "destination_asset_issuer": "GAUTUYY2THLF7SGITDFMXJVYH3LHDSMGEAKSBU267M2K7A3W543CKUEF",
        "destination_amount": "0.0005953",
        "path": []
      },
```

The above result item is included in 2.11. (compare: https://horizon.stellar.coinqvest.com/paths/strict-send?destination_account=GASKYWPPQ2VSO6KNIPIRVXMSSDGZLYZQ67CDTLVXOXYDG26SPZ66EDCQ&source_asset_type=credit_alphanum4&source_asset_code=BTC&source_asset_issuer=GAUTUYY2THLF7SGITDFMXJVYH3LHDSMGEAKSBU267M2K7A3W543CKUEF&source_amount=0.0005953).

Unfortunately this broke a few things in our application, which currently depends on the result item being present.  Can we make the item re-appear in the list?

**Comment by tamirms** [comment]
ok, it looks like normal payments are a subset of path payments. we can include these in the response

**Comment by marcinx** [comment]
I can imagine that other people used this to detect arbitrage opportunities. I am almost sure that this used to find them. It's irrelevant for our individual use case though. We are happy if the path is [] for this type of pair, as long as all assets on the destination account exist in the response.
