### ISSUE TITLE
services/horizon: Filter out "small" liquidity pool trades from /trade_aggregations

### ISSUE THREAD

**Issue by paulbellamy** [stellar/go#4160]
### What problem does your feature solve?

https://github.com/stellar/stellar-core/issues/3301

Small transactions on liquidity pools, can cause the price reported by /trade_aggregations to swing wildly (as in above).

DEX UIs use the output of /trade_aggregations to draw graphs, so the graphs can be misleading.

### What would you like to see?

There are two proposed solutions:

a. Filter out "dust" liquidity pool trades when calculating trade aggregations.
  - Possibly using formula: `|unrounded - rounded| / (unrounded + rounded) < epsilon`, but how do we calculate the unrounded? Is that data stored on the trades/transactions?
    - @paulbellamy: afaict, we would have to add it, and reingest.
  - If we offer both filtered and unfiltered data, that doubles the db size of trade aggregations table (currently ~60gb)
  - This option seems more feasible.
 
b. Add "supply ratio" metrics to /trade_aggregations.
  - We would need to track it at each point in time, though. We could track it incrementally, but then a historical reingest could impact all following trade aggregations.
  - We would need an equivalent metric for orderbook trades as well.
    - @jonjove: Possibly, the best thing to do would be to consider the resulting bid or ask depending on the direction of the trade.
  - Adding supply ratio stats (open/close/high/low) should only add around 1.7gb to the db, so it’s better there, but might be more intensive to calculate.

**Comment by jonjove** [comment]
Also related to https://github.com/stellar/go/issues/4132

**Comment by Shaptic** [comment]
Is it a viable option to instead prevent these trades from either (a) being returned, within the path-finding module, or (b) occurring on our Horizon (though this would involve parsing txs)?

I'm not sure (a) would mitigate much, as the offending party could just use their own path-finding, and (b) is quite involved, but just a thought.

**Comment by Shaptic** [comment]
Alternatively: close this as `wontfix` and pass the responsibility along to API consumers. The data we're providing is correct, after all...

**Comment by paulbellamy** [comment]
> (b) occurring on our Horizon (though this would involve parsing txs)?

Is this the same as option `a.` in the OP? Or do you mean hiding them at an earlier stage? Or preventing them from submitting altogether?

**Comment by paulbellamy** [comment]
> Alternatively: close this as `wontfix` and pass the responsibility along to API consumers. The data we're providing is correct, after all...

Appealing, but this *is* causing issues for API consumers, so would be good to have an alternative proposed approach for them. And/or to discourage the behaviour altogether.

**Comment by Shaptic** [comment]
For (b), I meant preventing them from submitting altogether. In other words, parse the transaction, and if it contains some bs nonsense trade like this, drop it. In some ways this is a step away from "neutrality" from our perspective, but hey, it's our Horizon... Like (a), this is mitigated by using custom software, but it's still a possible deterrent.

**Comment by paulbellamy** [comment]
Would this be a strong argument in favor of pushing wallets/exchanges to use candlestick graphs instead of line graphs?

**Comment by jonjove** [comment]
> Possibly using formula: `|unrounded - rounded| / (unrounded + rounded) < epsilon`, but how do we calculate the unrounded? Is that data stored on the trades/transactions?
@paulbellamy: afaict, we would have to add it, and reingest.

I was thinking a bit about how the `unrounded` values can be attained. There are a couple of tricky issues:

- the meta will only contain the pre/post state from the entire operation
- the same liquidity pool can be traded against multiple times in a single operation (for example, a path payment A -> B -> A)
- the claim liquidity atoms for `PathPaymentStrictReceive` are in reverse order relative to how core actually executes the trades

That being said, it should be possible to compute the `unrounded` values using just that information by taking the pre state and then applying the deltas from the claim liquidity atoms. I'm not sure if having the data in this way (eg. in effects and transaction results) is enough to avoid reingesting, but I figured I would mention an approach that I saw.

**Comment by hot-bit-git** [comment]
One of the ideas to mitigate rounding error I found is to introduce min_send limit (rise it from 1 stroop to 100 or 1000), another solution is to check both strictSend and strictReceive methods' outcomes and for a real trade choose one that yields better price. 
https://github.com/stellar/stellar-protocol/issues/1106#issuecomment-1006699068
In the second solution, sometimes `PathPaymentStrictSend` would be chosen instead of `PathPaymentStrictReceive`. Or instead of changing operation type transaction could simply be failed due to causing price to deviate from the best available market price.

Pros: some 1 to 1 stroop operations would be disallowed/failed, no need for any extra data to store in the db (for filtering purposes)
Cons: additional compute cost

**Comment by paulbellamy** [comment]
As @jonjove pointed out, the meta pre/post states include the pool reserves, and the amount bought/sold. So we can use that in the trades_processor to calculate expected "price", detect the rounding, and filter those trades out in trade aggs. 👍 We'll need to reimplement the liquidity pool calculation from core to calculate the unrounded, but, seems ok.

**Comment by hot-bit-git** [comment]
Sadly price charts are still unusable.
![broken-charts](https://user-images.githubusercontent.com/35734693/178156282-ef8a0ee0-4bf7-4047-a418-05ae2603a04b.png)
