### ISSUE TITLE
FetchCursor call that takes in a ledger or a timestamp and finds the closest cursor to that

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/go#42]
so people can stream various things from a particular point in time

**Comment by abhishekmehravaultbank** [comment]
Need help in retrieving transaction records based on specific timestamp.

**Comment by abhishekmehravaultbank** [comment]
Need help in retrieving transaction records based on specific timestamp

**Comment by howardtw** [comment]
@ire-and-curses is this still relevant? It was assigned to me a long time ago.

**Comment by 2opremio** [comment]
`FetchCursor` doesn't exist anymore
