### ISSUE TITLE
Remote captive core setup documentation on website out of date

### ISSUE THREAD

**Issue by l3utterfly** [stellar/go#4241]
### What version are you using?

Horizon 2.14
Go 1.17

### What did you do?

Follow the documentation steps to setup Remote Captive Core: https://developers.stellar.org/docs/run-api-server/remote-core/

### What did you expect to see?

Expected everything to work out of the box.

### What did you see instead?

Everything went well until running the command to start the captive core.

From the documentation:

stellar-captive-core-api \
  --stellar-core-binary-path=$(which stellar-core) \
  --captive-core-config-append-path=/etc/default/stellar-captive-core-stub.toml \
  --history-archive-urls="https://history.stellar.org/prd/core-testnet/core_testnet_001" \
  --port=8001

Error:

Error: unknown flag: --captive-core-config-append-path

Command that worked for me:

stellar-captive-core-api --stellar-core-binary-path=$(which stellar-core) --captive-core-config-path "/home/ubuntu/stellar-captive-core.cfg" --history-archive-urls="[urls omitted here]" --port=8001

It seems the website docs are out of date?

**Comment by mollykarcher** [comment]
Remote captive-core has been deprecated
