### ISSUE TITLE
Improve error message after Stellar-Core crash

### ISSUE THREAD

**Issue by bartekn** [stellar/go#4255]
Currently, when Stellar-Core crashes when preparing a new range it logs the following error message:
```
error preparing range: Error fast-forwarding to 17089856: error reading frame length: unmarshalling XDR frame header: xdr:DecodeUint: EOF while decoding 4 bytes - read: '[]'
```
This is really confusing. We should improve this message and, if possible, log the latest `error` level message from Stellar-Core.

**Comment by 2opremio** [comment]
Related https://github.com/stellar/go/pull/4066

**Comment by bartekn** [comment]
> https://github.com/stellar/go/pull/4066

Yeah, looks like there's another place in the code we aren't doing this properly.
