### ISSUE TITLE
Allow limiting number of path finding cycles per second

### ISSUE THREAD

**Issue by bartekn** [stellar/go#4263]
It should be able to limit a number of cycles a single path finding instance/Horizon instance can execute per second. This should allow to cap the CPU usage so that it doesn't consume 100% under heavy load connected to path finding. There should also be a simple stress-testing tool that will help checking what the limit should be set to on a specific instance type.

**Comment by tamirms** [comment]
I would prefer if we implemented a limit on the number of concurrent calls to the path finding function. Any attempts to call the function beyond the limit will be rejected with an error. I think this would be easier to implement.

**Comment by sreuland** [comment]
we are really pushing on the abilities of rules in lb/proxy rate limits based on anonymous client access, seems like it will hit a wall soon, may be worthwhile in parallel to start looking at authorized API access options on Horizon to address the scale of growing traffic in longer term. The concept has come up in [prior slack ](https://stellarfoundation.slack.com/archives/G01FUHTUQ8Z/p1646850924741439)here.

Two options could be:
 * move the high traffic endpoints behind AWS API Gateway and configure it with a [custom Lambda Authorizer](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-use-lambda-authorizer.html) and check for stellar-account signed JWT in http `Authorization` header and crosschecks with whitelist of accepted account ids from somewhere tbd 
 
 * Implement the same JWT authorization  routine as Horizon http middleware filter, it checks `Authorization` header for stellar-account signed JWT andcrosschecks with whitelist of accepted account ids from somewhere tbd
