### ISSUE TITLE
Missing toml in asset_stats

### ISSUE THREAD

**Issue by istrau2** [stellar/go#427]
Code: XIM
Issuing  Account: GBZ35ZJRIKJGYH5PBKLKOZ5L6EXCNTO7BKIL7DAVVDFQ2ODJEEHHJXIM

There is a home domain in the accounts table but no toml in the asset_stats table.

**Comment by bartekn** [comment]
As far as remember `/assets` endpoint (and `home_domain`) is updated when there's an operation involving the asset in the network. Updating it one account changes is not there yet: https://github.com/stellar/go/blob/master/services/horizon/internal/ingest/asset_stat.go#L43.

In short: send any operation that involves the asset (payment, offer, etc.) and it will update.

**Comment by istrau2** [comment]
Do you mean execute an operation involving the asset from the issuing account or just in general?  XIM has had  many ops executed after the home domain was  changed:  https://stellar.expert/explorer/public/asset/XIM-GBZ35ZJRIKJGYH5PBKLKOZ5L6EXCNTO7BKIL7DAVVDFQ2ODJEEHHJXIM

**Comment by bartekn** [comment]
I think this can be caused by https://github.com/stellar/go/pull/436 which is now blocked by https://github.com/stellar/go/issues/445 (and a fix for this: https://github.com/stellar/go/pull/446). I think this will be merged today and we will test it in testnet and master, then release a patch horizon build.

**Comment by Nathanofzion** [comment]
Hello istrau2 

Did you manage to resolve this issue as I'm having the same????

some help would much be appreciated
thanks

**Comment by bartekn** [comment]
The fix has been just deployed to horizon.stellar.org. Please check if it works after submitting a transaction involving the asset (it triggers stats update).

**Comment by istrau2** [comment]
@bartek we run our own horizon. What do we have to do?

**Comment by istrau2** [comment]
@bartekn Where can I find instructions on upgrading to the latest horizon?

**Comment by bartekn** [comment]
A new Horizon version that includes a fix for this issue has been released: https://github.com/stellar/go/releases/tag/horizon-v0.13.0 Please read release notes carefully.
