### ISSUE TITLE
FriendBot is not working

### ISSUE THREAD

**Issue by wooltar** [stellar/go#4287]
### What did you do?
Request to stellar  friendbot
https://friendbot.stellar.org/?addr=GDEJBLNFHKSTLO3N5CG6TJOI3Q4HUP6CYOC5P6LPVJYJUZYPIB64RLHE

response

```
{
"type": "https://stellar.org/horizon-errors/server_error",
"title": "Internal Server Error",
"status": 500,
"detail": "An error occurred while processing this request.  This is usually due to a bug within the server software.  Trying this request again may succeed if the bug is transient. Otherwise, please contact the system administrator."
}

```

### What did you expect to see?
I expect a 200 response

### What did you see instead?
a 500 response

**Comment by jacekn** [comment]
This happened because of a quarterly test network reset that was happening at the same time.
In the future you can refer to this website to check for ongoing maintenances or outages:
https://status.stellar.org/
