### ISSUE TITLE
ingest/ledgerbackend: change captive-core unit tests to use storage path in /tmp 

### ISSUE THREAD

**Issue by sreuland** [stellar/go#4290]
### What version are you using?

2.15.1

### What did you do?

`go test ./ingest/ledgerbackend/...`

### What did you expect to see?
no temporary test files generated during test execution in checked out repo paths

### What did you see instead?
several `./ingest/ledgerbackend/captive-core-xyz/` sub-folders were created in current checked out working directory

**Comment by leighmcculloch** [comment]
>change captive-core unit tests to cleanup storage path at finish

Is it possible to change the storage paths to a tmp directory, by using [os.MkdirTemp](https://pkg.go.dev/os#MkdirTemp)? So that tests aren't writing new files to the repo during run.

**Comment by sreuland** [comment]
yes, changed desired output to that behavior, probably should remove files at end of tests in any case.

**Comment by 2opremio** [comment]
Related: https://github.com/stellar/go/pull/3727/files  (it contains how some tests were updated to write to `/tmp` for the same reason).
