### ISSUE TITLE
gosdk StreamRange

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/go#43]
StreamEffectsRange
StreamTransactionsRange
etc
would allow you to fetch all the resources between two points. Useful if you want to calculate daily volume for example.

**Comment by bartekn** [comment]
I think we should use [`context`](https://golang.org/pkg/context) package instead. All `Stream*` functions will have another parameter `ctx context.Context`. Developers will be able to pass [`WithCancel`](https://golang.org/pkg/context/#WithCancel) contexts that will allow to cancel streaming objects. Then all you need to do is something like:
```go
ctx, cancel := context.WithCancel(context.Background())
handler := func(payment Payment) {
  // Do something with a payment
  if streamedAllPaymentsIWanted {
    cancel()
  }
}
go StreamPayments("G...", &Cursor("startingToken"), handler, ctx)
```
