### ISSUE TITLE
Offers result should return both amout of buying and selling

### ISSUE THREAD

**Issue by liangran** [stellar/go#434]
Horizon's reuslt will give amount and price. But the price is only 7 decimals. It is not enough for BTC offers. 

Example: User put a buy offer for BTC/CNY, the price is 64000. Horizon would return price 0.0000156, which equal 64102.

So, I suggest horizon return both amount of buying and selling. User could get the real price by calculation in such case.

**Comment by tomquisel** [comment]
Thanks for the report! Price is given as a ratio as well ([see here](https://www.stellar.org/developers/horizon/reference/endpoints/trades.html)), which should allow you to compute the price with complete accuracy.
