### ISSUE TITLE
Diagnose DB spike issue

### ISSUE THREAD

**Issue by jcx120** [stellar/go#4382]
Tasks:

- [x] Setup Staging environment (full history ingestion etc)
- [x] Reproduce Issue 
  * [x] Setup Staging
  * [x] Replay ALB Logs
- [ ] Analyze stg behavior while its replayed
- [x] Audit DB queries to verify timeout is happening

**Comment by sreuland** [comment]
@jcx120 , with the [incident document](https://docs.google.com/document/d/12lu10tspqk6aIyv_Zw57qoLOS-1jRaqjdcM8PfDRElk/edit#heading=h.iwpay4ltbuab) and the horizon [2.17.1/2.18.0 releases](https://github.com/stellar/go/releases) included optimizations based on findings, this ticket can likely be moved to done?

**Comment by jcx120** [comment]
Yes - updated to done. thanks
