### ISSUE TITLE
enable-ingestion-filtering does not reduce database

### ISSUE THREAD

**Issue by dpblnt** [stellar/go#4395]
### What version are you using?
5fa51492e3053aaf74ed5f0b57758f7f07a6aed7

### What did you do?
set HISTORY_RETENTION_COUNT=1
enabled enable-ingestion-filtering
whitelisted 35 accounts
ran horizon db reap
ran horizon serve

### What did you expect to see?
decrease postgresql db size from 30GB significantly
decrease postgresql insert activity caused by ingesting, significantly

### What did you see instead?
lots of info log in horizon dropping transaction, because it has nothing to do with the whitelisted accounts -- this is correct
but postgresql stays at 30GB

 public | account_filter_rules                   | table | horizon | permanent   | 32 kB      | 
 public | accounts                               | table | horizon | permanent   | 1193 MB    | 
 public | accounts_data                          | table | horizon | permanent   | 17 MB      | 
 public | accounts_signers                       | table | horizon | permanent   | 1049 MB    | 
 public | asset_filter_rules                     | table | horizon | permanent   | 16 kB      | 
 public | claimable_balances                     | table | horizon | permanent   | 6232 MB    | 
 public | exp_asset_stats                        | table | horizon | permanent   | 58 MB      | 
 public | gorp_migrations                        | table | horizon | permanent   | 16 kB      | 
 public | history_accounts                       | table | horizon | permanent   | 15 MB      | 
 public | history_assets                         | table | horizon | permanent   | 1224 kB    | 
 public | history_claimable_balances             | table | horizon | permanent   | 308 MB     | 
 public | history_effects                        | table | horizon | permanent   | 71 MB      | 
 public | history_ledgers                        | table | horizon | permanent   | 368 kB     | 
 public | history_liquidity_pools                | table | horizon | permanent   | 440 kB     | 
 public | history_operation_claimable_balances   | table | horizon | permanent   | 1464 kB    | 
 public | history_operation_liquidity_pools      | table | horizon | permanent   | 944 kB     | 
 public | history_operation_participants         | table | horizon | permanent   | 16 MB      | 
 public | history_operations                     | table | horizon | permanent   | 187 MB     | 
 public | history_trades                         | table | horizon | permanent   | 6448 kB    | 
 public | history_trades_60000                   | table | horizon | permanent   | 1448 kB    | 
 public | history_transaction_claimable_balances | table | horizon | permanent   | 1464 kB    | 
 public | history_transaction_liquidity_pools    | table | horizon | permanent   | 632 kB     | 
 public | history_transaction_participants       | table | horizon | permanent   | 11 MB      | 
 public | history_transactions                   | table | horizon | permanent   | 406 MB     | 
 public | key_value_store                        | table | horizon | permanent   | 56 kB      | 
 public | liquidity_pools                        | table | horizon | permanent   | 2480 kB    | 
 public | offers                                 | table | horizon | permanent   | 350 MB     | 
 public | trust_lines                            | table | horizon | permanent   | 5121 MB    | 
 public | txsub_results                          | table | horizon | permanent   | 8192 bytes |

**Comment by 2opremio** [comment]
BTW, I am assuming from your report that you ran `horizon serve` with the `HISTORY_RETENTION_COUNT=1`.

It would be helpful if you shared:
1. The exact sequence of commands you shared
2. How long was Horizon running in order to lead to that table storage
3. The table storage listings:
     *  before the manual reaping
     * after the manual reaping
     * after running Horizon

**Comment by dpblnt** [comment]
> 1. Ingestion filtering only filters the information in the history tables. The state tables (e.g. offers, trust_lines etc ...) won't be affected by it.

Is there no way to reduce those tables? 
Is it not possible to apply the filter to the state tables?
> 2. Ingestion filtering doesn't currently do automatic back-filling (i.e. it will only affect the current a current and future ingestions). Thus, existing history won't be changed unless you do a manual re-ingestion with filtering enabled. See [services/horizon/ingest/filtering: Backfill low level design #4267](https://github.com/stellar/go/issues/4267) . The `horizon db reap` should had reset the history tables, but it's worth confirming.

This node was running with history-retention-count=1 before, so there was not much history to remove by reap.
But I was hoping it would remove all history, except last ledger of whitelisted accounts, that would result in a 30 row history table.
> 3. You are setting `history-retention-count` to `1`. This tells Horizon to only retain the history of the last ledger and clashes, to a certain extend, with ingestion filtering (there is little point in filtering ingestion if you are only going to keep the history of the last ledger).

I was hoping to reduce postgresql traffic and the state tables.
Maybe I will change this to keep history of the whitelisted accounts only.
> 4. It's surprising that the tables occupy that much with `history-retention-count` set to `1`. How long did have you run Horizon with that setting? The reaper (responsible of enforcing the retention) kicks in every hour.

Not more then a week.  And I had a manual reap ran on it after I have set the whitelist.
It was started with history-retention-count=1 in the first place, since my use case does not need any history to operate.
This database was never less then 29GB.

**Comment by dpblnt** [comment]
> BTW, In the comment above, I am assuming from your report that you ran `horizon serve` with `HISTORY_RETENTION_COUNT=1` but now I am thinking that may not be the case.

This is correct, the command is `horizon serve` with `HISTORY_RETENTION_COUNT=1`

> 
> It would be helpful if you shared:
> 
> 1. The exact sequence of commands you ran

1. control-C in the running horizon screen
2. git fetch , switch to master, install horizon
3. `horizon serve`  -- to have a running horizon that can handle filtering
4. `curl -X PUT -H "Content-Type: application/json"  -d '@account_whitelist.json' http://127.0.0.1:8001/ingestion/filters/account` -- set the filter
5. control-C in horiozn screen
6. `horizon reap`
7. `horizon serve`

> 2. How long was Horizon running in order to lead to that table storage

less then a week
> 3. The table storage listings:
>    
>    * before the manual reaping

dont have the data
>    * after the manual reaping

dont have the data
>    * after running Horizon (which I guess is the one you shared)

correct
> 4. The accounts you are filtering (if they are not sensitive). The only history table with an oddly high storage is `history_claimable_balances`

I would not share the addresses

**Comment by 2opremio** [comment]
Thanks. Here are a couple of questions/conclusions

1. I don't understand why the size of the history tables in the DB are that large considering that reaper is enabled with a 1-ledger retention. Could you please check Horizon logs and see whether the reaper is kicking in?  Also could you check the table storage after VACUUMing the DB?
2. It doesn't really make sense to run ingestion filtering with a history retention of 1 ledger. 
3. Those table sizes (without reaping, which is likely not being executed) seem reasonable for running Horizon during a week. Note how most of the storage comes from state tables (which aren't filtered). It would be useful to see a graph with the DB growth throughout the week.

**Comment by dpblnt** [comment]
> 3. You are setting `history-retention-count` to `1`. This tells Horizon to only retain the history of the last ledger and clashes, to a certain extend, with ingestion filtering (there is little point in filtering ingestion if you are only going to keep the history of the last ledger).

Let me add, that I notice significant reduction in postgresql usage while horizon is serving and synced.
Since I added filtering only stellar-core and postgres autovacuum stresses disk IO.
I have no measured data to prove, but as I watch the node live, I'd say disk IO dropped by 90% overall on a synced serving horizon.

**Comment by 2opremio** [comment]
That's a fair point. I would be interested to understand the usecase of retaining just one ledger worth of history for a small amount of accounts. Could you elaborate?

**Comment by 2opremio** [comment]
> I'd say disk IO dropped by 90% overall

We also observed a ~90% reduction in storage with a small amount of accounts (the 100 more active during history)

**Comment by dpblnt** [comment]
> That's a fair point. I would be interested to understand the usecase of retaining just one ledger worth of history for a small amount of accounts. Could you elaborate?

I tried setting `history-retention-count` to 0, but the database started growing, so I concluded 1 is the minimum.
My trading bots do not need history to operate, only current balance and live offers.
So I whitelist only the accounts these bots use.
For statistics I download effects from any public full history node, like SDF, publicnode or lobstr.

**Comment by dpblnt** [comment]
public | history_claimable_balances             | table | horizon | permanent   | 310 MB  | 

select count(id) from history_claimable_balances;
 2777425

I don't think my accounts have that many claimable balances, and I'm sure I have not claimed that many.
Indeed that should have been cleared out, the node is running since, and I even had a manual reap on it.

**Comment by dpblnt** [comment]
horizon=# select * from history_claimable_balances limit 3;
 id |                           claimable_balance_id                           
----+--------------------------------------------------------------------------
  1 | 000000000100a9ab30c698aa11ae9fb8f7663b27cf125bdf9ea914dfdbd2b42121c1130b
  2 | 0000000001200f7504a87cad8e8038df6c906f3cd42f87a33a1839b379926c0c2f4a46d2
  3 | 0000000002d6527e1196c153c8f6b03d7fc5b1c7ceb87fd6615fd05720a054075f6444ea
(3 rows)

horizon=# select * from history_claimable_balances order by id desc limit 3;
   id    |                           claimable_balance_id                           
---------+--------------------------------------------------------------------------
 3318815 | 00000000fdc13bdbefc387aecf0c73b7a01756d3623eb04fa2a130cb3468cbf80b0ebb74
 3318814 | 00000000fce9113070cc09bab9cf270fd15ebe33a20a59ba32a19186cf1f0d95e436b8a9
 3318813 | 00000000f32d5e91e5a3a254540ca9ea73f49f2b63c6d5ec9c7e2b136591fdae95421fa9
(3 rows)

I think I have full history here

**Comment by 2opremio** [comment]
uhm, it could be that the reaper is not clearing out that table.

**Comment by 2opremio** [comment]
The other _big_ tables are `history_transactions` and `history_operations`. Could you check whether their size makes sense (I doubt it).

**Comment by dpblnt** [comment]
`horizon=> select count(id) from history_claimable_balances;`
Before `horizon db reap` : 3111861
After: 3111861

Here is the  debug
I can't find history_claimable_balances in it.

2022/05/23 21:23:45 Checking DB migrations...
2022/05/23 21:23:45 Preparing captive core...
INFO[2022-05-23T21:23:45.229+03:00] Initializing horizon...                       pid=13996
WARN[2022-05-23T21:23:45.230+03:00] could not load stellar-core info: http request errored: Get "http://localhost:11626/info": dial tcp 127.0.0.1:11626: connect: connection refused  pid=13996
INFO[2022-05-23T21:23:45.230+03:00] Initializing database...                      pid=13996
INFO[2022-05-23T21:23:45.230+03:00] Establishing database session for history     pid=13996
INFO[2022-05-23T21:23:45.231+03:00] Establishing database session for ingest      pid=13996
DEBU[2022-05-23T21:23:45.236+03:00] sql: get                                      args="[]" dur="926.001µs" pid=13996 sql="SELECT sequence, closed_at FROM history_ledgers ORDER BY sequence DESC LIMIT 1"
DEBU[2022-05-23T21:23:45.236+03:00] sql: get                                      args="[]" dur="242.9µs" pid=13996 sql="SELECT COALESCE(MIN(sequence), 0) FROM history_ledgers"
DEBU[2022-05-23T21:23:45.237+03:00] sql: get                                      args="[exp_ingest_last_ledger]" dur="475.91µs" pid=13996 sql="SELECT key_value_store.value FROM key_value_store WHERE key_value_store.key = $1"
INFO[2022-05-23T21:23:45.237+03:00] reaper: clearing                              end_ledger=40990170 pid=13996 start_ledger=40989678
DEBU[2022-05-23T21:23:45.237+03:00] sql: begin                                    pid=13996
DEBU[2022-05-23T21:23:45.255+03:00] sql: exec                                     args="[176049326483570688 176051443902447616]" dur=17.571135ms pid=13996 sql="DELETE FROM history_operation_participants WHERE history_operation_id >= $1 AND history_operation_id < $2"
DEBU[2022-05-23T21:23:45.255+03:00] sql: exec                                     args="[176049326483570688 176051443902447616]" dur="333.74µs" pid=13996 sql="DELETE FROM history_trades_60000 WHERE open_ledger_toid >= $1 AND open_ledger_toid < $2"
DEBU[2022-05-23T21:23:45.255+03:00] sql: exec                                     args="[176049326483570688 176051443902447616]" dur="135.14µs" pid=13996 sql="DELETE FROM history_transaction_claimable_balances WHERE history_transaction_id >= $1 AND history_transaction_id < $2"
DEBU[2022-05-23T21:23:45.256+03:00] sql: exec                                     args="[176049326483570688 176051443902447616]" dur="722.6µs" pid=13996 sql="DELETE FROM history_transaction_liquidity_pools WHERE history_transaction_id >= $1 AND history_transaction_id < $2"
DEBU[2022-05-23T21:23:45.257+03:00] sql: exec                                     args="[176049326483570688 176051443902447616]" dur=1.37505ms pid=13996 sql="DELETE FROM history_transactions WHERE id >= $1 AND id < $2"
DEBU[2022-05-23T21:23:45.258+03:00] sql: exec                                     args="[176049326483570688 176051443902447616]" dur="343.62µs" pid=13996 sql="DELETE FROM history_effects WHERE history_operation_id >= $1 AND history_operation_id < $2"
DEBU[2022-05-23T21:23:45.259+03:00] sql: exec                                     args="[176049326483570688 176051443902447616]" dur="794.291µs" pid=13996 sql="DELETE FROM history_ledgers WHERE id >= $1 AND id < $2"
DEBU[2022-05-23T21:23:45.259+03:00] sql: exec                                     args="[176049326483570688 176051443902447616]" dur="165.84µs" pid=13996 sql="DELETE FROM history_operation_claimable_balances WHERE history_operation_id >= $1 AND history_operation_id < $2"
DEBU[2022-05-23T21:23:45.260+03:00] sql: exec                                     args="[176049326483570688 176051443902447616]" dur="883.16µs" pid=13996 sql="DELETE FROM history_transaction_participants WHERE history_transaction_id >= $1 AND history_transaction_id < $2"
DEBU[2022-05-23T21:23:45.260+03:00] sql: exec                                     args="[176049326483570688 176051443902447616]" dur="744.65µs" pid=13996 sql="DELETE FROM history_operation_liquidity_pools WHERE history_operation_id >= $1 AND history_operation_id < $2"
DEBU[2022-05-23T21:23:45.262+03:00] sql: exec                                     args="[176049326483570688 176051443902447616]" dur=1.684881ms pid=13996 sql="DELETE FROM history_operations WHERE id >= $1 AND id < $2"
DEBU[2022-05-23T21:23:45.263+03:00] sql: exec                                     args="[176049326483570688 176051443902447616]" dur="804.51µs" pid=13996 sql="DELETE FROM history_trades WHERE history_operation_id >= $1 AND history_operation_id < $2"
DEBU[2022-05-23T21:23:45.265+03:00] sql: commit                                   pid=13996
DEBU[2022-05-23T21:23:46.232+03:00] sql: exec                                     args="[]" dur="218.93µs" pid=13996 sql="select 1"
DEBU[2022-05-23T21:23:46.235+03:00] sql: exec                                     args="[]" dur="213.65µs" pid=13996 sql="select 1"
INFO[2022-05-23T21:23:46.265+03:00] reaper succeeded                              new_elder=40990171 pid=13996

**Comment by 2opremio** [comment]
I created https://github.com/stellar/go/issues/4396

**Comment by dpblnt** [comment]
> How many transactions per hour do your accounts submit?
That depends on the market.
Let me put this another way:
`select distinct account from history_transactions;` gives 17 rows
`select distinct source_account  from history_operations;` gives 21 rows
So I think it's fine.

**Comment by dpblnt** [comment]
`select created_at from history_transactions  order by created_at limit 2;`
         created_at         
 2022-05-23 20:49:42.980061
 2022-05-23 20:49:54.341157

`select created_at from history_transactions  order by created_at desc limit 2;`
         created_at         
 2022-05-23 20:52:27.293029
 2022-05-23 20:52:15.727393

Looks good.

**Comment by dpblnt** [comment]
`select history_transactions.created_at `
`from history_operations `
`left join history_transactions on history_transactions.id = history_operations.transaction_id  `
`order by history_operations.id  `
`limit 2;`
         created_at         
 2022-05-23 20:49:42.980061
 2022-05-23 20:49:42.980061

`select history_transactions.created_at `
`from history_operations `
`left join history_transactions on history_transactions.id = history_operations.transaction_id  `
`order by history_operations.id `
`desc limit 2;`
         created_at         
 2022-05-23 21:04:24.585208
 2022-05-23 21:04:24.585208

This also looks good to me.

**Comment by 2opremio** [comment]
OK, good, I find it surprising that the storage listing showed:

```
public | history_transactions | table | horizon | permanent | 406 MB |
public | history_operations | table | horizon | permanent | 187 MB |
```

Just to wrap up, can you share the counts of those tables?

**Comment by dpblnt** [comment]
> Just to wrap up, can you share the counts of those tables?

I don't have that, 
but I have the current state
 public | history_operations                     | table | horizon | permanent   | 392 kB  | 
726
 public | history_transactions                   | table | horizon | permanent   | 6040 kB | 
148

**Comment by dpblnt** [comment]
Let me add that since the filtering enabled the node's SSD is usually at 5%, 
sometimes stellar-core pushes it up to 40%(for 1-2 seconds), and sometimes autovacuum to 100%(for 1-2 seconds).

Before filtering it was constantly between 90%-101%. 
So maybe database maintenance operations were lagging, but they can catch up now.

I also observed less timeouts/errors/warnings, and improved responsiveness from horizon, stellar-core and postgresql.

Overall I am very pleased with this improvement, and I think it is very rewarding to use this filtering wherever possible.

Thank you

**Comment by 2opremio** [comment]
> Overall I am very pleased with this improvement, and I think it is very rewarding to use this filtering wherever possible.

That's fantastic!

@dpblnt I am closing this (we will work on https://github.com/stellar/go/issues/4396 separately). Please let me know if you don't agree.
