### ISSUE TITLE
Horizon api find all trustees to an asset issuing account

### ISSUE THREAD

**Issue by tred456** [stellar/go#442]
I would like a feature to be able to find all accounts that trust an issuing account through the horizon api.

**Comment by seemaphalke** [comment]
@bartekn:   My team also need this need a feature where we can query all trust lines created for the assent issued along with its balances.

**Comment by tomerweller** [comment]
This feature is hard to implement in horizon's current form. 
Horizon reaches out to core's db for trustlines, but core does not have a index on trustlines by assets.

This comes back to a necessity to have horizon maintain it's own view on the ledger entries it's interested in tracking.

**Comment by IlyaShkapo** [comment]
Hello @tomquisel , we would like to have this feature as well. Our application needs to get the token (asset) distribution (the amount held by each wallet that holds tokens), so this endpoint would be very useful!

**Comment by tomquisel** [comment]
@IlyaShkapo thanks for highlighting this. We need to solve a larger architectural issue with Horizon before we take on this issue. We should be able to resolve this issue in the second half of 2019. Until then, hopefully you can find a work-around.

**Comment by orbitlens** [comment]
> However, (a) I don't know if there's any SLA attached to it 

That's strictly speaking is not a public API endpoint yet. Thus there is no SLA, the data format may (and will) be changed without preliminary notice. @IlyaShkapo drop me a message with details of your case, and we'll discuss it.

> (b) it ingests from history archives so information can be up to 5 minutes stale.

I found a way to overcome this limitation; the aggregated data will be available immediately once the ledger is closed. Currently working on the implementation, expect it to be ready by the end of April.

**Comment by IlyaShkapo** [comment]
Thank you @tomquisel , @tomerweller for the answer! 

We've already used this workaround for a while, but we faced several issues like interference between SQL users when they exceed connections in the pool. So, as for now, we have to deal with it for a time being, but we expect that this functionality will be available from Horizon API to remove a the dependency on the database and easily switch between nodes.

@orbitlens, we use this token distribution functionality to provide a possibility for the issuer to see and manage token holders. Could you be so kind as to drop me a message when you'll release the final version of Stellar Experts API for our consideration?

Thank you in advance!

**Comment by bartekn** [comment]
Make sure we have #1550 before we ship this. We will probably display trust line balances and this is a critical information for some apps.

**Comment by bartekn** [comment]
Closed in #1835.
