### ISSUE TITLE
Add metrics to Horizon Lite

### ISSUE THREAD

**Issue by Shaptic** [stellar/go#4451]
Epic: #4317

-----------------

As part of Phase 3, we need metrics to effectively compare it to Sunset Horizon. This issue covers a few metrics:

  * [ ] How long do indices take to build?
  * [ ] How long do indices take to update in real time?
  * [x] How old is a request, and, how does it correlate with how long servicing it takes?
  * [x] How long different parts of the on-the-fly ingestion take: 
    - [x] index lookup, 
    - [x] ledger downloads, 
    - [x] ingestion itself, etc.
  * [ ] #4528

Some of these should be exposed as Prometheus metrics on the new `/metrics` endpoint while others are part of the logs.

**Comment by sreuland** [comment]
I'm working on these metrics initially:

http request - Gauge
http request duration m/s - Gauge
number of of ledgers traversed in http request - Gauge

**Comment by Shaptic** [comment]
I'm closing this in favor of leaving the one remaining issue open, #4528
