### ISSUE TITLE
Document Captive Core - Disk Mode runbook

### ISSUE THREAD

**Issue by jcx120** [stellar/go#4467]
User documentation on recommended ways to configure and operate Captive Core SQL Lite disk mode:

Describe:
   - HW requirements: RAM, IOPS, CPU, Disk space requirements
   - How to configure/enable/start/stop
   - Typical behavior (expected startup times, restart process)
   - Troubleshooting 

For each scenario:
1. Forward-ingestion
2. Re-ingestion: (should disk mode even be used for this???)
  - what are the benchmarks and expected performance characteristics (ie: 10 workers take 350GB of disk, 16k IOPS etc, AWS machine type will finish re-ingestion of X in Y time)

**Comment by jcx120** [comment]
cc @sreuland

**Comment by sreuland** [comment]
@jcx120 , I've posted [draft of the on-disk runbook on confluence](https://stellarorg.atlassian.net/wiki/spaces/HOR/pages/4377477125/CC+on-disk+runbook)

I'll tune up per feedback, moving this ticket to review, thanks.

**Comment by mollykarcher** [comment]
I'm going to close this, as I think we'll cover the intent throughout https://github.com/orgs/stellar/projects/37/views/14
