### ISSUE TITLE
 exp/lighthorizon: consistent error formatting and semantics

### ISSUE THREAD

**Issue by sreuland** [stellar/go#4472]
### What problem does your feature solve?
* light horizon should re-use horizon `problems` package for overall consistent  error message formatting on web service endpoints. 
* error responses should have their http status code verified, correct 4XX or 5XX for the error context.
* For `/accounts/{account_id}/...` endpoints, if `account_id` doesn't exist in the underlying index, it returns empty response, is that acceptable or should it return 404, it's dependent on the exported index state, there is no current state of the network available that can provide the deterministic 'not found'

### What would you like to see?
Good error descriptions and correct 4XX or 5XX http status codes on error responses from web endpoints.

**Comment by Shaptic** [comment]
Closed by #4542.
