### ISSUE TITLE
exp/lighthorizon: Create pubnet indices for the MVP endpoints.

### ISSUE THREAD

**Issue by Shaptic** [stellar/go#4475]
Parent epic: #4317

------------

Our target endpoint is:

    GET /accounts/:id/transactions

So we need an index for each account that stores information about which ledgers the account was active in. Before we actually do this, there's an open question to answer: **What kind of indices do we make?**

1. Should they be checkpoint-based or ledger-based? There are trade-offs. **or**
2. Should we just create both? Then, we can compare both index size and latency differences.

-------

The index builder is ready for parallel construction, but it might not be perfectly ready for AWS Batch. There is some preliminary work to get both steps (map and reduce) "dockerized" and running on Batch.

**Comment by sreuland** [comment]
as @2opremio is going on holiday, I'm helping take over last step here of running a range on cloud to confirm indexes are built out. Initially will build for 07/01 - 07/31 to confirm.

**Comment by sreuland** [comment]
@Shaptic , looking into alternative k8s job for batch processing in lieu of AWS batch in short term. needs some adjustment on cluster to support JOB_COMPLETION_INDEX per https://github.com/stellar/ops/issues/1790

**Comment by sreuland** [comment]
after discussion with @Shaptic , the partial index data loaded onto s3 will suffice for mvp criteria, therefore will move this ticket to done, and carved out new ticket for follow-up on `reduce` performance, #4566
