### ISSUE TITLE
[BUG] Multi-signature unexpected failure (tx_bad_auth_extra while all signers are legit)

### ISSUE THREAD

**Issue by MisterTicot** [stellar/go#450]
## Description

When a transaction is signed by more legit signers than required, it will be rejected with 'tx_bad_auth_extra' error.

## Expected behavior

The transaction should be validated and each legit signer should be recorded into the blockchain; Or at least the transaction should get validaded. (to be done in Stellar horizon?)

The rationale for including all the signatures is that there's usage cases where it does matters who signed, beyond the fact that the threshold have been met. For instance: voting system, legal contracts, proof of presence. Those are commons use of blockchain systems that could easily and cheaply get supported by Stellar. (to be done in Stellar core?)

## Consequences

In the current state of affairs wallets/authenticator multisig implementors have to implement additional routines to remove valid signatures from transaction so that the transaction get validated.

## Steps to reproduce

```
StellarSdk.Network.useTestNetwork()
var server = new StellarSdk.Server('https://horizon-testnet.stellar.org')
var account1 = StellarSdk.Keypair.random()
var account2 = StellarSdk.Keypair.random()

function fundAccount (publicKey) {
  return new Promise(function (resolve, reject) {
    const xhr = new XMLHttpRequest()
    xhr.open('GET', 'https://friendbot.stellar.org/?addr=' + publicKey, true)
    xhr.send()
    xhr.onloadend = function () {
      if (xhr.readyState === 4 && xhr.status === 200) resolve()
      else reject()
    }
  })
}

console.log('Fund account1')
fundAccount(account1.publicKey())
  .then(function() {
    console.log('Fund account2')
    return fundAccount(account2.publicKey())
  })
  .then(function() {
    console.log('Set account2 as signer for account1')
    return server.loadAccount(account1.publicKey())
  })
  .then(function(account) {
    var tx = new StellarSdk.TransactionBuilder(account)
      .addOperation(StellarSdk.Operation.setOptions({
        signer: { weight: 1, ed25519PublicKey: account2.publicKey() }
      }))
      .build()
    tx.sign(account1)
    return server.submitTransaction(tx)
  })
  .then(function() {
    console.log('Sign a transaction with both account1 & account2 and send')
    return server.loadAccount(account1.publicKey())
  })
  .then(function(account) {
    console.log(account)
    var tx = new StellarSdk.TransactionBuilder(account)
      .addOperation(StellarSdk.Operation.setOptions({}))
      .build()
    tx.sign(account1)
    tx.sign(account2)
    return server.submitTransaction(tx)
  })
  .then(console.log)
  .catch(console.log)
```

**Comment by bartekn** [comment]
This can't be changed in this repository, move the issue to https://github.com/stellar/stellar-core.

**Comment by bartekn** [comment]
Horizon is not accepting any transactions, it's passing them to core. This this is solely connected to core.

**Comment by bartekn** [comment]
[deleted my previous comment]

I don't think horizon should modify submitted transactions in any way. I'll wait for others's opinion and then we can decide whether to reopen this or not.
