### ISSUE TITLE
Horizon Lite: Do a filtered horizon-cmp to check we get the right objects back

### ISSUE THREAD

**Issue by jcx120** [stellar/go#4511]
We can compare indices against the existing e.g. history_accounts table

**Comment by bartekn** [comment]
https://github.com/stellar/pipelines/pull/421 should help.

**Comment by sreuland** [comment]
@jcx120 , can. you provide a bit more details on acceptance criteria? i.e. do you expect an automated comparison report as part of CI build/integration test output or an ad-hoc tool invocation. What format of results, csv/txt file, assume it can follow the same text format as current horizom-cmp tool, one line per url request, etc?

**Comment by sreuland** [comment]
this is done by https://github.com/stellar/go/pull/4496
