### ISSUE TITLE
Design PostGres History DB export solution (Spike)

### ISSUE THREAD

**Issue by jcx120** [stellar/go#4517]
Given current challenges running a historical re-ingestion for larger historical periods (1 year+), with HW costs (RAM, Disk, IO) being out of reach for many, we want to explore a low-cost, easy solution to allow Horizon classic operators to catch up to history without running re-ingestion:

Given the majority of data density is from the last 2-4 years (2/18 to now):
<img width="786" alt="Screen Shot 2022-08-05 at 5 40 37 PM" src="https://user-images.githubusercontent.com/91218921/183226645-834fc5c7-6844-4997-8218-2cfc0e54131c.png">

Some thoughts:
 - Given the most valuable data is closer to now, should we work backwards and provide exports in X intervals depending on what is feasible to manage or 1 giant catch up file from genesis to July 2022?
 - What should be the maximum size of each incremental export?
 - What are robust export utilities we can leverage out of the box for Postgres?
 - How do we guarantee there are no gaps in data when performing incremental imports?

**Comment by mollykarcher** [comment]
Documented results of this spike - https://docs.google.com/document/d/1KhWYt9-v7UxqGtWOPWxjtM9SZkg0CKuhZGaTtnePfR8/edit#heading=h.5uel9fpp3rjq
