### ISSUE TITLE
Failure when submitting transactions to Horizon

### ISSUE THREAD

**Issue by panther93** [stellar/go#455]
> sql: Scan error on column index 5: xdr:decode: switch '1' is not valid for union 

I get this error when submitting the transaction envelope obtained from POST/builder to bridge. This gets timed-out but XLM gets transfered from source account to destination account. This also happens when submitting POST/payment to bridge. This error occurs in horizon!

**Comment by bartekn** [comment]
Can you post the transaction that is causing this error here?

**Comment by ckmakcesar** [comment]
+1... I am not using Bridge but also faced the same error on Horizon. But no transaction to share from me, as I am not sure how I triggered this. 

This stops Horizon to ingest new ledgers, and also disallows submitting new tx...

**Comment by panther93** [comment]
@bartekn 

> {
	"source": "GASCAIXHKGR5LQWYTTGEGWO2CIY3QFJSV544LZECUBDQGWNSSPMT3IZN",
	"sequence_number": "39059596525961218",
	"operations": [
		{
			"type": "payment",
			"body":{
				"source":"GASCAIXHKGR5LQWYTTGEGWO2CIY3QFJSV544LZECUBDQGWNSSPMT3IZN",
				"destination":"GBR55UE5WDDRQGQNPOQ6KJFGLCUI5OWGLPUL7HYHMWQARZOEVEQBOF7C",
				"amount": "2000"
			}
		}	
	],	
	"signers": ["SA4OMJ3C6LREJXRGWWP6QSM6PLKB2VM3HNGJ7EE6CSGQ3Z6NND5FFERW"]
}

this is the transaction details that i post to bridge(POST/builder). I got a transaction envelope as result which is `AAAAACQgIudRo9XC2JzMQ1naEjG4FTKvecXkgqBHA1myk9k9AAAAZACKxH8AAAACAAAAAAAAAAAAAAABAAAAAQAAAAAkICLnUaPVwticzENZ2hIxuBUyr3nF5IKgRwNZspPZPQAAAAEAAAAAY97QnbDHGBoNe6HlJKZYqI66xlvov58HZaAI5cSpIBcAAAAAAAAABKgXyAAAAAAAAAAAAbKT2T0AAABAGTeSY6GK3OB6bP4PniiBEYfpB8SyClE5/oX9HMi/+JcRRt6f0eaa3o/0MFSNuNF0WREZAK4sqDirC+78+HN7Dw==` !! While submitting this to horizon(POST/transactios) i got an internal server error in postman but transfer of xlm happened.

**Comment by bartekn** [comment]
What horizon version are you using exactly?

**Comment by ckmakcesar** [comment]
For me, I have been using private network and always build from the latest git Horizon. Would like to know which one @panther93 is using too.

**Comment by panther93** [comment]
My horizon version is v0.12.3
@bartekn @cesarmak

**Comment by bartekn** [comment]
@cesarmak @panther93 can you also post your stellar-core versions? I think we should implement this: https://github.com/stellar/go/issues/385 as horizon and core versions may be incompatible.

**Comment by cesarmak** [comment]
unfortunately I have rebuilt both Core and Horizon to restart everything.... will provide you the versions if this haunts again, thank you @bartekn

**Comment by panther93** [comment]
@bartekn @cesarmak 
stellar-core version - 0.9.2 !

**Comment by Dilidonka** [comment]
Same problem, 
stellar-core v9.2.0-213-g13d55680
horizon-v0.12.3

> INFO[0005] history db is empty, establishing base at ledger 18159789  pid=32104
> ERRO[0005] import session failed: failed to load transactions: select failed: sql: Scan error on column index 5: xdr:decode: switch '1' is not valid for union  pid=32104

**Comment by bartekn** [comment]
Should be fixed by: https://github.com/stellar/go/issues/385. Closing this issue for now.

**Comment by playersai** [comment]
what is meaning？“import session failed: failed to load transactions: select failed: sql: Scan error on column index 5: xdr:decode: switch '1' is not valid for union”

**Comment by cesarmak** [comment]
@playersai 
refer to https://github.com/stellar/go/issues/371

"Make sure you are compiling the prod branch", because some [dev] branches Horizon may not be compatible with some Stellar Core
