### ISSUE TITLE
`Historical DB Is Too Stale`

### ISSUE THREAD

**Issue by sokiaoba** [stellar/go#4550]
### What version are you using?

* stellar-core: v19.0.1
* horizon: v2.17.0

### What did you do?

I tried to send a transaction.

### What did you expect to see?

Transaction successfully accepted.

### What did you see instead?

Our self-hosting node temporarily returned `Historical DB Is Too Stale` error.

Additionally, I have a few question.

* I suppose this error is caused by node sync delay, is it correct? (When this error occured, our node was delaying for 50 blocks)
* If so, is there's a way to avoid node sync delay.

Thank you.

**Comment by mollykarcher** [comment]
Documentation on this error code is [here](https://developers.stellar.org/api/horizon/errors/http-status-codes/horizon-specific/stale-history). If you have persistent issues with your ingestion lag, please reopen with more detail on your setup. Better yet, join our [developer discord](https://discord.gg/XNEvNdGN) for help debugging your Horizon setup.
