### ISSUE TITLE
services/soroban-rpc: Support new XDR

### ISSUE THREAD

**Issue by paulbellamy** [stellar/go#4553]
Figure out how to build the new xdr into the go repo for this. We can keep existing services using the current xdr, but add a new `next` folder, and use it from the soroban-rpc service.

See: https://github.com/stellar/stellar-xdr-next for new XDR

New txn envelope and operation for ingestion
New ledger close metas, including SCVal types.

### Complication
In particular, figure out implications not including transactionresults anymore, as per [stellar-protocol/cap-0056.md at 2a3c395c4d838b616a4eda87a9ac4856f4ca5912 · stellar/stellar-protocol](https://github.com/stellar/stellar-protocol/blob/2a3c395c4d838b616a4eda87a9ac4856f4ca5912/core/cap-0056.md#stop-storing-transactionresults-in-archives) and comment
- should only impact places we use a TransactionResult without the TransactionMeta available. Which is probably nowhere? do a grep in the codebase

**Comment by paulbellamy** [comment]
Depends on https://github.com/stellar/go/issues/4558

**Comment by sreuland** [comment]
@2opremio @tamirms , is this version built as a horizon unstable package yet, if not, is it ok if to kick off a build for 'soroban' pkg, I'm working on #4559 , updates to quickstart image, it needs to pull deb pkg of horizon with xdr support so that soroban-rpc can use the horizon api.

**Comment by tamirms** [comment]
@sreuland sure, you can create a soroban build of horizon

**Comment by sreuland** [comment]
i used `0.0.0~soroban` version prefix, first build here [stellar-horizon_0.0.0~soroban-299](https://buildmeister-v3.stellar-ops.com/job/Horizon/job/stellar-horizon-package-builder-new/299/console)
