### ISSUE TITLE
services/soroban-rpc: simulateTransaction, sendTransaction, and getTransactionStatus methods

### ISSUE THREAD

**Issue by paulbellamy** [stellar/go#4555]
Depends on https://github.com/stellar/stellar-core/issues/3484, which is merged now.

This API should follow the soroban-rpc API Docs on Confluence, so that devs can swap out API server they are using `soroban-rpc`/`cli serve`/`horizon` seamlessly.

Compeleting this issue requires the following to be completed : 
- [x] https://github.com/stellar/go/issues/4593
- [x] https://github.com/stellar/go/issues/4594
- [x] https://github.com/stellar/go/issues/4595
- [x] #4637

**Comment by paulbellamy** [comment]
Depends on https://github.com/stellar/go/issues/4558

**Comment by sreuland** [comment]
@paulbellamy , can you confirm detail on expected outcome, for estimation, is this requesting a new web server to be created at new path of `/exp/soroban-rpc` and it will publish just the 3 soroban API endpoints mentioned?

**Comment by paulbellamy** [comment]
Using the existing web service from #4558. The interesting part here is this is the first one using a DB (for tracking transactionStatus), so that will need to be added.

**Comment by jcx120** [comment]
Assumption: For Meridian, this is to support a single session, local service (not remotely hosted, shared instance)
