### ISSUE TITLE
services/soroban-rpc: getAccount method v1 (sequence only)

### ISSUE THREAD

**Issue by paulbellamy** [stellar/go#4556]
Add a jsonrpc `getAccount` method. This is needed so that users can calculate the correct sequence number to use for transactions.

Note: the API docs on confluence also include `balances`. But they are more complicated and less critical, so I moved them to a separate issue: https://github.com/stellar/go/issues/4569

## getAccount

Fetch a minimal set of current info about a stellar account.

Needed to get the current sequence number, and balance for the account so you can build a successful transaction.

Parameters:

`<address>` - Address of the account to lookup, as a string

Returns:

- `<object>`
  - `id: <address>`
  - `sequence: <string>` - Current sequence number of the account
  - ~`balances: <array>` - Balances for the account (same format as in horizon).~

TODO: Do we need signers/flags/thresholds/etc?

**Comment by paulbellamy** [comment]
Depends on https://github.com/stellar/go/issues/4558

**Comment by sreuland** [comment]
initial scope - figure out how to get the account info from core's data, needs a design approach, ingest-like or other.
