### ISSUE TITLE
services/soroban-rpc: Quickstart packaging and distribution

### ISSUE THREAD

**Issue by paulbellamy** [stellar/go#4559]
Set up a fork (label?) of the Quickstart image which includes soroban-rpc, and captive-core. This will give devs something to run locally so they can use futurenet.

**Comment by paulbellamy** [comment]
@leighmcculloch suggests adding a flag, which launces soroban-rpc instead of horizon, and packaging them in the same image, to minimize forking.

**Comment by sreuland** [comment]
https://github.com/stellar/go/issues/4590 spike for including soroban-rpc and horizon in the image has overlap, may leverage the outcome here.

**Comment by sreuland** [comment]
this has dependency on quickstart to support connecting to `futurenet` https://github.com/stellar/quickstart/issues/368

**Comment by smac711** [comment]
@sreuland can we update the status of this issue? Would this be completed blocked from progressing until https://github.com/stellar/quickstart/issues/368 is completed?

**Comment by sreuland** [comment]
@smac711 , current status is in progress which is accurate, I've also assigned myself to  https://github.com/stellar/quickstart/issues/368 which is mostly a sub-task of this effort. 

one potential  blocker on this effort is dependency on when `futurenet` instance will be available, can't really configure the core cfg in quickstart for the new `--futurenet` network until that is known, I checked with @leighmcculloch , and for current dev effort will stub in a placeholder cfg to proceed overall - 
https://github.com/stellar/quickstart/issues/368#issuecomment-1251514065

**Comment by sreuland** [comment]
futurenet has been deployed, it's on earlier stable release of non-soroban core to start with - https://github.com/stellar/ops/issues/1832#issuecomment-1266045534, continuing to test quickstart against this instance to confirm when it will work, at which point should be able to close this.
