### ISSUE TITLE
Prototype - PG Export Utility

### ISSUE THREAD

**Issue by jcx120** [stellar/go#4563]
Test and verify a sample export job for the following scenario:

1. Incremental export (ie: monthly archives)
2. Full export (catchup from genesis)

A. For 1 - we can run a sample monthly exports for July and August 2022
- Try to complete a dump using pg_dump in archive mode for each month. Check the result file size and export speed
- Capture metadata (ledger range, checksum of archive, and date rate)
- Using a blank DB, re-import the dumps, and see how fast it takes, are there DB integrity issues?
- Research if it’s possible to export the raw structure of indexes so they don’t have to be created from an empty state
- Verify if it is possible to run Re-ingestion to catch up to present from latest pg_dump 
-- can fill gap be used?

B. For 2 - run a test export from genesis to July 31, 2022
- Can pg_dump support such a large export?
- How long would this take?
- What is the size? 
- Can monthly incremental exports be used to append to this?

Also-- 
- Consider publishing AWS RDS snapshots as an interim solution.
- Research a signing process in SDF.
- Research a verification process (ie: a simple checksum)

Note that beyond this test, we'll also leverage partners to host the export archives which can be solved by others.

**Comment by mollykarcher** [comment]
Closing this ticket, no longer relevant per output of this investigation - https://docs.google.com/document/d/1YETNALx5EzqZDNSVWzTfaK5Ogw84PsBlrt64nOr-Njg/edit#heading=h.ay7b6e6q2akx
