### ISSUE TITLE
Horizon Lite: Generate per-ledger indices for accounts

### ISSUE THREAD

**Issue by Shaptic** [stellar/go#4567]
We currently have per-checkpoint indices, but per-ledger ones would be useful for comparisons. 

We should use the single-process index builder to minimize deployment complexity until #4566 is resolved. You can achieve this via the `accounts_by_ledger` module on the indexer.

#### Acceptance Criteria

- [ ] Either (a) the existing S3 bucket is split into two folders or (b) a separate S3 bucket is created for these indices.
- [ ] 24 hours of indices on a recent, contiguous ledger range are on said S3 bucket/folder.
- [ ] A "live" indexer is continuously running on the rest of the above ledger range.

**Comment by paulbellamy** [comment]
Initially lets just generate these for the latest 7 days to make the generation easier to run.
