### ISSUE TITLE
services/horizon: [Spike] - analyze effects for assets moving to/from smart so classic balances stay accurate

### ISSUE THREAD

**Issue by paulbellamy** [stellar/go#4585]
Define expectations from client use cases up front a bit further, doc those, this will drive dev scope.

Part of the complication with assets on soroban, is that they can either be on the "classic" network or on the "smart" network. Contracts can move them back and forth between the two networks. Ideally we should update horizon to show both the accounts' smart and classic balances. But maybe a good (and easier) first step is to emit effects when assets are moved to/from, and the account balances can stay reflecting the "classic" balance only.

Acceptance Criteria: proposal doc on solution

**Comment by paulbellamy** [comment]
This is dependent on https://github.com/stellar/rs-soroban-env/issues/455

**Comment by sreuland** [comment]
this living doc on single/double balance may provide latest input on these evolving requirements ... - https://docs.google.com/document/d/1rSkkwtrZhwCJQ3LqvzJfF9vvofVwXSqbS5S5t-lq5OI/edit#heading=h.qaurejqpyz5b

**Comment by mollykarcher** [comment]
Closing as dup of https://github.com/stellar/go/issues/4722
