### ISSUE TITLE
Horizon Lite: deploy on separate AWS infra

### ISSUE THREAD

**Issue by sreuland** [stellar/go#4586]
Get horizon light stack running on separate AWS environment. 
This is dependent on bulk of infra being provided already by Ops - https://github.com/stellar/ops/issues/1818

Acceptance Criteria:
- [x] horizon light web, index(single/continuous), ledger exporter(continuous) deployed and running
- [x] clone the index and tx-meta s3 buckets over
- [x] horizon light web api ingress url is routed at new deployment.

**Comment by sreuland** [comment]
@Shaptic , I've deployed the horizon light stack([k8s manifests](https://github.com/stellar/go/tree/lighthorizon/exp/lighthorizon/build/k8s)) into horizon-lite-dev , updated the [MVP docs](https://stellarorg.atlassian.net/wiki/spaces/HOR/pages/4393730346/k8s+mvp+deployment) to reflect.

the 'forward/watch' processes are running starting from a ledger of today(42654178) , pointed at the sdf s3 buckets. and the web is up at https://lh-dev-pubnet.prototypes.kube001.services.stellar-ops.com/, once ready, we can take down the older mvp deployment in horizon-dev, and could then change the web url back to https://lighthorizon-pubnet.prototypes.kube001.services.stellar-ops.com/

there are two jobs running on k8s now to copy the horizon s3 buckets over to the sdf s3 buckets.

**Comment by Shaptic** [comment]
Awesome, looks great to me!
