### ISSUE TITLE
Text memo without content

### ISSUE THREAD

**Issue by Synesso** [stellar/go#459]
See https://horizon.stellar.org/transactions/3ce2aca2fed36da2faea31352c76c5e412348887a4c119b1e90de8d1b937396a

It has `"memo_type": "text"`, but no `"memo"` field. 

Is this valid? Should it be read as `"memo":""`?

**Comment by bartekn** [comment]
Duplicate https://github.com/stellar/go/issues/149.

Yes, it's a bug. If `memo_type` is `text` and `memo` field is empty it means it's an empty string.
