### ISSUE TITLE
services/soroban-rpc: Spike to try running horizon & soroban-rpc together in a quickstart container

### ISSUE THREAD

**Issue by paulbellamy** [stellar/go#4590]
As a short-term solution, having soroban-rpc proxy to a horizon server would be a quicker way for us to build `getAccount` functionality (https://github.com/stellar/go/issues/4556).

We want devs to be able to run a local standalone network (and run soroban-rpc locally pointed at futurenet). This will be done via the `quickstart` docker image.

However, I am concerned that both horizon and soroban-rpc running captive-core in the same docker image will conflict. The spike here is to see if that causes issues, or if it just works.

**Comment by leighmcculloch** [comment]
Is the quickstart container referencing http://github.com/stellar/quickstart? That image would be the ideal place to do this I think, and it already has all the foundation for running nodes, horizon, friendbot, captive-core, etc.

**Comment by leighmcculloch** [comment]
For an example for how to add a new service to the quickstart image, see this PR where we added friendbot recently: https://github.com/stellar/quickstart/commit/f7fe34c68af64f0d814e70c4929b4c3641a2e991

**Comment by sreuland** [comment]
@paulbellamy , wanted to confirm usage of `futurenet` and `standalone` mentioned in spec:

![Image](https://user-images.githubusercontent.com/10703845/190478681-de73ce32-812c-40cd-93ce-dd3c39827e83.png)

 they are referring to same instance of core/network hosted in quickstart image or different?

**Comment by leighmcculloch** [comment]
The quickstart image supports 3 networks out of the box today:
- `pubnet`, `testnet` – it connects to these networks as a node.
- `standalone` – it starts its own private network.

I imagine we will add another option similar to the first two that is `futurenet` or `sorobannet`.

soroban-rpc should be able to work with the others, like `standalone` too though.

**Comment by sreuland** [comment]
@leighmcculloch , thanks, I'll start looking into quickstart repo per your suggestions, I think have confirmed the expected outcome of the image/container on [#4554 chat](https://github.com/stellar/go/issues/4554#issuecomment-1248688425) to support the dev use case from there:

![Untitled-2022-09-15-0601](https://user-images.githubusercontent.com/10703845/190518631-1f0df6b1-7575-4aed-b7ab-6519c8a3398d.png)

**Comment by sreuland** [comment]
@leighmcculloch @paulbellamy @tamirms 

I've posted [PR draft with changes in quickstart](https://github.com/stellar/quickstart/pull/367) to modify the image and include [latest version of soroban-rpc](https://github.com/stellar/go/pull/4591) by @tamirms for getAccount, which dropped usage of captive core/ingest, instead using horizon api, the modified quickstart container looks stable, I put soroban-rpc behind quickstart's nginx, and was able to invoke `getAccount` and `getHealth`.

**Comment by sreuland** [comment]
@leighmcculloch @paulbellamy , wanted to check with you on how 'futurenet' network could be used with this image, can that be accomplished as-is with `--standalone` network and persistent-mode with `-v` docker host volume in order to provide custom core.cfg files, and later that can be automated in quickstart repo such as with a new network flag like `--futurenet` or does `--futurenet` network in quickstart need to be included now?

**Comment by leighmcculloch** [comment]
@sreuland We need to add a command line option that configures all of the applications to point to futurenet in the same way we already have the `--pubnet` and `--testnet` options.

**Comment by sreuland** [comment]
@leighmcculloch , thanks for confirm, do you know where I could obtain a sample of core.cfg file for `futurenet`? 

We want to allow captive core mode in the image `--enable-horizon-captive-core` to be allowed with `--futurenet` also correct? similar as it's allowed for `--standalone` network in the image.

**Comment by leighmcculloch** [comment]
Futurenet doesn't exist yet, and the command line options in the quickstart image need to be added for it. I don't think there is an issue for this work, so I just created: https://github.com/stellar/quickstart/issues/368.

**Comment by sreuland** [comment]
ok, the effort to support `--futurenet` will be done on #4559, the spike for confirming soroban-rpc with horizon api was completed here, closing this.
