### ISSUE TITLE
Horizon StreamOperations

### ISSUE THREAD

**Issue by smorano** [stellar/go#460]
Implementation of operations-all is missing in horizon client stream ?
https://github.com/stellar/go/blob/master/clients/horizon/main.go

https://www.stellar.org/developers/horizon/reference/endpoints/operations-all.html

**Comment by tomerweller** [comment]
streaming all operations in the go horizon client hasn't been implemented yet. Contributions are welcome :)

**Comment by ire-and-curses** [comment]
This has now been implemented in the new `horizonclient`: https://godoc.org/github.com/stellar/go/clients/horizonclient#Client.StreamOperations
