### ISSUE TITLE
horizon: support soroban InvokeHostFn xdr parsing

### ISSUE THREAD

**Issue by sreuland** [stellar/go#4604]
sub-task from https://github.com/stellar/go/issues/4600

ensure correct parsing of new soroban InvokeHostFn xdr usages

* for api json resource model of InvokeHostFunctionOp, use plain, xdr-base64 encoded serialization of top level elements.
* demonstrate integration test of InvokeHostFn:CreateContract
  * CreateContract with `create_contract_from_ed25519` 
* include latest xdr updates related to soroban contract from [stellar-xdr-next)](https://github.com/stellar/stellar-xdr-next)

**Comment by sreuland** [comment]
@2opremio @paulbellamy , does OperationTypeInvokeHostFunction need to emit effects for initial soroban use cases or can we leave that as no-op?

**Comment by sreuland** [comment]
confirmed with @paulbellamy , can skip effects wire up here, it's carved out to separate effort - https://github.com/stellar/go/issues/4585

**Comment by sreuland** [comment]
@paulbellamy @2opremio , I'm adding the `Details` json part for history operation of InvokeHostFunction, and looking at how to serialize the ScVals, I noticed a long conversation on canonical JSON representation of ScVal on  [soroban-cli #22 ](https://github.com/stellar/soroban-cli/issues/22), what was the outcome on that, is there a implementation in cli or elsewhere of JSON model that I could reference for ScVal's here in horizon? 

Or any other preferred approach to serialize them for horizon's concern, lmk, I was naively going to just use `json.Marshal(scVal)`

**Comment by paulbellamy** [comment]
Re: effects, not for now. There is https://github.com/stellar/go/issues/4585 to add some specifically for the token contract, but those aren't designed yet.

**Comment by paulbellamy** [comment]
I would just xdr-base64 encode the ScVals. That's fine. Any JSON representation is either super verbose, or ambiguous. So not worth it. Better to send xdr scvals, and let clients parse it from there.

**Comment by leighmcculloch** [comment]
@sreuland I don't think we get enough value out of a stable canonical or even Horizon specific JSON representation of the ScVec of args for the invocation. I think it is okay at this point to base64 XDR encode the ScVec and have it as a single entry.

**Comment by sreuland** [comment]
got it, will keep scope to that, thanks for responses!

**Comment by sreuland** [comment]
I pushed out other non-critical path test coverage of `create_contract_from_account` and `InvokeHostFunction:HostFunctionHostFnCall` to follow-on ticket - #4617

**Comment by sreuland** [comment]
bringing this back to 'in progress' to pull in the newest soroban xdr updates from 9/26 on [https://github.com/stellar/stellar-xdr-next](stellar-xdr-next)), should just be an xdr gen change.

**Comment by sreuland** [comment]
back to in progress to update the core version and verify the integration tests still work
