### ISSUE TITLE
Could not complete "horizon db init" exec failed: pq: unrecognized configuration parameter "lock_timeout"

### ISSUE THREAD

**Issue by sivaji** [stellar/go#461]
I get the following error on running the command -  horizon db init. My Horizon install is compiled from the source for CentOS 7 following https://www.stellar.org/developers/horizon/reference/admin.html . 

> ERRO[0000] exec failed: pq: unrecognized configuration parameter "lock_timeout"  pid=8107

I understand this is related to the lower version of Postgres on my server. I have a bunch of issues with upgrading to Postgres 9.3 or above. I tried hard to edit the SQL schema files that horizon db init uses. But all my attempt ends in futile. 

I even ran,
> "$ find ./ -type f -exec sed -i 's/SET lock_timeout = 0;/;/g' {} \;" 

from horizon repository before running 

> "$ go install github.com/stellar/go/services/horizon" .

I would like to know what changes to horizon source code (I'm using devel branch) would help me get rid of "lock_timeout" error without having to upgrade the Postgres.

**Comment by bartekn** [comment]
Horizon [requires](https://github.com/stellar/go/blob/master/services/horizon/internal/docs/reference/admin.md#prerequisites) Postgres >= 9.3. It's possible that other parts of the system won't work as expected, even if you manage to pass `horizon db init` command.

**Comment by sivaji** [comment]
Thank you for the swift reply, I wish https://galactictalk.org/d/20-setting-up-stellar-core-on-centos-7 had that requirements explicitly mentioned. I will re-install Stellar core at least the Postgres part.
