### ISSUE TITLE
horizon: support TxMetaV3

### ISSUE THREAD

**Issue by sreuland** [stellar/go#4610]
Update ingestion and the transaction endpoint to provide TransactionMetaV3 (which provides the contract events). Otherwise Horizon can't provide event information to soroban-rpc.

Refer to #4600 for parent issue and context of overall horizon support ites.

**Comment by bartekn** [comment]
It's in progress: https://github.com/stellar/go/pull/4606. Currently blocked due to Stellar-Core bug in meta v3 for some failed txs.
