### ISSUE TITLE
horizon: derisk/confirm alternative for TransactionResults not in Archives

### ISSUE THREAD

**Issue by sreuland** [stellar/go#4611]
Deal with the fact that [TransactionResults won't be present in the archives](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0056.md#stop-storing-transactionresults-in-archives) 

Refer to #4600 for parent ticket and larger horizon scope of this change.

**Comment by tsachiherman** [comment]
According to @sisuresh, `TransactionResult` will end up in the archives, therefore, this task is not needed for meridian.

**Comment by tsachiherman** [comment]
I believe that we can close this one.

**Comment by sreuland** [comment]
@tsachiherman , based on prior feedback, am closing this ticket as obsoleted, no work was needed.
