### ISSUE TITLE
Use the CLI to deploy contract

### ISSUE THREAD

**Issue by tsachiherman** [stellar/go#4628]
## Use the CLI to deploy contract

Use Soroban Examples, Hello world : sample from soroban-example, addi32 contract
deploy contract to standalone network on quickstart

**Comment by sreuland** [comment]
confirmed this works, 

pre-req:  need to have latest rust/cargo build environment, on mac, got it from rustup 1.25.1, `rustup update` triggered to get latest rustc 1.64.0

deployed a sample 'add 2 numbers' [wasm contract file that is in go repo as part of horizon tests](https://github.com/stellar/go/blob/soroban-xdr-next/services/horizon/internal/integration/testdata/example_add_i32.wasm)
```
$ git clone https://github.com/stellar/soroban-cli.git; cd soroban-cli
$ cargo install --path .
$ docker pull stellar/quickstart:pr-373-soroban-dev
$ docker run --platform linux/amd64 --rm -it -p "8000:8000" --name stellar stellar/quickstart:pr-373-soroban-dev --standalone --enable-soroban-rpc --protocol-version 20

$ SOROBAN_SECRET_KEY=xxx soroban-cli deploy --rpc-server-url="http://localhost:8000/soroban/rpc" --network-passphrase="Standalone Network ; February 2017" --wasm /path/to/stellar/go/services/horizon/internal/integration/testdata/example_add_i32.wasm

Contract ID: 89fa5fb9b80fb6272cd651a592827ef1e9709aac4b23ec760379f3769edb70b6
success
```
