### ISSUE TITLE
"deb https://apt.stellar.org/ focal stable" not finding Horizon v 2.21

### ISSUE THREAD

**Issue by jcx120** [stellar/go#4631]
### What version are you using?
Horizon 2.20

### What did you do?

`deb https://apt.stellar.org/ focal stable`
no longer  seems to work for upgrading Horizon to latest (v2.21) where it did before. for previous versions

Context: Once we promote a release to stable it should show up in that repo, (Ops maintains this process) but this is one of the last steps likely that might have gotten skipped during last Horizon deploy.

`apt-cache policy stellar-horizon` did not work

> stellar-horizon:
>   Installed: 2.20.0-296
>   Candidate: 2.20.0-296
>   Version table:
>  *** 2.20.0-296 100
>         100 /var/lib/dpkg/status

### What did you expect to see?
The 2.21 version

### What did you see instead?
Still the 2.20 version

**Comment by Shaptic** [comment]
I'm not seeing a problem, after following the instructions [here](https://github.com/stellar/packages/blob/master/docs/adding-the-sdf-stable-repository-to-your-system.md#adding-the-bleeding-edge-unstable-repository) and running `pt update` on a fresh Ubuntu container. 

```
# apt update
...
Get:6 https://apt.stellar.org focal/stable amd64 Packages [15.5 kB]
...

# apt search stellar-horizon
[...]
stellar-horizon/focal 2.21.0-298 amd64
  Horizon is the client facing API server for the Stellar ecosystem.
```
