### ISSUE TITLE
Doc for Quickstart (End Users setup and how to run) - Meridian

### ISSUE THREAD

**Issue by jcx120** [stellar/go#4645]
Documentation for first batch of Meridian users:

1. How to get the Quickstart package
2. How to setup / configure
3. How to run it for the first time (ie, run a minimal set of steps to)
--  verify connectivity to Futurenet
--  minimal "hello world" type of send/recieve txn to verify e2e is working
5. Common issues / troubleshooting 

For now, let's place this content as a new page under a new `Network Testing` section in this repo:
https://github.com/stellar/soroban-docs/tree/main/docs

**Comment by sreuland** [comment]
for reference, there is a brief section on [quickstart README](https://github.com/stellar/quickstart/blob/4559_packaging_soroban/README.md#soroban-development) that highlights steps to use
