### ISSUE TITLE
RPC E2E test for Futurenet 

### ISSUE THREAD

**Issue by jcx120** [stellar/go#4646]
## Conduct CLI end to end testing for the core soroban support against `Futurenet.`
(This is an analog to https://github.com/stellar/go/issues/4623 for Futurenet)

Sub tasks : 
- [x] Run the existing integration tests against the updated quickstart docker to see if any breaking changes were introduced. 
https://github.com/stellar/go/issues/4647
- [x] Use the CLI to deploy contract. 
https://github.com/stellar/go/issues/4648
  - Use Soroban Examples, Hello world : sample from soroban-example, addi32 contract
- [ ] Invoke a contract using JS 
https://github.com/stellar/go/issues/4649
- [x] Invoke a contract using Soroban CLI
https://github.com/stellar/go/issues/4650
- [x] Use the CLI to create token 
https://github.com/stellar/go/issues/4651

for anyone doing e2e tasks against `futurenet`, the soroban docker image of quickstart to run for this is:
```
docker pull stellar stellar/quickstart:pr-373-soroban-dev
docker run --platform linux/amd64 --rm -it -p "8000:8000" --name stellar stellar stellar/quickstart:pr-373-soroban-dev --futurenet --enable-soroban-rpc --protocol-version 20

```

any test must create a new account on Futurenet first to use as source account:
1. First generate a KeyPair using Laboratory's page and save the pub/private key - https://laboratory.stellar.org/#account-creator
2. `curl --location --request GET 'https://friendbot-futurenet.stellar.org?addr=<pub key>'` 

for reference on hosted futurenet deployment configuration, here is the ops ticket that performed it - https://github.com/stellar/ops/issues/1832 

soroban-rpc service URL entrypoint will be reachable from the locally run container at:
`http://localhost:8000/soroban/rpc`

[Quickstart soroban dev readme](https://github.com/stellar/quickstart/blob/4559_packaging_soroban/README.md#soroban-dev)

**Comment by sreuland** [comment]
@jcx120 , after fix to horizon ingestion https://github.com/stellar/go/pull/4653 was pushed, I reran these futurenet tests, and they passed, steps to reproduce each test are on the sub-tickets. the only one I didn't retest was #4649 for 'invoke contract using JS on futurenet'  as it's [more complex, left comment](https://github.com/stellar/go/issues/4649#issuecomment-1272090571)
