### ISSUE TITLE
query for all asset holders in a given timestamp

### ISSUE THREAD

**Issue by tomerweller** [stellar/go#465]
This is a requirement by many asset issuers. Specifically for the purpose of dividend distributions.

It's currently doable but requires catching up stellar-core to a specific ledger and querying the `trustlines` table directly.

**Comment by ire-and-curses** [comment]
Seems like this is a filter on #442?

**Comment by bartekn** [comment]
Similar but #442 gives you data for the latest ledger only.

**Comment by abuiles** [comment]
@ericstamper @bartekn @tomerweller shouldn't this be something we answer in a BI system (like Hubble) rather than Horizon?

**Comment by ire-and-curses** [comment]
@abuiles I think that depends. If Hubble is i) publically available and ii) accessible as needed for this use case, then it could work. But Hubble may not have an API, be public, or be hosted with sufficient reliability. Horizon is still the de-facto gateway for programmatic queries about the network.

**Comment by tomerweller** [comment]
I don't know anything about hubble but this feature feels more like business logic than business intelligence.

**Comment by ire-and-curses** [comment]
We discussed this within the Horizon team today. One concern is finding the right boundary for Horizon (there are many of these sorts of historical query that could be interesting). Another is implementation - this is a lot of data to work with.

We're going to defer this for now. There are basically three options for future implementation:

1. Write an ingestion plug-in to do this
2. Hubble becomes available to answer this
3. We add it to Horizon proper

The first two options are maturing rapidly, so by the end of the year we should know which way to go.

**Comment by bartekn** [comment]
This can be done using the ingestion package right now. I don't think we will add this to Horizon because of storage requirements.

```go
package main

import (
	"context"
	"fmt"
	"io"

	"github.com/stellar/go/exp/ingest/adapters"
	"github.com/stellar/go/support/historyarchive"
	"github.com/stellar/go/xdr"
)

func main() {
	archive, err := historyarchive.Connect(
		"http://s3-eu-west-1.amazonaws.com/history.stellar.org/prd/core-live/core_live_001",
		historyarchive.ConnectOptions{Context: context.Background()},
	)
	if err != nil {
		panic(err)
	}

	historyAdapter := adapters.MakeHistoryArchiveAdapter(archive)
	changeReader, err := historyAdapter.GetState(context.Background(), 63, 3)
	if err != nil {
		panic(err)
	}
	defer changeReader.Close()

	i := 0

	for {
		i++
		if i%100000 == 0 {
			fmt.Println("Processed", i, "entries")
		}

		change, err := changeReader.Read()
		if err == io.EOF {
			break
		}
		if err != nil {
			panic(err)
		}

		if change.Type == xdr.LedgerEntryTypeTrustline {
			trustline := change.Post.Data.TrustLine
			fmt.Println(trustline.AccountId.Address(), trustline.Balance)
		}
	}
}
```
