### ISSUE TITLE
Use the CLI to create token on Futurenet

### ISSUE THREAD

**Issue by jcx120** [stellar/go#4651]
this is for retesting connected to Futurenet
(Reference for standalone network: https://github.com/stellar/go/issues/4630)

**Comment by tsachiherman** [comment]
Isn't this issue and https://github.com/stellar/soroban-cli/issues/42 are dup ?

**Comment by jcx120** [comment]
Yes, I believe they are the same but #42 was closed without Futurenet testing. We can re-open #42 to cover Futurenet / close this one or vice versa.

**Comment by jcx120** [comment]
Actually closing this since #42 still open.

**Comment by sreuland** [comment]
the scope seems different, this is just for qa tests against cli on futurenet, not behavior of cli for create token which the other seems to be more focused on, seems easier to track this if it's open and contributing to e2e #4646 scope

**Comment by sreuland** [comment]
Prereq:

1. created account keypair using Laboratory Web - https://laboratory.stellar.org/#account-creator:
```
Public Key	GBVTI25S2H6UHPOJLVAJQVLWQLGKQATRWKO2UQXAXY627CL5E4OUXE3I
Secret Key	SCO2XXDYOZ4RKJ2VZOEGUMPOCX7SEAP2VP5Z74YZZWR3UCJDBS34S734
```

2. funded account on Futurenet:
```
curl --location --request GET 'https://friendbot-futurenet.stellar.org?addr=GBVTI25S2H6UHPOJLVAJQVLWQLGKQATRWKO2UQXAXY627CL5E4OUXE3I'
```

3. need to have latest rust/cargo build environment, on mac, got it from rustup 1.25.1, rustup update triggered to get latest rustc 1.64.0

4. build latest cli
```
$ $(git clone https://github.com/stellar/soroban-cli.git; cd ./soroban-cli; git checkout v0.1.0;cargo install --path .)
```

5. run soroban quickstart docker image
```
# DIGEST:sha256:4447d440a432c3b4fe301f9116fb6065d91b120014db50a5658933d90cfedfcf
$ docker pull stellar/quickstart:pr-373-soroban-dev
$ docker run --platform linux/amd64 --rm -it -p "8000:8000" --name stellar stellar/quickstart:pr-373-soroban-dev --futurenet --enable-soroban-rpc --protocol-version 20

```


the test:
```
soroban token create --rpc-url="http://localhost:8000/soroban/rpc" --network-passphrase="Test SDF Future Network ; October 2022" --name "exampletoken" --symbol "EXT" --decimal 2 --secret-key= SCO2XXDYOZ4RKJ2VZOEGUMPOCX7SEAP2VP5Z74YZZWR3UCJDBS34S734
```

expected response:
```
success
success
<token contract id>

```
