### ISSUE TITLE
Horizon offers output wrong for amount/proice in buying

### ISSUE THREAD

**Issue by usser0134** [stellar/go#4665]
I'm trying to explore buying offers of a specific asset and get buying prices/.. But horizon returns totally wrong everything.

What horizon returns?
https://horizon.stellar.org/offers?buying_asset_type=credit_alphanum4&buying_asset_issuer=GASGTOADMEWP6AWWH7Q52LA3EOWBCHDNXIIPMUHQ4ORSEBZZBSA7YFPF&buying_asset_code=HBAR&limit=3

What should return ?
https://lobstr.co/trade/HBAR:GASGTOADMEWP6AWWH7Q52LA3EOWBCHDNXIIPMUHQ4ORSEBZZBSA7YFPF
Look at buying prices in lobstr and look on horizon..

Is this a bug? How i can get buying prices?

**Comment by mollykarcher** [comment]
These requests are now outdated, so it's not possible to tell anymore what part of the data you thought was wrong. Please reopen with more detail and repro steps if your issue persists!
