### ISSUE TITLE
servies/horizon: Deprecate stellar/horizon docker image

### ISSUE THREAD

**Issue by 2opremio** [stellar/go#4669]
The official docker image is [`stellar/stellar-horizon`](https://hub.docker.com/r/stellar/stellar-horizon) docker image.

However, we used to push [`stellar/horizon`](https://hub.docker.com/r/stellar/horizon/) (note the lack of the `stellar-` prefix), which still exists.

`stellar/horizon` is outdated and shouldn't be used anymore, however, it's easy for users to be confused.

We should deprecate `stellar/horizon`. The plan (discussed offline with @jacekn ) is to:

1. Push a new `stellar/horizon` image showing a deprecation warning when invoking the `horizon` command
2. After 6 months, completely delete the `stellar/horizon` image

**Comment by urvisavla** [comment]
Looks like we've already added the warning that this image will be removed. 
```
urvisavla ~  $ docker run --platform linux/amd64 stellar/horizon  
WARNING: The stellar/horizon Docker image is outdated deprecated, please use stellar/stellar-horizon instead.
WARNING: The stellar/horizon image will be removed from DockerHub on March 27 2023.

```

@jacekn What is the process for submitting the image for deletion ?

**Comment by urvisavla** [comment]
The image has been deleted. Closing the issue.
