### ISSUE TITLE
Add to documentation the payment types available in the payment for account endpoint

### ISSUE THREAD

**Issue by cecilygardner** [stellar/go#467]
It could be helpful to articulate the types of payments available within the payment endpoint (ex: type = payment, type = create_account). I noted it's not available in the documentation about the payments for account endpoint (https://www.stellar.org/developers/horizon/reference/endpoints/payments-for-account.html) or the operations page (https://www.stellar.org/developers/horizon/reference/resources/operation.html#payment). I found them listed here https://github.com/stellar/go/blob/29a41f2de1ce8cd38f45e7097cdb693c1c898862/services/horizon/internal/db2/history/operation.go#L111-L119 but only after clicking through to a variety of locations.

**Comment by bartekn** [comment]
Fixed in https://github.com/stellar/go/pull/528
