### ISSUE TITLE
Soroban RPC API: getContractData

### ISSUE THREAD

**Issue by jcx120** [stellar/go#4675]
Provide an endpoint for Developers to access meta data about a deployed Contract in the RPC

- [ ] Design the API Spec, get feedback. Considerations:
 - returns: source account, transaction, no of invocations calls, wasm build information
 - Should this be in Horizon as well or only in RPC?
- [ ] Implement the method
- [ ] Implement integration test coverage

Considerations:
 - Future: Should we provide in Horizon, a /Contracts/ endpoint for finding data about all contracts deployed and also by contract account owner (or by contract id)?

References:
Submitted by community: https://github.com/stellar/go/issues/4668

**Comment by jcx120** [comment]
Looks like this is already implemented? @paulbellamy

**Comment by 2opremio** [comment]
yep!
