### ISSUE TITLE
[Prototype/Spike] Embed Env Rust Host into Go for Preflight

### ISSUE THREAD

**Issue by jcx120** [stellar/go#4677]
Build a rapid prototype on the embedded Env Host solution into Go for the preflight rpc [refactor](https://github.com/stellar/go/issues/4673) epic. Time box to 1 week. 

Steps:
- Import https://github.com/stellar/rs-soroban-env into the Go world
- Generate a wasm artifact and calling it from Go (via CGO etc)
- Using Rust's FFI to call the library from Go https://github.com/mediremi/rust-plus-golang 

Understand:
    - Ease of use
    - Performance
    - Debuggability (understand error chain)
    - Any gotcha’s / tradeoff's
    - Maturity, future roadmap for support/adoption of supporting tools (CGO etc)
    - Scaling concerns (can this work in a horizontally scaled, multi-tenant IaaS deployment for infra providers)

**Comment by 2opremio** [comment]
Happy to take this one up!

**Comment by paulbellamy** [comment]
I'd suggest trying it with a contract which uses storage (not just a hello-world), so we exercise the host functions. But the prototype doesn't need to load the contract data from on-chain for this.

**Comment by jcx120** [comment]
Consider compiling Rust as a static lib and linking against go.
