### ISSUE TITLE
exp/soroban-rpc: relocate soroban-rpc to soroban-tools repository

### ISSUE THREAD

**Issue by sreuland** [stellar/go#4679]
epic - https://github.com/stellar/go/issues/4672

### What would you like to see?
soroban rpc code is moved into it's own repo:

- [x] Rename soroban-cli repo to soroban-tools https://github.com/stellar/terraform/pull/1002
- [x] Copy Soroban RPC to soroban-CLI repo ( will be deleted from go repository at a later stage ) https://github.com/stellar/soroban-cli/pull/251
- [x] Add go repository as a dependency to soroban-rpc. https://github.com/stellar/soroban-cli/pull/251
  - [x] use go.mod to point to go repository
- [ ] Update Jenkins [soroban-package-builder](https://buildmeister-v3.stellar-ops.com/job/Horizon/job/soroban-package-builder/) to reference new soroban rpc code location
- [ ] Verify quickstart  [soroban-dev](https://github.com/stellar/quickstart/blob/master/Dockerfile.soroban-dev) image still works with latest build of Jenkins pkg
- [ ] Remove soroban-rpc from go repo

### What alternatives are there?
leave in mono-repo, rely on new tags to reference versions.

**Comment by paulbellamy** [comment]
What are the issues that this is attempting to solve?

**Comment by tomerweller** [comment]
> What are the issues that this is attempting to solve?

I'd like to reiterate this @paulbellamy's question. @tsachiherman ?

**Comment by tsachiherman** [comment]
> > What are the issues that this is attempting to solve?
> 
> I'd like to reiterate @paulbellamy's question. @tsachiherman ?

Moving the soroban-rpc to the same place as the soroban-cli addresses several issues:
- the components are now gurenteed to be synchronized.
- the components can be tested to work together. 
- the soroban-rpc is going to use the soroban-env-host to run simulateTransaction. That's a rust package that would need to be wrapped. Ideally, it would live where we already have other rust components.
- less error prone : the soroban tools are all in one repository.
