### ISSUE TITLE
Uninformative Error Reporting

### ISSUE THREAD

**Issue by glowkeeper** [stellar/go#468]
Error reporting in Stellar is unhelpful; all errors get reported under the catchall '_BadResponseError: Transaction submission failed. Server responded: 400 Bad Request_', rather than something more specific (helpful), such as '_The receiving account doesn't have a trust line to the sending account_' or, '_the issuing account is locked_' etc.

**Comment by michaelran16** [comment]
@glowkeeper could you give a list of example of such misleading errors in Horizon, so we can fix accordingly? 
You have already listed 2: 

1. no trustline to sending account
2. issuing account is locked

**Comment by bartekn** [comment]
Response body returned by Horizon contains error codes for each [operation](https://www.stellar.org/developers/guides/concepts/list-of-operations.html) or [transaction](https://www.stellar.org/developers/guides/concepts/transactions.html#possible-errors).

**Comment by glowkeeper** [comment]
Ah, forgive me - is this where (for instance)?

_transaction: "tx_bad_auth"_
