### ISSUE TITLE
exp/soroban-rpc: finish soroban-rpc code refactor, remove from this repo

### ISSUE THREAD

**Issue by sreuland** [stellar/go#4680]
epic - https://github.com/stellar/go/issues/4672

depends on: https://github.com/stellar/go/issues/4679
depends on: https://github.com/stellar/soroban-cli/issues/240
depends on: https://github.com/stellar/soroban-cli/issues/241

### What would you like to see?
after all refactoring with cli and soroban-rpc is complete in dependent tasks, delete the soroban-rpc sub-path from the go repository.

**Comment by paulbellamy** [comment]
Seems like this is abandoning the go monorepo approach?
