### ISSUE TITLE
horizon: PostgreSQL 14 database validation

### ISSUE THREAD

**Issue by 2opremio** [stellar/go#4689]
Before upgrading the database to Postgres version 14 we should test

1. Correctness. At the very least all integration tests should pass. I did some testing in the past and integration tests seem to work but unit tests failed https://github.com/stellar/go/pull/4401

2. Performance. We should make sure is as performant as Postgres 10 (or Postgres 12 if we have already upgraded to it). Trade aggrenation / claimable balance queries come to mind. We could use goreplay for this.

**Comment by mollykarcher** [comment]
Closing this as a dup of https://github.com/stellar/go/issues/4831
