### ISSUE TITLE
services/soroban-rpc: getTransactionStatus should include tx xdr and meta xdr

### ISSUE THREAD

**Issue by paulbellamy** [stellar/go#4693]
Currently it only includes the result xdr. But in horizon we include the tx xdr, and meta xdr, which can also be useful. I assume it should be fairly straightforward to add these to the soroban-rpc `getTransactionStatus` return result.

Design doc: https://docs.google.com/document/d/1TZUDgo_3zPz7TiPMMHVW_mtogjLyPL0plvzGMsxSz6A/edit#heading=h.gptc62vxfsa4

Discord Discussion:
https://discord.com/channels/897514728459468821/1040460154644209774/1041869519523680336

**Comment by jcx120** [comment]
Note: 
- can be retrieved from CaptiveCore
- update SDK's (node.js only) and docs as well (API [google doc](https://docs.google.com/document/d/1TZUDgo_3zPz7TiPMMHVW_mtogjLyPL0plvzGMsxSz6A/edit), rust client, CLI).
