### ISSUE TITLE
soroban-rpc: review endpoints

### ISSUE THREAD

**Issue by tsachiherman** [stellar/go#4716]
Review current Soroban API, identify higher level non-network functionality that could be moved to JS SDK. Remove those endpoints. (needs a new ticket to cover effort)

**Comment by paulbellamy** [comment]
# Proposed Revisions

## getAccount
- [x] Implement in the client.
- [ ] Deprecate & remove from server.

## ~getHealth~
- [ ] Remove it and just use `getNetwork`, which gives more info

## getLedgerEntry
- [ ] Replace with `getLedgerEntries`, so you can fetch multiple in one txn (in the same ledger)

## getEvents
- keep it as we need server-side filtering for performance.
- [ ] Consider adding `getLedgers` to fetch a range of ledgers for lower-level access

## getTransactionStatus
- [ ] Add `eta` field, for more efficient polling

## sendTransaction
- [ ] Add `eta` field, for more efficient polling

## simulateTransaction
- [ ] Replace `footprint` field with an array of `footprints`, for multi-operation support (https://github.com/stellar/soroban-tools/issues/363)

## ~getLatestLedger~
- [ ] Merged into `getNetwork`. Remove from soroban-docs.

## getNetwork
- [ ] Add some fields, and implement it.
  - friendbotUrl?: string;
  - latestLedgerHash: string;
  - latestLedgerSeq: number;
  - latestLedgerTime: string;
  - passphrase: string;
  - protocolVersion: string;

## ~requestAirdrop~
- [ ] Remove from soroban-docs. Add `friendbotUrl` to `getNetwork` instead

**Comment by tsachiherman** [comment]
by writing `getLedgers` you meant "retrieve the txclosemeta for a series of ledgers", right ?
I think that I'd like to be avoid going that path, unless you can see any concrete use for that.
i.e. I'd like to avoid exposing internal data structures as part of our API.

**Comment by tsachiherman** [comment]
The `getNetwork` seems to be beyond network passphrase. maybe we should rename it into `getStatus` and retrieve bunch of more info ? i.e. rpc version, captive core version, xdr version, etc.
thinking about that further - maybe *two* endpoints : one to retrieve "static" info, like versions and network passphrase and one for dynamic status such as last ledger num, early ledger num, etc.

**Comment by tsachiherman** [comment]
could you elaborate on the `eta` ?

**Comment by paulbellamy** [comment]
`getLedgers`, I don't have a specific use case. But seemed in the spirit of a lower-level-but-more-powerful API. I don't think txclosemeta is a very internal data structure. It's in the stellar-xdr library, so anyone can parse it. That said, I'm not particularly attached to the `getLedgers` endpoint proposal.

**Comment by jcx120** [comment]
Open: Do we want to include getLedgers?
