### ISSUE TITLE
horizon: add single asset balance payment support

### ISSUE THREAD

**Issue by tsachiherman** [stellar/go#4728]
master issue: #4722 

Payments

@bartekn raised a good point: horizon has a payments endpoint which returns all operations that result in a payment to / from an account. Since stellar assets can be transferred via smart contract invocations it would make sense to include those operations in the payments endpoint.

prerequisite: #4747

**Comment by sreuland** [comment]
@tamirms , is  #https://github.com/stellar/go/pull/4782 considered a pre-requisite for this dev? it implements the new contract data processor which brings in the contract id parsing functionality.
