### ISSUE TITLE
dsn for sqlite

### ISSUE THREAD

**Issue by codingsett** [stellar/go#473]
I wrote the configuration file but i cant figure out why i get errors when i start the server i assume its the database part of the TOM file..any help is appreciated thanks

`[database]
type = "sqlite3"
dsn = "sqlite://home/xirkle/bot/stellar.db"`

**Comment by tomerweller** [comment]
If you suspect there's a bug please attach your exact configuration and error logs. Otherwise, general questions should be asked in the [Stellar Stack Exchange](https://stellar.stackexchange.com/).

Horizon only has support for postgresql at the moment.
