### ISSUE TITLE
horizon: invalid base64 encoded TransactionMeta in response

### ISSUE THREAD

**Issue by christian-rogobete** [stellar/go#4751]
### What version are you using?

Horizon: 2.23.0-131110fc3776aac47132eed7b512ffd0ecaf901c

### What did you do?
Submitted a transaction and tried to decode 'result_meta_xdr' from the horizon response

### What did you expect to see?
A valid base64 string

### What did you see instead?
An invalid base64 string

### More Info
Tried to validate it online base64 validation tools. They also say it is invalid. Laboratory can decode it.

### result_meta_xdr received

AAAAAgAAAAIAAAADAArgjQAAAAAAAAAAUkmHRK0KHYf0oiuzeZFkKwotiG3J7yvQgdukwwet7JwAAAAXSHbnOAAK4IkAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAABAArgjQAAAAAAAAAAUkmHRK0KHYf0oiuzeZFkKwotiG3J7yvQgdukwwet7JwAAAAXSHbnOAAK4IkAAAABAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAwAAAAAACuCNAAAAAGPSvOUAAAAAAAAAAgAAAAIAAAADAArgiwAAAAEAAAAAuziAGO+4LToDPFKUSbMqJ/JdRSJzSD2B3HDXDR5Lsb0AAAABU0RLAAAAAABSSYdErQodh/SiK7N5kWQrCi2IbcnvK9CB26TDB63snAAAAAAAAAAADafQOBc3eIAAAAABAAAAAAAAAAAAAAABAArgjQAAAAEAAAAAuziAGO+4LToDPFKUSbMqJ/JdRSJzSD2B3HDXDR5Lsb0AAAABU0RLAAAAAABSSYdErQodh/SiK7N5kWQrCi2IbcnvK9CB26TDB63snAAAteQ+wOWADafQOBc3eIAAAAABAAAAAAAAAAAAAAACAAAAAwAK4IsAAAABAAAAALs4gBjvuC06AzxSlEmzKifyXUUic0g9gdxw1w0eS7G9AAAAAlBIUFNUQVIAAAAAAAAAAAAhtK2Ou1GXJKI3qXrAxV3XM/ivI7ALEZhk8iQnZfeMFwAAAAAAAAAADafQOBc3eIAAAAABAAAAAAAAAAAAAAABAArgjQAAAAEAAAAAuziAGO+4LToDPFKUSbMqJ/JdRSJzSD2B3HDXDR5Lsb0AAAACUEhQU1RBUgAAAAAAAAAAACG0rY67UZckojepesDFXdcz+K8jsAsRmGTyJCdl94wXAAC15D7A5YANp9A4Fzd4gAAAAAEAAAAAAAAAAAAAAAA=AAAAAgAAAAIAAAADAArgjgAAAAAAAAAAuziAGO+4LToDPFKUSbMqJ/JdRSJzSD2B3HDXDR5Lsb0AAAAXSHbm1AAK4IgAAAABAAAAAgAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAwAAAAAACuCLAAAAAGPSvNsAAAAAAAAAAQAK4I4AAAAAAAAAALs4gBjvuC06AzxSlEmzKifyXUUic0g9gdxw1w0eS7G9AAAAF0h25tQACuCIAAAAAgAAAAIAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAMAAAAAAArgjgAAAABj0rzqAAAAAAAAAAEAAAAIAAAAAAAK4I4AAAABAAAAALs4gBjvuC06AzxSlEmzKifyXUUic0g9gdxw1w0eS7G9AAAAAzaJdfODlLgD/YMULopa/UidSI95KjFYbbRHGEV5lzp+AAAAAAAAAAANp9A4Fzd4gAAAAAAAAAAAAAAAAAAAAAMACuCOAAAAAAAAAAC7OIAY77gtOgM8UpRJsyon8l1FInNIPYHccNcNHkuxvQAAABdIdubUAArgiAAAAAIAAAACAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAADAAAAAAAK4I4AAAAAY9K86gAAAAAAAAABAArgjgAAAAAAAAAAuziAGO+4LToDPFKUSbMqJ/JdRSJzSD2B3HDXDR5Lsb0AAAAXSHbm1AAK4IgAAAACAAAABAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAwAAAAAACuCOAAAAAGPSvOoAAAAAAAAAAwAK4I0AAAABAAAAALs4gBjvuC06AzxSlEmzKifyXUUic0g9gdxw1w0eS7G9AAAAAVNESwAAAAAAUkmHRK0KHYf0oiuzeZFkKwotiG3J7yvQgdukwwet7JwAALXkPsDlgA2n0DgXN3iAAAAAAQAAAAAAAAAAAAAAAQAK4I4AAAABAAAAALs4gBjvuC06AzxSlEmzKifyXUUic0g9gdxw1w0eS7G9AAAAAVNESwAAAAAAUkmHRK0KHYf0oiuzeZFkKwotiG3J7yvQgdukwwet7JwAALXkPsDlgA2n0DgXN3iAAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAEAAAAAAAAAAAAAAAAACuCOAAAABTaJdfODlLgD/YMULopa/UidSI95KjFYbbRHGEV5lzp+AAAAAAAAAAFTREsAAAAAAFJJh0StCh2H9KIrs3mRZCsKLYhtye8r0IHbpMMHreycAAAAAlBIUFNUQVIAAAAAAAAAAAAhtK2Ou1GXJKI3qXrAxV3XM/ivI7ALEZhk8iQnZfeMFwAAAB4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAADAArgjQAAAAEAAAAAuziAGO+4LToDPFKUSbMqJ/JdRSJzSD2B3HDXDR5Lsb0AAAACUEhQU1RBUgAAAAAAAAAAACG0rY67UZckojepesDFXdcz+K8jsAsRmGTyJCdl94wXAAC15D7A5YANp9A4Fzd4gAAAAAEAAAAAAAAAAAAAAAEACuCOAAAAAQAAAAC7OIAY77gtOgM8UpRJsyon8l1FInNIPYHccNcNHkuxvQAAAAJQSFBTVEFSAAAAAAAAAAAAIbStjrtRlySiN6l6wMVd1zP4ryOwCxGYZPIkJ2X3jBcAALXkPsDlgA2n0DgXN3iAAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAEAAAAAAAAAAAAAAAA=AAAAAgAAAAIAAAADAArgjwAAAAAAAAAAuziAGO+4LToDPFKUSbMqJ/JdRSJzSD2B3HDXDR5Lsb0AAAAXSHbmcAAK4IgAAAACAAAABAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAwAAAAAACuCOAAAAAGPSvOoAAAAAAAAAAQAK4I8AAAAAAAAAALs4gBjvuC06AzxSlEmzKifyXUUic0g9gdxw1w0eS7G9AAAAF0h25nAACuCIAAAAAwAAAAQAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAMAAAAAAArgjwAAAABj0rzvAAAAAAAAAAEAAAAGAAAAAwAK4I8AAAAAAAAAALs4gBjvuC06AzxSlEmzKifyXUUic0g9gdxw1w0eS7G9AAAAF0h25nAACuCIAAAAAwAAAAQAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAMAAAAAAArgjwAAAABj0rzvAAAAAAAAAAEACuCPAAAAAAAAAAC7OIAY77gtOgM8UpRJsyon8l1FInNIPYHccNcNHkuxvQAAABdIduZwAArgiAAAAAMAAAAGAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAADAAAAAAAK4I8AAAAAY9K87wAAAAAAAAAAAArgjwAAAAEAAAAAuziAGO+4LToDPFKUSbMqJ/JdRSJzSD2B3HDXDR5Lsb0AAAADrOgtVsHfv4agJkTSQRSlwYMDQsNd5gjY6twHzSDy/B0AAAAAAAAAAA2n0DgXN3iAAAAAAAAAAAAAAAAAAAAAAwAK4I4AAAABAAAAALs4gBjvuC06AzxSlEmzKifyXUUic0g9gdxw1w0eS7G9AAAAAlBIUFNUQVIAAAAAAAAAAAAhtK2Ou1GXJKI3qXrAxV3XM/ivI7ALEZhk8iQnZfeMFwAAteQ+wOWADafQOBc3eIAAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAQAAAAAAAAAAAAAAAQAK4I8AAAABAAAAALs4gBjvuC06AzxSlEmzKifyXUUic0g9gdxw1w0eS7G9AAAAAlBIUFNUQVIAAAAAAAAAAAAhtK2Ou1GXJKI3qXrAxV3XM/ivI7ALEZhk8iQnZfeMFwAAteQ+wOWADafQOBc3eIAAAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAgAAAAAAAAAAAAAAAAAK4I8AAAAFrOgtVsHfv4agJkTSQRSlwYMDQsNd5gjY6twHzSDy/B0AAAAAAAAAAAAAAAJQSFBTVEFSAAAAAAAAAAAAIbStjrtRlySiN6l6wMVd1zP4ryOwCxGYZPIkJ2X3jBcAAAAeAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAA==

![Screenshot 2023-01-26 at 20 07 22](https://user-images.githubusercontent.com/35729606/214927151-1696b7df-856a-45b8-be2a-d5dc04793a06.png)

![Screenshot 2023-01-26 at 20 07 42](https://user-images.githubusercontent.com/35729606/214927168-e3dc1d1b-ce31-4831-ac52-8de29ad2a797.png)

**Comment by leighmcculloch** [comment]
Thanks for reporting. Could you share the transaction ID for the transaction this result XDR relates to?

**Comment by christian-rogobete** [comment]
Thanks for the fast reply. I am so sorry, it was my error. The xdr in the issue contains multiple concatenated results. In Laboratory I get the correct result. Sorry

**Comment by leighmcculloch** [comment]
No worries. Thanks for reporting back on the cause. Cheers!
