### ISSUE TITLE
tests: re-enable SAC testing for authnext support

### ISSUE THREAD

**Issue by tsachiherman** [stellar/go#4757]
this ticket is a followup on https://github.com/stellar/soroban-tools/issues/347.

during the xdr updates, we found that the unit testing around the SAC were failing due to changes in the contract.
The contract need to be updated for the test to pass. There might be other culprits that were missed before.

related PR : https://github.com/stellar/rs-soroban-env/pull/645

this issue is part of the authNext efforts, which are covered in https://github.com/stellar/soroban-tools/issues/346

**Comment by 2opremio** [comment]
In order to fix this the soroban examples repo needs to be updated with a new token contract spec

**Comment by sreuland** [comment]
@2opremio @tsachiherman , i'm getting up to speed, here's what I think actions are needed:

* get new rs-soroban-sdk that includes auth-next in rs-soroban-env from [#645](https://github.com/stellar/rs-soroban-env/pull/645)
* copy https://github.com/2opremio/soroban-examples/tree/sac_test to soroban/examples/single_asset
* update soroban-examples deps to latest rs-soroban-sdk with auth-next
* obtain new soroban token spec wasm that is auth compliant, copy it to soroban-examples/soroban_token_spec.wasm
* compile soroban-examples/single_asset to .wasm and copy that to test fixture that SAC tests use in monorepo
* get new debian pkg of stellar-core~soroban that includes latest  rs-soroban-env, use that in monorepo
* re-enable sac tests in monorepo, should pass now

**Comment by tsachiherman** [comment]
yes, all of these looks right. I don't know if there would be more once we're done with these.

**Comment by sreuland** [comment]
after looking at the [asset contract tests in monorepo](https://github.com/stellar/go/blob/soroban-xdr-next/services/horizon/internal/integration/sac_test.go), I think is example of where system-test can be used instead, i.e. those asset contract tests, could be done as a dapp feature test in system-test driven higher up from soroban cli tool, so captured that as additional feature request for later in system-test, at which point they could be deprecated here:

https://github.com/stellar/system-test/issues/22

**Comment by tsachiherman** [comment]
@sreuland I agree that the system tests would provide good coverage for these features, however, depending on these prevent us from pinpointing a potential bug in horizon. i.e. a potential bug in the CLI would prevent us from testing horizon. That's not that great. I do agree that we should cross-level and skip-level testing ( i.e. the ticket that you've created is valid and should be completed )

**Comment by sreuland** [comment]
merged pr https://github.com/stellar/go/pull/4759
