### ISSUE TITLE
Internal Server Error 500

### ISSUE THREAD

**Issue by shenhao217** [stellar/go#4764]
Hello, sending and getting PATH under the node I built will return a 500 error. This is my request content:
```
/paths/strict-receive?source_assets=USDC:GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN&destination_asset_type=native&destination_amount=10
------------------------------------
{
  "type": "https://stellar.org/horizon-errors/server_error",
  "title": "Internal Server Error",
  "status": 500,
  "detail": "An error occurred while processing this request.  This is usually due to a bug within the server software.  Trying this request again may succeed if the bug is transient. Otherwise, please contact the system administrator."
}
------------------------------------
```
 Steller node information：
 
 ```
2023-02-13T08:26:20.117 [default INFO] Config from stellar-core.cfg
2023-02-13T08:26:20.199 [default INFO] Generated QUORUM_SET: {
   "t" : 5,
   "v" : [
      {
         "t" : 2,
         "v" : [
            "Blockdaemon_Validator_1",
            "Blockdaemon_Validator_2",
            "Blockdaemon_Validator_3"
         ]
      },
      {
         "t" : 2,
         "v" : [ "sdf_3", "sdf_1", "sdf_2" ]
      },
      {
         "t" : 2,
         "v" : [ "wirexSG", "wirexUK", "wirexUS" ]
      },
      {
         "t" : 2,
         "v" : [ "coinqvest_finland", "coinqvest_hong_kong", "coinqvest_germany" ]
      },
      {
         "t" : 2,
         "v" : [ "satoshipay_iowa", "satoshipay_singapore", "satoshipay_frankfurt" ]
      },
      {
         "t" : 3,
         "v" : [
            "lobstr_5_australia",
            "lobstr_4_asia",
            "lobstr_1_europe",
            "lobstr_2_europe",
            "lobstr_3_north_america"
         ]
      },
      {
         "t" : 2,
         "v" : [ "hercules", "lyra", "bootes" ]
      }
   ]
}

2023-02-13T08:26:20.199 [default INFO] Assigning calculated value of 2 to FAILURE_SAFETY
Content-Length: 1388
Content-Type: application/json

{
   "info" : {
      "build" : "stellar-core 19.6.0 (b3a6bc28116e80bff7889c2f3bcd7c30dd1ac4d6)",
      "ledger" : {
         "age" : 5145,
         "baseFee" : 100,
         "baseReserve" : 5000000,
         "closeTime" : 1676242847,
         "hash" : "0bc03238e74707df1baec4e032da463363d1604a5e9edf17b468db5123171e70",
         "maxTxSetSize" : 1000,
         "num" : 44919805,
         "version" : 19
      },
      "network" : "Public Global Stellar Network ; September 2015",
      "peers" : {
         "authenticated_count" : 0,
         "pending_count" : 9
      },
      "protocol_version" : 19,
      "quorum" : {
         "node" : "GCMGZ",
         "qset" : {
            "agree" : 20,
            "cost" : 24400592,
            "delayed" : 0,
            "disagree" : 0,
            "fail_at" : 4,
            "hash" : "b68a69",
            "lag_ms" : null,
            "ledger" : 44920078,
            "missing" : 3,
            "phase" : "EXTERNALIZE"
         },
         "transitive" : {
            "critical" : null,
            "intersection" : true,
            "last_check_ledger" : 44727504,
            "node_count" : 27
         }
      },
      "startedOn" : "2023-01-30T02:21:45Z",
      "state" : "Joining SCP",
      "status" : [
         "Catching up to ledger 44920063: Download & apply checkpoints: num checkpoints left to apply:5 (37% done)"
      ]
   }
}
------------------------------------------------
  "horizon_version": "2.23.1-6def2295c2e739883f028b5098c30d82969a94a5",
  "core_version": "stellar-core 19.6.0 (b3a6bc28116e80bff7889c2f3bcd7c30dd1ac4d6)",
  "ingest_latest_ledger": 44919782,
  "history_latest_ledger": 44919782,
  "history_latest_ledger_closed_at": "2023-02-12T22:58:33Z",
  "history_elder_ledger": 44719625,
  "core_latest_ledger": 44919804,
  "network_passphrase": "Public Global Stellar Network ; September 2015",
  "current_protocol_version": 19,
  "supported_protocol_version": 19,
  "core_supported_protocol_version": 19
---------------------------------------------
```
Please take a look, thank you

**Comment by 2opremio** [comment]
We need the logs during the occurrence of the problem.

Also, we need details on how you are running horizon. Is this a node you are running yourself? Does it have sufficient capacity?

The request seems to work just fine on the public network: https://horizon.stellar.org/paths/strict-receive?source_assets=USDC:GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN&destination_asset_type=native&destination_amount=10

**Comment by shenhao217** [comment]
> We need the logs during the occurrence of the problem.
> 
> Also, we need details on how you are running horizon. Is this a node you are running yourself? Does it have sufficient capacity?
> 
> The request seems to work just fine on the public network: https://horizon.stellar.org/paths/strict-receive?source_assets=USDC:GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN&destination_asset_type=native&destination_amount=10

thank you for your reply. Yes, this node is built by myself.

Here is the node log：
time="2023-02-15T17:07:30.663+08:00" level=info msg="Finished request" app_name=undefined app_version=undefined bytes=354 client_name=undefined client_version=undefined duration=0.000629168 host="****:8000" ip=103.178.54.22 ip_port="103.178.54.22:50002" method=GET path="/paths/strict-receive?source_assets=USDC%3AGA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN&destination_asset_type=native&destination_amount=10" pid=28650 referer=undefined req=cvallis-plotter-002/qET2iFGU4K-001306 route=/paths/strict-receive status=500 streaming=false x_forwarder_for=

Here is the node configuration：
export STELLAR_CORE_BINARY_PATH="/usr/bin/stellar-core" 
export CAPTIVE_CORE_STORAGE_PATH="./"
export CAPTIVE_CORE_CONFIG_APPEND_PATH="/home/cvallis/product/horizon/horizon-v2.23.1-linux-amd64/captive-core-pubnet.cfg"
export CAPTIVE_CORE_PEER_PORT=11625
export ENABLE_CAPTIVE_CORE_INGESTION=true
export DATABASE_URL="postgresql://postgres:**@127.0.0.1/horizon"
export PORT=8000
export STELLAR_CORE_URL="http://localhost:11626"
export LOG_LEVEL="info"
export INGEST=true
export HISTORY_RETENTION_COUNT="200000"
export PER_HOUR_RATE_LIMIT="7200000"
export NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
export HISTORY_ARCHIVE_URLS="http://history.stellar.org/prd/core-live/core_live_001/"
export ADMIN_PORT=6060

The node will save the latest 200,000 pieces of data. Will insufficient data cause this?

**Comment by mollykarcher** [comment]
Closing this due to lack of info. If you're still having an issue, please reopen with more detail. More general support requests should be directed to our developer discord https://discord.gg/stellardev
