### ISSUE TITLE
services/horizon: benchmark and document current memory footprint of horizon + captive core

### ISSUE THREAD

**Issue by mollykarcher** [stellar/go#4768]
### What problem does your feature solve?

We field questions and issues from partners fairly often asking about the hardware requirements necessary to run their horizon nodes. While we have some [recommendations](https://developers.stellar.org/docs/run-api-server/prerequisites) these are likely quite excessive, and just provide a safe/high-enough ceiling such that most people following these won't run into any issues. We'd like to have a more granular understanding of the current state of things, and how we may expect those requirements to grow/change over time. This would help us have more targeted + useful conversations with partners about what hardware they need to set up.

### What would you like to see?

A documented analysis of how much RAM both horizon and captive core require, when run in different configurations. That documentation should be made available in our public documentation, such that we can point partners/infrastructure providers to it as a reference. We should be clear there to set expectations around when our findings were last updated and how we may expect them to change over time.

Historical context:
- [02/2022](https://github.com/stellar/go/pull/4092#issuecomment-1029355374): Observed a combined ~10GB for in-memory configuration (on a laptop)
- [02/2022](https://github.com/stellar/go/pull/4092#issuecomment-1029355374): Observed a combined ~2.5GB for on-disk configuration (on a laptop)
- [02/2023](https://stellarfoundation.slack.com/archives/C02B04RMK/p1676313888344859?thread_ts=1676068034.636199&cid=C02B04RMK): Observed a combined ~14GB for on-disk configuration (in staging pubnet) 

The on-disk footprint in 2023 was observed to be quite significantly higher than what was observed in 02/2022. While the environments in which these were run is very different, the growth/difference is still somewhat worrisome.

**Comment by sreuland** [comment]
Ran bench tests on local machine, Mac M1, 3.2Ghz, 8 core, 16GB ram.

Core. 19.7 and Horizon 2.24.1 with captive core ingestion config `--captive-core-use-db` for on-disk mode of core, and configured for pubnet network.

**Observations:** 
From an empty db, core and horizon first spent about 1 day collectively on catch up. During that time, both core and horizon start at sub-1GB ram usage, once core catches up after a couple hours, it was around 1.5GB RAM at which point that instance of core shuts down and Horizon runs a new instance of core in `run` mode with pipe `--metadata-output-stream fd:3` at which point the core process remains around 1.5 - 1.8 GB of RAM range. 

Horizon switches to next phase of ingestion which processing ledger entry changes from archives, it stays in this process for about 1 day, during which the RAM usage of horizon increased to about 7GB,  while logging statuses of:
```
level=info msg="Processing ledger entry changes" pid=30593 processed_entries=3350000 progress="7.60%" sequence=44973311 service=ingest source=historyArchive
```

Once ledger entries processing hit 100%, horizon's RAM usage dropped down to 1.5GB and it started logging forward ingestion, and RAM did not fluctuate from 1.5GB from that point forward. 
```
level=info msg="Processed ledger" commit=true duration=0.699152375 ledger=true pid=30593 sequence=44978119 service=ingest state=true
```

**Summary:**
Once caught up, forward ingestion with captive core on-disk mode on the test machine: Horizon 1.5GB + Core 1.5GB = 3GB total system RAM combined.

**Comment by sreuland** [comment]
Inspected the runtime instance of a staged deployment of horizon with captive core ingestion on a cloud vm, same Horizon 2.24.1 with captive core(19.7) and  `--captive-core-use-db` ,`top`  results:

VIRT: Horizon 10GB + Core 4GB = 14GB total system memory(ram + mmap/swapped on-disk).
RES: Horizon 7GB + Core 2.4GB = 9.4GB RAM memory.

The horizon instance has been running for several days. Observing it at present, the VIRT levels remain consistent, but noticed the RES levels which represent RAM consumption only, vary from 1.5GB to 7GB within a couple hours range.

What's interesting is there is a 2nd deployment instance running legacy ingestion against pubnet network with same Horizon 2.24.1, there is no captive core instance running, instead horizon is querying a postgresdb that core is directly writing ledgers to instead. This horizon instance has very similar VIRT and RES RAM memory usage pattern.

It appears like an ingesting horizon instance's RAM usage isn't affected much by captive core vs. legacy mode.

Using `pprof` tool to get more info on heap/RAM usage within horizon process to see where it's going:

**horizon with captive core ingestion, getting ledgers from pipe**
```
Type: inuse_space
Showing nodes accounting for 2825.88MB, 96.97% of 2914.13MB total
Showing top 10 nodes out of 28
      flat  flat%   sum%        cum   cum%
 1472.51MB 50.53% 50.53%  2783.01MB 95.50%  github.com/stellar/go/ingest.(*CheckpointChangeReader).streamBucketContents
    1292MB 44.34% 94.87%     1292MB 44.34%  github.com/stellar/go/ingest.(*memoryTempSet).Add
   27.28MB  0.94% 95.80%    65.78MB  2.26%  github.com/stellar/go/services/horizon/internal/ingest/processors.AssetStatSet.addDelta
   20.50MB   0.7% 96.51%    20.50MB   0.7%  math/big.NewInt (inline)
      10MB  0.34% 96.85%    18.50MB  0.63%  github.com/stellar/go/xdr.(*LedgerEntryData).DecodeFrom
    1.61MB 0.055% 96.90%   109.73MB  3.77%  github.com/stellar/go/services/horizon/internal/ingest.(*system).verifyState
       1MB 0.034% 96.94%    18.50MB  0.63%  github.com/stellar/go/xdr.(*BucketEntry).DecodeFrom
    0.98MB 0.034% 96.97%    14.67MB   0.5%  github.com/lib/pq.(*conn).QueryContext
         0     0% 96.97%    14.67MB   0.5%  database/sql.(*DB).queryDC
         0     0% 96.97%    14.67MB   0.5%  database/sql.(*DB).queryDC.func1
```

**horizon legacy ingestion, getting ledgers from postgres db**
```
Type: inuse_space
Showing nodes accounting for 2842.46MB, 96.26% of 2952.83MB total
Showing top 10 nodes out of 37
      flat  flat%   sum%        cum   cum%
 1438.07MB 48.70% 48.70%  2753.07MB 93.24%  github.com/stellar/go/ingest.(*CheckpointChangeReader).streamBucketContents
    1292MB 43.75% 92.46%     1292MB 43.75%  github.com/stellar/go/ingest.(*memoryTempSet).Add
   46.40MB  1.57% 94.03%    46.40MB  1.57%  reflect.growslice
   17.50MB  0.59% 94.62%    18.50MB  0.63%  github.com/stellar/go/ingest/verify.(*StateVerifier).Write
   15.14MB  0.51% 95.13%    31.64MB  1.07%  github.com/stellar/go/services/horizon/internal/ingest/processors.AssetStatSet.addDelta
      14MB  0.47% 95.61%    19.50MB  0.66%  github.com/stellar/go/xdr.(*LedgerEntryData).DecodeFrom
    7.59MB  0.26% 95.86%   130.67MB  4.43%  github.com/stellar/go/services/horizon/internal/ingest.addAccountsToStateVerifier
    6.24MB  0.21% 96.08%   187.75MB  6.36%  github.com/stellar/go/services/horizon/internal/ingest.(*system).verifyState
    3.50MB  0.12% 96.19%       23MB  0.78%  github.com/stellar/go/xdr.(*BucketEntry).DecodeFrom
       2MB 0.068% 96.26%    48.40MB  1.64%  reflect.Value.extendSlice

```

`CheckpointChangeReader` and its tree of sub-calls(cumulative), appears to account for the majority of memory usage. Am wondering if the variance observed in RAM over course of hours may be related to go garbage collection cycles.

**Comment by sreuland** [comment]
@mollykarcher , I've posted some analysis, maybe we can review for next steps, thanks!
