### ISSUE TITLE
xdr: Update XDR to support network confirm transaction type

### ISSUE THREAD

**Issue by tsachiherman** [stellar/go#4788]
## What

Update XDR to support network confirm transaction type.

There will be a new transaction type `NetworkConfirm` (todo: confirm this name). We should ingest/store/etc this like any other transaction.

## Epic

https://github.com/stellar/soroban-tools/issues/519

**Comment by 2opremio** [comment]
@tsachiherman I have bumped the XDR definitions at https://github.com/stellar/go/pull/4851 but I don't see any `NetworkConfirm` transaction type. I will ask on Slack

**Comment by tsachiherman** [comment]
> @tsachiherman Is this issue about consuming changes to network settings? If so, there's no new operation or transaction type. There's a new ledger entry type (`CONFIG_SETTING`), and you can consume the changes for it through tx meta.

I see. @2opremio do we need to update the ingestion to ignore this ledger entry type ?

**Comment by 2opremio** [comment]
I think the new entry is already being considered for ingestion (probably just ignored). @tamirms  @Shaptic do you remember?
