### ISSUE TITLE
Effects links return 404 error in effect.md

### ISSUE THREAD

**Issue by cecilygardner** [stellar/go#479]
In [ effect.md](https://github.com/stellar/go/blob/6a367049e8f9ad52798f5c8f69df8b875fde4a1a/services/horizon/internal/docs/reference/resources/effect.md) in the Endpoints section all of the effects links return a 404.

**Comment by bartekn** [comment]
Links are designed to work in Developers site: https://www.stellar.org/developers/horizon/reference/resources/effect.html
