### ISSUE TITLE
contractevent, services/horizon: Update Stellar Asset Contract event parsing and testing.

### ISSUE THREAD

**Issue by tsachiherman** [stellar/go#4790]
**Epic**: stellar/soroban-tools#471

--------------------

### What?
**TL;DR:** Update SAC event processing for new `ScVal` format.

This is a significant piece of work because there are two large components:

 - [x] Updating the new `support/contractevent` library (#4802) to parse SAC events in their new format
 - [x] Updating the `integration/sac_test.go` test suite to ensure we properly interact with the SAC
 - [x] Updating the `integration/invoke_host_function.go` test suite
 - [x] Updating the contract data processor (`ingest/processors/contract_data.go`)

**Comment by Shaptic** [comment]
@tamirms would you mind/want to switch this for one of mine? Since I'm actively working on event parsing I might have an easier time fighting the new XDR
