### ISSUE TITLE
Go SDK versioning

### ISSUE THREAD

**Issue by bartekn** [stellar/go#485]
Please discuss and share ideas regarding Go SDK versioning in this issue.

Resources:
* https://research.swtch.com/vgo-import
* https://research.swtch.com/vgo

**Comment by tomerweller** [comment]
Another resource that I found great for context and overview is this post: https://blog.golang.org/versioning-proposal

I think we should do our best to preserve backward compatibility, as long as it's not too cumbersome. For moving resources around, type aliases and deprecation notices should suffice. Here's an example for what I think is a good enough solution for these situations: https://github.com/stellar/go/pull/491 (note, type aliases breaks go1.8 support)


For breaking changes, we should have a different import path. Though, in the context of our monorepo I'm not sure what this means. Will it be a top level `go/v2` or a specific `clients/horizon/v2` for the horizon client?

**Comment by 2opremio** [comment]
Closing, since I think this no longer applies. Please reopen if you think otherwise.
