### ISSUE TITLE
services/horizon: fully remove non-captive core horizon support

### ISSUE THREAD

**Issue by mollykarcher** [stellar/go#4855]
### What problem does your feature solve?

Currently, running horizon in non-captive-core (or legacy) mode is still supported, just [deprecated](https://developers.stellar.org/docs/run-api-server/migrating). We also still use 2 legacy instances for ingestion and transaction submission in our own public horizon deployment. We've maintained this setup due to concern over startup time of the captive-core instances when they are restarted or state is rebuilt.

However, those concerns may have been alleviated now that core has merged a [change](https://github.com/stellar/stellar-core/pull/3655) to significantly speed-up that start-up time.

### What would you like to see?

- [x] Observe startup time on the core release where this change goes out (v19.10) to validate it's quick/acceptable. We may also want to sanity-check this restart startup time a few times on staging (or similar)
- [x] Work with ops to remove the legacy ingesters from our deployment. This requires doing in staging first, and consider having more than 2 instances of captive core ingesters, need to confirm stability and responsiveness on restarts in staging, identify the typical wait for catch up ties after restarts, so, no surprises when lands in prod. Ops ticket referencing this work:
    - [x] https://github.com/stellar/ops/issues/2557
- [x] Note that these are currently also serving transaction submission requests, so we may want to first move txsub to the captive-core instances and observe that behavior/performance for some time before fully killing these off. Consider keeping transaction submission isolated from ingestion, this would keep all user behavior/API requests from ever bottlenecking the ingestion process. So instead of completely dropping the legacy ingestors, we redeploy them as captive-core instances and disable ingestion on them, so they're only serving transaction submission. But we should consider the pros/cons here. Ops ticket referencing this work:
    - [x] https://github.com/stellar/ops/issues/2558
- [x] Remove any code and integration tests supporting the db backend or legacy setup:
  * `--stellar-core-db-url`
- [x] Update external developer docs 
- [x] deprecate usage of `ENABLE_CAPTIVE_CORE_INGESTION` flag, the distinction is no longer relevant, `INGEST` flag presumes captive core ingestion.

**Comment by sydneynotthecity** [comment]
@Shaptic says that captive core nodes in prod on an upgrade sometimes fall out of sync (~20 min+) with current state. We need to figure out why they fall behind because Horizon does fall back on these ingestion nodes when that occurs.

**Comment by mollykarcher** [comment]
> captive core nodes in prod on an upgrade sometimes fall out of sync (~20 min+) with current state
@Shaptic can you point to how exactly that materializes or you see it happening?

There was some [semi-recent discussion](https://stellarfoundation.slack.com/archives/C02B04RMK/p1689101203249169) where core team more-or-less concluded that we should be seeing gaps on the order of seconds, not minutes. I've tried to look into this before, and [Core's App metrics](https://grafana.stellar-ops.com/d/DCQsHZ7Wk/stellar-core-full?orgId=1&from=now%2Fy&to=now&var-environment=prd&var-instance=horizon-blue-captivecore-001a.prd.stellar002&var-instance=horizon-blue-captivecore-002c.prd.stellar002&var-instance=horizon-green-captivecore-001a.prd.stellar002&var-instance=horizon-green-captivecore-002c.prd.stellar002&var-db_metric=All&var-overlay_recv_metric=All&var-overlay_outbound_metric=All&var-over) and Horizon's [stellar-core-synced metric](https://grafana.stellar-ops.com/d/vHv3RMNMz/horizon-dashboard-bartek?orgId=1&viewPanel=1695) seem like the best indicators we have, but neither seem to really highlight this issue. I'm wondering if this issue has gone away (as Core team seems to think) or if we have an observability gap here.

**Comment by aditya1702** [comment]
Instead of moving transaction submission to captive-core, we finally decided to keep it as it is. Instead we will update our Scaling page - https://developers.stellar.org/docs/run-api-server/scaling and add a section of using legacy core for large-scale deployments (similar to SDF's instance).
