### ISSUE TITLE
services/horizon: change default for `--captive-core-use-db` to true

### ISSUE THREAD

**Issue by mollykarcher** [stellar/go#4856]
### What problem does your feature solve?

Currently, there's a lot of inconsistency in what configuration we recommend for horizon, which leads to confusion both internally and externally. At present, the default value for `CAPTIVE_CORE_USE_DB` is `false`, however our recommendations to external partners (and what we've chosen to do in our deployment) is `true`. The size of the ledger grows unbounded over time, so with an in-memory configuration, the RAM required of horizon/captive-core will eventually become unreasonably large and/or prohibitively expensive. 

### What would you like to see?

- [x] Update the default of `CAPTIVE_CORE_USE_DB` to `true`
- [x] Update quickstart to use new default (this may happen automatically, not sure if quickstart is explicitly setting this flag)
- [ ] Update external documentation to reflect new default

Updating the default is a breaking change, as any customers not explicitly setting this flag will experience a behavior flip. However, it's unlikely that anyone using in-memory is doing it explicitly/intentionally and in a worse-case scenario where it causes an issue for them, the revert is quite simple (ie. explicitly set the flag to `false`)

### What alternatives are there?

- Another option would be to remove in-memory option altogether. We've chosen this route for [soroban-rpc](https://github.com/stellar/soroban-tools/issues/615); being a new product offering, we don't want to muddy the waters with this option when our recommendation is to always use on-disk mode. We could go the same route here (and maybe we'll want to eventually), but it's probably best to at least give users the option to explicitly now set/choose this option for now, since it's a quick and easy back-stop if they do notice or complain when the default changes.
- We could consider deprecating the in-memory option (for removal in a later release)

**Comment by Shaptic** [comment]
We also want this to be the new default in the stub configuration provided when you install the `.deb` package. I think it's [here](https://github.com/stellar/packages/blob/master/stellar-captive-core/debian/stellar-captive-core.default).
