### ISSUE TITLE
Offers Streaming

### ISSUE THREAD

**Issue by robertDurst** [stellar/go#489]
AFAIK, not yet implemented:

Ref: https://github.com/stellar/go/blob/50091de20dff08100374ba2adfaa18f5e813a42e/services/horizon/internal/docs/reference/endpoints/offers-for-account.md

**Comment by robertDurst** [comment]
Still interested ...  may put on hold for time being.

**Comment by robertDurst** [comment]
12222234

**Comment by ire-and-curses** [comment]
This has been implemented in the new `horizonclient`: https://godoc.org/github.com/stellar/go/clients/horizonclient#Client.StreamOffers
