### ISSUE TITLE
Orderbook Streaming

### ISSUE THREAD

**Issue by robertDurst** [stellar/go#490]
AFAIK, not yet implemented

Ref: https://github.com/stellar/go/blob/50091de20dff08100374ba2adfaa18f5e813a42e/services/horizon/internal/docs/reference/endpoints/orderbook-details.md

**Comment by ire-and-curses** [comment]
This has been implemented in the new `horizonclient`: https://godoc.org/github.com/stellar/go/clients/horizonclient#Client.StreamOrderBooks
