### ISSUE TITLE
ingest/filtering: enable filtering by default

### ISSUE THREAD

**Issue by sreuland** [stellar/go#4906]
### What problem does your feature solve?
un-necessary configuration flag to enable ingestion filtering rather than default

### What would you like to see?
ingestion filtering enabled by default, don't need to configure the runtime flag, remove `--exp-enable-ingestion-filtering` flag from the help output, but keep the flag definition. Log a warning message saying the flag is deprecated if it's present. find any references to the flag in the repo and remove them or document as deprecated.

There will be no filter rules created by default which results in effectively same end result, nothing filtered. Need to confirm this is the outcome when filtering enabled with no rules.

remove reference of the flag in the[ public ingestion docs ](https://developers.stellar.org/docs/run-api-server/ingestion-filtering)

### What alternatives are there?
set the `--exp-enable-ingestion-filtering` in horizon runtime config.

**Comment by mollykarcher** [comment]
Let's check the expected behavior when an unknown flag is sent; will installs fail or silently ignore it. This will impact how we want to roll it out - with deprecation warning or just hard remove
