### ISSUE TITLE
multi-arch binaries to support Captive Core are included as supporting GH release artifacts 

### ISSUE THREAD

**Issue by sreuland** [stellar/go#4925]
### What problem does your feature solve?
Horizon uses captive core for ingestion, any horizon installation needs the core binary for captive core to work. End users are faced with finding the best way to get the core binary, it gets complicated for any non-amd host architectures, as those binaries are not pre-built or packaged.

### What would you like to see?
To make Horizon install easier for users, we can provide pre-built stellar core binaries to be used as the `STELLAR-CORE-BINARY-PATH` for both of the main architecture for GA [core GH releases](https://github.com/stellar/stellar-core/releases).
The Horizon GH release includes artifact links to binaries in both linux/amd64 and linux/arm64 for the latest GA released core.
The Horizon GH release includes artifact links to binaries in both linux/amd64 and linux/arm64 for the current Horizon release.

### What alternatives are there?
* people on amd architectures manually compile core from source or get core bin from debian package for the release they want to use as captive core bin for horizon.
* people on arm architectures manually compile core from source for the release they want to use as captive core bin for horizon.

**Comment by urvisavla** [comment]
I think this is covered in https://github.com/stellar/go/issues/4920.

**Comment by sreuland** [comment]
defer to #4920

**Comment by sreuland** [comment]
yes, defer to #4920
