### ISSUE TITLE
services/horizon:  deprecate --stellar-core-db-url

### ISSUE THREAD

**Issue by sreuland** [stellar/go#4943]
### What problem does your feature solve?
horizon users configuring ingestion to connect directly to core's db url using `--stellar-core-db-url`

### What would you like to see?
`--stellar-core-db-url` is removed so horizon users can't use it and therefore, nudges people to use the captive core config flags instead which is preferred.

**Comment by mollykarcher** [comment]
Have a related ticket here to fully remove this functionality - https://github.com/stellar/go/issues/4855 - of course we'll need to deprecate our own usage of it internally, first.

**Comment by sreuland** [comment]
nice, I'll add comment about this flag on #4855 , close as dup here.
