### ISSUE TITLE
Bump postgres version in horizon integration / unit tests

### ISSUE THREAD

**Issue by tamirms** [stellar/go#4961]
We are running postgres version 9.6 in our CI. However, Postgres version 9 is no longer supported and we have long since upgraded our production deployments to postgres version 12. We should update our CI configuration to run the Horizon tests with postgres version 12.

**Comment by urvisavla** [comment]
Version updated in  https://github.com/stellar/go/commit/f4eeed670abefa25732415206adc7dac6f28c915.
