### ISSUE TITLE
horizon: `X-RateLimit-*` headers did not appear in the response from horizon.stellar.org.

### ISSUE THREAD

**Issue by overcat** [stellar/go#4982]
### What version are you using?
https://horizon.stellar.org instance.
```
"horizon_version": "2.26.1-9a7522eac66867b9768d7cc24c837d5efde66a3c"
"core_version": "stellar-core 19.12.0 (2109a168a895349f87b502ae3d182380b378fa47)"
```

### What did you do?
```
curl --location 'https://horizon.stellar.org/ledgers/11581' -i
curl --location 'https://horizon-futurenet.stellar.org/ledgers/11581' -i
```

### What did you expect to see?

<img width="810" alt="horizon" src="https://github.com/stellar/go/assets/2368403/4c189f49-6357-41bb-90b6-a347e4fd9a0f">

### What did you see instead?

`X-RateLimit-*` headers appear in the response from horizon.stellar.org.

**Comment by mollykarcher** [comment]
Thanks for the report! Rate limiting on SDF horizon is handled at the infra level, and we disable the typical application-code rate limiting that exists in this codebase. We will be investigating options with our operations team as to if/how we can get these returned when rate limiting at the infra layer as well

**Comment by mollykarcher** [comment]
Failed to close this ticket when this was resolved, but this should have been fixed around 8/5. Please reopen if issue persists
