### ISSUE TITLE
Pages Generic Replication

### ISSUE THREAD

**Issue by robertDurst** [stellar/go#500]
In order to implement more endpoints for the Go SDK, I was finding myself creating `Pages` structures for each resource. @tomerweller @nikhilsaraf and myself began to discuss the best way for doing this and here are the two options we discussed:

1. Generate code to create each of these structs.
2. We have a `Pageable` interface which we use for a [BasePage](https://github.com/stellar/go/blob/master/support/render/hal/page.go#L11):
```go
// BasePage represents the simplest page: one with no links and only embedded records.
// Can be used to build custom page-like resources
type BasePage struct {
	FullURL *url.URL `json:"-"`
	Embedded struct {
		Records []Pageable `json:"records"`
	} `json:"_embedded"`
}
```

Here is a nice overview of all options (with pros + cons): https://appliedgo.net/generics/
1. Copy-pasta
2. Use interfaces
3. Use type assertions
4. Use reflection
5. Use a code generator

Related to #491

**Comment by sbsends** [comment]
Hey @robertDurst,

take a look at this: https://github.com/GoogleCloudPlatform/google-cloud-go/wiki/Iterator-Guidelines

**Comment by sbsends** [comment]
IMHO, interface pages are probably the most idiomatic.

**Comment by bartekn** [comment]
This will probably be solved by creating `*Page` (ex. `EffectsPage`) structs in `protocols/horizon`. See #1132 for a discussion and reasoning.
