### ISSUE TITLE
Eviction of Soroban ledger entries can lead to Horizon having invalid asset stats

### ISSUE THREAD

**Issue by tamirms** [stellar/go#5031]
Horizon ingests two types of contract data ledger entries from the Stellar Asset Contract:

- [AssetInfo](https://github.com/stellar/rs-soroban-env/blob/main/soroban-env-host/src/native_contract/token/contract.rs#L141) which is used by horizon to map contract ids to Stellar Assets
- [BalanceValue](https://github.com/stellar/rs-soroban-env/blob/main/soroban-env-host/src/native_contract/token/balance.rs#L61) which is used by horizon to keep track of how many contracts hold a given Stellar Asset and the total balance of that asset held by all contracts

Horizon will only ingest [BalanceValue](https://github.com/stellar/rs-soroban-env/blob/main/soroban-env-host/src/native_contract/token/balance.rs#L61) ledger entries from contracts which have an [AssetInfo](https://github.com/stellar/rs-soroban-env/blob/main/soroban-env-host/src/native_contract/token/contract.rs#L141) ledger entry. But, it is possible for a Stellar asset contract to have an evicted [AssetInfo](https://github.com/stellar/rs-soroban-env/blob/main/soroban-env-host/src/native_contract/token/contract.rs#L141) ledger entry while also having live [BalanceValue](https://github.com/stellar/rs-soroban-env/blob/main/soroban-env-host/src/native_contract/token/balance.rs#L61) ledger entries.

In that scenario, a Horizon instance starting from an empty DB will ignore all live [BalanceValue](https://github.com/stellar/rs-soroban-env/blob/main/soroban-env-host/src/native_contract/token/balance.rs#L61) ledger entries from that contract because the [AssetInfo](https://github.com/stellar/rs-soroban-env/blob/main/soroban-env-host/src/native_contract/token/contract.rs#L141) ledger entry is evicted and therefore not present in the ledger. If the  [AssetInfo](https://github.com/stellar/rs-soroban-env/blob/main/soroban-env-host/src/native_contract/token/contract.rs#L141) ledger entry was restored, then Horizon would ingest it, but it would not ingest the pre-existing live [BalanceValue](https://github.com/stellar/rs-soroban-env/blob/main/soroban-env-host/src/native_contract/token/balance.rs#L61) ledger entries. So, in that case the Horizon DB would not have an accurate count of contract holders and state verification would fail.

Here's a concrete example:

1. [init_asset()](https://github.com/stellar/rs-soroban-env/blob/main/soroban-env-host/src/native_contract/token/contract.rs#L113) is called on asset `USD:GB...` .
2. `mint()` is called to give contract `CA...` some `USD:GB...` .
3. The expiration for the contract balance of `CA...` is bumped but the [AssetInfo](https://github.com/stellar/rs-soroban-env/blob/main/soroban-env-host/src/native_contract/token/contract.rs#L141) for `USD:GB...` is allowed to expire and eventually becomes evicted.
4. A new Horizon instance starts up. When it bootstraps from the history archives it encounters the `USD:GB...` contract balance for `CA...`. However, it ignores the contract balance because there is no  [AssetInfo](https://github.com/stellar/rs-soroban-env/blob/main/soroban-env-host/src/native_contract/token/contract.rs#L141) for `USD:GB...` in the ledger.
5. Eventually the [AssetInfo](https://github.com/stellar/rs-soroban-env/blob/main/soroban-env-host/src/native_contract/token/contract.rs#L141) for `USD:GB...` is restored. Horizon ingests the ledger entry and records the contract id for asset `USD:GB...` in its DB.
6. If you query the horizon asset stats endpoint for `USD:GB...` , Horizon will state that the asset does not have any contract holders. However this is not correct. `CA...` is a contract holder but Horizon wasn't able to ingest its contract balance since it existed before the [AssetInfo](https://github.com/stellar/rs-soroban-env/blob/main/soroban-env-host/src/native_contract/token/contract.rs#L141) for `USD:GB...` was restored.

To fix this issue we can ingest all [BalanceValue](https://github.com/stellar/rs-soroban-env/blob/main/soroban-env-host/src/native_contract/token/balance.rs#L61) values even if there is no [AssetInfo](https://github.com/stellar/rs-soroban-env/blob/main/soroban-env-host/src/native_contract/token/contract.rs#L141) ledger entry present. Even though it is possible that Horizon will store asset stats for fake token contracts, those asset stats will never be exposed in the asset stats endpoint because we will make sure the response only includes asset stats which have an  [AssetInfo](https://github.com/stellar/rs-soroban-env/blob/main/soroban-env-host/src/native_contract/token/contract.rs#L141) present in the ledger.

It would be ideal if we could avoid having to store asset stats for fake token contracts but this is an acceptable tradeoff if we consider the alternative of augmenting [BalanceValue](https://github.com/stellar/rs-soroban-env/blob/main/soroban-env-host/src/native_contract/token/balance.rs#L61) ledger entries with additional fields so we can verify they come from legitimate Stellar Asset contracts. 

More context and discussion is [on Slack](https://stellarfoundation.slack.com/archives/C02B04RMK/p1693238533355599).

**Comment by Shaptic** [comment]
> it is possible to have a Stellar asset which is held by 0 accounts and a non-zero amount of smart contracts

Wat :flushed: why would someone do this :sob: either way, I guess we need to consider it. Thanks for noting that, even though I hate it.

> if we don't ingest the asset info ledger entry

And even if we do, we run into the same expiration + catch-up issue as described here... Dang.

----------

Another alternative, then: could we relate the balance entries to events? Those have the asset info, so we could fill it out accordingly. I guess we wouldn't have the right auth flags, though... Maybe this is the only way.
