### ISSUE TITLE
Use COPY to speed up all ChangeProcessors

### ISSUE THREAD

**Issue by tamirms** [stellar/go#5098]
In https://github.com/stellar/go/issues/5086 we improved performance of the ClaimableBalancesChangeProcessor by using COPY to bulk insert claimable balance rows. We should use COPY to improve the performance of all the remaining change processors.

Most of the change processors combine new ledger entries and updates of existing ledger entries into a single list which is then upserted into the DB. We should change this workflow so that we handle new ledger entries separately from updating existing ledger entries because we can bulk insert new ledger entries efficiently with COPY.

The claimable balance change processor has already been taken care of in https://github.com/stellar/go/issues/5086 and the asset stats processor is still in flux because of https://github.com/stellar/go/pull/5033 . So we should implement the COPY optimization on the following remaining change processors:  

- [x] [SignersProcessor](https://github.com/stellar/go/blob/d50c63e68acca8e2c59e2a8c53d167665d18e7e9/services/horizon/internal/ingest/processors/signers_processor.go#L14)
- [x] [AccountDataProcessor](https://github.com/stellar/go/blob/d50c63e68acca8e2c59e2a8c53d167665d18e7e9/services/horizon/internal/ingest/processors/account_data_processor.go#L12)
- [x] [AccountsProcessor](https://github.com/stellar/go/blob/d50c63e68acca8e2c59e2a8c53d167665d18e7e9/services/horizon/internal/ingest/processors/accounts_processor.go#L13)
- [x] [LiquidityPoolsChangeProcessor](https://github.com/stellar/go/blob/d50c63e68acca8e2c59e2a8c53d167665d18e7e9/services/horizon/internal/ingest/processors/liquidity_pools_change_processor.go)
- [x] [OffersProcessor](https://github.com/stellar/go/blob/d50c63e68acca8e2c59e2a8c53d167665d18e7e9/services/horizon/internal/ingest/processors/offers_processor.go#L16)
- [x] [TrustLinesProcessor](https://github.com/stellar/go/blob/d50c63e68acca8e2c59e2a8c53d167665d18e7e9/services/horizon/internal/ingest/processors/trust_lines_processor.go#L12)

I anticipate that once COPY is used in all the change processors, ingesting from the history archives will be significantly faster, which means that state rebuilds will much faster than before.

**Comment by hethm999** [comment]
ok
