### ISSUE TITLE
there should only be one Asset struct

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/go#51]
now there is 
build.Asset
and
horizon.Asset

**Comment by howardtw** [comment]
@jedmccaleb looks like `build.Asset` is used by all the services other than `horizon` and it also looks like it's being replaced by [txnbuild.Asset](https://github.com/stellar/go/blob/6d23756a0e48d08db1b927e08089f84ea2879e51/exp/txnbuild/asset.go#L9-L12). Did you want to take `Asset` out from `protocols/horizon/base` and put it in the top level of `protocols` and have every single service use it? cc @ire-and-curses

**Comment by ire-and-curses** [comment]
In `txnbuild`, I ended up [implementing](https://github.com/stellar/go/blob/master/txnbuild/asset.go) an `Asset` interface, and then simple structs for `NativeAsset` and `CreditAsset`. I'm not sure how much value I see in combining the types here.

**Comment by howardtw** [comment]
@ire-and-curses is this still relevant? It was assigned to me a long time ago.
