### ISSUE TITLE
Failed migration database

### ISSUE THREAD

**Issue by Arkptz** [stellar/go#5107]
Docker Image - stellar/stellar-horizon:2.26.1
I ran it with helm-chart - https://helm.stellar.org/charts/horizon  v0.0.7

I ger error:
`2023/11/10 08:29:58 Applying DB migrations...
could not apply migrations: pq: relation "history_trades_60000" already exists handling 47_precompute_trade_aggregations.sql
2023/11/10 08:30:19 Applying DB migrations...
could not apply migrations: pq: relation "history_trades_60000" already exists handling 47_precompute_trade_aggregations.sql
2023/11/10 08:30:41 Applying DB migrations...
could not apply migrations: pq: relation "history_trades_60000" already exists handling 47_precompute_trade_aggregations.sql
2023/11/10 08:31:28 Applying DB migrations...
could`

**Comment by mollykarcher** [comment]
@Arkptz this looks like you had a partially created/migrated database before. Our [developer discord](https://discord.gg/5UBnSTba) is a better place to get support in debugging your own instance/setup. If you do find that there is still a real bug, please refile an issue but we need more specific details on how to reproduce the issue (ie. exact commands you're running).
