### ISSUE TITLE
services/horizon/ingest: remove the force flag on reingestion cmds

### ISSUE THREAD

**Issue by sreuland** [stellar/go#5128]
### What problem does your feature solve? 
the [force flag](https://github.com/stellar/go/blob/master/services/horizon/cmd/db.go#L254) is incompatible with the new flushed data-flow of ingestion where we batch multiple ledgers in a single transaction, done in prior #5099

### What would you like to see?
removal of force flag to avoid unintended mis-use

**Comment by tamirms** [comment]
Actually, we can close this issue. The force flag is only incompatible when you have parallel workers and we already check for that:

https://github.com/stellar/go/blob/master/services/horizon/cmd/db.go#L398-L400
