### ISSUE TITLE
services/horizon: test live ingestion + reingestion performance improvements

### ISSUE THREAD

**Issue by mollykarcher** [stellar/go#5133]
First phase of [ingestion performance improvements](https://github.com/orgs/stellar/projects/37/views/16) are ready to release. As part of this process we'll want to:
- run verify-range on full history, to ensure no regressions in ingestion
- benchmark _old_ live ingestion against the new version, so that we can report comparisons/improvements gained from this work
- benchmark _old_ historical reingestion (for some limited amount of history) against the new version, so that we can report comparisons/improvements gained from this work

**Comment by sreuland** [comment]
concluded testing/verification exercises and captured [writeup as doc for review](https://docs.google.com/document/d/1hxWY2i41o1b6_wcEyyXlzNt1msFpKiRuhKEI0jyEu50/edit#heading=h.kvfiet2qfiqs).

**Comment by sreuland** [comment]
review of doc feedback has wound down, [summarized here](https://docs.google.com/document/d/1hxWY2i41o1b6_wcEyyXlzNt1msFpKiRuhKEI0jyEu50/edit#heading=h.kaiwwnb3j49v)

the net take-away is a few issues that will need to be addressed prior to releasing:
[go/5152](https://github.com/stellar/go/issues/5152) - fix logging output for `Processed ledger`
[go/5156](https://github.com/stellar/go/issues/5156) - fix logging output for `Reingestion done`
[go/5153](https://github.com/stellar/go/issues/5153) - don't do core cursor update when captive core in effect
[go/5127](https://github.com/stellar/go/issues/5127) - fix rebuild trade agg buckets during parallel worker reingestion state.

closing this ticket, it has provided the requested benchmarks.
