### ISSUE TITLE
Fix slow query in Payments for Account endpoint

### ISSUE THREAD

**Issue by bartekn** [stellar/go#515]
`history_operation_participants` has a composite index `hist_op_p_id` on `(history_account_id, history_operation_id)` fields. When running "payments for account" query:
```sql
SELECT hop.id, hop.transaction_id, hop.application_order, hop.type, hop.details, hop.source_account, ht.transaction_hash FROM history_operations hop LEFT JOIN history_transactions ht ON ht.id = hop.transaction_id JOIN history_operation_participants hopp ON hopp.history_operation_id = hop.id WHERE hop.type IN ($1,$2,$3,$4) AND hopp.history_account_id = $5 AND hop.id > $6 ORDER BY hop.id asc LIMIT 10
```
Postgres query planner opt to use `history_account_id` part of the index and because  `history_operation_id` is not used in a query the execution was slow.

This can be fixed by changing the query to use `hopp.history_operation_id` instead of `hop.id` when filtering and ordering results. The query is equivalent to the previous one but is using all fields of `history_operation_participants.hist_op_p_id` index.

Initial fix in #439 but was closed because the code should be improved.

**Comment by howardtw** [comment]
@bartekn Is this PR still blocked by the improvement of the query builder as suggested here https://github.com/stellar/go/pull/439#issuecomment-388421122? Do we have a ticket for the improvement?

**Comment by bartekn** [comment]
@howardtw it's not an issue with the query builder, more with PR #439. It was a _quick fix_ so it just requires better code to fix this issue.
