### ISSUE TITLE
tag 2.27.0 is having issue where stellar core is failing to run inside the horizon for testnet servers

### ISSUE THREAD

**Issue by ggangisettiqn** [stellar/go#5151]
### What version are you using? 

2.27.0

### What did you do? 

after the latest protocol release, i wanted to upgrade my testnet servers from tag 2.27.0-rc2-384 to tag 2.27.0 (released on dec 18)

### What did you expect to see?

stellar core should be able to run, as there were no major fixes to be done on my code

### What did you see instead?

`time="2024-01-05T08:28:37.977Z" level=warning msg="could not load stellar-core info: http request errored: Get \"http://localhost:11626/info\": dial tcp 127.0.0.1:11626: connect: connection refused" pid=1
time="2024-01-05T08:28:37.977Z" level=error msg="failed to load the stellar-core info" err="http request errored: Get \"http://localhost:11626/info\": dial tcp 127.0.0.1:11626: connect: connection refused" pid=1 stack="[main.go:43 client.go:139 app.go:230 app.go:442 asm_amd64.s:1598]"`

this is my docker run command i am using earlier

`docker run --name horizon   --network=host --rm --mount type=bind,source=/etc/default/horizon-stellar-captive-core.toml,target=/etc/default/stellar-captive-core.toml  --mount type=bind,source=/etc/default/stellar-horizon,target=/etc/default/stellar-horizon -e NETWORK=testnet -e DATABASE_URL=postgres://postgres:xxxxxxxxxxxx@xxxxxxxx:5432/postgres?sslmode=disable -e PER_HOUR_RATE_LIMIT=0 -e INGEST=true -e STELLAR_CORE_BINARY_PATH=/usr/bin/stellar-core stellar/stellar-horizon:2.27.0 --apply-migrations`

after all the possible tries. I manually did a private build on my server and made the server work.

I pulled the latest (with head point to b0220a0d92ba925cfb22f976f7805f4c4a3b4992 this commit) and generated a docker image using docker compose in the latest. This docker image seems to be working for me to bring up the chain.

these are versions of stellar inside my private build container

`
stellar-core-prometheus-exporter/now 0.10.5-18 amd64 [installed,local]
stellar-core-utils/now 0.2-9 amd64 [installed,local]
stellar-core/now 20.0.2-1633.669916b56.focal amd64 [installed,local]
stellar-horizon-utils/now 0.3-5 amd64 [installed,local]
stellar-horizon/now 2.28.0~rc1-396 amd64 [installed,local]`

looks like 2.28.0~rc1-396 is working but not 2.27.0

**Comment by mollykarcher** [comment]
`2.28.0` is now officially released
