### ISSUE TITLE
"Processed Ledger" logged twice during resume state

### ISSUE THREAD

**Issue by tamirms** [stellar/go#5152]
In the release-horizon-v2.28.0 branch, the "Processed Ledger" message is logged twice whenever a ledger is ingested in the resume state:

1. https://github.com/stellar/go/blob/release-horizon-v2.28.0/services/horizon/internal/ingest/fsm.go#L560
2. https://github.com/stellar/go/blob/release-horizon-v2.28.0/services/horizon/internal/ingest/processor_runner.go#L356

The first case includes a duration field which measures the total time to ingest the ledger through all the processors.
The second case also includes a duration field, however, that field only measures the time to run the transaction processors.

We should only be logging the first case during resume state ingestion. This bug was introduced in https://github.com/stellar/go/pull/5117

In 2.27.0 we never logged the "Processed Ledger" message in processor runner:

https://github.com/stellar/go/blob/release-horizon-v2.27.0/services/horizon/internal/ingest/processor_runner.go

The  "Processed Ledger" message was logged only in fsm during the resume state and the other states which only reingested history. We should fix this bug and ensure that "Processed Ledger" is only logged once per ledger in every state of the fsm (resume, reingest history, etc)

**Comment by sreuland** [comment]
https://github.com/stellar/go/pull/5155

**Comment by sreuland** [comment]
merged
