### ISSUE TITLE
No need to update cursor when ingesting from captive core

### ISSUE THREAD

**Issue by tamirms** [stellar/go#5153]
As @sreuland reported, we always update the cursor via the stellar core client in the resume state:

https://github.com/stellar/go/blob/master/services/horizon/internal/ingest/fsm.go#L526

We should only be doing this if we're running legacy ingestion via the stellar core postgres DB. When running captive core, there is no need to update the cursor.

**Comment by sreuland** [comment]
https://github.com/stellar/go/pull/5158 merged
