### ISSUE TITLE
services/horizon/ingest: new metric label for bytes-downloaded on history archive metrics

### ISSUE THREAD

**Issue by sreuland** [stellar/go#5186]
### What problem does your feature solve?
bytes downloaded per HA server is not captured in metrics, just count of download attempts

### What would you like to see?
`bytes_downloaded` label added to`history_archive_stats_total` , grouped per `source` label, i.e an individual HA server

**Comment by Shaptic** [comment]
Great call to captive this in an issue, and `bytes_cached` would be really useful as a comparison.

**Comment by sreuland** [comment]
@Shaptic , i think this ticket can be closed, looks like implemented on https://github.com/stellar/go/pull/5197, want to add retro points?

**Comment by Shaptic** [comment]
Nice catch @sreuland! Done - I think 2 points is reasonable to cover code + test + grafana work?
