### ISSUE TITLE
horizon: meta should be returned as null rather than empty when `SKIP_TXMETA` enabled

### ISSUE THREAD

**Issue by mollykarcher** [stellar/go#5221]
Original issue here https://github.com/stellar/go/issues/5189

Our original implementation of this had the API returning valid but empty metas. This seems to have been a miscommunication as the product request was for the API to return `null`. We should update the API responses to return null rather than empty metas.

**Comment by mollykarcher** [comment]
To be released in 2.28.4

**Comment by sreuland** [comment]
this went out in 2.29.0 release.
