### ISSUE TITLE
stellar-horizon startup doesn't look normal

### ISSUE THREAD

**Issue by airstring** [stellar/go#5222]
### What version are you using?
1.stellar-core 20.2.0 (34d82fc00426643e16b7ad59c9fde169b778eb4b)
2.stellar-horizon 2.28.3-fa5404bc79ba72ec9311e063e1a27cd5712941be

### What is the exec-command?
1.stellar-core
   /data/xlm/bin/stellar-core --conf /data/xlm/conf/stellar-core.cfg run
2.stellar-horizon
    export HISTORY_ARCHIVE_URLS="https://history.stellar.org/prd/core-live/core_live_001/" && export NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015" && export DATABASE_URL="dbname=horizon host=localhost user=stellar password=xx" &&export STELLAR_CAPTIVE_CORE_HTTP_PORT=0 && export STELLAR_CORE_URL="http://localhost:11626/" && export CAPTIVE_CORE_CONFIG_PATH="/data/xlm/conf/stellar-captive-core.cfg" && export STELLAR_CORE_BINARY_PATH="/data/xlm/bin/stellar-core" && nohup /data/xlm/bin/stellar-horizon serve > stellar-horizon.log 2>&1 &
### What is the problem?
stellar-core starts successfully.
stellar-horizon startup doesn't look normal.Keep scrolling down the contents repeatedly.
![image](https://github.com/stellar/go/assets/26688391/186ebe44-1c00-4e48-a45d-5eacd433ad2d)
![image](https://github.com/stellar/go/assets/26688391/d4b6435e-5dd8-47ec-9b34-2e804dbd8d95)

The horizon database in postgres also has no data.
![image](https://github.com/stellar/go/assets/26688391/8db09848-cad6-47cb-af36-8ec815b21797)

**Comment by sreuland** [comment]
it looks like captive core is trying to sync up to pubnet network, is the intention to run horizon with ingestion of pubnet data? If so, can simplify the approach at runtime, don't need to run multiple core instances, i.e. a standalone core process first, instead horizon will spawn a new child process with core binary found at `STELLAR_CORE_BINARY_PATH` as the 'captive' core process for ingestion automatically, thereby reducing number of core processes running on your machine to just that one, as running two simultaneously, both on pubnet, may be taxing on compute resources of single host, slowing performance.

you can leverage the new `NETWORK` config parameter as of [2.27.0](https://github.com/stellar/go/releases/tag/horizon-v2.27.0) to handle most of the pubnet config automatically, see if following this [Single Instance Horizon deployment recommendation](https://developers.stellar.org/docs/run-platform-server/configuring#single-instance-deployment) works out better:

```
$ export NETWORK="pubnet" export DATABASE_URL="dbname=horizon host=localhost user=stellar password=xx" export STELLAR_CORE_BINARY_PATH="/data/xlm/bin/stellar-core" stellar-horizon serve 
```

**Comment by sreuland** [comment]
closing for now, please respond if this doesn't resolve issue, thanks!
