### ISSUE TITLE
add base offer id and counter offer id to trade resource and ingestion

### ISSUE THREAD

**Issue by tomerweller** [stellar/go#527]
### Problem

Tom submits an offer. Part of that offer is immediately matched with a previous offer in the order-book (trade a).  The remainder is persisted in the order book and is later matched with a new offer (trade b).  
While trades a and b result from the same offer, it is impossible to link them together based on the trade resources alone.

### Proposal

- Add `base_offer_id` and `counter_offer_id` to trade ingestion
Determining the `offer_id` for the taking offer (the "bid") : If the taking offer was only partially consumed, it will have the same `offer_id` as the offer that was saved in the orderbook. If the taking offer was fully consumed, no `offer_id` will be given to it. 
- Modify `Trade` resource to include the offer ids. In case of a missing id, The respective `offer_id` in the resulting trade resource  will have a null value.
- Modify the "Trades for Offer" endpoint to search in both `base_offer_id` and `counter_offer_id`.

**Comment by nullstyle** [comment]
At first glance, I think your proposal makes sense and I have no objections to it.  It's considtent with the existing design of `horizon_trades`. I'll add a grain of salt though by reminding you that I generally have pretty poor intuition about the trading portions of our API.  

 The wonkiness you mentioned in standup is just the nature of tradeoffs we made when moving from the previous model of representing trades as effects to `history_trades`.  The question "What trades occurred as a result of my offer X" requires a perspective to answer. Unfortunately `history_trades` is a representation of a two-way interaction that is without perspective.  We get to pay the cost of "reifying perspective" in our query by having goofy OR clauses (In other words, a trade is a result of my offer if `base_offer_id = X OR counter_offer_id = X `).  Does that make sense?

 I think it is worth including design impedances like this when we consider our upcoming "multihorizon" project (for lack of some other name) that we talked about during our roadmap meetings. The real wonkiness here, IMO, is that we don't have a mechanism to let end users have more control over how their horizon instance ingests data from the network. The end user should be able to choose whether a representation with perspective or without is the most appropriate form for their use case.
