### ISSUE TITLE
LoadAccountMergeAmount does not check for horizon error

### ISSUE THREAD

**Issue by mlsteele** [stellar/go#529]
[`Client.LoadAccountMergeAmount`](https://github.com/stellar/go/blob/master/clients/horizon/client.go#L269) makes a request to horizon but does not check for an error. As a result if there is a horizon error it will likely always return this error, instead of the horizon error.
```
Could not find `account_credited` effect in `account_merge` operation effects`.
```

It should probably use something like [decodeResponse](https://github.com/stellar/go/blob/4c8cfd0/clients/horizon/internal.go#L16) to unmarshal the horizon response. Although I don't understand why that method accepts http status [200, 300) instead of just 200.

Here is a hacked up [standalone example](https://play.golang.org/p/h3avUsBe33C) of the gist of this bug.

**Comment by robertDurst** [comment]
Good catch! Checking this out

**Comment by robertDurst** [comment]
Opening a pr -- yes, this should use `decodeResponse` since `decodeResponse` does more than just decode, it checks status and then if it is unsuccessful, returns the error.
