### ISSUE TITLE
Horizon reaper can run on multiple horizon nodes at the same time

### ISSUE THREAD

**Issue by tamirms** [stellar/go#5339]
SDF uses a horizon architecture where there are multiple ingesting nodes and multiple request serving nodes. If reaping is enabled on multiple nodes, there is nothing preventing two horizon nodes from reaping at the same time. Redundant reaping processes are wasteful because we end up repeating the same delete statements which result in unnecessary extra load on the horizon DB.

As a workaround we can enable reaping on only 1 Horizon node. However, the ideal solution would be to allow multiple Horizon nodes to coordinate so that only 1 node can reap at a time. We already do something similar for ingestion (only 1 horizon node can ingest at time).

**Comment by JakeUrban** [comment]
Hey Tamir, do you mind explaining how we support multiple ingestion nodes? Whats the point of this too, if only one node can ingest at a time?

**Comment by JakeUrban** [comment]
> the other nodes who attempted to acquire the lock realize the ledger has already been ingested and so they release the lock as well

Got it, how do nodes realize the ledger was ingested? Do they make a DB query to confirm?

**Comment by tamirms** [comment]
@JakeUrban yeah, they query the latest ledger in the db and if it's greater than or equal to the ledger they're about to ingest that means the ledger has already been ingested.
