### ISSUE TITLE
ingest/ledgerbackend: getLogLineWriter() leaks goroutines and pipes

### ISSUE THREAD

**Issue by 2opremio** [stellar/go#5342]
`getLogLineWriter()` creates a pipe and a goroutine, but the goroutine sometimes doesn't exit (and the pipe is never released).

Every time captive core is restarted this causes a leak.

The easiest fix is probably returning a `CloseWriter` and making sure that the writer is closed (releasing the pipe and the goroutine).

**Comment by 2opremio** [comment]
Discovered while investigating https://github.com/stellar/soroban-rpc/pull/207

**Comment by 2opremio** [comment]
It turns out the goroutines are closed in many places but something must be amiss, since they are still left behind in some cases. All the `(*pipe).read` goroutines in this dump are from `Closed()` core ledger backends:


<img width="700" alt="Screenshot 2024-06-13 at 17 30 56" src="https://github.com/stellar/go/assets/2362916/43558679-1295-4b62-ada5-913cb47aad03">

**Comment by 2opremio** [comment]
I think `stellarCoreRunner.handleExit()` may not be closing the pipes in some cases

**Comment by 2opremio** [comment]
Here's another dump:

<img width="691" alt="Screenshot 2024-06-13 at 18 28 57" src="https://github.com/stellar/go/assets/2362916/02109d27-01c5-401c-92f5-d7707996325e">

**Comment by tamirms** [comment]
It looks like there are createCmd calls where we do not close the log line writers:

https://github.com/stellar/go/blob/a4e5a3fc6664f7cf6b26fb3196b366910563636f/ingest/ledgerbackend/stellar_core_runner.go#L311

https://github.com/stellar/go/blob/a4e5a3fc6664f7cf6b26fb3196b366910563636f/ingest/ledgerbackend/stellar_core_runner.go#L400-L404

https://github.com/stellar/go/blob/a4e5a3fc6664f7cf6b26fb3196b366910563636f/ingest/ledgerbackend/stellar_core_runner.go#L311
