### ISSUE TITLE
Changing Horizon HAL base path

### ISSUE THREAD

**Issue by edunuzzi** [stellar/go#535]
Hi, I am running a Horizon instance that sits behind a load balancer. My problem is that the base path inside the `_links` attribute gives me the instance URL, which is different than the one I am using (load balancer's). 

Does anyone have any suggestions to deal with this kind of architecture?

**Comment by bartekn** [comment]
Probably changing https://github.com/stellar/go/blob/49a0d85c4217dc38f7576c058e31a8653b2f20b2/services/horizon/internal/httpx/base_url.go#L29 to `r.Header.Get("Host")` should fix this.

**Comment by edunuzzi** [comment]
Actually, i realized that the actual implementation already works. Using `r.Host` checks for the `Host` header in the request. I just had to include it on all requests by default.

Thanks a lot @bartekn!
