### ISSUE TITLE
Document sub-resources

### ISSUE THREAD

**Issue by nullstyle** [stellar/go#537]
Accounts are composite resources; They contain an array of balances and an array of signers, for example.  We should document these portions of horizon's protocol.

## Non-Exhaustive List

- Balances
- Signers
- Flags on issued assets

**Comment by robertDurst** [comment]
Here is the list I came up with:
* Signers
* Balances
* Flags on assets
* price (how it is represented by Horizon)
* payment path
* orderbook bids (maybe)
* thresholds (some sort of link back to accounts)
