### ISSUE TITLE
Intermittent 500 errors from Horizon

### ISSUE THREAD

**Issue by tomquisel** [stellar/go#538]
This issue occurs intermittently for Horizon version `snapshot-snapshots-2-g49a0d85`, but was not seen in `snapshot-c5fe0ff` (although it could still exist there, as the issue occurs intermittently).

Reproduction steps:

1. Submit an offer with account A that does not immediately get taken
1. Immediately after (within 1s) request `/accounts/{account_id}/offers` for account A

Intermittently, the second request will respond with a 500 error. It appears to happen in streaks: if a Horizon server experiences the issue once, it will likely occur again the next time you try to reproduce. Similarly, if it doesn't happen the first time, it probably won't happen for a while.

It's not particularly helpful, but here's an example of Horizon's logs from one such event:

```
time="2018-07-12T20:43:04Z"
level=info
msg="Finished request"
bytes=470
duration=9.779893ms
host=horizon-stellarx.stellar.org
ip="[2604:2000:12c1:460b:0:740e:c14a:96e]:35045"
method=GET
path="/accounts/GBNDB4UHLDRBLR35JNU4ADYG3J5WA4LJZOPBXMNHZKTKSL37BDX4UBQY/offers?limit=50&c=0.9582919216768715"
pid=11539
req="horizon-stellarx-002c/TEA0BtkP5Y-295077"
status=500
streaming=false
```

**Comment by tomquisel** [comment]
Not that I can see, although I'm only using the Kibana logstash view.

Below are the start and finish log lines for another example of this, with no other log entries in between:

![image](https://user-images.githubusercontent.com/1427679/43093584-54f926c6-8e65-11e8-9d92-0aa77d64416f.png)

**Comment by bartekn** [comment]
Tracking in https://github.com/stellar/go/issues/650.
