### ISSUE TITLE
Not able to run Ticker on Docker.

### ISSUE THREAD

**Issue by akhilparakka** [stellar/go#5419]
### What did you do?
I am trying to run ticker in docker. I followed the steps as mention in the readme. 
First error I encountered was
```bash
unknown directive: toolchain
```

I fixed it by changing the base image to 
```
FROM golang:1.22.6 as build
```
The next was
```
E: The repository 'http://apt.postgresql.org/pub/repos/apt stretch-pgdg Release' does not have a Release file.
```

I changed it to
```
deb https://apt-archive.postgresql.org/pub/repos/apt stretch-pgdg main
```
The error was

```bash
29.07 The following packages have unmet dependencies:
29.14  postgresql-9.5 : Depends: libldap-2.4-2 (>= 2.4.7) but it is not installable
29.14                   Depends: libssl1.1 (>= 1.1.0) but it is not installable
29.14                   Recommends: sysstat but it is not going to be installed
29.14  postgresql-contrib-9.5 : Depends: libssl1.1 (>= 1.1.0) but it is not installable
```

### What did you expect to see?
Expected to run ticker in docker

### What did you see instead?
Postgres Dependency errors.

Any help is appreciated.

**Comment by leighmcculloch** [comment]
It appears that there are not tests for the `ticker` docker image and when the following changes were made there were other changes needed to keep the image in a working state:
- https://github.com/stellar/go/pull/5103
- https://github.com/stellar/go/pull/5232

We could include in ci a build check of all the docker images in this repo. Although this issue occurs rarely.

@akhilparakka The updates you suggest sound about right. A different postgres deb link is probably needed, probably the `jammy` one instead of the `stretch` one to align with the 22.04 ubuntu image.

**Comment by akhilparakka** [comment]
> It appears that there are not tests for the `ticker` docker image and when the following changes were made there were other changes needed to keep the image in a working state:
> 
> * [Switch Ubuntu to 22.04 from 20.04 in Dockerfile base #5103](https://github.com/stellar/go/pull/5103)
> * [Bump go version to 1.22 #5232](https://github.com/stellar/go/pull/5232)
> 
> We could include in ci a build check of all the docker images in this repo. Although this issue occurs rarely so probably not worth adding unless this becomes a recurring issue.
> 
> @akhilparakka The updates you suggest sound about right. A different postgres deb link is probably needed, probably the `jammy` one instead of the `stretch` one to align with the 22.04 ubuntu image.

Fixed the issue by bumping the image version and using
```
deb http://apt.postgresql.org/pub/repos/apt/ jammy-pgdg main
```

**Comment by leighmcculloch** [comment]
Reopening so the issue remains open till the image is fixed in this repo.

@akhilparakka would you be up for opening a pull request with the fix you used to get it working?

**Comment by akhilparakka** [comment]
Would be happy to help out. But even after i get the image running, It stops with
```
evel=fatal msg="could not upgrade the database:pq: syntax error at or near \"AS\" handling 20220909100700-trades_pk_to_bigint.sql" pid=99
```
