### ISSUE TITLE
services/galexie: docker build and runtime debian inconsistency

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/go#5430]
The docker image for the `galexie` service is a multi-step build.

The build is performed with the `golang:1.22-bullseye` image, based on Debian 11 (bullseye).

https://github.com/stellar/go/blob/f2f4a0e085ed09426df7da6e13c299f8365b1b40/services/galexie/docker/Dockerfile#L1

The image used for running is the `ubuntu:22.04` image, based on Debian 12 (bookworm).

https://github.com/stellar/go/blob/f2f4a0e085ed09426df7da6e13c299f8365b1b40/services/galexie/docker/Dockerfile#L15

The inconsistency is a pretty minor thing if galexie doesn't use cgo, and may have no material impact at all. But I'm guessing the inconsistency is by accident, and we can probably update the golang image to build with bookworm to keep the OSes we're using and depending on consistently recent.

cc @urvisavla @stellar/platform-eng

**Comment by urvisavla** [comment]
@leighmcculloch  You're absolutely right - this was an oversight. I'll update it to `golang:1.22-bookworm`. Thanks!
