### ISSUE TITLE
Update Horizon ingestion and tests to support the new host function

### ISSUE THREAD

**Issue by Shaptic** [stellar/go#5437]
**Epic**: https://github.com/stellar/go/issues/5433
**Note**: All work should target a feature branch: [`protocol-22`](https://github.com/stellar/go/tree/protocol-22).
**Depends On**: #5423 

-------------------------

* Update Horizon's [operations_processor.go](https://github.com/stellar/go/blob/master/services/horizon/internal/ingest/processors/operations_processor.go#L672) to inspect the new type
* Ensure that Horizon's [invocation](https://github.com/stellar/go/blob/master/services/horizon/internal/integration/invokehostfunction_test.go) and [SAC tests](https://github.com/stellar/go/blob/master/services/horizon/internal/integration/sac_test.go) use / validate the new type

**Comment by tamirms** [comment]
implemented in https://github.com/stellar/go/pull/5488
