### ISSUE TITLE
protocols/horizon: Remove deprecated API fields

### ISSUE THREAD

**Issue by Shaptic** [stellar/go#5438]
**Epic**: #5433 

-----------------------

There are several API fields that have been deprecated for a very long time. We should remove them as part of the Protocol 22 release in which we will change to the protocol-specific versioning scheme (i.e. `horizon-v22.0.0`).

The following API fields are deprecated:

* In `/assets`, the `num_accounts` and `amount` fields:

https://github.com/stellar/go/blob/dfabe31b5b89cb235e81732d708a3f5bdeff507a/protocols/horizon/main.go#L180-L187

* In `/transactions/:id` (or any paginating variant), the `valid_before` and `valid_after` fields, because users should instead check the transaction's preconditions which can have way more than time bounds:

https://github.com/stellar/go/blob/dfabe31b5b89cb235e81732d708a3f5bdeff507a/protocols/horizon/main.go#L536-L538

**Comment by sreuland** [comment]
should this effort include a coordinated outreach/blast to sdk's for notice? a separate ticket for cleanup of the same in js-sdk?
