### ISSUE TITLE
Many of the current doc examples are out of date

### ISSUE THREAD

**Issue by robertDurst** [stellar/go#544]
When I was a Stellar Newbie, I got tripped up when I tried to copy-pasta example code/curl snippets and they:

* didn't work
* presented different output than expected

Would be a good use of time to spend an hour and make sure all examples in docs are correct.

**Comment by robertDurst** [comment]
WIP: #549

**Comment by theaeolianmachine** [comment]
Resolved through #1130, #1129, #1127, #1124, #1119, #1118, and #1112.
