### ISSUE TITLE
services/galexie: publish grafana dashboard

### ISSUE THREAD

**Issue by mollykarcher** [stellar/go#5458]
This work should include:
- [x] Update the namespace of all metrics in application code to "galexie" from "ledger exporter"
- [x] Final review / audit on [existing dashboard](https://grafana.stellar-ops.com/d/jyuDB-lSk/ledger-exporter?orgId=1&from=now-6h&to=now&var-Datasource=Prometheus&var-job=ledgerexporter-gcp-pubnet)
- [x] Move dashboard into source control in [puppet-v4 repo](https://github.com/stellar/puppet-v4/tree/master/modules/grafanaconfig/files/var/lib/grafana/dashboards) alongside other dashboards
- [x] Publish on grafana marketplace: https://grafana.com/orgs/stellar/dashboards

**Comment by urvisavla** [comment]
Dashboard published on Grafana https://grafana.com/grafana/dashboards/22285-stellar-galexie/
