### ISSUE TITLE
Trades Streaming Endpoint

### ISSUE THREAD

**Issue by sbsends** [stellar/go#546]
Is there any reason that the `/trades` endpoint does not have streaming capability? I think it would be useful to monitor recent trades. If no one is opposed, I am happy to implement code/PR that abides by the Stellar spec. 

@robertDurst

**Comment by sbsends** [comment]
@jedmccaleb @nullstyle

**Comment by tomquisel** [comment]
@bartekn @tomerweller this is something we'd love to have.

@sbsends I'm not sure how others feel, but I'd be excited if you implemented this.

**Comment by sbsends** [comment]
Closing due to no feedback. @tomquisel, I will let you know if I implement the streaming endpoint.

**Comment by bartekn** [comment]
Let's leave it open.

**Comment by bartekn** [comment]
Added in #647. Will be released in 0.15.0.

**Comment by sbsends** [comment]
Sweet! Thanks, @bartekn.
