### ISSUE TITLE
Don't use bufio.Scanner for streaming

### ISSUE THREAD

**Issue by raymontag** [stellar/go#548]
The streaming functions in clients/horizon use the Scanner type from bufio. However, it is possible that this breaks if a streamed token is too long which happens regularly for me (raising error with message "bufio.Scanner: token too long"). You should use bufio.Reader instead as the documentation states:

`Scanning stops unrecoverably at EOF, the first I/O error, or a token too large to fit in the buffer. When a scan stops, the reader may have advanced arbitrarily far past the last token. Programs that need more control over error handling or large tokens, or must run sequential scans on a reader, should use bufio.Reader instead. `

Refer to https://golang.org/pkg/bufio/#Scanner

**Comment by bartekn** [comment]
Thanks for catching this. The fix is in `master` branch.
