### ISSUE TITLE
bigint out of range

### ISSUE THREAD

**Issue by argjv** [stellar/go#566]
I'm using the quickstart setup for our stellar core and horizon but we are seeing the error in horizon after running it for a while:

level=error msg="import session failed: Ingestion.Flush error: Error adding values while inserting to history_transactions: Error adding values while inserting to history_transactions: exec failed: pq: bigint out of range"

I queries the table by MAX(id) and found the last transaction inserted belongs to ledger 10216114, which makes me think the problem is in the next one. However, I couldn't find any value bigger than 9223372036854775808

The only 2 bigint fields in that table are id and account_sequence.

Any idea what may be the issue?

**Comment by bartekn** [comment]
I believe this was fixed in 0.13.1 and Docker image has been updated too in https://github.com/stellar/docker-stellar-core-horizon/pull/67. You may just need to update the image:
```
docker rmi stellar/quickstart:latest
```
and then start it again, it will pull the latest version.

**Comment by argjv** [comment]
Thanks! But I'm not using docker.

`sudo apt-get update && sudo apt-get install stellar-horizon`

Says i'm in the latest version (0.13.0-18).

Is 0.13.1 available for package download?

**Comment by bartekn** [comment]
Let's track it in https://github.com/stellar/packages/issues/21. When it comes to alternatives you can download a binary here: https://github.com/stellar/go/releases/tag/horizon-v0.13.1.

**Comment by bartekn** [comment]
@argjv `0.13.1-20` has been published.

**Comment by argjv** [comment]
Awesome that works, thanks!
