### ISSUE TITLE
XDR serde of unsigned transactions

### ISSUE THREAD

**Issue by Synesso** [stellar/go#570]
There is a use-case for creating XDR of a transaction before it is signed. (e.g. https://stellar.stackexchange.com/questions/1358/how-to-sign-transaction-offline-with-go-sdk)

From what I can tell, no such ability exists in the Go SDK.

**Comment by frankegoesdown** [comment]
I write some trick via json
```
from := "SCRUYGFG76UPX3EIUWGPIQPQDPD24XPR3RII5BD53DYPKZJGG43FL5HI"

to := "GA3A7AD7ZR4PIYW6A52SP6IK7UISESICPMMZVJGNUTVIZ5OUYOPBTK6X"

passphrase := network.TestNetworkPassphrase

tx, err := b.Transaction(
	b.Network{passphrase},
	b.SourceAccount{from},
	b.AutoSequence{horizon.DefaultTestNetClient},
	b.Payment(
		b.Destination{to},
		b.NativeAmount{"0.5"},
	),
)
	
if err != nil {
	log.Println(err)
	return
}
bytes, err := json.Marshal(tx)
if err != nil {
	log.Println(err)
}
log.Println(string(bytes))
```
From `tx` struct we can get tx.HashHex() or other params
If we need to sign in in offline machine just unmarshal json

```
data := &b.TransactionBuilder{}
err = json.Unmarshal(bytes, data)
if err != nil {
     log.Println(err)
}
```
Maybe it can helps you

**Comment by sharmilan5** [comment]
Did you find any solution for the above issue ?
