### ISSUE TITLE
Receiving GOAWAY while streaming

### ISSUE THREAD

**Issue by raymontag** [stellar/go#573]
Sometimes while using the streaming functionality I get the following error:

    http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=""

Is there a correct way to handle this in order to establish a new streaming connection where the last one stopped?

**Comment by bartekn** [comment]
This is actually connected to AWS ELB: https://forums.aws.amazon.com/thread.jspa?threadID=246562 Please check AWS employee response.

**Comment by raymontag** [comment]
Thank you. For now I will just interpret the error of StreamPayments() (and the other streaming functions) and establish a new connection.
