### ISSUE TITLE
500 error publishing BumpSequenceOp to test-network

### ISSUE THREAD

**Issue by Synesso** [stellar/go#577]
[This transaction](https://www.stellar.org/laboratory/#xdr-viewer?input=AAAAAHGvaazr2%2BUfrfL8clS8kowU%2BSYY0%2Fati8DYov8WEwS5AAAAZACfyrgAAAABAAAAAAAAAAAAAAABAAAAAAAAAAsAn8q4AAAACQAAAAAAAAABFhMEuQAAAEDZemhEroIqvvrbusPC4kxAXFdtKUgssx0lrw5WSBo%2Bc9qNz5gd%2BccOrN309TS%2FiHc1v89Gz1qVq%2FbCLAOON8sP&type=TransactionEnvelope&network=test) with a single BumpSequenceOperation gave the following response via the lab:

```
{
  "type": "https://stellar.org/horizon-errors/server_error",
  "title": "Internal Server Error",
  "status": 500,
  "detail": "An error occurred while processing this request.  This is usually due to a bug within the server software.  Trying this request again may succeed if the bug is transient, otherwise please report this issue to the issue tracker at: https://github.com/stellar/go/services/horizon/internal/issues. Please include this response in your issue."
}
```

**Comment by Synesso** [comment]
Additionally, the error message asks that the issue be raised on a page that 404s.

**Comment by bartekn** [comment]
Testnet has not been upgraded to V10 yet. It will probably happen later today.

**Comment by Synesso** [comment]
Thanks. Obviously it downgrades the importance quite a bit, but what do you think about the HTTP response code 500? Is this a side-effect of deployment in progress?  Otherwise it should be a 4xx if the error is on the client side.

**Comment by bartekn** [comment]
Yeah, this probably shouldn't be 500. Have you sent this transaction to horizon-testnet.stellar.org?

**Comment by Synesso** [comment]
Yes, I sent the txn to horizon-testnet.stellar.org via the lab. 

I note that the same txn now results in HTTP 400 with `op_not_supported`, so it's either fixed (quick work!) or transient.
