### ISSUE TITLE
horizon reports wrong protocol version

### ISSUE THREAD

**Issue by tomerweller** [stellar/go#580]
The `protocol_version` field in the root resource reports core's maximum supported version rather than the actual protocol version used.

**Comment by bartekn** [comment]
The same issue in core: https://github.com/stellar/stellar-core/issues/1740 Hard to fix because some apps are relying on this but would be good to fix in the future.

**Comment by MonsieurNicolas** [comment]
For Horizon, if SDKs are relying on it, we should return it with the value of `latest_ledger.protocol_version` instead (and maybe add a new field to return the one that core supports, but I am not sure what people outside would use it for)

**Comment by bartekn** [comment]
Fixed in #783.
