### ISSUE TITLE
Build fails.  Unable to update checked out version

### ISSUE THREAD

**Issue by sgehrman** [stellar/go#582]
This did work, not sure what is going on today.  Let me know if you have any suggestions.

RUN mkdir -p /go/src/github.com/stellar/     && git clone --depth 1 --branch bifrost-v0.0.2 https://github.com/stellar/go.git /go/src/github.com/stellar/go     && cd /go/src/github.com/stellar/go     && curl https://glide.sh/get | sh     && glide install     && go install github.com/stellar/go/services/bifrost
 ---> Running in 767debb9f51a
Cloning into '/go/src/github.com/stellar/go'...
Note: checking out '9eb9682656c21d73a8fef16813872398ae6a6b6c'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4833  100  4833    0     0  19409      0 --:--:-- --:--:-- --:--:-- 19409
ARCH=amd64
OS=linux
Using curl as download tool
Getting https://glide.sh/version
TAG=v0.13.1
GLIDE_DIST=glide-v0.13.1-linux-amd64.tar.gz
Downloading https://github.com/Masterminds/glide/releases/download/v0.13.1/glide-v0.13.1-linux-amd64.tar.gz
glide version v0.13.1 installed successfully
[WARN]	Lock file may be out of date. Hash check of YAML failed. You may need to run 'update'
[INFO]	Downloading dependencies. Please wait...
[INFO]	--> Fetching bitbucket.org/ww/goautoneg
[INFO]	--> Fetching github.com/agl/ed25519

...

[INFO]	--> Setting version for gopkg.in/gorp.v1 to c87af80f3cc5036b55b83d77171e156791085e2e.
[ERROR]	Failed to set version on gopkg.in/fatih/set.v0 to 27c40922c40b43fe04554d8223a402af3ea333f3: Unable to update checked out version: exit status 128
[ERROR]	Failed to set references: Unable to update checked out version: exit status 128 (Skip to cleanup)
ERROR: Service 'bifrost' failed to build: The command '/bin/sh -c mkdir -p /go/src/github.com/stellar/     && git clone --depth 1 --branch bifrost-v0.0.2 https://github.com/stellar/go.git /go/src/github.com/stellar/go     && cd /go/src/github.com/stellar/go     && curl https://glide.sh/get | sh     && glide install     && go install github.com/stellar/go/services/bifrost' returned a non-zero code: 1

**Comment by bartekn** [comment]
`gopkg.in/fatih/set.v0 ` was recently archived. You need to apply this patch to make it working: https://github.com/stellar/go/commit/74039275798fb21c57873f20c5c9be27006c5210

**Comment by sgehrman** [comment]
Would building from the master branch rather than the bifrost branch also work?  Is that safe?

**Comment by bartekn** [comment]
Although Bifrost tests pass in master branch, I wouldn't recommend it for production use. Please use the tagged releases.
