### ISSUE TITLE
Error decoding horizon.Problem

### ISSUE THREAD

**Issue by matheusb-comp** [stellar/go#585]
Sometimes when [submitting transactions](https://godoc.org/github.com/stellar/go/clients/horizon#Client.SubmitTransaction) to `horizon-testnet.stellar.org`, the function takes a long time and returns the error:
```
error decoding horizon.Problem: invalid character '<' looking for beginning of value
```

Since it comes from the [JSON decoder](https://github.com/stellar/go/blob/master/clients/horizon/internal.go#L20), takes a long time to return the error, and the first caracter is a `<`, could it be that the SDK is receiving an HTML response on timeouts from the server?
Seems to be what happened in [this issue](https://github.com/digitalocean/godo/issues/142).

XDR of one of the transactions when this error happened:
```
AAAAAItx8cG/J56YwbIutCTzprPnWq/GKc5CShCp9+omK5x5AAAD6ABlHIsAABJ+AAAAAAAAAAEAAAAZRk9PSFRFU1QgZnVuZGluZyBhY2NvdW50cwAAAAAAAAoAAAAAAAAAAAAAAACDPZskt1fWv4MCLM/yuFRmQCH6R479ru2WidYwdaW/5wAAAAACfzVHAAAAAAAAAAAAAAAA5JgFIxTiqLIU+ZiHMaPcGdnXQPbDwxVVLNZR5ukkR9YAAAAAA4efRgAAAAAAAAAAAAAAAOMeefjGtROxRLokVaVEn8RqWpQnL+OdjQseXI5dE4vLAAAAAAN8BpYAAAAAAAAAAAAAAAArQDyggJ8uSgvyblgNYio1tbDSn2hgPgCk9GIrFff0ywAAAAACnqBdAAAAAAAAAAAAAAAAS/f9i4E0vibdRKWjYUaRZv05QksUzHRlmCduJjEeag8AAAAAAzrf6wAAAAAAAAAAAAAAACDq/lTiA3kQUruzoOM3R2wdlzuf9pgNGtbxwee3WqGJAAAAAAKKdAEAAAAAAAAAAAAAAADUBFHiaQ1BIO7wQFVA/KDJDNRb9ht5/b7nuWFpA+VdvAAAAAADC+OIAAAAAAAAAAAAAAAAKzPkUETXNKAO7O3RvlYGc0SbSlxxdRNjyVD0QMmNs/wAAAAAArvjZgAAAAAAAAAAAAAAAGlV/hD1leg0fLZg5lLSHtaZJem1EjoBS+4m9C64ljloAAAAAALhXxoAAAAAAAAAAAAAAACC5FUy5ygKuCuh4+Jc7lPe3Nxv2hjsuh9ajX3nN9ScdAAAAAACorIXAAAAAAAAAAEADynhAAAAQKc7lQOzdg2Giu1tzR+2XD5QaM3L5YfYZBPkjw4tauARKZ1JXawmU1ZTUT4+WazhNCFFaGhgyiK2E3LN8FflFgc=
```

**Comment by bartekn** [comment]
I think the reason might have been CloudFlare. We turned it off.
