### ISSUE TITLE
Getting started documentation broken

### ISSUE THREAD

**Issue by jzs** [stellar/go#59]
The code examples on: https://www.stellar.org/developers/guides/get-started/create-account.html are broken.

Let's take the first one as an example:

```
package main

import (
	"log"

	"github.com/stellar/go/keypair"
)

func main() {
	pair, err := keypair.Random()
	if err != nil {
		log.Fatal(err)
	}

	log.Println(pair.secret())
	// SAV76USXIJOBMEQXPANUOQM6F5LIOTLPDIDVRJBFFE2MDJXG24TAPUU7
	log.Println(pair.Address())
	// GCFXHS4GXL6BVUCXBWXGTITROWLVYXQKQLF4YH5O5JT3YZXCYPAFBJZB
}
```
I don't think it has ever worked as pair.secret is not an exposed method. On top of that there's no function anymore called secret. `pair.Seed()` maybe?

The second example has broken imports (`http` which should be `net/http`) and expects code from the first example (`pair.Address()`) to be present. At last `fmt.Println(body)` does not make much sense. Maybe a `fmt.Println(string(body))` would suffice here.
I suggest either remove the imports and main? or show a fully working example?

I haven't ran more examples through yet, but i have a feeling there's more broken stuff.

Besides, adding comments to exposed methods/functions is always a nice bonus ;-)
```
➜  github.com/stellar/go/keypair git:(master) ✗ golint
from_address.go:19:1: exported method FromAddress.Address should have comment or be unexported
from_address.go:23:1: exported method FromAddress.Hint should have comment or be unexported
from_address.go:28:1: exported method FromAddress.Verify should have comment or be unexported
from_address.go:42:1: exported method FromAddress.Sign should have comment or be unexported
from_address.go:46:1: exported method FromAddress.SignDecorated should have comment or be unexported
full.go:11:6: exported type Full should have comment or be unexported
full.go:15:1: exported method Full.Address should have comment or be unexported
full.go:19:1: exported method Full.Hint should have comment or be unexported
full.go:24:1: exported method Full.Seed should have comment or be unexported
full.go:28:1: exported method Full.Verify should have comment or be unexported
full.go:42:1: exported method Full.Sign should have comment or be unexported
full.go:47:1: exported method Full.SignDecorated should have comment or be unexported
```

About the lint messages, i could do a pull request on that, once i have read up a bit more on the stellar documentation :)

**Comment by jzs** [comment]
Gonna close this one and make some pull requests instead.

**Comment by jedmccaleb** [comment]
Thanks jzs. I'm going to leave it open though. normally we close it in the PR that fixes the issue. I'll mark as that you are doing it so we know :)

**Comment by jedmccaleb** [comment]
oh I see you already made the PR. awesome
