### ISSUE TITLE
Offers resource returns 200 with non-existent public key.

### ISSUE THREAD

**Issue by froocpu** [stellar/go#590]
The following request returns a status code of 200:

`curl https://horizon.stellar.org/accounts/yomama/offers`

This is the response body:

```json
{
  "_links": {
    "self": {
      "href": "https://horizon.stellar.org/accounts/yomama/offers?cursor=\u0026limit=10\u0026order=asc"
    },
    "next": {
      "href": "https://horizon.stellar.org/accounts/yomama/offers?cursor=\u0026limit=10\u0026order=asc"
    },
    "prev": {
      "href": "https://horizon.stellar.org/accounts/yomama/offers?cursor=\u0026limit=10\u0026order=desc"
    }
  },
  "_embedded": {
    "records": []
  }
}
```

The same happens on both the public and test networks. When the `/offers` resource is removed completely or replaced with another resource like `/payments` or `/transactions`, a 404 is returned. This seems to be inconsistent behaviour.

**Comment by robertDurst** [comment]
So the crux of this is 200 returned may mean either:
1. No account exists
2. No offers for said account

Not a priority to change for now, but will update the docs.

**Comment by froocpu** [comment]
Thanks @robertDurst. Are you saying that this is expected behaviour? I would expect a 200 where there are no offers on a valid account, but not when the account doesn't exist. Returning a 200 in that scenario could give the illusion that the account exists when it doesn't.

If it's a trivial change, I could take a crack at adding some error handling myself.
