### ISSUE TITLE
Should SCP Peer be part of stellar/go?

### ISSUE THREAD

**Issue by tinco** [stellar/go#595]
As part of my SBC submission I made a small Go library that uses stellar/go and some of Go's std crypto libraries to make connections to Stellar Core nodes.

With some cleanup and some tests I think it would fit well in the monorepo. Would you like me to see if I can make a PR to achieve this?

You can find the stellar peer at https://github.com/tinco/stellar-core-go

It's also got a few example stellar-core client tools, as well as a bunch of Ruby scripts implementing a stellar-core crawler, I'll simply rename the repository to just be the crawler if the peer is merged into stellar/go.

**Comment by 2opremio** [comment]
I will close this since no further work seems to have been done in this regard. @tinco I will be happy to reopen it if you think otherwise.
