### ISSUE TITLE
horizon binary always returns devel version

### ISSUE THREAD

**Issue by gituser** [stellar/go#599]
Hi.

I've just built latest branch `v0.13.2` and `horizon version` returns `devel` instead of `v0.13.2`, how do you add the correct version there when building?

Also tried this:

```
build-xenial:~/.gvm/pkgsets/go1.10.3/global/src/github.com/stellar/go/services/horizon$ export VERSION=v0.13.2
build-xenial:~/.gvm/pkgsets/go1.10.3/global/src/github.com/stellar/go/services/horizon$ go build -ldflags "-X main.version=$VERSION"
build-xenial:~/.gvm/pkgsets/go1.10.3/global/src/github.com/stellar/go/services/horizon$ ./horizon version
devel
```

Can you share the build script you're using to get the same binaries as posted in downloads?

Thanks.

**Comment by bartekn** [comment]
Builds for debian packages and GitHub releases are compiled using this [script](https://github.com/stellar/go/blob/master/support/scripts/build_release_artifacts/main.go). If you want to set version you need to pass a special param like:
```
go build -v -X github.com/stellar/go/support/app.version={version} ./services/horizon
```

**Comment by gituser** [comment]
@bartekn doesn't work for me:

```
build-xenial:~/.gvm/pkgsets/go1.10.3/global/src/github.com/stellar/go$ go build -v "-X github.com/stellar/go/support/app.version=$VERSION" ./services/horizon
flag provided but not defined: -X github.com/stellar/go/support/app.version
usage: build [-o output] [-i] [build flags] [packages]
Run 'go help build' for details.
```

**Comment by bartekn** [comment]
I updated the comment, please check it now.

**Comment by gituser** [comment]
ok, it works, thank you!
