### ISSUE TITLE
/assets numAccounts & amount incorrect

### ISSUE THREAD

**Issue by tomquisel** [stellar/go#606]
Check out what Horizon is reporting about `XIM` here: https://www.stellar.org/laboratory/#explorer?resource=assets&endpoint=single&values=eyJhc3NldF9jb2RlIjoiWElNIn0%3D&network=public

Currently, it shows the following:

- issuer: GBZ35ZJRIKJGYH5PBKLKOZ5L6EXCNTO7BKIL7DAVVDFQ2ODJEEHHJXIM
- numAccounts: 0
- amount: ""

Despite the fact that I and many others hold XIM.

Stellar.expert shows the real story: 
https://stellar.expert/explorer/public/asset/XIM-GBZ35ZJRIKJGYH5PBKLKOZ5L6EXCNTO7BKIL7DAVVDFQ2ODJEEHHJXIM

- numAccounts: 429
- amount: 10,000,000,000,000

Perhaps it's an issue with the 10T amount exceeding some check in Horizon?
@bartekn

**Comment by bartekn** [comment]
> Perhaps it's an issue with the 10T amount exceeding some check in Horizon?

It should be fixed after: https://github.com/stellar/go/pull/436 Let me check what's happening.

**Comment by bartekn** [comment]
Fix in #609.
