### ISSUE TITLE
Attempting to filter /trades by single asset returns 500

### ISSUE THREAD

**Issue by vcarl** [stellar/go#615]
Requesting `https://horizon.stellar.org/trades?base_asset_type=native` returns a 500 error. I'm thinking that filtering by a single half of the trade isn't supported, in which case this should be a 400 with some kind of message.

**Comment by ricardohsd** [comment]
@bartekn I was looking into this and I think you solved this on https://github.com/stellar/go/commit/044dc2a1#diff-1004c08360da885fe8a59bd5e06e454bR51

Or is it something else?

**Comment by bartekn** [comment]
Yeah, thanks!

**Comment by ricardohsd** [comment]
@bartekn I've created a PR adding test to cover the error message .
