### ISSUE TITLE
tx_bad_auth,why?

### ISSUE THREAD

**Issue by lauyang** [stellar/go#618]
trancation - create_acctount
if use "https://horizon-testnet.stellar.org", no error,
but use myself config url "https://test-api.essblock.com:8000" , error "tx_bad_auth". 
anybody help me~
```
tx, err := build.Transaction(
		build.SourceAccount{"GC65YDKGHFVCA2K2OALYG7XY5XKSL3X2G6YMRGKFM5K72NDNAUSEJLZY"},
		build.AutoSequence{horizon.DefaultTestNetClient},
		build.TestNetwork,
		build.CreateAccount(
			build.Destination{"GDX7QCR3WDU5KIN2DICWUIXE6HHZCHB6R4ULA2F6Y4LJBW7XICJHO3PF"},
			build.NativeAmount{"1"},
		),
	)

	if err != nil {
		fmt.Println(err)
		return
	}

	txe, err := tx.Sign("SCUYUW4NEHSILU3MJAQTNUZHCZAHJRSKPR2OMUGBZ3EI5F4GO4KYGG76")
	if err != nil {
		fmt.Println(err)
		return
	}

	txeB64, err := txe.Base64()

	if err != nil {
		fmt.Println(err)
		return
	}

	fmt.Printf("tx base64: %s", txeB64)
	fmt.Println()

	resp, err := horizon.DefaultTestNetClient.SubmitTransaction(txeB64)
	if err != nil {
		fmt.Println(string(err.(*horizon.Error).Problem.Extras["result_codes"]))
		panic(err)
	}```

**Comment by robertDurst** [comment]
The network is part of the signature: https://github.com/stellar/go/blob/master/build/transaction.go#L277

So here when you set the network as TestNet, it will be signed for *"Test SDF Network ; September 2015"* versus I see that the network passphrase for this horizon is: *"Public Global EnterpriseSourceSystem Network ; September 2015"*

**Comment by bartekn** [comment]
Please ask questions at [Stack Exchange](https://stellar.stackexchange.com/).
