### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by shank007** [stellar/go#624]
While Using friendbot api for my horizon server I am getting below error.

ERROR! { type: 'https://stellar.org/horizon-errors/server_error',
  title: 'Internal Server Error',
  status: 500,
  detail: 'An error occurred while processing this request.  This is usually due to a bug within the server software.Trying this request again may succeed if the bug is transient, otherwise please report this issue to the issue trackerat: https://github.com/stellar/horizon/issues. Please include this response in your issue.',
  instance: 'ip-172-31-29-1/JUTrKE7rgo-000022' }

**Comment by barchandune** [comment]
Seeing same issue again and again.
```
"Response: {'type': 'https://stellar.org/horizon-errors/server_error', 'title': 'Internal Server Error', 'status': 500, 'detail': 'An error occurred while processing this request.  This is usually due to a bug within the server software.  Trying this request again may succeed if the bug is transient, otherwise please report this issue to the issue tracker at: https://github.com/stellar/go/services/horizon/internal/issues. Please include this response in your issue.'}"
```

**Comment by bartekn** [comment]
Please use https://friendbot.stellar.org service.
