### ISSUE TITLE
Horizon dies 

### ISSUE THREAD

**Issue by hanzhang-us** [stellar/go#626]
[horizon.log](https://github.com/stellar/go/files/2341901/horizon.log)

See the debug log attached.
This happened a few times since we started running this.
There's no error messages in the log, it just stopped.
On the VM, only Horizon and Stellar-core. Nothing else.

**Comment by bartekn** [comment]
Any chance you could share that VM privately? Usually you would see an error message when Horizon crashes so it's strange.

**Comment by bartekn** [comment]
Horizon was not started as a service, it was killed by the system (`SIGHUP`).
