### ISSUE TITLE
[Question] Confirmation / Validation of incoming transaction (or payment) on Stellar network

### ISSUE THREAD

**Issue by gituser** [stellar/go#628]
Hi!

I'm just beginning to learn about Stellar and Horizon, so my question is:

If I accept transactions to my Stellar account what to check in order to be sure that the transaction has been validated and included in the ledger and won't be reversed or wasn't failed ?

Also the same question goes for incoming payments (can payment fail? if it fails what to check in RPC output ?)

E.g. in XRP (Ripple): you need to check for `validated: true` and in bitcoin you check for confirmations field in RPC output (`confirmations: 2`), so what to check in Stellar Horizon to be sure ?

Thank you.

**Comment by bartekn** [comment]
Please ask questions at [Stack Exchange](https://stellar.stackexchange.com/).
