### ISSUE TITLE
slice bounds out of range in /account/{id}/offers stream

### ISSUE THREAD

**Issue by bartekn** [stellar/go#637]
https://sentry.io/stellarorg/stellar-horizon/issues/673483740/

**Comment by bartekn** [comment]
https://github.com/stellar/go/blob/master/services/horizon/internal/actions_offer.go#L48

**Comment by bartekn** [comment]
Looks like the code responsible for steaming offers has been copied from other action without thinking about implications of using Core database. It does take into account that users can remove their offers so using the code like:
```go
for _, record := range action.Records[stream.SentCount():] {
```
can easily panic if any offer was removed (and no new offer was added) while streaming.

I can see 2 ways of fixing it:
- A _quickfix_ method would require us to change the code to support situations when offer is removed while streaming (update cursor after each `SSE()` call with the latest offer id?).
- I think that streaming behaviour of this endpoint is broken. We should probably send updates and removals too using `history_operations` table.

Thoughts @howardtw @tomquisel?

**Comment by howardtw** [comment]
> update cursor after each SSE() call with the latest offer id

How is it different than the current behavior? We use `Last-Event-ID` after the very first `SSE()` call as the cursor, which is essentially the latest offer id/the last offer we sent to the user. If one `SSE()` call loads 10 offers and one of the unsent offers gets dropped while we are looping, all we can do is to re-load the records with last sent offer id to update the cache, right? We can load one record at a time (tho inefficient) or have a mechanism to know when to re-load again. [This](https://github.com/stellar/go/pull/837/files) can at least return the user the records at the time of loading without panicing.

> I think that streaming behaviour of this endpoint is broken. We should probably send updates and removals too using history_operations table.

If we want to do it, we should probably do it in another PR.

**Comment by bartekn** [comment]
> How is it different than the current behavior?

Currently we don't update cursor, that's why we do slicing (like `action.Records[stream.SentCount():]`). So currently we get all offers since the cursor from a DB and just slice the results to get the values that were not sent yet. The problem is that when an account removes some offers `stream.SentCount()` is higher then `len(action.Records)` what results in "slice bounds out of range".

**Comment by howardtw** [comment]
> Currently we don't update cursor

I thought by [setting](https://github.com/stellar/go/blob/master/services/horizon/internal/actions_offer.go#L56) the `id` field in the `Event` object, we get the `Last-Event-ID` set automatically?

**Comment by bartekn** [comment]
`Last-Event-ID` is used only when client reconnects (and then it's used as a cursor). Each stream has an internal state and there's no code that updates the cursor. Again, if there was such code, you wouldn't have to slice the `action.Records` as it would always contain the events that have not been sent.

**Comment by howardtw** [comment]
I'll add the logic to update the cursor. Thanks for the information. I didn't know `Last-Event-ID` will only get set when the last connection is dropped.
