### ISSUE TITLE
Remove dependency on GoConvey

### ISSUE THREAD

**Issue by kr** [stellar/go#638]
In https://github.com/stellar/go/pull/635#discussion_r215681206, @bartekn says that this codebase wants to move away from GoConvey. I 100% support this direction, so here's an issue to discuss and track progress on that.

We might start opening pull requests to convert tests if that would make sense!

**Comment by lechengfan** [comment]
Go Convey should be completely removed now

**Comment by kr** [comment]
Nice!

**Comment by bartekn** [comment]
Can you also remove it from `Gopkg.lock`?

**Comment by bartekn** [comment]
I mean we should regenerate it so that running `dep ensure` after cloning the repo doesn't make any changes to the working directory.
