### ISSUE TITLE
tls: failed to parse private key

### ISSUE THREAD

**Issue by kahwooi** [stellar/go#64]
I bought an SSL, key is one I generate using openssl, and crt is downloaded from CA:

**I generated using a password.** 

```
certificate-file = "mm_hhprint_com.crt"
private-key-file = "mm.hhprint.com.key"
```
but I got this:

`level=error msg="failed to start server: tls: failed to parse private key" pid=14328`

Am I missing out something?

**Comment by kahwooi** [comment]
Solve it by removing key password:

`openssl rsa -in key.pem -out key.unencrypted.pem -passin pass:TYPE_YOUR_PASS`

**Comment by safeerk** [comment]
HI , Got something similiar liek this for me 
I have purchased the certificate - I installed it on my machine - I put the crt & key file on the federation root folder - But when i run the federation server its poping me error.

Regards
S

**Comment by bartekn** [comment]
@safeerk there are many possible reasons, one of them is password (check @kahwooi message). Please search `tls: failed to parse private key` on Google, we are using standard Golang libraries and you will certainly find an answer. If not, please ask on our [Stack Exchange](https://stellar.stackexchange.com/).

**Comment by safeerk** [comment]
Thanks i figured out the issue - SSL was succesfully configured. (Private key error)

Right now my federation URL works based on SSL 
But https://necpaymentsuat.com:8002/federation?q=safeer_kk%2Anecpaymentsuat.com&type=name

But on federation application am getting bad certificate error?? Screenshot below
![image](https://user-images.githubusercontent.com/22815639/38813918-e777708a-4198-11e8-879d-1b31f7078a36.png)

**Comment by DarshanMurthy** [comment]
`openssl rsa -in client.key -out key.unencrypted.pem ` this worked for me.

**Comment by xvzhu** [comment]
But it's not safety to save unenrcrypted private key on disk.  Any other way? @alwayscodemonkey

**Comment by somnusx** [comment]
对我也有用
