### ISSUE TITLE
Improve streaming /order_book endpoint

### ISSUE THREAD

**Issue by tomquisel** [stellar/go#644]
It looks like Horizon's streaming `/order_book` endpoint is unaware of changes to the data. It sends the entire orderbook every second over the eventstream.

Check out the [Stellar Lab](https://www.stellar.org/laboratory/#explorer?resource=order_book&endpoint=details&values=eyJzZWxsaW5nX2Fzc2V0Ijp7InR5cGUiOiJuYXRpdmUiLCJjb2RlIjoiIiwiaXNzdWVyIjoiIn0sImJ1eWluZ19hc3NldCI6eyJ0eXBlIjoiY3JlZGl0X2FscGhhbnVtNCIsImNvZGUiOiJFVVJUIiwiaXNzdWVyIjoiR0FQNUxFVE9WNllJRTYyWUFNNTZTVERBTlBSRE83WkZEQkdTTkhKUUlZR0dLU01PWkFIT09TMlMifSwic3RyZWFtaW5nIjp0cnVlfQ%3D%3D&network=public) for an example.

Ideally it could do one of the following:

* Only transmit the entire orderbook when there's a change to the orderbook
* Even better, transmit a list of added & removed bids + asks when a change occurs
* Best of all, compute both and transmit whichever is shorter

Either way, it could be rate limited to send at most an update every 200ms (configurable), to avoid flooding the client with a very busy order book.

@bartekn @tomerweller

**Comment by bartekn** [comment]
Good idea, I think I vote for:
> * Only transmit the entire orderbook when there's a change to the orderbook

it's easy to check the difference in the client side (especially in React apps where you can simply push a new state to the app) and sending a diff would complicate this endpoint a lot.

I think along this change we could also keep a local cache of each active order book (that has listening clients) and send updates if there is a change. Then even if there are thousands of listening clients to a single order book it will only send a single DB query every X seconds.

I'm adding this to Horizon 0.14.X milestone as it's a performance fix but would be really great to have this.

> Either way, it could be rate limited to send at most an update every 200ms (configurable), to avoid flooding the client with a very busy order book.

There will be no changes between ledgers so this can be updated every new ledger (2-5 sec.).

**Comment by howardtw** [comment]
Closed by https://github.com/stellar/go/pull/828
