### ISSUE TITLE
Horizon should not use core db anywhere outside ingest package

### ISSUE THREAD

**Issue by bartekn** [stellar/go#651]
The description will be updated later. This issue now is only to track all the issues caused by connecting to core DB:
* https://github.com/stellar/go/issues/650
* https://github.com/stellar/go/issues/631 (slow, unoptimized queries made against core DB)
* https://github.com/stellar/go/issues/477
* https://github.com/stellar/go/issues/183

**Comment by abuiles** [comment]
We can close this once https://github.com/stellar/go/pull/2731 is merged

**Comment by abuiles** [comment]
Fix in #2759
