### ISSUE TITLE
github.com/stellar/go/address package fails to resolve with dep

### ISSUE THREAD

**Issue by seemaphalke** [stellar/go#660]
if imported github.com/stellar/go/address  package, it fails to run dep
see following error:

Solving failure: No versions of github.com/stellar/go met constraints:
        master: Could not introduce github.com/stellar/go@master, as it depends on github.com/asaskevich/govalidator from https://github.com/asaskevich/govalidator.git, but github.com/asaskevich/govalidator is already marked as coming from github.com/asaskevich/govalidator by , /utility
        benchmark_stellar-core: Could not introduce github.com/stellar/go@benchmark_stellar-core, as it is not allowed by constraint master from project .
        exp-paths: Could not introduce github.com/stellar/go@exp-paths, as it is not allowed by constraint master from project .
        fix-trade-tests: Could not introduce github.com/stellar/go@fix-trade-tests, as it is not allowed by constraint master from project .
        fuzz-xdr: Could not introduce github.com/stellar/go@fuzz-xdr, as it is not allowed by constraint master from project .
        go-vet: Could not introduce github.com/stellar/go@go-vet, as it is not allowed by constraint master from project .
        horizon-0.15.0: Could not introduce github.com/stellar/go@horizon-0.15.0, as it is not allowed by constraint master from project .
        ico: Could not introduce github.com/stellar/go@ico, as it is not allowed by constraint master from project .
        master-debug-build: Could not introduce github.com/stellar/go@master-debug-build, as it is not allowed by constraint master from project .
        new_paging: Could not introduce github.com/stellar/go@new_paging, as it is not allowed by constraint master from project .
        paging_params: Could not introduce github.com/stellar/go@paging_params, as it is not allowed by constraint master from project .
        travis-snapshots: Could not introduce github.com/stellar/go@travis-snapshots, as it is not allowed by constraint master from project .
        wallet: Could not introduce github.com/stellar/go@wallet, as it is not allowed by constraint master from project .
        bifrost-v0.0.1: Could not introduce github.com/stellar/go@bifrost-v0.0.1, as it is not allowed by constraint master from project .
        bifrost-v0.0.2: Could not introduce github.com/stellar/go@bifrost-v0.0.2, as it is not allowed by constraint master from project .
        federation-v0.0.0-testing: Could not introduce github.com/stellar/go@federation-v0.0.0-testing, as it is not allowed by constraint master from project .
        federation-v0.2.0: Could not introduce github.com/stellar/go@federation-v0.2.0, as it is not allowed by constraint master from project .
        federation-v0.2.1: Could not introduce github.com/stellar/go@federation-v0.2.1, as it is not allowed by constraint master from project .
        horizon-v0.12.0: Could not introduce github.com/stellar/go@horizon-v0.12.0, as it is not allowed by constraint master from project .
        horizon-v0.12.0-testing: Could not introduce github.com/stellar/go@horizon-v0.12.0-testing, as it is not allowed by constraint master from project .
        horizon-v0.12.1: Could not introduce github.com/stellar/go@horizon-v0.12.1, as it is not allowed by constraint master from project .
        horizon-v0.12.2: Could not introduce github.com/stellar/go@horizon-v0.12.2, as it is not allowed by constraint master from project .
        horizon-v0.12.3: Could not introduce github.com/stellar/go@horizon-v0.12.3, as it is not allowed by constraint master from project .
        horizon-v0.13.0: Could not introduce github.com/stellar/go@horizon-v0.13.0, as it is not allowed by constraint master from project .
        horizon-v0.13.1: Could not introduce github.com/stellar/go@horizon-v0.13.1, as it is not allowed by constraint master from project .
        horizon-v0.13.2: Could not introduce github.com/stellar/go@horizon-v0.13.2, as it is not allowed by constraint master from project .
        horizon-v0.13.3: Could not introduce github.com/stellar/go@horizon-v0.13.3, as it is not allowed by constraint master from project .
        horizon-v0.14.0: Could not introduce github.com/stellar/go@horizon-v0.14.0, as it is not allowed by constraint master from project .
        horizon-v0.14.0rc1: Could not introduce github.com/stellar/go@horizon-v0.14.0rc1, as it is not allowed by constraint master from project .
        horizon-v0.14.0rc2: Could not introduce github.com/stellar/go@horizon-v0.14.0rc2, as it is not allowed by constraint master from project .
        horizon-v0.14.0rc3: Could not introduce github.com/stellar/go@horizon-v0.14.0rc3, as it is not allowed by constraint master from project .
        snapshots: Could not introduce github.com/stellar/go@snapshots, as it is not allowed by constraint master from project .
        stellar-archivist-v0.1.0: Could not introduce github.com/stellar/go@stellar-archivist-v0.1.0, as it is not allowed by constraint master from project .
        stellar-hd-wallet-v0.0.1: Could not introduce github.com/stellar/go@stellar-hd-wallet-v0.0.1, as it is not allowed by constraint master from project .
        stellar-hd-wallet-v0.0.2: Could not introduce github.com/stellar/go@stellar-hd-wallet-v0.0.2, as it is not allowed by constraint master from project .
        stellar-sign-v0.1.0: Could not introduce github.com/stellar/go@stellar-sign-v0.1.0, as it is not allowed by constraint master from project .
        stellar-sign-v0.2.0: Could not introduce github.com/stellar/go@stellar-sign-v0.2.0, as it is not allowed by constraint master from project .
make: *** [dep] Error 1

**Comment by bartekn** [comment]
It looks like your trying to add all branches of `github.com/stellar/go` repo. I think you're doing something wrong. Please ask questions at [Stack Exchange](https://stellar.stackexchange.com/).
