### ISSUE TITLE
gostellar.org seems down

### ISSUE THREAD

**Issue by overcat** [stellar/go#701]
I tried to use it to test the compliance protocol but got an error report. Is the service hanging? Have I missed something?
![send](https://user-images.githubusercontent.com/2368403/46251573-7dcd4100-c488-11e8-9ae7-e7c59f2cfe4f.png)

![failed](https://user-images.githubusercontent.com/2368403/46251569-61310900-c488-11e8-9b30-7f80ed4c289d.png)
Thanks.

**Comment by bartekn** [comment]
It's likely a problem with your code:
> Response from AuthServer is not valid JSON
