### ISSUE TITLE
Error on executing dep

### ISSUE THREAD

**Issue by Fanbingxia** [stellar/go#712]
me and my colleague both encountered the same issue on Mac and centos when executing `dep ensure -v` in the terminal.

`could not find project Gopkg.toml, use dep init to initiate a manifest`

**Comment by bartekn** [comment]
Are you actually running it in the `stellar/go` directory? This doesn't look like an issue with this repository (I will reopen if it is). For now please ask questions at: https://stellar.stackexchange.com/
