### ISSUE TITLE
Cannot start horizon

### ISSUE THREAD

**Issue by Abusher** [stellar/go#713]
I've started stellar-core but when i run horizon it fails with error:

connect failed: pq: password authentication failed for user "user"

I've tried to change password for user in postgres but didn't work, can you give me some hints?

**Comment by lechengfan** [comment]
Make sure that your DATABASE_URL is configured properly in the format `postgres://[username]:[password]@[host url]:5432/[dbname]`. When you run horizon for the first time, you'll need to do `horizon db init` to install the schema.

**Comment by Abusher** [comment]
Yes, it seems like database url configured ok.
It's ok with running stellar core but horizon gives next errors:
horizon db init --db-url postgres://localhost/horizon?sslmode=disable
--stellar-core-db-url postgres://localhost/stellar?sslmode=disable
--stellar-core-url http://localhost:8080

error is:  connect failed: pq: password authentication failed for user
"user"

but when i run:

horizon db init --db-url postgres://postgres:password@127.0.0.1:8000/horizon
--stellar-core-db-url postgres://localhost/stellar?sslmode=disable
--stellar-core-url http://localhost:8080

error: connect failed: dial tcp 127.0.0.1:8000: connect: connection refused

Again stellar core is working ok.

чт, 11 окт. 2018 г. в 2:04, Le Cheng Fan <notifications@github.com>:

**Comment by lechengfan** [comment]
Postgres typically runs on port 5432 so I would change your `127.0.0.1:8000` address to `127.0.0.1:5432`

**Comment by Abusher** [comment]
Wow, it worked. Thank you very much!

чт, 11 окт. 2018 г. в 20:20, Le Cheng Fan <notifications@github.com>:
