### ISSUE TITLE
Stream changes of an account/account balance

### ISSUE THREAD

**Issue by TorstenStueber** [stellar/go#720]
For a client application (e.g., a wallet) it would be beneficial to be able to get live streaming update of the user's account balances. At the moment this can only be done by streaming effects and transactions of an account and derive account balance updates from them. However, this is very laborous (e.g., taking transaction fees into account) and error prone.

A stream that sends an event whenever the account resource (or at least its balance array) changes would make this much easier.

**Comment by bartekn** [comment]
You can stream `/accounts/{id}` endpoint.
