### ISSUE TITLE
Bifrost roadmap/production readiness

### ISSUE THREAD

**Issue by JonasPf** [stellar/go#722]
Is there any roadmap or plans for Bifrost? I'm particularly interested if and when it can be considered production ready.

From https://github.com/stellar/go/blob/master/services/bifrost/README.md:

> We are releasing the **alpha version** of this software. We encourage our community of developers to test and improve it.

**Comment by bartekn** [comment]
Bifrost has been used by several ICOs and it worked well. However, we give no guarantees that it is bug-free etc. Before using it, make sure you understand how it works and test it before going to production. If you have any questions you can ask them at [Stack Exchange](http://stellar.stackexchange.com) (`bifrost` tag).
