### ISSUE TITLE
Collect data on SDK Usage

### ISSUE THREAD

**Issue by bartekn** [stellar/go#725]
Collect data using HTTP header and save the value in `Started request` and `Finished request` log entries. It will be much easier to aggregate if two headers are sent: client name (`X-Client-Name`) and version (`X-Client-Version`). Also, it looks like some `EventStream` implementations (especially implementation found in browsers) don't allow to send custom headers so we should allow sending them via GET parameter. Horizon should check if header is present and if not should check GET params.

SDF:
- [x] Horizon https://github.com/stellar/go/pull/727
- [x] JS https://github.com/stellar/js-stellar-sdk/pull/206
- [x] Go
- [x] Java
- [ ] Docs

Community SDKs:
- [x] Python
- [x] Scala
- [x] C#
- [x] C++
- [x] Ruby
- [x] iOS and macOS SDK

**Comment by ire-and-curses** [comment]
Python SDK supports this: https://github.com/StellarCN/py-stellar-base/commit/d3052c8f5d97f52eb284d4ee7ba0351b9072c4db

**Comment by Synesso** [comment]
This will be present in the next release of Scala SDK.

**Comment by ire-and-curses** [comment]
I audited the SDKs and I think they all support this now :tada:

@bartekn from the original description, what docs were you thinking are needed? That's all that's left to close this.

**Comment by bartekn** [comment]
@ire-and-curses I was thinking about a simple doc somewhere [here](https://www.stellar.org/developers/horizon/reference/index.html) explaining what headers should be sent to activate tracking.

**Comment by tomquisel** [comment]
@theaeolianmachine just a heads up, this should be quick to knock out.

**Comment by tomquisel** [comment]
@rice2000 can you put it on your list to document these headers as Bartek [mentions](https://github.com/stellar/go/issues/725#issuecomment-494876195)?

**Comment by rice2000** [comment]
> @rice2000 can you put it on your list to document these headers as Bartek [mentions](https://github.com/stellar/go/issues/725#issuecomment-494876195)?

I added it to the list of new docs to write.  Thanks for pointing this out!

**Comment by bartekn** [comment]
Looks like it can be closed.
