### ISSUE TITLE
Standard for encrypted keyfiles

### ISSUE THREAD

**Issue by sbsends** [stellar/go#729]
@bartekn mentioned in https://github.com/stellar/stellar-protocol/issues/48 that he votes to use a similar definition to https://github.com/ethereum/wiki/wiki/Web3-Secret-Storage-Definition for encrypting private keys. 

I have started to port web3-ssd for Stellar with a few minor changes (no uuid field and more extensibility). Find the repo here https://github.com/tensortask/stellar-keyfile. 

Here is an example keyfile:
```json

{
  "crypto": {
    "cipher": "aes-128-ctr",
    "ciphertext": "62e3c8c15245be6a7323302965caf19b8bd18aa22a2cd5ec7d2c5508d39e4ad06fee910ffc112a04ba3c09547bcee1525857ea085cef3120",
    "cipherparams": {
      "iv": "e8d9a67b7007c8bc198525644cbb4b88"
    },
    "kdf": "scrypt",
    "kdfparams": {
      "keyLen": 32,
      "n": 262144,
      "p": 1,
      "r": 8,
      "salt": "a07860088e95b225d1b67a79ed9462246675922576702ea7718bf13cba1216e3"
    },
    "mac": "353f8ed42ae06884bee688f9e5a0afad668b8155939c296c7a8adcfe8d965cff"
  },
  "account": "GBGRTRIJ6M6XXTPROIPA5I4SFTKXWCOE3B67B2IZCG3S7TYKGKJIGKO6",
  "version": 1
}

```

A standardized keyfile format would simplify cross-service access to accounts. For instance, desktop wallets could read the same keyfiles placed in a .stellar directory, and web-platforms could store the encrypted keyfile (without the password) and then decrypt client side. 

I am aware that work was done to support mnemonic keyfile storage which is awesome. A keyfile format that easily supports switching encryption/kdf algorithms and respective parameters is useful too.

If you give the green light, I will try to merge (the finished port) as a subpackage called "keyfile" in the monorepo.

**Comment by bartekn** [comment]
Hey @sbsends! I'd like to first make it a [SEP](https://github.com/stellar/stellar-protocol). Then we can think about the code. Could you open an issue there?

**Comment by sbsends** [comment]
Moved to: https://github.com/stellar/stellar-protocol/issues/198
