### ISSUE TITLE
MemoHash contruction...

### ISSUE THREAD

**Issue by pawmart** [stellar/go#739]
Silly question, but how do we construct 32 byte memo hash from a hash string?

```
xdr.Hash(hashBytes)
````

I guess is the function to be called but struggling to convert string to 32 byte array.

Here is a full example:

```
	var hashBytes [32]byte
	copy(hashBytes[:], []byte("9692fb89f30da74090c6126215d3237edb398c897ae870ea251ea78adc519738"))

	tx, err := build.Transaction(
		build.Network{passphrase},
		build.SourceAccount{source},
		build.AutoSequence{horizon.DefaultTestNetClient},
		build.MemoHash{xdr.Hash(hashBytes)},
		build.Payment(
			build.Destination{destination},
			build.NativeAmount{"0.000001"},
		),
	)

```

Then when I fetch transaction and would like to read the memo my only option is to call:

```
tx.Memo 
```

which gives me string however not the one I inserted originally as 'hashstring'... unless I call

```
base64.StdEncoding.DecodeString(tx.Memo)
```

The problem is it gets trimmed giving me 9692fb89f30da74090c6126215d3237e

Original  Memo Hash: 9692fb89f30da74090c6126215d3237edb398c897ae870ea251ea78adc519738
Fetched Memo Hash: 9692fb89f30da74090c6126215d3237e

Is this due to 32 bytes conversion (I thought that sha256 is exactly 32 bytes)?

Any suggestions? 
Should I used 'Attachment' to store sha256? Is it supported in Go SDK?

**Comment by bartekn** [comment]
build.MemoHash requires `xdr.Hash` which really is `[32]byte`. You are passing `9692fb89f30da74090c6126215d3237edb398c897ae870ea251ea78adc519738` which is really 64 bytes long. You should probably use `encoding/hex` package to decode the value before passing it to transaction builder.
