### ISSUE TITLE
add failed transaction count to ledger resource

### ISSUE THREAD

**Issue by tomerweller** [stellar/go#754]
While https://github.com/stellar/go/issues/309 is not fixed, there's a visibility issue into the actual congestion status of the network. A simple quick fix can be adding a `tx_failed_count` to the ledger resource. 

~This will require ledger ingestion to make an additional query to core's db and then simply subtract the number of ingested transactions.~ update: actually, the data is already there in ingestion. it's just a matter of modifying the ledger table and resources

**Comment by bartekn** [comment]
Closed in #756.
