### ISSUE TITLE
ENABLE_ASSET_STATS=false flag is also disabling history_asset creation

### ISSUE THREAD

**Issue by istrau2** [stellar/go#769]
Here is the point where a history asset gets created: 
https://github.com/stellar/go/blob/master/services/horizon/internal/ingest/asset_stat.go#L169
and
https://github.com/stellar/go/blob/master/services/horizon/internal/db2/history/asset.go#L81

It has been disabled by the flag here:
https://github.com/stellar/go/blob/master/services/horizon/internal/ingest/session.go#L70

Is this intended behavior? The flag name (and docs) are quite confusing if so. It should be called `ENABLE_ASSETS` instead...

**Comment by tomerweller** [comment]
@istrau2 it seems like the code you're referencing is from an outdated feature branch. Can you update this to reflect master? for example: 
https://github.com/stellar/go/blob/a3adccc1371114476a35a5e0ed749294dfb1c703/services/horizon/internal/ingest/session.go#L70

**Comment by istrau2** [comment]
@tomerweller Ok, the OP is updated.

**Comment by bartekn** [comment]
I think [Horizon 0.15.0](https://github.com/stellar/go/releases/tag/horizon-v0.15.0) release notes are quite clear:
> Assets stats are disabled by default. This can be changed using an environment variable (`ENABLE_ASSET_STATS=true`) or CLI parameter (`--enable-asset-stats=true`). Please note that it has a negative impact on a DB and **ingestion time**.

The problem with asset stats is that it's using queries on stellar-core DB that are not using indexes and are super slow. So you either need a high-end DB cluster or just wait for rearchitecture of `ingest` package.

**Comment by bartekn** [comment]
> @bartekn I am referring to the history_assets table in this issue (not the asset_stats table). The flag name and docs implied (to me anyway) that only the asset_stats table would be affected, not history_assets. When you think about it, there is a foreign key between history_trades and history_assets that is going to be violated if the asset isn't there and horizon tries to add trades in an asset pair including the asset.

Disabled asset stats (`ENABLE_ASSET_STATS=true`) should not influence `horizon_assets` table. Are you sure the table is not populated for you? After checking the code quickly I think it only inserts new rows there if there was a trade between assets.

> I was hoping to use this opportunity to ask for flags in general. I think as Stellar grows, more and more people may have customized setups. It would be great if horizon had flags so that people could use the parts of it they wanted and turn off other parts. 

Great idea, could you add a new issue?

**Comment by istrau2** [comment]
@bartekn I am pretty sure it IS influencing `history_assets` table. I know there are no assets being added to our table (we've had to add some manually). If you take a look at the links in my OP, you will see that it is quite evident from the code why this is happening.

**Comment by bartekn** [comment]
`history_assets` is only updated when there is a trade connected to the asset whereas with `ENABLE_ASSET_STATS` it's updated with each operation on a given asset.

**Comment by istrau2** [comment]
@bartekn Ok, that's fine. We've fixed it internally. Thanks!
