### ISSUE TITLE
Build error due to incorrect type

### ISSUE THREAD

**Issue by Lawrence-Windsor** [stellar/go#770]
Hey @bartekn just flagging this here for your thoughts. File in reference: [Link](https://github.com/stellar/go/blob/master/services/bifrost/stress/ethereum.go)

**Build Issue**
Trying to build this as is will through an error (Ref-1 snippet below), turns our line 73 is passing in the wrong type. the function `big.NewInt(1)` takes a `Int64` and returns a `*Int`. Well `types.NewTransaction` is expecting an `uint64`, hence the error.

			```tx := types.NewTransaction(
				uint64(i),
				g.randomAddress(),
				g.randomAmount(),
				big.NewInt(1),
				big.NewInt(2),
				[]byte{0, 0, 0, 0},
			)```

**My Temp Fix**
Changing `big.NewInt(1)` to `1` this builds and works as expected but havent done major review to see if its an actual fix.

			```tx := types.NewTransaction(
				uint64(i),
				g.randomAddress(),
				g.randomAmount(),
				1,
				big.NewInt(2),
				[]byte{0, 0, 0, 0},
			)```

**Ref-1**
```go build main.go
# github.com/stellar/go/services/bifrost/stress
stress/ethereum.go:73:15: cannot use big.NewInt(1) (type *big.Int) as type uint64 in argument to types.NewTransaction``

**Comment by bartekn** [comment]
It's very likely that you are not using `dep` to download dependencies. Please use `dep ensure -v` command and try again.
