### ISSUE TITLE
Silent "database is closed" errors during shutdown

### ISSUE THREAD

**Issue by bartekn** [stellar/go#777]
During shutdown a lot of errors like: `get failed: sql: database is closed` are generated that make alerts triggered. They should be either silenced or temporarily degraded to `WARN` level.

**Comment by bartekn** [comment]
Looks like ingestion can still generate errors during shutdown.

**Comment by ire-and-curses** [comment]
Do we expect this to be resolved once we move to new ingestion?

**Comment by bartekn** [comment]
Yes, this can be annoying when `ERROR` level logs trigger alerts.
