### ISSUE TITLE
Setting flags on accounts

### ISSUE THREAD

**Issue by Varunram** [stellar/go#789]
New to stellar here, please excuse me if this has been asked already. 

I'm trying to set the immutable flag on an account but I can't seem to find tutorials in the documentation that do this (there are examples for java and js, but not go at https://www.stellar.org/developers/guides/issuing-assets.html). I'm creating my account using `build.CreateAccount()` and passing the destination and amount parameters along. Would be great if someone could point me to it, thanks!

**Comment by bartekn** [comment]
Please ask questions at [Stellar Stack Exchange](https://stellar.stackexchange.com/). GH issues are used to report bugs and request features only.

**Comment by Varunram** [comment]
@bartekn If you had referred the documentation I linked to, you can see that there is none for Go (. As such, this is a feature request to add complete Go documentation to the file linked above because it is incomplete. Attaching a picture here to save you the click.
![screenshot 2018-12-20 at 8 50 08 am](https://user-images.githubusercontent.com/18598959/50288562-4db48f00-0434-11e9-885a-caceac2a4e74.png)
