### ISSUE TITLE
Problem about Dep ensure -v when install Horizon stellar

### ISSUE THREAD

**Issue by TanDung2512** [stellar/go#794]
Hi everyone , i'm currently studying about stellar and i'm preparing for my project. I have problems while installing Horizon . 

At first , i follow step by step from the instruction of Swetakedia https://github.com/stellar/go/issues/287.

Because Stellar has changed packer manager from "glide" to "dep" and the URL of horizon . 
so i also change a little bit as the instruction in "https://github.com/stellar/go/tree/master/services/horizon"

However, when executing "dep ensure -v"  i got problem 
"/usr/local/go/src/github.com/stellar/go is not within a known GOPATH/src"

 my GOPATH is GOPATH =/usr/local/go

i have tried many ways on google but failed all

**Comment by bartekn** [comment]
GitHub Issues is a place for reporting bugs and feature requests. Please ask questions at [Stellar Stack Exchange](https://stellar.stackexchange.com/).
