### ISSUE TITLE
Trezor Transactions Failing

### ISSUE THREAD

**Issue by bosomt** [stellar/go#795]
Trezor users are not able to send transactions between wallets.

Error 400 says:
The transaction failed when submitted to the stellar network. The `extras.result_codes` field on this response contains further details.  

I'm attaching screenshot and logs from Chrome console.
Please contact Trezor developers directly or please give us any info that I can forward to them.

[trezor.io-1546007926613.log](https://github.com/stellar/go/files/2715037/trezor.io-1546007926613.log)
![screenshot from 2018-12-28 15-46-04](https://user-images.githubusercontent.com/31506317/50518789-d3c97900-0ab7-11e9-872e-8cb8e3ce8814.png)

**Comment by bartekn** [comment]
I think this is connected to https://github.com/trezor/trezor-core/issues/421. Closing.
