### ISSUE TITLE
Send objects in a stream only when updated

### ISSUE THREAD

**Issue by bartekn** [stellar/go#809]
Currently, single-object streams like `/accounts/{id}` or `/order_book` send objects every time there's a new ledger, even when objects did not change. It is not only eating bandwidth but also requires stream consumer to manually check if the data changed.

It looks like fixing this shouldn't be hard. Each time we get data from the DB we can hash it to check if the previous version was different. If it was, we send a new object to the stream.

The hash function should be selected carefully. It should be fast and the sum should take as little space as possible. At the same time probability of a conflict should be very low for our use case (stringified JSON objects).

Similar issues: https://github.com/stellar/go/issues/644 https://github.com/stellar/go/issues/736.

**Comment by bartekn** [comment]
> Why do we need to use a hash function to compare two stringified JSON objects?

Memory. We will need to store the last value in each stream. Objects like Accounts can have arbitrary length (ex. one can add thousands of trust lines or data entries if they wish and have funds to do it). So someone could create a very large account response and create a bunch of streams of this account. If we store a hash (so just a few bytes instead of, possibly, kilobytes) it's much harder to make a node run out of memory.

**Comment by tomquisel** [comment]
Another similar issue: #735

**Comment by howardtw** [comment]
Closed by https://github.com/stellar/go/pull/828
