### ISSUE TITLE
Port horizon into here

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/go#82]
- [x] copy stellar/horizon  -> stellar/go/services/horizon
- [x] deal with the dependencies (GB -> go build)
- [x] change stellar/docs, stellar/developers to point to the new horizon url
- [x] update stellar/horizon with a "repository has moved" message
- [x] merge any changes made to stellar/horizon during the port (1 change)
- [x] update the documentation how to build horizon
- [x] horizon tests to use Postgres() for parallelization (remove horizon script from .travis.yml)

**Comment by mvaneijk** [comment]
I would kindly request to also update the documentation how to build horizon

**Comment by nikhilsaraf** [comment]
yes, added that to the list and will update the README file asap.

you can do the following `glide install && go generate github.com/stellar/go/... && go install github.com/stellar/go/services/horizon/cmd/horizon`

**Comment by nikhilsaraf** [comment]
all these issues are completed and merged; closing out this issue.
