### ISSUE TITLE
Switch back to postgres 9.4 (?) in Travis

### ISSUE THREAD

**Issue by bartekn** [stellar/go#823]
* For rebuilding test scenarios we should use Docker to prevent unnecessary DB dumps diffs.
* Ideally Horizon uses the same version as Stellar-Core.
* If we want to migrate to 10: 1) it's a breaking change, 2) consider deployment easiness - ex. default Ubuntu packages.

**Comment by howardtw** [comment]
Do you plan on modifying both https://github.com/stellar/go/blob/master/services/horizon/internal/scripts/rebuild_schema.bash and /scripts/build_test_scenarios.bash to have them run with Postgres 9.6? I think we should at least bump the Travis Postgres to `9.6` as suggested here https://github.com/stellar/docker-stellar-core-horizon#stellar-quickstart-docker-image

**Comment by tomerweller** [comment]
We should probably not go above 9.5 because that's as far as the official ubuntu packages for 16.04LTS go.

**Comment by tomerweller** [comment]
> we should use Docker to prevent unnecessary DB dumps diffs.

@bartekn we can probably achieve a stable dump for the empty db but not for the populated ones, as the dumps contain timestamps (in their current form).

**Comment by brahman81** [comment]
@bartekn I think that from the packages perspective it would be better to stick to stock 16.04 (postgresql 9.5) at the minimum.
