### ISSUE TITLE
Better communicate testnet reset: add date of reset to friendbot response

### ISSUE THREAD

**Issue by tomquisel** [stellar/go#840]
- [ ] Add a field to the friendbot JSON response that communicates the date of the next testnet reset and links to the best practices doc.
- [ ] Ensure that the stellar lab Account Creator shows the friendbot response when it is used

Why: we don't want users of the testnet to be caught unaware when the testnet resets.

**Comment by bartekn** [comment]
Just sent it to @theaeolianmachine but decided to discuss it here too. I'm wondering if we should have a central API/place that other services (dashboard/laboratory/friendbot/docs?) can pull data from and display info about next reset. Otherwise we'll have to update all of them over and over again.

**Comment by tomquisel** [comment]
I was thinking we could keep to an algorithmic schedule (except for this first date, which can be hard coded). The schedule would be we second Wednesday of Jan, April, July, and October. That way we can code that schedule once in each service + mention in docs, and just let it ride. It's more brittle if we need to change the date, but honestly it's best if we just keep a consistent schedule.

**Comment by tomquisel** [comment]
It's pretty painful to do this without a central source of reset dates. Closing for now.
