### ISSUE TITLE
Better communicate testnet reset

### ISSUE THREAD

**Issue by tomquisel** [stellar/go#841]
We need to better communicate to devs working with testnet that the ledger will be reset every 3 months. It may also be important to change the network passphrase and avoid any kind of accidental mixing between nodes & clients during testnet reset.

Ideas:
- update Horizon errors on testnet to state the date of the last reset and the date of the next one, and link out to our testnet best practices
- change the network passphrase, and update SDKs to auto-detect the current passphrase
- modify Stellar lab to state reset information when in testnet mode

Any other ideas?

**Comment by tomquisel** [comment]
Ok, thinking about this more, here's what I'd recommend:

- We go forward with changing the network passphrase each time we reset testnet (but probably don't do it for the one upcoming in Feb)
- We set the passphrase to be the date of the next reset using ISO 8601: `Stellar Test Network; Next Full Reset 2019-02-27T09:00:00Z`
- We change Horizon SDKs to read the testnet passphrase from https://testnet.horizon.org when initializing a testnet session.
- Any service that wants to know the date of the next reset can look at the testnet passphrase as the one source of truth
- We move forward with #840 and stellar/laboratory#364

The downside is that this basically locks us in to the next testnet reset date at the time of the current reset, but I think that's ok. We should keep it consistent and commit months in advance so the community can easily plan around it.

@brahman81 @MonsieurNicolas @bartekn thoughts?

**Comment by MonsieurNicolas** [comment]
That seems fine.

For the date in the passphrase, does it need to be fully specified or just have the month/Quarter (and have a link to get the actual date)?
Something like `Stellar Test Network Q3 2019; See http://www.stellar.org/testnet for more information`

Do we need to use templates somehow for all the sample configurations that we have for Horizon/Core - also, some of those, I think, are packaged/tagged with releases

**Comment by brahman81** [comment]
I like updating the passphrase with date + time, it will be a good motivator for automating the reset, which ultimately is the goal here.

With regards to configs, the [stellar-core-postgres](https://github.com/stellar/packages/blob/master/stellar-core-postgres/stellar-core_postgres.cfg) package has a sample Testnet configuration which would need to be updated every quarter. We could easily modify the `NETWORK_PASSPHRASE` during package build and then simply schedule a build of this package every 3 months.

Caveat: Package end-users utilising a modified config will still need to update the passphrase manually.

**Comment by tomquisel** [comment]
Yeah, the advantage of including the date + time is that https://horizon-testnet.stellar.org/ becomes the one source of truth for when the reset is happening.

**Comment by brahman81** [comment]
Below are the 3 configs with a Testnet passphrase that end up in the .deb packages:

 * https://github.com/stellar/packages/blob/master/stellar-core-postgres/stellar-core_postgres.cfg
 * https://github.com/stellar/stellar-core/blob/master/docs/stellar-core_testnet.cfg
 * https://github.com/stellar/stellar-core/blob/master/docs/stellar-core_standalone.cfg

The standalone config should probably be updated to use `"Standalone Network ; February 2017"` in the same way that the docker quickstart standalone config does [here](https://github.com/stellar/docker-stellar-core-horizon/blob/master/standalone/core/etc/stellar-core.cfg#L8).

For public docker images, we need to update:

 * https://github.com/stellar/docker-stellar-core-horizon/blob/master/testnet/core/etc/stellar-core.cfg
 * https://github.com/stellar/docker-stellar-core-horizon/blob/a2f1f5ff4717520e6a2c28aa468d1d8758fd7d8b/stat#L77
 * https://github.com/stellar/docker-stellar-core/blob/1ea7fa8c7b99732574ab5a20166f8eee1171ff5b/examples/compat_complete.env#L22
 * https://github.com/stellar/docker-stellar-core/blob/1ea7fa8c7b99732574ab5a20166f8eee1171ff5b/examples/compat_minimal.env#L20
 * https://github.com/stellar/docker-stellar-core/blob/1ea7fa8c7b99732574ab5a20166f8eee1171ff5b/examples/local.env#L34
 * https://github.com/stellar/docker-stellar-core/blob/1ea7fa8c7b99732574ab5a20166f8eee1171ff5b/examples/single.env#L36

There is also a bunch of documentation that needs updating as part of the process, either permanently or on each reset.

https://github.com/stellar/docs/search?q=Test+SDF+Network+%3B+September+2015&unscoped_q=Test+SDF+Network+%3B+September+2015

We wouldn't have to update all the configs/docs if we set the passphrase to `NETWORK_PASSPHRASE="Test SDF Network ; Testnet is reset every 3 months - backup your data"`, or something along those lines.

But then new quickstarts might still get bad messages from non reset peers.

@MonsieurNicolas is there anything else we can do to ignore messages from stale peers ?

**Comment by MonsieurNicolas** [comment]
Maybe a stupid idea... but can’t we change our various packages and scripts to just curl a know url (like our packages repo) for the latest version of the testnet config?

**Comment by MonsieurNicolas** [comment]
As for ignoring other peers without changing the passphrase I don’t think we can do a lot more than what we’re doing

**Comment by tomquisel** [comment]
Resolving this as testnet resets seem to be going smoothly lately, thanks to Tom's work and better announcements.

**Comment by bartekn** [comment]
@tomquisel do you think this issue can be closed?
