### ISSUE TITLE
Add ticker functionality to Horizon

### ISSUE THREAD

**Issue by tomquisel** [stellar/go#855]
**Who:** for developers building exchanges or other SDEX tools
**What:** a ticker endpoint that returns recent volume and last price for all recently traded assets
**Why:** All SDEX frontends and many other tools end up re-implementing ticker functionality. Implement it once in Horizon to make it easier to build on the SDEX.

The endpoint should return enough information to render a display like [this](https://www.stellarx.com/markets)

**Comment by tomerweller** [comment]
There's a ticker script here: https://github.com/stellar/ticker-py which
feeds http://ticker.stellar.org/. It's not great and can use some love.

Tickers require some opinions about what assets should and shouldn't
appear. I'd be hesitant about introducing these types of opinions into
horizon.

**Comment by orbitlens** [comment]
@tomquisel It's on my list of the upcoming StellarExpert features. Once I finish [fiat-binding part](https://github.com/orbitlens/stellar-expert-explorer/issues/104) and some other stats improvements, I'll implement customizable tickers for all Stellar assets and XLM itself. Should be ready in 2-3 months. 

The tickers will be available free of charge and without any limitations (except of a moderate request rate limiting), with wildcard CORS headers included. Let's see what people say once it is ready. If they are ok with my API, then there is no need to implement the same functionality in Horizon.

**Comment by tomquisel** [comment]
Ok, cool. I'll close this out. @orbitlens I'm excited for your tickers! Will they support all markets? As in price of asset X in terms of asset Y for all X and Y that have non-empty order books.

**Comment by orbitlens** [comment]
@tomquisel 
Currently, I store information for X-XLM pairs only. Once the USD price mapping is ready, I will be able to introduce tickers for X-USD (GBP, EUR, JPY, etc) pairs. Adding aggregation capabilities for X-Y asset pairs will take some time, but I expect it to be ready in Q2 2019. 

Planned 24H price ticker structure:

```json
{
  "symbol": "ETH-GBSTRH4QOTWNSVA6E4HFERETX4ZLSR3CIUBLK7AXYII277PFJC4BBYOG_XLM",
  "priceChangePercent": "-2.85",
  "peviosClosePrice": "1538.4614265",
  "lastPrice": "1538.4614265",
  "openPrice": "1583.52866645",
  "highPrice": "1593.11773144",
  "lowPrice": "1412.7217514",
  "baseVolume": "2891.6262647108364143311200529473",
  "quoteVolume": "4448655.4681119",
  "openTime": 1550016000000,
  "closeTime": 1550102400000,
  "tradesCount": 4797
}
```

In Q3 2019 (maybe even earlier) I'm also planning to add "bidPrice" and "askPrice" values.
