### ISSUE TITLE
Unify/simplify Go SDK interface

### ISSUE THREAD

**Issue by ire-and-curses** [stellar/go#862]
Currently, a developer needs:

- `keypair` to manage keys
- `client` to query ledgers and submit transactions
- `build` to create transactions
- `protocols/horizon` to demarshal the Horizon responses

Compare this to the JS SDK, which has a single library and a uniform interface to all Stellar features. The JS SDK exposes `js-stellar-base`, so that lower level operations are made available through a single interface.

Is there any scope for presenting the Go SDK in a more uniform way? This issue is to discuss the shortcomings of the current developer experience, and agree on the work needed to improve it, then do it.

**Comment by bartekn** [comment]
I think it's because Go and JS project have different structure. Even if we move SDK packages to a separate repo I think we should still have `keypair`, `client`, `build`, ... packages inside. Should we move them to a separate repo? It requires a larger discussion.

**Comment by ire-and-curses** [comment]
That makes sense. What do you think about wrapping the lower level library functions and then exposing them from the `client` package? This is how e.g. the `matplotlib` library works in Python. This insulates the user from the implementation of the lower level libraries. So the goal would be that the user only imports packages under `client`.

**Comment by ire-and-curses** [comment]
There are places in our existing code where we already do something like this. Example: [horizon.base.Asset](https://godoc.org/github.com/stellar/go/protocols/horizon/base) is re-exported as [horizon.Asset](https://github.com/stellar/go/blob/master/protocols/horizon/main.go#L107). However:
1. Unfortunately the docs don't pick up the underlying definition, so you have to click through to see the fields.
2. I haven't tested what happens to the type in this situation (do we still see the underlying base type?).

For now I'm going to leave this alone. We can always improve this later after adding more functionality.
