### ISSUE TITLE
Find payment paths API endpoint returns apparently incorrect source amounts

### ISSUE THREAD

**Issue by Reidmcc** [stellar/go#864]
I'm using the `/paths?` Horizon endpoint to determine the exact amount of a source asset to set as the `maxAmount` for path payments. When I use the exact numeric string that Horizon returns as the `maxAmount` for the payment the payment usually (~95% of the time) returns the `[op_over_source_max] ` error. This error is to be expected sometimes, when the offers are no longer present, but this seems like way to often.

There is another step involved. The purpose the process is to do arbitrage using circular path payments. The `destination_amount` sent to `/paths?` is determined by querying Horizon for the relevant orderbook top bid against the circular begin/end asset. The find-payments query is for the last path asset before the end of the circle. The circular path should successfully end with the static amount against which the destination amount is calculated.

I'm omitting some of the error handling code and func definitions for brevity. This is all done with Kelp's `model.Number` type and its functions.

First get the SDEX orderbook in question:
````
func (w *DexWatcher) GetOrderBook(api *horizon.Client, pair TradingPair) (orderBook horizon.OrderBookSummary, e error) {
	baseAsset, quoteAsset := Pair2Assets(pair)
	b, e := api.LoadOrderBook(baseAsset, quoteAsset)
        return b, e
}
````
Then extract the top bid:
````
orderBook, e := w.GetOrderBook(w.API, pair)
if len(bids) == 0 {
	return model.NumberConstants.Zero, model.NumberConstants.Zero, nil
}
topBidPrice, e := model.NumberFromString(bids[0].Price, utils.SdexPrecision)
````
Use that bid to convert target amount into what will be the destination amount: 
````
amountConversion := model.NumberConstants.One.Divide(*bidPrice)
convertedAmount := amountConversion.Multiply(*p.staticAmount)
````
Then the actual API call:
````
// GetPaths gets and parses the find-path data for an asset from horizon
func (w *DexWatcher) GetPaths(endAsset horizon.Asset, convertedAmount *model.Number) (*FindPathResponse, error) {
	var s strings.Builder
	var paths FindPathResponse
	amountString := convertedAmount.AsString()

	s.WriteString(fmt.Sprintf("%s/paths?source_account=%s", w.API.URL, w.TradingAccount))
	s.WriteString(fmt.Sprintf("&destination_account=%s", w.TradingAccount))
	s.WriteString(fmt.Sprintf("&destination_asset_type=%s", endAsset.Type))
	s.WriteString(fmt.Sprintf("&destination_asset_code=%s", endAsset.Code))
	s.WriteString(fmt.Sprintf("&destination_asset_issuer=%s", endAsset.Issuer))
	s.WriteString(fmt.Sprintf("&destination_amount=%s", amountString))

	resp, e := w.API.HTTP.Get(s.String())

	defer resp.Body.Close()
	byteResp, e := ioutil.ReadAll(resp.Body)

	json.Unmarshal([]byte(byteResp), &paths)

	return &paths, nil
}
````
The json unmarshalls into:
````
type PathRecord struct {
	SourceAssetType        string      `json:"source_asset_type"`
	SourceAmount           string      `json:"source_amount"`
	DestinationAssetType   string      `json:"destination_asset_type"`
	DestinationAssetCode   string      `json:"destination_asset_code"`
	DestinationAssetIssuer string      `json:"destination_asset_issuer"`
	DestinationAmount      string      `json:"destination_amount"`
	Path                   []PathAsset `json:"path"`
}
````
The string that returns as `SourceAmount` is used as `maxAmount` for the path payment, while `staticAmount.AsString()` value of the end asset is used as the payment builder's `Amount`:
````

	pw := build.PayWith(convertHoldAsset, maxPayAmount)

	for i := 0; i < len(payPath.Path); i++ {
		dA.l.Infof("Adding to payment path: %s|%s", payPath.Path[i].AssetCode, payPath.Path[i].AssetIssuer)
		convertAsset := PathAsset2BuildAsset(payPath.Path[i])
		pw = pw.Through(convertAsset)
	}

	// if not calculating the full circle you must add the asset set as the "destination" as a path asset
	lastPathAsset := PathAsset{
		AssetType:   payPath.DestinationAssetType,
		AssetCode:   payPath.DestinationAssetCode,
		AssetIssuer: payPath.DestinationAssetIssuer,
	}

	lastConvertAsset := PathAsset2BuildAsset(lastPathAsset)

	pw = pw.Through(lastConvertAsset)
	dA.l.Infof("Adding to payment path: %s|%s", lastPathAsset.AssetCode, lastPathAsset.AssetIssuer)

	dA.l.Infof("Raw build.PayWith set to: %s", pw)

	if convertHoldAsset == build.NativeAsset() {

		payOp := build.Payment(
			build.Destination{AddressOrSeed: dA.TradingAccount},
			build.NativeAmount{Amount: receiveAmount},
			pw,
		)
		return &payOp, nil
	}
````

The one calculation on my program's end is the price conversion at the beginning, which uses the Kelp number model's `.Divide()` and `.Multiply()` functions, which should be Horizon compatible. The formula is right, which I tested by setting the `maxAmount` 1% high, which wouldn't have worked if the formula were upside down. The other possible influence is that many of these conversions are from XLM to BTC or ETH, so they involve very small numbers as the prices, or conversely very small amount values; this could exacerbate any rounding errors on either Horizon's end or in the Kelp number model calculations. My best idea as to what could cause this, if it is in fact a bug, is a conflict with Stellar core's offer matching rounding calculations in `/stellar-core/src/transactions/OfferExchange.cpp` since those calculations are altered for path payments.

Below is a sample log from my app that includes the paths and some of the raw operation strings:

````
2019/02/03 00:22:35 Best path amount output for USD|GBSTRUSD7IRX73RQZBL3RQUH6KS3O4NYFY3QCALDLZD77XMZOPWAVTUK was 7 for 6.984568
2019/02/03 00:22:35 With a ratio if 1.0022094
2019/02/03 00:22:35 
2019/02/03 00:22:35 ***** Minimum profit ratio was met, proceeding to payment! *****
2019/02/03 00:22:35 
2019/02/03 00:22:35 receiveAmount string set to: 7.0000000
2019/02/03 00:22:35 maxPayAmount string set to: 6.9845680
2019/02/03 00:22:35 Adding to payment path: ETH|GBSTRH4QOTWNSVA6E4HFERETX4ZLSR3CIUBLK7AXYII277PFJC4BBYOG
2019/02/03 00:22:35 Adding to payment path: LTC|GCSTRLTC73UVXIYPHYTTQUUSDTQU2KQW5VKCE4YCMEHWF44JKDMQAL23
2019/02/03 00:22:35 Adding to payment path: USD|GBSTRUSD7IRX73RQZBL3RQUH6KS3O4NYFY3QCALDLZD77XMZOPWAVTUK
2019/02/03 00:22:35 Raw build.PayWith set to: {{  %!s(bool=true)} 6.9845680 [{ETH GBSTRH4QOTWNSVA6E4HFERETX4ZLSR3CIUBLK7AXYII277PFJC4BBYOG %!s(bool=false)} {LTC GCSTRLTC73UVXIYPHYTTQUUSDTQU2KQW5VKCE4YCMEHWF44JKDMQAL23 %!s(bool=false)} {USD GBSTRUSD7IRX73RQZBL3RQUH6KS3O4NYFY3QCALDLZD77XMZOPWAVTUK %!s(bool=false)}]}
2019/02/03 00:22:35 reloading sequence number
2019/02/03 00:22:35 Pre-XDR raw was: &{%!s(*xdr.Transaction=&{{0 0xc0004e0b20} 100 95259432572683232 <nil> {0 <nil> <nil> <nil> <nil>} [{<nil> {2 <nil> <nil> 0xc00036c620 <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil>}}] {0}}) Public Global Stellar Network ; September 2015 %!s(uint64=100)}
2019/02/03 00:22:35 tx XDR: AAAAANMPjNEIHpYFg2jygIrckXPemsQ+CPMuKYW55pg0liQlAAAAZAFSbfMAAAPgAAAAAAAAAAAAAAABAAAAAAAAAAIAAAAAAAAAAAQpwrAAAAAA0w+M0QgelgWDaPKAityRc96axD4I8y4phbnmmDSWJCUAAAAAAAAAAAQsHYAAAAADAAAAAUVUSAAAAAAAZTifkHTs2VQeJw5SRJO/MrlHYkUCtXwXwhGv/eVIuBAAAAABTFRDAAAAAAClOK5i/ulbow8+JzhSkhzhTSoW7VQicwJhD2LziVDZAAAAAAFVU0QAAAAAAGU40kP6I3/uMMhXuMKH8qW3cbguNwEBY15H/92Zc+wKAAAAAAAAAAE0liQlAAAAQHxs5KvwQMKeBjf4tE5rfiNEmtDgIKOrUiD/PriDPBFlcUxxsqtlmD3DOUowtJRDU4zf6m46ihk2YfoeROX+Kwg=
2019/02/03 00:22:35 submitting tx XDR to network (async)
2019/02/03 00:22:44 (async) error: result code details: tx code =%!(EXTRA string=tx_failed, string=, opcodes =, []string=[op_over_source_max])
````

**Comment by Reidmcc** [comment]
My app's involved code is in:

https://github.com/Reidmcc/rockfish/blob/master/modules/dexAgent.go
https://github.com/Reidmcc/rockfish/blob/master/modules/pathRequester.go
https://github.com/Reidmcc/rockfish/blob/master/modules/horizonResponses.go
https://github.com/Reidmcc/rockfish/blob/master/modules/dexWatcher.go

**Comment by bartekn** [comment]
It is possible that there's some obscure bug but are you sure that:
* simply, there isn't somebody else who is able to consume these offers first?
* the top offer you are trying to consume is actually with a small amount so you consume it fully?

Can you check these 2 things first? Some markets are pretty active so it's possible that the state changes before your transaction is propagated in the network.

**Comment by Reidmcc** [comment]
@bartekn 

_There isn't somebody else who is able to consume these offers first?_
 
I'm seeing occasions in my logs where an attempt returns `[op_over_source_max]` and the next ratio check (ten seconds later) returns the same qualifying ratio and another attempt is made, which again returns `[op_over_source_max]`.

I've been running this app for over a week now and the behavior is consistent. Combined with the fact that the markets on which I'm trading typically have trade frequencies in the minutes, or tens of minutes, this seems to suggest something else is going on. For example, [Stronghold BTC / XLM](https://stellarport.io/exchange/alphanum4/BTC/GBSTRH4QOTWNSVA6E4HFERETX4ZLSR3CIUBLK7AXYII277PFJC4BBYOG/native/XLM/Stellar?tab=Markets) is one of the higher frequency markets I use. 

_the top offer you are trying to consume is actually with a small amount so you consume it fully?_

This one seemed like a likely cause, so on my most recent test branch I'm setting the attempted amount  to `amountThatShouldWork.Scale(0.98)` to make sure I'm not just barely overshooting the offer, and setting `maxPayAmount` as equal to the receive amount instead of the calculated ratio. So if the amount that should work were 7.0, the setting I'd use now would be:
````
receiveAmount string set to: 6.8600000
maxPayAmount string set to: 6.8600000
````
This has made no apparent difference. 

The additional thing I can think of is I could have my logger output every involved value for each cycle and manually check that they aren't changing. If you have additional ideas for diagnosis I'm happy to try them.

**Comment by Reidmcc** [comment]
I'm going ahead and closing this. If I do the huge amount of digging to confirm this isn't just others getting the orders first I can open a new issue. Given the ~5 second turnaround time for the `/paths?` endpoint it might not be feasible.
