### ISSUE TITLE
Consolidate horizon actions package

### ISSUE THREAD

**Issue by howardtw** [stellar/go#868]
Files prefixed with `actions_` in `horizon/internal` directory can be moved to the `actions` package and renamed to the names without the prefix. For example, `actions_account.go` can be `account.go` in the `actions` package. All the associated action structs can also be renamed.

We should also take `App` out from the action if there's a circular import. Please see this one https://github.com/stellar/go/issues/869

**Comment by bartekn** [comment]
Connected: https://github.com/stellar/go/issues/869#issuecomment-461804465.
