### ISSUE TITLE
Reorganize horizon directory

### ISSUE THREAD

**Issue by howardtw** [stellar/go#871]
The current files in `services/horizon/` directory (`db.go`, `serve.go`, `version.go`, and `main.go`) can all be moved to a new directory `horizon/cmd`, where we use to spin up the horizon process.

**Comment by tomerweller** [comment]
The majority of horizon is under an [`internal`](https://golang.org/doc/go1.4#internalpackages) package to avoid it being imported by other go applications. This is required because other parts of this repo (like common resources) should be importable.

**Comment by howardtw** [comment]
Cool TIL. I'm going to modify this issue and just work on the `cmd` part, which should be simple.

**Comment by howardtw** [comment]
This is a good reference: https://www.ardanlabs.com/blog/2017/02/package-oriented-design.html
