### ISSUE TITLE
/order_book/trades endpoint not working

### ISSUE THREAD

**Issue by swetakedia** [stellar/go#874]
I used below endpoint earlier 

"https://horizon-testnet.stellar.org/order_book/trades?selling_asset_type=native&buying_asset_type=credit_alphanum4&buying_asset_code=FOO&buying_asset_issuer=GBAUUA74H4XOQYRSOW2RZUA4QL5PB37U3JS5NE3RTB2ELJVMIF5RLMAG&limit=20&order=desc"

However the same is not working now. How can I check if this is deprecated?

**Comment by tomquisel** [comment]
This should do the trick: https://horizon-testnet.stellar.org/trades?selling_asset_type=native&buying_asset_type=credit_alphanum4&buying_asset_code=FOO&buying_asset_issuer=GBAUUA74H4XOQYRSOW2RZUA4QL5PB37U3JS5NE3RTB2ELJVMIF5RLMAG&limit=20&order=desc

The old endpoint was deprecated in [early 2017](https://github.com/stellar/go/blob/master/services/horizon/CHANGELOG.md#v0120---2017-03-08).
