### ISSUE TITLE
Add ledger fullness information to /operation_fee_stats

### ISSUE THREAD

**Issue by tomquisel** [stellar/go#891]
Who: for wallets & exchanges that want user transactions to succeed even during network congestion
What: report information on how full recent ledgers were
Why: This allows wallets to decide if they need to increase the fee for transactions they submit to ensure the transactions are included in the next ledger

I'd recommend we add these fields to the response:
`"last_ledger_fraction_full": 0.6`
`"last_10_ledgers_fraction_full": 0.2`

@MonsieurNicolas please suggest any tweaks.

**Comment by bartekn** [comment]
Yeah, I think we should do it. I'm afraid that people will focus too much on percentiles and other stats and will still use super high fees when ledgers aren't full (in such situation base fee is fine).

**Comment by bartekn** [comment]
PTAL https://github.com/stellar/go/pull/922

**Comment by bartekn** [comment]
Closed in #922.
