### ISSUE TITLE
Extra `for` loop in clients/horizon/client.go causes infinite querying of horizon server

### ISSUE THREAD

**Issue by Reidmcc** [stellar/go#895]
There is an extra `for` loop in the `stream` function in `clients/horizon/client.go`,  around the code that sends the request to the Horizon server. If you use call the function as it is now it goes into an infinite loop, continuously re-sending the request. 

#### To reproduce:

1. ~~Set your handler to print so you can see what happens.~~ I should have said to add a print to the `stream` function around where it submits the `GET`, for example printing the url it's about to send, which is how I determined where it was stuck. It never gets to the actual handler.
2. Call one of the streaming functions; I first encountered this while using a custom orderbook streaming function, and then replicated it with `StreamLedgers`.

I'll submit a pull request (I've signed the Contributor License Agreement).

**Comment by ire-and-curses** [comment]
Thanks for raising this. We're working on some changes to the Go SDK at the moment, so we can take a look at this when we evaluate the current state of streaming soon (@poliha).

**Comment by Reidmcc** [comment]
@bartekn you're right about https://github.com/stellar/go/pull/896; it won't ever restart a dropped stream. I wrap it in another goroutine to do that.

If you want to restart dropped streams, I have two ideas

- use a ticker inside `stream`. I was talking to the SatoshiPay folks about dropped streams and they mentioned Horizon by default drops streams after 55 seconds. To deal with that you could do (pseudocode):
````
func stream { 
	finishTheURL	
	restartTicker := time.NewTicker(55 * time.Second)
	
	for {
		submitGET
		makeReader
		for Events{		
			[do the things]	
		}		
	<- restartTicker.C
	}
````

- to more robustly handle unscheduled drops you could use channels connected to the funcs that call `stream` e.g.
````
func StreamLedgers([current inputs], streamVerify chan bool} {
	buildTheURL
	dropTicker := time.NewTicker(([expected return time] + [allowance for delay) * time.Second)
	return stream([current inputs], streamVerify) {
		[the stream things]
	}
	for {
		select {			
		case <-streamVerify:
			// continue
		case <-dropTicker.C:
			return stream([current inputs], streamVerify) {
			[the stream things]
			}
		}		
	}	
}
````
and 
````
func stream ([current inputs, streamVerify chan<- bool]) {
	finishTheURL	

	submitGET
	makeReader
	
	for {
		for Events{		
			[do the things]	
			[exit loop normally]
		}
		if [data handled successfully in Events] {
			streamVerify<- true
			continue
		}
		return nil
	}
}
````
If either of those sounds reasonable I can code it up and submit a new PR (I don't want to come off like I'm spamming PRs).

**Comment by ire-and-curses** [comment]
@Reidmcc: We've released a new client, `horizonclient`, which implements streaming. Would you like to try it and see if this problem is resolved in the new implementation?
