### ISSUE TITLE
stellar-core Database Schema Update

### ISSUE THREAD

**Issue by jonjove** [stellar/go#900]
https://github.com/stellar/stellar-core/pull/1906 was merged this morning. It includes schema changes for the stellar-core database `accounts` and `accountdata` tables. Updated schema documentation can be found in https://github.com/stellar/stellar-core/pull/1932, which should be merged shortly.

As of this change, the database schema version is 9. If you need to check the stellar-core database schema version in order to maintain compatibility with both schemas, this information can be retrieved with the query `SELECT state FROM storestate WHERE statename = 'databaseschema';` More information about the `storestate` table can be found in https://github.com/stellar/stellar-core/blob/master/src/main/PersistentState.cpp

**Comment by bartekn** [comment]
Closed in #916.
