### ISSUE TITLE
Design larger analytical system

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/go#91]
for our internal dashboards

**Comment by lisaclaire** [comment]
Need this to capture year end metrics, and general reporting. Requesting all data in current dashboard for >30 day period (transactions, offers, signers, accounts, etc). Access to total history would be ideal.

Other useful filters:
- filters for 'daily sum' view
     - by operation type 
     - by asset
     - by account

**Comment by howardtw** [comment]
Closing since we are now using Grafana, Kibaba, and Cloudwatch
