### ISSUE TITLE
Horizon should query account data atomically along with ledger header

### ISSUE THREAD

**Issue by nikhilsaraf** [stellar/go#941]
Horizon should be able to atomically fetch ledger numbers along with account balances.
This can be included in the `/accounts` endpoint so it is atomic. This will include ledger number and/or ledger hash in the result which will use a SQL join on the backend. Since this can be expensive, the horizon server would need a special env var or command line flag to use this mode.

- Knowing the freshness of ledger data is very important for consistency. It's no surprise that a smart consumer will want it and we should support it.
- Current horizon account details endpoint is very problematic. It queries core's db in 4 return trips. Nothing promises consistency across these trips. So for example, you can get trustlines from ledger 9 and data entries from ledger 10. It also queries data from horizon but that’s unused by that endpoint.
- The low hanging fruit is fetching all this information + last ledger number in a single statement. However, that's not enough as consistency is still not promised.
- The only way to get consistency is by transaction isolation.
- PG's "Repeatable Read" isolation level should suffice for this.

Discussion details below:

core already does "SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL SERIALIZABLE" when we open a session with postgres.

we can't have Horizon perform those reads with serializable transactions, that will for sure starve core to death
we need those transactions to be "read only" as well in order to avoid blocking core, not sure how this gets done

"SET TRANSACTION READ ONLY"
also pg is MVCC, reads never block writes (and writes never block reads). they just fork the universe / bulk up the tuple space a bit until vacuum time
you might, however, get your transaction aborted due to a serialization failure. so you have to commit your read txn, and not-return data to a user if your read transaction fails on attempt to commit.
the commit point (I know, you're not writing, but it checks at the commit point) is where the db tells you if you violated serializability.
https://www.postgresql.org/docs/11/transaction-iso.html#XACT-SERIALIZABLE
it is super subtle and easy to get wrong and kill yourself. I don't want to pretend this is a no-risk or low-risk thing to play with. just that the machinery exists to use correctly (or incorrectly) if we try hard enough

This single account details sql statement should go upstream. The strong consistency via transaction shenanigans is the part that should be behind a flag for now. Even without a transaction it's order of magnitudes better than what we have now
you probably want something similar to this: https://github.com/stellar/go/issues/432#issuecomment-388517678
only yours will be simpler because you're only fetching a single account but you'll also need to bring in the ledger seq numebr

you might want to just use subqueries for select statements as CTEs have optimization fence

can you elaborate? I was going to use a join query inside the read serialized transaction

Yeah you’ll need to use a join. But I mean instead of doing `with ((first query) as t1, (second query) as t2...) select ... from t1 inner join t2 on...`, you might wanna do `select ... from (first query) as t1 inner join (second query) as t2 on...` directly

ok yeah, thanks for the tip, will do it directly

sounds good to me if behind a feature flag. for transaction isolation level, I think you should do something like `SET TRANSACTION ISOLATION LEVEL REPEATABLE READ, READ ONLY`, that's what I found to be the optimal option when I was improving path finding code recently (ex. previous code did not always have a stable view of offers, some from ledger X, some from ledger X+1). from the docs:
> The Repeatable Read isolation level only sees data committed before the transaction began; it never sees either uncommitted data or changes committed during transaction execution by concurrent transactions. This is a stronger guarantee than is required by the SQL standard for this isolation level, and prevents all of the phenomena described in Table 13-1 [dirty read, nonrepeatable read, phantom read].
> Applications using this level must be prepared to retry transactions due to serialization failures. (...) Note that only updating transactions might need to be retried; *read-only* transactions will never have serialization conflicts.
any reason you think this should be `SERIALIZABLE`?

honestly I can't tell if there's any difference in semantics between readonly+repeatable-read and readonly+serializable on pg.
we're doing serializable in core at least in part because most of our txns are not strictly readonly.

**Comment by nikhilsaraf** [comment]
Noting this here from our discussion, for posterity's sake.

**Comment by bartekn** [comment]
I believe this is fixed in the new ingestion system (since Horizon 1.0.0). All account properties (account, trust lines, signers, etc.) are now queries in a `REPEATABLE READ` transaction so are consistent. The ledger sequence at the DB transaction time can be found in `Latest-Ledger` header.
