### ISSUE TITLE
exp/clients/horizon: tests and documentation

### ISSUE THREAD

**Issue by poliha** [stellar/go#947]
Need to add complete tests, examples and docs to the endpoints created in #932 and #946

**Comment by sgehrman** [comment]
I was going to work on this.  Is that cool?  I found one bug already.  

// effect_request.go
// you have
		if resp.StatusCode >= 200 && resp.StatusCode < 300 {

// should be:
		if !(resp.StatusCode >= 200 && resp.StatusCode < 300) {

Let me know if you or someone is already actively working on this, otherwise I'll submit some PRs.

Thanks

**Comment by poliha** [comment]
Good catch.. will update in my next PR. This is an experimental package, and things might still change quickly. You might want to wait before diving into some PRs as there might already be plans to implement what you decide to work on
