### ISSUE TITLE
What should SDKs or Horizon validate?

### ISSUE THREAD

**Issue by ire-and-curses** [stellar/go#951]
It's easy to validate things like keys. But there's a long tail of validation. How far should we go with client-side validation? Let's discuss what to validate, and whether it should be in the SDKs, in Horizon, or left up to the user.

The goal is to have a clear list of validation that each SDK should perform, and a second list of validation that Horizon should perform. Then we can raise issues to implement those.

**Comment by ire-and-curses** [comment]
We discussed this in person. To summarise:

* Builder code should do minimal validation as necessary to construct well-formed objects (e.g. identify required fields)
* Builder code should avoid field introspection, e.g. a bad sequence number will be rejected by Horizon, no need to duplicate checks
* Builder code should not use client or server for anything - these are stand-alone objects
* Horizon should do validation so that validation is centralised and not duplicated/missing within SDKs
* Client code should not validate - Horizon will return 400 with appropriate information if needed

Does that sound correct to everyone? @bartekn @poliha @tomquisel

**Comment by poliha** [comment]
Yes looks good
