### ISSUE TITLE
Horizon server returns incorrect payment paths 

### ISSUE THREAD

**Issue by IlyaShkapo** [stellar/go#964]
Hello Stellar Team, 

We have faced an issue when path search returns only paths with offers, but doesn't check if this offer belongs to source account. In this case payment cannot be completed due to cross self offer.

# Version found
  10.2.0

## Condition:
Find payment paths. Destination asset is not “native”. 
The only offer for selling this custom asset and buying native is created by source account.
No valid offers for selling native and buying this custom asset exists.

## Actual result
Path search returns payment path with native asset as source.

## Expected result
Paths without valid offers shouldn't be returned.

Please let me know if this is expected behaviour.

**Comment by bartekn** [comment]
We believe this has been fixed in `0.20.0` release (and `0.20.1` that contains some performance fixes). Horizon `0.20.1rc1` is currently deployed to https://horizon.stellar.org. Please check it out. It is using the new in-memory order book graph.
