### ISSUE TITLE
Horizon 0.17.0 get failed: sql: Scan error on column index 0

### ISSUE THREAD

**Issue by cod** [stellar/go#967]
Have private network with core and horizon.
Horizon builded from branch release-horizon-v0.17.0.
Got errors on any requests:

`ERRO[2019-02-28T22:10:17.253Z] get failed: sql: Scan error on column index 0: unsupported Scan, storing driver.Value type <nil> into type *string  pid=15272 req="project/yVM1r0Tga4-000001" stack="[main.go:43 session.go:106 session.go:83 signer.go:23 actions_account.go:64 actions_account.go:37 base.go:186 actions_account.go:35 base.go:57 main_generated.go:10 init_web.go:100 server.go:1947 mux.go:418 mux.go:354 server.go:1947 mux.go:69 mux.go:295 server.go:1947 mux.go:418 mux.go:354 server.go:1947 mux.go:69 mux.go:295 server.go:1947 mux.go:418 mux.go:354 server.go:1947 http.go:73 server.go:1947 cors.go:190 server.go:1947 compress.go:66]"
`
accounts table in stellar-core database has only 1 record of root account with NULL signers field.

Stellar-core built from master branch.
All DBs created from scratch.

`./stellar-core version
v10.2.0-61-g5f0517e-dirty`

**Comment by edunuzzi** [comment]
Having a similar issue here on v0.17.2.

When i try to fetch a existing account on `/accounts/{account}`:

`msg="get failed: sql: Scan error on column index 0, name \"signers\": unsupported Scan, storing driver.Value type <nil> into type *string" pid=1 req=1ccb10424691/o030iNMfp4-000004 stack="[main.go:43 session.go:106 session.go:83 signer.go:23 actions_account.go:64 actions_account.go:37 base.go:186 actions_account.go:35 base.go:57 main_generated.go:10 init_web.go:100 server.go:1964 mux.go:418 mux.go:354 server.go:1964 mux.go:69 mux.go:295 server.go:1964 mux.go:418 mux.go:354 server.go:1964 mux.go:69 mux.go:295 server.go:1964 mux.go:418 mux.go:354 server.go:1964 http.go:73 server.go:1964 cors.go:190 server.go:1964 compress.go:66]"`

**Comment by bartekn** [comment]
I think you are using an unstable stellar-core release, the schema change will be part of 10.3.0. Downgrading to 10.2.0 should solve this. We'll have a fix in Horizon early next week.

**Comment by cod** [comment]
Thank you. Will try.

**Comment by cod** [comment]
It's working well with tags/v10.2.0. Closing.
