### ISSUE TITLE
Transaction streaming endpoint sends error events with undefined messages

### ISSUE THREAD

**Issue by tomquisel** [stellar/go#970]
Here's a report from kungfooio on Keybase:
>`kungfoo.bc.server.transactions().cursor('now').stream({onmessage: async function(transaction){},
  onerror:function(err){console.log(err)}});}`
>continually reports this: `Event { type: 'error', message: undefined }`

Others are seeing this as well when listening on a Horizon stream. We should either:
* not send out the `undefined` errors, since the stream appears to continue working
* properly report the error message

kungfooio reports it happens with the `/payments` endpoint as well, so it's probably present for all of them.

**Comment by tomquisel** [comment]
@howardtw this would be a good issue to knock out!

**Comment by bartekn** [comment]
It looks like this is expected behaviour for [Server-Sent Events](https://www.w3.org/TR/2009/WD-eventsource-20090421/):
> When a user agent is to reset the connection, the user agent must set the readyState attribute to CONNECTING, queue a task to fire a simple event named error at the EventSource object, and then fetch the event source resource again after a delay equal to the reconnection time of the event source. Only if the user agent resets the connection does the connection get opened anew!

Resetting a connection means reconnecting. No idea why this is part of the protocol but it looks like users need to ignore empty error events.

**Comment by tomquisel** [comment]
@bartekn I think you're right. From test requests (`curl -N --http2 -H "Accept:text/event-stream" 'https://horizon.stellar.org/accounts/GB3P6W2MZQWW55PCWILIY5XYWT2Z4Y7URGFCMVQB7DH2CO3MQES44RUV/transactions?cursor=97325543770394624' for example`) I don't see any evidence that Horizon is generating its own empty error responses.

It sounds like the events are likely generated when a connection is reset (and are not coming from Horizon), so they should be ignored.

**Comment by MikeFair** [comment]
Since these empty error events are to be ignored, can the SDK simply not deliver them in the first place?

**Comment by tomquisel** [comment]
@MikeFair I'm leaning away from that idea. It's certainly more useable for the default case to filter the empty error events, but it deviates from the EventSource specification. Since it's a deviation, I lean towards not interfering with the default behavior. A developer may expect our system to deliver those empty errors, and may be depending on them.
