### ISSUE TITLE
Better values for `type` field in errors, and consistent documentation around errors

### ISSUE THREAD

**Issue by nikhilsaraf** [stellar/go#975]
There are some minor inconsistencies in the docs around the structure of the `type` field in errors and various examples:
• [https://www.stellar.org/developers/horizon/reference/errors/transaction-failed.html#example](https://www.stellar.org/developers/horizon/reference/errors/transaction-failed.html#example)
• [https://www.stellar.org/developers/horizon/reference/errors/rate-limit-exceeded.html](https://www.stellar.org/developers/horizon/reference/errors/rate-limit-exceeded.html)
Some without examples:
• [https://www.stellar.org/developers/horizon/reference/errors/timeout.html](https://www.stellar.org/developers/horizon/reference/errors/timeout.html)

The code looks like all `type`s should be of structure `https://stellar.org/horizon-errors/*`:  [stellar/go/support/render/problem/main.go](https://github.com/stellar/go/blob/749e51c965fdc59b5180c2a1509eb0bc1d372012/support/render/problem/main.go#L48)

The `horizon-errors` format redirects for certain errors like [https://stellar.org/horizon-errors/transaction_failed](https://stellar.org/horizon-errors/transaction_failed) but not others like [https://stellar.org/horizon-errors/timeout](https://stellar.org/horizon-errors/timeout)

Since `type` is the field that identifies the actual error, I wanted to ensure that I’m going to receive all my errors with that specific structure (e.g. `https://stellar.org/horizon-errors/timeout`)

Also it would be a big plus if the docs were consistent around that and had examples for the different types

**Comment by theaeolianmachine** [comment]
Next steps:
* Add examples and the `type` field to each of the errors and their respective responses.
* Fix the redirects for any errors that aren't currently being redirected, or file an issue to get rid of the redirect and hardcode the URLs in Horizon (most likely the prior).
