### ISSUE TITLE
Use identical XDR files in all services

### ISSUE THREAD

**Issue by mvaneijk** [stellar/go#98]
This modification https://github.com/stellar/stellar-core/commit/e3e334d4f9bae35c9fe944a7e097080295f7e797 has not been processed in this stellar/go repository. I guess it has no technical impact, but the protocol should be the same in all services.

**Comment by bartekn** [comment]
Thanks, this will be updated. I think we should really consider https://github.com/stellar/stellar-core/issues/984 otherwise situations like this will be happening again and again.

**Comment by howardtw** [comment]
Closing because we have [this issue](https://github.com/stellar/stellar-core/issues/984)
